### ISSUE TITLE
Clarify language settings

### ISSUE THREAD

**Issue by greatislander** [pressbooks/pressbooks#100]
Right now language settings for books and users are sometimes counterintuitive. To be addressed.

**Comment by greatislander** [comment]
See: https://groups.google.com/d/msg/pressbooks/l_rlsyNG3x4/z1VB6Bq4JxcJ

**Comment by greatislander** [comment]
This one, @hughmcguire

**Comment by hughmcguire** [comment]
review how this should work.

**Comment by hughmcguire** [comment]
How this should work (note: priority on getting German & German hyphenation working!)

# 1. Network >> Settings >> Default Language = (LanguageA).

Result: 
— default new user profile >> language = (languageA)
— default new book >> book info >> language = (default language)
— default network web “admin” (login buttons etc) = (default language)

# 2. Book >> Book Info >> Language = (languageA)

Result:
— “public” web “admin” (login, read buttons etc) = (languageA)
— export metadata tagged: language = (languageA)
— translation routine translates: Contents & Chapter (in CSS) to language A
— PDF/Prince hyphenation routine points to correct hyphen dictionary. NOTE: Prince comes installed with Hyphen dictionaries, including German — to point to in PDF exports.

See also:
http://www.princexml.com/doc/7.1/properties/prince-hyphenate-patterns/
http://www.princexml.com/forum/topic/1474/prince-and-hyphenation

# 3. Profile Language >> (languageA)
Result:
- internal admin dashboard language = (languageA).
- book & external web stays the default language.

**Comment by greatislander** [comment]
@hughmcguire: Some progress, which you can test in https://github.com/pressbooks/pressbooks/tree/language-options:

# 1. Network >> Settings >> Default Language = (LanguageA).

Result:

- [x] default new user profile >> language = (languageA)
- [x] default new book >> book info >> language = (default language)
- [x] default network web “admin” (login buttons etc) = (default language)

# 2. Book >> Book Info >> Language = (languageA)

Result:
- [x] “public” web “admin” (login, read buttons etc) = (languageA)
- [x] export metadata tagged: language = (languageA)
- [x] translation routine translates: Contents & Chapter (in CSS) to language A
- [ ] PDF/Prince hyphenation routine points to correct hyphen dictionary. NOTE: Prince comes installed with Hyphen dictionaries, including German — to point to in PDF exports.

See also:
http://www.princexml.com/doc/7.1/properties/prince-hyphenate-patterns/
http://www.princexml.com/forum/topic/1474/prince-and-hyphenation

# 3. Profile Language >> (languageA)

Result:

- [x] internal admin dashboard language = (languageA).
- [x] book & external web stays the default language.

The hyphenation dictionary issue is a bit weird. See here: https://github.com/pressbooks/pressbooks/blob/f3ef656c0b4e43bc110c609e09643db5df8be403/functions.php#L174

This function is called when hyphenation is enabled for PDF (Prince) exports. It tells Prince to use the hyphenation dictionaries in `/symbionts/dictionaries/` rather than Prince's own dictionaries—as far as I can tell. This means we only have access to the English dictionary in `/symbionts/dictionaries/`, even though Prince includes built-in dictionaries for Danish, German, English, French, Finnish, Icelandic, Italian, Lithuanian, Polish, Portuguese, Russian, Slovenian and Swedish… Not sure why this was set up this way but we can test without the custom dictionary location and see if the others work out of the box. (I think German does in my initial experiments.)

**Comment by hughmcguire** [comment]
@greatislander re: hyphen dics, could we ...:
- verofy the language (defined by book info >> language)
- look in ~/symbionts/ ...for the correct language dic
- if we find that, use that
- if we don't find the correct dictionary in symbionts ... then revert to Prince default

? 

that way ... we can add an improved dic if we have one, but default will fall-back on whatever exists in Prince?

**Comment by greatislander** [comment]
@hughmcguire German hyphenation has been working for a while—if there is no hyphen dictionary in `/symbionts/dictionaries/` Prince falls back on its built-in dictionaries.

You can test this now as follows:

`git checkout -b language-options origin/language-options`

**Comment by hughmcguire** [comment]
hi ned, with `git branch language options` ... I cannot create new books on my local install (tried on two separate installs).

working fine on `dev`  and `new-book-theme` ...

**Comment by hughmcguire** [comment]
since I can't test properly at at the moment, I'm going to write out a testing protocol: 

# network language = languageA

1. user NOT logged in ...

a) visits pressbooksnetwork.com
- signin button should be in LanguageA
- "Copyright © 2015 [network name] is powered by Pressbooks.com" should be in LanguageA
(currently not)

b) ~/wp-login.php
- should be in LanguageA
(currently not) 

c) visits ~/wp-login.php?action=lostpassword ...
should be in LanguageA
(currently not)

2. user NOT logged in 

d) visits ~/book1/ AND book *IS NOT* public, book info language = LanguageA
"Access Denied" message should be in LanguageA 
(50% of it is)

e) visits  ~/book1/ AND book *IS* public, book info >> language = LanguageA
the following should be in LanguageA 
- "read" 
- "buy" 
- "login" << *not currently in LanguageA*
- "book description" 
- "table of contents" 
- footer content 

f) visits ~/book1/chapter/chaptername/ 
- buy
- home
- table of contents 
- footer 
should all be in LanguageA
(yes!)

NOTE: book theme is getting revamped, so there might be some changes there to content/location etc.

**Comment by hughmcguire** [comment]
# network language = languageA ...

1. user creates new book 
a) default book info >> language = LanguageA
(cannot currently test)
