### ISSUE TITLE
Review admin interface

### ISSUE THREAD

**Issue by greatislander** [pressbooks/pressbooks#101]
Make sure the sidebar hooks still make sense in 4.1, other tweaks TBD.

**Comment by greatislander** [comment]
Beginning to work on this. @hughmcguire, how do you like this for the revised sidebar?

I am moving utilities (as opposed to settings) under a tools menu positioned like the standard WordPress one:

![tools](https://cloud.githubusercontent.com/assets/605361/9390078/4145711c-4745-11e5-92dc-ef05faff36df.png)

And I've moved the Sell page (still named Sell for now) under settings.

![settings](https://cloud.githubusercontent.com/assets/605361/9390079/439721cc-4745-11e5-9e30-a7db1e800793.png)

As you'll note, I've changed some of the icons—rather than using Font Awesome (which is an extra library to load) I'm using WordPress' built in icon font, Dashicons, which has become fairly comprehensive over the years.

Extras is currently located right above tools and will handle extras management (à la Plugins). Let me know what you think so far.

**Comment by hughmcguire** [comment]
Hi Ned, 

We can discuss where to put this button later, but in the mean time can you pls: 
a) change the "SELL" button to "PUBLISH"

b) replace the copy on that page with the file I will send you in Slack.

**Comment by hughmcguire** [comment]
Other than that -- I guess I am OK with this new setup. Not crazy about expanding the number of buttons in the sidebar ... but it all makes sense.

**Comment by greatislander** [comment]
@hughmcguire Okay. And okay to move Publish under the settings menu?

**Comment by hughmcguire** [comment]
@greatislander per slack convo, pls leave PUBLISH as top-level menu item (and, if you could implement that change asap, would be appreciated.)

**Comment by hughmcguire** [comment]
@greatislander looks fine to me... one thing, while we are here ... 

SETTINGS >> ADVANCED ...isn;t very useful, contains two totally unrelated features: 
- error logs
- chapter taxonomy

So, let's remove "settings >> advanced" and instead have:  
SETTINGS >> ERROR LOGS

and ... chapter taxonomy ... ug. I guess "chapter taxonomy" setting should go under:
APPEARANCE >> THEME OPTIONS >> GLOBAL OPTIONS.

**Comment by greatislander** [comment]
I would suggest rather than Settings >> Error Logs we call it "Export Settings"—that's a logical place and then we can use it for future export-related settings we may want to add rather than being stuck with a settings page that is only useful for one relatively wonky thing. I agree that Chapter Types should be under Theme Options >> Global Options; it's not unlike the multilevel TOC as a feature. If you are okay with this I will go ahead, make those changes and make live.

**Comment by hughmcguire** [comment]
yes that works.
