### ISSUE TITLE
Theme selection page

### ISSUE THREAD

**Issue by greatislander** [pressbooks/pressbooks#102]
It's become somewhat unwieldy given the number of themes now available. Examine strategies to make theme selection more user-friendly, as seen on WordPress.com.

**Comment by hughmcguire** [comment]
in particular would like users to be able to filter by tags and/or categories so they can see, eg, themes suited for Romance, vs. Mystery, vs. Thriller, vs. Memoir.

**Comment by hughmcguire** [comment]
I'd like to bump up this feature ... to discuss.

**Comment by greatislander** [comment]
Closing as low priority. Can re-open when spec'ed if this is still desired.
