### ISSUE TITLE
Fatal Error 

### ISSUE THREAD

**Issue by jdrodriguez** [pressbooks/pressbooks#1021]
### Prerequisites

_Check the boxes below by changing them from `[ ]` to `[x]`._

* [yes ] Can you reproduce the behavior you wish to address with [all other plugins deactivated](http://codex.wordpress.org/Multisite_Network_Administration#Plugins)?
* [yes ] Are you running the [latest version of Pressbooks](http://github.com/pressbooks/pressbooks/releases/latest/) and the [latest version of WordPress](http://codex.wordpress.org/Upgrading_WordPress)?
* [no ] Are you experiencing this issue with one of our built-in root or book themes?
* [yes ] Did you [perform a cursory search](https://github.com/issues?q=+is%3Aissue+repo%3Apressbooks%2Fpressbooks) to see if your bug or enhancement is already listed?

### Description

[I just updated to the latest version of the plugin and now I get this error:

Fatal error: Uncaught Error: Call to undefined function HM\Autoloader\register_class_path() in /home4/jdrodri/public_html/sdjpublicaciones.com/wp-content/plugins/pressbooks/compatibility.php:75 Stack trace: #0 /home4/jdrodri/public_html/sdjpublicaciones.com/wp-content/plugins/pressbooks/compatibility.php(63): pb_init_autoloader() #1 /home4/jdrodri/public_html/sdjpublicaciones.com/wp-content/plugins/pressbooks/pressbooks.php(120): pb_meets_minimum_requirements() #2 /home4/jdrodri/public_html/sdjpublicaciones.com/wp-settings.php(268): include_once('/home4/jdrodri/...') #3 /home4/jdrodri/public_html/sdjpublicaciones.com/wp-config.php(107): require_once('/home4/jdrodri/...') #4 /home4/jdrodri/public_html/sdjpublicaciones.com/wp-load.php(37): require_once('/home4/jdrodri/...') #5 /home4/jdrodri/public_html/sdjpublicaciones.com/wp-admin/admin.php(31): require_once('/home4/jdrodri/...') #6 /home4/jdrodri/public_html/sdjpublicaciones.com/wp-admin/network/admin.php(13): require_once('/home4/jdrodri/...') #7 /home4/jdrodri/public_h in /home4/jdrodri/public_html/sdjpublicaciones.com/wp-content/plugins/pressbooks/compatibility.php on line 75]

### Steps to Reproduce

1. [Unistall old PB plugin]
2. [Install new version]
3. [Activate for Network]

**Expected behavior:** [System to be updated to latest version of PB]

**Actual behavior:** [Fatal Error]

I am running WP 4.9.1 and PHP7.1 on my installation.

**Comment by greatislander** [comment]
This is covered in both the [Upgrading](https://docs.pressbooks.org/upgrading/#autoloader) section and the [Installation](https://docs.pressbooks.org/installation/#part-2-pressbooks) section of our documentation site, https://docs.pressbooks.org.
