### ISSUE TITLE
Internal links to chapters do not correctly export to EPUB, MOBI and EPUB 3

### ISSUE THREAD

**Issue by luis-r-izquierdo** [pressbooks/pressbooks#1026]
### Prerequisites

* [x] Can you reproduce the behavior you wish to address with [all other plugins deactivated](http://codex.wordpress.org/Multisite_Network_Administration#Plugins)?

* [ ] Are you running the [latest version of Pressbooks](http://github.com/pressbooks/pressbooks/releases/latest/) and the [latest version of WordPress](http://codex.wordpress.org/Upgrading_WordPress)?

#### WordPress Configuration

Network URL: http://wisc.pb.unizin.org/
Network Type: Subdirectory
Version: 4.9.1
Language: en_US
WP_ENV: Not set
WP_DEBUG: Disabled
Memory Limit: 64M

#### Pressbooks Configuration

Version: 4.5.0
Book Theme: Open Textbooks
Book Theme Version: 1.0.6
Root Theme: Pressbooks Publisher
Root Theme Version: 3.1.3

* [x] Are you experiencing this issue with one of our built-in root or book themes?

Book Theme: Open Textbooks
Book Theme Version: 1.0.6
Root Theme: Pressbooks Publisher
Root Theme Version: 3.1.3

* [x] Did you [perform a cursory search](https://github.com/issues?q=+is%3Aissue+repo%3Apressbooks%2Fpressbooks) to see if your bug or enhancement is already listed?

### Description

Hi There,

In our book, we have a few links from one chapter to another, and these do not correctly export to EPUB, MOBI and EPUB 3. A MWE is the following:

`<a href="https://wisc.pb.unizin.org/gametheory/chapter/1-0/">the next chapter</a>`

gets translated in EPUB, MOBI and EPUB 3 files into:

`<a href="chapter-005-1-0.html">the next chapter</a>`

but the name of the html file in the EPUB, MOBI and EPUB 3 file is:

chapter-005-slug-1-0.html

so the internal link does not work.

This occurs even if you define the original link in relative terms, i.e. as:

`<a href="/gametheory/chapter/1-0/">the next chapter</a>`

### Steps to Reproduce

As above

**Expected behavior:** 

That internal links to other chapters work

**Actual behavior:** 

They don't

#### Book Info

Book ID: 28
Book URL: https://wisc.pb.unizin.org/gametheory/
Book Privacy: Public

#### Browser

Platform: OS X
Browser Name: Safari
Browser Version: 11.0.2
User Agent String: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_2) AppleWebKit/604.4.7 (KHTML, like Gecko) Version/11.0.2 Safari/604.4.7

#### WordPress Configuration

Network URL: http://wisc.pb.unizin.org/
Network Type: Subdirectory
Version: 4.9.1
Language: en_US
WP_ENV: Not set
WP_DEBUG: Disabled
Memory Limit: 64M

#### Pressbooks Configuration

Version: 4.5.0
Book Theme: Open Textbooks
Book Theme Version: 1.0.6
Root Theme: Pressbooks Publisher
Root Theme Version: 3.1.3

#### Pressbooks Dependencies

Epubcheck: Installed
Kindlegen: Installed
xmllint: Installed
PrinceXML: Installed
Saxon-HE: Not Installed

#### Must-Use Plugins

hm-autoloader.php: n/a

#### Network Active Plugins

CM Tooltip Glossary: 3.5.8
Enhanced Media Library: 2.4.5
H5P: 1.10.0
Hypothesis: 0.5.0
Login Security Solution: 0.56.0
Pressbooks: 4.5.0
Pressbooks Textbook: 3.1.6
Regenerate Thumbnails: 3.0.1
Simple Custom CSS: 3.3
Simple Lightbox: 2.6.0
SSL Insecure Content Fixer: 2.5.0
TablePress: 1.9
TablePress Extension: DataTables Buttons: 1.1
Unizin Allow Custom Post Types: 1.0
Unizin Allow Plugins: 1.0.0
Unizin Allow Upload Extensions: 1.0.0
Unizin Mail From: 1.0.0
UW-Madison Kaltura Enable oEmbed: 1.0
WP-ShowHide: 1.04

#### Book Active Plugins

Broken Link Checker: 1.11.5
H5P: 1.10.0

#### Server Configuration

PHP Version: 7.1.12-3+ubuntu14.04.1+deb.sury.org+1
MySQL Version: 5.6.27
Webserver Info: Apache/2.4.7 (Ubuntu)

#### PHP Configuration

Safe Mode: Disabled
Memory Limit: 512M
Upload Max Size: 50M
Post Max Size: 55M
Upload Max Filesize: 50M
Time Limit: 300
Max Input Vars: 1000
URL-aware fopen: On (1)
Display Errors: N/A

#### PHP Extensions

OPcache: Zend
XDebug: Disabled
cURL: Supported
cURL Version: 7.35.0
imagick: Installed
xsl: Installed

**Comment by hughmcguire** [comment]
Can you test using a different theme?

**Comment by luis-r-izquierdo** [comment]
Sure, 
Same issue with Clarke

**Comment by connerbw** [comment]
This happens because your slug (also known as post_name) starts with a number.

These get pre-sanitized so that they can be used as XML IDs but the appended "slug" was not considered when trying to determine if the link was internal.
