### ISSUE TITLE
Uncaught (in promise) TypeError: Cannot read property 'getNotificationManagerImpl' of undefined

### ISSUE THREAD

**Issue by connerbw** [pressbooks/pressbooks#1028]
### Prerequisites

* [X] Can you reproduce the behavior you wish to address with [all other plugins deactivated](http://codex.wordpress.org/Multisite_Network_Administration#Plugins)?
* [X] Are you running the [latest version of Pressbooks](http://github.com/pressbooks/pressbooks/releases/latest/) and the [latest version of WordPress](http://codex.wordpress.org/Upgrading_WordPress)?
* [X] Are you experiencing this issue with one of our built-in root or book themes?
* [X] Did you [perform a cursory search](https://github.com/issues?q=+is%3Aissue+repo%3Apressbooks%2Fpressbooks) to see if your bug or enhancement is already listed?

### Description

I occasionally see a Javascript console bug on the Book Info page: `tinymce.min.js?ver=4607-20171116:28 Uncaught (in promise) TypeError: Cannot read property 'getNotificationManagerImpl' of undefined`

This appears to be an upstream problem. It is best described by quoting someone from the bug reports below linked below:

> only appears when I scroll. Even weirder: when the page loads and I don't scroll until it's finished loading, the error will not show up. If, however, I start scrolling back & forth before the page is fully loaded, it will spawn this error on every scroll movement. [...] Although the error spawns, it seems like I can still use tinyMCE editors.

 + https://github.com/tinymce/tinymce/issues/3947
 + https://core.trac.wordpress.org/ticket/42722

### Steps to Reproduce

 1. In Chrome, navigate to Book Info
 2. Scroll down until you see TinyMCE
 3. Open JavaScript console (Ctrl+Shift+J)
 4. Reload page (Ctrl+R)
 5. Scroll before page has finished rendering.

![js-bug](https://user-images.githubusercontent.com/812192/34577571-918c815e-f14f-11e7-9671-d1f0cd602d2a.png)

**Comment by greatislander** [comment]
Looks like this is fixed in WordPress Core and will be released in WordPress 4.9.3.
