### ISSUE TITLE
Loading books via API produces "Undefined index" notice from metadata namespace

### ISSUE THREAD

**Issue by greatislander** [pressbooks/pressbooks#1034]
### Prerequisites

* [x] Can you reproduce the behavior you wish to address with [all other plugins deactivated](http://codex.wordpress.org/Multisite_Network_Administration#Plugins)?
* [x] Are you running the [latest version of Pressbooks](http://github.com/pressbooks/pressbooks/releases/latest/) and the [latest version of WordPress](http://codex.wordpress.org/Upgrading_WordPress)?
* [x] Are you experiencing this issue with one of our built-in root or book themes?
* [x] Did you [perform a cursory search](https://github.com/issues?q=+is%3Aissue+repo%3Apressbooks%2Fpressbooks) to see if your bug or enhancement is already listed?

### Description

Loading `/books/` API endpoint in the root catalog sporadically produces a PHP notice:

```
Notice: Undefined index: in /srv/www/pressbooks.test/current/web/app/plugins/pressbooks/inc/metadata/namespace.php on line 589
```

### Steps to Reproduce

1. Load Aldine (landing page or catalog page).

**Expected behavior:** Book lists load without issue.

**Actual behavior:** The above notice is presented.

### System Information

Aldine: 1.0.0-alpha7ish
Pressbooks: 5.0-dev
WordPress: 4.9.1
PHP: 7.1

**Comment by connerbw** [comment]
Tested with dev branch of pressbooks-aldine

Note to future self `pressbooks/pressbooks-aldine:dev-dev` currently

 + is missing ` composer require erusev/parsedown-extra`
 + complains about missing MD docs:

```php
if ( ! get_option( 'pb_aldine_activated' ) ) {
	$extra = new ParsedownExtra();
	$home = $extra->text( file_get_contents( get_stylesheet_directory() . '/docs/home.md' ) );
	$help = $extra->text( file_get_contents( get_stylesheet_directory() . '/docs/help.md' ) );
	// ... snip ...
```

I did not fix those.

**Comment by greatislander** [comment]
☝️ I fixed them in https://github.com/pressbooks/pressbooks-aldine/commit/15fe65d7bf06cae145c05026ba835064ef6de17b
