### ISSUE TITLE
ODT export

### ISSUE THREAD

**Issue by greatislander** [pressbooks/pressbooks#104]
We want this.

**Comment by hughmcguire** [comment]
ned can you take a look at at building this pls ... I've sent you the updated XSLT so you can use that & see where we are!

**Comment by programmieraffe** [comment]
+1

**Comment by greatislander** [comment]
@hughmcguire I've got a rough version of this running on Textopress for you to experiment with. It's by no means perfect—one issue I've observed is that chapter/part numbering isn't being handled by the XSLT. Let me know what you think.

**Comment by greatislander** [comment]
@nudgeD We will need an icon for ODT files—OpenOffice blue? Shoot me an email if you need any more info.

**Comment by hughmcguire** [comment]
@bdolor first (well, second) cut of ODT export is available in pressbooks/dev .... i'm just starting to review it, but could you take a look as well.

**Comment by bdolor** [comment]
sure thing.

**Comment by bdolor** [comment]
Looks like two settings.xml files are being created: 

![screen shot 2015-04-03 at 9 35 47 am](https://cloud.githubusercontent.com/assets/2048170/6985321/ed26a144-d9e6-11e4-8766-f09994d12219.png)

**Comment by greatislander** [comment]
Not being familiar with XSLT—I assume this would be generated based on the spec [here](https://github.com/pressbooks/pressbooks/blob/dev/includes/modules/export/odt/xhtml2odt.xsl#L47)? It doesn't appear that there's any reason two should be generated. Can you see any reason for this, @bdolor?

**Comment by bdolor** [comment]
look no further than the redundant `$settings` variable  [here](https://github.com/pressbooks/pressbooks/blob/dev/includes/modules/export/odt/class-pb-odt.php#L90), good sir

**Comment by greatislander** [comment]
Thanks, @bdolor. Fixed!

**Comment by greatislander** [comment]
Any further feedback here?

**Comment by bdolor** [comment]
images, footnotes don't appear to make it through. ODT file icon not appearing on export page...Not sure how thorough to be at this point — Styling of block quotes, pull quotes, underline, super and sub scripts don't make it through. Looks like there is some smattering of raw html that makes it through to the document. Let me know if you need/want me to dig deeper.

**Comment by greatislander** [comment]
Thanks for the investigation, @bdolor. I'm aware of the missing icon. @hughmcguire, how do you want to proceed with comprehensive review of the output from this?

**Comment by hughmcguire** [comment]
hang tight, v2 is on the way shortly.

**Comment by hughmcguire** [comment]
Hi @bdolor can you pull & test now... I have a list of niggles but I think we are getting there.

**Comment by bdolor** [comment]
Must exclude the ability to load entities in an XML document when using `loadXML()`. Conforms to this document's suggested best practice: http://phpsecurity.readthedocs.org/en/latest/Injection-Attacks.html#defenses-against-xml-external-entity-injection 

- specifically, this line here: https://github.com/pressbooks/pressbooks/blob/dev/includes/modules/export/odt/class-pb-odt.php#L95
- reference: https://php.net/manual/en/function.libxml-disable-entity-loader.php
- previous discussion: https://github.com/pressbooks/pressbooks/commit/fc40d2b311cb6cf28aaca3100b56ba50ea91b4a7#commitcomment-4356326

Other possible side effects: 

![screen shot 2015-05-01 at 1 53 14 pm](https://cloud.githubusercontent.com/assets/2048170/7437536/fee0bffa-f00c-11e4-8ea7-04b91b2091f1.png)

**Comment by bdolor** [comment]
A more robust image 'fetcher' is necessary to both avoid causing the export to fail entirely (by that I mean not produce any document) if an image cannot be found, plus allow for LaTex images to make it through: 

- specifically, this line: https://github.com/pressbooks/pressbooks/blob/dev/includes/modules/export/odt/class-pb-odt.php#L134
- reference for robust image 'fetcher' `fetchAndSaveUniqueImage()`: https://github.com/pressbooks/pressbooks/blob/dev/includes/modules/export/epub/class-pb-epub201.php#L1614 
- render LaTeX images during an export: https://github.com/pressbooks/pressbooks/blob/dev/includes/modules/export/epub/class-pb-epub201.php#L1634

Doing so will avoid not producing the document at all on an image error: 
![screen shot 2015-05-01 at 2 40 28 pm](https://cloud.githubusercontent.com/assets/2048170/7437817/139f7348-f010-11e4-9a0f-c574b7afbde5.png)

And avoid not rendering LaTeX images:
![screen shot 2015-05-01 at 2 41 56 pm](https://cloud.githubusercontent.com/assets/2048170/7437838/4dfa22a4-f010-11e4-907a-afa9c8f375b4.png)

**Comment by bdolor** [comment]
Non-functional request is to bring consistency to how the ODT class file represents [coding standard formats](http://codex.wordpress.org/WordPress_Coding_Standards) which have so far, been adhered to with some vigor in this project. Spacing, use of camelCase for class variables only, and perhaps indenting here and there stand out at first glance.

**Comment by greatislander** [comment]
Thanks, @bdolor—will address some of these ASAP.

**Comment by hughmcguire** [comment]
@greatislander is this in your hands at the moment then?

**Comment by greatislander** [comment]
Yep—I had assigned you for review previously, @hughmcguire.

**Comment by greatislander** [comment]
@bdolor I've implemented the more robust image fetching routine as per your suggestion and the images are copying into the media folder; however they don't appear to be showing up in the document itself. Any ideas?

**Comment by bdolor** [comment]
I've tested three books and *most* of the images come out in the ODT export file. No pattern has emerged yet with the ones that don't make it through, but I haven't looked all that hard. Consistently, the cover image never makes it through and the latex images end up in the media folder but the link to them in content.xml aren't updated. 

![screen shot 2015-05-12 at 3 05 04 pm](https://cloud.githubusercontent.com/assets/2048170/7599596/52df01b2-f8b8-11e4-9270-2c1e9dedaaf7.png)

**Comment by hughmcguire** [comment]
what next? : /

**Comment by greatislander** [comment]
@bdolor Sorry for my ignorance here but what needs to happen to the link to latex images? Is this something that needs a change in the XSLT?

**Comment by hughmcguire** [comment]
@bdolor do you have other comments on the ODT export?

**Comment by hughmcguire** [comment]
Or is it just the image problem?

**Comment by bdolor** [comment]
We need the value at `xlink:href` to point to the media file that's been generated. The image fetching routine now generates an image and puts it in the `media` folder for any link that points to the image rendering service. 

![screen shot 2015-05-14 at 12 14 56 pm](https://cloud.githubusercontent.com/assets/2048170/7639726/e8994fac-fa32-11e4-9480-9fe2ff79b4da.png)

Now that link source needs to be updated. In the epub export it happens [here](https://github.com/pressbooks/pressbooks/blob/dev/includes/modules/export/epub/class-pb-epub201.php#L1593)

@hughmcguire  I will endeavour to look at the ODT export more thoroughly to see if there is anything else besides images.

**Comment by hughmcguire** [comment]
thanks @bdolor

**Comment by hughmcguire** [comment]
@bdolor we have a BCcampus-designated deadline of the end of June for delivery of ODT export -- I need to know if there are any other issues (besides images/cover images) that need to be address ... thanks!

**Comment by bdolor** [comment]
Right, thanks for the reminder. I am looking at it now.

**Comment by bdolor** [comment]
Export produces **PHP Notice** of undefined property here: https://github.com/pressbooks/pressbooks/blob/dev/includes/modules/export/odt/class-pb-odt.php#L319  — Images are never compressed. 

**Image captions:**
- aren't supported (converted to regular 'p' tags). Need an XSL rule/template that targets `<p class="wp-caption-text" `
- also, prints anything in the `<img alt` attribute as content `<img alt="this will end up as content"...`. In the example below the `<img alt` attribute is 'colour-dependent bar chart'
![screen shot 2015-06-12 at 11 01 09 am](https://cloud.githubusercontent.com/assets/2048170/8136797/90ac9e34-10f3-11e5-996e-a95be71af8d3.png)

**Table captions**
- any content in `<table><caption>This will disappear</caption></table>` will be excluded in the export file.

**Bookmarks**
- Bookmark rules only currently [apply to headers](https://github.com/pressbooks/pressbooks/blob/dev/includes/modules/export/odt/xhtml2odt.xsl#L517). If an anchor is declared on anything other than h1-h6, it will not be converted to a bookmark. 
- Internal links with the pattern `<a href="#internalanchor">Link to a bookmark</a>` will not be preserved on output. Need a test that looks for that pattern [here](https://github.com/pressbooks/pressbooks/blob/dev/includes/modules/export/odt/xhtml2odt.xsl#L873)

**Page Authors in TOC**
- currently indistinguishable from chapter title. (should we just remove/hide page author from TOC?). In the example below, `homer simpson` is the author, `Introduction` is the title.
![screen shot 2015-06-12 at 11 28 28 am](https://cloud.githubusercontent.com/assets/2048170/8137171/34331e50-10f6-11e5-855e-d26915c9affc.png)

**Page license in TOC**
- as above, page license (in this case `cc-by`) is right up against page authors in TOC
![screen shot 2015-06-12 at 11 43 31 am](https://cloud.githubusercontent.com/assets/2048170/8137460/705e0eec-10f8-11e5-86d9-c125e2bd0023.png)

**Parts in TOC**
- a part with no chapters marked for export still makes it into the TOC (see above screenshot, look for `Part 1`) 

**Image height/width fixed**
- Regardless of an image size, it is hard coded to display at a [fixed ratio](https://github.com/pressbooks/pressbooks/blob/dev/includes/modules/export/odt/xhtml2odt.xsl#L820) . Many images come out distorted and stretched like it's 1994.

**Styling** 
- indented styling not supported `<p class="indent"`
- no styling associated for shaded text box `<div class="textbox shaded"`
- pull quote left `<span class="pullquote-left"` needs borders, to be consistent with pull quote right.
- background colors and text colours aren't supported.

**Comment by hughmcguire** [comment]
thanks. working on all this.

**Comment by greatislander** [comment]
Image import for cover images and LaTex (#134) is now fixed, in my testing.

**Comment by hughmcguire** [comment]
hi @greatislander did you get the new XSL in slack?

**Comment by greatislander** [comment]
Yes, I integrated it in 2.5.1.

**Comment by hughmcguire** [comment]
gah where are we on this? let me check latest XSL files.

**Comment by greatislander** [comment]
For our own sanity, @hughmcguire, I am going to close this issue and ask that you create specific issues for outstanding bugs in the ODT export.
