### ISSUE TITLE
Missing dependencies for export

### ISSUE THREAD

**Issue by jdrodriguez** [pressbooks/pressbooks#1055]
### Prerequisites

_Check the boxes below by changing them from `[ ]` to `[x]`._

* [ ] Can you reproduce the behavior you wish to address with [all other plugins deactivated](http://codex.wordpress.org/Multisite_Network_Administration#Plugins)?
* [ ] Are you running the [latest version of Pressbooks](http://github.com/pressbooks/pressbooks/releases/latest/) and the [latest version of WordPress](http://codex.wordpress.org/Upgrading_WordPress)?
* [ ] Are you experiencing this issue with one of our built-in root or book themes?
* [ ] Did you [perform a cursory search](https://github.com/issues?q=+is%3Aissue+repo%3Apressbooks%2Fpressbooks) to see if your bug or enhancement is already listed?

### Description
I am getting an error when trying to export my book. It reads the following way:

Some dependencies for PDF, Print PDF, EPUB, MOBI, EPUB3, XHTML, ICML, and OpenDocument exports could not be found. Please verify that you have completed the installation instructions.

This is a working installation of PB that recently got upgraded to the latest version. It was working fine before the upgrade. 

I have installed the latest versions of KindleGen and EpubCheck in my server. I don't know what else to do. 

Here are the two lines of code to define those installations:

define( 'PB_KINDLEGEN_COMMAND', '/home4/jdrodri/usr/bin/KindleGen/kindlegen' );
define( 'PB_EPUBCHECK_COMMAND', '/home4/jdrodri/usr/bin/epubcheck -jar /home4/jdrodri/usr/bin/epubcheck/epubcheck-master/epubcheck-4.0.jar' );

### Steps to Reproduce

**Expected behavior:** [Export to Epub]

**Actual behavior:** [Unable to export]

#### Root Blog Info

Root Blog ID: 1
Root Blog URL: http://sdjpublicaciones.com/

#### Browser

Platform: Windows
Browser Name: Chrome
Browser Version: 63.0.3239.132
User Agent String: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36

#### WordPress Configuration

Network URL: http://sdjpublicaciones.com/
Network Type: Subdomain
Version: 4.9.2
Language: en_US
WP_ENV: Not set
WP_DEBUG: Disabled
Memory Limit: 64M

#### Pressbooks Configuration

Version: 4.5.0
Root Theme: Pressbooks Publisher
Root Theme Version: 3.1.3

#### Pressbooks Dependencies

Epubcheck: Not Installed
Kindlegen: Installed
xmllint: Not Installed
PrinceXML: Not Installed
Saxon-HE: Not Installed

#### Must-Use Plugins

hm-autoloader.php: n/a

#### Network Active Plugins

GitHub Updater: 7.4.4.4
Loco Translate: 2.0.17
Pressbooks: 4.5.0
Pressbooks mPDF: 3.0.0
Pressbooks Textbook: 3.1.6

#### Inactive Plugins

Akismet Anti-Spam: 4.0.2
Formidable Forms: 2.05.08
Hello Dolly: 1.6
Jetpack by WordPress.com: 5.6.1
MOJO Marketplace: 0.7.1
Ninja Forms: 3.2.6

#### Server Configuration

PHP Version: 7.0.25
MySQL Version: 5.6.32
Webserver Info: Apache

#### PHP Configuration

Safe Mode: Disabled
Memory Limit: 500M
Upload Max Size: 500M
Post Max Size: 500M
Upload Max Filesize: 500M
Time Limit: 3600
Max Input Vars: 5000
URL-aware fopen: On (1)
Display Errors: On (1)

#### PHP Extensions

OPcache: Disabled
XDebug: Disabled
cURL: Supported
cURL Version: 7.19.7
imagick: Not Installed
xsl: Installed

**Comment by connerbw** [comment]
On your web server edit the file: `pressbooks\inc\utility\namespace.php`

Find the functions: 
+ check_epubcheck_install()
+ check_kindlegen_install()

Live debug by doing `var_dump($output);` (or error_log() if you know how, whatever suits you) before these functions return.

I suspect your web server doesn't have permissions to `exec` or that the files are not there.

The output will tell you.

**Comment by greatislander** [comment]
From your debugging output:

> **Pressbooks Dependencies**
Epubcheck: Not Installed
Kindlegen: Installed
xmllint: Not Installed
PrinceXML: Not Installed
Saxon-HE: Not Installed

Pressbooks tests each of these by seeing if they output the correct version.

## EpubCheck (required for Epub and Kindle MOBI)

Default value for `PB_EPUBCHECK_COMMAND` is `/usr/bin/epubcheck`.

To test the EpubCheck install, Pressbooks executes the command:

```
PB_EPUBCHECK_COMMAND -h
```

And checks the output to make sure the libxml version >= 4.0.

## KindleGen (required for Kindle MOBI)

Default value for `PB_KINDLEGEN_COMMAND` is `/opt/kindlegen/kindlegen`.

To test the KindleGen install, Pressbooks executes the command:

```
PB_KINDLEGEN_COMMAND -h
```

And checks the output to make sure the KindleGen version >= 2.9.

## xmllint (required for XHTML and PDF)

Default value for `PB_XMLLINT_COMMAND` is `/usr/bin/xmllint/`.

To test the xmllint install, Pressbooks executes the command:

```
PB_XMLLINT_COMMAND --version
```

And checks the output to make sure the libxml version >= 20706.

### PrinceXML (required for PDF)

Default value for `PB_PRINCE_COMMAND` is `/usr/bin/prince/`.

To test the xmllint install, Pressbooks executes the command:

```
PB_PRINCE_COMMAND --version
```

And checks the output to make sure the PrinceXML version >= 11.

### Saxon-HE (required for ODT)

Default value for `PB_SAXON_COMMAND` is `/usr/bin/java -jar /opt/saxon-he/saxon-he.jar`.

To test the Saxon-HE install, Pressbooks executes the command:

```
PB_SAXON_COMMAND -?
```

And checks the output to make sure the Saxon-HE version >= 9.7.0-10.

I'd suggest running each of these commands on your server and checking the output. If you don't require specific formats, you can disregard the errors for those formats.

If you have any follow-up questions, I suggest posting them in the [Pressbooks Forum](https://discourse.pressbooks.org), as this is a configuration issue, not a bug/feature request. Thanks! And I hope this helps you figure out what exactly isn't working.

**Comment by swerizwan** [comment]
Please, help me is there any easy how to fix this error?
