### ISSUE TITLE
I valideted the htmlbook export against htmlbook.xsd and got many error messages

### ISSUE THREAD

**Issue by thomasdumm** [pressbooks/pressbooks#1079]
### Prerequisites

_Check the boxes below by changing them from `[ ]` to `[x]`._

* [x] Can you reproduce the behavior you wish to address with [all other plugins deactivated](http://codex.wordpress.org/Multisite_Network_Administration#Plugins)?
* [x] Are you running the [latest version of Pressbooks](http://github.com/pressbooks/pressbooks/releases/latest/) and the [latest version of WordPress](http://codex.wordpress.org/Upgrading_WordPress)?
* [x] Are you experiencing this issue with one of our built-in root or book themes?
* [ ] Did you [perform a cursory search](https://github.com/issues?q=+is%3Aissue+repo%3Apressbooks%2Fpressbooks) to see if your bug or enhancement is already listed?

### Description
I validated the htmlbook export against https://raw.githubusercontent.com/oreillymedia/HTMLBook/master/schema/htmlbook.xsd with oxygen editor
I got many error messages. Mostly related to h1...h6 tags but also to border="0" attribute in the table tag. Also errors on block content in td like:

 ```
<td><b>Interne Anspruchsgruppen</b>
<ul>
 <li>Eigentümer</li>
<li>Management</li>
<li>Mitarbeitende</li>
 </ul>
</td>
```

Should I report them in detail or is this still ongoing work or am I validating against the wrong schema?

**Comment by connerbw** [comment]
> Should I report them in detail or is this still ongoing work or am I validating against the wrong schema?

The work is ongoing. [From our blog:](https://pressbooks.org/blog/2018/01/17/pressbooks-5-developer-guide/)

> "We’re also working with the creators of HTMLBook to expand and improve the standard. [...] At this time, our HTMLBook exporter is not production-ready, but we will be using it as a testbed to refine our best practices for coding export modules in Pressbooks."

Our initial assumption was that HTMLBook would make it easier to support HTML5 than how we do it in our XHTML ouptut. [1] After we built the prototype, which you are using, we realized our assumption was wrong. If you want to use HTMLBook then you will have to make sure your HTML conforms to their validatotion rules. Pressbooks does not sanitize (valid) HTML5 at this time.

[1] https://github.com/oreillymedia/HTMLBook/issues/215

**Comment by greatislander** [comment]
Related: investigate section handling within HTMLBook (and HTMLBook TOC).
