### ISSUE TITLE
Non-Breaking spaces &nbsp; create parser error messages in php_error.log during in htmlbook 

### ISSUE THREAD

**Issue by thomasdumm** [pressbooks/pressbooks#1080]
### Prerequisites

_Check the boxes below by changing them from `[ ]` to `[x]`._

* [x] Can you reproduce the behavior you wish to address with [all other plugins deactivated](http://codex.wordpress.org/Multisite_Network_Administration#Plugins)?
* [x] Are you running the [latest version of Pressbooks](http://github.com/pressbooks/pressbooks/releases/latest/) and the [latest version of WordPress](http://codex.wordpress.org/Upgrading_WordPress)?
* [x] Are you experiencing this issue with one of our built-in root or book themes?
* [x] Did you [perform a cursory search](https://github.com/issues?q=+is%3Aissue+repo%3Apressbooks%2Fpressbooks) to see if your bug or enhancement is already listed?

### Description
Non-Breaking spaces &nbsp; create parser error messages in php_error.log during in htmlbook export.  i see these error messages in the php_error.log:

/Applications/MAMP/htdocs/wordpress/wp-content/uploads/sites/6/pressbooks/exports/Personalmarketing-und-entwicklung-1517926096.-htmlbook.html:1628: parser error : Entity 'nbsp' not defined
offenen Stellen werden auf der eigenen Firmen-Homepage publiziert, rund 60&nbsp;

#### Book Info

Book ID: 8
Book URL: http://localhost/wordpress/testpb5/
Book Privacy: Public

#### Browser

Platform: OS X
Browser Name: Firefox
Browser Version: 58.0
User Agent String: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:58.0) Gecko/20100101 Firefox/58.0

#### WordPress Configuration

Network URL: http://localhost/wordpress/
Network Type: Subdirectory
Version: 4.9.3
Language: en_US
WP_ENV: developer
WP_DEBUG: Enabled
Memory Limit: 64M

#### Pressbooks Configuration

Version: 4.5.0
Book Theme: McLuhan
Book Theme Version: 2.0.0-alpha1
Root Theme: Aldine
Root Theme Version: 1.0.0-alpha.6

#### Pressbooks Dependencies

Epubcheck: Installed
Kindlegen: Installed
xmllint: Installed
PrinceXML: Installed
Saxon-HE: Installed

#### Must-Use Plugins

hm-autoloader.php: n/a

#### Network Active Plugins

Pressbooks: 5.0.0-dev

#### Inactive Plugins

Activity Log: 2.4.0
WP Security Audit Log: 3.0.1

#### Server Configuration

PHP Version: 7.1.12
MySQL Version: 5.6.38
Webserver Info: Apache/2.2.34 (Unix) mod_wsgi/3.5 Python/2.7.13 PHP/7.1.12 mod_ssl/2.2.34 OpenSSL/1.0.2j DAV/2 mod_fastcgi/2.4.6 mod_perl/2.0.9 Perl/v5.24.0

#### PHP Configuration

Safe Mode: Disabled
Memory Limit: 256M
Upload Max Size: 32M
Post Max Size: 32M
Upload Max Filesize: 32M
Time Limit: 30
Max Input Vars: 1000
URL-aware fopen: On (1)
Display Errors: On (1)

#### PHP Extensions

OPcache: Disabled
XDebug: Disabled
cURL: Supported
cURL Version: 7.52.1
imagick: Not Installed
xsl: Installed

**Comment by connerbw** [comment]
This is not a PHP error. This is an HTMLBook validation error. It happens when doing:

`xmllint --noout --schema htmlbook.xsd <your_html_filename>.html`

htmlbook.xsd wants stricter XML, doesn't like `&nsbp;`

**Comment by connerbw** [comment]
Related: https://github.com/pressbooks/pressbooks/issues/1079

**Comment by greatislander** [comment]
Closing in favour of #1079.
