### ISSUE TITLE
For books that existed in the system before PB5 was installed I am not able to add new chapters to the parts

### ISSUE THREAD

**Issue by thomasdumm** [pressbooks/pressbooks#1081]
### Prerequisites

_Check the boxes below by changing them from `[ ]` to `[x]`._

* [x] Can you reproduce the behavior you wish to address with [all other plugins deactivated](http://codex.wordpress.org/Multisite_Network_Administration#Plugins)?
* [x] Are you running the [latest version of Pressbooks](http://github.com/pressbooks/pressbooks/releases/latest/) and the [latest version of WordPress](http://codex.wordpress.org/Upgrading_WordPress)?
* [x] Are you experiencing this issue with one of our built-in root or book themes?
* [ ] Did you [perform a cursory search](https://github.com/issues?q=+is%3Aissue+repo%3Apressbooks%2Fpressbooks) to see if your bug or enhancement is already listed?

### Description

For books that existed in the system before PB5 was installed I am not able to add new chapters.
Also the part drop-down in the chapter is not shown.
I think the two problems are related. I am probably able to create a new chapter and save it, but as it is not attached to a part, it does not show up anywhere.

The issue also happens if I activate the Clarke theme. So it looks related to pressbooks and not pressbooks-book.

#### Book Info

Book ID: 6
Book URL: http://localhost/wordpress/pwlo00117r7/
Book Privacy: Public

#### Browser

Platform: OS X
Browser Name: Firefox
Browser Version: 58.0
User Agent String: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:58.0) Gecko/20100101 Firefox/58.0

#### WordPress Configuration

Network URL: http://localhost/wordpress/
Network Type: Subdirectory
Version: 4.9.4
Language: en_US
WP_ENV: developer
WP_DEBUG: Enabled
Memory Limit: 64M

#### Pressbooks Configuration

Version: 4.5.0
Book Theme: McLuhan
Book Theme Version: 2.0.0-beta.2
Root Theme: Aldine
Root Theme Version: 1.0.0-alpha.6

#### Pressbooks Dependencies

Epubcheck: Installed
Kindlegen: Installed
xmllint: Installed
PrinceXML: Installed
Saxon-HE: Installed

#### Must-Use Plugins

hm-autoloader.php: n/a

#### Network Active Plugins

Pressbooks: 5.0.0-dev

#### Server Configuration

PHP Version: 7.1.12
MySQL Version: 5.6.38
Webserver Info: Apache/2.2.34 (Unix) mod_wsgi/3.5 Python/2.7.13 PHP/7.1.12 mod_ssl/2.2.34 OpenSSL/1.0.2j DAV/2 mod_fastcgi/2.4.6 mod_perl/2.0.9 Perl/v5.24.0

#### PHP Configuration

Safe Mode: Disabled
Memory Limit: 256M
Upload Max Size: 32M
Post Max Size: 32M
Upload Max Filesize: 32M
Time Limit: 30
Max Input Vars: 1000
URL-aware fopen: On (1)
Display Errors: On (1)

#### PHP Extensions

OPcache: Disabled
XDebug: Disabled
cURL: Supported
cURL Version: 7.52.1
imagick: Not Installed
xsl: Installed

**Comment by thomasdumm** [comment]
Do you need more information from me? In case this is a reproducible issue it looks like a major issue to me.
![img00](https://user-images.githubusercontent.com/3658808/36146132-ea03325a-10b3-11e8-86a1-39740a99e239.jpg)
![img01](https://user-images.githubusercontent.com/3658808/36146134-ed6fbb0c-10b3-11e8-8877-7c30b7b65de9.jpg)

**Comment by connerbw** [comment]
I saw this once, when developing, but that's because the upgrade routine was aborted by accident while developing.

Can you do me a favour? In: `\pressbooks\inc\admin\metaboxes\namespace.php` change `override_parent_id` near line 706 to:

```php
/**
 * Render "Part" meta box
 *
 * @param |WP_Post $post
 */
function override_parent_id( $post ) {

	if ( 'chapter' !== $post->post_type ) {
		var_dump( "NOT A CHAPTER?" . $post->post_type );
		return; // Do nothing
	}

	if ( $post->post_parent ) {
		$selected = $post->post_parent;
	} elseif ( isset( $_GET['startparent'] ) ) {
		$selected = absint( $_GET['startparent'] );
	} else {
		$selected = 0;
	}

	$pages = wp_dropdown_pages(
		[
			'post_type' => 'part',
			'selected' => $selected,
			'name' => 'parent_id',
			'sort_column' => 'menu_order',
			'echo' => 0,
		]
	);

	var_dump( @$post->post_parent, @$_GET['startparent'], $selected );
	var_dump( $pages );

	if ( ! empty( $pages ) ) {
		echo $pages;
	}
}
```

This will print some debug junk in the upper right. Please copy paste the text in this ticket (and not a screenshot, because as you can see, it gets truncated I can't see all the info. You might have to do a view source.):

![debug-junk](https://user-images.githubusercontent.com/812192/36153855-a613f860-109d-11e8-8103-a69939d0b429.PNG)

**Comment by thomasdumm** [comment]
That gives me:
string(1) "3" NULL string(1) "3" string(0) "" 

PS: To be sure that it is not related to the fact that the Pressbooks 4.5.1 book was originally cloned I deleted the book and went back to V4.5.1 and manually created a new book with the same result.

**Comment by connerbw** [comment]
Click on "Personalmarketing" from your screenshot. Does the URL look? 
`http://pressbooks.test/test1/wp-admin/post.php?post=3&action=edit`
What does it say for `post=3` I would like to know the number.

Next, add this to the top of the function and get back to me with the results:
```php
	global $wpdb;
	$results = $wpdb->get_results( "SELECT ID, post_status FROM {$wpdb->posts} WHERE post_type = 'part' ", ARRAY_A );
	print_r( $results );
```

Thanks for your help.

**Comment by thomasdumm** [comment]
http://localhost/wordpress/test/wp-admin/post.php?post=3&action=edit

**Comment by thomasdumm** [comment]
Array ( [0] => Array ( [ID] => 3 [post_status] => publish ) ) string(1) "3" NULL string(1) "3" string(125) "

**Comment by thomasdumm** [comment]
Now the dropdown works. The Part title is shown now. I can also add new chapters to the book.

- Did the last "operation" fix that?
- Was I blind before?

**Comment by connerbw** [comment]
> Did the last "operation" fix that?

Yeah. Exactly. Weird. I think that's also what happened to me. Do you have Memcached or Redis? Might have been a caching issue?

**Comment by thomasdumm** [comment]
I have no non-Pressbooks Plugins installed in my Wordpress installation at the moment.

**Comment by connerbw** [comment]
As a safety I think i'm going to rewrite the code to use our own query instead of `wp_dropdown_pages`. I'm not sure what's going here. Sorry.

**Comment by connerbw** [comment]
PS:

Workaround: Click on the part in the administration interface.

_I think that was the action that fixed it._

Will submit code soon.
