### ISSUE TITLE
Add "Create New <contributor type>" button, add clarification label to field (if possible)

### ISSUE THREAD

**Issue by greatislander** [pressbooks/pressbooks#1086]
### Prerequisites

* [x] Can you reproduce the behavior you wish to address with [all other plugins deactivated](http://codex.wordpress.org/Multisite_Network_Administration#Plugins)?
* [x] Are you running the [latest version of Pressbooks](http://github.com/pressbooks/pressbooks/releases/latest/) and the [latest version of WordPress](http://codex.wordpress.org/Upgrading_WordPress)?
* [x] Are you experiencing this issue with one of our built-in root or book themes?
* [x] Did you [perform a cursory search](https://github.com/issues?q=+is%3Aissue+repo%3Apressbooks%2Fpressbooks) to see if your bug or enhancement is already listed?

### Description

It may not be immediately clear that the contributor select fields only choose from existing contributors. We should:

1. Add a label to the select field which reads `Choose some (authors|editors|…)` (see [here](https://select2.org/configuration); this may not be supported in Custom Metadata, but worth checking).
2. Add a button below each contributor select field which links to the new contributor action on the taxonomy management page.

### Mockup

<img width="774" alt="screen shot 2018-02-08 at 8 30 27 pm" src="https://user-images.githubusercontent.com/605361/36006142-94d8e63a-0d11-11e8-90e2-2920f8d21a26.png">

Button (`<a class="button">`) links to: `wp-admin/edit-tags.php?taxonomy=contributor&add-tag`

### Steps to Reproduce

Not applicable.

### System Information

Pressbooks: 5.0.0-beta.1
WordPress: 4.9.4
PHP: 7.1

**Comment by zwhpressbooks** [comment]
Looks good, would just change copy in field to: "Choose author(s)..." etc.
