### ISSUE TITLE
SILE as PDF generator backend?

### ISSUE THREAD

**Issue by skreutzer** [pressbooks/pressbooks#109]
You guys might consider to look into http://www.sile-typesetter.org (https://www.youtube.com/watch?v=5BIP_N9qQm4) as a way to get rid of the PrinceXML dependency, as the latter is proprietary software. Unfortunately, SILE is licensed under the X11 license, but as Pressbooks is under GPLv2, I guess you're not bothered too much regarding it's shortcomings in protecting users rights.

There are other freely licensed PDF generator backends as well, this is the latest one I got notified about.

**Comment by bdolor** [comment]
For the last few months @jgraham909 and I have been working on an [alternative PDF backend](https://github.com/bdolor/pressbooks/tree/pdf) using [mPDF](http://www.mpdf1.com/mpdf/index.php) as a backend. This will provide an open source alternative to Prince — Prince is fantastic, but as mentioned, proprietary, which can be a barrier. I'll be submitting a Pull Request by the end of the week. mPDF is also released under [GPL](http://www.mpdf1.com/mpdf/index.php?page=Licence)

**Comment by skreutzer** [comment]
Thank you very much! I'll look into mPDF as soon as I can find the time.

**Comment by greatislander** [comment]
@bdolor @skreutzer Are we comfortable closing this issue now that #111 has been merged in? I’d like to focus development resources on enhancing mPDF as our open source PDF export option given the work that's already gone into it on @bdolor and @jgraham909's part.

**Comment by bdolor** [comment]
If providing an alternative to PrinceXML was the intended goal, closing this sounds reasonable to me.

**Comment by greatislander** [comment]
Thanks @bdolor.
