### ISSUE TITLE
registered users without access to any books do not see the menus needed to create or clone a book, even if their role allows it

### ISSUE THREAD

**Issue by thomasdumm** [pressbooks/pressbooks#1102]
### Prerequisites

_Check the boxes below by changing them from `[ ]` to `[x]`._

* [x] Can you reproduce the behavior you wish to address with [all other plugins deactivated](http://codex.wordpress.org/Multisite_Network_Administration#Plugins)?
* [x] Are you running the [latest version of Pressbooks](http://github.com/pressbooks/pressbooks/releases/latest/) and the [latest version of WordPress](http://codex.wordpress.org/Upgrading_WordPress)?
* [x] Are you experiencing this issue with one of our built-in root or book themes?
* [ ] Did you [perform a cursory search](https://github.com/issues?q=+is%3Aissue+repo%3Apressbooks%2Fpressbooks) to see if your bug or enhancement is already listed?

### Description

registered users without access to any book do not see the menus needed to create or clone a book, even if their role allows it

#### Root Blog Info

Root Blog ID: 1
Root Blog URL: http://localhost/wordpress/

#### Browser

Platform: OS X
Browser Name: Firefox
Browser Version: 58.0
User Agent String: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:58.0) Gecko/20100101 Firefox/58.0

#### WordPress Configuration

Network URL: http://localhost/wordpress/
Network Type: Subdirectory
Version: 4.9.4
Language: en_US
WP_ENV: developer
WP_DEBUG: Enabled
Memory Limit: 64M

#### Pressbooks Configuration

Version: 4.5.0
Root Theme: Aldine
Root Theme Version: 1.0.0-alpha.6

#### Pressbooks Dependencies

Epubcheck: Installed
Kindlegen: Installed
xmllint: Installed
PrinceXML: Installed
Saxon-HE: Installed

#### Must-Use Plugins

hm-autoloader.php: n/a

#### Network Active Plugins

Pressbooks: 5.0.0-dev

#### Server Configuration

PHP Version: 7.1.12
MySQL Version: 5.6.38
Webserver Info: Apache/2.2.34 (Unix) mod_wsgi/3.5 Python/2.7.13 PHP/7.1.12 mod_ssl/2.2.34 OpenSSL/1.0.2j DAV/2 mod_fastcgi/2.4.6 mod_perl/2.0.9 Perl/v5.24.0

#### PHP Configuration

Safe Mode: Disabled
Memory Limit: 256M
Upload Max Size: 32M
Post Max Size: 32M
Upload Max Filesize: 32M
Time Limit: 30
Max Input Vars: 1000
URL-aware fopen: On (1)
Display Errors: On (1)

#### PHP Extensions

OPcache: Disabled
XDebug: Disabled
cURL: Supported
cURL Version: 7.52.1
imagick: Not Installed
xsl: Installed

**Comment by connerbw** [comment]
Did you enable cloning at the network level?

![enable-cloning](https://user-images.githubusercontent.com/812192/36159751-830bf308-10ad-11e8-839f-cc3a141c6339.png)

http://pressbooks.test/wp/wp-admin/network/settings.php?page=pressbooks_sharingandprivacy_options

**Comment by thomasdumm** [comment]
that is correctly set. that is not the problem. as soon as i have access to one book i see the menus. otherwise this is the view of all roles except network admin:
![t1](https://user-images.githubusercontent.com/3658808/36160123-b6afd2a0-10e0-11e8-9687-0fd423111716.jpg)

**Comment by greatislander** [comment]
@thomasdumm Did you register that user without registering a book? Generally, users:

1. Register and create a book at the same time;
2. Are registered and added to a book at the same time (by an administrator of an existing book).

This appears to be an edge case.

**Comment by greatislander** [comment]
TODO:

- [ ] Add link to registration page from the dashboard of a user who has registered without registering a book.

**Comment by greatislander** [comment]
FYI @thomasdumm this is the behaviour of WordPress Multisite (if you register a user without a blog, you end up on a dashboard where you can't "do" anything). We can add a link back to the registration page for convenience.
