### ISSUE TITLE
Question: Is there a way to hide the publish menu for the whole network?

### ISSUE THREAD

**Issue by thomasdumm** [pressbooks/pressbooks#1108]
### Prerequisites

_Check the boxes below by changing them from `[ ]` to `[x]`._

* [ ] Can you reproduce the behavior you wish to address with [all other plugins deactivated](http://codex.wordpress.org/Multisite_Network_Administration#Plugins)?
* [ ] Are you running the [latest version of Pressbooks](http://github.com/pressbooks/pressbooks/releases/latest/) and the [latest version of WordPress](http://codex.wordpress.org/Upgrading_WordPress)?
* [ ] Are you experiencing this issue with one of our built-in root or book themes?
* [ ] Did you [perform a cursory search](https://github.com/issues?q=+is%3Aissue+repo%3Apressbooks%2Fpressbooks) to see if your bug or enhancement is already listed?

### Description
Is there a way to hide the publish menu for the whole network?

![publish](https://user-images.githubusercontent.com/3658808/36262491-dcf694ac-1267-11e8-8548-5e9d0fceb146.jpg)

**Comment by connerbw** [comment]
Thomas, GitHub is for Bug reports . Can I suggest you join us in the forums?

https://discourse.pressbooks.org/
