### ISSUE TITLE
Arrows are not available and other bugs

### ISSUE THREAD

**Issue by colomet** [pressbooks/pressbooks#1139]
### Prerequisites

_Check the boxes below by changing them from `[ ]` to `[x]`._

* [x] Can you reproduce the behavior you wish to address with [all other plugins deactivated](http://codex.wordpress.org/Multisite_Network_Administration#Plugins)?
* [x] Are you running the [latest version of Pressbooks](http://github.com/pressbooks/pressbooks/releases/latest/) and the [latest version of WordPress](http://codex.wordpress.org/Upgrading_WordPress)?
* [x] Are you experiencing this issue with one of our built-in root or book themes?
* [x] Did you [perform a cursory search](https://github.com/issues?q=+is%3Aissue+repo%3Apressbooks%2Fpressbooks) to see if your bug or enhancement is already listed?

### Description

Home page of book theme I get that error. here: http://pressbooks.lvps84-39-103-248.mammuts-servidor.es/booknew/

Fatal error
: Uncaught Error: Call to undefined function Pressbooks\xdebug_break() in /var/www/vhosts/lvps84-39-103-248.mammuts-servidor.es/pressbooks.lvps84-39-103-248.mammuts-servidor.es/wp-content/plugins/pressbooks/inc/class-book.php:631 Stack trace: #0 /var/www/vhosts/lvps84-39-103-248.mammuts-servidor.es/pressbooks.lvps84-39-103-248.mammuts-servidor.es/wp-content/plugins/pressbooks/functions.php(37): Pressbooks\Book::get('prev') #1 /var/www/vhosts/lvps84-39-103-248.mammuts-servidor.es/pressbooks.lvps84-39-103-248.mammuts-servidor.es/wp-content/themes/pressbooks-book/functions.php(228): pb_get_prev() #2 /var/www/vhosts/lvps84-39-103-248.mammuts-servidor.es/pressbooks.lvps84-39-103-248.mammuts-servidor.es/wp-content/themes/pressbooks-book/partials/content-cover-book-header.php(3): pb_get_links(false) #3 /var/www/vhosts/lvps84-39-103-248.mammuts-servidor.es/pressbooks.lvps84-39-103-248.mammuts-servidor.es/wp-content/themes/pressbooks-book/page-cover.php(14): include('/var/www/vhosts...') #4 /var/www/vhosts/lvps84-39-103 in
/var/www/vhosts/lvps84-39-103-248.mammuts-servidor.es/pressbooks.lvps84-39-103-248.mammuts-servidor.es/wp-content/plugins/pressbooks/inc/class-book.php
on line
631

also the change the page arrows are not available

### Steps to Reproduce

go to one book, go to read, and try to change the page

**Expected behavior:** [to see the arrows and be able to change the page]

**Actual behavior:** [the arrows for change the page are missing]

### System Information

Pressbooks: [5.0.1]
WordPress: [4.9.4]
PHP: [7.0]

#### Root Blog Info

Root Blog ID: 1
Root Blog URL: http://pressbooks.lvps84-39-103-248.mammuts-servidor.es/

#### Browser

Platform: OS X
Browser Name: Firefox
Browser Version: 58.0
User Agent String: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:58.0) Gecko/20100101 Firefox/58.0

#### WordPress Configuration

Network URL: http://pressbooks.lvps84-39-103-248.mammuts-servidor.es/
Network Type: Subdirectory
Version: 4.9.4
Language: en_US
WP_ENV: Not set
WP_DEBUG: Enabled
Memory Limit: 64M

#### Pressbooks Configuration

Version: 5.0.1
Root Theme: Aldine
Root Theme Version: 1.0.0-RC.2

#### Pressbooks Dependencies

Epubcheck: Not Installed
Kindlegen: Installed
xmllint: Installed
PrinceXML: Not Installed
Saxon-HE: Installed

#### Must-Use Plugins

hm-autoloader.php: n/a

#### Network Active Plugins

Pressbooks: 5.0.1
Wordfence Security: 7.1.0

#### Inactive Plugins

mPDF for Pressbooks: 3.1.0
Textbooks for Pressbooks: 4.0.0

#### Server Configuration

PHP Version: 7.0.27
MySQL Version: 5.5.59
Webserver Info: Apache

#### PHP Configuration

Safe Mode: Disabled
Memory Limit: 256M
Upload Max Size: 2M
Post Max Size: 8M
Upload Max Filesize: 2M
Time Limit: 30
Max Input Vars: 1000
URL-aware fopen: On (1)
Display Errors: On (1)

#### PHP Extensions

OPcache: Zend
XDebug: Disabled
cURL: Supported
cURL Version: 7.35.0
imagick: Installed
xsl: Installed

**Comment by colomet** [comment]
Did you see also the arrows are not longer available? the way we change the page

**Comment by greatislander** [comment]
Yes, @colomet, that was the bug I fixed.
