### ISSUE TITLE
Restore password-protected content management

### ISSUE THREAD

**Issue by greatislander** [pressbooks/pressbooks#1143]
### Prerequisites

* [x] Can you reproduce the behavior you wish to address with [all other plugins deactivated](http://codex.wordpress.org/Multisite_Network_Administration#Plugins)?
* [x] Are you running the [latest version of Pressbooks](http://github.com/pressbooks/pressbooks/releases/latest/) and the [latest version of WordPress](http://codex.wordpress.org/Upgrading_WordPress)?
* [x] Are you experiencing this issue with one of our built-in root or book themes?
* [x] Did you [perform a cursory search](https://github.com/issues?q=+is%3Aissue+repo%3Apressbooks%2Fpressbooks) to see if your bug or enhancement is already listed?

### Description

We need to bring back password-protected chapters. See: https://discourse.pressbooks.org/t/visibility-controls-in-editor-missing-password-section/413

### Steps to Reproduce

Not applicable.

### System Information

Pressbooks: 5.0.2
WordPress: 4.9.4
PHP: 7.1

**Comment by connerbw** [comment]
> Spec

Show in Web = false
![screen shot 2018-03-12 at 11 40 25 am](https://user-images.githubusercontent.com/812192/37291296-b9738838-25e4-11e8-97f3-f255f57281e5.png)

Show in Web = true
![screen shot 2018-03-12 at 11 40 13 am](https://user-images.githubusercontent.com/812192/37291294-b7751c86-25e4-11e8-8777-9f19018e9fd6.png)

Show in Web = true, Require a Password = true
![screen shot 2018-03-12 at 11 39 55 am](https://user-images.githubusercontent.com/812192/37291325-c9b381da-25e4-11e8-8946-19e94596efe3.png)
