### ISSUE TITLE
Keyboard navigation: No visual marker to show when keyboard focus is on "Download this book"

### ISSUE THREAD

**Issue by josieg** [pressbooks/pressbooks#1149]
### Description

When tabbing through the links on a book's homepage, there is no visual marker when the keyboard focus is on the "Download this book" drop-down menu. This is an accessibility issue for visual users who use a keyboard to navigate. 

### Steps to Reproduce

1. Go to a book's home page.
2. Use the [Tab] key to navigate through the link on this page to try to access the "Download this book" drop-down menu. 
3. The order of links when tabbing is: ... Home > Read > Admin > Sign out > Search field > Search icon > Download this book > .. etc
4. All of the links have a visual marker showing when the keyboard focus is on them, except for "Download this book." As such, a visual user tabbing through the links has to know the order of links to know when the keyboard focus is on "Download this book" to be able to expand that drop-down menu.

**Expected behavior:**

I would expect the "Download this book" drop-down menu to have a visual marker when the keyboard focus is on it. 

**Actual behavior:** [What actually happened]

As it is now, there is no visual marker when keyboard focus is on the "Download this book" drop-down menu.

### System Information

Pressbooks: 5.0.2
WordPress: 4.9.4
PHP: 7.19.7

**Comment by greatislander** [comment]
Hi @josieg—can you move this issue to https://github.com/pressbooks/pressbooks-book? Thank you.
