### ISSUE TITLE
audio files included in web output, not displaying in export

### ISSUE THREAD

**Issue by bdolor** [pressbooks/pressbooks#115]
**To recreate**: Add an audio file from media library to your content area. Export the book. Audio file (url with link back to the audio file) and content proceeding audio file do not display.

**Description**: adding audio files to the content area invokes `wp_audio_shortcode()` which adds a default, inline `style` attribute with `visibility:hidden`. https://core.trac.wordpress.org/changeset/28182#file3

 Without the necessary CSS and JS present in the browser, this inline style remains in the XHTML output, preventing it from being displayed in any of the export routines. 

![screen shot 2015-04-15 at 11 38 37 am](https://cloud.githubusercontent.com/assets/2048170/7169702/cd49af34-e37c-11e4-920b-17804de95df2.png)

**Potential Resolutions**: It could be overridden with CSS, but that would mean going through each and every theme. Invoking HTMLLawed `deny_attribute` can target specific attributes on specific elements, but the `audio` tag is converted to a `div` tag in `\PressBooks\Sanitize\html5_to_xhtml11` so taking it out would mean targeting all `div` tags, instead of just the `audio` tag — is this such a bad thing? Likely a `preg_replace` or DOM traversal and node replacement is in order.

**Comment by hughmcguire** [comment]
what does the div tag look like in the xHTML?

**Comment by bdolor** [comment]
Note: `visibility: hidden` 
![screen shot 2015-05-14 at 12 02 54 pm](https://cloud.githubusercontent.com/assets/2048170/7639495/440a6738-fa31-11e4-8224-6fe2848fadd9.png)

Curious that  `<div id="audio-1-1">` also seems to envelop the rest of the content on the page, making any content that follows the audio clip not appear.

**Comment by greatislander** [comment]
@bdolor That is very odd. In terms of fixing this—could targeting `<div>` elements whose `class="wp-audio-shortcode"` and removing the inline style be sufficient to address this primary issue?

**Comment by bdolor** [comment]
seems like a plausible suggestion.

**Comment by greatislander** [comment]
Okay, I can take a look at this.

**Comment by greatislander** [comment]
Fix is underway.

**Comment by greatislander** [comment]
@bdolor Looking for some `preg_replace` insight here. I can capture audio elements by `id` with no issue as follows:
```
$t = preg_replace('/(id=\"audio-[0-9]-[0-9]\")/u', "$1 data-replaced=\"true\"", $t);
```
However when I try to capture the `style` tag as well it doesn`t work:

```
$t = preg_replace('/(id=\"audio-[0-9]-[0-9]\")( style=\"width: 100%; visibility: hidden;\")/u', "$1", $t);
```

Thoughts?

**Comment by bdolor** [comment]
If it's just a matter of the correct reg_exp try this:

`preg_replace('/(id=\"audio-[0-9]-[0-9]\")(.*)(style="[^\"]*\")/ui', "$1$2", $t );`

**Comment by greatislander** [comment]
Thanks @bdolor! Does https://github.com/bight/pressbooks/commit/de459efd866d17cdedc119e37ad8b055d1c42b46 do the trick for you?

**Comment by bdolor** [comment]
I'm glad you also took care of the possibility that `id ="audio-1-2` could have more numbers that just 1-9. I noticed that after I hit 'Comment'. Looks good from the outset. Do you need me to test it as well, or have you already done so?

**Comment by greatislander** [comment]
I have done so, and the link to the audio file (in the webbook) does indeed show up. We don't have a routine to embed audio files during the export routine but that wasn't in the scope of this issue so I'm content to merge in and mark this as completed.
