### ISSUE TITLE
change the "Part" to "Chapter" on TOC of Ebook.

### ISSUE THREAD

**Issue by jing-library** [pressbooks/pressbooks#1184]
### Prerequisites

_Check the boxes below by changing them from `[ ]` to `[x]`._

* [x] Can you reproduce the behavior you wish to address with [all other plugins deactivated](http://codex.wordpress.org/Multisite_Network_Administration#Plugins)?
* [x] Are you running the [latest version of Pressbooks](http://github.com/pressbooks/pressbooks/releases/latest/) and the [latest version of WordPress](http://codex.wordpress.org/Upgrading_WordPress)?
* [x] Are you experiencing this issue with one of our built-in root or book themes?
* [x] Did you [perform a cursory search](https://github.com/issues?q=+is%3Aissue+repo%3Apressbooks%2Fpressbooks) to see if your bug or enhancement is already listed?

### Description
This is not a bug reporting. 

I was asked to change the "Part" to "Chapter" on both PDF and eBook.
For PDF, I made the following changes, and it works.
          /*change Part to Chapters on TOC and main body*/
          #toc .part a::before {
            content: 'Chapter ' counter(part,upper-roman) ".\A0"; }
          h3.part-number::before {
            content: 'Chapter '; }

For eBook, I added the following code to change the title, but I could not find a way to change the TOC page. Is there a variable I may use to change "Part" to "Chapter" in the TOC section of Ebook format?
          div.part-title-wrap > h3.part-number:before {
            content: 'Chapter '; }

Thank you in advance,
Jing
[Description of the bug or feature]

### Steps to Reproduce

1. Export PDF and ePub

**Expected behavior:** [What you expected to happen]
I want to replace Part with Chapter on both PDF and Ebook versions

**Actual behavior:** [What actually happened]
The TOC section of Ebook version does not change 

### System Information
_Replace this section with the contents of the Diagnostics page, available at `https://<yourdomain.tld>/<yourbook>/wp-admin/options.php?page=pressbooks_diagnostics` or via the Diagnostics link in the admin footer. If you are using Pressbooks < 3.9.4, you will have to enter the following information manually:_

I am using the cloud version of Pressbooks at https://otn.pressbooks.pub. 
Pressbooks: [N/A]
WordPress: [N/A]
PHP: [N/A]

_You can get the version of Pressbooks from the readme.txt file in the Pressbooks plugin (usually located at `https://<yourdomain.tld>/wp-content/plugins/pressbooks/readme.txt`) and the version of WordPress from the readme.html file in the WordPress root directory (usually located at `https://<yourdomain.tld>/readme.html`). You can usually get your PHP version from your web host, or by using the [`phpversion()`](http://php.net/manual/en/function.phpversion.php) function._

**Comment by greatislander** [comment]
Hi @jing-library, unfortunately the EPUB TOC label cannot currently be changed via CSS as it is inserted into markup during the export process in PHP (not supplied via CSS). This is something we'd consider changing but it is not currently on our roadmap. I'm going to close this issue, but if you'd like us to prioritize this feature I would request that you open an issue on our ideas repo (https://github.com/pressbooks/ideas) outlining the use case for the feature. Thank you!
