### ISSUE TITLE
Simple quotation marks automatically replaced in web e-book

### ISSUE THREAD

**Issue by martakule** [pressbooks/pressbooks#1192]
### Prerequisites

_Check the boxes below by changing them from `[ ]` to `[x]`._

* [ ] Can you reproduce the behavior you wish to address with [all other plugins deactivated](http://codex.wordpress.org/Multisite_Network_Administration#Plugins)?
* [x] Are you running the [latest version of Pressbooks](http://github.com/pressbooks/pressbooks/releases/latest/) and the [latest version of WordPress](http://codex.wordpress.org/Upgrading_WordPress)?
* [x] Are you experiencing this issue with one of our built-in root or book themes?
* [x] Did you [perform a cursory search](https://github.com/issues?q=+is%3Aissue+repo%3Apressbooks%2Fpressbooks) to see if your bug or enhancement is already listed?

### Description

When I type in simple quotes after an equal sign in the visual editor, the web e-book gets rendered with those replaced with a right curly quote and a double prime for numbers and two right curly quotes for other characters:
`tabindex="0" tabindex="x"` becomes `tabindex=”0″ tabindex=”x”`

### Steps to Reproduce

1. Type `tabindex="0"` in visual editor
2. View chapter

**Expected behavior:** I expect actual simple quotes to show. Better yet, an option for inline code formatting. The tag <pre></pre> displays as block, and the editor clears out any attempts to set style to display:inline.

**Actual behavior:** `tabindex=”0″ tabindex=”x”` No option for inline code formatting.

### System Information

I don't have admin access. http://pressbooks.library.ryerson.ca/

**Comment by greatislander** [comment]
Hi @martakule, I tried your steps to reproduce in a standard WordPress editor and the same thing happened. This isn't a bug with Pressbooks. If you want to enter special characters without it being modified (WordPress tries to turn things into smart quotes, which is the issue for you) you should enclose it in a `<code>` tag:

<a href="https://cl.ly/412l3z3e0M1W" target="_blank"><img src="https://dzwonsemrish7.cloudfront.net/items/300x212M2G0H2q3i3t2C/Screen%20Recording%202018-04-17%20at%2003.54%20PM.gif" style="display: block;height: auto;width: 100%;"/></a>

**Comment by greatislander** [comment]
(Note that you will need to use the text editor.)

**Comment by martakule** [comment]
That was so simple! Thank you.
