### ISSUE TITLE
SVG's in ePub 2.0

### ISSUE THREAD

**Issue by lukaiser** [pressbooks/pressbooks#1218]
Hi guys,

I have the following case:
In some books, users are using SVG's, well knowing that not all ePub-Reader support them.
If you export an ePub, the img tag gets included, but the image file is not added to the svg bundle.
When viewing the ePub in a reader, that supports SVG, they show up but only if the reader has a internet connection.

That is not really understandable for a user.
I see two options:

1. Add the SVG's to the bundle.
2. Remove the image tags from the ePub html and alert the user.

I would go with option one as more and more readers do support svg's.

Whats your take on that?
I would implement it if you are okay with it.

**Comment by connerbw** [comment]
Epub2 files are used to build mobi files. Many Pressbooks users care more about the mobi files than they do the epub2 files. If you implement it then the resulting mobi files will need to work.

**Comment by lukaiser** [comment]
I am still working on this. It is just moving slower then I thought.
