### ISSUE TITLE
Cloning content with <pre> tag removes line breaks

### ISSUE THREAD

**Issue by greatislander** [pressbooks/pressbooks#1225]
### Prerequisites

* [x] Can you reproduce the behavior you wish to address with [all other plugins deactivated](http://codex.wordpress.org/Multisite_Network_Administration#Plugins)?
* [x] Are you running the [latest version of Pressbooks](http://github.com/pressbooks/pressbooks/releases/latest/) and the [latest version of WordPress](http://codex.wordpress.org/Upgrading_WordPress)?
* [x] Are you experiencing this issue with one of our built-in root or book themes?
* [x] Did you [perform a cursory search](https://github.com/issues?q=+is%3Aissue+repo%3Apressbooks%2Fpressbooks) to see if your bug or enhancement is already listed?

### Description

Line breaks are stripped from within `<pre>` tags by the clone tool.

### Steps to Reproduce

1. Create a book with the following content in a chapter.
```
<pre>Line one
Line two
Line three</pre>
```
2. Clone the book.
3. View the cloned chapter.

**Expected behavior:** The source and cloned chapters are identical.

**Actual behavior:** Line breaks have been stripped from the cloned chapter:

```
<pre>Line oneLine twoLine three</pre>
```

### System Information

Pressbooks: 5.3.3

**Comment by connerbw** [comment]
Similar issue:
https://discourse.pressbooks.org/t/import-xml-stripping-embedded-content/423/17
