### ISSUE TITLE
Unable to open a "Part" that contains text via the table of contents when using Firefox

### ISSUE THREAD

**Issue by josiegray** [pressbooks/pressbooks#1228]
### Prerequisites

* [ ] Can you reproduce the behavior you wish to address with [all other plugins deactivated](http://codex.wordpress.org/Multisite_Network_Administration#Plugins)?
* [ ] Are you running the [latest version of Pressbooks](http://github.com/pressbooks/pressbooks/releases/latest/) and the [latest version of WordPress](http://codex.wordpress.org/Upgrading_WordPress)?
* [ ] Are you experiencing this issue with one of our built-in root or book themes?
* [x] Did you [perform a cursory search](https://github.com/issues?q=+is%3Aissue+repo%3Apressbooks%2Fpressbooks) to see if your bug or enhancement is already listed?

### Description

A user has identified that the web-book table of contents behaves differently in different browsers: 

In Chrome and Microsoft Edge, when you click on a "Part" in the table of contents (See "What is Technical Communication?" in image below) and the part contains text, the browser opens to the Part, even if there are individual pages within that part, which is the desired behaviour. In Firefox, that doesn't happen. In Firefox, parts that contain text will only open if the part does not contain pages. If the part does contain pages, the drop-down menu will expand to display the individual pages within the part, but will not display the text content of the part itself.

### Expected behaviour

In all browsers: when a part contains text (whether or not it also contains individual pages), a user should be able to navigate directly to the part by clicking on the name of the part in the table of contents. As it is now, this is only the case in Chrome and Microsoft Edge, but not in Firefox.

### Actual behaviour

In Firefox, when you click on a "Part" in the table of contents from the book's home page, it will display the pages within that part, but it will not open the part itself. It will only open to the part if there are no pages within the part. Chrome and Microsoft Edge behave as expected.

### Steps to reproduce

<img width="488" alt="toc" src="https://user-images.githubusercontent.com/37554861/41316736-002317ca-6e48-11e8-9988-a2b65f0f25b5.PNG">

1. Open a window in Firefox. 
2. Go to https://pressbooks.bccampus.ca/technicalwriting/ 
3. Scroll down to the table of contents. 
4. Click one of the parts, e.g. "What is technical communication"
5. The part will expand to show the pages it contains, but it will not open up the part itself.

#### Book Info

Book ID: 296
Book URL: https://pressbooks.bccampus.ca/technicalwriting/
Book Privacy: Public

#### Browser

Platform: Windows
Browser Name: Firefox
Browser Version: 60.0
User Agent String: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:60.0) Gecko/20100101 Firefox/60.0

#### WordPress Configuration

Network URL: http://pressbooks.bccampus.ca/
Network Type: Subdirectory
Version: 4.9.5
Language: en_US
WP_ENV: Not set
WP_DEBUG: Enabled
Memory Limit: 64M

#### Pressbooks Configuration

Version: 5.2.1
Book Theme: Open Textbooks
Book Theme Version: 2.1.2
Root Theme: Aldine
Root Theme Version: 1.2.1

#### Pressbooks Dependencies

Epubcheck: Installed
Kindlegen: Installed
xmllint: Installed
PrinceXML: Installed
Saxon-HE: Installed

#### Must-Use Plugins

hm-autoloader.php: n/a

#### Network Active Plugins

BC Post-Secondary Validator: 1.0.0
CC Export for Pressbooks: 0.2.1
f5 Force SSL: 1.0.0
iThemes Security: 6.9.2
Openstax Import for Pressbooks: 1.2.0
Pressbooks: 5.2.1
Pressbooks Stats: 1.4.0
Textbooks for Pressbooks: 4.0.3
WP-Piwik: 1.0.19

#### Inactive Plugins

Akismet Anti-Spam: 4.0.3
H5P: 1.10.1
mPDF for Pressbooks: 3.1.1
WP QuickLaTeX: 3.8.4

#### Server Configuration

PHP Version: 7.1.17
MySQL Version: 5.5.5
Webserver Info: Apache

#### PHP Configuration

Safe Mode: Disabled
Memory Limit: 512M
Upload Max Size: 500M
Post Max Size: 500M
Upload Max Filesize: 500M
Time Limit: 60
Max Input Vars: 1000
URL-aware fopen: On (1)
Display Errors: N/A

#### PHP Extensions

OPcache: Disabled
XDebug: Disabled
cURL: Supported
cURL Version: 7.19.7
imagick: Installed
xsl: Installed

**Comment by greatislander** [comment]
Hi @josiegray, this is a known issue—thanks for opening! It belongs in https://github.com/pressbooks/pressbooks-book, though. Would you mind moving it there?
