### ISSUE TITLE
The Pressbooks plugin is causing errors.

### ISSUE THREAD

**Issue by kumar8k** [pressbooks/pressbooks#1229]
After migrating the Pressbook to other domain I am getting this error:

> The Pressbooks plugin is inactive, but you have active plugins that require Pressbooks. This is causing errors. Please go to the Plugins page, and activate Pressbooks.

Now I am not able to log in the admin panel, nor able to visit the site. It keeps showing this error. No other plugins have been installed.

**Comment by greatislander** [comment]
Please open an issue on https://discourse.pressbooks.org. GitHub is for bugs/feature requests, not installation and configuration issues. Thanks!
