### ISSUE TITLE
Add DocRaptor export module to core

### ISSUE THREAD

**Issue by greatislander** [pressbooks/pressbooks#1238]
### Prerequisites

* [x] Can you reproduce the behavior you wish to address with [all other plugins deactivated](http://codex.wordpress.org/Multisite_Network_Administration#Plugins)?
* [x] Are you running the [latest version of Pressbooks](http://github.com/pressbooks/pressbooks/releases/latest/) and the [latest version of WordPress](http://codex.wordpress.org/Upgrading_WordPress)?
* [x] Are you experiencing this issue with one of our built-in root or book themes?
* [x] Did you [perform a cursory search](https://github.com/issues?q=+is%3Aissue+repo%3Apressbooks%2Fpressbooks) to see if your bug or enhancement is already listed?

### Description

The [DocRaptor for Pressbooks](https://github.com/pressbooks/pressbooks-docraptor) export module should be added to core, and enabled as a drop-in replacement for Prince PDF when configured properly.

### Steps to Reproduce

Not applicable.

### System Information

Pressbooks: 5.4.0-dev

**Comment by johnpeterm** [comment]
How to configure the Docraptor API in the core module

**Comment by greatislander** [comment]
@johnpeterm Did you check https://docs.pressbooks.org/installation? Looks like you didn't.

![screen shot 2018-08-22 at 11 47 53 am](https://user-images.githubusercontent.com/605361/44470937-41910000-a601-11e8-859f-dfc2e27bec79.png)

**Comment by johnpeterm** [comment]
Thank you @greatislander ....appreciate very much
