### ISSUE TITLE
User Activation Keys plugin

### ISSUE THREAD

**Issue by hughmcguire** [pressbooks/pressbooks#124]
we should include the User Activation Keys plugin ... in pressbooks? https://wordpress.org/plugins/user-activation-keys/

(it's installed on Pressbooks.com).

certainly need it for client installs -- otherwise usernames & emails can get "stuck"  in the bd as unactivated (but reserved) & there is no clean mechanism to force activation for the network admin.

**Comment by greatislander** [comment]
I'm thinking we won't incorporate this into the core plugin as it addresses a general problem with Wordpress networks that may or may not be relevant to self-hosted Pressbooks users. However we may want to include this plugin in documentation for network administrators so they know that it's available and potentially helpful.

**Comment by hughmcguire** [comment]
agreed.
