### ISSUE TITLE
Travis CI Tests failing in PHP:nightly job

### ISSUE THREAD

**Issue by connerbw** [pressbooks/pressbooks#1241]
### Prerequisites

* [X] Can you reproduce the behavior you wish to address with [all other plugins deactivated](http://codex.wordpress.org/Multisite_Network_Administration#Plugins)?
* [X] Are you running the [latest version of Pressbooks](http://github.com/pressbooks/pressbooks/releases/latest/) and the [latest version of WordPress](http://codex.wordpress.org/Upgrading_WordPress)?
* [X] Are you experiencing this issue with one of our built-in root or book themes?
* [X] Did you [perform a cursory search](https://github.com/issues?q=+is%3Aissue+repo%3Apressbooks%2Fpressbooks) to see if your bug or enhancement is already listed?

### Description
Travis CI Tests failing in PHP:nighly job with errors like: `compact(): Undefined variable: groupby` because:

![image](https://user-images.githubusercontent.com/812192/41755063-6e566ec4-75a3-11e8-81b3-cb0a0c13f6ff.png)

@see https://core.trac.wordpress.org/ticket/44416

**Comment by greatislander** [comment]
Fixed in #1513.
