### ISSUE TITLE
Creating a new book requires Clarke to be installed

### ISSUE THREAD

**Issue by thomasdumm** [pressbooks/pressbooks#1251]
### Prerequisites

* [x] Can you reproduce the behavior you wish to address with [all other plugins deactivated](http://codex.wordpress.org/Multisite_Network_Administration#Plugins)?
* [x] Are you running the [latest version of Pressbooks](http://github.com/pressbooks/pressbooks/releases/latest/) and the [latest version of WordPress](http://codex.wordpress.org/Upgrading_WordPress)?
* [x] Are you experiencing this issue with one of our built-in root or book themes?
* [x] Did you [perform a cursory search](https://github.com/issues?q=+is%3Aissue+repo%3Apressbooks%2Fpressbooks) to see if your bug or enhancement is already listed?

### Description
If I create a new book with only McLuhan installed I get the message.

_Your theme, pressbooks-clarke, is not installed. Please visit GitHub for installation instructions._

I thought the new default theme is McLuhan.

#### Root Blog Info

Root Blog ID: 1
Root Blog URL: http://localhost/wordpress/

#### Browser

Platform: OS X
Browser Name: Firefox
Browser Version: 61.0
User Agent String: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:61.0) Gecko/20100101 Firefox/61.0

#### WordPress Configuration

Network URL: http://localhost/wordpress/
Network Type: Subdirectory
Version: 4.9.6
Language: en_US
WP_ENV: developer
WP_DEBUG: Enabled
Memory Limit: 64M

#### Pressbooks Configuration

Version: 5.4.0
Root Theme: Aldine
Root Theme Version: 1.4.0

#### Pressbooks Dependencies

Epubcheck: Installed
Kindlegen: Installed
xmllint: Installed
PrinceXML: Not Installed
Saxon-HE: Installed

#### Must-Use Plugins

hm-autoloader.php: n/a

#### Network Active Plugins

Hypothesis: 0.5.0
Pressbooks: 5.4.0

#### Server Configuration

PHP Version: 7.2.1
MySQL Version: 5.6.38
Webserver Info: Apache/2.2.34 (Unix) mod_wsgi/3.5 Python/2.7.13 PHP/7.2.1 mod_ssl/2.2.34 OpenSSL/1.0.2j DAV/2 mod_fastcgi/2.4.6 mod_perl/2.0.9 Perl/v5.24.0

#### PHP Configuration

Safe Mode: Disabled
Memory Limit: 256M
Upload Max Size: 32M
Post Max Size: 8M
Upload Max Filesize: 32M
Time Limit: 30
Max Input Vars: 1000
URL-aware fopen: On (1)
Display Errors: On (1)

#### PHP Extensions

OPcache: Disabled
XDebug: Disabled
cURL: Supported
cURL Version: 7.52.1
imagick: Not Installed
xsl: Installed

**Comment by greatislander** [comment]
Is this a fresh install? I created a fresh install and could not reproduce.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by thomasdumm** [comment]
no, an existing install where I deleted Carke

**Comment by greatislander** [comment]
Was Clarke used for any books on that network before you deleted it?

**Comment by thomasdumm** [comment]
yes

**Comment by greatislander** [comment]
So, the error you are getting is probably due to you having deleted a theme that was required by an existing book. This is not a bug.
