### ISSUE TITLE
Cloning, import, and export operations should display progress

### ISSUE THREAD

**Issue by greatislander** [pressbooks/pressbooks#1282]
### Feature Description

Currently cloning, import, and exports happen as a form submission. They should be run via AJAX requests and should display progress on the clone/import/export page.

### Feature Use Case

This will provide a better UX for these operations and provide realtime feedback showing which steps are taking the longest (e.g. downloading media files).

### Other Notes

Not applicable.

### System Information

Pressbooks: 5.4.1

**Comment by connerbw** [comment]
WIP: https://github.com/pressbooks/pressbooks/tree/cloning-with-status-bar
