### ISSUE TITLE
Suppress “Try Gutenberg” callout in WordPress 4.9.8

### ISSUE THREAD

**Issue by greatislander** [pressbooks/pressbooks#1296]
### Prerequisites

* [x] Can you reproduce the behavior you wish to address with [all other plugins deactivated](http://codex.wordpress.org/Multisite_Network_Administration#Plugins)?
* [x] Are you running the [latest version of Pressbooks](http://github.com/pressbooks/pressbooks/releases/latest/) and the [latest version of WordPress](http://codex.wordpress.org/Upgrading_WordPress)?
* [x] Are you experiencing this issue with one of our built-in root or book themes?
* [x] Did you [perform a cursory search](https://github.com/issues?q=+is%3Aissue+repo%3Apressbooks%2Fpressbooks) to see if your bug or enhancement is already listed?

### Description

WordPress 4.9.8 will introduce a call-to-action encouraging users to try Gutenberg. We need to hide this for the time being. See:

- https://core.trac.wordpress.org/ticket/41316
- https://github.com/senlin/classic-editor-addon/blob/master/classic-editor-addon.php#L57

### Steps to Reproduce

1. Install WordPress 4.9.8-beta.2.

**Expected behavior:** I don't want to be prompted to install Gutenberg.

**Actual behavior:** I am prompted to install Gutenberg.

### System Information

Pressbooks: 5.5.0-dev
WordPress: 4.9.8-beta.2

**Comment by greatislander** [comment]
Maybe not needed? https://core.trac.wordpress.org/ticket/44680

**Comment by greatislander** [comment]
Not needed because @connerbw already did this in https://github.com/pressbooks/pressbooks/commit/2f4abf75bd795f15f8b56c6e5fc1dfe9e1bc4b2c 🙃

**Comment by connerbw** [comment]
Improved here: https://github.com/pressbooks/pressbooks/pull/1308
