### ISSUE TITLE
Private chapters are not displayed in the TOC if book is public and user is logged in

### ISSUE THREAD

**Issue by marcusschiesser** [pressbooks/pressbooks#130]
For public books we have the following display behaviour in the TOC:

1. Private chapters are not displayed if a user is not logged in 
2. Private chapters are not displayed if a user is logged in 

But as for private books chapters are displayed in the TOC (if a user is logged in), the expected behaviour for 2 would be that private chapters are displayed if a user is logged in

**Comment by greatislander** [comment]
Thanks for this, @marcusschiesser. I will investigate further.

**Comment by marcusschiesser** [comment]
the problem is not only in the TOC, but also if you view the book. It's not possible to go to these chapters with the previous/next chapter button

**Comment by greatislander** [comment]
@marcusschiesser I've fixed this issue in https://github.com/pressbooks/pressbooks/commit/8dbb0eced4b2bf9b47e95ea33cdc0727e54d5c70. Note that private chapters will not appear in overall chapter numbering scheme although they will now be visible for logged-in users.

**Comment by marcusschiesser** [comment]
Ok, the TOC is now displayed, for users with role 'Subscriber' or higher. But a user needs at least the role 'Editor' to view a chapter. My expectation would be to view a chapter already with 'Subscriber' rights (as it is the case with private books).
In my case, if I am clicking in the TOC at a private chapter, I get redirected to the root page of the site.
I tested this with two different books. I am using pressbooks 2.5
