### ISSUE TITLE
PHP Notice: Undefined index: license in attachments.php on line 252

### ISSUE THREAD

**Issue by connerbw** [pressbooks/pressbooks#1316]
### Prerequisites

* [X] Can you reproduce the behavior you wish to address with [all other plugins deactivated](http://codex.wordpress.org/Multisite_Network_Administration#Plugins)?
* [X] Are you running the [latest version of Pressbooks](http://github.com/pressbooks/pressbooks/releases/latest/) and the [latest version of WordPress](http://codex.wordpress.org/Upgrading_WordPress)?
* [X] Are you experiencing this issue with one of our built-in root or book themes?
* [X] Did you [perform a cursory search](https://github.com/issues?q=+is%3Aissue+repo%3Apressbooks%2Fpressbooks) to see if your bug or enhancement is already listed?

### Description

Notice: Undefined index: license in /srv/www/pressbooks.test/current/web/app/plugins/pressbooks/inc/shortcodes/attributions/class-attachments.php on line 252

### Steps to Reproduce

1.  Clone this book: https://jctestbook.textopress.com
2. Look at this chapter in clone: https://jctestbook.textopress.com/chapter/footnotes-and-media-attribution/

**Expected behavior:** Nothing 

**Actual behavior:** PHP Notice: Undefined index: license 

### Reason

```php
// license attribution
sprintf(
	'%1$s %2$s',
	$license_prefix,
	( isset( $attribution['license'] ) ) ?
		sprintf(
			'<a rel="license" href="%1$s">%2$s</a>',
			$licensing->getUrlForLicense( $attribution['license'] ),
			$supported[ $attribution['license'] ]['desc']
		) : $supported[ $attribution['license'] ]['desc']
)
```

Ie: 

`( isset( $attribution['license'] ) ) ? [...] :  $supported[ $attribution['license'] ]['desc']`

If `$attribution['license']` is not set, then `$supported[ $attribution['license'] ]['desc']` can't work.

@bdolor is the default supposed to be something like `$supported['all-rights-reserved']['desc']`? I'm having a hard time figuring out the default here. All the other code in the function has a default defined at the top. Not this one.

Help?

**Comment by greatislander** [comment]
@connerbw I haven't fixed this yet, it's on my list.
