### ISSUE TITLE
ODT export images

### ISSUE THREAD

**Issue by greatislander** [pressbooks/pressbooks#134]
Cover image & latex images need to be handled better/at all as specified [here](https://github.com/pressbooks/pressbooks/issues/104#issuecomment-101436907). (FYI @bdolor, haven't forgotten this.)

**Comment by hughmcguire** [comment]
this is high priority -- we have a deadline to deliver to BCcampus, end of June.

**Comment by greatislander** [comment]
Cover images are fixed now from my testing.

**Comment by greatislander** [comment]
In my testing the LaTex import is now fixed as well. Please let me know if you run into any issues.
