### ISSUE TITLE
Handle books with editors but no authors

### ISSUE THREAD

**Issue by crism** [pressbooks/pressbooks#1341]
### Feature Description

Now that Pressbooks has much better structured contributor support, a problem arises for edited monographs with no proper whole-work authors. PB will properly display all the contributors “below the fold,” in the “Metadata” section, but will only list the author(s) in the upper part of the page.

It should either be possible to have only editors listed as the primary work creators. Three possible approaches:

 1. Allow a selection of the “primary role”—contributors with that role would be listed in the top section, with all contributors listed properly in the “Metadata” section, as currently.
 1. Allow all authors to be removed, and fall back through other roles for primary creator display. (Currently, if all authors are removed, the book-owning user is reinserted as an author automatically.) If there are no authors but there are editors, list them in the upper section; if there are no editors, list the contributors; if no contributors, list the translators, etc.
 1. Allow an arbitrary “credits” line—free text that would override the generated default.

The last option is redundant and unstructured, but infinitely flexible. The first option keeps structure and some flexibility, though it doesn’t handle a case with _e.g._ editors and a translator desired as the primary creators.

### Feature Use Case

A scholarly monograph or textbook with contributions from multiple authors generally only gives the editors as the credits on the cover and title page. To publish such works in Pressbooks, we have to create a fake “author” with a name like “John Smith and Jane Doe, eds.,” which then messes up the properly-structured metadata in the lower section. It would be nice to be able to keep the structured data clean, but also have the desired display on the title page.

#### Root Blog Info

Root Blog ID: 1
Root Blog URL: https://iopn.library.illinois.edu/pressbooks/

#### Browser

Platform: Linux
Browser Name: Firefox
Browser Version: 61.0
User Agent String: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:61.0) Gecko/20100101 Firefox/61.0

#### WordPress Configuration

Network URL: http://iopn.library.illinois.edu/pressbooks/
Network Type: Subdirectory
Version: 4.9.8
Language: en_US
WP_ENV: Not set
WP_DEBUG: Disabled
Memory Limit: 64M

#### Pressbooks Configuration

Version: 5.4.7
Root Theme: Pressbooks Publisher
Root Theme Version: 3.1.4

#### Pressbooks Dependencies

Epubcheck: Installed
Kindlegen: Installed
xmllint: Installed
PrinceXML: Installed
Saxon-HE: Not Installed

#### Must-Use Plugins

hm-autoloader.php: n/a

#### Network Active Plugins

Google Analytics Dashboard for WP (GADWP): 5.3.5
H5P: 1.10.3
Hypothesis: 0.5.0
mPDF for Pressbooks: 3.2.1
Pressbooks: 5.4.7

#### Inactive Plugins

Akismet Anti-Spam: 4.0.8
Hello Dolly: 1.6

#### Server Configuration

PHP Version: 7.1.20
MySQL Version: 5.5.56
Webserver Info: Apache/2.4.6 (CentOS) OpenSSL/1.0.2k-fips mod_fcgid/2.3.9 PHP/7.1.20

#### PHP Configuration

Safe Mode: Disabled
Memory Limit: 256M
Upload Max Size: 12M
Post Max Size: 12M
Upload Max Filesize: 12M
Time Limit: 30
Max Input Vars: 1000
URL-aware fopen: On (1)
Display Errors: N/A

#### PHP Extensions

OPcache: Zend
XDebug: Disabled
cURL: Supported
cURL Version: 7.29.0
imagick: Not Installed
xsl: Installed
```

**Comment by crism** [comment]
I’ve mostly addressed (and will send a PR for) the override. The “forceful” addition of an author in `Pressbooks\Admin\Metaboxes::add_required_data()` is clearly intentional… How disastrous would it be to drop that? Is the author set initially once, somewhere else? [Partly this is a note for my own purposes, to come back and investigate that after implementing the credit override part.]

**Comment by greatislander** [comment]
Hi @crism, thanks for your work on this. We are going to discuss and we'll get back to you; I am not sure that option 3 is my preference as it leaves a gap in terms of how the book creator (in your use case, an editor or team of editors) is attributed in metadata (see: https://schema.org/Book).

**Comment by crism** [comment]
@greatislander, I get that, and I agree… we would love to be part of those conversations. This patch suffices for our current use, but it does feel inadequate for general metadata.

**Comment by crism** [comment]
Idea: 1) Designate primary role (editor, in this case). 2) Require primary role to be populated (as author is now). 3) Construct a default free-text credits line based on language and primary role. 4) Allow editing and/or override of credit line, used for display on title pages. 5) Use primary role for Creator when relevant.

**Comment by greatislander** [comment]
I've moved this to https://github.com/pressbooks/ideas/issues/134 so we can iterate on the concept a bit more, then will re-open issues here and at pressbooks/pressbooks-book when we have identified an implementation path.
