### ISSUE TITLE
If h1 has a class, it gets replaced with pressbooks section-header class during xhtml-export

### ISSUE THREAD

**Issue by thomasdumm** [pressbooks/pressbooks#1386]
### Prerequisites

* [x] Can you reproduce the behavior you wish to address with [all other plugins deactivated](http://codex.wordpress.org/Multisite_Network_Administration#Plugins)?
* [x] Are you running the [latest version of Pressbooks](http://github.com/pressbooks/pressbooks/releases/latest/) and the [latest version of WordPress](http://codex.wordpress.org/Upgrading_WordPress)?
* [x] Are you experiencing this issue with one of our built-in root or book themes?
* [x] Did you [perform a cursory search](https://github.com/issues?q=+is%3Aissue+repo%3Apressbooks%2Fpressbooks) to see if your bug or enhancement is already listed?

### Description

If h1 has a class or an id, it gets replaced with pressbooks section-header/chapter class and id during xhtml-export

### Steps to Reproduce

1. Insert h1
2. add class on h1
3. export xhtml
4. check class of h1 in xhtml file

**Expected behavior:** 
A css  class that is set in edit mode is preserved. Pressbooks section-header class is added to the existing class.
**Actual behavior:** 
A css class that is set in edit mode is replaced with section-header class.
#### Book Info

Book ID: 6
Book URL: http://pressbooks.delivros.ch/demo/
Book Privacy: Public

#### Browser

Platform: OS X
Browser Name: Firefox
Browser Version: 62.0
User Agent String: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:62.0) Gecko/20100101 Firefox/62.0

#### WordPress Configuration

Network URL: http://pressbooks.delivros.ch/
Network Type: Subdirectory
Version: 4.9.8
Language: en_US
WP_ENV: development
WP_DEBUG: Disabled
Memory Limit: 64M

#### Pressbooks Configuration

Version: 5.5.2
Book Theme: pressbooks-kssg
Book Theme Version: 1.0
Root Theme: Aldine
Root Theme Version: 1.5.0

#### Pressbooks Dependencies

Epubcheck: Installed
Kindlegen: Installed
xmllint: Installed
PrinceXML: Installed
Saxon-HE: Installed

#### Must-Use Plugins

hm-autoloader.php: n/a

#### Network Active Plugins

Enable Media Replace: 3.2.7
H5P: 1.10.3
Hypothesis: 0.5.0
Pressbooks: 5.5.2
Pressbooks LTI Provider: 1.1.1
Re-send Welcome Email: 0.4.2
WP Mail SMTP: 1.3.3
WP QuickLaTeX: 3.8.5

#### Book Active Plugins

Enable Media Replace: 3.2.7
H5P: 1.10.3
Hypothesis: 0.5.0
Pressbooks: 5.5.2
Pressbooks LTI Provider: 1.1.1
Re-send Welcome Email: 0.4.2
WP Mail SMTP: 1.3.3
WP QuickLaTeX: 3.8.5

#### Server Configuration

PHP Version: 7.2.9-1+ubuntu16.04.1+deb.sury.org+1
MySQL Version: 5.7.23
Webserver Info: Apache/2.4.18 (Ubuntu)

#### PHP Configuration

Safe Mode: Disabled
Memory Limit: 256M
Upload Max Size: 128M
Post Max Size: 128M
Upload Max Filesize: 128M
Time Limit: 90
Max Input Vars: 1000
URL-aware fopen: On (1)
Display Errors: N/A

#### PHP Extensions

OPcache: Zend
XDebug: Disabled
cURL: Supported
cURL Version: 7.47.0
imagick: Not Installed
xsl: Installed

**Comment by connerbw** [comment]
Does this happens when "Enable two-level table of contents (displays headings under chapter titles)" is **off**? My feeling is no but I would like some more information.

![image](https://user-images.githubusercontent.com/812192/46547817-29b4c900-c89b-11e8-9ee2-6d3b4afcb8fe.png)

**Comment by thomasdumm** [comment]
You are right! The described problem only arises if the option "Two-Level TOC" is selected.

**Comment by connerbw** [comment]
I can fix for `class` (have more than one) but not for `id`. 

The code, as is, needs to take over the ID to make the Two-Level TOC. Refactoring this is not something we can do lightly right now Rather it would come later when we look at [multi level sections](https://oreillymedia.github.io/HTMLBook/#_sections).

For now i'll, in addition to keeping what's in the class attribute, i'll move the old ID into the class attribute, then prepend our `section-header` class.

Hope that's OK?

**Comment by thomasdumm** [comment]
perfect!
