### ISSUE TITLE
Simplify and improve editor experience for glossary terms

### ISSUE THREAD

**Issue by greatislander** [pressbooks/pressbooks#1424]
### Feature Description

A few changes are needed for the initial release of the glossary tool:

- [x] The glossary terms editor should not support rich text, shortcodes, etc. To communicate this, the visual editor should be disabled and a line of text should be added [above the editor](https://developer.wordpress.org/reference/hooks/edit_form_after_title/) to clarify this, reading: "HTML and shortcodes are not supported in glossary terms."
- [x] The glossary terms editor should have a simplified post status metabox and a visibility toggle (which simply switches post status between `publish` and `private`). It's important to verify that tooltips will still appear for `private` glossary terms, and that `private` glossary terms will not appear in the shortcode-generated list.
- [x] The 'View Glossary Terms' link should be removed from the glossary terms table admin bar, and the 'View Glossary Term' link should be removed from the glossary terms editor.
- [x] The glossary terms table should have the Quick Edit and View action links [removed](https://frique.me/blog/how-to-remove-wordpress-quick-edit/).
- [x] The glossary terms table should have the date filter removed.

### Feature Use Case

Not applicable.

### Mockups

![Status & Visibility](https://user-images.githubusercontent.com/605361/47568332-301cea80-d907-11e8-8e60-701345b000f3.png)

![Glossary Terms](https://user-images.githubusercontent.com/605361/47568674-1a5bf500-d908-11e8-84f9-a7c0833b1aa4.png)

![View Link](https://user-images.githubusercontent.com/605361/47568791-6ad35280-d908-11e8-9ac1-b2cfbb372aec.png)

### Other Notes

Not applicable.

### System Information

Pressbooks: 5.6.0-dev

**Comment by connerbw** [comment]
In progress: https://github.com/pressbooks/pressbooks/tree/glossary-ux
