### ISSUE TITLE
H1 headings are not appearing the TOC when two-level TOC is turned on

### ISSUE THREAD

**Issue by josieg** [pressbooks/pressbooks#1425]
### Prerequisites

* [x] Can you reproduce the behavior you wish to address with [all other plugins deactivated](http://codex.wordpress.org/Multisite_Network_Administration#Plugins)?
* [x] Are you running the [latest version of Pressbooks](http://github.com/pressbooks/pressbooks/releases/latest/) and the [latest version of WordPress](http://codex.wordpress.org/Upgrading_WordPress)?
* [x] Are you experiencing this issue with one of our built-in root or book themes?
* [x] Did you [perform a cursory search](https://github.com/issues?q=+is%3Aissue+repo%3Apressbooks%2Fpressbooks) to see if your bug or enhancement is already listed?

### Description

I have two-level TOC enabled in global theme options but my h1 headings are not appearing in my table of contents. This appears in the webbook and the PDF (I didn't test the other files). I tested this on both the Open Textbook Theme and McLuhan and found the same thing. 

### Steps to Reproduce

1. Add a chapter with multiple headings set as h1.
2. Turn on "Enable two-level table of contents (displays headings under chapter titles)" in Global Theme Options. 
3. Look at the TOC for the webbook and the PDF. Those H1 headings will not be listed. 

**Expected behavior:** 
I expect that when the two-level TOC option is activated, that all h1 headings in my content will appear in the table of contents of all formats. 

**Actual behavior:** 
h1 headings do not appear in the TOC when the two-level TOC option is activated

#### Book Info

Book ID: 214
Book URL: https://opentextbc.ca/openedinfo/
Book Privacy: Public

#### Browser

Platform: Windows
Browser Name: Chrome
Browser Version: 69.0.3497.100
User Agent String: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36

#### WordPress Configuration

Network URL: http://opentextbc.ca/
Network Type: Subdirectory
Version: 4.9.8
Language: en_US
WP_ENV: Not set
WP_DEBUG: Disabled
Memory Limit: 64M

#### Pressbooks Configuration

Version: 5.5.3
Book Theme: Open Textbooks
Book Theme Version: 2.1.4
Root Theme: Aldine
Root Theme Version: 1.5.0

#### Pressbooks Dependencies

Epubcheck: Installed
Kindlegen: Installed
xmllint: Installed
PrinceXML: Installed
Saxon-HE: Installed

#### Must-Use Plugins

hm-autoloader.php: n/a

#### Network Active Plugins

Akismet Anti-Spam: 4.0.8
Better WordPress Google XML Sitemaps: 1.4.1
CC Export for Pressbooks: 0.2.5
f5 Force SSL: 1.0.0
iThemes Security: 7.2.0
Openstax Import for Pressbooks: 1.3.0
Pressbooks: 5.5.3
Pressbooks Stats: 1.4.0
Textbooks for Pressbooks: 4.2.1
User Activation Keys: 4.6
WP-Piwik: 1.0.19

#### Book Active Plugins

Akismet Anti-Spam: 4.0.8
Better WordPress Google XML Sitemaps: 1.4.1
CC Export for Pressbooks: 0.2.5
f5 Force SSL: 1.0.0
iThemes Security: 7.2.0
Openstax Import for Pressbooks: 1.3.0
Pressbooks: 5.5.3
Pressbooks Stats: 1.4.0
Textbooks for Pressbooks: 4.2.1
User Activation Keys: 4.6
WP-Piwik: 1.0.19

#### Inactive Plugins

H5P: 1.10.3
Hypothesis: 0.5.0
mPDF for Pressbooks: 3.2.2
Relevanssi: 4.1.0.1
WP QuickLaTeX: 3.8.5

#### Server Configuration

PHP Version: 7.1.22
MySQL Version: 5.5.5
Webserver Info: Apache

#### PHP Configuration

Safe Mode: Disabled
Memory Limit: 512M
Upload Max Size: 500M
Post Max Size: 500M
Upload Max Filesize: 500M
Time Limit: 60
Max Input Vars: 1000
URL-aware fopen: On (1)
Display Errors: N/A

#### PHP Extensions

OPcache: Disabled
XDebug: Disabled
cURL: Supported
cURL Version: 7.19.7
imagick: Installed
xsl: Installed

**Comment by greatislander** [comment]
Hi @josieg, thanks for reporting this. I created a new book and could not reproduce. Can you try navigating to **Organize** and un-checking, then re-checking, the **Export** checkbox for any chapter, then try exporting/viewing the webbook TOC again? Thanks!

**Comment by greatislander** [comment]
That's puzzling. Do you have a development environment you can use to test with just Pressbooks and McLuhan enabled (to remove any other potential conflicts)?

**Comment by greatislander** [comment]
@josieg @bdolor Any more info about this?

**Comment by josieg** [comment]
I don't think I know what I'm doing to be able to test in our development site and Brad is likely busy with other sprints at the moment - he may even be off today. I will follow up when I get the chance to speak with him. Thanks!

**Comment by greatislander** [comment]
Hi @josieg, as we haven't heard any further info and we can't reproduce the issue, I'm going to close this for now. Please feel free to re-open if it is persisting.
