### ISSUE TITLE
h3 is always centered 

### ISSUE THREAD

**Issue by BakingSoda** [pressbooks/pressbooks#145]
https://github.com/pressbooks/pressbooks/blob/dev/themes-book/pressbooks-book/style.css#L130
@bdolor 
![screen shot 2015-06-12 at 9 33 22 am](https://cloud.githubusercontent.com/assets/10442086/8134709/2935119e-10e6-11e5-9b5d-59da3e27d186.png)

**Comment by bdolor** [comment]
@BakingSoda - this is a modification that can be handled at the Open Textbook theme level. It may be something that PB put in the parent theme intentionally. Could you please open a ticket on the PBT project? https://github.com/bccampus/pressbooks-textbook/issues
