### ISSUE TITLE
Chapters imported from MS Word include <a id="_GoBack"></a> at end of each chapter

### ISSUE THREAD

**Issue by mcgratay** [pressbooks/pressbooks#1473]
### Prerequisites

* [x] Can you reproduce the behavior you wish to address with [all other plugins deactivated](http://codex.wordpress.org/Multisite_Network_Administration#Plugins)?
* [x] Are you running the [latest version of Pressbooks](http://github.com/pressbooks/pressbooks/releases/latest/) and the [latest version of WordPress](http://codex.wordpress.org/Upgrading_WordPress)?
* [x] Are you experiencing this issue with one of our built-in root or book themes?
* [x] Did you [perform a cursory search](https://github.com/issues?q=+is%3Aissue+repo%3Apressbooks%2Fpressbooks) to see if your bug or enhancement is already listed?

### Description

Chapters imported from MS Word include the tag <a id="_GoBack"></a> at the end of the chapter in the text editor. The link causes an anchor to appear at the end of the chapter
![screen shot 2018-11-22 at 3 59 18 pm](https://user-images.githubusercontent.com/39064028/48921715-ab72ad00-ee6f-11e8-939d-cc00f369c552.png)

Example: https://open.baypath.edu/admintestbook/chapter/go-back-test/
Doc: 
[GoBack.docx](https://github.com/pressbooks/pressbooks/files/2609317/GoBack.docx)

### Steps to Reproduce

1. Import any document from MS Word (Tools > Import)
2. Go to the chapter editor for the imported chapter and switch to the text editor view to see the tag
3. Switch back to the visual editor to see the anchor 

**Expected behavior:** Chapters imported from Word do not contain any links or anchors not in the original Word document

**Actual behavior:** All imported chapters include <a id="_GoBack"></a> at the end of the chapter

#### Book Info

Book ID: 7
Book URL: https://open.baypath.edu/admintestbook/
Book Privacy: Public

#### Browser

Platform: OS X
Browser Name: Safari
Browser Version: 12.0.1
User Agent String: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.0.1 Safari/605.1.15

#### WordPress Configuration

Network URL: http://open.baypath.edu/
Network Type: Subdirectory
Version: 4.9.8
Language: en_US
WP_ENV: production
WP_DEBUG: Disabled
Memory Limit: 64M

#### Pressbooks Configuration

Version: 5.5.6
Book Theme: McLuhan
Book Theme Version: 2.5.2
Root Theme: Aldine
Root Theme Version: 1.5.0

#### Pressbooks Dependencies

Epubcheck: Installed
Kindlegen: Installed
xmllint: Installed
PrinceXML: Not Installed
Saxon-HE: Installed

#### Must-Use Plugins

Bedrock Autoloader: 1.0.0
hm-autoloader.php: n/a
telemetry.php: n/a

#### Network Active Plugins

Hypothesis: 0.5.0
Pressbooks: 5.5.6
Pressbooks BISAC: 2.0.0
Pressbooks LTI Provider: 1.1.2
Pressbooks Stats: 1.6.2
Pressbooks Whitelabel: 1.3.0
Redis Object Cache: 1.3.9
User Activation Keys: 4.6
WP Fail2Ban Redux: 0.5.0

#### Book Active Plugins

Hypothesis: 0.5.0
Pressbooks: 5.5.6
Pressbooks BISAC: 2.0.0
Pressbooks LTI Provider: 1.1.2
Pressbooks Stats: 1.6.2
Pressbooks Whitelabel: 1.3.0
Redis Object Cache: 1.3.9
User Activation Keys: 4.6
WP Fail2Ban Redux: 0.5.0

#### Inactive Plugins

Akismet Anti-Spam: 4.1
H5P: 1.11.2
Parsedown Party: 1.1.1
TablePress: 1.9.1
WP QuickLaTeX: 3.8.5

#### Server Configuration

PHP Version: 7.1.23-3+ubuntu16.04.1+deb.sury.org+1
MySQL Version: 5.5.5
Webserver Info: nginx/1.13.6

#### PHP Configuration

Safe Mode: Disabled
Memory Limit: 256M
Upload Max Size: 25M
Post Max Size: 25M
Upload Max Filesize: 25M
Time Limit: 240
Max Input Vars: 1000
URL-aware fopen: On (1)
Display Errors: N/A

#### PHP Extensions

OPcache: Zend
XDebug: Disabled
cURL: Supported
cURL Version: 7.47.0
imagick: Not Installed
xsl: Installed

**Comment by connerbw** [comment]
Docx files are  zip files with (mostly) XML in them.

When I do right click, unzip `GoBack.docx`, and look at `word/document.xml`, I see (snippet):

```xml
<w:t xml:space="preserve">This is a word document </w:t></w:r>
<w:bookmarkStart w:id="0" w:name="_GoBack"/><w:bookmarkEnd w:id="0"/>
```

`bookmarkStart` + `_GoBack` +  `bookmarkEnd`  is in there. This isn't a bug.

Thinking about this some more, I made my own docx file, using the Bookmark feature in LibreOffice:

```xml
<w:t xml:space="preserve">This is a </w:t></w:r>
<w:bookmarkStart w:id="0" w:name="DacTest1"/><w:r><w:rPr><w:lang w:val="en-US"/></w:rPr><w:t>word</w:t></w:r><w:bookmarkEnd w:id="0"/>
<w:r><w:rPr><w:lang w:val="en-US"/></w:rPr><w:t xml:space="preserve"> document </w:t></w:r>
<w:bookmarkStart w:id="1" w:name="_GoBack2"/><w:bookmarkEnd w:id="1"/>
```

I thought if the ID was 0, or if the name started with an _underscore, or if they tag was empty, I could, maybe, ignore certain anchors... As seen in the snippet from my own docx file, the user (me) may intentionally be doing odd things with Bookmarks. There's no way to tell unwanted anchors from wanted anchors.

Fixing this issue has a very high risk of breaking bookmark importing for everyone else. The user should, instead, save a Word file without bookmarks in them?

**Comment by greatislander** [comment]
FYI @mcgratay.

**Comment by connerbw** [comment]
> The _Goback bookmark enables the go to previous edit functionality (Shift+F5) across sessions. It is a hidden bookmark (and should be displayed if you check the box) and you should expect it to be present in documents produced by Word. In the case where you are manipulating documents outside Word it is very questionable whether it has any validity after you have finished so it isn't likely to matter if you delete it.

[Source](https://social.msdn.microsoft.com/Forums/en-US/0e0c5c33-dc4b-4e0f-b795-7868e6a63836/goback-hidden-bookmark-in-open-xml-while-processing-office-2010-word-document?forum=oxmlsdk) 

I'm going to change my mind and delete it.
