### ISSUE TITLE
Source comparison tool displays removed original content and added content in illogical way 

### ISSUE THREAD

**Issue by mcgratay** [pressbooks/pressbooks#1484]
### Prerequisites

* [x] Can you reproduce the behavior you wish to address with [all other plugins deactivated](http://codex.wordpress.org/Multisite_Network_Administration#Plugins)?
* [x] Are you running the [latest version of Pressbooks](http://github.com/pressbooks/pressbooks/releases/latest/) and the [latest version of WordPress](http://codex.wordpress.org/Upgrading_WordPress)?
* [x] Are you experiencing this issue with one of our built-in root or book themes?
* [x] Did you [perform a cursory search](https://github.com/issues?q=+is%3Aissue+repo%3Apressbooks%2Fpressbooks) to see if your bug or enhancement is already listed?

### Description

The source comparison tool intersperses the words of any addition to a cloned book with the words of any content removed from a chapter in comparison to its original. This results in a disruptive display in which it's difficult to read new content and compare it with the source content. 
![screen shot 2018-11-29 at 5 06 38 pm](https://user-images.githubusercontent.com/39064028/49255312-aaa2c380-f3f9-11e8-9005-5371551b02f3.png)

### Steps to Reproduce

1. Clone any book 
2. Turn on the Source Comparison tool by going to **Appearance > Theme Options > Web Options** and selecting "Enable Source Comparison." Save your changes. 
3. Access the content editor for a chapter and remove a line of text 
4. Add new text in the place of the old text and save your changes
5. View the webbook and click the "Show Comparison With Original" button 

**Expected behavior:** The new text displays as one complete chunk, and the removed text displays as one complete chunk. 

**Actual behavior:** Words from each version display interspersed with one another. 

### System Information

Pressbooks: 5.6.2
McLuhan: 2.6.0

**Comment by greatislander** [comment]
@mcgratay For what it's worth, that's just how the diff tool we are using works: http://incaseofstairs.com/jsdiff/

**Comment by greatislander** [comment]
My inclination would be to use the WordPress Core text diff tool (used in the revisions viewer). Do you think that's an improvement?
