### ISSUE TITLE
Second step of import label "Import in progress" can, sometimes, mislead editor.

### ISSUE THREAD

**Issue by connerbw** [pressbooks/pressbooks#1504]
### Feature Description

Second step of import label "Import in progress" can, sometimes, mislead editor.

It should be changed to emphasize the chapter selection process. 

### Feature Use Case

In rare cases, the 2nd step of an import will look like this:

![image](https://user-images.githubusercontent.com/812192/49743477-d3804f80-fc68-11e8-9894-c01170265a78.png)

This appears to be some sort of bug where no chapters are available for import. That bug should be fixed and we're working on it, but in the buggy cases where we can't foresee this happening, the label should be changed  to emphasize that this is a selection menu and that no import is actually in progress...

**Comment by mcgratay** [comment]
Suggestion for copy: 
On the left above the white bar: 
Select content below for import to Pressbooks 

On the right above the white bar (this should wrap down to another line if URLs are long): 
**File:** filename.wordpress.blablabla.xml

**Comment by greatislander** [comment]
@mcgratay How about:

**Source:** filename.xml

(Just so if it's a web URL it doesn't say "File" which might be confusing.)

**Comment by greatislander** [comment]
How's this?

![Screenshot of import screen which reads "Select content below for import into Pressbooks."](https://user-images.githubusercontent.com/605361/49802806-63cf9a80-fd24-11e8-9a1c-c4f753e519d5.png)
