### ISSUE TITLE
Support Knight Labs OEmbed Endpoint

### ISSUE THREAD

**Issue by greatislander** [pressbooks/pressbooks#1514]
### Feature Description

We currently support iframe embeds of Knight Labs Timelines. We can support their OEmbed endpoint too.

### Feature Use Case

It's easier!

### Other Notes

@SteelWagstaff came up with a prototype that works on vanilla WordPress (may need tweaks for Pressbooks coding standards, et cetera):

```php
wp_oembed_add_provider( 'cdn.knightlab.com/libs/timeline*', 'https://oembed.knightlab.com/timeline/' );
wp_oembed_add_provider( 'uploads.knightlab.com/storymapjs/*/index.html', 'https://oembed.knightlab.com/storymap/' );
```

### System Information

Pressbooks: 5.7.0-dev

**Comment by SteelWagstaff** [comment]
Note that this will allow user to embed both [Timeline](http://timeline.knightlab.com/) and [StoryMap](https://storymap.knightlab.com/#examples) objects (two separate Knight Lab) projects.
