### ISSUE TITLE
Allow users to hide glossary tooltip pop-out by clicking anywhere else on the page

### ISSUE THREAD

**Issue by NMSalmon** [pressbooks/pressbooks#1528]
### Feature Description

At present, the new glossary tool pops out a tooltip gloss when a glossary term is clicked. To hide the tooltip again, users have to click on the underlined glossary term in the text or click on another glossary term. 

It would be nice if users could hide the tooltip again by simply clicking anywhere else on the page that is not the tooltip itself (rather than having to click on a specific glossary term within a paragraph.)

### Feature Use Case

This change would apply to anyone who uses the glossary tool as a reader. It is a small change, but it may help resolve some slight confusion for first-time Pressbooks readers who may not find it intuitive to click back on the original term.

### Other Notes

It's especially useful that the new glossary tool allows users to copy/paste text from the tooltip itself, so this would be a good feature to preserve if you were to make the described change.

**Comment by greatislander** [comment]
Closed in #1559.
