### ISSUE TITLE
MCE Table Buttons

### ISSUE THREAD

**Issue by hughmcguire** [pressbooks/pressbooks#154]
Hi Ned,
3 features we want from PB-Textbook on all PB instances (asap!), TinyMCE buttons for:
--superscript
--subscript, and 
--table

NOTE re: the table button: we also want to add the following to:
`~/themes-book/pressbooks-book/editor-style.css`

`table {min-width: 50%;}` 

This makes sure that when the MCE table button is used, the resulting blank table in the editor looks like a blank table.

**Comment by greatislander** [comment]
@hughmcguire I'm going to keep this one for the table editor and create a separate one for superscript and subscript buttons, as they are independent features.

**Comment by greatislander** [comment]
This is ready to go—however, waiting to merge into master until I can arrange to avoid conflicts with Pressbooks Textbook's implementation (see https://github.com/BCcampus/pressbooks-textbook/issues/25).
