### ISSUE TITLE
When validating an epub3 file with http://validator.idpf.org/application/validate I get 'The entity "nbsp" was referenced, but not declared.'

### ISSUE THREAD

**Issue by thomasdumm** [pressbooks/pressbooks#1540]
### Prerequisites

* [ ] Can you reproduce the behavior you wish to address with [all plugins except Pressbooks deactivated](http://codex.wordpress.org/Multisite_Network_Administration#Plugins)?
* [x] Are you running the [latest version of Pressbooks](http://github.com/pressbooks/pressbooks/releases/latest/), the latest version of [McLuhan](http://github.com/pressbooks/pressbooks-book/releases/latest/), and the [latest version of WordPress](http://codex.wordpress.org/Upgrading_WordPress)?
* [x] Are you experiencing the issue while using this book theme?
* [x] Did you [perform a cursory search](https://github.com/issues?q=+is%3Aissue+repo%3Apressbooks%2Fpressbooks-book) to see if your bug or enhancement is already listed?

When validating an epub3 file with http://validator.idpf.org/application/validate I get 'The entity "nbsp" was referenced, but not declared.'

#### Book Info

Book ID: 22
Book URL: https://pressbooks.delivros.ch/oeffentlichesrecht/
Book Privacy: Public

#### Browser

Platform: OS X
Browser Name: Firefox
Browser Version: 64.0
User Agent String: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:64.0) Gecko/20100101 Firefox/64.0

#### WordPress Configuration

Network URL: http://pressbooks.delivros.ch/
Network Type: Subdirectory
Version: 5.0.2
Language: en_US
WP_ENV: development
WP_DEBUG: Disabled
Memory Limit: 64M

#### Pressbooks Configuration

Version: 5.6.3
Book Theme: McLuhan
Book Theme Version: 2.6.1
Root Theme: Aldine
Root Theme Version: 1.5.0

#### Pressbooks Dependencies

Epubcheck: Installed
Kindlegen: Installed
xmllint: Installed
PrinceXML: Installed
Saxon-HE: Installed

#### Must-Use Plugins

hm-autoloader.php: n/a

#### Network Active Plugins

Advanced WPLink: 1.1.0
Enable Media Replace: 3.2.7
Import users from CSV with meta: 1.12.1
Pressbooks: 5.6.3
Pressbooks LTI Provider: 1.1.2
Re-send Welcome Email: 0.4.2
Really Simple SSL: 3.1.3
Really Simple SSL pro multisite: 2.0.21
Simple History: 2.29.1
WP Mail SMTP: 1.4.1

#### Book Active Plugins

Advanced WPLink: 1.1.0
Enable Media Replace: 3.2.7
Import users from CSV with meta: 1.12.1
Pressbooks: 5.6.3
Pressbooks LTI Provider: 1.1.2
Re-send Welcome Email: 0.4.2
Really Simple SSL: 3.1.3
Really Simple SSL pro multisite: 2.0.21
Simple History: 2.29.1
WP Mail SMTP: 1.4.1

#### Inactive Plugins

Co-Authors Plus: 3.3.1
H5P: 1.11.3
Hypothesis: 0.5.0
PublishPress: 1.18.0
PublishPress Multiple Authors: 2.1.3
WP QuickLaTeX: 3.8.6

#### Server Configuration

PHP Version: 7.2.9-1+ubuntu16.04.1+deb.sury.org+1
MySQL Version: 5.7.24
Webserver Info: Apache/2.4.18 (Ubuntu)

#### PHP Configuration

Safe Mode: Disabled
Memory Limit: 256M
Upload Max Size: 128M
Post Max Size: 128M
Upload Max Filesize: 128M
Time Limit: 90
Max Input Vars: 1000
URL-aware fopen: On (1)
Display Errors: N/A

#### PHP Extensions

OPcache: Zend
XDebug: Disabled
cURL: Supported
cURL Version: 7.47.0
imagick: Not Installed
xsl: Installed

**Comment by thomasdumm** [comment]
To be use that I understand you correctly: You suggest that I replace the nbsp manually in the epub3 file and validate again to check that it validates without the error message?

**Comment by thomasdumm** [comment]
manually replacing all &nbsp; with &#160; in the epub3 file makes the epub3 valid in http://validator.idpf.org/application/validate

**Comment by greatislander** [comment]
Okay. Is this a new issue you've encountered in a recent version of Pressbooks? I'd also note that http://validator.idpf.org uses EpubCheck, which is already run during the export from Pressbooks; if you are not receiving any errors related to EPUB validation when running the EPUB3 export on Pressbooks I don't think this is a concern. I'm not sure how recently http://validator.idpf.org was updated; this may be a bug in older versions of EpubCheck or any number of other things. Note that, as per http://idpf.org:

> On January 30, 2017 the combination of IDPF and W3C was completed (W3C press release: www.w3.org/2017/01/pressrelease-idpf-w3c-combination.html.en), and IDPF has ceased operations as a membership organization. This website is now an archive. For current information about EPUB and more visit https://www.w3.org/publishing/

**Comment by thomasdumm** [comment]
The &nbsp; are in the epub2 and in the epub3 exports. I used latest Pressbooks and latest Pressbooks-book. I tried another epub validator and the epub2 file is perfectly valid (as it references a dtd). the epub3 file is not valid when validated with an epub3.0.1 checker (I used https://www.pagina.gmbh/produkte/epub-checker/ which is a recent version but in German). I think the &nbsp are really making the file invaild. I also opened the epub3 file with the latest oxygen editor which then also states validation erros for every &nbsp; with the same error message. I think the epub3 files should not have character entity references but googling this did not lead to a document that made this clear to me.

**Comment by thomasdumm** [comment]
I checked with the latest release  EPUBCheck 4.2.0-alpha-1 from from https://github.com/w3c/epubcheck/releases

Same situation: Entity "nbsp" was referenced but not declared

**Comment by connerbw** [comment]
Can you try again with 4.1.1 please?

https://github.com/w3c/epubcheck/releases/tag/v4.1.1

**Comment by thomasdumm** [comment]
Thank you for pointing me to 4.1.1. The &nbsp; error is not shown anymore.
