### ISSUE TITLE
Spaces before </em> tags are removed when text is copy/pasted from Microsoft Word 

### ISSUE THREAD

**Issue by mcgratay** [pressbooks/pressbooks#1547]
### Prerequisites

* [x] Can you reproduce the behavior you wish to address with [all other plugins deactivated](http://codex.wordpress.org/Multisite_Network_Administration#Plugins)?
* [x] Are you running the [latest version of Pressbooks](http://github.com/pressbooks/pressbooks/releases/latest/) and the [latest version of WordPress](http://codex.wordpress.org/Upgrading_WordPress)?
* [x] Are you experiencing this issue with one of our built-in root or book themes?
* [x] Did you [perform a cursory search](https://github.com/issues?q=+is%3Aissue+repo%3Apressbooks%2Fpressbooks) to see if your bug or enhancement is already listed?

### Description
When content from a Word document with italicized text is copy/pasted into Pressbooks, the space directly after an italicized word or term is erased, causing the italicized word to bump into the following text or other object. This is not consistent; the issue does not occur after every italicized word in the copied text. 

Example: https://testbooknormaluser.textopress.com/chapter/italics-test/
Word Doc: 
[italicstest.docx](https://github.com/pressbooks/pressbooks/files/2742793/italicstest.docx)

![screen shot 2019-01-09 at 4 52 11 pm](https://user-images.githubusercontent.com/39064028/50931153-d325d080-142f-11e9-8c0d-5196e6ac7051.png)

### Steps to Reproduce

1. Create a Word document in the most recent version of Microsoft Word with any amount of text and a few word in italics
2. Copy the text including the italics from the Word document you've created
3. Create a new chapter in pressbooks
4. Paste your copied text from Word into the **Visual Editor** of the chapter
5. Hit Save
6. View text in Visual Editor

**Expected behavior:** A space should remain between the end of an italicized word and its closing </em> tag. 
**Actual behavior:** Some of these spaces are removed after italicized words when text is copied from Word. 

#### Book Info

Book ID: 180
Book URL: http://testbooknormaluser.textopress.com/
Book Privacy: Public

#### Browser

Platform: OS X
Browser Name: Safari
Browser Version: 12.0.2
User Agent String: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_2) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.0.2 Safari/605.1.15

#### WordPress Configuration

Network URL: http://textopress.com/
Network Type: Subdomain
Version: 5.0.2
Language: en_US
WP_ENV: staging
WP_DEBUG: Disabled
Memory Limit: 64M

#### Pressbooks Configuration

Version: 5.7.0-dev
Book Theme: Adunis
Book Theme Version: 1.7.0
Root Theme: Aldine
Root Theme Version: 1.6.0-dev

#### Pressbooks Dependencies

Epubcheck: Installed
Kindlegen: Installed
xmllint: Installed
PrinceXML: Not Installed
Saxon-HE: Installed

#### Must-Use Plugins

Bedrock Autoloader: 1.0.0
hm-autoloader.php: n/a
telemetry.php: n/a

#### Network Active Plugins

Hypothesis: 0.5.0
Pressbooks: 5.7.0-dev
Pressbooks BISAC: 2.0.0
Pressbooks Client Marketing: 1.0.1
Pressbooks LTI Provider: 1.1.2
Pressbooks SELF-e: 1.5.1
Pressbooks Stats: 1.6.2
Pressbooks Whitelabel: 1.3.0
Redis Object Cache: 1.4.1

#### Book Active Plugins

Hypothesis: 0.5.0
Pressbooks: 5.7.0-dev
Pressbooks BISAC: 2.0.0
Pressbooks Client Marketing: 1.0.1
Pressbooks LTI Provider: 1.1.2
Pressbooks SELF-e: 1.5.1
Pressbooks Stats: 1.6.2
Pressbooks Whitelabel: 1.3.0
Redis Object Cache: 1.4.1

#### Inactive Plugins

H5P: 1.11.3
Parsedown Party: 1.1.1
Pressbooks BiblioBoard OAuth: 3.0.0
Pressbooks CAS Single Sign-On: 1.1.1
Pressbooks Shibboleth Single Sign-On: 0.0.5
Pressbooks VIP: 5.4.0
TablePress: 1.9.1
WP QuickLaTeX: 3.8.6

#### Server Configuration

PHP Version: 7.1.23-3+ubuntu16.04.1+deb.sury.org+1
MySQL Version: 5.5.5
Webserver Info: nginx/1.13.6

#### PHP Configuration

Safe Mode: Disabled
Memory Limit: 256M
Upload Max Size: 25M
Post Max Size: 25M
Upload Max Filesize: 25M
Time Limit: 120
Max Input Vars: 1000
URL-aware fopen: On (1)
Display Errors: N/A

#### PHP Extensions

OPcache: Zend
XDebug: Disabled
cURL: Supported
cURL Version: 7.47.0
imagick: Not Installed
xsl: Installed

**Comment by connerbw** [comment]
Tested with @mcgratay 
Copy pasting from Mac Word into Gmail does the same thing.
Doesn't happen on Windows (using LibreOffice)
This is a Mac Word issue and I don't think I can do anything about it.
Sorry.
