### ISSUE TITLE
Pressbooks Print PDF Exports failing since upgrade to 5.6.4

### ISSUE THREAD

**Issue by beckej13820** [pressbooks/pressbooks#1549]
### Prerequisites

* [x] Can you reproduce the behavior you wish to address with [all other plugins deactivated](http://codex.wordpress.org/Multisite_Network_Administration#Plugins)?
* [x] Are you running the [latest version of Pressbooks](http://github.com/pressbooks/pressbooks/releases/latest/) and the [latest version of WordPress](http://codex.wordpress.org/Upgrading_WordPress)?
* [x] Are you experiencing this issue with one of our built-in root or book themes?
* [x] Did you [perform a cursory search](https://github.com/issues?q=+is%3Aissue+repo%3Apressbooks%2Fpressbooks) to see if your bug or enhancement is already listed?

### Description

I'm getting failure in creating a Print PDF since upgrading to the latest version of Pressbooks. I can reproduce in two different books. PDF for Digital Distribution work fine, only Print PDFs are failing
### Steps to Reproduce

1. Books I'm getting errors on: https://oer.ed-beck.com/civilizacionhispanoamericana , https://oer.ed-beck.com/programmingforproblemsolving . For some reason https://oer.ed-beck.com/sunymicrobiologylab worked fine. 

Here are some of the error logs:

Array
(
    [time] => Sat Jan 12 01:33:32 2019
    [user] => beckej
    [site_url] => https://oer.ed-beck.com/civilizacionhispanoamericana
    [blog_id] => 36
    [theme] => McLuhan
    [url] => https://oer.ed-beck.com/civilizacionhispanoamericana/format/xhtml?timestamp=1547256797&hashkey=ea67bf0c097d70ca0027f4c4aabfeaef&pb-latex-zoom=3&optimize-for-print=1
)
Sat Jan 12 01:33:19 2019: ---- begin
Sat Jan 12 01:33:20 2019: /var/www/html/wp-content/uploads/sites/36/pressbooks/css/prince-1547256797.css:855: warning: parse error in value of property 'border-top' at '('
Sat Jan 12 01:33:23 2019: https://s3-us-west-2.amazonaws.com/courses-images/wp-content/uploads/sites/3123/2018/09/14022318/Historia_de_la_conquista_del_Per%C3%BA_1851__Muerte_del_Inca_Atahualpa_._3970908347-300x210.jpg: warning: ICC profile has color_space_rgb but expected color_space_gray
Sat Jan 12 01:33:24 2019: page 213: warning: no font for Emoticons character U+1F642, fallback to '?'
Sat Jan 12 01:33:26 2019: error: stripped image transparency to comply with PDF/X-1a:2003

--

Array
(
    [time] => Sat Jan 12 01:26:49 2019
    [user] => beckej
    [site_url] => https://oer.ed-beck.com/openstaxchemistry
    [blog_id] => 6
    [theme] => Jacobs
    [url] => https://oer.ed-beck.com/openstaxchemistry/format/xhtml?timestamp=1547256364&hashkey=f436d8c6884e7612b2567eab67b133be&pb-latex-zoom=3&optimize-for-print=1
)

**Expected behavior:** 

**Actual behavior:** 

#### Root Blog Info

Root Blog ID: 1
Root Blog URL: https://oer.ed-beck.com/

#### Browser

Platform: OS X
Browser Name: Chrome
Browser Version: 71.0.3578.98
User Agent String: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36

#### WordPress Configuration

Network URL: http://oer.ed-beck.com/
Network Type: Subdirectory
Version: 5.0.3
Language: en_US
WP_ENV: production
WP_DEBUG: Disabled
Memory Limit: 5000M

#### Pressbooks Configuration

Version: 5.6.4
Root Theme: Aldine
Root Theme Version: 1.5.0

#### Pressbooks Dependencies

Epubcheck: Installed
Kindlegen: Installed
xmllint: Installed
PrinceXML: Installed
Saxon-HE: Installed

#### Must-Use Plugins

hm-autoloader.php: n/a

#### Network Active Plugins

GitHub Updater: 8.6.0
Pressbooks: 5.6.4
Pressbooks LTI Provider: 1.1.2
Pressbooks Stats: 1.4.1
Really Simple SSL: 3.1.3

#### Root Blog Active Plugins

GitHub Updater: 8.6.0
Pressbooks: 5.6.4
Pressbooks LTI Provider: 1.1.2
Pressbooks Stats: 1.4.1
Really Simple SSL: 3.1.3
WP QuickLaTeX: 3.8.6

#### Inactive Plugins

Akismet Anti-Spam: 4.1
CC Export for Pressbooks: 1.0.0
H5P: 1.10.3
Hello Dolly: 1.6
Hypothesis: 0.5.0
mPDF for Pressbooks: 3.2.4
Openstax Import for Pressbooks: 1.2.4
Textbooks for Pressbooks: 4.2.3
Wp Show Site ID: 1.0.2

#### Server Configuration

PHP Version: 7.2.10-0ubuntu0.18.04.1
MySQL Version: 5.7.24
Webserver Info: Apache/2.4.29 (Ubuntu)

#### PHP Configuration

Safe Mode: Disabled
Memory Limit: 5000M
Upload Max Size: 1000M
Post Max Size: 1000M
Upload Max Filesize: 1000M
Time Limit: 30
Max Input Vars: 1000
URL-aware fopen: On (1)
Display Errors: N/A

#### PHP Extensions

OPcache: Zend
XDebug: Disabled
cURL: Supported
cURL Version: 7.58.0
imagick: Installed
xsl: Installed

**Comment by greatislander** [comment]
Which book theme are you using, @beckej13820?

**Comment by greatislander** [comment]
Also, remind me — are you running Prince on your server, or…?

**Comment by beckej13820** [comment]
Openstax chemistry failed using Jacobs.

Civilizacion hispanoamerica failed using McLuhan. 

Using PrinceXML. What’s weird is that exports for digitize distrobution worked fine using prince, it’s only the PDFs for print that failed. 

And then I have one book that I tested that was working fine.

**Comment by greatislander** [comment]
@beckej13820 The current version of Jacobs is 1.2.0: https://github.com/pressbooks/pressbooks-jacobs/releases/tag/1.2.0

Does upgrading Jacobs do anything to address the errors? Also, it looks like Prince is not happy with one of your images. The print profile has certain requirements which may not be being met:

```
warning: ICC profile has color_space_rgb but expected color_space_gray
```

Does deselecting the chapter with that image allow you to export?

**Comment by greatislander** [comment]
Also for additional context -- what version did you upgrade from when you installed 5.6.4?

**Comment by beckej13820** [comment]
Hi Ned,

I haven't been able to track this down, but I think it is not a pressbooks problem. I'm playing with some PHP settings to see if it is my server timing out when trying to export large or media-rich books. Especially if no one else is seeing these symptoms.

**Comment by greatislander** [comment]
Thanks for the update, Ed! Hope you are able to get it sorted.
