### ISSUE TITLE
Import progress notices display inaccurate counts

### ISSUE THREAD

**Issue by greatislander** [pressbooks/pressbooks#1599]
### Description

When importing from EPUB or API, the `$y->tick()` counts for the number of items being imported reflects the _available_ number of front matter, parts, chapters, back matter, etc. rather than the _selected_ number.

### Steps to Reproduce

1. Import a book via API or EPUB.
2. Select 2 of _n_ sections to import.
3. Click **Import Selection**.

**Expected behavior:** The progress bar label reflects the selected count, e.g. "Importing (1 of 2)".

**Actual behavior:** The progress bar label reflects the total available count, e.g. "Importing (1 of _n_)".

### Other Notes

Making `$y-tick()` work as expected might require a lot of rewriting based on my quick examination of the underlying import module code, so perhaps a better solution for the 5.7.0 release would be to remove the ticks for import modules.

**Comment by connerbw** [comment]
Let me try something today. I think I can get it working.
