### ISSUE TITLE
If a chapter contains an h1, then anchor ids of anchors on paragraphs are stripped in xhtml and thus in pdf export

### ISSUE THREAD

**Issue by thomasdumm** [pressbooks/pressbooks#1602]
### Prerequisites

* [x] Can you reproduce the behavior you wish to address with [all other plugins deactivated](http://codex.wordpress.org/Multisite_Network_Administration#Plugins)?
* [x] Are you running the [latest version of Pressbooks](http://github.com/pressbooks/pressbooks/releases/latest/) and the [latest version of WordPress](http://codex.wordpress.org/Upgrading_WordPress)?
* [x] Are you experiencing this issue with one of our built-in root or book themes?
* [x] Did you [perform a cursory search](https://github.com/issues?q=+is%3Aissue+repo%3Apressbooks%2Fpressbooks) to see if your bug or enhancement is already listed?

### Description

If a chapter contains an h1, then  anchor ids of anchors on paragraphs are stripped in xhtml and thus in pdf export

### Steps to Reproduce

1. Add an anchor to paragraph of an empty test chapter with the insert anchor button. Example: `<a id="anchor1"></a>`
2. export the xhtml file and search and find id="anchor1"
3. Add an h1 heading to the test chapter before or after the paragraph with the anchor
4. export the xhtml file and search and you will **not** find  id="anchor1". You find only the empty `<a></a>` without the id.

**Expected behavior:** 
ids of anchors in the text are not stripped
**Actual behavior:** 
ids of anchors in the text are stripped in case of an h1 in the chapter
#### Book Info

Book ID: 6
Book URL: https://pressbooks.delivros.ch/demo/
Book Privacy: Public

#### Browser

Platform: OS X
Browser Name: Firefox
Browser Version: 65.0
User Agent String: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:65.0) Gecko/20100101 Firefox/65.0

#### WordPress Configuration

Network URL: http://pressbooks.delivros.ch/
Network Type: Subdirectory
Version: 5.0.3
Language: en_US
WP_ENV: development
WP_DEBUG: Disabled
Memory Limit: 64M

#### Pressbooks Configuration

Version: 5.6.5
Book Theme: McLuhan
Book Theme Version: 2.7.3
Root Theme: Aldine
Root Theme Version: 1.5.0

#### Pressbooks Dependencies

Epubcheck: Installed
Kindlegen: Installed
xmllint: Installed
PrinceXML: Installed
Saxon-HE: Installed

#### Must-Use Plugins

hm-autoloader.php: n/a

#### Network Active Plugins

Advanced WPLink: 1.1.0
Enable Media Replace: 3.2.8
Import users from CSV with meta: 1.12.6.2
Pressbooks: 5.6.5
Pressbooks LTI Provider: 1.1.2
Re-send Welcome Email: 0.4.2
Really Simple SSL: 3.1.3
Really Simple SSL pro multisite: 2.0.22
Simple History: 2.29.1
WP Mail SMTP: 1.4.1

#### Book Active Plugins

Advanced WPLink: 1.1.0
Co-Authors Plus: 3.3.1
Enable Media Replace: 3.2.8
H5P: 1.11.3
Import users from CSV with meta: 1.12.6.2
Pressbooks: 5.6.5
Pressbooks LTI Provider: 1.1.2
Re-send Welcome Email: 0.4.2
Really Simple SSL: 3.1.3
Really Simple SSL pro multisite: 2.0.22
Simple History: 2.29.1
WP Mail SMTP: 1.4.1

#### Inactive Plugins

Hypothesis: 0.5.0
PublishPress: 1.19.3
PublishPress Multiple Authors: 2.1.3
WP QuickLaTeX: 3.8.6

#### Server Configuration

PHP Version: 7.2.9-1+ubuntu16.04.1+deb.sury.org+1
MySQL Version: 5.7.25
Webserver Info: Apache/2.4.18 (Ubuntu)

#### PHP Configuration

Safe Mode: Disabled
Memory Limit: 256M
Upload Max Size: 128M
Post Max Size: 128M
Upload Max Filesize: 128M
Time Limit: 90
Max Input Vars: 1000
URL-aware fopen: On (1)
Display Errors: N/A

#### PHP Extensions

OPcache: Zend
XDebug: Disabled
cURL: Supported
cURL Version: 7.47.0
imagick: Not Installed
xsl: Installed

**Comment by connerbw** [comment]
Cannot reproduce?

Content:

```
<h1>First H1</h1>
<a id="anchor1"></a>
<h1>Second H1</h1>
```

Renders:

```
<div class="chapter standard" id="chapter-anchors-away" title="Anchor's away">
    <div class="chapter-title-wrap">
         <h3 class="chapter-number">1</h3>
         <h2 class="chapter-title">Anchor's away</h2>
    </div>
    <div class="ugc chapter-ugc">
         <h1>First H1</h1>
         <p><a id="anchor1"></a></p>
         <h1>Second H1</h1>
    </div>
</div>
```

When I paste your chapter into my dev instance:

https://pressbooks.delivros.ch/demo/wp-json/pressbooks/v2/chapters/54

I get (with tidy turned on):

![image](https://user-images.githubusercontent.com/812192/52975232-bcf62300-3392-11e9-9d4b-ed38bee466c3.png)

**Comment by connerbw** [comment]
The way the XHTML export works if you have  If you have `<a id="Anchor1"></a>` in more than one chapter, the second one (and third, and fourth...) will get stripped.

This is because anchors in a single XHTML document must be unique.

**Comment by thomasdumm** [comment]
I still think that there is a bug. I did not catch all preconditions in the original bug report. After a lot of testing I think the described problem only occurs if the option "Two-Level TOC" is selected. If I deselect the option the described problem does *not* occur. As this option is deselected by default you did not come across the bug when trying to reproduce it. Some code for the "Two-Level TOC" handling must erase the ids if an h1 is in the content.

**Comment by connerbw** [comment]
Thanks @thomasdumm, fixed.
