### ISSUE TITLE
Remove DOI and ISBN from cloning routine when a book is cloned

### ISSUE THREAD

**Issue by mcgratay** [pressbooks/pressbooks#1609]
### Description

Currently, DOI and ebook ISBN entered into the Book Info page of a source remains in the metadata when an openly licensed public book is cloned onto another network. Both DOIs and ISBNs are meant to be unique and specific to a single version of a book, and must be changed with any adaption or new version. This metadata should be removed from the cloning and import processes. 

### Steps to Reproduce

1. Find an existing public, openly licensed book with a DOI or ISBN
2. Clone that book onto another network
3. Check the Book Info page of the cloned book to see the DOI or ISBN from the source book

**Expected behavior:** DOI and ISBN metadata can only be cloned internally within a network

**Actual behavior:** DOI and ISBN metadata can be cloned from any public, openly licensed book

**Comment by SteelWagstaff** [comment]
The solution should also catch situations where books are imported via XML/WXR and book info is copied over.

**Comment by SteelWagstaff** [comment]
ISBNs (print and digital) and DOI values are no longer included in any cloning operations. ISBNs and DOI values are still included in XML exports and will be brought in when 'book information' is selected for inclusion in a WXR import.
