### ISSUE TITLE
chapertype is not saved, after assigning it in a chapter and saving the chapter

### ISSUE THREAD

**Issue by thomasdumm** [pressbooks/pressbooks#1615]
### Prerequisites

* [x] Can you reproduce the behavior you wish to address with [all other plugins deactivated](http://codex.wordpress.org/Multisite_Network_Administration#Plugins)?
* [x] Are you running the [latest version of Pressbooks](http://github.com/pressbooks/pressbooks/releases/latest/) and the [latest version of WordPress](http://codex.wordpress.org/Upgrading_WordPress)?
* [x] Are you experiencing this issue with one of our built-in root or book themes?
* [x] Did you [perform a cursory search](https://github.com/issues?q=+is%3Aissue+repo%3Apressbooks%2Fpressbooks) to see if your bug or enhancement is already listed?

### Description

I am trying to assign a chapertype. But saving the chaper does not save the chaptertype. In the debug.log I see:

PHP Warning:  array_map(): Argument #2 should be an array in /var/www/html/pressbooks.delivro
s.ch/wp-admin/includes/post.php on line 2005

### Steps to Reproduce

1. Set the chaptertype "numberless"
2. save the chapter
3. check the chaptertype
4. see that chaptertype is "standard"

#### Book Info

Book ID: 25
Book URL: http://pressbooks.delivros.ch/arbeitsrechtloesungen/
Book Privacy: Public

#### Browser

Platform: Windows
Browser Name: Firefox
Browser Version: 65.0
User Agent String: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:65.0) Gecko/20100101 Firefox/65.0

#### WordPress Configuration

Network URL: http://pressbooks.delivros.ch/
Network Type: Subdirectory
Version: 5.1
Language: en_US
WP_ENV: development
WP_DEBUG: Enabled
Memory Limit: 64M

#### Pressbooks Configuration

Version: 5.6.5
Book Theme: Jacobs
Book Theme Version: 1.2.0
Root Theme: Aldine
Root Theme Version: 1.5.0

#### Pressbooks Dependencies

Epubcheck: Installed
Kindlegen: Installed
xmllint: Installed
PrinceXML: Installed
Saxon-HE: Installed

#### Must-Use Plugins

hm-autoloader.php: n/a

#### Network Active Plugins

Pressbooks: 5.6.5
Really Simple SSL: 3.1.3
Really Simple SSL pro multisite: 2.0.22

#### Book Active Plugins

Pressbooks: 5.6.5
Really Simple SSL: 3.1.3
Really Simple SSL pro multisite: 2.0.22

#### Inactive Plugins

Advanced WPLink: 1.1.0
Co-Authors Plus: 3.3.1
Enable Media Replace: 3.2.8
H5P: 1.12.0
Hypothesis: 0.5.0
Import users from CSV with meta: 1.13.2
Pressbooks LTI Provider: 1.1.2
PublishPress: 1.19.4
PublishPress Multiple Authors: 2.3.0
Simple History: 2.29.2
WP Mail SMTP: 1.4.1
WP QuickLaTeX: 3.8.6

#### Server Configuration

PHP Version: 7.2.9-1+ubuntu16.04.1+deb.sury.org+1
MySQL Version: 5.7.25
Webserver Info: Apache/2.4.18 (Ubuntu)

#### PHP Configuration

Safe Mode: Disabled
Memory Limit: 256M
Upload Max Size: 128M
Post Max Size: 128M
Upload Max Filesize: 128M
Time Limit: 90
Max Input Vars: 1000
URL-aware fopen: On (1)
Display Errors: N/A

#### PHP Extensions

OPcache: Zend
XDebug: Disabled
cURL: Supported
cURL Version: 7.47.0
imagick: Not Installed
xsl: Installed

**Comment by greatislander** [comment]
Hi @thomasdumm, we generally discourage users from upgrading the version of WordPress until Pressbooks has been tested and determined to be compatible. You are using Pressbooks 5.6.5 with a version of WordPress that it has [not been tested against](https://github.com/pressbooks/pressbooks/blob/5.6.5/readme.txt#L5-L6):

```
Requires at least: 4.9.8
Tested up to: 5.0.3
```

The issue you are reporting was discovered by our team and [fixed earlier this week](https://github.com/pressbooks/pressbooks/pull/1608). Pressbooks 5.7 ensures compatibility with WordPress 5.1 and will be released mid-March.
