### ISSUE TITLE
EXPORT failure

### ISSUE THREAD

**Issue by sswettenham** [pressbooks/pressbooks#162]
Export Your Book button results in blank screen for any format,
I have changed files/folder mPDF to CHMOD 777 with no change in result.
Perhaps this is a Webnames hosting issue?
Pressbooks is working save for the Export.

**Comment by bdolor** [comment]
Typically, you'll want to provide enough information so that others can attempt to re-create your issue, or be able to ascertain if it's something specific about your setup. Some quick details about your PHP version, server details etc is a good place to start. Providing error messages from log files is very helpful. For instance blank screens will usually show as error messages in Apache log files or in debug.log.

**Comment by sswettenham** [comment]
Host - 	PleskLinux56.webnames.ca -
Server - LiteSpeed
Wordpress 4.2.2  RAM 39,0/96M
mysqli 5.1.73
PHPv 5.6.1 - memory_limit 256M 

Debug  true - 
Fatal error: Allowed memory size of 100663296 bytes exhausted (tried to allocate 32 bytes) in /var/www/vhosts/.../httpdocs/ebooks/wp-includes/functions.php on line 4485

**Comment by bdolor** [comment]
Running out of memory is a problem to be solved by modifying your server configuration. PHP needs more than has been allotted. Of note, there is a discrepancy between how much memory has been declared that PHP has access to (256M) and the value in the error message 'Allowed memory size' (100663296 bytes = 96M).

**Comment by sswettenham** [comment]
Since I will have to contact my host to make the change (if allowed), what is the optimum memory for the server configuration?

**Comment by bdolor** [comment]
Server administration of shared hosting is foreign to me, but the same principle should apply: Optimum memory allocation depends on the total amount of RAM available to Apache on the machine and the Max Clients, or number of httpd processes that can request a chunk of that RAM. The situation server admins want to avoid is having httpd processes request more memory than is available which the server deals with by writing to disk (swap). At any rate, you need more memory than you have, but not much more according to the error log. Ask for 256M, if they say no, see if they'll go for 128M.

**Comment by greatislander** [comment]
Thanks for jumping in, @bdolor. It is also worth noting that a shared hosting platform like Webnames is unlikely to include or support the installation of the required software for exporting PDF and Kindle files. It may be that your exports are failing because you have no available libraries for these particular export routines. Do you have mPDF and Kindlegen installed?

**Comment by sswettenham** [comment]
Pressbooks Version: 2.5

php_value memory_limit 512M

Fatal error: Out of memory (allocated 321126400) (tried to allocate 72 bytes) in /../wp-includes/functions.php on line 4485

When I run:
http://../wp-content/plugins/pressbooks/symbionts/mpdf/examples/example01_basic.php
I get a PDF download
Hence I assume that mPDF is working as per readme test.

Exporting 3 chapters to PDF.  It appears to be working then after a short time displays error.

**Comment by greatislander** [comment]
Thoughts, @bdolor?

**Comment by bdolor** [comment]
For WP v4.2.2 [line 4485](https://github.com/WordPress/WordPress/blob/4.2.2/wp-includes/functions.php#L4485) in `wp-includes/functions.php` calls `debug_backtrace()` which is, according to the log, where the memory error is occurring. I interpret this to mean that the stack trace this function is handling is large and it runs out of memory. Needless to say, if that function is being called then errors are occurring and it's trying to handle them. So, my guess would be that this isn't the problem, but a symptom of another problem. At any rate, I can't reproduce the error and with the information available to me can only offer general advice to check php extensions and server dependencies. 

The WP function in which `debug_backtrace()` occurs is `wp_debug_bactrace_summary()` which is returned in a [wrapper function](https://github.com/WordPress/WordPress/blob/4.2.2/wp-includes/wp-db.php#L3086) called `get_caller()` in `wp-includes/wp-db.php`. We're left looking at a database query, but it's worth noting that none of this is pointing directly to PB code. 

https://github.com/WordPress/WordPress/blob/4.2.2/wp-includes/wp-db.php#L1284
https://github.com/WordPress/WordPress/blob/4.2.2/wp-includes/wp-db.php#L1747

**Comment by sswettenham** [comment]
When all else fails backup and reinstall:

1. I reinstalled WP 4.2.2
2. Modified wp-config and htaccess with Multisite parameters
3. Modified wp-config with define('WP_MEMORY_LIMIT', '256M');
4. Modified htaccess with
     AddType application/x-httpd-php56 .php
     php_value memory_limit 512M
5. Added Pressbooks 2.5.1 and Pressbooks Textbook 1.2.10
6. Created site
7. Added Part -> Main Body for chapters
8. Copied over Text (HTML) to Front Part and Chapters
9. Added author data to Book Info
10. Tested and confirmed mPDF functioning with
     http://domainname/site/wp-content/plugins/pressbooks/symbionts/mpdf/examples/example01_basic.php
10. Export > Export Your Book
11. Progress bar continued for about 60 seconds
12. PDF generated and displayed for download or trash

Export working for PDF.

**Comment by sswettenham** [comment]
Thanks for looking into this and the updated Pressbooks + Textbook plugins
