### ISSUE TITLE
During book cloning the glossary page gets populated with the actual glossary terms. 

### ISSUE THREAD

**Issue by thomasdumm** [pressbooks/pressbooks#1622]
### Prerequisites

* [x] Can you reproduce the behavior you wish to address with [all other plugins deactivated](http://codex.wordpress.org/Multisite_Network_Administration#Plugins)?
* [x] Are you running the [latest version of Pressbooks](http://github.com/pressbooks/pressbooks/releases/latest/) and the [latest version of WordPress](http://codex.wordpress.org/Upgrading_WordPress)?
* [x] Are you experiencing this issue with one of our built-in root or book themes?
* [x] Did you [perform a cursory search](https://github.com/issues?q=+is%3Aissue+repo%3Apressbooks%2Fpressbooks) to see if your bug or enhancement is already listed?

### Description

During book cloning the glossary page gets populated with the actual glossary terms. In the original version of the book the glossary page was empty and set to the post type "glossary" (as required for automatic glossary generation). I do not know if this is a wanted behavior, that is why I report it here.

I am using the development branch of Pressbooks 5.7.0

**Comment by connerbw** [comment]
Thanks @thomasdumm, fixed.
