### ISSUE TITLE
Add ARIA attributes to any alerts that provide users with real time information

### ISSUE THREAD

**Issue by SteelWagstaff** [pressbooks/pressbooks#1637]
### Description

When users receive information in real time, we should ensure that this information is communicated to users of assistive technology as well. This can be done by adding role=”status” or role=”alert’ to the message. See https://www.w3.org/TR/wai-aria-practices/#alert or https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/Alert_Role for the `alert` role and https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/ARIA_Techniques/Using_the_status_role for more on the `status` role.

For example, when book information is saved, the user sees a 'Book Information updated' alert. This message and others like it should receive an ARIA role attribute of `status` or `update`.  
![Screen Shot 2019-04-03 at 12 11 07 PM](https://user-images.githubusercontent.com/13485451/55498573-953ce080-5609-11e9-9e3e-532bb9f04bc5.png)

**Comment by mcgratay** [comment]
Looks good, with the exception that I would label export error reports as alerts instead of status updates. 
![Screen Shot 2019-04-24 at 2 19 58 PM](https://user-images.githubusercontent.com/39064028/56683874-7d063180-669c-11e9-91da-346e097eb242.png)

**Comment by connerbw** [comment]
>  I would label export error reports as alerts instead of status updates

Done in https://github.com/pressbooks/pressbooks/commit/7f5082119fa7734f44e02d0f617c788838613183

**Comment by mcgratay** [comment]
Resolved 👍
