### ISSUE TITLE
No error message provided upon incomplete input on contributor page

### ISSUE THREAD

**Issue by SteelWagstaff** [pressbooks/pressbooks#1639]
### Description

If a user leaves the required 'name' input field blank on the contributor creation page and presses the submit button, the field becomes highlighted in red, but no error message is provided.

![Screen Shot 2019-04-03 at 12 48 28 PM](https://user-images.githubusercontent.com/13485451/55500868-d683bf00-560e-11e9-9300-bd7e520694cc.png)

We should provide an error message with instructions to help users correct the incomplete submission. See https://developer.mozilla.org/en-US/docs/Learn/HTML/Forms/Form_validation#Customized_error_messages for more details.

**Comment by SteelWagstaff** [comment]
Minimally, all we need is to indicate that the field is required.

**Comment by connerbw** [comment]
That field comes from WordPress core. I opened at ticket: https://core.trac.wordpress.org/ticket/47018

**Comment by mcgratay** [comment]
Resolved 👍
