### ISSUE TITLE
Call to undefined function PressBooks\get_user_by

### ISSUE THREAD

**Issue by borayeris** [pressbooks/pressbooks#164]
Fatal error: Call to undefined function PressBooks\get_user_by() in /dir/public_html/wp-content/plugins/pressbooks/includes/class-pb-book.php on line 118

error happens on export .

**Comment by greatislander** [comment]
Hi @borayeris, are you running Pressbooks 2.5? This is a known issue and will be fixed in Pressbooks 2.5.1, which will be released within the next 24 hours or so. Thanks for your patience.

**Comment by borayeris** [comment]
WP 4.2.2
PressBooks Version 2.5
