### ISSUE TITLE
Date picker for publication date on book info isn't fully accessible

### ISSUE THREAD

**Issue by SteelWagstaff** [pressbooks/pressbooks#1640]
### Description

The date picker we use for publication date on our book info page is not fully accessible to users of assistive technologies. While it is possible to navigate around the calendar with the keyboard, focus remains on the text field and no additional information is communicated to AT users. In addition to using a date picker that is more accessible to screen readers, we should consider allowing users to type directly into the field. A reference implementation for a replacement that looks very similar to what we currently have in place can be found at https://dequeuniversity.com/library/aria/date-pickers/sf-date-picker

**Comment by mcgratay** [comment]
If the date is not entered a very specific way, then the user is given an error to "match the requested format." 

However, a requested format is not given. 

Suggestion: Change the italicized text under the date to read: "This is added to the metadata in your ebook. Please write date in MM/DD/YYYY format. 
![Screen Shot 2019-04-17 at 3 26 55 PM](https://user-images.githubusercontent.com/39064028/56315385-8c79fd80-6125-11e9-9fc2-199777442a68.png)

**Comment by mcgratay** [comment]
Great 👍
