### ISSUE TITLE
"Undefined index: paragraph_separation error" on creation of a new book

### ISSUE THREAD

**Issue by rootl** [pressbooks/pressbooks#1645]
### Description

Upon creation of a book, these errors appear in the admin dashboard of the new book  :
```
Notice: Undefined index: paragraph_separation in /var/www/html/milnepublishing.geneseo.edu/wp-content/plugins/pressbooks/inc/modules/themeoptions/class-weboptions.php on line 507

Notice: Undefined index: paragraph_separation in /var/www/html/milnepublishing.geneseo.edu/wp-content/plugins/pressbooks/inc/modules/themeoptions/class-weboptions.php on line 518
```
I turned error display off to suppress the error messages for now.

### Steps to Reproduce

1.  My Catalog >> Create a New Book
2.  Enter webbook address
3.  Enter Book Title
4.  Book is created, errors noted above appear in dashboard. 

**Expected behavior:** Book created, no errors.

**Actual behavior:** Book created successfully, but error messages in dashboard. 

#### Root Blog Info

Root Blog ID: 1
Root Blog URL: https://milnepublishing.geneseo.edu/

#### Browser

Platform: Windows
Browser Name: Firefox
Browser Version: 67.0
User Agent String: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:67.0) Gecko/20100101 Firefox/67.0

#### WordPress Configuration

Network URL: http://milnepublishing.geneseo.edu/
Network Type: Subdirectory
Version: 5.1.1
Language: en_US
WP_ENV: Not set
WP_DEBUG: Enabled
Memory Limit: 64M

#### Pressbooks Configuration

Version: 5.7.0
Root Theme: Aldine
Root Theme Version: 1.6.0

#### Pressbooks Dependencies

Epubcheck: Installed
Kindlegen: Installed
xmllint: Installed
PrinceXML: Installed
Saxon-HE: Installed

#### Must-Use Plugins

Global SMTP: 1.0
hm-autoloader.php: n/a
WP Multisite Allow Hyphens and Underscores Override Admin: 1.0
WP Pressbooks Allow Prince 300dpi Images: n/a

#### Network Active Plugins

Better Search Replace: 1.3.3
Candela Citation: 0.2.2
Check Email: 0.5.5
Disable Comments: 1.9.0
GitHub Updater: 8.7.2
Hypothesis: 0.5.0
iframe: 4.4
Openstax Import for Pressbooks: 1.3.2
Pressbooks: 5.7.0
Textbooks for Pressbooks: 4.2.3
UpdraftPlus - Backup/Restore: 2.16.10.24
WordPress Mass Email to users: 1.1
WP-Optimize: 2.2.13
WP QuickLaTeX: 3.8.6

#### Root Blog Active Plugins

Better Search Replace: 1.3.3
Candela Citation: 0.2.2
Check Email: 0.5.5
Disable Comments: 1.9.0
GitHub Updater: 8.7.2
Hypothesis: 0.5.0
iframe: 4.4
Openstax Import for Pressbooks: 1.3.2
Pressbooks: 5.7.0
Textbooks for Pressbooks: 4.2.3
UpdraftPlus - Backup/Restore: 2.16.10.24
WordPress Mass Email to users: 1.1
WP-Optimize: 2.2.13
WP QuickLaTeX: 3.8.6

#### Inactive Plugins

Candela Utility: 0.4.1
H5P: 1.11.3
WP-Matomo: 1.0.21

#### Server Configuration

PHP Version: 7.3.1
MySQL Version: 5.6.42
Webserver Info: Apache/2.4.6 () OpenSSL/1.0.2k-fips PHP/7.3.1

#### PHP Configuration

Safe Mode: Disabled
Memory Limit: 256M
Upload Max Size: 60000M
Post Max Size: 100000M
Upload Max Filesize: 60000M
Time Limit: 5000
Max Input Vars: 1000
URL-aware fopen: On (1)
Display Errors: N/A

#### PHP Extensions

OPcache: Zend
XDebug: Disabled
cURL: Supported
cURL Version: 7.29.0
imagick: Not Installed
xsl: Installed

**Comment by mcgratay** [comment]
Tested on the recently migrated Milne Publishing network - unable to reproduce.

**Comment by SteelWagstaff** [comment]
I think the issue may have been related to the PHP setting `Display Errors`, which we don't have turned on in our test networks.
