### ISSUE TITLE
Focus order follows unexpected sequence on Book Information page 

### ISSUE THREAD

**Issue by mcgratay** [pressbooks/pressbooks#1649]
### Prerequisites

* [x] Can you reproduce the behavior you wish to address with [all other plugins deactivated](http://codex.wordpress.org/Multisite_Network_Administration#Plugins)?
* [x] Are you running the [latest version of Pressbooks](http://github.com/pressbooks/pressbooks/releases/latest/) and the [latest version of WordPress](http://codex.wordpress.org/Upgrading_WordPress)?
* [x] Are you experiencing this issue with one of our built-in root or book themes?
* [x] Did you [perform a cursory search](https://github.com/issues?q=+is%3Aissue+repo%3Apressbooks%2Fpressbooks) to see if your bug or enhancement is already listed?

### Description

The "Save" button on the Book Information page receives focus before any book information fields, which is an illogical sequence for those using keyboard-only navigation. 

This button should receive focus after the user has gone through all of the information. 

Consider moving the Save button to the bottom of the Book Information page. 

### Steps to Reproduce

1. Access the Book Information page of any book 
2. Using a keyboard to navigate, tab down to the Save button

**Comment by SteelWagstaff** [comment]
Duplicates #1642
