### ISSUE TITLE
Create a secondary means of locating content on Pressbooks 

### ISSUE THREAD

**Issue by mcgratay** [pressbooks/pressbooks#1651]
Pages in the Pressbooks backend can only be found through navigation. Create a secondary means for users to locate content on the site. We plan to create a 'site map' in the footer that leads to a structured list of all admin menu pages.

**Comment by SteelWagstaff** [comment]
Site map is the way to go, I think.

**Comment by mcgratay** [comment]
One small thing -- per the current visual layout, Profile access from the admin bar wouldn't be nested under the book being accessed. Unless there's a technical reason that it's more appropriate, I'd recommend moving everything between "Hello, user" and "Log out" one tab to the left in hierarchy 
![Screen Shot 2019-04-26 at 11 21 51 AM](https://user-images.githubusercontent.com/39064028/56818512-c0d07680-6815-11e9-8ab2-8cc05d0127e1.png)
