### ISSUE TITLE
Admin color scheme for user profile does not save 

### ISSUE THREAD

**Issue by mcgratay** [pressbooks/pressbooks#1652]
### Prerequisites

* [x] Can you reproduce the behavior you wish to address with [all other plugins deactivated](http://codex.wordpress.org/Multisite_Network_Administration#Plugins)?
* [x] Are you running the [latest version of Pressbooks](http://github.com/pressbooks/pressbooks/releases/latest/) and the [latest version of WordPress](http://codex.wordpress.org/Upgrading_WordPress)?
* [x] Are you experiencing this issue with one of our built-in root or book themes?
* [x] Did you [perform a cursory search](https://github.com/issues?q=+is%3Aissue+repo%3Apressbooks%2Fpressbooks) to see if your bug or enhancement is already listed?

### Description

Users have the option to change the color scheme of their Pressbooks back end interface, through the Admin Color Scheme settings on the user's profile settings page, but this setting cannot be saved. 

If users choose a color scheme other than "Pressbooks," the color scheme reverts to "Pressbooks" when the user clicks "Update Profile" at the bottom of the page. The color scheme will also automatically revert back to "Pressbooks" when the user closes out a session. 

This setting should either allow the user to change the interface color scheme and have it save until the user chooses to change it again, or should be removed. 

### Steps to Reproduce

1. Access a Pressbooks network
2. Click on your username in the top menu
3. Click "Edit My Profile" 
4. Next to the "Admin Color Scheme" setting, choose a color scheme other than "Pressbooks" 
5. Close out the browser, then log back in to see if the color scheme remained the same _or_ click "Update Profile" at the bottom of th epage

**Expected behavior:** A user's chosen color scheme is saved to their profile until they choose to change it

**Actual behavior:** The admin color scheme option only applies the color scheme for one session, and only if profile settings are not updated

**Comment by greatislander** [comment]
I think this was a long-ago historical decision (before my day). There's code which forces the use of the Pressbooks admin colours here:

https://github.com/pressbooks/pressbooks/blob/e096ea7602e0d764e6c530e4f17147fa4902f1db/inc/class-activation.php#L416-L435

Hooked here:

https://github.com/pressbooks/pressbooks/blob/e096ea7602e0d764e6c530e4f17147fa4902f1db/inc/class-activation.php#L66-L67

**Comment by SteelWagstaff** [comment]
I believe that https://github.com/pressbooks/pressbooks/pull/1681 also fixes this issue. Can you confirm @connerbw or @dannylonglegs?

**Comment by connerbw** [comment]
@SteelWagstaff Yup!
