### ISSUE TITLE
SVG files not uploading to Pressbooks

### ISSUE THREAD

**Issue by mcgratay** [pressbooks/pressbooks#1653]
### Prerequisites

* [x] Can you reproduce the behavior you wish to address with [all other plugins deactivated](http://codex.wordpress.org/Multisite_Network_Administration#Plugins)?
* [x] Are you running the [latest version of Pressbooks](http://github.com/pressbooks/pressbooks/releases/latest/) and the [latest version of WordPress](http://codex.wordpress.org/Upgrading_WordPress)?
* [x] Are you experiencing this issue with one of our built-in root or book themes?
* [x] Did you [perform a cursory search](https://github.com/issues?q=+is%3Aissue+repo%3Apressbooks%2Fpressbooks) to see if your bug or enhancement is already listed?

### Description

SVG files are not uploading to Pressbooks, regardless of size. When SVG file uploads are attempted, users receive the following error report: 

"Sorry, this file type is not permitted for security reasons." 

SVG files are whitelisted as accepted upload file types. 

![Screen Shot 2019-04-05 at 2 03 49 PM](https://user-images.githubusercontent.com/39064028/55647595-0d430c00-57ac-11e9-882f-2e3d3f1b3e51.png)

### Steps to Reproduce

1. Log in to a Pressbooks network and access a chapter
2. Click "Add Media" 
3. Drag and drop an SVG file into the Add Media window 
4. See if an error appears

**Expected behavior:** SVG files under the network's maximum upload file size limit should successfully upload to the chapter 

**Actual behavior:** The SVG file is rejected, and the user receives an error stating that SVG files are not permitted

**Comment by greatislander** [comment]
:wave: WordPress does not include support for SVG out of the box. Here's some info and a method for safely enabling them (TL:DR; they can be a security risk if they aren't properly sanitized):

https://kinsta.com/blog/wordpress-svg/

**Comment by SteelWagstaff** [comment]
Options for handling: 1) do nothing until/until WordPress changes its mind about [this ongoing conversation](https://core.trac.wordpress.org/ticket/24251), 2) define ALLOW_UNFILTERED_UPLOADS to true for all/some networks (#5 in [this list](https://code.tutsplus.com/articles/new-wp-config-tweaks-you-probably-dont-know--wp-35396)), and define who can use this super admin power, 3) review Daryll Doyle's [Safe SVG plugin](https://wordpress.org/plugins/safe-svg/) and if approved, install it for networks who request it. We're choosing #1 for now.
