### ISSUE TITLE
H5P content types overlap navigation bar in Pressbooks webbook 

### ISSUE THREAD

**Issue by mcgratay** [pressbooks/pressbooks#1658]
### Prerequisites

* [x] Can you reproduce the behavior you wish to address with [all other plugins deactivated](http://codex.wordpress.org/Multisite_Network_Administration#Plugins)?
* [x] Are you running the [latest version of Pressbooks](http://github.com/pressbooks/pressbooks/releases/latest/) and the [latest version of WordPress](http://codex.wordpress.org/Upgrading_WordPress)?
* [x] Are you experiencing this issue with one of our built-in root or book themes?
* [x] Did you [perform a cursory search](https://github.com/issues?q=+is%3Aissue+repo%3Apressbooks%2Fpressbooks) to see if your bug or enhancement is already listed?

### Description

Images overlap the navigation bar when scrolling of a user has added an H5P element of the content type "Collage". Collages only overlap the navigation bar when a shortcode is used. Image in the collage do not overlap the navigation bar when an iframe is used to embed the element instead. 

Issue does not seem to affect any other H5P content type. 

Tested on Safari. 

Example: 
https://h5pcollageerror.textopress.com/chapter/chapter-1/

![Screen Shot 2019-04-10 at 2 15 33 PM](https://user-images.githubusercontent.com/39064028/55903207-1dd3f780-5b9b-11e9-9487-06ed386994af.png)

### Steps to Reproduce

1. Access an existing book or create a new one 
2. Go to **Plugins** from the left sidebar menu and click **Activate** on the H5P plugin if it has not already been activated on the book
3. Navigate to the **H5P Content** page from the left sidebar menu 
4. Click **Add New** and select "Collage" from the content menu 
5. Create a collage 
6. Copy the H5P shortcode and paste into a chapter, then save
7. View the webbook and scroll to see if the images overlap the navigation bar 

**Expected behavior:** No elements overlap the navigation bar in the webbook interface. 

**Actual behavior:** The Collage H5P content type will overlap navigation links in the webbook interface when a shortcode is used.

**Comment by SteelWagstaff** [comment]
I've actually seen it with other H5P types as well. See, for example: https://wisc.pb.unizin.org/portuguese/chapter/licao-1/ (the fill in the black and multiple choice activities will overlap our navbar). 
![Screen Shot 2019-04-10 at 1 45 13 PM](https://user-images.githubusercontent.com/13485451/55905163-0abf2880-5b97-11e9-9d30-fd3bb663f13b.png)

I'm guessing its a javascript conflict and possibly fixable with z-index tweaks?

**Comment by greatislander** [comment]
Related:

- https://github.com/pressbooks/pressbooks-book/issues/220
- https://github.com/pressbooks/pressbooks-book/commit/95152b5f779a7a6fd493d58402732cbadcbe7540#diff-d1eae7e3409073cb5f1e93ddc7bbb9abR207
- https://github.com/pressbooks/pressbooks-book/pull/224/

**Comment by SteelWagstaff** [comment]
Did some cursory investigation. Many H5P activities have an .h5p-container class with a `z-index` value of 1. Our `.nav-reading` nav element does not have a z-index value itself, but the various divs and buttons inside of it do (currently `z-index=23`). Adding a 'z-index' property of 1 to the `nav.nav-reading` element seems to fix the issue for me, at least with the Portuguese book I was looking at.

**Comment by dannylonglegs** [comment]
This is a pressbooks-book issue. PR here: https://github.com/pressbooks/pressbooks-book/pull/534

**Comment by mcgratay** [comment]
Can confirm fixed on Textopress.
