### ISSUE TITLE
No way to close glossary tooltip with a keyboard

### ISSUE THREAD

**Issue by josieg** [pressbooks/pressbooks#1660]
### Prerequisites

* [x] Can you reproduce the behavior you wish to address with [all other plugins deactivated](http://codex.wordpress.org/Multisite_Network_Administration#Plugins)?
* [x] Are you running the [latest version of Pressbooks](http://github.com/pressbooks/pressbooks/releases/latest/) and the [latest version of WordPress](http://codex.wordpress.org/Upgrading_WordPress)?
* [x] Are you experiencing this issue with one of our built-in root or book themes?
* [x] Did you [perform a cursory search](https://github.com/issues?q=+is%3Aissue+repo%3Apressbooks%2Fpressbooks) to see if your bug or enhancement is already listed?

### Description
When navigating with a keyboard in a webbook chapter using the [Tab] key to move between links, there doesn't seem to be a straightforward way to close a glossary term's tooltip once it's been expanded. Maybe there is something that I am missing, but this could be an accessibility issue for people using keyboards for navigation.

This problem is most obvious when there is only one glossary term on a page, because when you navigate to the next glossary term, the previous term's tool tip will close. 

### Steps to Reproduce

1. Insert a glossary term in a chapter.
2. View the glossary term in the webbook.
3. Use the [Tab] key to navigate to the glossary term. 
4. When you reach the glossary term, the tool tip expands.
5. Keep tabbing. Tooltip remains expanded unless there is another glossary term to navigate to.
6. Try to close the tooltip using keyboard only. No luck.

**Expected behaviour:** 
I expect for there to be an easy way to close the tooltip for someone who relies on keyboard navigation. For example, the tooltip could disappear after focus leaves the glossary term, or the tooltip could close when you hit "enter" on the keyboard when the term is selected.

**Actual behaviour:** 
I tried a bunch of different things but I can't get the tooltip to disappear without clicking with a mouse. The tooltip only disappears if there is another glossary term on a page because only one tooltip is open at one time.

**Comment by greatislander** [comment]
Does ‘esc’ work? I could have sworn I implemented that as a shortcut but I could be misremembering.

**Comment by josieg** [comment]
Ah yes that works! Thanks!

**Comment by SteelWagstaff** [comment]
I'm going to close this issue. Thanks for writing it up, Josie and for `solving` it, Ned!
