### ISSUE TITLE
Investigate the importer issue causing #1588

### ISSUE THREAD

**Issue by SteelWagstaff** [pressbooks/pressbooks#1662]
Investigate whether the importer issue causing #1588 is caused by XSLT or not. If not, fix it!

**Comment by connerbw** [comment]
Caused by XSLT, sorry to disappoint.

> `<!-- @TODO This currently sucks, and needs improvement -->`
https://github.com/pressbooks/pressbooks/commit/038b0dc54bb17ba91566f3a860b04c00d67cefbd
