### ISSUE TITLE
Enable a two-level TOC

### ISSUE THREAD

**Issue by sswettenham** [pressbooks/pressbooks#168]
Host - PleskLinux56.webnames.ca -
Server - LiteSpeed
Wordpress 4.2.2
mysqli 5.1.73
PHPv 5.6.1 - memory_limit 256M 
php_value memory_limit 512M

Pressbooks 2.5.1
Pressbooks Textbook 1.2.10

Two Level TOC not expanded on "Visit Site" view.
New site view is not expanding:
![not expanded](https://cloud.githubusercontent.com/assets/360534/8621451/d7d21e7e-26e2-11e5-9759-ea1c80dd3d47.png)

But ironically old problematic site did present correctly:
![correct view](https://cloud.githubusercontent.com/assets/360534/8621458/e5c2e36a-26e2-11e5-845c-11022e31701e.png)

Any solutions?

**Comment by greatislander** [comment]
@sswettenham That first screenshot looks like a chapter rather than the index page which should have the Pressbooks-generated TOC. Can you send me the URL so I can take a look? (If the book is public.)

**Comment by sswettenham** [comment]
http://on-linelearning.ca/epub/clinical-teaching/

**Comment by sswettenham** [comment]
Old Site: http://on-linelearning.ca/ebooks/clinical-teaching/

**Comment by greatislander** [comment]
@sswettenham It looks like this book was not properly activated. The index is supposed to be set to a page called "Cover" which is created in the function [here](https://github.com/pressbooks/pressbooks/blob/dev/includes/class-pb-activation.php#L133). Was this book displaying the cover properly before you upgraded to the new versions of Pressbooks & Pressbooks Textbook? Is it possible for you to export the book to Pressbooks XML, create a new book and re-import?

**Comment by sswettenham** [comment]
Was this book displaying the cover properly before you upgraded to the new versions of Pressbooks & Pressbooks Textbook?
--- UNKNOWN

WORKAROUND SOLUTION:
RE-IMPORT TEST displayed correctly - http://on-linelearning.ca/epub/test/

ALTERNATE TRIALS:
I tried re-activating theme and site but neither solved the issue.
Unable to find a quickfix to existing site.

**Comment by greatislander** [comment]
This issue hasn't appeared on any of our production sites to my knowledge. I believe there is a way to trigger the initialization function on an existing book—I will investigate and let you know.

**Comment by sswettenham** [comment]
FYI - Book Information not exported with PressBooks XML when I did the RE-IMPORT TEST

**Comment by greatislander** [comment]
I'm going to close this as it seems to be an issue with a corrupted install rather than a traceable bug. Sorry for the trouble.
