### ISSUE TITLE
Users unable to reset password and log in

### ISSUE THREAD

**Issue by mcgratay** [pressbooks/pressbooks#1683]
### Prerequisites

* [x] Can you reproduce the behavior you wish to address with [all other plugins deactivated](http://codex.wordpress.org/Multisite_Network_Administration#Plugins)?
* [x] Are you running the [latest version of Pressbooks](http://github.com/pressbooks/pressbooks/releases/latest/) and the [latest version of WordPress](http://codex.wordpress.org/Upgrading_WordPress)?
* [x] Are you experiencing this issue with one of our built-in root or book themes?
* [x] Did you [perform a cursory search](https://github.com/issues?q=+is%3Aissue+repo%3Apressbooks%2Fpressbooks) to see if your bug or enhancement is already listed?

### Description

Users who forget their password are unable to reset it and log in. Two circumstances sometimes occur: 

1. The user is sent more than one password reset link. The initial reset link leads to the confirmation page but the page only gives the user an error 

2. The user enters a new password and confirms it but is redirected to a login page with an error, even though the password has successfully been saved  

Error does not seem to be consistent and may target some domains more than others. 

### Steps to Reproduce

1. Click "Sign In" on a network homepage, then "Lost Your Password?" underneath the sign in form 
2. Fill in the details for an existing account on that network and attempt to reset the password
3. See if it's successful

**Expected behavior:** Users can successfully reset their password an access their account every visit

**Actual behavior:** Users are sometimes stuck in the password reset system and can't access their account

**Comment by SteelWagstaff** [comment]
@mcgratay, do you have a sense of how widely has this been reported and on how many different networks?

**Comment by connerbw** [comment]
Probably: https://core.trac.wordpress.org/ticket/38769

**Comment by connerbw** [comment]
Also: https://core.trac.wordpress.org/ticket/45367
