### ISSUE TITLE
Glossary tooltips no longer displaying upon hover

### ISSUE THREAD

**Issue by SteelWagstaff** [pressbooks/pressbooks#1685]
### Description
Rollovers with tooltips no longer appear when links for glossary terms are hovered over.

### Steps to Reproduce

1. Create glossary term
2. Publish chapter
3. Visit published chapter and roll mouse over the glossary term.

To see an example, check https://university.pressbooks.pub/latex/chapter/chapter-1/

**Expected behavior:** 
A tooltip containing the glossary definition used to appear when a user hovered over the glossary term (i.e. before the user clicked the link to display the glossary definition).

**Actual behavior:** 
No tooltip is displayed upon hover.

**Comment by greatislander** [comment]
This was a deliberate change on my part; the UX of trying to select text in a hovered term was (in my opinion) very bad, so I decided instead to make the terms appear on click or focus only.

**Comment by SteelWagstaff** [comment]
Thanks for explanation, @greatislander. I also noticed that we still provide similar tooltips when a footnote link is hovered over. 
![Screen Shot 2019-04-24 at 7 38 53 PM](https://user-images.githubusercontent.com/13485451/56702259-bf456800-66c8-11e9-9615-981543963ff0.png)
Does that feel like similarly bad UX to you, or would you make a different argument in that case? I personally like the tooltip upon rollover/hover in both cases, as it can save some users a click, but am open to other points of view.

**Comment by greatislander** [comment]
Honestly, I didn't know footnotes had the full content in a tooltip, and now I don't know what to think anymore. Certainly the browser-native tooltips provided by footnotes are not selectable (at all) and as such have worse UX than even the glossary ones did.

**Comment by greatislander** [comment]
Also relevant, re: `title` attributes: https://www.24a11y.com/2017/the-trials-and-tribulations-of-the-title-attribute/

**Comment by greatislander** [comment]
More, less diplomatic: https://axesslab.com/title-texts-suck/
