### ISSUE TITLE
Greyscale not rendering correctly in PDF files 

### ISSUE THREAD

**Issue by mcgratay** [pressbooks/pressbooks#1687]
### Prerequisites

* [x] Can you reproduce the behavior you wish to address with [all other plugins deactivated](http://codex.wordpress.org/Multisite_Network_Administration#Plugins)?
* [x] Are you running the [latest version of Pressbooks](http://github.com/pressbooks/pressbooks/releases/latest/) and the [latest version of WordPress](http://codex.wordpress.org/Upgrading_WordPress)?
* [x] Are you experiencing this issue with one of our built-in root or book themes?
* [x] Did you [perform a cursory search](https://github.com/issues?q=+is%3Aissue+repo%3Apressbooks%2Fpressbooks) to see if your bug or enhancement is already listed?

### Description

Users are reporting that printers and print-on-demand services are rejecting their files when they've specified that images are in greyscale and have uploaded only greyscale images into their books. 

Reports include the following details: 
- images are in CMYK 
- ICC color should be turned off and greyscale adjusted
- color conversion may be affected by PDF/X value

Users report that this has never been flagged before with similar files submitted to the same printer. 

### Steps to Reproduce

1. Create a book 
2. Upload greyscale images to a chapter and save
3. Upload greyscale image to the cover generator and save
4. Export the cover
5. Export the print PDF
6. Test if it can be accepted to a common print service as a greyscale file

**Expected behavior:** Greyscale images render in PDFs as greyscale. 

**Actual behavior:** Greyscale images render in PDFs as CMYK.

**Comment by connerbw** [comment]
Nothing has changed. No bug. The problem was the images, not the PDF export process.

Command line tools I used: `identify` (From ImageMagick), `pdfinfo` and `pdfimags` (From Poppler Utils), `exiftool` (reads information in a wide variety of files)

Two very similar images were uploaded: The original and an edit. The edit had an ICC profile embedded into it.
