### ISSUE TITLE
Update site/admin footers following website launch

### ISSUE THREAD

**Issue by SteelWagstaff** [pressbooks/pressbooks#1690]

**Comment by SteelWagstaff** [comment]
Moved to private repo

**Comment by SteelWagstaff** [comment]
See https://docs.google.com/document/d/1fzBWojJhg7anIolEXkodAMC2O80-THAs7jeIPiQzK_Q/edit?usp=sharing for details

**Comment by mcgratay** [comment]
Admins have the ability to disable the contact form, so if the contact form is disabled
- the contact link on the root site footer does nothing, and
- the contact link on the admin footer takes you to the root site homepage

If this is the expected behavior, then this task is complete.

**Comment by PressbooksLiz** [comment]
- the contact link on the root site footer does nothing, and
(this is not ideal, but I can live with it - would be better if link became not a link, or linked to home page)
- the contact link on the admin footer takes you to the root site homepage
(this is okay)

**Comment by SteelWagstaff** [comment]
An admin option to allow network managers to add a custom URL for the support link is a candidate for a future sprint. Until that time, I'm ok with the functionality (or lack thereof) described here.
