### ISSUE TITLE
Footnote links suggestions for accessibility

### ISSUE THREAD

**Issue by beckej13820** [pressbooks/pressbooks#1693]
### Feature Description

For the last two days in SUNY OER, we had training with My BlindSpot, a group of accessibility advocates who are also pro users of screen readers. They had a couple of suggestions about the implementation of footnotes in Pressbooks.

They were looking at the links that are generated, and they thought that they should add an aria label to the footnote link as it appears in the body of the text. They felt that the number only that was announced in the text might not be enough to provide context. They suggested to use an Aria statement to announce "footnote 1"

Finally, they were impressed that there was a link after each footnote to return you to the text where you had left off, but they thought that another Aria attribute would enhance that link with text similar to "return to text"

### Feature Use Case

Improving accessibility

**Comment by SteelWagstaff** [comment]
Thanks for the suggestions, Ed. These look like great ideas.

**Comment by mcgratay** [comment]
Resolved.
