### ISSUE TITLE
investigate adding table class dropdown to tinymce button

### ISSUE THREAD

**Issue by hughmcguire** [pressbooks/pressbooks#171]
usecase:
- client uses 3 different kinds of tables, say (borders/shaded/something else)
- in the TinyMCE tables button -- have a dropdown to add a class
- in markup will then be: 

     `<table class="x">`
     `etc.`
     `</table>`

details of what classes are & what they should be called to come!

**Comment by greatislander** [comment]
Hide properties as well. To investigate.

**Comment by hughmcguire** [comment]
To discuss... this is a client feature, so would like to get to it sooner rather than later.

**Comment by hughmcguire** [comment]
OK, so the proposal is: to add a mechanism to add an arbitrary class to a table, using the dropdown? 
is that correct? 

(you can currently do similar in the current plugin, though it's very unclear how the various tools work, eg: 
Table >> Table Properties >> Advanced 

Gives you fields you can fill in. So, we would either: 
a) remove some of the current options in the set-up 
or
b) just add a new field with "Table Type" (probably clearer for humans than "table class") ...

and then we'll need to give documentation regarding table classes.

**Comment by greatislander** [comment]
Ready for you to test on Textopress.
