### ISSUE TITLE
Full glossary list alphabetizes capitalized terms separately from uncapitalized terms 

### ISSUE THREAD

**Issue by mcgratay** [pressbooks/pressbooks#1719]
### Prerequisites

* [x] Can you reproduce the behavior you wish to address with [all other plugins deactivated](http://codex.wordpress.org/Multisite_Network_Administration#Plugins)?
* [x] Are you running the [latest version of Pressbooks](http://github.com/pressbooks/pressbooks/releases/latest/) and the [latest version of WordPress](http://codex.wordpress.org/Upgrading_WordPress)?
* [x] Are you experiencing this issue with one of our built-in root or book themes?
* [x] Did you [perform a cursory search](https://github.com/issues?q=+is%3Aissue+repo%3Apressbooks%2Fpressbooks) to see if your bug or enhancement is already listed?

### Description

The glossary tool sorts capitalized terms separately from uncapitalized terms. Order priority goes to all capitalized terms. The first uncapitalized term will not appear until all the capitalized terms have been listed. 

![Screen Shot 2019-06-04 at 3 02 11 PM](https://user-images.githubusercontent.com/39064028/58906361-bd17f580-86d9-11e9-97c0-c97d6eb5a45d.png)

Example: https://glossaryalphabeticbug.textopress.com/back-matter/glossary/

Related: Issue #1711 

### Steps to Reproduce

1. Add a number of capitalized and uncapitalized terms to your test book
2. Ensure these terms are all set to "Show in Glossary List" 
3. Go to **Organize** and create a new back matter post 
4. Set Back Matter Type to "Glossary" and leave the editor blank, then save the chapter
5. View the glossary in webbook or other formats to see if terms have properly alphabetized. 

**Expected behavior:** All terms order themselves alphabetically regardless of capitalization

**Actual behavior:** All capitalized terms alphabetized separately from all uncapitalized terms

**Comment by connerbw** [comment]
https://github.com/pressbooks/pressbooks/blob/23b6d3abb2c76183722ad0cb271607177124dc0d/inc/shortcodes/glossary/class-glossary.php#L166

Try changing to `SORT_NATURAL | SORT_FLAG_CASE`

See: https://www.php.net/manual/en/function.sort.php
