### ISSUE TITLE
Unable to trash Export of ODT

### ISSUE THREAD

**Issue by sswettenham** [pressbooks/pressbooks#173]
Method:
1. select ODT in export
2. blank display with email error:
Array
(
   [time] => Fri Jul 10 22:43:22 2015
   [user] => administrator
   [site_url] => http://.../clinical-teaching
   [blog_id] => 2
   [theme] => Open Textbooks
   [url] => http://.../clinical-teaching/format/xhtml?timestamp=1436568199&hashkey=8f9a2a778b7470b6547a68c88532ff84
)
Transformation failed

Screen output attempting to trash but does not:
![odt_exportlocked](https://cloud.githubusercontent.com/assets/360534/8631122/1cf3abcc-272d-11e5-9639-2bd0b953b0b8.png)

**Comment by sswettenham** [comment]
Other persistent symptom is that the list of exports continues:
![export creative clinical teaching in the health professions pressbooks 2015-07-11 08-33-40](https://cloud.githubusercontent.com/assets/360534/8638753/0a941074-2882-11e5-8b81-84b1b1630bf6.png)

**Comment by greatislander** [comment]
Hi @sswettenham, thanks for noticing this. It looks like the ODT export failed and there were some extraneous files left behind. I've updated the plugin to handle failed ODT exports more gracefully. I will push out a release on WordPress.org that does this in the next few days, but I would appreciate your help testing. If you download the [latest GitHub version](https://github.com/pressbooks/pressbooks/archive/dev.zip) and replace Pressbooks on your server with it, you should be able to clear that lingering file by exporting a fresh ODT.

**Comment by sswettenham** [comment]
Pressbooks v.2.5.2 and PressBooks Textbook v.1.2.13
ODT Export issue corrected on Export “Pressbooks New” page.

email error message is definitive:
Array
(
   [time] => Thu Jul 16 17:30:57 2015
   [user] => administrator
   [site_url] => http://.../.../newsite
   [blog_id] => 2
   [theme] => Open Textbooks
   [url] => http://.../.../newsite/format/xhtml?timestamp=1437067857&hashkey=89529a8aa0c7fe94d2dd2a1218b90107
)
Transformation failed
