### ISSUE TITLE
Apply a11y fixes made upstream by extended-cpts plugin

### ISSUE THREAD

**Issue by SteelWagstaff** [pressbooks/pressbooks#1732]
We recently reported some a11y issues upstream. One of [these bugs](https://github.com/johnbillion/extended-cpts/issues/119) was recently fixed by the maintainers of the Extended CPTs plugin, which now adds explicit form field labels where appropriate (see https://github.com/johnbillion/extended-cpts/commit/f10cec188175c728bcbc8b037a149e96bd0aaa7c). We should include this fix in a forthcoming product release.

**Comment by connerbw** [comment]
Removed our javascript fix in: https://github.com/pressbooks/pressbooks/commit/e87bdc79526165a9aac548674e99e33892d79618

Extended-cpts 4.2.4 does it like this now:

![image](https://user-images.githubusercontent.com/812192/60026866-682d2680-966a-11e9-9226-6679a769b42e.png)

**Comment by mcgratay** [comment]
Resolved.
