### ISSUE TITLE
Upgrade jenssegers/blade

### ISSUE THREAD

**Issue by connerbw** [pressbooks/pressbooks#1734]
We're currently using `jenssegers/blade` 1.1.0 which uses Blade templates 5.4.

The new version uses Blade Templates 5.5.

When we started using `jenssegers/blade` we replaced Pimple with Illuminate Container 5.4 because it is a required dependency and we didn't want two containers.

To keep backwards compatibility with Pimple we overrode the new container:

+ https://github.com/pressbooks/pressbooks/blob/dev/inc/class-container.php

Version 5.5 of Illuminate Container breaks our class because `static function get( $var ) {` which wasn't there before, is not static, and it doesn't do the same thing.

This can be fixed by deprecating Pimple and changing all `Container::get()` functions with `resolve()` I.e. Move both of these into our functions.php file.

+ https://github.com/laravel/framework/blob/c0f28b4266e0d419631310f9c09e7ece3982df47/src/Illuminate/Foundation/helpers.php#L96

+ https://github.com/laravel/framework/blob/c0f28b4266e0d419631310f9c09e7ece3982df47/src/Illuminate/Foundation/helpers.php#L732

This affects many lines of code in a few of our plugins and themes.

**Comment by SteelWagstaff** [comment]
Would be nice to update to Blade 8 for future gains.

**Comment by SteelWagstaff** [comment]
I think maybe closed by mistake @cmurtagh?

**Comment by cmurtagh** [comment]
Yeah, I'm not sure what I did to close this. All I meant to do was merge the upstream bedrock changes.

**Comment by greatislander** [comment]
This may no longer be relevant based on the conversation last week. Assigning it to you all regardless.
