### ISSUE TITLE
Recursion in PDF Export when setting locale

### ISSUE THREAD

**Issue by bseeger** [pressbooks/pressbooks#175]
I'm using Pressbooks version 2.5

I'm seeing recursion during exporting in PDF format:

In plugins/pressbooks/hook.php:
if ( \PressBooks\Book::isBook() && \PressBooks\l10n\use_book_locale() ) {
        add_filter( 'locale', '\PressBooks\Export\Export::setLocale' );
} else {
        add_filter( 'locale', '\PressBooks\L10n\set_locale' );
}
My code executes the 'if' portion above, adding the \PressBooks\Export\Export::setLocale to the filters.

Then later, when the filter is applied, the export's setLocale() calls into getBookInformation() (/plugins/pressbooks/includes/modules/export/class-pb-export() line 713), which then again, applies filters:

plugins/pressbooks/includes/class-pb-book.php line 104:
$val = apply_filters( 'the_content', $val );

And the recursion begins...

My work around is to skip the 'if' clause above and just use what's in the 'else' part of. Is there something in our setup that's causing this recursion?

**Comment by greatislander** [comment]
Thanks for noting this issue, @bseeger. Will investigate.

**Comment by greatislander** [comment]
@connerbw Hi Dac—wondering if you have any insight on this? I've tried to wrap my head around this but I'm not sure why it's set up the way it is. Thanks in advance.

**Comment by connerbw** [comment]
It's setup like this so that if a user has their locale set to French, but
they want to export a book written in Spanish, then  the underlying
translation for things like "Chapter" or "Table of Contents" will be
correct.

I can't speak for what changed but that's the "why"

Good luck.

**Comment by greatislander** [comment]
Hi @bseeger: can you check out https://github.com/pressbooks/pressbooks/tree/fix-locale-recursion and see if this resolves the issue? We don't really need to be applying all `the_content` filters on https://github.com/pressbooks/pressbooks/blob/dev/includes/class-pb-book.php#L104, as this is just preparing two blocks of custom text for output. I have substitude `wpautop()` and `wptexturize()` for the `apply_filters()` routine here and I believe this should prevent the recursion you encountered.

**Comment by bseeger** [comment]
Yes, I was able to successfully run with the changes you put in the class-pb-book.php file.   Not seeing the recursion anymore.   Thank you!
