### ISSUE TITLE
Feature Request: Add new privacy option: Set user role that is allowed to view private chapters

### ISSUE THREAD

**Issue by marcusschiesser** [pressbooks/pressbooks#176]
Per default private chapters in public books are only visible to users with role Editor or Administrator.

To make this more configurable, add a new option in the admin menu at Utilities/Privacy Settings (URL: /wp-admin/options-general.php?page=privacy-options) for each blog. Using the new option the admin can decide which user roles are entitled to view private chapters.

The option would be a dropdown menu where the user could select one of the following user options: 

Subscriber or better
Author or better
Editor and Administrator (default selection)
Just Administrator

The label of the dropdown menu will be :'User roles entitled to view private chapters'

The new option will only be visible, if Site Visibility is set to public.

Depending on the selection the entitlement for private chapters will change accordingly.

For implementation, take a look at the following commits:
https://github.com/pressbooks/pressbooks/commit/8dbb0eced4b2bf9b47e95ea33cdc0727e54d5c70
https://github.com/pressbooks/pressbooks/commit/d44ef0ac8caae3a4456d7f87ef66478a261f5d7f

Most likely these files have to be modified.

**Comment by marcusschiesser** [comment]
@greatislander: as this feature is probably not on your roadmap, I am happy to implement it, if you would merge it to your release

**Comment by greatislander** [comment]
To clarify, the use case is:

1. Book is public.
2. Certain chapters are private.
3. You want to be able to add users as Subscribers who can view *all* content in the book, including the private chapters, overriding the default `read_private_posts` capability which restricts private posts to Editors and Administrators only.

If @hughmcguire agrees—and I can see this being useful for other users—I will implement this as an option under privacy settings, though I would suggest (if you agree) that I simplify this by making the option for Subscribers and up to view private content a simple on/off toggle (defaulting to off). Something like:

> 🔘 Allow all users assigned to this book to view private front matter, chapters and back matter?
> *By default, only users with Editor and Administrator privileges can view sections marked as private.*

Let me know if this would work.

**Comment by marcusschiesser** [comment]
yes, this functionality would also be fine for me. So you're going to implement it? If so any idea by when it would be commited?

**Comment by greatislander** [comment]
I am waiting on approval from @hughmcguire but unless he has any issues I should be able to implement within the week.

**Comment by marcusschiesser** [comment]
great, looking forward to it.

On Wed, Jul 15, 2015 at 9:14 PM, Ned Zimmerman <notifications@github.com>
wrote:

> I am waiting on approval from @hughmcguire
> <https://github.com/hughmcguire> but unless he has any issues I should be
> able to implement within the week.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pressbooks/pressbooks/issues/176#issuecomment-121718479>
> .
>



-- 
Marcus Schiesser
Email: mail@marcusschiesser.de

http://www.marcusschiesser.de

**Comment by hughmcguire** [comment]
why not make it make explicut radio button choice, something like: 

who can see private posts:
- everyone including subscribers [x]
- only editors and administrators [o]

**Comment by marcusschiesser** [comment]
Sounds good for me too

**Comment by greatislander** [comment]
This is done and will be released next week in Pressbooks 2.5.3. @hughmcguire, if you want me to tweak the language please advise.

![privacy_settings_ _the_hobbit_ _pressbooks](https://cloud.githubusercontent.com/assets/605361/8762943/dd501640-2d5d-11e5-9262-140cf2347798.png)
