### ISSUE TITLE
Feature Request: Possibility to set Book Parts private

### ISSUE THREAD

**Issue by marcusschiesser** [pressbooks/pressbooks#177]
If a book is public, it is possible to set chapters as private, but parts are always public. 

Imagine a part where all chapters are set to private, then every user is still able to read the main page defined in the part. This behaviour might not be desired, so it should be possible to set a part as private.

If a part is set as private, all its chapters must be private too.

Also if a part is set to private the privacy option specified in #176 must also apply.

**Comment by greatislander** [comment]
Thanks for the feature request. I will review this with @hughmcguire and let you know.

**Comment by hughmcguire** [comment]
agree that described behaviour is preferable. so, yes to this.

**Comment by hughmcguire** [comment]
oops i guess this is over to you ned.

**Comment by hughmcguire** [comment]
but maybe ... #209 fixes this?

**Comment by greatislander** [comment]
No, he just opened a duplicate. It isn't fixed yet.
