### ISSUE TITLE
Admin Navigation Regions Semantic Ordering is Visually Inconsistent

### ISSUE THREAD

**Issue by avaaec** [pressbooks/pressbooks#1773]
### Steps to Reproduce

1. Go to admin interface for a book
2. From the top of the page use tab to navigate through the interactive elements of the page
3. Notice that although the Toolbar region visually appears above the Main Menu region, it is after the Main Menu region in the tab order.

**Expected behavior:** 
It is expected that the tab order of the page follows the elements of the page from top to bottom and left to right. To make the Main Menu region easier to reach for keyboard users a "Skip to Main Menu" link can be added to the top of the page.
**Actual behavior:** 
The navigation regions of the page are semantically ordered in the DOM in a different order than they appear visually. Although I assume that this ordering was done intentionally to make the Main Menu region More discoverable and easy to reach, it does so at the cost of creating a splinter between the experience of mouse users and keyboard users and breaking the expectations of visual keyboard users.

**Comment by avaaec** [comment]
This is a UW ATS priority 1 issue

**Comment by SteelWagstaff** [comment]
> Consider the Admin Bar. Up to now, it’s been loaded with the wp_footer hook:

`add_action( 'wp_footer', 'wp_admin_bar_render', 1000 );`

In WordPress 5.4, the Admin Bar loads in the hook wp_body_open(new since WP 5.2) and fixes that source-order problem:

`add_action( 'wp_body_open', 'wp_admin_bar_render', 0 );`

Of course, some older themes don’t yet support the wp_body_open hook. For them, there’s a fallback in the wp_footer function:

```
function wp_footer() {
    /*
     * Sets up the Admin Bar if the current theme does not use `wp_body_open`.
     * @since 5.4.0
     */
    if ( ! did_action( 'wp_body_open' ) ) {
        add_action( 'wp_footer', 'wp_admin_bar_render', 1000 );
    }
}
```
>See the relevant Trac ticket: [#47053](https://core.trac.wordpress.org/ticket/47053)

https://make.wordpress.org/core/2020/02/26/miscellaneous-developer-focused-changes-in-wordpress-5-4/

**Comment by SteelWagstaff** [comment]
@greatislander could I get your eyes on this when you have a minute? Happy to discuss in upcoming product meeting as well. What if anything ought we to change to benefit from this change? Only potentially relevant code I see in Pressbooks currently is https://github.com/pressbooks/pressbooks/blob/3043f6efc5d6cda672d643c38a97a4fb54876d5d/hooks.php#L174-L175 ...

**Comment by SteelWagstaff** [comment]
This has been fixed in WordPress and inherited by Pressbooks.
