### ISSUE TITLE
Nested Headings in Admin Interface Broken Hierarchy

### ISSUE THREAD

**Issue by avaaec** [pressbooks/pressbooks#1775]
### Steps to Reproduce

1. Navigate to the admin interface for a book
2. Navigate to the "My Catalog" page
3. Notice that the headings jump from H1 to H4
3. Navigate to the "Exports" page
3. Notice that there are two H1 elements on the page
4. Navigate to some other pages in the admin interface and notice that there are numerous issues with the hierarchy of headings. Uh oh 

**Expected behavior:** 
Headings hierarchy should follow the spec: https://www.w3.org/WAI/tutorials/page-structure/headings/
**Actual behavior:** 
Headings do not follow the spec. :(

**Comment by SteelWagstaff** [comment]
Hi @avaaec thanks for reporting. The 'My Catalogue' page is very old (a kind of 'vestigal tail') and has problems. This is definitely one of them! You noted in the ticket that we could "Navigate to some other pages in the admin interface and notice that there are numerous issues with the hierarchy of headings." Apart from those which appear on the 'My Catalogue' page, did you have other specific instances in mind? Links/references would be very helpful for us to identify and fix.

**Comment by SteelWagstaff** [comment]
I'm asking because we did try to identify and fix nested heading and heading hieraracy issues for several pages recently (see https://github.com/pressbooks/pressbooks/issues/1632 for example). Our general a11y clean up work didn't catch the 'My Catalogue' page, unfortunately, as several of your recent tickets have made us aware. Would be ideal for us to fix as many problems at once as we can, so if you can point to other examples, we'd be very grateful.

**Comment by avaaec** [comment]
Here is a list of headings issues I have found in the admin site:
1. My Catalog: jumps from h1 to h4
2. Organize -> Glossary Terms: two Invisible headings, "Filter Glossary Terms List" and "Glossary Terms List"
3. Appearance -> Custom Styles: Jumps from h1 to h3
4. Export: Multiple level 1 headings
5. Publish: Jumps from h1 to h3
6. Media -> Library: invisible heading "attachments list"

Let me know if there is anything else I can do!

**Comment by SteelWagstaff** [comment]
Thank you! Very helpful.

**Comment by laurenray** [comment]
This is UW priority 1 issue.

**Comment by SteelWagstaff** [comment]
For #1: My catalog page. See https://github.com/pressbooks/pressbooks/blob/2965e63f1d50261ca9fc081d2ef1730255e8b764/inc/admin/class-catalog-list-table.php#L468-L479

**Comment by SteelWagstaff** [comment]
I don't see the problem with numbers 2 and 6 (in both cases there are header elements that are suppressed for sighted viewers but are explicitly made visible for users with screenreaders--this was done for accessibility reasons, I believe). As for number 4, HTML5 pages can have more than one H1 element, and the h1 elements on the export page seem well-formed and semantically reasonable to me. I'm not sure what the accessibility issue is here, and don't think we'll be changing this. 1, 3, 5 are definitely issues -- we will be fixing these soon, so thanks for catching and reporting!

**Comment by connermwallace** [comment]
University of Washington Accessibility Technology Services has inspected this issue and we have verified that it has been fixed. Version: 5.3.2.
