### ISSUE TITLE
Out of Order Form Controls in My Catalog

### ISSUE THREAD

**Issue by avaaec** [pressbooks/pressbooks#1777]
### Steps to Reproduce

1. Navigate to My Catalog in the admin interface
2. Use the keyboard to navigate to the "Add by URL" button
3. Notice that to reach the button you have to tab through the search edit field and associated button which visually appears after the "Add by URL" button
**Expected behavior:** 
Tab order should follow the visual ordering of things from top to bottom and left to right.
**Actual behavior:** 
The search field and associated button appear in the tab order before the "Add by URL" field and button, creating inconsistency.

**Comment by mcgratay** [comment]
✅

**Comment by avaaec** [comment]
This is a UW ATS priority 3 issue

**Comment by connermwallace** [comment]
University of Washington Accessibility Technology Services has inspected this issue and we have verified that it has been fixed. Version: 5.3.2.
