### ISSUE TITLE
Allow MOBI export without requiring EPUB export

### ISSUE THREAD

**Issue by greatislander** [pressbooks/pressbooks#180]
Right now, because we use an EPUB file as the basis for MOBI (Kindle) exports, we are making users select both file types even if only MOBI is desired. This should be handled under the hood instead (as is the case with PDF via Prince, which requires an XHTML export prior to processing).

**Comment by greatislander** [comment]
Your next testing assignment, @hughmcguire.

I've changed the way we handle MOBI exports so:

1. You only need to select MOBI to export a MOBI file on the export page.
2. The export routine checks if EPUB was also selected; if not, it exports an EPUB file too.
3. After the export is completed, if only MOBI was selected, the EPUB file that was exported to transform into MOBI will be quietly removed (so you will only get the MOBI export you requested).

Please try this out and let me know if it is working properly for you. Effectively, we should be testing to make sure that:

1. If EPUB and MOBI are selected, both exported files turn up where they belong.
2. If MOBI is selected but EPUB is not, only a MOBI file should be generated.

Thanks!

**Comment by hughmcguire** [comment]
testing and working as expected on dev.
