### ISSUE TITLE
Fix nlogo uploads + explore allowing SVG and MusicXML uploads with plugin sanitizer

### ISSUE THREAD

**Issue by SteelWagstaff** [pressbooks/pressbooks#1807]
See https://github.com/pressbooks/pressbooks/issues/1803 for more context

**Comment by connerbw** [comment]
Did some work on this, got stumped by https://github.com/Blobfolio/blob-mimes/issues/9

**Comment by mcgratay** [comment]
Tested with svg, nlogo, musicxml, and txt. Works fine.
