### ISSUE TITLE
Update mPDF export to use XHTML source

### ISSUE THREAD

**Issue by greatislander** [pressbooks/pressbooks#181]
As discussed in the original PR, our mPDF should ultimately use the same XHTML source as Prince to ensure feature parity.

**Comment by hughmcguire** [comment]
note this will be a @bdolor project :)

**Comment by jflowers45** [comment]
Just a heads up that we've noticed the current mPDF implementation doesn't support multi-level TOC, whereas Prince does, so you can add that to list of things to check on with regards to feature parity if/when you go down this road

**Comment by hughmcguire** [comment]
@jflowers45 in theory this would be solved by this ticket -- the multi-level TOC is generated through the xHTML output.

**Comment by jflowers45** [comment]
@hughmcguire @bdolor If custom CSS is the activated theme, would this introduce a new 'mpdf' option in the dropdown for 'You are currently editing CSS for: '  (when custom CSS is the activated theme), or were you planning to just have it use the 'PDF' one since people are probably only going to pick one of the PDF rendering engines?

**Comment by bdolor** [comment]
Since mPDF and PrinceXML require vastly different css files, using the CustomCSS file from the PrinceXML export won't work. That said, the functionality is not related to mPDF parsing the XHTML file.

**Comment by jflowers45** [comment]
@bdolor cool ... was mainly asking because I'm working on enabling a custom CSS option for mPDF on our install, and since 'feature parity' was mentioned here I thought I'd ask, but you're right - separate issue. thanks!

**Comment by hughmcguire** [comment]
@greatislander can we move these mPDF issues out of Pressbooks?
