### ISSUE TITLE
Prepare for WP 5.3

### ISSUE THREAD

**Issue by SteelWagstaff** [pressbooks/pressbooks#1813]
WordPress 5.3 is scheduled to be released on November 12th. There are six areas that specific focus should be given as plugin-related changes coming in 5.3:

- [x] Note the Admin CSS changes and recommendations for plugin authors https://make.wordpress.org/core/2019/10/18/noteworthy-admin-css-changes-in-wordpress-5-3/ as well as the reduction of block editor CSS https://make.wordpress.org/core/2019/09/27/block-editor-theme-related-updates-in-wordpress-5-3/

- [x] Note the changes to the WP_MS_Sites_List_Table class in the Networks and Sites devnote: https://make.wordpress.org/core/2019/10/15/enhancements-to-the-network-sites-screen-in-wordpress-5-3/

- [x] Note the potential impact if you extend certain classes and overload certain methods in the spread operator devnote: https://make.wordpress.org/core/2019/10/09/wp-5-3-introducing-the-spread-operator/ _(In only one case – wpdb::prepare() -, WP 5.3 has changed an existing parameter. A plugin we use on Pressbooks dot com could be impacted: https://github.com/stuttter/ludicrousdb/releases )_

- [x] Note the support for PHP 7.4 and recommendation to add the PHPCompatibility checker to your toolkit to help detect PHP version compatibility issues in the PHP 7.4 devnote: https://make.wordpress.org/core/2019/10/11/wordpress-and-php-7-4/
 
- [x] Note the changes to wp_die() and need to update PHP calls in the related devnote: https://make.wordpress.org/core/2019/10/15/changes-to-wp_die-html-output-in-wordpress-5-3/

- [x] Note the various plugin recommendations in the miscellaneous changes devnote: https://make.wordpress.org/core/2019/10/15/miscellaneous-developer-focused-changes-in-5-3/

**Comment by connerbw** [comment]
> Note the Admin CSS changes and recommendations for plugin authors

We maintain this repo, it's where our admin colors come from, updates should probably go in there:

https://github.com/pressbooks/wp-admin-colors

**Comment by cagp-dev-mtl** [comment]
I have gone through the checklist, these are my comments:

1) Pressbooks team needs to decide if we accept or adapt the new accessibility WP changes that are not compatible with our current branding colorset or if we rollback those changes by overriding the affected classes with the styles of the previous WP version.

2) We are not extending class `WP_MS_Sites_List_Table` in our codebase.

3) I confirm that `https://github.com/stuttter/ludicrousdb` does not overloads method 'prepare' of class 'wpdb'.

4) Currently 'PHPCompatibility checker' has support up to PHP 7.3, once PHP 7.4 is released and 'PHPCompatibility checker' supports it, we can perform a full check in our codebase.

When performing a full analysis of our code against PHP 7.3, we have the following valid warning:

```
FILE: /srv/www/pressbooks.test/current/web/app/plugins/pressbooks/inc/admin/diagnostics/namespace.php
-----------------------------------------------------------------------------------------------------
FOUND 0 ERRORS AND 1 WARNING AFFECTING 1 LINE
-----------------------------------------------------------------------------------------------------
 139 | WARNING | INI directive 'safe_mode' is deprecated since PHP 5.3 and removed since PHP 5.4
-----------------------------------------------------------------------------------------------------
```
5) Our WP_die() implementations are compatible with the new `<div>` wrapper that replaces `<p>`. E.g.:
![WP_die type 1](https://user-images.githubusercontent.com/8563418/69277156-c32d6000-0bad-11ea-84ad-b18549113b61.png)
![WP_die type 2](https://user-images.githubusercontent.com/8563418/69277157-c32d6000-0bad-11ea-90aa-1a11ad91b84c.png)

6) Misc Recommendations list some improvements and changes that do not affect our current implementation.
