### ISSUE TITLE
Punctuation in right-to-left scripts is displaced in the editor and all book formats

### ISSUE THREAD

**Issue by mcgratay** [pressbooks/pressbooks#1815]
### Description

Right-to-left languages can be used on Pressbooks when users add the script to their books via their Global Theme Options. One example is Hebrew. However, though the script will appear fine in the webbook and export formats, the editor automatically moves all punctuation to the location it would be in a left-to-right directed paragraph: the right end of the last line. 

Attempts to place a period at the (left) end of a sentence will automatically place it at the (right) beginning of the last line. 

Using your browser settings to change text direction from ltr to rtl does fix the display, but only until the chapter is saved. 

The punctuation, correct when copied from another document, shifts as soon as the paragraph is copy/pasted into the editor. There's no markup in the text editor to indicate why. 

Adding or removing the script from the global theme options doesn't impact the punctuation issue in the editor. 

This issue impacts all supported book formats. 

![Screen Shot 2019-10-25 at 11 33 10 AM](https://user-images.githubusercontent.com/39064028/67584267-3c56a600-f71b-11e9-8d36-bf236d0d083c.png)

Example: https://hebrewtext.textopress.com/ 

### Steps to Reproduce

1. Try to write or copy Hebrew (or another rtl script) into Pressbooks 
2. Attempt to add punctuation to the end of the rtl paragraph 
3. Go to **Appearance > Theme Options > Global Options** and add script support for the language you've used, then save changes 
4. Export in all supported formats, incl webbook, and view 

**Expected behavior:** Punctuation appears where it is typed

**Actual behavior:** Punctuation at the end of an rtl paragraph is displaced

**Comment by mcgratay** [comment]
Resources (from Steel): 

https://codex.wordpress.org/Right_to_Left_Language_Support 
https://en.forums.wordpress.com/topic/punctuation-marks-in-hebrew-left-to-right-language/#post-2422109
https://wordpress.org/plugins/wp-rtl/

**Comment by SteelWagstaff** [comment]
See https://github.com/pressbooks/ideas/issues/234

**Comment by SteelWagstaff** [comment]
Sprint goal: research this issue, and propose solution w/ estimate. If very simply, then fix; if not, workarounds welcomed.

**Comment by ho-man-chan** [comment]
Possible Solution without modification using browser:

Steps:
1. Right click on text fields and text areas in a page.
2. See a "Writing Direction" context menu.
3. Choose between "RTL", "LTR" or "Default".
4. Temporarily change the writing direction of the text field for reading convenience.

![image](https://user-images.githubusercontent.com/21694293/73008570-ce368380-3ddc-11ea-86d6-4805118ca390.png)

**Comment by SteelWagstaff** [comment]
Awesome! 
Questions I have: 1) what browsers is this writing direction feature available in? and 2) does this address the punctuation being placed at wrong end of sentence issue (in visual editor, webbook, exports, etc)?

**Comment by ho-man-chan** [comment]
1. In a chrome browser. But most browsers seems to support it as well.

2. It will have to confirm with you later.

**Comment by SteelWagstaff** [comment]
Apparently you can use the shortcut `ctrl+shift+x` in Firefox. For most Windows programs (including MS Word, Internet Explorer, and Notepad), you can use the following shortcuts to switch direction:
For right-to-left, press: Ctrl + Right.Shift
For left-to-right, press: Ctrl + Left.Shift

I don't know about other browsers. https://www.w3.org/International/questions/qa-html-dir may also be a userful resource?

**Comment by ho-man-chan** [comment]
Created a new format in editor called 'Write right to left' and 'Write left to right', which adds a CSS style `direction: rtl` or `direction: ltr` to content. 

See video link below for a demonstration:

https://drive.google.com/file/d/1LgBjI60-LfRH03ckuTFmMF_hKXQ9Ky_i/view?usp=sharing
