### ISSUE TITLE
Make 'Save Book Information' box sticky

### ISSUE THREAD

**Issue by SteelWagstaff** [pressbooks/pressbooks#1822]
The book info page contains a 'Save Book Information' box. When users have set screen options to 2 column and are viewing the page at sufficient width, this box sits at the top right of the page (CSS rules target `#post-body.columns-2 #postbox-container-1`). 

![Screenshot from 2019-11-03 14-28-16](https://user-images.githubusercontent.com/13485451/68091501-390f9880-fe46-11e9-87a5-4a5c20d5798a.png)

For better UX, it should be made sticky as the user scrolls down a very long page. See https://alligator.io/css/position-sticky/ and https://caniuse.com/#feat=css-sticky for some implementation ideas.

**Comment by SteelWagstaff** [comment]
Quick & dirty CSS (for wide page views): 
`position: fixed; z-index: 1; right: 20px; margin-right: 0; float: none;`

**Comment by mcgratay** [comment]
👍
