### ISSUE TITLE
Allow import/export of contributor lists

### ISSUE THREAD

**Issue by SteelWagstaff** [pressbooks/pressbooks#1824]
As a network manager, I want to be able to quickly export a list of contributors from one book and import them into another book so that I can attribute them on my book info page in that second book. This will be especially helpful in situations where a large group of people were involved in multiple book projects which are not clones of each other.

To make this possible, we should 1) add a 'Download' option to 'Bulk Actions' on the contributors page (would ideally produce a CSV or JSON file) and 2) add an import option that allows users to upload downloaded contributor lists and bulk create contributors from existing files. See pressbooks/ideas#82 and pressbooks/ideas#205 for similar ideas.

**Comment by fdalcin** [comment]
### Update

- [ ] add a 'Download' option to 'Bulk Actions' on the contributors page
- [ ] generate a CSV or JSON file when downloading contributors
- [ ] add an import option that allows users to upload downloaded contributor lists and bulk create contributors from existing files

**Comment by fdalcin** [comment]
### Update

It's now possible to import a list of contributors. The only remaining step is to add some tests to keep code coverage.

https://images.zenhubusercontent.com/9209369/e0c2ced3-de93-484d-95d9-9e2b1a089973/screen_recording_2021_09_02_at_18_13_53.mov

**Comment by richard015ar** [comment]
I tested on integrations using the same cases than https://github.com/pressbooks/pressbooks/pull/2356#issuecomment-915430224
and it works as expected. It is ready to deploy to Production. Thank you @fdalcin!
