### ISSUE TITLE
Shortcode within shortcode testing for 3 specific situations

### ISSUE THREAD

**Issue by SteelWagstaff** [pressbooks/pressbooks#1826]
Explore what adding a shortcode in a shortcode looks like and what we should know before adding support for this with any existing tools for these three specific examples: 

1. [latex] inside of [footnote] + [blockquote]
1. [media]/[caption] inside of [glossary] and 
1. [footnote] instead of [textbox]. 

Can we get these working?

See: https://stackoverflow.com/questions/4773186/shortcodes-inside-a-shortcode-wordpress + https://codex.wordpress.org/Shortcode_API + [this plugin](https://wordpress.org/plugins/nested-shortcodes/)

See https://github.com/pressbooks/ideas/issues/159

**Comment by mcgratay** [comment]
Currently the caption shortcode, which is supposed to be paired with an image, won't work inside glossary terms because the glossary editor intentionally strips out images. That falls within expected behavior. Everything else checks out.
