### ISSUE TITLE
Book Info > About the Book > Long Description missing Add Media button

### ISSUE THREAD

**Issue by sswettenham** [pressbooks/pressbooks#183]
Not sure if this a feature request or missing Add Media button.

On chapter edit pages you get an Add Media button:
![add media](https://cloud.githubusercontent.com/assets/360534/8764771/bcbedf40-2daa-11e5-9831-c5957638f9fa.png)

But on the Long Description it is missing:
![bookinfo](https://cloud.githubusercontent.com/assets/360534/8764775/e6fbf7ca-2daa-11e5-9b8b-76526e88b127.png)

**Comment by greatislander** [comment]
This is a feature request. We have not supported media in descriptions thus far. Not sure if this is something @hughmcguire would want to include.

**Comment by greatislander** [comment]
@hughmcguire, let me know what you think about this.
