### ISSUE TITLE
Build PDF footnote fix for block elements using JS hack

### ISSUE THREAD

**Issue by SteelWagstaff** [pressbooks/pressbooks#1831]
When a user creates a footnote which includes one or more HTML block elements, the footnote breaks in the XHTML and PDF exports. This happens because the footnote is currently being rendered as a `<span>`, an inline element which cannot contain block elements and remain valid HTML. For example, if an author puts a second paragraph or a block quote within a footnote, the footnote will display normally in the webbook, but not the PDF exports. Here's how the HTML in webbook looks: 
![Screenshot from 2019-12-09 13-54-04](https://user-images.githubusercontent.com/13485451/70468056-fc117400-1a8b-11ea-8fa5-b5370f167a28.png)

Here's how that same footnote renders in a PDF export:
![Screenshot from 2019-12-09 13-52-21](https://user-images.githubusercontent.com/13485451/70467640-32022880-1a8b-11ea-8e6d-242fb705dbce.png)

See footnote 1 here: https://integrations.pressbooks.network/steelstest/chapter/footnote-test/ and page 48 (54) here: https://integrations.pressbooks.network/steelstest/open/download?type=print_pdf

We cannot leave the footnote element in place and process as a `<div>` because these elements cannot live within `<p>` elements either. See https://stackoverflow.com/a/10763952. 

We've discussed in the [PrinceXML forums](https://www.princexml.com/forum/topic/4382/block-elements-in-paragraphs-footnotes?p=1#22060), where Mike Day told us:
> The tricky part is that Prince allows this via the CSS display property, but HTML syntax does not allow nesting blocks within spans and is unaware of the CSS, so it breaks the markup.

> I think it would be possible to solve this with JavaScript, in which the footnote block content is elsewhere in the document and a script moves it into place, allowing a block to be inside a span without breaking everything.

A sample implementation that we'd like to try in Pressbooks was provided by Mark Brown:

> Here's an example. The footnote elements are placed outside the `<p>` elements so as not to break the html, and are linked by another element with class "indirect". The script moves any footnotes into their correct places.

```
<script>
ind = document.getElementsByClassName("indirect");
for (var i=0; i<ind.length; i++) {
    var e = document.getElementById(ind[i].getAttribute("ref"));
    if (e) ind[i].appendChild(e);
}
</script>

<p>
A paragraph containing a footnote.<span style="float: footnote;">
    <span class="indirect" ref="fn1"></span>
</span>
Content in the same paragraph.
</p>

<div id="fn1">
    <ul>
        <li>Block content in a footnote
        <li>doesn't interrupt flow
    </ul>
</div>
```
Footnote shortcodes are processed with this code: https://github.com/pressbooks/pressbooks/blob/92bb307be76a5ee20a88e246459cac4b30403fce/inc/shortcodes/footnotes/class-footnotes.php#L70-L159

Footnotes are wrapped in `<span>` elements for the XHTML export here: https://github.com/pressbooks/pressbooks/blob/92bb307be76a5ee20a88e246459cac4b30403fce/inc/modules/export/xhtml/class-xhtml11.php#L466-L470

From [most recent PrinceXML documentation](https://www.princexml.com/doc/styling/#footnotes):
> Footnotes are created with the float property (see also Floats): an element can be removed from the normal flow of the document by styling it with the footnote value. This creates a footnote call in the place where the element would be in its natural flow, and moves the element's content to the bottom of the page. The footnote marker is rendered outside the footnote in the left margin area, and the footnote is displayed as a block element.

> The property footnote-display can be used to change the default display of footnotes: besides the default block display, they can be also treated as inline elements. The value compact leaves it up to Prince to determine whether to display the footnote as a block or inline element: if two or more footnotes fit on one line, they will be treated as inline elements to take up less space.

> Making a footnote into an inline element moves the footnote marker into the footnote box as the first inline box inside the footnote.

**Comment by connerbw** [comment]
> within the footnote in exports.

Cannot reproduce in epub or mobi. Are you sure? Please show a recent example file.

> PDF

PDF styling is with Prince using `<span>`: https://www.princexml.com/doc/styling/#footnotes

Paragraphs inside spans are invalid HTML: https://stackoverflow.com/a/23371977/1926840

Changing span to div seems to fix the issue? Caveat: Read Prince docs thoroughly, test, make sure div is a supported footnote syntax by Prince.

+ https://github.com/pressbooks/pressbooks/blob/25c372e7c5dca8b4d1d7728d0f58f087423957f7/inc/modules/export/xhtml/class-xhtml11.php#L457-L469
+ https://github.com/pressbooks/pressbooks/blob/25c372e7c5dca8b4d1d7728d0f58f087423957f7/inc/modules/export/htmlbook/class-htmlbook.php#L310-L331

**Comment by SteelWagstaff** [comment]
Yes, problem persists. See link in original post (for PDF) or view screenshot of PDF below:
![Screenshot from 2019-12-09 13-52-21](https://user-images.githubusercontent.com/13485451/70467640-32022880-1a8b-11ea-8e6d-242fb705dbce.png)

**Comment by connerbw** [comment]
Hi @SteelWagstaff 

> Yes, problem persists. See link in original post (for PDF) or view screenshot of PDF below:

> Cannot reproduce in **epub or mobi**. Are you sure? Please show a recent example file.

I did not make any changes. I gave a solution for PDF. What about  **epub or mobi**?

**Comment by SteelWagstaff** [comment]
Sorry — misunderstood the note. No, I’m not sure about EPUB/MOBI. I only encountered the error in PDF as I recall.

**Comment by SteelWagstaff** [comment]
In EPUBs and MOBI files the expected content does appear in the footnotes. Paragraph tags ar stripped out in the webbook and ebook exports however (probably because the shortcode generation process calls `wp_strip_all_tags`): https://github.com/pressbooks/pressbooks/blob/faf341a8050294dcb1dddf31cab1886d01634005/inc/shortcodes/footnotes/class-footnotes.php#L100

**Comment by connerbw** [comment]
I don't think so. IMHO that code does not do what you are describing.

**Comment by connerbw** [comment]
Let's me try again.

 + This bug is specific to PDF.
 + The reason the bug happens is because footnotes in XHTML and HTMLBook are inline, in a `<span>` tag.
   + [Other formats use a `<div>` tag.](https://github.com/pressbooks/pressbooks/blob/724daf0752d90ad6bf7ebab20c4c9b784f85cf02/inc/shortcodes/footnotes/class-footnotes.php#L139-L141)
 + The `<span>` element does not accept block element children.

I can fix the problem by changing `<span>` to `<div>`.  PrinceXML [hints at using span in their documentation](https://www.princexml.com/doc/styling/#footnotes), but changing it to div seems to work.

By doing so I may be hindering semantic HTML, possibly invalid HTML. For example, the HTMLBook spec says:

 > If you need to include multiple blocks of content in a footnote, use `<br/>` elements to delimit them, e.g.:

```html
<p>This is a really short paragraph.<span data-type="footnote">Largely because I like 
to put lots and lots of content in footnotes.<br/><br/>
For example, let me tell you a story about my dog...</span></p>
```

Source: https://oreillymedia.github.io/HTMLBook/#_footnote_endnote

**Comment by connerbw** [comment]
Problem, changing to div changes "inline" behavior:

![image](https://user-images.githubusercontent.com/812192/71119669-b1d57480-21a8-11ea-83fb-c4d1ea9ff9e9.png)

**Comment by connerbw** [comment]
Code I was playing around with before aborting:

```php

use function Pressbooks\Utility\str_ends_with;
use function Pressbooks\Utility\str_lreplace;


function convertBlockElements($content ) {
	// The <span> element does not accept block element children
	// If you need to include multiple blocks of content in a footnote, use <br/> elements to delimit them
	// TODO: Later, HTMLawed rejigs <blockquote> (and other block elements)
	$content = wpautop( $content, false );
	$content = preg_replace( '/<p[^>]*?>/', '', $content );
	$content = str_replace( '</p>', '<br /><br/>', $content );
	$content = trim( $content );
	if ( str_ends_with( $content, '<br /><br/>' ) ) {
		$content = str_lreplace( '<br /><br/>', '', $content );
	}
	return $content;
}
```

**Comment by SteelWagstaff** [comment]
From [most recent PrinceXML documentation](https://www.princexml.com/doc/styling/#footnotes):
> Footnotes are created with the float property (see also Floats): an element can be removed from the normal flow of the document by styling it with the footnote value. This creates a footnote call in the place where the element would be in its natural flow, and moves the element's content to the bottom of the page. The footnote marker is rendered outside the footnote in the left margin area, and the footnote is displayed as a block element.

> The property footnote-display can be used to change the default display of footnotes: besides the default block display, they can be also treated as inline elements. The value compact leaves it up to Prince to determine whether to display the footnote as a block or inline element: if two or more footnotes fit on one line, they will be treated as inline elements to take up less space.

> Making a footnote into an inline element moves the footnote marker into the footnote box as the first inline box inside the footnote.

**Comment by SteelWagstaff** [comment]
See conversation with Mike Day at Prince: https://www.princexml.com/forum/topic/4382/block-elements-in-paragraphs-footnotes?p=1#22060

**Comment by ricardopressbooks** [comment]
Javascript solution by Mark Brown doesn't work, and that's because we are putting a `div` inside a `p`, and it just break the DOM and split the paragraph in multiple parts.

With the solution proposed here: https://github.com/pressbooks/pressbooks/pull/1974, we are handling footnotes as a separate DOM and adding manually references as a `<sup>` tag. I also added a [CSS rule](https://github.com/pressbooks/pressbooks/pull/1974/commits/275059176324b5af07bbda8eee2b62d932229f17#diff-3a3271312ce87bb7d7f36877f67da886) in order to hide references generate automatically by prince using footnotes feature. So now we can continue using footnotes Prince feature and `footnote` CSS class reference.

**Comment by SteelWagstaff** [comment]
@ricardopressbooks Mark Brown thinks we might be able to modify the javascript so that it only runs inside of Prince and not before and suggests 

> Can you try the following slight variation? This should ensure the script is only run once it gets to Prince.

``` 
<script>
function replaceIndirect() {
    ind = document.getElementsByClassName("indirect");
    for (var i=0; i<ind.length; i++) {
        var e = document.getElementById(ind[i].getAttribute("ref"));
        if (e) ind[i].appendChild(e);
    }
}

if (typeof Prince != "undefined") {
    replaceIndirect();
}
</script>
```

**Comment by SteelWagstaff** [comment]
The proposed solution appears to work for PDF exports. It also alters the appearance and display of XHTML exports so that footnote content is no longer represented as inline span elements but as div elements at the bottom of each chapter.

**Comment by SteelWagstaff** [comment]
Upon further testing, I found that the footnote content blocks are empty for any footnotes created in parts, front matter & back matter, though the feature works well in chapter content. Screenshot:
![Screenshot from 2020-07-20 10-20-52](https://user-images.githubusercontent.com/13485451/87954988-baf62f00-ca72-11ea-93ad-fc040be92d9c.png)

See test book at https://integrations.pressbooks.network/footnotetest/wp-admin/options.php?page=pb_export or sample PDF export https://drive.google.com/file/d/1EYT1r2vteog6dsSUYB2LQoAhtg6nJYK1/view?usp=sharing

**Comment by ricardopressbooks** [comment]
Thank you for noticed that Steel. I just opened a new PR for fix that: https://github.com/pressbooks/pressbooks/pull/1986

**Comment by SteelWagstaff** [comment]
New PR appears to fix issue in parts & front/back matter. I think this is ready for release.
