### ISSUE TITLE
mPDF export - table of contents/bookmarks displays numbers

### ISSUE THREAD

**Issue by sswettenham** [pressbooks/pressbooks#184]
WordPress 4.2.2
PressBooks 2.5.2
PBTextbook 1.2.13

MAC PREVIEW - PDF 
![pdf-autogeneratedno](https://cloud.githubusercontent.com/assets/360534/8769917/d392660a-2e64-11e5-91d7-15236d1796c4.png)

Tried the numberless chapters via chapter types but did not change mPDF output.

**Comment by greatislander** [comment]
@bdolor Do you have a moment to investigate this?
