### ISSUE TITLE
Fix styling changed in WP 5.3 to look like PB

### ISSUE THREAD

**Issue by SteelWagstaff** [pressbooks/pressbooks#1845]
Rollback unwanted changes by overriding the affected classes with the styles of the previous WP version (primarily color)

**Comment by connerbw** [comment]
@cagp-dev-mtl 

Can you check this page? It's new in 5.3.0

![image](https://user-images.githubusercontent.com/812192/69759636-a1455780-1130-11ea-8706-5bab44c1bcd8.png)

 + https://github.com/WordPress/WordPress/blob/6f86cedb09f4ad42c5443cf5cc0c46b30bd41010/wp-login.php#L611
+ https://pressbooks.test/wp/wp-login.php?redirect_to=https%3A%2F%2Fpressbooks.test%2Fwp%2Fwp-admin%2F&action=confirm_admin_email

@SteelWagstaff @mcgratay Do we want to suppress this feature? Anyone with `[manage_options](https://wordpress.org/support/article/roles-and-capabilities/#manage_options)` will see this page...

**Comment by mcgratay** [comment]
Can verify that network managers would see this page. I'd recommend we disable it since the preferred default is that all network and site admins are set to ops@pressbooks.com. It also looks like it may pop up on book logins. 

Not finding any unwanted blue, so other than the above, everything looks good to go.

**Comment by cagp-dev-mtl** [comment]
@mcgratay ,  I have addressed your comments + most of Dac's notes attached in the [PR](https://github.com/pressbooks/pressbooks/pull/1867). 

Admin email screen confirmation page should not appear anymore, I added a hook that Dac sent me to block those emails. (Locally did not see the email confirmation window after adding the hook)

I could not change the color of the checkboxes arrows, I tried a couple of solutions including replacing the content attribute by an awesome icon, but the arrows appear misplaced out of the checkbox. I think if we want to address that particular issue we need to reasearch more....

**Comment by mcgratay** [comment]
Two hopefully quick fixes: 

1) The page size dropdown on the book list was fixed but that apparently didn't affect the user list one: 

![Screen Shot 2019-12-05 at 11 34 33 AM](https://user-images.githubusercontent.com/39064028/70254523-365cd780-1753-11ea-8ccb-1414a1123f9f.png)

And 2) Now that the highlights that appear on selected objects has been switched from blue to red, there are some discrepancies through different features. The most obvious is on the Media Library page where any selected media or search box is highlighted blue: 

![Screen Shot 2019-12-05 at 11 39 31 AM](https://user-images.githubusercontent.com/39064028/70254945-e7fc0880-1753-11ea-8e61-9f9c46c24b8d.png)

Search boxes on other pages are red: 
![Screen Shot 2019-12-05 at 11 40 16 AM](https://user-images.githubusercontent.com/39064028/70254993-02ce7d00-1754-11ea-878c-b44ab7cb2480.png)

At a more granular level, the highlight switches between blue and red across several of the visual editor tools (ex: compare the red-highlighted anchor tool to the blue-highlighted glossary tool). In addition, highlight color changes depending on which dropdown menu you're opening (ex: compare the red-highlighted paragraph dropdown menu on the visual editor to the blue-highlighted Chapter Type dropdown). 

It's going to take a hot minute to track down every element that's still highlighted in blue or showing a blue dropdown, and likely a bit of time to target each of those tools. I'd recommend fixing 1) as priority.

**Comment by mcgratay** [comment]
Good to go 👍
