### ISSUE TITLE
Table of Contents not public

### ISSUE THREAD

**Issue by sswettenham** [pressbooks/pressbooks#185]
PressBooks v.2.5.2
PressBooks Textbook v.1.2.13

Table of Contents (TOC) Title is displayed but nothing else in public view.
In admin view, TOC is displayed correctly.
PUBLIC:
![toc-public](https://cloud.githubusercontent.com/assets/360534/8761935/d4d333ee-2d26-11e5-8acf-191c63e6b52d.png)

ADMIN:
![toc-admin](https://cloud.githubusercontent.com/assets/360534/8761936/dacd00a4-2d26-11e5-9049-7fc17ec57d1f.png)

 bdolor commented:

This is an issue that affects all themes and is not specific to PBT. It looks like it was introduced in PressBooks recently and I encourage you to open up a ticket there.

Include in your description of the problem that anonymous (not logged in) users are not assigned a has_cap / capability role that would allow them to read a page, so any condition that checks for that will fail as seen:
pressbooks/pressbooks@f564185#diff-11dc803bb0b542aa987d37d504029e8fR20
pressbooks/pressbooks@f564185#diff-11dc803bb0b542aa987d37d504029e8fR37
pressbooks/pressbooks@f564185#diff-11dc803bb0b542aa987d37d504029e8fR54
pressbooks/pressbooks@f564185#diff-348c9f9580f4e8b34f5a0a3dcab76b8eR11
pressbooks/pressbooks@f564185#diff-348c9f9580f4e8b34f5a0a3dcab76b8eR44

**Comment by greatislander** [comment]
Apologies for this and thanks for spotting it. Should be fixed in [Pressbooks 2.5.3](https://wordpress.org/plugins/pressbooks/developers/).
