### ISSUE TITLE
Footnotes lose italics when imported in a Word doc (copy-paste retains itals)

### ISSUE THREAD

**Issue by SteelWagstaff** [pressbooks/pressbooks#1852]
Old Asana ticket:
When users import Word documents with footnotes, styling information (like italics) are stripped out as part of the import sanitization. This is particularly annoying for academic users in cases where footnotes follow specific reference styles that include italics.

See also: https://github.com/pressbooks/pressbooks/issues/631

**Comment by SteelWagstaff** [comment]
Plan: fix italics being stripped in initial import for now. Research what it would take to turn Word footnote into Pressbooks footnote shortcode upon import so that team can scope & estimate task at next backlog refinement meeting.

**Comment by ricardopressbooks** [comment]
This fix (for now) include italic, underlined and bold styles.
Mixed style for the same text is not included.
