### ISSUE TITLE
Chapters that require a password are cloned without content

### ISSUE THREAD

**Issue by mcgratay** [pressbooks/pressbooks#1863]
### Description

There are three privacy statuses for chapters inside of a public book:
- Shown in Web
- Shown in Exports 
- Password protected

Only chapters which are selected to show in web can be cloned as part of a public, openly licensed book. However, **because password protected chapters require the "Show in web" setting to be enabled, these chapters are also able to be cloned.**

The cloning routine copies the password protected chapters into the new book, but not the content, since that content is hidden. 

Example: https://privacytest.textopress.com

### Steps to Reproduce

1. Create a book with chapter that's shown in web and add filler text to the body
2. Set the chapter to Require a password and save all changes
3. Go to **Book Info** and apply a CC license that allows derivatives
4. Set the book's privacy setting to "Public" on the Organize page
5. Clone that book, then view the password protected chapter

**Expected behavior:** Only chapters that are accessible can be cloned

**Actual behavior:** Password-protected chapters are cloned without any content

**Comment by SteelWagstaff** [comment]
This recently caused an issue for our pressbooks.com -> pressbooks.pub migration tool. We'll need to find a solution so that others aren't adversely impacted.

**Comment by SteelWagstaff** [comment]
To test: check the migration request routine to make sure that password protected content is now cloned.

**Comment by tw77** [comment]
In my initial test I migrated a book from Textopress where all pages were public ("Show in web" checked) but password-protected. The content in each page was cloned successfully including password-protected front matter, chapters in two parts and back matter.

In the resulting book, each page was no longer password-protected, but was now set to private instead ("Show in web" unchecked). I assume this is desired behaviour. The password-protection and specific passwords aren't retained in the migrated book, but the routine ensures that pages that were password-protected are hidden by default. Noting this here just to make sure.

Next up to test:

- migration of a book with pages that are set to private to begin with and that are also password-protected
- in-network clone in Integrations2 (password-protected content shouldn't be cloned here)
- clone from one network to another (password-protected content shouldn't be cloned here)

**Comment by tw77** [comment]
When I clone https://dev.pressbooks.pub/testpwprotected/wp-admin/ to Integrations2 after setting all pages (front matter, chapters in two parts and back matter) to password-protected, I find that, as expected, none of the content of the pages is brought over in this regular clone.

This is a pretty minor detail, but I notice a difference in this regular clone between the handling of password-protected front matter / back matter vs. password-protected chapters. Password-protected pages from the front matter / back matter are included in the cloned book but emptied of any content (or reverted to the default Introduction and Appendix content that always appears in newly created books). On the other hand, password-protected chapters are fully withheld from the cloned book, not appearing at all in the Organize page.

[_Original on dev.pressbooks.pub_
](https://dev.pressbooks.pub/testpwprotected/wp-admin/)<img width="354" alt="Screen Shot 2022-08-02 at 2 52 05 PM" src="https://user-images.githubusercontent.com/44182629/182479849-0088029c-6f70-45cc-a4c4-5100c4ee9e57.png">


[_Clone on Integrations2_
](https://integrations2.pressbooks.network/testpwprotectedclone/wp-admin/)<img width="518" alt="Screen Shot 2022-08-02 at 2 52 34 PM" src="https://user-images.githubusercontent.com/44182629/182479919-a0cf413a-a689-464f-a4f3-ddeac9e5dca0.png">

**Comment by tw77** [comment]
When cloning a book within the same network, https://integrations2.pressbooks.network/testcloningpwprotectedcontent/ to https://integrations2.pressbooks.network/testinnetworkcloneofpwprotectedcontent/, I don't run into the minor unexpected detail noted above in the dev.pressbooks.pub -> Integrations2 clone. All password-protected front matter / chapters / back matter are brought over but emptied of content.

The other difference with the in-network regular clone is that there isn't a reversion to the default Introduction, Chapter 1 and Appendix placeholder text. Those pages are empty just like the other pages that are password-protected in the source book.

**Comment by tw77** [comment]
When I migrated a book from textopress -> dev.pressbooks.pub that included a range of private and password-protected pages within the front matter, chapters (in visible and invisible parts) and back matter, I found this unexpected behaviour:

1. Front matter / chapters / back matters that were private in the source became public in the migrated book, although the word "Private: " was added to their titles (despite them being public)

2. All content was set to public in the migrated book. Perhaps because of the presence of private content in addition to password-protected content in the source book, all password-protected content was public by default in the migrated book.

**Comment by tw77** [comment]
Migration of a book with a mix of private and password-protected content from Textopress to dev.pressbooks.pub is working well. "Private: " is not prepended and content in all pages is brought over. Tested as a super admin and as a regular user.

Regular clones appear to work as expected as well. I will do some final testing here.

**Comment by tw77** [comment]
Further tests of regular clones from one network to another and in-network indicate that https://github.com/pressbooks/pressbooks/issues/1863#issuecomment-1203253459 and https://github.com/pressbooks/pressbooks/issues/1863#issuecomment-1203266686 are still the case, which may be considered expected behaviour.

Since the issues of migration not bringing over password-protected content and "Private: " being prepended are resolved, this is ready for deploy.

**Comment by richard015ar** [comment]
@richard015ar will be responsible to present this during the sprint review.
