### ISSUE TITLE
Epub Export generates a blank page occasionally.

### ISSUE THREAD

**Issue by hughmcguire** [pressbooks/pressbooks#187]
occasionally a user clicks on export EPUB & gets a blank page instead of exported files. the url structure of the blank page is usually something like: 
~.pressbooks.com/wp-admin/admin.php?page=pb_export&export=yes&_wpnonce=7a2817a59c

to replicate
1. go to an affected project:
2. select EPUB (or EPUB + MOBI)
3. press "export"
3. this will return ... a blank page with URL like: 
~.pressbooks.com/wp-admin/admin.php?page=pb_export&export=yes&_wpnonce=7a2817a59c

@greatislander I will send you example URLs offline.

**Comment by greatislander** [comment]
@hughmcguire The example site you sent me has a 4MB cover image (5527 × 8333 pixels) which seems to be causing this:

`PHP Fatal error:  Allowed memory size of 268435456 bytes exhausted (tried to allocate 6252 bytes) in /wp-includes/media.php on line 2108`

Can you try to get the user (or can you) compress and scale down the image a bit and see if it works then? Thanks in advance.

**Comment by hughmcguire** [comment]
oh sorry -- yes ... got it ned, thanks.

I guess we should have a better error protocol than ... blank screen.

in mean time I sent info to user -- and awaiting news back from him.

**Comment by greatislander** [comment]
Unfortunately I think that's the way WordPress deals with "out of memory" errors—badly. We can perhaps proactively check for images that are of a size that will cause this issue and warn ahead of export (say when the user uploads a cover image?).

**Comment by hughmcguire** [comment]
yes, we have some recommended specs for cover images, see: 
http://guide.pressbooks.com/chapter/how-to-design-your-book-cover/

perhaps we could check against the max suggestions there on upload in book info? :/

**Comment by greatislander** [comment]
I've added a warning (similar to the one for cover images that are too small) to alert users when they have uploaded an image above the recommended filesize. Right now it doesn't block the upload, so we may want to get a bit stricter about this in future. But at least there's an alert now before they run into export issues.
