### ISSUE TITLE
Installation for ODT Export?

### ISSUE THREAD

**Issue by sswettenham** [pressbooks/pressbooks#188]
Are there installation instructions for setting up ODT export function?

**Comment by greatislander** [comment]
There is one external dependency that I am aware of for ODT—namely, your server needs to have Java (as is also the case for [EpubCheck](https://github.com/pressbooks/pressbooks/blob/dev/readme.txt#L111)). This and any other relevant information information will be added to the readme when the ODT feature is no longer considered quite as experimental as it is now.
