### ISSUE TITLE
H1s in Word Documents initially created in Google Docs aren't parsed as new chapters upon import

### ISSUE THREAD

**Issue by PressbooksLiz** [pressbooks/pressbooks#1881]
### Prerequisites

* [ x] Can you reproduce the behavior you wish to address with [all other plugins deactivated](http://codex.wordpress.org/Multisite_Network_Administration#Plugins)?
* [ x] Are you running the [latest version of Pressbooks](http://github.com/pressbooks/pressbooks/releases/latest/) and the [latest version of WordPress](http://codex.wordpress.org/Upgrading_WordPress)?
* [? ] Are you experiencing this issue with one of our built-in root or book themes?
* [ x] Did you [perform a cursory search](https://github.com/issues?q=+is%3Aissue+repo%3Apressbooks%2Fpressbooks) to see if your bug or enhancement is already listed?

### Description

H1 chapter headings in Word docs created / downloaded from Google docs don't seem to translate into chapters using the regular Import a Word doc tool in Pressbooks. 

### Steps to Reproduce

1. Create a Google doc with H1s for sample chapter headings 
2.  Download this document as a Word doc. 
3. Upload this Word file using the one-click Import tool... 

**Expected behavior:** I thought PB would break the doc into chapters as it does with Word files.

**Actual behavior:** Chapter headers were not recognized. The whole doc imported as one chapter.

**Comment by mcgratay** [comment]
Cannot reproduce. Successfully imported a five-chapter docx file exported from Google Docs. 

[Note that while this process should work fine for importing several chapters, Pressbooks does not support any method of import from Google Docs at this time, and we can't guarantee that formatting or markup from Google Docs will be compatible with Pressbooks software.]
