### ISSUE TITLE
Importer seems not to recognize Word doc (docx file) created in online version of Word 

### ISSUE THREAD

**Issue by PressbooksLiz** [pressbooks/pressbooks#1882]
### Prerequisites

* [x ] Can you reproduce the behavior you wish to address with [all other plugins deactivated](http://codex.wordpress.org/Multisite_Network_Administration#Plugins)?
* [x ] Are you running the [latest version of Pressbooks](http://github.com/pressbooks/pressbooks/releases/latest/) and the [latest version of WordPress](http://codex.wordpress.org/Upgrading_WordPress)?
* [ ] Are you experiencing this issue with one of our built-in root or book themes?
* [x ] Did you [perform a cursory search](https://github.com/issues?q=+is%3Aissue+repo%3Apressbooks%2Fpressbooks) to see if your bug or enhancement is already listed?

### Description

Trying to upload a Word doc created in the online version of Word. It is a pure .docx file that I did not open in any other software before uploading. 

### Steps to Reproduce

1. Create a Word doc in the online version of Word.
2. Download it as a Word doc. 
3. Upload it using the Word Importer in Pressbooks

**Expected behavior:**  Document would upload, and hopefully detect chapter headings. 

**Actual behavior:** Error message. "Your file does not appear to be a valid docx"

### System Information

![Screen Shot 2020-01-03 at 12 35 16 PM](https://user-images.githubusercontent.com/28898944/71745396-379f2400-2e27-11ea-8653-012ca4aa7604.png)
![Screen Shot 2020-01-03 at 12 36 49 PM](https://user-images.githubusercontent.com/28898944/71745399-3a017e00-2e27-11ea-8a33-b6d751d8973b.png)

**Comment by PressbooksLiz** [comment]
[Sample Word Document 12.50.06 PM.docx](https://github.com/pressbooks/pressbooks/files/4020670/Sample.Word.Document.12.50.06.PM.docx)
This is the file in question.

**Comment by mcgratay** [comment]
Confirmed reproducible. Created a docx file at https://onedrive.live.com

Test file: 
[OnlineWordImportTest.docx](https://github.com/pressbooks/pressbooks/files/4041638/OnlineWordImportTest.docx)
