### ISSUE TITLE
Several discrepancies in keyboard accessibility of the webbook homepage between Safari and other supported browsers

### ISSUE THREAD

**Issue by mcgratay** [pressbooks/pressbooks#1883]
### Prerequisites

* [x] Can you reproduce the behavior you wish to address with [all other plugins deactivated](http://codex.wordpress.org/Multisite_Network_Administration#Plugins)?
* [x] Are you running the [latest version of Pressbooks](http://github.com/pressbooks/pressbooks/releases/latest/) and the [latest version of WordPress](http://codex.wordpress.org/Upgrading_WordPress)?
* [x] Are you experiencing this issue with one of our built-in root or book themes?
* [x] Did you [perform a cursory search](https://github.com/issues?q=+is%3Aissue+repo%3Apressbooks%2Fpressbooks) to see if your bug or enhancement is already listed?

### Description

There are several items on the webbook homepage that do not receive focus when using screen reader technology with the Safari browser on the webbook homepage. Testing was done using Apple's VoiceOver feature for all four supported browsers (Safari, Edge, Chrome, and Firefox). 

Using screen reader technology with Safari, only the following items can be focused on: 
- Increase Font Size button
- Search icon and box
- Download this book dropdown
- Hide Contents/ Show Contents button
- Toggles to collapse and expand parts 

Chrome, Edge, and Firefox browsers all allow users to focus on the following items in addition to those listed above: 
- Skip to Content option
- All admin menu links (Contact, Home, Sign Out, et cetera) 
- The site logo
- The search box itself
- Metadata links (like DOI) and links in the License statement 
- Read Book button and Buy Book button
- The links to every chapter, part, and subsection
- The download links for all available files (causing the file list to remain open even after users have tabbed onto other elements on the page) 
- All links in the book description fields 
- All footer icons and links

### Steps to Reproduce

1. Visit the homepage of a webbook on the Safari browser
2. Enable your screen reader and tab through the page via keyboard
3. Note all items that receive focus
4. Switch to another Pressbooks-supported browser and do the same 

**Expected behavior:** All clickable objects on the webbook homepage receive keyboard focus while using a screenreader
**Actual behavior:** Behavior in the Safari browser is different than in other Pressbooks-supported browsers, and only select items on the webbook homepage receive keyboard focus.

**Comment by greatislander** [comment]
@mcgratay I don't think this is a Pressbooks bug, I expect it's this system setting: https://www.weba11y.com/blog/2014/07/07/keyboard-navigation-in-mac-browsers/

**Comment by greatislander** [comment]
(Specifically: Safari &rarr; Preferences &rarr; Advanced &rarr; Accessibility.)

**Comment by mcgratay** [comment]
Looks like you're right @greatislander – thanks.
