### ISSUE TITLE
Change email hardcoded into 8 Bibliolabs bedrocks 

### ISSUE THREAD

**Issue by mcgratay** [pressbooks/pressbooks#1884]
### Prerequisites

* [x] Can you reproduce the behavior you wish to address with [all other plugins deactivated](http://codex.wordpress.org/Multisite_Network_Administration#Plugins)?
* [x] Are you running the [latest version of Pressbooks](http://github.com/pressbooks/pressbooks/releases/latest/) and the [latest version of WordPress](http://codex.wordpress.org/Upgrading_WordPress)?
* [x] Are you experiencing this issue with one of our built-in root or book themes?
* [x] Did you [perform a cursory search](https://github.com/issues?q=+is%3Aissue+repo%3Apressbooks%2Fpressbooks) to see if your bug or enhancement is already listed?

### Description

There is a **Contact** link present in the footer of every Pressbooks webbook. On networks with the Aldine theme, this link can be customized by anyone with admin access to the network rootsite. The Librarian theme used for Bibliolabs networks does not have this setting, however. The link destination is hardcoded. 

The email address the contact link is currently directing to is `eakesc@biblioboard.com` and needs to be changed in 8 bedrocks to direct to `cara@biblioboard.com` instead. The end goal is to have Contact link on all 173 active Bibliolabs networks direct toward the new email address. 

### Steps to Reproduce

1. Access a webbook on any bibliolabs network 
2. Scroll to the footer
3. Click the **Contact** link to see what email address users are directed to 

**Expected behavior:** Email destination is cara@biblioboard.com

**Actual behavior:** Email destination is eakesc@biblioboard.com

**Comment by SteelWagstaff** [comment]
All instances where eakesc@biblioboard.com occurs: https://github.com/search?q=org%3Apressbooks+eakesc%40biblioboard.com&type=Code

**Comment by SteelWagstaff** [comment]
3 of the repos are no longer in production and were skipped. The other 5 received the change.
