### ISSUE TITLE
Publishing logo is (sometimes) tiny on PB networks

### ISSUE THREAD

**Issue by hughmcguire** [pressbooks/pressbooks#1891]
### Prerequisites

* [x] Can you reproduce the behavior you wish to address with [all other plugins deactivated](http://codex.wordpress.org/Multisite_Network_Administration#Plugins)?
* [x] Are you running the [latest version of Pressbooks](http://github.com/pressbooks/pressbooks/releases/latest/) and the [latest version of WordPress](http://codex.wordpress.org/Upgrading_WordPress)?
* [x] Are you experiencing this issue with one of our built-in root or book themes?
* [x] Did you [perform a cursory search](https://github.com/issues?q=+is%3Aissue+repo%3Apressbooks%2Fpressbooks) to see if your bug or enhancement is already listed?

### Description

publisher logo is tiny on some PB networks on book pages.

### Steps to Reproduce

1. go here: https://pressbooks.online.ucf.edu/aimidworkflows/
2. look at publisher logo (top left corner)...notice it's size: 

NOTE: the logo is available in high res:  https://pressbooks.online.ucf.edu/app/uploads/2018/08/TabLockup_horizontal_KGrgb_300ppi.png

**Expected behavior:** 
pub logo to be reasonably sized.

**Actual behavior:** 
pub logo is too small.

**Comment by SteelWagstaff** [comment]
Closing -- issue already exists: https://github.com/pressbooks/pressbooks-aldine/issues/201
