### ISSUE TITLE
Research / scope PB #1771

### ISSUE THREAD

**Issue by SteelWagstaff** [pressbooks/pressbooks#1893]
See https://github.com/pressbooks/pressbooks/issues/1771

**Comment by SteelWagstaff** [comment]
If our top nav-bar is an admin nav bar, we can remove the link taking users to book home pages and simply allow users to visit book admin pages for books in the list. This would simplify the dropdown menus and the number/depth of links in our menu. Users have the ability to visit a book home page very easily from a book's admin panel.

**Comment by SteelWagstaff** [comment]
Recommendations:
1. Simplify the top level nav menu so that each top level item no longer contains a link itself but simply opens/closes a menu with links. This will not affect the PB logo, Network Admin, Network Root top-level menu, or Individual Book Dashboard menus, since the first item in the list is the same as the top level option. 
2. Change the `My Catalog` menu entry so that the top level text reads 'My Books' but does not contain a link. 
3. Add the `My Catalog` link to be the first child of the `My Books` menu.
4. Simply each of the Book entries in the list so that they have no children elements (no `dashboard` or `visit book` sub menu choices). Clicking a book's title should simply take a user to the book's dashboard.
![Screenshot from 2020-02-27 08-30-11](https://user-images.githubusercontent.com/13485451/75454769-953d8180-593b-11ea-9acd-5332be1edbca.png)
5. As a result, a user should be able to navigate the top nav-bar by keyboard (tabbing through top-level choices), open/close the top level menus by clicking enter, and then tab through sub menu choices. Pressing enter should take them to the desired link destination.

**Comment by mcgratay** [comment]
To clarify, can the "My Books" tab be clicked or only hovered over? Since all of the other top nav elements also double as links to the first page on the dropdown, I'd recommend that this behavior be consistent for the My Books tab as well.

**Comment by SteelWagstaff** [comment]
The intention would be that none of the top level items function as links anymore, since the link function competes with the expand/contract menu item. See option 2 here: https://www.w3.org/WAI/tutorials/menus/flyout/#flyoutnavmousefixed. Before we remove the top level link, we'd simply need to make sure that the link it points to is represented in the child list. The 'My Catalog' link is the only case where that does not happen at present.

**Comment by mcgratay** [comment]
👍
