### ISSUE TITLE
Remove book from fetcher when book visiblity changes

### ISSUE THREAD

**Issue by ho-man-chan** [pressbooks/pressbooks#1898]
Make sure the book fetcher can remove a book from Algolia when a specific network book changes the visibility status from public to private. Similarly, archived/deactivated/deleted/marked as spam books should notify the book fetcher to remove the book from Algolia.

Possible Solution:
- [ ] Create authenticated API endpoints in the fetcher to accept a list of deleted/removed books (book URL) - L
- [ ] In Pressbooks plugin, create a function that will attach to the visibility change and archive/deactivate/delete/spam actions for a given book. The function should return the **book URL** in order for the fetcher to identify the book. - L
- [ ] The function will notify the book fetcher securely to remove the book info from Algolia's database (using symmetric key). - L
- [ ] Hardcode a static fetcher URL into Pressbooks plugin, so networks will know where to communicate with the fetcher.

References:
https://www.algolia.com/doc/api-reference/api-methods/delete-objects/
https://rudrastyh.com/wordpress-multisite/delete-blog-deprecated.html
https://expressjs.com/en/5x/api.html
https://auth0.com/blog/node-js-and-express-tutorial-building-and-securing-restful-apis/

**Comment by SteelWagstaff** [comment]
See also https://github.com/pressbooks/book-directory-fetcher/issues/6 for other ideas

**Comment by SteelWagstaff** [comment]
Proposal for _this_ task:
1. build endpoint in fetcher to receive calls/status update notifications from networks
2. write functions in Pressbooks to send deletion requests to fetcher when 1) public books are made private, 2) a book is marked as spam, deactivated, archived, or deleted, 3) the book URL is changed

**Comment by SteelWagstaff** [comment]
Closing in favor of https://github.com/pressbooks/book-directory-fetcher/issues/6
