### ISSUE TITLE
Feature: Allow network users without permissions in a book to clone a new book

### ISSUE THREAD

**Issue by SteelWagstaff** [pressbooks/pressbooks#1899]
When a new user is added to a Pressbooks network, but not given a role or permissions in an existing site/book (i.e. they're created as a 'lowly user'), they only see the 'create a new book' option following log-in at `https://network.url/wp-admin/user/`. 

![Screenshot from 2020-02-27 08-44-19](https://user-images.githubusercontent.com/13485451/75455573-282beb00-593f-11ea-9cd9-0daca55d890f.png)

Where networks permit cloning books, these 'lowly users' should also see the 'Clone a Book' option from their `My Catalog` list and be able to clone a new book to the network.

## Notes

To fix, we'll probably need to make changes in a few places: 
1. the routine that registers the cloning page needs to be moved somewhere that isn't 'replace book admin' in hooks-admin.php

1. We'll want to move the cloning routine to somewhere accessible to these lowly users, instead of as a subpage in an existing book/site on the network: https://github.com/pressbooks/pressbooks/blob/86b921b5c3ede76e3fd94732e56cce50c710ded8/inc/admin/laf/namespace.php#L842-L848

One possible approach might be to try to register the cloning page as a submenu page to the user profile page (wp-admin/user/profile.php)? https://developer.wordpress.org/reference/functions/add_users_page/. Something like `NETWORKURL/wp-admin/user/profile.php?page=cloner`

We would then want to hide it from the side dashboard as a child of profile but display it in the top admin menu below my catalog and create a new book, just as it appears for super admins or users with a role in at least one other book.

![Screenshot from 2021-05-24 14-36-05](https://user-images.githubusercontent.com/13485451/119410280-75f7e600-bc9d-11eb-9db6-839b7124b86a.png)

1. If we do that, we'll need to figure out a way to deal with the required capabilities for registering sub menu pages, since lowly users don't have any capabilities: https://github.com/pressbooks/pressbooks/blob/86b921b5c3ede76e3fd94732e56cce50c710ded8/inc/admin/laf/namespace.php#L398-L399

Maybe we create a loop to check for user capabilities and give it to them if it doesn't exist?

https://github.com/WordPress/WordPress/blob/master/wp-admin/user-edit.php

**Comment by SteelWagstaff** [comment]
To fix, we'd need to change permissions in at least two places: 
1. the routine that registers the cloning page needs to be moved somewhere that isn't 'replace book admin' in hooks-admin.php
2. the permissions check should be 'user can create book', not 'user can edit posts'

**Comment by beckej13820** [comment]
Steel,

Is this related to the fact that cloning can't be done until at least 1 book is made, AND artifacts of the first book on the network show up in the revision history of cloned books?

For example:
When I hover over clone a book on pressbooks.sunycreate.cloud (Pressbooks 5.17.2 on Wordpress 5.5.3 using sub-domains) the clone a book button actually uses the URL https://perspectives.pressbooks.sunycreate.cloud/wp-admin/options.php?page=pb_cloner (That's the first book on the network that the user has access to.)
<img width="673" alt="Screen Shot 2020-11-01 at 4 15 14 PM" src="https://user-images.githubusercontent.com/29982981/97815740-47151680-1c5e-11eb-9c42-7ba6a83ceaed.png">


In addition in the revision history on cloned books, sometimes we see URLs of the first book on the network. (See Screenshot)
<img width="1018" alt="Screen Shot 2020-11-01 at 4 20 09 PM" src="https://user-images.githubusercontent.com/29982981/97815743-4da38e00-1c5e-11eb-86c7-a13f42e5cfc9.png">

**Comment by beckej13820** [comment]
I don't know if it's clear from the 2nd screenshot above, but the cloned book is showing a URL of a 3rd book that the book admin user does not have access to or rights to.

**Comment by SteelWagstaff** [comment]
Ned suggests asking Jeremy Felt: https://profiles.wordpress.org/jeremyfelt/ if he has any ideas

**Comment by SteelWagstaff** [comment]
@richard015ar & @arzola testing locally since the deploy to integrations pipeline isn't working right now. I notice that there's a new 'clone a book' menu option in each book's dashboard that should probably be removed. See
![clone_a_book](https://user-images.githubusercontent.com/13485451/127234348-7dd9cdc1-7e6d-499c-97b4-774b63b7c625.png)

**Comment by SteelWagstaff** [comment]
Tested -- works as expected on integrations. I notice that the clone a book option still appears on textopress (a subdirectory installation), however. I don't think this will affect Pressbooks.com because cloning is not enabled on that network, but wanted to flag it:
![Screenshot from 2021-07-28 11-55-01.png](https://images.zenhubusercontent.com/6012398f80b7cb0f8d1385bc/61f6e5af-b02a-4f71-8965-90d5375d0dc8)

**Comment by SteelWagstaff** [comment]
Tested again. Works as expected.
