### ISSUE TITLE
'My catalog' listing doesn't allow users to scroll down long list

### ISSUE THREAD

**Issue by SteelWagstaff** [pressbooks/pressbooks#1901]
When users belong to lots of books in a given network, they aren't able to see the full list of books from the `my catalog` drowndown menu, because it's longer than the page and doesn't scroll.

**Comment by mcgratay** [comment]
Test notes: 

- List width always expands to _just_ shy of the longest title in **Safari** and **Firefox** browsers, which means that there is always horizontal scroll bar, and the longest title is always cut off: 

Long, long title
![Screen Shot 2020-03-06 at 9 58 48 AM](https://user-images.githubusercontent.com/39064028/76095071-a87ecb80-5f91-11ea-9854-a93cbac80595.png)

Much shorter title, still has a horizontal scroll
![Screen Shot 2020-03-06 at 9 59 11 AM](https://user-images.githubusercontent.com/39064028/76095089-b0d70680-5f91-11ea-9e9a-938afa478e82.png)

- Overflows the right margin on mobile screens, but that's true before this change as well 
![Screen Shot 2020-03-06 at 11 09 45 AM](https://user-images.githubusercontent.com/39064028/76100641-fe0ba600-5f9a-11ea-937a-8e9cd7d96aa2.png)

- Tested on Safari, Firefox, and Chrome
- All other functionality as expected

**Comment by mcgratay** [comment]
Not seeing any change: Firefox and Safari still affected.

**Comment by SteelWagstaff** [comment]
Yeah -- i'm seeing that now too. Couple of ways we can approach this. One would be to turn off overflow. Another would be to set a max-width for the element and just cut off longer titles. A third would be to figure out better way to detect width of element so that scroll bar doesn't appear on firefox/safari (might be appearing because there's now a vertical scroll bar, which eats up some space -- idk yet). I'll discuss with team on Monday in scrum.

**Comment by mcgratay** [comment]
👍
