### ISSUE TITLE
Notify directory fetcher when relevant book info is changed

### ISSUE THREAD

**Issue by SteelWagstaff** [pressbooks/pressbooks#1905]
Write functions in Pressbooks to send record removal requests to fetcher endpoint described in https://github.com/pressbooks/book-directory-fetcher/issues/9 when 

1. public books are made private 
1. a book is marked as spam, deactivated, archived, or deleted, 
1. the book URL is changed

Precondition 2/2 for https://github.com/pressbooks/book-directory-fetcher/issues/6

**Comment by SteelWagstaff** [comment]
1. The public/private toggle for a book is inherited from the core WordPress [blog_public value](https://codex.wordpress.org/Option_Reference). There are several places where we refer to this function: https://github.com/pressbooks/pressbooks/search?q=blog_public&unscoped_q=blog_public

Book and super admins can make a book public/private from the organize page; see https://github.com/pressbooks/pressbooks/blob/497bf6486ec5c0d56889dc1c7a28f48d9977d100/templates/admin/organize.php#L12. They can also make it public/private from the `site-info.php` page inherited from core WordPress.

Network managers on hosted networks can also change a book's privacy status from the Book List: https://github.com/pressbooks/pressbooks-network-analytics/blob/125fffa4ce8cccc8f7aa0a7bc001feaf73c7d951/assets/src/scripts/booklist.js#L68

2. Books can be marked as spam, deactivated, archived, or deleted from the `site-info.php` page and from the `network/sites.php` page. Books can be deleted by book admins from the `ms-delete-site.php` page and can also be deactived and deleted by network managers on hosted networks from the Book List: https://github.com/pressbooks/pressbooks-network-analytics/blob/4a08bcb09618c8ebeea805c72a262165bb74453a/inc/admin/class-books.php#L249-L254

3. A book's address (URL) can be changed from the `site-info.php` page.

**Comment by cagp-dev-mtl** [comment]
PR for this ticket:

https://github.com/pressbooks/pressbooks/pull/1912

@ho-man-chan , I have added all the necessary triggers for the book directory delete index actions in Pressbooks, once you have the delete endpoint URL, you just need to set that value in the class constant "DELETE_BOOK_ENDPOINT"  the class "BookDirectory" and you will receive a POST request with the post pairs ''network' and 'book-id'
