### ISSUE TITLE
mPDF  - generate an index at the end of document

### ISSUE THREAD

**Issue by sswettenham** [pressbooks/pressbooks#191]
enhancement

Add the ability to have an index generated in PDF export and in other outputs.

Although http://mpdf1.com/manual/index.php?tid=244  can generate the index, it would useful if a page in Pressbooks could be produced in the back matter that represented the index.

**Comment by greatislander** [comment]
Hi @sswettenham, the ability to add an index is on our roadmap (see #172) but as with most Pressbooks features, we aim to introduce them for all principal output formats concurrently—so index support would need to be developed for PDF (Prince), PDF (mPDF), EPUB and Mobi. So I am going to close this ticket as a duplicate and consider your request part of #172.
