### ISSUE TITLE
XHTML/EPUB/PDF Title page doesn't have semantically correct HTML

### ISSUE THREAD

**Issue by SteelWagstaff** [pressbooks/pressbooks#1911]
See https://github.com/pressbooks/pressbooks/blob/7ea8dd2aff224cfdf1bab8d119f1588e44772a72/inc/modules/export/epub/class-epub201.php#L1045-L1063

and 
https://github.com/pressbooks/pressbooks/blob/7ea8dd2aff224cfdf1bab8d119f1588e44772a72/inc/modules/export/xhtml/class-xhtml11.php#L999-L1017

**Comment by richard015ar** [comment]
I think it could be closed @SteelWagstaff , it seems to be fixed with the new xhtml templates.
