### ISSUE TITLE
Changing the site url of a book results in page redirect for front matter pages

### ISSUE THREAD

**Issue by programmieraffe** [pressbooks/pressbooks#192]
Hey there,

I'm using pressbooks 2.5.3. 

I added a new book with the url "/testrewrite/" via the top menu bar. Chars like "-" are not allowed in the initial creation form, so I changed the site url to "/test-rewrite/" afterwards in the network management of wordpress (/wp-admin/network/sites.php -> edit site -> path)

After that change front-matter pages (e.g. introducation) only return 301 and there is a redirect to the front page of the whole network ("/").
Pages in the main chapter work work well after the change.

Is there a specific redirect for pages with /front-matter/ in the permalink? Unfortunately I couldn't find something in the pressbooks code. Help appreciated.

Thanks in advance,
Matthias

**Comment by hughmcguire** [comment]
my solution would be to not use chars like "-" in the book/site name/url.

but that probably doesn't answer your question :/

**Comment by programmieraffe** [comment]
Yes, I agree but the problem also occurs when I rename the site to "/testrewrite2/". So it is rather a problem with updating the site url than a problem with the dash. Regarding that I would consider this a bug, because somewhere there is a 301 redirect with the original site url (on creation) which is not updated properly. (In the database or the files? I couldn't figure out where the redirect for url parts like front-matter/ or chapter/ is in pressbooks - maybe you could give me a hint? :))

Maybe I should have stated this more clearly in the beginning. 

Thanks for the quick response!

**Comment by hughmcguire** [comment]
"doctor, it hurts when i do this ... "

( sorry still not helping, I know  ... :/ )

**Comment by programmieraffe** [comment]
I do understand that you don't consider this as a bug. But for some people
changing the site url of a book is a common use-case. At least imho. (And
for most people urls with dashes will look a lot better - which would be a
pro for pressbooks)

So to close this discussion I would be very grateful for some advice where
the URL rewrites for url parts like "chapter/" or "front-matter/" are
located in the pressbooks code. Maybe i can fix it myself.

If this is not possible, you can just close this discussion.
Am 30.07.2015 19:47 schrieb "Hugh McGuire" <notifications@github.com>:

**Comment by bdolor** [comment]
When encountering an unexpected redirect back to the network page I have had success in the past  navigating to `http://my-domain/my-hyphenated-book-url/wp-admin/options-permalink.php` and hitting `Save`. You could try this potentially low-hanging-fruit-solution if you wanted to avoid hunting around in the code for a solution.

**Comment by nciske** [comment]
A bit easier - install this plugin and use it to flush your rewrite rules after editing a site name.

https://wordpress.org/plugins/rewrite-rules-inspector/

_________________________
Nick Ciske
VP Web Engineering
http://cimbura.com
@nciske

**Comment by greatislander** [comment]
I'm going to look into this and see if we can't add a hook to Pressbooks that will flush a book's rewrite rules when the site's name is changed.

**Comment by programmieraffe** [comment]
Thanks @bdolor, that worked.

@nciske Thanks for the advice, but the rewrite rules inspector didn't work in my multisite environment.

@greatislander Thanks for your effort! A possible workaround would be a "flush permalink" button in the dashboard as well. I saw a "FORCE_FLUSH"-section in the pressbooks source code as well, but I could not figure out how to detect a site url change in wordpress to trigger it (maybe you can ;)).

**Comment by greatislander** [comment]
@programmieraffe This issue should be fixed in https://github.com/pressbooks/pressbooks/commit/96614312719815844fd847020197c11d0cc6213d. Can you check out the development branch and test? Thanks!

**Comment by programmieraffe** [comment]
Thanks for fixing this! :-)  I tested it on my local dev server and it worked.
