### ISSUE TITLE
Prepare for WordPress 5.4

### ISSUE THREAD

**Issue by SteelWagstaff** [pressbooks/pressbooks#1920]
Big picture summary available from: https://make.wordpress.org/core/2020/03/03/wordpress-5-4-field-guide/ + https://wordpress.org/support/wordpress-version/version-5-4/#developer-notes +
https://wptavern.com/preparing-for-wordpress-5-4-changes-theme-and-plugin-developers-should-know-about

TODO: 

- [ ] Remove 'main' role fix on new site creation page (https://github.com/pressbooks/pressbooks/pull/1837), as it's been fixed upstream: https://core.trac.wordpress.org/ticket/48657 

- [x] Remove site health status box (a div with ID `dashboard_site_health`) from the root network dashboard (i.e. https://integrations.pressbooks.network/wp/wp-admin/).
![image](https://user-images.githubusercontent.com/13485451/80047360-d7fe7e80-84d2-11ea-89d6-efb035f49cba.png) Here's recommended method: https://developer.wordpress.org/apis/handbook/dashboard-widgets/#removing-default-dashboard-widgets and here's where the widget is created & registered in core WordPress: https://github.com/WordPress/WordPress/blob/900cfc4816459e13eec4b28c62b28c4de326e3b8/wp-admin/includes/dashboard.php#L45-L57
- [x] We can begin replacing do_shortcode w/ apply_shortcode. See https://make.wordpress.org/core/2020/02/13/wordpress-5-4-introduces-apply-shortcodes-as-an-alias-for-do-shortcode/ and https://github.com/pressbooks/pressbooks/search?q=do_shortcode&unscoped_q=do_shortcode
- [x] Accessibility: the Admin Bar is now loaded with wp_body_open when available. Moving the toolbar to load in the new hook wp_body_open (5.2) fixes a long-standing source order problem. In WordPress 5.4, the Admin Bar loads in the hook wp_body_open (instead of the footer) and fixes a long-standing source-order problem. See https://core.trac.wordpress.org/ticket/47053 & https://github.com/pressbooks/pressbooks/issues/1773. Problem for us is that we don't yet make use of wp_body_open (new in WP 5.2). We probably should?

- [x] wp-env: Zero config, automatic docker creation for local development with a single command. Possible to explore/use with Pressbooks? Conversation in comments here is interesting: https://make.wordpress.org/core/2020/03/03/wp-env-simple-local-environments-for-wordpress/

- [x] Media: store the original URL of the attachment in the _source_url post meta value: https://make.wordpress.org/core/2020/02/26/miscellaneous-developer-focused-changes-in-wordpress-5-4/ + https://core.trac.wordpress.org/ticket/48164. "When you use media_sideload_image to sideload a file from a URL, the original URL is now automatically stored as metadata. You can also use media_sideload_image to store a local copy of a file. Storing the source URL gives you an easy way to find out where that file was originally hosted. Plus, you can query existing attachments and not sideload the same file twice." We don't appear to use media_sideload_image currently, but might not be bad idea for our import routines? 

- [x] API updates: API now permits creation & registration of metadata when media (images, etc.) is created via API: https://core.trac.wordpress.org/ticket/44567. The API will also store each generated embedded object in a temporary cache when querying for linked resources so that repeated links to the same resource do not trigger repeated queries or processing. https://core.trac.wordpress.org/ticket/48838#comment:4

- [x] The switch_blog action now has a new $context parameter. The action is fired by both switch_to_blog() and restore_current_blog(), and previously it was difficult for callback functions to determine which function had fired it.

- [x] Favicon updates: WP 5.4 introduces new functions and hooks for favicon handling. I don't think we use these, but worth knowing about: https://make.wordpress.org/core/2020/02/19/enhancements-to-favicon-handling-in-wordpress-5-4/.

**Comment by SteelWagstaff** [comment]
I don't see any high-level blockers from installing locally and reading release notes. Sounds like some open source users have upgraded without complaint as well: https://pressbooks.community/t/is-pressbooks-tested-with-wordpress-5-4/1302. I recommend deploying to staging for further testing.

**Comment by cagp-dev-mtl** [comment]
I have installed WP 5.4 locally I did not noticed cosmetic or functional changes, it does not conflict with the main role fix, I think we can revert the fix once we enable and deploy WP 5.4.

With regards to the deprecation of 'do_shortcode', I think we can create a new ticket exclusively to address that issue.

**Comment by cagp-dev-mtl** [comment]
Just noticed in my local that the favicon of the main page of Pressbooks is the one of WordPress, we i might be a local env issue only, however we need to check if this happens in Staging.

**Comment by SteelWagstaff** [comment]
Yes, I noticed this as well (locally). I also saw that the 'site health' widget appeared on the network dashboard admin panel. I thought we had suppressed this, and don't know if local environment is different or if something has changed with 5.4. Worth looking into when we deploy to staging.

**Comment by SteelWagstaff** [comment]
New ticket created for do_shortcode replacement: https://github.com/pressbooks/ideas/issues/302

**Comment by SteelWagstaff** [comment]
Related: https://github.com/pressbooks/private/issues/153

**Comment by SteelWagstaff** [comment]
TODO: 
- [ ] Remove site health box (a div with ID `dashboard_site_health`) from the root network dashboard (i.e. https://integrations.pressbooks.network/wp/wp-admin/).
![image](https://user-images.githubusercontent.com/13485451/80047360-d7fe7e80-84d2-11ea-89d6-efb035f49cba.png)
