### ISSUE TITLE
Multi-level TOC parsing broken by unexpected tags

### ISSUE THREAD

**Issue by hughmcguire** [pressbooks/pressbooks#196]
Have seen 2 recent problems: 

`1.` chapter ugc wrapped in an extra div breaks subsection counting ... so : 

```
     <div> 
     Chapter content text text text
    <h1>First subsection</h1>
    text text
    <h1>2nd subsection</h1>
    text tex
    </div>
```

does not get counted right ... 

`2.` subsection `<h1>` with inline styling breaks subsection counting ... so: 

`<h1 style="text-align: left;">Whatever</h1>` 

doesn't get counted correctly.

Result: 
-- pagination in PDF TOC & linking is wrong.

**Comment by greatislander** [comment]
Pretty sure I've squashed these bugs. Please confirm (just deployed to Textopress for testing).
