### ISSUE TITLE
Change books last updated value when publication status changes

### ISSUE THREAD

**Issue by SteelWagstaff** [pressbooks/pressbooks#1962]
In order for our directory book fetcher to work as expected, we need to change the 'last updated' value whenever a book's publication status changes from public -> private or from private -> public.

**Comment by cagp-dev-mtl** [comment]
@ho-man-chan I tested the current code, I did change the privacy settings of a book and every update from private to public or vice versa on section "Sharing and Privacy Settings" updates the field "last_updated". 

How did you notice the issue? are you able to reproduce it?

![image](https://user-images.githubusercontent.com/8563418/84228104-bae63500-aaab-11ea-8510-82969dd01261.png)
