### ISSUE TITLE
To discuss: Access to read all books in a network 

### ISSUE THREAD

**Issue by hughmcguire** [pressbooks/pressbooks#197]
We are getting more users with dedicated pressbooks networks ... who want: 
a) to keep their books private from the wider web
b) but wish to make all their books accessible to read/comment on for a set of users  

An example of this is a university with a set of faculty-developed course textbooks. 
- They DO NOT want random people reading those books
- The DO want to give students access to read all of those books

So, maybe we want a new  kind of user that has read-only access on all books in the system? Like a system-subscriber ... 

To discuss.

**Comment by bdolor** [comment]
LTI integration is what I believe you're after — it has already been [developed for PB](https://github.com/lumenlearning/candela/tree/master/wp-content/plugins/lti) and I believe it has been [implemented at scale](https://github.com/lumenlearning/candela/tree/master/wp-content/plugins/candela-lti) for a number of institutions with different Student Authentication Systems. Perhaps @bracken could confirm this assumption and speak to how that has worked out for the use cases that they have come across. 

Here's the use case that I think you're describing Hugh: A faculty member creates a book and sets it to 'private' allowing only authenticated users to see the content. I am a student with a student ID at my institution and I want to access a restricted resource using my existing institutional credentials. Using LTI, I authenticate with my student credentials in PB and am automatically assigned a 'subscriber' role. I read/comment/interact with the book.

**Comment by hughmcguire** [comment]
Hi @bdolor ... that is a particular use case (when there is an LTI to plug into, and yes I should look at that).

The generic usecase is ... same behaviour, no LTI to plug into ...

**Comment by hughmcguire** [comment]
note to self & others: integration with Shibboleth ?
see:
https://shibboleth.net/
