### ISSUE TITLE
PDF preview on subdomain installs is blocked by CORS policy

### ISSUE THREAD

**Issue by SteelWagstaff** [pressbooks/pressbooks#1975]
When users attempt to load the XHTML/Prince preview on books on subdirectory installations of Pressbooks, the preview appears briefly and then disappears/fails. The console displays the following error message: ```
the Access to XMLHttpRequest at 'https://pressbooks.com/app/uploads/sites/65066/pressbooks/css/prince-1577847317.css' from origin 'https://peranakan.pressbooks.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.```

See example at https://peranakan.pressbooks.com/format/xhtml?debug=prince

**Comment by SteelWagstaff** [comment]
https://github.com/pressbooks/textopress-infrastructure/pull/8 + https://github.com/pressbooks/pressbooks-infrastructure/pull/5 appear to be related

**Comment by SteelWagstaff** [comment]
See https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS/Errors/CORSMissingAllowOrigin?utm_source=devtools&utm_medium=firefox-cors-errors&utm_campaign=default

**Comment by ricardopressbooks** [comment]
PR: https://github.com/pressbooks/pressbooks/pull/2026

Allow subdomains in my docker environment and understand how nginx settings works inside dev-kit takes more time than I expected.
Trying to hard code prince css file (main file with CORS problem) for debugging purposes, that didn't work. Nevertheless, trellis looks with expected configuration for nginx. 
After try with different approach in my local nginx settings, I relalized that main issue was related to my local settings. After tried a generic solucion for my local environment  [that was documented for future references](https://github.com/pressbooks/setup-development-environment#how-to-allow-subdomains-for-new-books) I just replace the domain for subdomain in a funcion who generate the URL for contents.

**Comment by SteelWagstaff** [comment]
Looks good on textopress!
