### ISSUE TITLE
Add an exception for Sentry env variables

### ISSUE THREAD

**Issue by ricardopressbooks** [pressbooks/pressbooks#1978]
We already have set [Sentry env variables](https://github.com/pressbooks/private/issues/130#issuecomment-634938654) but if those variables are not set correctly we get the following errors in Logs:
```
[07-Jul-2020 23:07:24 UTC] Error initializing Sentry: The option "dsn" with value "https://@.ingest.sentry.io/" is invalid.
```

- [ ] Add default values and avoid Sentry entirely for those environments where Sentry is not being used.

**Comment by cagp-dev-mtl** [comment]
@ricardopressbooks , @SteelWagstaff  As per previous discussions, we agreed to enable Sentry only in staging, is that still the case? I recommend to keep Sentry enabled only on staging (textopress and integrations) and add a condition prevent invoking Sentry if the .env variables are not defined. (which is the case in production networks)

**Comment by ricardopressbooks** [comment]
PR: https://github.com/pressbooks/pressbooks/pull/1979
