### ISSUE TITLE
Large table over runs in HTML and EPUB

### ISSUE THREAD

**Issue by sswettenham** [pressbooks/pressbooks#198]
PressBooks 2.5.3
PressBooks Textbook 1.2.13
Host - PleskLinux56
Server - LiteSpeed
Wordpress 4.2.4 RAM 39,0/96M
mysqli 5.1.73
PHPv 5.6.1 - memory_limit 256M

--------------------------------------------
Table Sample
<table cellspacing="0">
<thead>
<tr>
<td></td>
<td><strong>LIBERAL</strong></td>
<td><strong>BEHAVIORIST</strong></td>
<td><strong>PROGRESSIVE</strong></td>
<td><strong>HUMANIST</strong></td>
<td><strong>RADICAL</strong></td>
</tr>
</thead>
<tbody>
<tr>
<td>PURPOSE OF EDUCATION</td>
<td>Develop intellectual abilities.</td>
<td>Emphasize skill acquisition.</td>
<td>Equip learners with practical knowledge and problem-solving skills.</td>
<td>Enhance personal growth, development.</td>
<td>Promote fundamental social, political &amp; economic changes in society.</td>
</tr>
<tr>
<td> VIEW OF LEARNER</td>
<td>Always a learner.

Seeks knowledge rather than information.</td>
<td>Needs to practice new behaviour.

Strong environmental influence on learning.</td>
<td>Learn by doing, experimenting and working with real-life problems.</td>
<td>Motivated, self-directed, responsible. Learners have unlimited potential.</td>
<td>Equal to the teacher within learning process.</td>
</tr>
<tr>
<td>ROLE OF TEACHER</td>
<td>Experts who transmit knowledge.

Direct the learning process.</td>
<td>Manage, control and positively reinforce. Predict and direct learning outcomes.</td>
<td>Organize, guide and establish interactive reciprocal relationships with learners.</td>
<td>Facilitate, support and partner.

Attentive to emotional and affective issues.</td>
<td>Coordinates and suggests but does not determine direction of learning.</td>
</tr>
<tr>
<td>METHODS USED</td>
<td> Lecture, readings, discussion groups.</td>
<td>Programmed instruction.

Computer-assisted learning.</td>
<td> Problem-based learning, cooperative learning.</td>
<td>Team teaching, group tasks, individualized learning.</td>
<td>Group identifies problems to solve.

Discussion groups.</td>
</tr>
<tr>
<td>KEY WORDS</td>
<td>Learning for its own sake.

Classical, traditional.</td>
<td>Stimulus-response.

Behaviour modification.

Learning objectives and evaluation of those objectives.</td>
<td>Based on experience.

Democratic principles.

Problem-solving.</td>
<td>Self-actualization, cooperation, group work, self-direction.</td>
<td>Raising of awareness of social problems.

Social action.

Non-compulsory learning activities.</td>
</tr>
<tr>
<td>AUTHORS</td>
<td>Socrates, Plato, Piaget</td>
<td>Pavlov, Skinner, Watson</td>
<td>Dewey, Parker, Lindeman</td>
<td>Rogers, Maslow. Knowles</td>
<td>Friere, Illich, Holt</td>
</tr>
<tr>
<td>EXAMPLES</td>
<td>University or college lectures.</td>
<td>CPR certification and renewal.</td>
<td>Problem-based health care programs.</td>
<td>Clinical pre-and post conferences.</td>
<td>Literacy training.</td>
</tr>
</tbody>
</table>

Webpage Read View - table appears to be non-responsive
![table-opentextbook-theme](https://cloud.githubusercontent.com/assets/360534/8533444/58b88a12-23f2-11e5-8815-e12a52292282.png)

ePUB Export View - Table contents cropped
![epub](https://cloud.githubusercontent.com/assets/360534/8876064/8ec43692-31da-11e5-9e3f-fc83a916baa0.png)

ePUB 3 Export View - Table contents cropped
![epub3](https://cloud.githubusercontent.com/assets/360534/8876100/be826bec-31da-11e5-9475-e5dc5a2e2347.png)

------------------------------
I tried using Tablepress and FooTable plugins to fix the overrun on webpages.  However, any additional shortcode will not be recognized by the exporters.
Noteworthy that FooTable did organize the webpage view better than using tables in Pressbooks Textbook editor.

TinyMCE table buttons with previously discussed large table is displayed correctly in mPDF export but not ePUB or webpage.

A good treatise on solutions to table over-runs:
http://exisweb.net/responsive-table-plugins-and-patterns
First choice - 4. Responsive Tables - keeps all content in focus and thus I like this one
Second choice is - 2. Foundation Zurb – Lock first column - keeps row and column headers in focus

------------------------------
Any quick fix solutions?

**Comment by hughmcguire** [comment]
try:
```
table { 
overflow-x: auto; 
}
```

**Comment by sswettenham** [comment]
Is this in pressbooks-textbook > themes-book > 0pentextbooks > styles.css  ?
This resulting addition of:
---
*  DEFAULT STYLES
 =================== */

table {
	border: 1px solid #000;
	border-width: 1px 0;
	overflow-x: auto;
}
---

removed the webpage display.

Also tried the following without success:
Themes > Editor > Open Textbooks > styles.css

/*******************************
	Textbook specific styles 
********************************/

#content table {
	border-spacing: 0;
	display: table;
	overflow-x: auto;
}

**Comment by hughmcguire** [comment]
what does "removed the webpage display." mean? can you be more specific? 

what does "without success" mean? can you be more specific?

**Comment by sswettenham** [comment]
As per Illustration A above.
