### ISSUE TITLE
Allow public books to be 'excluded from PB directory'

### ISSUE THREAD

**Issue by SteelWagstaff** [pressbooks/pressbooks#1982]
By default the new Pressbooks directory displays metadata for all public books on a given network. In some cases, individual book authors would like to exclude opt-out of having their public books displayed in the general directory. 

In cases where the network does not exclude all public, non-catalogued books from the directory, individual book admins should be given the option to remove their books from the directory without making them private.

- [x] Add an 'exclude from Pressbooks directory' option for book metadata (Add a check button to book info that allows book admins to exclude a book from directory)
- [ ] Add support for this field to the API & our directory fetcher
- [ ] when checked/unchecked, make sure that last updated date is also adjusted

**Comment by ricardopressbooks** [comment]
@SteelWagstaff , adding more E2E tests in https://github.com/pressbooks/pressbooks-book-directory-fe/issues/61 I found a couple of issues. I recommend wait for new PR related to issue mentioned before test it. Thank you.

**Comment by ricardopressbooks** [comment]
PR with fixes: https://github.com/pressbooks/pressbooks-book-directory-fe/pull/75

**Comment by SteelWagstaff** [comment]
Setting appears for individual books in sharing & privacy setting (with correct language) when global setting for network is not checked. Remaining work captured in future task: https://github.com/pressbooks/book-directory-fetcher/issues/29
