### ISSUE TITLE
Activating the PlugIn Problem

### ISSUE THREAD

**Issue by JasonSWrench** [pressbooks/pressbooks#1983]
When I try to activate the plugin, I receive the following error message. My hosting people told me to reach out to you, so fingers crossed:

Fatal error: Uncaught Error: Call to undefined function update_blog_option() in /hermes/bosnaweb15a/b2482/ipw.roadspea/public_html/communication/wp-content/plugins/pressbooks/compatibility.php:103 Stack trace: #0 /hermes/bosnaweb15a/b2482/ipw.roadspea/public_html/communication/wp-includes/class-wp-hook.php(287): pb_register_activation_hook('') #1 /hermes/bosnaweb15a/b2482/ipw.roadspea/public_html/communication/wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters('', Array) #2 /hermes/bosnaweb15a/b2482/ipw.roadspea/public_html/communication/wp-includes/plugin.php(478): WP_Hook->do_action(Array) #3 /hermes/bosnaweb15a/b2482/ipw.roadspea/public_html/communication/wp-admin/plugins.php(179): do_action('activate_pressb...') #4 {main} thrown in /hermes/bosnaweb15a/b2482/ipw.roadspea/public_html/communication/wp-content/plugins/pressbooks/compatibility.php on line 103

I have recently upgraded to WordPress 5.4.2
I also upped the PhP to 7.3

I admit, I don't know much about this world. 

Thanks,

Jason

**Comment by cagp-dev-mtl** [comment]
Hi Janson, please ensure that your WP installation has the multi-site option enabled:

https://wordpress.org/support/article/glossary/#multisite

Let us know.

Carlos

**Comment by JasonSWrench** [comment]
Carlos:

Thanks! I knew it would be something simple (and it was staring me in the face).

Jason

**Comment by cagp-dev-mtl** [comment]
Glad to hear you got it fixed.

Best.
