### ISSUE TITLE
Custom header tag for Table of Contents listing on Homepage

### ISSUE THREAD

**Issue by sswettenham** [pressbooks/pressbooks#201]
Situation:
Editor displays < H1 > as Title Case
Webpage presentation displays < H1 > as UPPERCASE.

Challenge:
Back Matter > About the Authors - would like the heading to be Title Case for "PhD" presentation

Inquiry:
Is there a way to have a custom tag that would display < H1 > as Title Case on  webpage presentation?

**Comment by hughmcguire** [comment]
This will differ from theme to theme. If you have particular desires for a new theme, I recommend you create a new theme & modify it as you like.
