### ISSUE TITLE
Recommended plugins feature no longer available

### ISSUE THREAD

**Issue by figureone** [pressbooks/pressbooks#2033]
Looks like it's due to the recommendation server shutting down:
https://pressbooks-plugins.now.sh/api/plugin-recommendations

https://github.com/pressbooks/pressbooks/blob/dev/inc/utility/namespace.php#L590

![Screen Shot 2020-09-17 at 11 24 34 AM](https://user-images.githubusercontent.com/125274/93530011-971b6200-f8d8-11ea-8007-3533a05b4172.png)

**Comment by SteelWagstaff** [comment]
Thanks @figureone -- you're absolutely right. The service we were using to host the 'recommended plugins' server has been discontinued. We'll look at this soon.

**Comment by SteelWagstaff** [comment]
@figureone The recommended plugins server should be fixed and up again. Let us know if you're still running into problems?

**Comment by figureone** [comment]
Yep, the Recommended Plugins tab looks great. Thanks guys for tackling that one so quickly. Cheers!
