### ISSUE TITLE
PrinceXMl - Unicode text not displayed on release 5.16.2 

### ISSUE THREAD

**Issue by omshivaprakash** [pressbooks/pressbooks#2038]
### Prerequisites

* [x] Can you reproduce the behavior you wish to address with [all other plugins deactivated](http://codex.wordpress.org/Multisite_Network_Administration#Plugins)?
* [x] Are you running the [latest version of Pressbooks](http://github.com/pressbooks/pressbooks/releases/latest/) and the [latest version of WordPress](http://codex.wordpress.org/Upgrading_WordPress)?
* [x] Are you experiencing this issue with one of our built-in root or book themes?
* [x] Did you [perform a cursory search](https://github.com/issues?q=+is%3Aissue+repo%3Apressbooks%2Fpressbooks) to see if your bug or enhancement is already listed?

### Steps to Reproduce

1. Changed Themes options ->  Language & Script Support -> selected kannada
2. Tried to export PDF for print
3. Export PDF shows gibrish.

**Expected behavior:** 

It should display the proper unicode text. It used to work just before the upgrade. 

**Actual behavior:** 

Shows ???? marks in exported pdf

#### Book Info

Book ID: 28
Book URL: https://ebooks.techfiz.com/book1
Book Privacy: Public

#### Browser

Platform: OS X
Browser Name: Chrome
Browser Version: 86.0.4240.42
User Agent String: Mozilla/5.0 (Macintosh; Intel Mac OS X 11_0_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.42 Safari/537.36

#### WordPress Configuration

Network URL: http://ebooks.techfiz.com/
Network Type: Subdirectory
Version: 5.5.1
Language: en_US
WP_ENV: Not set
WP_DEBUG: Enabled
Memory Limit: 64M

#### Pressbooks Configuration

Version: 5.16.2
Book Theme: Austen Classic
Book Theme Version: 1.7.0
Root Theme: Aldine
Root Theme Version: 1.8.2

#### Pressbooks Dependencies

Epubcheck: Installed
Kindlegen: Installed
xmllint: Installed
PrinceXML: Installed
Saxon-HE: Installed

#### Must-Use Plugins

hm-autoloader.php: n/a
ManageWP - Worker Loader: n/a

#### Network Active Plugins

Adminimize: 1.11.7
Akismet Anti-Spam: 4.1.6
GitHub Updater: 9.8.1
Hide My WP Ghost Lite: 4.0.11
Hypothesis: 0.6.0
ManageWP - Worker: 4.9.7
mPDF for Pressbooks: 3.3.1
Pressbooks: 5.16.2
TablePress: 1.12
WP QuickLaTeX: 3.8.6

#### Book Active Plugins

Adminimize: 1.11.7
Akismet Anti-Spam: 4.1.6
GitHub Updater: 9.8.1
Hide My WP Ghost Lite: 4.0.11
Hypothesis: 0.6.0
ManageWP - Worker: 4.9.7
mPDF for Pressbooks: 3.3.1
Pressbooks: 5.16.2
TablePress: 1.12
WP QuickLaTeX: 3.8.6

#### Inactive Plugins

Better Search Replace: 1.3.3
H5P: 1.15.0
Instant Articles for WP: 4.2.1

#### Server Configuration

PHP Version: 7.3.22
MySQL Version: 5.7.31
Webserver Info: Apache

#### PHP Configuration

Safe Mode: Disabled
Memory Limit: 256M
Upload Max Size: 100M
Post Max Size: 120M
Upload Max Filesize: 100M
Time Limit: 180
Max Input Vars: 3000
URL-aware fopen: On (1)
Display Errors: On (1)

#### PHP Extensions

OPcache: Zend
XDebug: Disabled
cURL: Supported
cURL Version: 7.72.0
imagick: Installed
xsl: Installed

**Comment by omshivaprakash** [comment]
Additionally i started seeing this issue - Your Bengali font could not be downloaded from https://github.com/googlefonts/noto-fonts/raw/master/unhinted/NotoSansBengali/NotoSansBengali-Bold.ttf.

Not Found

Now, not able to download other language fonts too.

**Comment by SteelWagstaff** [comment]
Hi @omshivaprakash there was a sudden change in the path of the Google Noto fonts we use to provide these features that broke this feature. We will be including a fix in our next release (see https://github.com/pressbooks/pressbooks/pull/2036), which should be coming out next week. Sorry for the inconvenience in the meantime.

**Comment by omshivaprakash** [comment]
@SteelWagstaff I see that its picking the kannada fonts. Why im still not able to see the text?

**Comment by omshivaprakash** [comment]
Latest version resolves this.
