### ISSUE TITLE
Clean up user dashboard

### ISSUE THREAD

**Issue by SteelWagstaff** [pressbooks/pressbooks#2041]
We'd like to use the `/wp-admin/user/` page as a potential landing spot post login for authenticated users, especially those without a role in any books.Currently, logged-in users who visit this page see the site health status and WP news widgets, which haven't been removed from this page. 
![Screenshot from 2020-10-09 08-34-39](https://user-images.githubusercontent.com/13485451/95602833-552e9900-0a0a-11eb-980b-4c9caf91e3c4.png)

- [x] Remove the unwanted widgets from the wp-admin/user page. For models for doing this, see https://github.com/pressbooks/pressbooks/blob/716d50e7d65c27c1e5acef9379fa19069855e039/inc/admin/dashboard/namespace.php#L25-L109

**Comment by richard015ar** [comment]
This task was scoped to: Remove site health and wp news widgets.
PR: https://github.com/pressbooks/pressbooks/pull/2045

**Comment by SteelWagstaff** [comment]
Tested and confirmed working as expected locally and on textopress and integrations.
