### ISSUE TITLE
Send main site domain as network for subdomain book networks

### ISSUE THREAD

**Issue by ho-man-chan** [pressbooks/pressbooks#2044]
Book directory fetcher does not recognize networks that use book URL in their network URL.
The network URL we sent to the book directory fetcher should not include the book complete book URL but only the main site URL.

Example: 
BAD: https://bookname.textopress.com
GOOD: https://integrations.pressbooks.network/bookname

All network should give only the main site
https://bookname.textopress.com -> https://textopress.com
https://integrations.pressbooks.network/bookname -> https://integrations.pressbooks.network

solution
update pressbooks to submit only the main network domain. We can probably find out if the network uses subdomain or not as their book url. if yes, remove the book url part from the host. 

https://github.com/pressbooks/pressbooks/blob/04bd5de1f2a2fbb11042cc3296daf4db05526c29/inc/class-bookdirectory.php#L135

context
When textopress was set to display all public books and I manually excluded an individual book from textopress from the directory using the book's sharing & privacy setting, it was not immediately removed from the directory listing at dev.pressbooks.directory, nor was it removed during the next cron job/sync. See https://portuguese.textopress.com/wp/wp-admin/options-general.php?page=pressbooks_sharingandprivacy_options

**Comment by SteelWagstaff** [comment]
@ho-man-chan would one of these functions get us the value you need? https://developer.wordpress.org/reference/functions/network_home_url/ or https://developer.wordpress.org/reference/functions/get_home_url/

**Comment by ho-man-chan** [comment]
> @ho-man-chan would one of these functions get us the value we need? https://developer.wordpress.org/reference/functions/network_home_url/ or https://developer.wordpress.org/reference/functions/get_home_url/

Looks promising! Thanks @SteelWagstaff
