### ISSUE TITLE
'Lost Password' page is broken when accessed directly from a book (instead of homepage)

### ISSUE THREAD

**Issue by pb-amy** [pressbooks/pressbooks#2061]
### Description

When someone decides to log-in or reset their password, they can do so by navigating from the network's home page or from the book site, both using the top menu bar.

From the home page, the "Lost Password" module works perfectly from the network's home page. ex: https://cod.pressbooks.pub/wp/wp-login.php?action=lostpassword

However, when you are on the book site, and you navigate to Log In -> Lost Password, the page is broken. Ex: https://cod.pressbooks.pub/**wp**/introductiontopsychology/wp-login.php?action=lostpassword

This happens on Aldine and the Publisher theme. The problem only appears on subdirectory installations (subdomains appear to be unaffected).

### Steps to Reproduce

1. Go onto a book site
2. Click on Log In on the top menu bar
3. Click on "Lost your Password?" in the login page.

**Expected behavior:** All 'Lost your Password?' pages should take you to working password reset pages.

**Actual behavior:** When 'Lost Password' module is accessed through the book site, the user is taken to a page which doesn't exist: `https://[institution].pressbooks.pub/**wp**/booktitle/wp-login.php?action=lostpassword` rather than `https://[institution].pressbooks.pub/booktitle/wp-login.php?action=lostpassword`

**Comment by pb-amy** [comment]
Bug discovered on this ticket: https://pressbooks.zendesk.com/agent/tickets/3066

**Comment by arzola** [comment]
@SteelWagstaff / @pb-amy 

We have two reset password valid URLs the "network one" and the "book one" 

**Network**

https://cod.pressbooks.pub/wp-login.php?action=lostpassword

**Book**

https://cod.pressbooks.pub/actionresearch/wp-login.php?action=lostpassword

Should we redirect to the "network one" ? as the expected behavior says? Those are slightly different logins, the network one it will take you to the general dashboard and the book one to the book administration directly

**Comment by SteelWagstaff** [comment]
@arzola thanks for checking. When they attempt to reset their login from the book site login, we should send them to the book one. I.e. https://cod.pressbooks.pub/actionresearch/wp-login.php?action=lostpassword. It looks like the problem is that we're adding /wp/ to the path?

**Comment by arzola** [comment]
Yes that is the problem I just asked because the expected behavior, but yeah thanks I will remove the Wp for this link I was thinking to use a filter for the reset password link but first I need to confirm the nginx rewrite rules

**Comment by SteelWagstaff** [comment]
Ned suggested looking at https://github.com/roots/multisite-url-fixer + https://github.com/roots/bedrock/issues/250. The extra `/wp/` in path issue does not appear to be present in networks (like BCcampus), which do not have this plugin installed (see password reset from https://opentextbc.ca/universityphysicsv2openstax/wp-login.php for example)

**Comment by pb-amy** [comment]
Reported again on here: https://pressbooks.zendesk.com/agent/tickets/3595

**Comment by SteelWagstaff** [comment]
Users are now able to login from the book home page on integrations (subdirectory install). `/wp/` still appears in the path for the main login page and for the login pages on textopress (subdomain install), but it doesn't produce a 404 error.
