### ISSUE TITLE
Fix broken unit test

### ISSUE THREAD

**Issue by SteelWagstaff** [pressbooks/pressbooks#2064]
```
PressbooksTest::test_allowedRootThemes
Failed asserting that actual size 0 matches expected size 1.
```
https://travis-ci.com/github/pressbooks/pressbooks/jobs/462163040

We think the issue is that the test expects twentyseventeen to be present as a network root theme: see https://github.com/pressbooks/pressbooks/blob/d3275b9c903363cf66d1a344d75b2d7069c7f146/tests/test-pressbooks.php#L38-L39 + https://github.com/pressbooks/pressbooks/blob/d3275b9c903363cf66d1a344d75b2d7069c7f146/inc/class-pressbooks.php#L91-L103

Perhaps the latest version of WordPress changes something so that the test fails: https://github.com/WordPress/WordPress/tree/master/wp-content/themes/twentyseventeen? Unclear why this is failing -- needs more research.

Ho Man suggests looking into https://github.com/pressbooks/pressbooks/blob/dev/bin/install-wp-tests.sh

**Comment by richard015ar** [comment]
This problem was solved in this PR: https://github.com/pressbooks/pressbooks/pull/2063
See: https://github.com/pressbooks/pressbooks/pull/2063#issuecomment-750422191

**Comment by ho-man-chan** [comment]
Reviewed and looks good. Since this PR is combined in Sentry's PR, it will be tested together once Sentry is ready. Would be good to separate them next time.
