### ISSUE TITLE
Subscribers of one book can read private chapters of another book

### ISSUE THREAD

**Issue by marcusschiesser** [pressbooks/pressbooks#207]
There is a user for one book logged in (role subscriber). This user is just added to this one book not the any other book.
Nevertheless the user can access private chapters of another book he is not added as subscriber too.
Both books are public books with private chapters and for both books subscribers are allowed to see private chapters.

Expected behaviour would be that a subscriber can only see private chapters of the books he is a subscriber for.

**Comment by greatislander** [comment]
@marcusschiesser Is this with version 2.5.3 or the Github development version?

**Comment by marcusschiesser** [comment]
Tested with 2.5.3

**Comment by greatislander** [comment]
@marcusschiesser Can you check out the dev branch and see if this issue is fixed for you? It appears to be in my testing.

**Comment by greatislander** [comment]
@marcusschiesser This should be fixed in 2.5.4 which is out now. Please confirm.

**Comment by marcusschiesser** [comment]
thanks i confirm this is fixed in 2.5.4

On Thu, Aug 13, 2015 at 12:20 AM, Ned Zimmerman <notifications@github.com>
wrote:

> @marcusschiesser <https://github.com/marcusschiesser> This should be
> fixed in 2.5.4 which is out now. Please confirm.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pressbooks/pressbooks/issues/207#issuecomment-130360747>
> .
>



-- 
Marcus Schiesser
Email: mail@marcusschiesser.de

http://www.marcusschiesser.de
