### ISSUE TITLE
Add docs in Readme for Sentry Integration

### ISSUE THREAD

**Issue by richard015ar** [pressbooks/pressbooks#2075]
Add docs about Sentry integration in Readme file with all necessary information to integrate Sentry in Pressbooks project.
Also, we can duplicate the private available document, rename the links and make a final copy.

**Comment by SteelWagstaff** [comment]
Final copy ready to share with others here: https://docs.google.com/document/d/1hg35gRWlxcQqC2DElrBi2btLFQQXvMgs-NhgvmnMqpA/edit#

**Comment by SteelWagstaff** [comment]
@ricardopressbooks I added a link to the document above to the release notes (https://github.com/pressbooks/pressbooks/releases), instead of adding to readme, since I think we're planning to move this out of core Pressbooks into a plugin soon. Work for you?
