### ISSUE TITLE
Read button for public books with private chapters leads to first non-private chapter

### ISSUE THREAD

**Issue by marcusschiesser** [pressbooks/pressbooks#208]
Given: A subscriber is logged in for a public book with private chapters. For this book subscribers are generally entitled to view private chapters.

Action: In the books overview page the 'read' button is pressed

Result: User lands on the first non-private chapter which may be in the middle of the book.

Expected result: User lands on the first chapter of the book (as he is allowed to view all chapters of the book, including the private chapters)

**Comment by greatislander** [comment]
@marcusschiesser Thanks for catching this. Can you let me know which version of Pressbooks you are using? 2.5.3 or the development version from Github?

**Comment by marcusschiesser** [comment]
Also with 2.5.3

**Comment by greatislander** [comment]
Thanks for catching this, @marcusschiesser—it should be fixed in the dev branch. Please let me know.

**Comment by greatislander** [comment]
@marcusschiesser This should be fixed in 2.5.4 which is out now. Please confirm.

**Comment by marcusschiesser** [comment]
thanks i confirm this is fixed in 2.5.4

On Thu, Aug 13, 2015 at 12:20 AM, Ned Zimmerman <notifications@github.com>
wrote:

> @marcusschiesser <https://github.com/marcusschiesser> This should be
> fixed in 2.5.4 which is out now. Please confirm.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pressbooks/pressbooks/issues/208#issuecomment-130360776>
> .
>



-- 
Marcus Schiesser
Email: mail@marcusschiesser.de

http://www.marcusschiesser.de
