### ISSUE TITLE
Add name for BISAC subjects in API for PB Directory

### ISSUE THREAD

**Issue by richard015ar** [pressbooks/pressbooks#2084]
Directory fetcher save the `name` attribute for the `about` field in the API:
![namefield_subject](https://user-images.githubusercontent.com/13248424/106491301-b8927a00-6484-11eb-808b-c5cec3f24506.png)
This additional field is displayed through: https://github.com/pressbooks/pressbooks/blob/0e8c4f5f4f49c501e0ba2b29ff2662751e5bba07/inc/metadata/namespace.php#L232 and https://github.com/pressbooks/pressbooks/blob/0e8c4f5f4f49c501e0ba2b29ff2662751e5bba07/inc/metadata/namespace.php#L243

But those are only for thema subjects. 
We should add the name field as well for Bisac objects here: https://github.com/pressbooks/pressbooks/blob/0e8c4f5f4f49c501e0ba2b29ff2662751e5bba07/inc/metadata/namespace.php#L253

There are some books that contains Bisac subjects and `name` field is not displayed in the `about` object: 
![about-noname](https://user-images.githubusercontent.com/13248424/106491776-36568580-6485-11eb-87c3-346da219c3a5.png)

In those cases, Directory Fetcher will store in Algolia null values for those subjects:
![null-subject-algolia](https://user-images.githubusercontent.com/13248424/106491964-69991480-6485-11eb-80ab-70a9a05bf7b9.png)
And therefore empty subjects are displayed in the Front End app:
![empty-subj-fe](https://user-images.githubusercontent.com/13248424/106492194-a8c76580-6485-11eb-8efd-e7557316c825.png)

Bisac subjects can be added/edited/deleted in the Add Book action, at the end of the big form:
![bisac-subj](https://user-images.githubusercontent.com/13248424/106492614-1f646300-6486-11eb-90c0-49383c451249.png)

**Comment by SteelWagstaff** [comment]
Nice catch. Thanks @richard015ar

**Comment by SteelWagstaff** [comment]
Closing in favor of https://github.com/pressbooks/bi-data-manager/issues/291
