### ISSUE TITLE
Error in Rich Text editor after latest update

### ISSUE THREAD

**Issue by SteelWagstaff** [pressbooks/pressbooks#2085]
### Prerequisites

* [ ] Can you reproduce the behavior you wish to address with [all other plugins deactivated](http://codex.wordpress.org/Multisite_Network_Administration#Plugins)?
* [x] Are you running the [latest version of Pressbooks](http://github.com/pressbooks/pressbooks/releases/latest/) and the [latest version of WordPress](http://codex.wordpress.org/Upgrading_WordPress)?
* [x] Are you experiencing this issue with one of our built-in root or book themes?
* [x] Did you [perform a cursory search](https://github.com/issues?q=+is%3Aissue+repo%3Apressbooks%2Fpressbooks) to see if your bug or enhancement is already listed?

### Description
After updating to Pressbooks 5.18.0, several open source users are reporting that they get a 'Failed to initialize plugin: table' error on any page which uses the TinyMCE rich-text editor (for example, the Book Info and edit part/chapter/front-matter pages all display this warning). 
![675399fbea40c6cd9a02d8dc505ad9c3d069c0ee](https://user-images.githubusercontent.com/13485451/106644557-12a44580-6540-11eb-9b17-8547b906007c.png)

### Steps to Reproduce
I cannot reproduce on Pressbooks-hosted networks. We recently bumped the version of TinyMCE: https://github.com/pressbooks/pressbooks/pull/2069. I wonder whether there also needs to be a corresponding code adjustment or rebuild scripts action for the table MCE plugin we've built: https://github.com/pressbooks/pressbooks/blob/fb9320e3af09ddd3373a19f5b37d2feba07736c2/inc/editor/namespace.php#L163 + https://github.com/pressbooks/pressbooks/blob/dev/assets/dist/scripts/table.js

### System Information

See https://pressbooks.community/t/php-7-4-compatibility-and-other-issue/1587/7 for more details, including the diagnostic information from one affected user.

**Comment by techfiz** [comment]
I started seeing this on our portal too after upgrade.

**Comment by SteelWagstaff** [comment]
Hi @techfiz we think this error was related to the TinyMCE dependency update we included in Pressbooks 5.18.0 (we got ahead of WordPress on TinyMCE versions). We’ve reverted the change in Pressbooks 5.18.1 which was yesterday: https://github.com/pressbooks/pressbooks/releases/tag/5.18.1. Updating to that version should fix the issue.
