### ISSUE TITLE
Links cannot be included in the Short & Long descriptions

### ISSUE THREAD

**Issue by pb-amy** [pressbooks/pressbooks#2088]
### Description
Found on the following Zendesk tickets: https://pressbooks.zendesk.com/agent/tickets/3909 (VT) and https://pressbooks.zendesk.com/agent/tickets/3976 (OpenOregon)

When adding a **Short or Long Description** in **Book Info**, you cannot add a link to any text; the `<a href="link">text</a>` will revert to  `<a href="">text</a>`. The hyperlink will still be there, but upon clicking on it, it will take you to the top of the page.

View what's happening on this video: https://drive.google.com/file/d/1gW95iEtR3lE0BHfvCNO7jfFcxrylU4eO/view

https://user-images.githubusercontent.com/61845107/106620824-f1dbf000-653f-11eb-9f12-b4602d197caa.mp4

### Steps to Reproduce

1. Create a hyperlink in the short / long description and save.
2. Go on the webbook, go down to the long description and click on it.
3. Look back in the book info and see that the link itself is gone.

**Expected behavior:** Hyperlinks should work, and should take you to the link.

**Actual behavior:** The text is linked but the field is empty.

**Comment by richard015ar** [comment]
### Tests on integrations
Those are the following use cases I tried in both fields: Short and Long descriptions:
- `I am a 'description' with "a'" <a href="link.com">link</a>`
- `<a href="link.co">link'</a><a href="link.com">'link'</a>` -> Result: Both links works
- `<a href="link.com" target='_link'>link</a>` -> Result: link with target attribute works.
- `<a href='link.com' target="_link">link</a> <script>alert("hi");</script>` -> Result: it works, and single quotes are replaced by double quotes.
- `<div>I am div</div><a href="link.com" target="_link">link</a>` -> Result: it works.
- `<a fakeattr='asd'>link</a>` -> Result: link works with any href and extra attribute is deleted.

All cases works as expected. 
Thank you @arzola! it was a nice job!
