### ISSUE TITLE
Feature Request: Don't redirect users to the backend after login

### ISSUE THREAD

**Issue by marcusschiesser** [pressbooks/pressbooks#210]
Given: A User requests a books landing page, e.g.:
http://{server}/{bookname}

Action: User clicks on the login button and confirms his credentials

Result: User is logged in and redirected to the backend (wp-admin)

Expected Result: User is logged in and is redirect to http://{server}/{bookname}

This sounds more logic to me, should be at least an option.

**Comment by hughmcguire** [comment]
hi @marcusschiesser  ... 
- i agree with this expected behaviour for a *subscriber*
- however for author/editor/administrator ... I think the backend is where you would expect to end up after logging in ... am I correct? 

NOTE: there is some other work that should/could be done to clean up the subscriber backend as well ... .

**Comment by marcusschiesser** [comment]
for the subscriber it is definitely like that - for other roles it also
might make sense, e.g. if they want to review the text. Generally other
roles could still login into the backend by requesting /wp-admin. As
mentioned I am talking about clicking on the 'Login" button from the
landing page.

On Thu, Aug 13, 2015 at 10:57 PM, Hugh McGuire <notifications@github.com>
wrote:

> hi @marcusschiesser <https://github.com/marcusschiesser> ...
>
>    - i agree with this expected behaviour for a *subscriber*
>    - however for author/editor/administrator ... I think the backend is
>    where you would expect to end up after logging in ... am I correct?
>
> NOTE: there is some other work that should/could be done to clean up the
> subscriber backend as well ... .
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pressbooks/pressbooks/issues/210#issuecomment-130721029>
> .
>



-- 
Marcus Schiesser
Email: mail@marcusschiesser.de

http://www.marcusschiesser.de

**Comment by greatislander** [comment]
As always, my inclination here is to follow the WordPress convention, which is:

1. If you are anywhere on the public-facing part of a website and you click the "Log In" button, you proceed to the login screen and once you have successfully authenticated you are returned to the page you were viewing before (but with the new privileges of being logged in, e.g. administrators can click the "Admin" button and proceed to the dashboard).
2. If you try to visit `/wp-admin/` or anything on the admin side when you aren't logged in, you are taken to the login screen and then to the desired admin page once you have successfully authenticated.

Would you be happy if I adjusted Pressbooks' behaviour to better align it with this convention, @hughmcguire?

**Comment by greatislander** [comment]
@hughmcguire I've changed the login buttons on the user catalog page, Pressbooks Publisher header, and book theme to redirect to the page being viewed after login.
