### ISSUE TITLE
Import changes embedded base64 encoded images

### ISSUE THREAD

**Issue by BenGig** [pressbooks/pressbooks#2106]
### Prerequisites

* [x] Can you reproduce the behavior you wish to address with [all other plugins deactivated](http://codex.wordpress.org/Multisite_Network_Administration#Plugins)?
* [ ] Are you running the [latest version of Pressbooks](http://github.com/pressbooks/pressbooks/releases/latest/) and the [latest version of WordPress](http://codex.wordpress.org/Upgrading_WordPress)? Pressbooks is up to date
* [x] Are you experiencing this issue with one of our built-in root or book themes?
* [x] Did you [perform a cursory search](https://github.com/issues?q=+is%3Aissue+repo%3Apressbooks%2Fpressbooks) to see if your bug or enhancement is already listed?

### Description

The import function scans for IMG tags. If an import contains embedded base64 encoded images, the import function treats them as broken and adds a "#fixme" at the end of the src attribute. In the case of base64, this leads to issues, particularly with Safari on iOS.

### Steps to Reproduce

1. Create an XML containing base64 encoded images
2. Import
3. Check in browser: base64 string ends with "#fixme". Safari on iOS shows no images.

**Expected behavior:** base64 encoded images should pass without being changed

**Actual behavior:** base64 string is changed

#### Root Blog Info

Root Blog ID: 1
Root Blog URL: http://pressbooks.benet.local/

#### Browser

Platform: Windows
Browser Name: Firefox
Browser Version: 78.0
User Agent String: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:78.0) Gecko/20100101 Firefox/78.0 Waterfox/78.8.0

#### WordPress Configuration

Network URL: http://pressbooks.benet.local/
Network Type: Subdirectory
Version: 5.6
Language: en_US
WP_ENV: Not set
WP_DEBUG: Disabled
Memory Limit: 64M

#### Pressbooks Configuration

Version: 5.18.2
Root Theme: Aldine
Root Theme Version: 1.9.0

#### Pressbooks Dependencies

Epubcheck: Not Installed
Kindlegen: Not Installed
xmllint: Not Installed
PrinceXML: Not Installed
Saxon-HE: Not Installed

#### Must-Use Plugins

hm-autoloader.php: n/a

#### Network Active Plugins

Hello Dolly: 1.7.2
Pressbooks: 5.18.2
WordPress Importer: 0.7

#### Root Blog Active Plugins

Hello Dolly: 1.7.2
Pressbooks: 5.18.2
WordPress Importer: 0.7

#### Inactive Plugins

Akismet Anti-Spam: 4.1.7

#### Server Configuration

PHP Version: 7.3.19-1~deb10u1
MySQL Version: 5.5.5
Webserver Info: Apache/2.4.38 (Debian)

#### PHP Configuration

Safe Mode: Disabled
Memory Limit: -1
Upload Max Size: 20M
Post Max Size: 20M
Upload Max Filesize: 20M
Time Limit: 30
Max Input Vars: 1000
URL-aware fopen: On (1)
Display Errors: N/A

#### PHP Extensions

OPcache: Zend
XDebug: Disabled
cURL: Not Supported
imagick: Not Installed
xsl: Installed

**Comment by SteelWagstaff** [comment]
@BenGig thanks for filing the issue and opening the PR. Our team is working to complete our current sprint right now, but will try to look at this and reply to you as soon as we're able. Hopefully before the end of March.

**Comment by SteelWagstaff** [comment]
Fixed by https://github.com/pressbooks/pressbooks/pull/2132
