### ISSUE TITLE
users with many books (50+ ? 75+ ?) have strange behaviour, disappearing admin interface

### ISSUE THREAD

**Issue by hughmcguire** [pressbooks/pressbooks#211]
case: 
-- user is admin/member of 50+ ? 75+ ? 95+ ? books
-- user logs in ... and sees a mostly blank admin interface
-- cannot navigate 
-- going directly to, eg, ~/bookname/wp-admin ... delivers similar mostly-blank screen & inability to access text
-- ditto trying to edit an individual chapter

see: 
<img width="844" alt="2015-08-13 at 4 06 pm" src="https://cloud.githubusercontent.com/assets/1991100/9260309/f56398de-41d4-11e5-9e78-ed8178c2ae04.png">

@greatislander , i will send you some credentials to investigate.

**Comment by greatislander** [comment]
This is fixed—but it raises another issue. Will send details.
