### ISSUE TITLE
Travis issue: Test failing

### ISSUE THREAD

**Issue by richard015ar** [pressbooks/pressbooks#2112]
Tests are failing in travis for some reason:
```
PHPUnit 7.5.20 by Sebastian Bergmann and contributors.
...............................................................  63 / 643 (  9%)
............................................................... 126 / 643 ( 19%)
............................................................... 189 / 643 ( 29%)
............................................................... 252 / 643 ( 39%)
..FFE.......................................................... 315 / 643 ( 48%)
............................................................... 378 / 643 ( 58%)
............................................................... 441 / 643 ( 68%)
............................................................... 504 / 643 ( 78%)
............................................................... 567 / 643 ( 88%)
............................................................... 630 / 643 ( 97%)
.............                                                   643 / 643 (100%)
Time: 3.47 minutes, Memory: 1.54 GB
There was 1 error:
1) IntegrationsTest::test_ImportPressbooksWxr
exif_read_data(4tatoos.jpg): Illegal IFD size: 2 + 0x1E00*12 = 0x16802 > 0x165C
/tmp/wordpress/wp-admin/includes/image.php:800
/tmp/wordpress/wp-admin/includes/media.php:466
/home/travis/build/[secure]/[secure]/inc/modules/import/wordpress/class-downloads.php:156
/home/travis/build/[secure]/[secure]/inc/modules/import/wordpress/class-downloads.php:70
/home/travis/build/[secure]/[secure]/inc/modules/import/wordpress/class-wxr.php:274
/home/travis/build/[secure]/[secure]/tests/test-integrations.php:133
--
There were 2 failures:
1) IntegrationsTest::test_cloneRemoteBook
Failed asserting that false is true.
/home/travis/build/[secure]/[secure]/tests/test-integrations.php:23
2) IntegrationsTest::test_ImportUsingCloningApi
Failed asserting that false is true.
/home/travis/build/[secure]/[secure]/tests/test-integrations.php:79
ERRORS!
Tests: 643, Assertions: 9242, Errors: 1, Failures: 2.
```
Review and fix this issue in order to be able to merge new changes in the repo.

There is a possibility this PR has a relation with the error: https://github.com/pressbooks/pressbooks/pull/2095/files
After that PR, travis started throwing the test failing error, and also looks like those are images-related.

**Comment by greatislander** [comment]
These three errors and failures all have to do with this book: https://pbtest.pressbooks.com

1. `IntegrationsTest::test_ImportPressbooksWxr` is failing to load this image: https://pressbooks.com/app/uploads/sites/109504/2018/08/4tatoos.jpg
2. `IntegrationsTest::test_cloneRemoteBook` is failing to clone that book.
3. `IntegrationsTest::test_ImportUsingCloningApi` is failing to clone that book.

#2095 was related to the Cover Generator's bar code generation code so I don't think it's related.

One thing that's notable is that the tests also fail in Github Actions so it's not a Travis issue (see here: https://github.com/greatislander/pressbooks/runs/2096937331?check_suite_focus=true).

**Comment by SteelWagstaff** [comment]
I was just able to clone the book manually to integrations with no issues. @ho-man-chan is it possible that Travis/GitHub actions have been IP banned from Pressbooks.com somehow?

**Comment by SteelWagstaff** [comment]
We've determined that the test failures are related to the WordPress 5.7 release -- we will fix temporarily by changing travis file to use WP 5.6.2 for test suite (the version of WordPress we use in production). Later we will seek to understand why tests break with WP 5.7 and address.
