### ISSUE TITLE
Searching for XMLLINT

### ISSUE THREAD

**Issue by sswettenham** [pressbooks/pressbooks#212]
readme.txt states:

* For XML validation install [xmllint](http://xmlsoft.org/xmllint.html) - Version 20800

The aforementioned link goes to an information page but no download. Downloads at https://git.gnome.org/browse/libxml2/refs/tags only display v2.8.0

If possible would great if the hard to find dependencies were included to reduce confusion.
Thanks,

**Comment by greatislander** [comment]
Hi @sswettenham— we include dependencies where possible but xmllint is software that has to be installed externally on any system that would be running Pressbooks and as such cannot be included with Pressbooks. I did a quick Google search for "xmllint installation" and the [fourth result](https://atom.io/packages/linter-xmllint) gave me these instructions:

> Before using this package, you must ensure that xmllint is installed on your system. On recent versions of Mac OS X, xmllint comes pre-installed. To install xmllint on other platforms, do the following:

> 1. On Linux:

> `[sudo] apt-get install libxml2-utils`

> 2. On Windows, follow the instructions [here](http://flowingmotion.jojordan.org/2011/10/08/3-steps-to-download-xmllint/).

Another tip which works for many external packages that Pressbooks requires or uses—such as xmllint, Java and Prince—is to type `which [command]` in your system's terminal interface. For example, typing:

`which xmllint`

…in the Terminal application on my Mac returns the following:

`/usr/bin/xmllint`

This indicates that the software is installed and can be run from the returned path value.

I hope this helps.

**Comment by sswettenham** [comment]
README.TXT states:
"Unlisted versions are not supported. Upgrade/downgrade accordingly. "

Thus I am assuming that xmllint preinstallations in Linux, Mac will be compatible.?

**Comment by greatislander** [comment]
Not supported does not necessarily mean that it won't function. I run Pressbooks without issue on my Mac and I am not sure which version is installed—your mileage may vary. It's likely that whichever version is installed will work just fine for you.
