### ISSUE TITLE
ePUB Option 'Compress Images' causes PNG files backgrounds to turn black

### ISSUE THREAD

**Issue by pb-amy** [pressbooks/pressbooks#2127]
### Description

This bug was identified in this ticket: https://pressbooks.zendesk.com/agent/tickets/4774

There is a setting in **Theme Options** > **ePUB Options** called "Compress Images". When this is turned on, any PNG files in the book will have a black background in EPUB exports.
![image](https://user-images.githubusercontent.com/61845107/113168165-69618f00-9212-11eb-8fa2-5809ef43774c.png)

When this setting is turned off, it will present normally, with a white background.

The original was cloned onto Integrations for the team to test on: https://integrations.pressbooks.network/pngtest/ -- a chapter where an example of this exists is: https://integrations.pressbooks.network/pngtest/chapter/public-key-cryptography/

### Steps to Reproduce

1. Observe an ePUB containing a PNG file
2. Go onto **Appearance** > **Theme Options** > **ePUB Options** and turn **Compress Images** on
3. Export another ePUB and observe

**Expected behavior:** PNGs should always have a white background

**Actual behavior:** Turning on the Compress Images option turns the backgrounds of PNGs black.

**Comment by arzola** [comment]
We need to add an `imagecolorallocate` call because by default `imagecreatetruecolor` create images with black backgrounds

```php
$dst = imagecreatetruecolor( $new_w, $new_h );
imagecolorallocate( $dst, 255, 255, 255 );
```

**Comment by pb-amy** [comment]
Some notes made by the client to add to the details of the bug:

1. Not all PNG files export with black backgrounds. Some export fine; I do not know what the variable is that causes some to export with black backgrounds.
2. When a PNG exports fine, it does not export with a white background; it exports with a transparent background. This allows the eReader platform to determine the background color.
3. The ideal solution is not to have all PNGs export with white backgrounds as this will eliminate the functionality in 2. The ideal solution is for all PNGs to export successfully with transparent backgrounds.
4. A PNG exporting with a white background is a passable solution only if that PNG cannot export successfully with a transparent background, but this should not be at the expense of removing transparent backgrounds for all other PNGs.

**Comment by SteelWagstaff** [comment]
Here's the resize image code that we use: https://github.com/pressbooks/pressbooks/blob/cbad133653d439d2d26165bb0711b60b46d55695/inc/image/namespace.php#L507-L560

See this comment for a recommended method for handling PNGs with transparent backgrounds: https://www.php.net/manual/en/function.imagecreatetruecolor.php#75298

**Comment by arzola** [comment]
@SteelWagstaff I tested it on integrations and it worked perfectly I tested on https://integrations.pressbooks.network/pngtest/
