### ISSUE TITLE
epub check error meaning?

### ISSUE THREAD

**Issue by sswettenham** [pressbooks/pressbooks#213]
Pressbooks Version 2.5.4
WP Version 4.2.4
EPUB  Version 3.0.1
XML  [xmllint] - Version 20800
___
Export has validation Error Report

PressBooks\Export\Epub\Epub201
...1439833737.epub/OEBPS/table-of-contents.html(21,254): 'section-1': fragment identifier is not defined in 'OEBPS/back-matter-001-author-information.html'
___
Sample webpage back-matter-001-author-information.htm (minus personal content)
```
<p style="text-align: center;"><a href="http://url/wp-content/uploads/sites/2/2015/08/photo.png">
<img src="http://url/wp-content/uploads/sites/2/2015/08/photo.png" alt="photo" class="alignnone size-full wp-image-35" height="200" width="200" /></a></p>

<section>
<h1 style="text-align: center;">photo</h1>
</section>
<p style="text-align: center;">center
<a href="http://link">http://link</a></p>

<blockquote>luser has published widely on educating</blockquote>
&nbsp;
```
___
What does this this mean?

**Comment by sswettenham** [comment]
It appears that the text-align of < H1 > was the source of the above epub error.  Removing the text-align resulted in error-free export.

```
 style="text-align: center;"
```

**Comment by greatislander** [comment]
This was fixed with my commit related to https://github.com/pressbooks/pressbooks/issues/196, and the forthcoming Pressbooks 2.6.1 should allow you to use inline styles on `<h1>` elements without breaking multilevel TOC.
