### ISSUE TITLE
Exporting a transparent image with caption and other properties to EPUB

### ISSUE THREAD

**Issue by richard015ar** [pressbooks/pressbooks#2137]
### Description

When upload a `.png` image with transparent background (try with other kind of images to confirm other use cases), and we add a caption, desc, alt text and other properties, it is displayed as expected in the web, but when it is exported to EPUB format, a validation error message is displayed: `Warning: The export has validation errors. See logs for more details.`

https://user-images.githubusercontent.com/13248424/114772842-4a97e800-9d3c-11eb-99ad-4f26fd37a498.mp4

Error in logs:
```bash
[14-Apr-2021 18:52:19 UTC] \PressBooks\Export\Epub201\fetchAndSaveUniqueImage is_valid_image, not a valid image 
[14-Apr-2021 18:52:19 UTC] Pressbooks\Modules\Export\Epub\Epub201
Array
(
    [time] => Wed Apr 14 18:52:19 2021
    [user] => admin
    [site_url] => https://pressbooks.test/theonboarding
    [blog_id] => 2
    [theme] => McLuhan
)
```
The epub file exported does not display the chapter as expected, only displaying an empty/blank page.

Image used: 
![dev](https://user-images.githubusercontent.com/13248424/114773448-140e9d00-9d3d-11eb-9ecb-f7947717b221.png)

### Steps to Reproduce

Add a transparent .png image format on a front-matter section (or chapter, part, etc), and check the "Show in Exports" checkbox in the "Organize" section for the chapter used, and finally export the book in .epub format.

https://user-images.githubusercontent.com/13248424/114773181-b7ab7d80-9d3c-11eb-8796-24e1880ff534.mp4

**Expected behavior:**  The chapter should be exported in epub format displaying the image with the caption and other properties.

### Example
Trying to replicate this book on Integrations: https://integrations.pressbooks.network/jctestbook/wp-admin/admin.php?page=pb_export

**Actual behavior:** Blank / Empty chapter exported.

**Comment by arzola** [comment]
Are we sure it is happening only with transparent pngs? I feel that is completely unrelated, there is no relation between the caption and the png file

**Comment by richard015ar** [comment]
Os, I am not sure if it only happens with transparent PNG images. This ticket needs more research.
But I am sure it is not related with a particular local book in my environment, since it can be replicated on Integrations, I tried with 2 different books on integrations and the error persists. 
For example, try with this one: https://integrations.pressbooks.network/jctestbook/wp-admin/admin.php?page=pb_export
(added to the issue description as example now).

**Comment by richard015ar** [comment]
btw @arzola I don't think this has a relation with the transparent images, we just need to try with multiple use cases, so far it looks like more a image properties issue (caption, alt text, etc)

**Comment by SteelWagstaff** [comment]
I think the problem is with the JC Text Book, which has been broken by search/replace.
