### ISSUE TITLE
Help Buttom in Admin area is not working

### ISSUE THREAD

**Issue by colomet** [pressbooks/pressbooks#214]
![captura de pantalla 2015-08-18 a las 14 55 55](https://cloud.githubusercontent.com/assets/3929177/9330373/49b99856-45b9-11e5-8f09-06251021acbe.png)

**Comment by greatislander** [comment]
Hi @colomet, this help button should have actually been disabled entirely, as it provides WordPress-specific help which is largely not applicable to Pressbooks installs.

**Comment by colomet** [comment]
ok. i was thinking to use it with my installation, and i did not know if it was on purpose or because a bug.

 i think is a good place for a tutorial or extra information, you can delete wordpress specific information, and write pressbooks information, i will activate for me in my installation for that pourpouse.

If you do not use, why do not take off?, if there is the label, but have no funcionality, looks like something is wrong.

**Comment by greatislander** [comment]
The commit above, https://github.com/pressbooks/pressbooks/commit/6cb0e0fad5ca215cb4ce4284350ed8abb18e5b15, removes the WordPress help button and will be released in the next public release of Pressbooks.

**Comment by colomet** [comment]
ok. now it will looks better. 

but is a pity you do not use the help content in the footer for that (more easy to find) help buttom.
