### ISSUE TITLE
Feature Request: Revision Date Field in Book Info

### ISSUE THREAD

**Issue by ghost** [pressbooks/pressbooks#215]
eBook development goes beyond traditional print and forget textbooks.  Pressbooks provides dynamic updating of content.  Having internal revision date information in export would help compare PDF and ePUB versions (beyond external download date information).

In Example:
![revision date](https://cloud.githubusercontent.com/assets/360534/9359330/94f6acb4-465e-11e5-87d4-b3bad951b58e.png)

**Comment by greatislander** [comment]
@sswettenham This feature needs some clarification. Would the revision date be automatically populated during each export UNLESS the user has set a custom revision date on the Book Info page? What if a user sets a custom revision date and then forgets to update it? I think this is a valuable feature to include but it needs to be done properly. Thoughts from you, @hughmcguire?

**Comment by sswettenham** [comment]
Default setting is auto date.  Manual over-ride would still include incremental revision number (i.e., unique identifier).  Both Date and Revision number have the option check box to be included with Published Date.  Default setting is on.  Thus authors/administrators can control the feature, or leave it in automatic pilot.

Alternatively, keep the publishing date field as is with incremental revision number as a unique identifier (minimalist perspective).  Currently exports are not saved with datetime stamp in filename which may be another strategy for keeping track of versions.

**Comment by sswettenham** [comment]
Minimalist Design
Book Info >
![info](https://cloud.githubusercontent.com/assets/360534/9561954/f6fd5808-4e2a-11e5-934f-87889c1eea6f.png)

Export >
![export](https://cloud.githubusercontent.com/assets/360534/9561956/04297854-4e2b-11e5-9a09-0256e8e5c86a.png)
