### ISSUE TITLE
Changing a contributor's slug removes that contributor from all chapters

### ISSUE THREAD

**Issue by NMSalmon** [pressbooks/pressbooks#2151]
### Prerequisites
* [x] Can you reproduce the behavior you wish to address with [all other plugins deactivated](http://codex.wordpress.org/Multisite_Network_Administration#Plugins)? [probably?]
* [x] Are you running the [latest version of Pressbooks](http://github.com/pressbooks/pressbooks/releases/latest/) and the [latest version of WordPress](http://codex.wordpress.org/Upgrading_WordPress)?
* [x] Are you experiencing this issue with one of our built-in root or book themes?
* [x] Did you [perform a cursory search](https://github.com/issues?q=+is%3Aissue+repo%3Apressbooks%2Fpressbooks) to see if your bug or enhancement is already listed?

### Description
If I've misspelled a name and change that name in the contributors list, the pages in PB will all update to reflect that new spelling, which is excellent.

However, if I change a contributor's _slug_ from, say "noami" to "naomi," all the chapters that had been tagged "noami" have their contributor removed, and I have to go back through the text and re-assign each chapter to that contributor.

(I'm not certain whether I'm reporting a bug or requesting a feature here, as it makes a lot of sense that changing a contributor's slug would confuse things elsewhere.)

### Steps to Reproduce

https://user-images.githubusercontent.com/35341860/116737649-10268000-a9b7-11eb-87dd-cd0c0a34bc49.mp4

**Expected behavior:** Changing the slug will update the contributor's 'record.' The book will remember which chapters had been affiliated with the contributor's previous slug and transfer the contributorship to the new slug.

**Actual behavior:** The old contributor's name disappears from the page entirely, and the user needs to remember or look up who contributed what where in order to update the contributor list for each of the relevant pages.

#### Book Info

Book ID: 577
Book URL: https://wisc.pb.unizin.org/wacsourcebook2020/
Book Privacy: Public

#### Browser

Platform: OS X
Browser Name: Chrome
Browser Version: 90.0.4430.93
User Agent String: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.93 Safari/537.36

#### WordPress Configuration

Network URL: http://wisc.pb.unizin.org/
Network Type: Subdirectory
Version: 5.6.2
Language: en_US
WP_ENV: production
WP_DEBUG: Disabled
Memory Limit: 96M

#### Pressbooks Configuration

Version: 5.20.1
Book Theme: Jacobs
Book Theme Version: 1.2.1
Root Theme: Aldine
Root Theme Version: 1.9.1

#### Pressbooks Dependencies

Epubcheck: Installed
Kindlegen: Installed
xmllint: Installed
PrinceXML: Not Installed
Saxon-HE: Installed

#### Must-Use Plugins

Bedrock Autoloader: 1.0.0
hm-autoloader.php: n/a
telemetry.php: n/a
Unizin Allow Custom Post Types: 1.0
Unizin Allow Plugins: 1.0.0
Unizin Allow Upload Extensions: 1.0.0
Unizin Mail From: 1.0.0
UW-Madison Kaltura Enable oEmbed: 1.0

#### Network Active Plugins

Enable Media Replace: 3.5.0
H5P xAPI: 0.1.7
Hypothesis: 0.6.0
iframe: 4.5
Lord of the Files: Enhanced Upload Security: 1.2.6
LTI: 0.1
Pressbooks: 5.20.1
Pressbooks BISAC: 2.1.0
Pressbooks Network Analytics: 1.6.0
Pressbooks Plugins Config: 1.0.0
Pressbooks Stats: 1.6.3
Pressbooks Whitelabel: 1.4.0
Redis Object Cache: 2.0.18
Regenerate Thumbnails: 3.1.5
TablePress: 1.13
TablePress Extension: DataTables Buttons: 1.3
Thin CC Exporter: 0.1.1
User Activation Keys: 4.6
Wisc Content Auth LTI: 0.2.10
WP Fail2Ban Redux: 0.7.0

#### Book Active Plugins

Enable Media Replace: 3.5.0
H5P: 1.15.2
H5P xAPI: 0.1.7
Hypothesis: 0.6.0
iframe: 4.5
Lord of the Files: Enhanced Upload Security: 1.2.6
LTI: 0.1
Pressbooks: 5.20.1
Pressbooks BISAC: 2.1.0
Pressbooks Network Analytics: 1.6.0
Pressbooks Plugins Config: 1.0.0
Pressbooks Stats: 1.6.3
Pressbooks Whitelabel: 1.4.0
Redis Object Cache: 2.0.18
Regenerate Thumbnails: 3.1.5
TablePress: 1.13
TablePress Extension: DataTables Buttons: 1.3
Thin CC Exporter: 0.1.1
User Activation Keys: 4.6
Wisc Content Auth LTI: 0.2.10
WP Fail2Ban Redux: 0.7.0
WP QuickLaTeX: 3.8.6

#### Inactive Plugins

Akismet Anti-Spam: 4.1.9
Parsedown Party: 1.2.1
Redirection: 5.1.1
Wisc H5P LTI Outcomes: 0.3.9.3

#### Server Configuration

PHP Version: 7.3.13-1+ubuntu18.04.1+deb.sury.org+1
MySQL Version: 5.6.10
Webserver Info: nginx/1.17.3

#### PHP Configuration

Safe Mode: Disabled
Memory Limit: 256M
Upload Max Size: 50M
Post Max Size: 50M
Upload Max Filesize: 50M
Time Limit: 240
Max Input Vars: 5000
URL-aware fopen: On (1)
Display Errors: N/A

#### PHP Extensions

OPcache: Zend
XDebug: Disabled
cURL: Supported
cURL Version: 7.58.0
imagick: Not Installed
xsl: Installed

**Comment by SteelWagstaff** [comment]
We've removed users' ability to edit slugs in our forthcoming release of Pressbooks. Should resolve this issue. Slugs aren't ever displayed in interface, so it's ok if they have typos/misspellings.
