### ISSUE TITLE
Ensure that cover image URLs are always https (instead of http) in API

### ISSUE THREAD

**Issue by SteelWagstaff** [pressbooks/pressbooks#2154]
## Description

The URL for the cover image provided via Pressbooks API for some books use http instead of https. We should use https whereever possible.

**Expected behavior:**
Visit https://uw.pressbooks.pub/wp-json/pressbooks/v2/books?page=3 and look at URLs in `image:` field for various books. All of them should be https. 

**Actual behavior:**
Instead, several of them use http. This causes problems in the Directory and the marketing site, which reads the book cover link to display cover images on each of these sites.

## Notes
See https://github.com/pressbooks/pressbooks-book-directory-fe/issues/180 and https://github.com/pressbooks/pressbooks-book-directory-fe/issues/269 for related issues.

We'd like network URL, site URL, home address, and image values to have is_ssl checks and then store the https value if true.

See https://github.com/pressbooks/private/issues/100

**Comment by hughmcguire** [comment]
The marketing site is pulling from Directory/Staging fyi.

**Comment by SteelWagstaff** [comment]
We've determined that the 'Network URL' for uw.pressbooks.pub and ecampus.pressbooks.pub are both set to http:// instead of https://. There may be other networks where this is the case as well. We need to investigate further.

**Comment by LeighKP** [comment]
@SteelWagstaff I'm meeting with Kayla today. Is there anything more for Plank to be concerned with here, or is it on us now?

**Comment by SteelWagstaff** [comment]
Fixed on integrations and textopress
