### ISSUE TITLE
Feature Request :  Download count for each export format

### ISSUE THREAD

**Issue by ghost** [pressbooks/pressbooks#216]
Would be an interesting stat to see which format is most often downloaded.

**Comment by JackDougherty** [comment]
Thanks to a PressBooks Textbook feature added by @bdolor, I view Google Analytics stats on event downloads by type in this way:
https://github.com/JackDougherty/pressbooks-textbook/tree/modified#modified-download-tracking-code-for-newer-universal-google-analyticsjs

**Comment by sswettenham** [comment]
Interesting strategy to apply an external Google Analytics service.  However, my focus was on an internal autonomous solution, similar to WP Power Stats plugin.

**Comment by hughmcguire** [comment]
pressbooks proper doesn't currently support downloads (PB Textbook does).
