### ISSUE TITLE
encoding on outputs (PDF, EPUB, xHTML) is a messed up (probably: WP 4.3 upgrade?) 

### ISSUE THREAD

**Issue by hughmcguire** [pressbooks/pressbooks#219]
The encoding of special characters in outputs is all messed up.

For instance, text editor input of:

`Through the fall, “creation” became “nature.”`

Is getting converted into xHTML of:

`Through the fall, &acirc;&#128;&#156;creation&acirc;&#128;&#157; became &acirc;&#128;&#156;nature.&acirc;&#128;&#157;`

and coming out in PDF as: 
![2015-08-20 at 3 33 pm](https://cloud.githubusercontent.com/assets/1991100/9393541/7529db98-4750-11e5-9b92-29bb24a5aa15.png)

Ned I will send you a specific instance of this via Slack.

**Comment by hughmcguire** [comment]
note, importantly ... that the WEB output is fine.

**Comment by hughmcguire** [comment]
... so maybe this is something else?

**Comment by hughmcguire** [comment]
for what it's worth ... local install was working fine on prev WP version + running `dev 4ba7acc` ...

pulled latest updates  & was forced to upgrade to WP 4.3 ... and have replicated the problem with the text above.

**Comment by hughmcguire** [comment]
OK, it's not WP 4.3 upgrade I don't think? I tested upgrading to WP 4.3 on an old dev branch, and exporting the offending text -- everything came out encoded as expected.

**Comment by greatislander** [comment]
I've fixed it, I believe. Please try on Textopress.

**Comment by hughmcguire** [comment]
ok all looks good on my end, thanks ned.
