### ISSUE TITLE
Remove MOBI exports from Pressbooks

### ISSUE THREAD

**Issue by SteelWagstaff** [pressbooks/pressbooks#2193]
TODO:
- [x] Remove MOBI export option from export menu, all references to MOBI export routines and tests (including MOBI hacks from EPUB: https://github.com/pressbooks/pressbooks/issues/1859), and references to KindleGen. 

    - https://github.com/pressbooks/pressbooks/pull/2260

- [ ] Remove KindleGen dependencies from all active infra repos. 

    - See https://github.com/pressbooks/textopress-infrastructure/pull/22 
    - https://github.com/pressbooks/trellis/pull/35 
    - https://github.com/pressbooks/ca-central-1-infrastructure/pull/126 
    - https://github.com/pressbooks/us-east-1-infrastructure/pull/3 
    - https://github.com/pressbooks/pressbooks-infrastructure/pull/12 
    - https://github.com/pressbooks/bibliolabs-infrastructure/pull/9 
    - https://github.com/pressbooks/ecampus-infrastructure/pull/6 
    - https://github.com/pressbooks/client-infrastructure/pull/17
    - https://github.com/pressbooks/unizin-infrastructure/pull/25 
    - https://github.com/pressbooks/unizin-b-infrastructure/pull/4 
    - https://github.com/pressbooks/sample-infrastructure/pull/1 
    - https://github.com/pressbooks/rebus-infrastructure/pull/2 
    - https://github.com/pressbooks/audit-infrastructure/pull/1

- [ ] Update documentation as needed

Amazon has retired the KindleGen tool that Pressbooks has historically used to generate MOBI exports. See [note](https://www.amazon.com/gp/feature.html?ie=UTF8&docId=1000765211): 
> KindleGen is no longer available for download. Please use Kindle Previewer to convert, preview, and validate your eBooks. Kindle Previewer provides the same functionality of KindleGen. ... We recommend using EPUB format for publishing new reflowable titles and updating previously published titles. MOBI should only be used when testing on older devices that do not support Enhanced Typesetting.

From [Amazon's KDP recommendations for publishers](https://kdp.amazon.com/en_US/help/topic/G79CTKR8BX79E96L):
> Note: We recommend submitting EPUB files for publishing reflowable content. MOBI is not recommended for reflowable content. Kindle Previewer is the best way to validate your EPUB content before publishing. 

For conversion houses, they note: 
> The preferred outputs from conversion houses to be processed by Amazon are: Books in EPUB format & Metadata in ONIX format (XML)
> Use Kindle Previewer [to] validate EPUB file and run checks for common errors. Any errors or warnings will prevent the titles from becoming available. These errors must be fixed in the EPUB file before the title is published in the Kindle store. Titles in EPUB format must abide by these publishing guidelines.

Amazon's KDP recommends the following file formats: 
* Microsoft Word (DOC/DOCX)
* Kindle Create (KPF)
* EPUB

For EPUB files they write: 
> We support books in EPUB format that meet the specifications outlined in the [Kindle Publishing Guidelines](https://kdp.amazon.com/en_US/help/topic/GU72M65VRFPH43L6).

They indicate that they support HTML, MOBI, RTF, TXT, and PDF. For MOBI files they note:
> We support books in MOBI format that meet the specifications outlined in the Kindle Publishing Guidelines. If your MOBI file contains reflowable content (i.e. text-heavy books), we recommend you upload an EPUB file instead.

In place of KindleGen, Amazon recommends using their Kindle Previewer tool (a free desktop application for Windows/Mac OS users): https://www.amazon.com/gp/feature.html?ie=UTF8&docId=1000765261, which apparently bundles a version of KindleGen. Kindle Previewer includes a command-line option which can help users validate multiple books for publishing errors and will provide a summary of validation status. Users can manually run Kindle Previewer from a command-line interface (on their Windows or Mac OS X computers) and can integrate it as part of an automated workflow. For details, see section [3 of their user guide](https://kindlepreviewer3.s3.amazonaws.com/UserGuide320_EN.pdf#page=20)

**Options:**
1. Continue generating MOBI files for users on demand using the EPUB export and KindleGen (either by continuing to use the last version Amazon made available for direct download or figuring out some way to harness Kindle Previewer or similar tool to do this)
2. Discontinue MOBI exports in Pressbooks. Instead, focus on improving our EPUB export routine (make EPUB 3 the default, and investigate what changes, if any, could be made to ensure that EPUB files produced by Pressbooks conform with [Kindle Publishing Guidelines](https://kdp.amazon.com/en_US/help/topic/GU72M65VRFPH43L6)). We should also provide instructions for users to create their own MOBI files from Pressbooks EPUBs using tools like Calibre or Kindle Previewer.

I prefer option 2.

**Comment by SteelWagstaff** [comment]
We will be removing support for MOBI exports in a future release of Pressbooks. More to come in a future announcement.

**Comment by SteelWagstaff** [comment]
See official announcement of forthcoming change: https://pressbooks.org/blog/2021/07/14/planned-deprecation-notice-mobi-exports/

**Comment by gavinpressbooks** [comment]
Testing on Integrations with https://integrations.pressbooks.network/opentextbookswithstudents/

Works as expected. The following tests were performed:
- [x] MOBI is no longer an export option available
- [x] Existing MOBI files can still be downloaded from the book homepage
- [x] EPUB 2.01, PressbooksXML and Common Cartridge with Weblinks are now listed under supported formats
- [x] No validation errors were present
