### ISSUE TITLE
Change the default book cover image 

### ISSUE THREAD

**Issue by LeighKP** [pressbooks/pressbooks#2195]
### Feature Description

Please switch the [default book cover](https://github.com/pressbooks/pressbooks/blob/dev/assets/dist/images/default-book-cover.jpg) (the red type writer and the word Pressbooks) to an updated version that does not feature a type writer. This is a bandaid solution until we can do something more dynamic (e.g. a cover generator, Cesar once made one for Rebus that was super cool). 

### Feature Use Case

Now that the search results display sorted by most recently updated, a lot more red type writers are showing up. The red type writers conflict with our innovative brand and make the search results look less impressive than they are.

### Other Notes

One option for the cover would be to have the same graphic designer [Leah Concepcion-Vanderbyl](https://www.leahcv.com/) who did the website and some of the assets do a standard book cover. I would be happy to facilitate the conversation.

**Comment by SteelWagstaff** [comment]
@LeighKP & @hughmcguire Leah has agreed to make three potential designs for the cover and make adjustments based on our feedback. Work should be done by June 16.

**Comment by SteelWagstaff** [comment]
AI file from Leah can be found at https://drive.google.com/file/d/11jyFqP3G2bHMqbXlrr0CQq_-RI_B6toB/view?usp=sharing
