### ISSUE TITLE
Quotation marks in short titles disrupt running content in the PDF format 

### ISSUE THREAD

**Issue by mcgratay** [pressbooks/pressbooks#2201]
### Description

The Chapter Metadata panel below the post editor contains a textbox that allows users to fill in a Chapter Short Title. The Chapter Short Title should appear in the PDF running header and in webbook navigation. 

When a user includes quotation marks in their chapter short title, then neither the quotation marks nor any of the content that is within or after them will appear in the running content. 

One workaround is to copy curly quotes from elsewhere on the web and use them in place of the default straight quotes that get typed when using your keyboard per normal in this textbox. Since the curly quotes worked, it's likely that straight quotes are getting interpreted as part of an HTML tag and getting hidden as a result. 

The follow test book has an example with a) a normal chapter short title; b) a chapter short title with one word surrounded in quote marks; c) a chapter short title entirely wrapped in quotation marks: https://shorttitlequotationmarks.textopress.com/ 

Other Notes: 
- Seems to affect all tested themes
- Webbook navigation cues were fine, so only impacts the PDF format 

![Screen Shot 2019-11-05 at 2 32 58 PM](https://user-images.githubusercontent.com/39064028/68239540-2c6f7980-ffd9-11e9-9b48-4be21371dc35.png)

![Screen Shot 2019-11-05 at 2 33 51 PM](https://user-images.githubusercontent.com/39064028/68239624-4b6e0b80-ffd9-11e9-98e5-d7bedb694b84.png)

### Steps to Reproduce

1. In your test chapter, scroll down to the Chapter Short Title setting in Chapter Metadata and enter some text that includes at least one word wrapped in quotation marks
2. Add some dummy text to the editor so that the chapter spans a couple of pages in PDF format, then save
3. Go to **Appearance > Theme Options > PDF Options** and scroll down to the Running Heads & Feet Section
4. Make sure the **Chapter Left** and **Chapter Right** sections are set to Chapter Title, then save
5. Export to PDF and check 

**Expected behavior:** Text added to the Chapter Short Title textbox appears in the running content of a PDF in place of the chapter's title 

**Actual behavior:** Chapter Short Titles with quotation marks do not display correctly in PDF format

**Comment by SteelWagstaff** [comment]
Related to https://github.com/pressbooks/pressbooks/issues/2158
