### ISSUE TITLE
LaTeX equations always centred in PDF exports

### ISSUE THREAD

**Issue by josieg** [pressbooks/pressbooks#2202]
### Description
Equations in Pressbooks that are created in LaTeX and rendered in MathJax are always centred in the PDF. That means it's impossible to add Latex equations in-line or just have them display left aligned in the PDF. I have tested this with both Clarke and McLuhan theme. This affects all equations wrapped in [latex] short codes.
### Steps to Reproduce

1. Create a LaTeX equation in Pressbooks with MathJax enabled. (For example, `[latex]\frac{1}{2}[/latex]` or `[latex]1+1=2[/latex]`
2. Export a PDF file.
3. Download and view the equation in the PDF.

**Expected behavior:**
I expect the formatting of math created with LaTeX and rendered with MathJax to be consistent across formats. For example, this is the display in the webbook, which is what I expect:
![webook latex](https://user-images.githubusercontent.com/23706762/78808212-f7959300-7979-11ea-9d84-95ade59c3b5f.jpg)

**Actual behavior:**
Right now the webbooks displays as expected, but PDF always centers the equation:
![PDF latex](https://user-images.githubusercontent.com/23706762/78808263-0714dc00-797a-11ea-8aba-90ae81db147b.jpg)

**Comment by SteelWagstaff** [comment]
Sample book with error occurring at https://integrations.pressbooks.network/mathtest/format/xhtml?debug=prince

**Comment by LMajor76** [comment]
hi there!  I'm guessing you are still working on this issue SteelWagstaff?  We are using MathJax in our book & have noticed that most of the book is blank right now when we try to "View Chapter"... is the MathJax issue resolved & might there be anything that we need to change since the update to be sure LaTex compiles?

**Comment by SteelWagstaff** [comment]
@LMajor76 we haven't made any recent changes to our MathJax microservice, so I'm not sure what's happening for your blank chapters. If you want to share more details in https://pressbooks.community (along with URL of sample chapter, screenshots, and info from your diagnostics page, etc), we might be able to help you troubleshoot there?

**Comment by LMajor76** [comment]
Okay - thanks, Steel!


A few quick related questions:

1) the inline latex call seems to work now with PDF documents.  Is this correct? We found it worked!

And just call it using [latex] [/latex] within text on a line

2) for $'s within latex, do we need a \$ within [latex] and [\latex] (specific to MathJax in Pressbooks)

3) for %'s in LaTex calls (ie: within [latex] and [\latex] calls), do we need \%?


thanks so much!

Leslie

________________________________

**Comment by josieg** [comment]
Hi @LMajor76 ! I am going to pass your LaTeX questions on to my colleague to answer. They are a bit outside of Steel's responsibility :) 

From my testing last week I do think in-line equations are displaying properly in the PDF when using MathJax. However, this week exports in our Pressbooks instances are not working, so I do still need to confirm.

**Comment by SteelWagstaff** [comment]
Appears to be resolved in latest versions of Pressbooks. Closing for now.
