### ISSUE TITLE
Store download event data in Pressbooks database when files are downloaded from webbook homepage

### ISSUE THREAD

**Issue by SteelWagstaff** [pressbooks/pressbooks#2203]
As a book author, I want to know how many times each of my book exports have been downloaded (by file type) from my book homepage without having to install Google Analytics or other tracking software so that I can understand how readers are interacting with my book and which file exports I should focus on improving.

As a network manager, I want to know which books have their export files downloaded most frequently, and to know which file types are most popular so that I can advise book admins on which file types users tend to download from our network.

As a product owner, I want to know which file types are most frequently downloaded across all networks so we can prioritize those export routines. I also want to know which files types are downloaded least often, so we can consider retiring or replacing them with more useful export options.

We currently have an event tracker built into Pressbooks-book which relays download information to Google Analytics: https://github.com/pressbooks/pressbooks-book/blob/dca488ac2ed41e1f9ef3eee48d280b95c85daeeb/partials/content-cover-book-header.php#L64-L74

I'd like us to store download events in the Pressbooks database so that it can be aggregated and displayed to book admins, network managers, and Pressbooks product team (for our hosted networks). Information we want to store in our database is the date of the action, the file type downloaded, and whether or not the person who downloaded the file was logged into Pressbooks at the time of download. We don't want to collect or store IP address or other identifying information about the user. Ultimately, our goal will be to count and display the number of file downloads by type over a given duration to book authors, network managers, and Pressbooks product team (for our hosted networks only).

Possible information to store in a new database table:
- is_logged_in
- date
- file type
- blog_id

Displaying this information is NOT in scope for this task. Collecting it in the Pressbooks database IS in scope for this task.

**Comment by SteelWagstaff** [comment]
@ho-man-chan We've added a new feature which should add a new database table called 'wp_pressbooks_tracking' when book download events are performed from the webbook homepage (see https://github.com/pressbooks/pressbooks/pull/2204). Will you check in Integrations database to see if this table exists for Making Open Textbooks with Students (book id #3), and that it contains events that look like the ones in Ricardo's PR comment?

**Comment by ho-man-chan** [comment]
@SteelWagstaff 
Looks Good!
Heres the result:
![image](https://user-images.githubusercontent.com/21694293/121703839-34d74280-caa1-11eb-9ab4-75f76fe63d6b.png)
