### ISSUE TITLE
EPUB EXPORT VALIDATION ERRORS with PB v.2.6.2

### ISSUE THREAD

**Issue by sswettenham** [pressbooks/pressbooks#221]
Pressbooks Version 2.6.2 
PressBooks Textbook Version 1.2.14
WP 4.3

Getting lots of errors from new update.  Had no errors in PB v.2.6
i.e.
```
Text - <img src="http://url/wp-content/uploads/sites/2/2015/08/TITLE_515×372.png" alt="CH1 - TITLE" class="size-full wp-image-28" height="372" width="515" />
```

ERRORS
ERROR: /var/www/html/wp-content/uploads/sites/2/exports/TITLE-1440131134.epub/OEBPS/table-of-contents.html(14,973): 'section-4': fragment identifier is not defined in 'OEBPS/title.html'
ERROR: /var/www/html/wp-content/uploads/sites/2/exports/TITLE-1440131134.epub/OEBPS/TITLE.html(69,135): The element type "img" must be terminated by the matching end-tag "</img>".

**Comment by sswettenham** [comment]
Also still getting error for h1 tag  center align, even though it was stated to be fixed in 2.6.1
Ref:
Fixed issues with subsection parsing where
< h1 > tags had inline styles or were wrapped in other block elements.

**Comment by greatislander** [comment]
Please test with 2.6.3 (should be available on WordPress.org momentarily).

**Comment by greatislander** [comment]
In my testing all of the EPUB errors introduced in 2.6.1 appear to have been resolved. Please advise if this is not the case.

**Comment by sswettenham** [comment]
Confirmed - no further errors from PB v.2.6.3  - including h1 align.
