### ISSUE TITLE
Pressbooks- chapter 1 isn't restarting page numbers

### ISSUE THREAD

**Issue by beckej13820** [pressbooks/pressbooks#2217]
### Prerequisites

* [x] Can you reproduce the behavior you wish to address with [all other plugins deactivated](http://codex.wordpress.org/Multisite_Network_Administration#Plugins)?
* [x] Are you running the [latest version of Pressbooks](http://github.com/pressbooks/pressbooks/releases/latest/) and the [latest version of WordPress](http://codex.wordpress.org/Upgrading_WordPress)?
* [x] Are you experiencing this issue with one of our built-in root or book themes?
* [x] Did you [perform a cursory search](https://github.com/issues?q=+is%3Aissue+repo%3Apressbooks%2Fpressbooks) to see if your bug or enhancement is already listed?

### Description

Book Exports using McLuhan and Jacobs are not restarting at roman numeral 1 for the first part or first chapter. This is showing up in multipart books with visible parts:

Some samples from the Table of Contents:
![Screen Shot 2021-06-15 at 2 07 53 PM](https://user-images.githubusercontent.com/29982981/122102198-2f506400-cde3-11eb-8248-d5ab2d56e5c5.png)

Jacobs:
![Screen Shot 2021-06-15 at 2 09 11 PM](https://user-images.githubusercontent.com/29982981/122102322-4e4ef600-cde3-11eb-969c-51ca37e88ab0.png)

McLuhan:
![Screen Shot 2021-06-15 at 2 11 24 PM](https://user-images.githubusercontent.com/29982981/122102583-93732800-cde3-11eb-8803-0bca08d8c79a.png)

Donham:
![Screen Shot 2021-06-15 at 2 12 03 PM](https://user-images.githubusercontent.com/29982981/122102699-b43b7d80-cde3-11eb-8878-d5ac86420958.png)

### Steps to Reproduce

1. Export a book with multiple parts as a Print PDF
2. Check to make sure numbering restarts at the first part or the first chapter

**Expected behavior:** 

I would expect for front matter to be numbered, and at the first part or first chapter following the front matter to restart numbering with page 1.

**Actual behavior:** 

Numbering is happening consecutively across multiple themes. Even themes that are designed with roman numeral front matter and arabic numeral body are going consecutively vii, viii, 9, 10, 11.

Looking at the XHTML of the book that is not working, the part does not have the class "introduction." Adding the class introduction manually and then running through Prince offline shows expected behavior.

![Screen Shot 2021-06-15 at 2 16 39 PM](https://user-images.githubusercontent.com/29982981/122103234-62472780-cde4-11eb-9add-f237be9eb4e7.png)

(I'm trying to say, I think something is going on with the classes to the first part. Is Pressbooks supposed to add a class to the first part or the first chapter that lets the CSS know to restart numbering?)

#### Book Info

Book ID: 23
Book URL: https://africanamericanlit.pressbooks.sunycreate.cloud/
Book Privacy: Public

#### Browser

Platform: OS X
Browser Name: Safari
Browser Version: 14.1
User Agent String: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.1 Safari/605.1.15

#### WordPress Configuration

Network URL: https://pressbooks.sunycreate.cloud/
Network Type: Subdomain
Version: 5.7.2
Language: en_US
WP_ENV: Not set
WP_DEBUG: Enabled
Memory Limit: 64M

#### Pressbooks Configuration

Version: 5.20.1
Book Theme: Donham
Book Theme Version: 1.7.0
Root Theme: Aldine
Root Theme Version: 1.9.1

#### Pressbooks Dependencies

Epubcheck: Installed
Kindlegen: Installed
xmllint: Installed
PrinceXML: Installed
Saxon-HE: Installed

#### Must-Use Plugins

hm-autoloader.php: n/a

#### Network Active Plugins

Limit Login Attempts Reloaded: 2.22.1
Pressbooks: 5.20.1
Pressbooks Stats: 1.6.3

#### Book Active Plugins

Candela Citation: 0.2.3
Limit Login Attempts Reloaded: 2.22.1
Pressbooks: 5.20.1
Pressbooks Shortcode Handler: 0.1
Pressbooks Stats: 1.6.3

#### Inactive Plugins

Git Updater: 10.0.1
H5P: 1.15.2
Hypothesis: 0.6.0
TablePress: 1.13
WordPress Importer: 0.7
WP QuickLaTeX: 3.8.6

#### Server Configuration

PHP Version: 7.3.20
MySQL Version: 5.7.30
Webserver Info: Apache

#### PHP Configuration

Safe Mode: Disabled
Memory Limit: 1024M
Upload Max Size: 128M
Post Max Size: 256M
Upload Max Filesize: 128M
Time Limit: 30
Max Input Vars: 1000
URL-aware fopen: N/A
Display Errors: N/A

#### PHP Extensions

OPcache: Zend
XDebug: Disabled
cURL: Supported
cURL Version: 7.71.0
imagick: Not Installed
xsl: Installed

**Comment by beckej13820** [comment]
Steps to reproduce may need to be updated...

I've replicated this on multiple books on my network, but it only seems to effect books with multiple visible parts. A book with only a "main body" part renumbered correctly on my server.

![Screen Shot 2021-06-23 at 2 19 13 PM](https://user-images.githubusercontent.com/29982981/123148415-348a6000-d42e-11eb-8f60-af21149b2a01.png)

**Comment by ajeannette** [comment]
Hello, All! 

My campus is a Pressbooks.education customer also having this issue:

![Screen Shot 2021-07-30 at 10 56 25 AM](https://user-images.githubusercontent.com/36711174/127672041-cb9b86b1-3916-45cc-8cb7-74cb973ac817.png)

**Comment by beckej13820** [comment]
What is the expected behavior here?

Should the first "chapter" of front matter start page numbering in roman numberals? From Amanda's example above, you can see that it must be starting from the 1st page of the PDF.

Are there rules for which front matter sections should be numbered and shouldn't be numbered? Are there behaviors that we are describing that aren't bugs, but are actually carefully decided rules that we need to read documentation for?

Amanda and I have reproduced on an open-source server running the latest version of Pressbooks and on a Pressbooks managed and hosted site. Do you need anything else from us?

**Comment by SteelWagstaff** [comment]
Hi @beckej13820 and @ajeannette -- sorry this hasn't been responded to sooner. Our QA specialist recently left (we're hiring a replacement) and we didn't get this one triaged like we normally would have. I'm heading out on vacation next week, unfortunately, but will add this to the list for our next team bug scrub.

**Comment by SteelWagstaff** [comment]
Chicago Manual of Style recommends:
> Printed books are paginated consecutively, and all pages except endpapers are counted in the pagination, whether or not the numbers appear. The page number, or folio, is most commonly found at the top of the page, flush left verso, flush right recto. The folio may also be printed at the bottom of the page, and in that location it is called a drop folio. Drop folios usually appear either centered on each page or flush left verso and flush right recto. ... Reflowable electronic formats generally lack fixed page numbers, though many formats include location information to help orient readers in the text
> The front matter of a book is paginated with lowercase roman numerals. This traditional practice prevents renumbering the remainder of a book when, for example, a dedication page or additional acknowledgments are added at the last moment. By convention, no folio appears on blank pages or on “display” pages (i.e., such stand-alone pages as those for the half title, title, copyright, dedication, and epigraph), and a drop folio (or no folio) is used on the opening page of each succeeding section of the front matter (e.g., table of contents, foreword, preface).
> The text, or the central part of a book, begins with arabic page 1. If the text is introduced by a second half title or opens with a part title, the half title or part title counts as page 1, its verso counts as page 2, and the first arabic number to appear is the drop folio 3 on the first page of text (see 1.46, 1.49). (Some publishers ignore the second half title in paginating their books, counting the first page of text as p. 1.) Page numbers generally do not appear on part titles, but if text appears on a part-title page (see 1.48), a drop folio may be used. Arabic numbering continues for the back matter. As in the front matter, the opening page of each chapter in the text and each section in the back matter carries either a drop folio or no page number. On pages containing only illustrations or tables, page numbers are sometimes omitted, except in the case of a long sequence of figures or tables. (When page numbers are retained, they are usually presented along with the running heads.) Page numbers are also omitted in the case of a blank page.

**Comment by SteelWagstaff** [comment]
@beckej13820 and @ajeannette I'm going to close this issue -- if there's anything you think I missed, please add a comment and we can reconsider opening it or filing a new one to address your concerns.
