### ISSUE TITLE
Book chapter not rendering

### ISSUE THREAD

**Issue by pb-amy** [pressbooks/pressbooks#2218]
### Prerequisites

* [x] Can you reproduce the behavior you wish to address with [all other plugins deactivated](http://codex.wordpress.org/Multisite_Network_Administration#Plugins)?
* [x] Are you running the [latest version of Pressbooks](http://github.com/pressbooks/pressbooks/releases/latest/) and the [latest version of WordPress](http://codex.wordpress.org/Upgrading_WordPress)?
* [x] Are you experiencing this issue with one of our built-in root or book themes?
* [x] Did you [perform a cursory search](https://github.com/issues?q=+is%3Aissue+repo%3Apressbooks%2Fpressbooks) to see if your bug or enhancement is already listed?

### Description

There is a chapter on the Oregon State network that does not show up in the webbook: https://open.oregonstate.education/open-judicial-politics/chapter/institutional-determinants-of-amici-filings-across-state-supreme-courts/

It's worth noting that this was not an issue in the past (the chapter rendered fine at the time of publication), but at some point, it stopped loading. This issue is likely tied to the image caption issue that was fixed in the last deploy. There are a series of images in the chapter (40-50) that are next to each other without captions, and upon investigation, it looks like these are what is causing the page to break. (Once you remove some of the images, the page renders)

### Steps to Reproduce

1. 
2. 
3. 

**Expected behavior:** Page should render regardless of the content within it.
**Actual behavior:** Page does not render with the series of images without captions

**Comment by pb-amy** [comment]
From this client ticket: https://pressbooks.zendesk.com/agent/tickets/5837

**Comment by SteelWagstaff** [comment]
Fixed by #2113
