### ISSUE TITLE
Upgrade Docraptor / PrinceXML

### ISSUE THREAD

**Issue by fdalcin** [pressbooks/pressbooks#2228]
### Description 

We currently lock [docraptor wrapper](https://github.com/DocRaptor/docraptor-php) at version 1.3. We should try to upgrade it to the 2.0 (released in August 2020). It has a breaking change, but seems to be a simple change to our code base.

[Version 1.3](https://github.com/DocRaptor/docraptor-php/tree/7739bbf5be46aa5a0d8b636ce8dc9300500fbbab#usage)
![image](https://user-images.githubusercontent.com/1761690/123277150-3a3e7f00-d4dc-11eb-9481-fab8811dde0b.png)

[Version 2.0](https://github.com/DocRaptor/docraptor-php#basic-usage)
![image](https://user-images.githubusercontent.com/1761690/123277433-7bcf2a00-d4dc-11eb-8ce7-dc95958bafe8.png)

Docraptor provides different pipelines to address which [PrinceXML](https://www.princexml.com/doc/) version to use. We currently use pipeline 7 (PrinceXML v12.5). There are 2 newer versions of prince available, [13](https://www.princexml.com/releases/13) and [14](https://www.princexml.com/releases/14) that bring new features and support improvements.

### Upgrade steps

* [x] Upgrade our docraptor wrapper version to v2.0 and ensure PDF generation works as expected
* [x] Change our docraptor pipeline to upgrade PrinceXML version and ensure PDF generation works as expected
* [ ] Work on improments to take advantage of PrinceXML new features

In scope for this task: complete task 1, produce testing notes for task 2. Task 3 can be a research report for a future sprint

**Comment by fdalcin** [comment]
While upgrading [docraptor/docraptor](https://github.com/DocRaptor/docraptor-php) to v2 I faced an issue because it requires [guzzlehttp/guzzle](https://github.com/guzzle/guzzle) at version ^6.2, while we have other dependencies that require guzzlehttp/guzzle but with a slightly higher version (^7.0). This prevents composer from installing it since composer autoload won't know which version to load.

Composer issue while upgrading docraptor.
![image.png](https://images.zenhubusercontent.com/60a7e6a889e8274a68d8c65b/cca1d551-bc5c-4d28-9d97-e10ab08d5da8)

I've managed to upgrade docraptor/docraptor by locking guzzlehttp/guzzle to version ^6.2 for all dependencies, since all of them support the lower version (temporary solution, [see](https://github.com/pressbooks/pressbooks/tree/pb-2228-docraptor-upgrade)). 
![image.png](https://images.zenhubusercontent.com/60a7e6a889e8274a68d8c65b/2056dd6d-5475-4473-9588-460d86e9b8f9)

There is a PR opened that adds support for guzzlehttp/guzzle 7 ([see here](https://github.com/DocRaptor/docraptor-php/pull/24)). This PR is opened for a while now and I don't know when it will be available. One option would be to fork the project while we wait for that PR to be accepted.

**Comment by fdalcin** [comment]
Locking guzzlehttp/guzzle version doesn't work, since it fails to generate PDFs.
We are trying to get this updated upstream so we can move forward.

**Comment by SteelWagstaff** [comment]
We cannot upgrade DocRaptor until it works with Guzzle 7. We could use the fork described in https://github.com/DocRaptor/docraptor-php/issues/23#issuecomment-769655002 and https://github.com/DocRaptor/docraptor-php/pull/24, but would prefer to wait until DocRaptor updates the dependency. Once that happens, we can merge https://github.com/pressbooks/pressbooks/pull/2308 and move forward with this
