### ISSUE TITLE
PDF Options  >> widows and orphans settings don't work (and values should be changed)  

### ISSUE THREAD

**Issue by hughmcguire** [pressbooks/pressbooks#223]
In APPEARANCE >> THEME OPTIONS >> PDF OPTIONS 

There are settings for **widows and orphans**, which the user can change. 

Currently:
a) these are the "wrong" default values (currently set at `widows = 3 / orphans = 3`)
b) these wrong values don't seem to do anything!
c) when users changes these values it does not have an effect on book outputs
 
The default values should be changed, as follows: 

```
widows = 2 
orphans = 1
```

And the output to the PDF CSS should be: 

`p {widows: (value); orphans: (value);}`

Note: need to test to make sure that on old books, we don't suddenly override working widow/orphan settings :/

**Comment by greatislander** [comment]
Can you test on an old book and let me know?

**Comment by hughmcguire** [comment]
do you mean: you have made a change and you would like me to test? 
or do you mean: you would like me to test on an old book before doing anything here?

**Comment by greatislander** [comment]
The latter.

**Comment by greatislander** [comment]
If it's not working on old books too than I can't break anything… right? ;)

**Comment by hughmcguire** [comment]
it is already a known issue that:
a) the current default are not getting applied
b) changing the values has no impact on outputs.

**Comment by greatislander** [comment]
Okay. I guess I was confused by this:

> Note: need to test to make sure that on old books, we don't suddenly override working widow/orphan settings :/

**Comment by hughmcguire** [comment]
This means: 
a) If we implement this feature correctly
b) and if old books have (unupdated) widow/orphan default values of 3

... then ... will new exports now implement `p {widow: 3; orphan: 3;}`

?

**Comment by greatislander** [comment]
They will have whatever was saved before, so 3 / 3.

**Comment by greatislander** [comment]
The CSS being exported is as follows:

```
@page, p { widows: 2; }
@page, p { orphans: 1; }
```

Is the `@page` causing the error?

**Comment by hughmcguire** [comment]
right ... and now that the feature actually "works" ... that setting will override the _correct_  styling that is in the stylesheets ... ?

**Comment by greatislander** [comment]
I don't think there is any value for widows and orphans in the stylesheet except for what is generated from the options.

**Comment by hughmcguire** [comment]
all themes have pdf stylesheets...with w/o setting.

**Comment by hughmcguire** [comment]
it's possible that the open source ones don't ...

**Comment by hughmcguire** [comment]
no, the open source ones do -- but we should remove the settings from `@page` ...I don;t think that's the right place to apply them (<< I can fiddle with styling changes, but I'd like to make sure that the PDF OPTIONS actually work, which I don't believe they do).

**Comment by hughmcguire** [comment]
ok so ... testing a bit. looks like removing the `@page` does the trick, so if the output CSS is no longer: 
```
@page, p { widows: (value); }
@page, p { orphans: (value); }
```

but instead: 
```
p { widows: (value); }
p { orphans: (value); }
```

then the settings work ... (update: looks like we need an `!important` in there ... )

however, this now poses the conundrum ... 

a) many books will have the default PDF Option values of: `{widows: 3; orphans: 3}` ... 
b) but since this feature isn't currently working , then those `3s` are ignored, and instead the values in the Themes (usually: `p {widows: 2; orphans: 1;}`) are being used
c) i think we want the theme defaults to be used on old books (otherwise unexpected things happen to users exporting older books
d) but new users to be able to use this feature. 

let's talk by skype :/

**Comment by greatislander** [comment]
Hi Hugh, please test book exports on Textopress (updated with https://github.com/pressbooks/pressbooks/commit/a55904d09483fa411a8f75c93cabea9fa174a495) and see if the new default widow and orphan settings are being exported properly.

**Comment by greatislander** [comment]
Updates, @hughmcguire?

**Comment by hughmcguire** [comment]
@greatislander 

OK i think this looks right -- there was an `!important` override coming in from pdf-house-styles which I have removed (on dev), see:  
https://github.com/pressbooks/private-themes/commit/4c04328d979b1d9a9aec97806c295a39fbd317d7

if you are ok with this ... could you also merge that into prod & push all this & close.

**Comment by greatislander** [comment]
Done.
