### ISSUE TITLE
Broken Links in Admin Screen- Contributors Page

### ISSUE THREAD

**Issue by beckej13820** [pressbooks/pressbooks#2231]
### Description

In the Admin panel, on the contributor page, there is a table that includes Name, Description, Slug, and the Count of posts.

The count of posts is a link to /wp-admin/edit.php?contributor=slug

However that page is blank and doesn't display any posts, even if the contributor has posts connected to them.

### Steps to Reproduce

1. Create a book, a contributor and assign chapters to the contribtor
2. Go to /wp-admin/edit-tags.php?taxonomy=contributor
3. Confirm that the counter works, but the links lead to an unhelpful page

**Expected behavior:** 

I'd expect the link to lead to a page with all the contributor's posts OR for the link to be removed.

**Actual behavior:** 

There is a link to a page with no useful information or purpose.

TO DO:
- [x] remove the description, slug, and count fields 
- [x] add profile picture, biographical info, and institution fields to this view so that they can be seen at a glance

**Comment by gavinpressbooks** [comment]
This issue was reproduced following the steps in the original bug report without issue. Anywhere a contributor is added, whether in the Book Info or Chapter Info pages, the counter increases accordingly but following the linked number provides an empty list. A screen recording is attached.

https://user-images.githubusercontent.com/85123231/126491266-56a2b5dc-99ec-4f57-83c8-d1375cf335ec.mov

**Comment by SteelWagstaff** [comment]
If possible, we should overhaul the contributor menu by removing the description, slug, and count fields and adding profile picture, biographical info, and institution fields so they can be seen at a glance.

We also want to create new bulk actions for contributors (export/import). See https://github.com/pressbooks/pressbooks/issues/1824

**Comment by fdalcin** [comment]
Tested on integrations and works as expected
