### ISSUE TITLE
Trim book info information before save

### ISSUE THREAD

**Issue by SteelWagstaff** [pressbooks/pressbooks#2263]
Occasionally, book info values will be stored with extra spaces before after a value. 

This can causes when these fields need to be sorted in alphabetical order, as in the Pressbooks Directory. For example, when the title of a book has extra spaces before the title begins, the book will appear too early in alphabetical order. We should trim/sanitize these values upon save in Pressbooks 'book info'.

**Comment by SteelWagstaff** [comment]
@arzola we want to trim (or run 'sanitize_text_field) https://developer.wordpress.org/reference/functions/sanitize_text_field/) each of these values before they're saved: https://github.com/pressbooks/pressbooks/blob/dev/inc/admin/metaboxes/namespace.php#L189-L209. I can see that you wrote the PR to sanitize other text input fields on this file using sanitize_callback. Can you help with this task?

**Comment by gavinpressbooks** [comment]
Tested on Integrations with integrations.pressbooks.network/usaskphystest

Works as expected. Tested with extra spaces before and after text and HTML tags which were all removed from free text fields upon saving. The only field that was not sanitized was the keywords field, which retained superfluous characters.
