### ISSUE TITLE
Print PDF icon image missing on export page

### ISSUE THREAD

**Issue by SteelWagstaff** [pressbooks/pressbooks#2264]
### Description

The print PDF icon image is missing on the export page. 

### Steps to Reproduce

1. Produce a print PDF export.
2. Look at the file listing on the export page

**Expected behavior:** 
I expect to see an icon that says printPDF

**Actual behavior:** 
There is no icon for the print PDF export.

![Screenshot from 2021-07-19 11-06-32](https://user-images.githubusercontent.com/13485451/126206542-e55fd076-9560-4295-b2e2-4e6de22eed6f.png)

**Comment by gavinpressbooks** [comment]
Test on Integrations with the following book: https://integrations.pressbooks.network/usaskphystest

Works as expected. Red banner 'Print PDF' icon is now visible for print PDF exports.

See also: #2266
