### ISSUE TITLE
Add "Print" to "Print PDF" icon

### ISSUE THREAD

**Issue by SteelWagstaff** [pressbooks/pressbooks#2266]
When we generate PDF exports, the icons used for digital and print PDFs are visually disambiguated by color only (red & greeen). 
![PDF_export](https://user-images.githubusercontent.com/13485451/69245864-a412dc00-0b75-11ea-9ae9-f9d30b2fc692.png)

We should improve this by adding the word 'print' to the print PDF export icon.

The code for the current print PDF icon can be found here: https://github.com/pressbooks/pressbooks/blob/8da7f180f8e6187b82d6c64d49f6c8aa339c5a8c/assets/src/styles/export.scss#L135-L141. I don't know how these PNGs were originally generated (I think that was @greatislander's work?), but there are four sizes of this icon here: https://github.com/pressbooks/pressbooks/tree/master/assets/src/images

**Comment by gavinpressbooks** [comment]
Test on Integrations with the following book: https://integrations.pressbooks.network/usaskphystest

Works as expected. Red banner 'Print PDF' icon is now visible for print PDF exports.

**Comment by gavinpressbooks** [comment]
Test on Integrations with the following book: https://integrations.pressbooks.network/usaskphystest

Works as expected. Red banner 'Print PDF' icon is now visible for print PDF exports.

See also: https://github.com/pressbooks/pressbooks/issues/2266
