### ISSUE TITLE
empty tags resulting in formatting problems in PDF outputs

### ISSUE THREAD

**Issue by hughmcguire** [pressbooks/pressbooks#228]
for instance:

```
<p class="indent"><b></b>One day I began to present ... </p>

```
The `<b></b>` should be ignored ... but in PDF outputs this is resulting in huge swaths of the book being bold. 

Oh. Looking at the xHTML ... 

The source tags (in the TEXT editor) of: 
`<p class="indent"><b></b>One day I began to ...`

is coming out in xHTML as:
`<p class="indent"><b/>One day I began to ...`

So the `<b>` has disappeared, and is I suspect the cause of this problem.

(NOTE: it's not a problem in EPUB & Web) ... 

This is a new problem -- I suspect related to the fix here:
https://github.com/pressbooks/pressbooks/issues/196

**Comment by greatislander** [comment]
Appears to be fixed now. I have added code to remove empty `<b>`, `<i>`, `<em>` and `<strong>` tags [here](https://github.com/pressbooks/pressbooks/commit/6cb4f68b4fda7da8f52c1408d9468b52bdce1108)—let me know if you run into any other issues.

**Comment by greatislander** [comment]
Okay, ready for you to test on staging.

**Comment by greatislander** [comment]
Finally.
