### ISSUE TITLE
[Research] Allow users to search Directory from 'Clone a book' page

### ISSUE THREAD

**Issue by SteelWagstaff** [pressbooks/pressbooks#2285]
Cloner page currently is very spare: 
![Screenshot from 2021-07-28 15-54-34](https://user-images.githubusercontent.com/13485451/127406523-cfbb5acd-0b42-455c-8c7c-05390eb92579.png)

- [x] As a first step, we should improve the text instructions and inform users about the Directory as a place to find books of interest for cloning. See https://github.com/pressbooks/pressbooks/pull/2288

- [x] As a second step, we should research how to allow users to search the directory and initiate the cloning routine without having to leave the cloning page. See https://github.com/BCcampus/pressbooks-textbook for an early prototype of this idea (used the Pressbooks API to provide a 'search and import' tool and and present list of content which could be downloaded from 'federated networks' defined by user). 

Done for this task equals a feasible proposal with details to implement in a future sprint.

**Comment by arzola** [comment]
After doing some tests and research it's feasible to integrate algolia instant search + autocomplete to be able to search for books inside the cloning page.

https://share.getcloudapp.com/GGupLLrY

This would require the following.

1. Create an specific js file for this change
2. Include a couple of libraries required to work (instant search and autocomplete)
3. Work on the styles and the required data to be presented on the suggestions box.

I created the prototype using algolia instant search 3 but it's possible to build with the new version with some adjustments.
