### ISSUE TITLE
Front and back matter image size is inconsistent in PDF exports

### ISSUE THREAD

**Issue by gavinpressbooks** [pressbooks/pressbooks#2293]
### Description

Images embedded in book front and back matter will default to the medium image size in PDF exports, regardless of what which preset image size or custom image size is applied. [(Related Zendesk support ticket)
](https://pressbooks.zendesk.com/agent/tickets/6592)
### Steps to Reproduce

1. Select any front matter or back matter type.
2. Embed an image using the medium size preset.
3. Embed the same image using the large size preset.
4. Embed the same image using a custom size.
5. Export the book in a PDF format.

**Expected behavior:** Resizing of images is reflected in PDF outputs and is consistent with the style of the webbook and EPUB exports.

**Actual behavior:** All images embedded in front and back matter default to one size regardless of the image dimensions indicated.

![Screen Shot 2021-08-02 at 9 42 30 AM](https://user-images.githubusercontent.com/85123231/127871444-66884e45-2509-4232-9c88-2aa02a6e8724.png)
![Screen Shot 2021-08-02 at 9 42 43 AM](https://user-images.githubusercontent.com/85123231/127871460-ffedb53e-7fbc-473b-99c5-741b115c75b4.png)
![Screen Shot 2021-08-02 at 9 43 33 AM](https://user-images.githubusercontent.com/85123231/127871469-bfaec2f6-e605-4f54-b824-4fc780a4ed80.png)

**Comment by SteelWagstaff** [comment]
Closing in favour of https://github.com/pressbooks/pressbooks/issues/2346
