### ISSUE TITLE
Users cannot choose a profile language different than their book metadata if only one language is installed for the network

### ISSUE THREAD

**Issue by gavinpressbooks** [pressbooks/pressbooks#2301]
### Description

On the [University of Kansas network](https://opentext.ku.edu), the option to choose an interface language within the Profile Menu is missing. When changing the metadata language of a book in the Book Info page, the user interface automatically mirrors that language, causing confusion for the user experience. On the University of Kansas network settings, only English is available to choose as the Site default, whereas other networks with multiple languages installed see more than one option. Please see the related client interaction in Zendesk: https://pressbooks.zendesk.com/agent/tickets/6515

### Steps to Reproduce

1. Log in to https://opentext.ku.edu
2. Navigate to Network Admin > Settings > Network Options.
3. Observe that one default language is available.
4. Create a new book or visit an existing book.
5. Change the book's metadata language to something other than English in the Book Info page.
6. Navigate to the User Profile page and attempt to change the language.

**Expected behavior:** The user can change the Profile language independently of the book's metadata language.

**Actual behavior:** The option to change the Profile language is missing.

**Comment by SteelWagstaff** [comment]
Can be potentially be fixed by https://github.com/pressbooks/client-infrastructure/pull/18

**Comment by SteelWagstaff** [comment]
Added English UK and French as default languages available for all networks on clients server. Fixed for one client, can deploy to others during next deploy task.
