### ISSUE TITLE
Add and handle profile picture field for contributors

### ISSUE THREAD

**Issue by SteelWagstaff** [pressbooks/pressbooks#2311]
As a book author, I'd like to upload small profile images for each of my book's contributors so that they can be displayed as part of their 'contributor profile' on chapters, contributor front matter, and the book's home page.

Users should either be prompted/required to upload a square image (no bigger than 500px), or should be allowed to crop an image that they've uploaded/chosen from the media library. 

If they upload a very large image, we should resize it before saving.

Contributor images should be displayed as part of the user's profile in the 'About the Authors' block.

Progress on profile picture in `hackathon-contributorProfilePicture` branch:

https://user-images.githubusercontent.com/13248424/128247043-b52358ee-3290-410c-85ef-7b47bbfe384f.mp4

Pending:
- make sure that input fields are cleared after the user's profile picture is added and a new contributor is saved 
- add user profile picture for `contributor_picture` taxonomy metadata for existing users
- Force size (square). Now it's using thumbnail by default (there is some progress at the backend level, but it needs to be improved)
- Styling

**Note**: _the plugin that Ned suggested won't work because it's for avatars, and it's a custom field (each user will have different pictures for different books, instead a user metadata - avatar for all books)_

**Comment by arzola** [comment]
I tested it on integrations and works perfectly, thanks
