### ISSUE TITLE
EPUB validation errors when `>` and `<` characters are used in chapter titles

### ISSUE THREAD

**Issue by SteelWagstaff** [pressbooks/pressbooks#2316]
### Description

If a user includes a `<` or `>` sign in their chapter title or an H1 element (if the 'Enable two-level table of contents (displays headings under chapter titles)' theme option is selected), the EPUB export will produce a fatal error when producing the table of contents, because these characters are not properly escaped.

### Steps to Reproduce

1. Create a new book with a greater than or less than sign in the title
2. Set up book setting so that you email yourself the error (settings->export->Email Validation Logs)
3. Produce an EPUB export and observe an error that resembles the following\
```
FATAL(RSC-016): /srv/www/university.pressbooks.pub/releases/20210810175859/web/app/uploads/sites/712/pressbooks/exports/EPUB-Export-1628725612.epub/OEBPS/table-of-contents.html(13,126): Fatal Error while parsing file: The content of elements must consist of well-formed character data or markup.
ERROR(RSC-005): /srv/www/university.pressbooks.pub/releases/20210810175859/web/app/uploads/sites/712/pressbooks/exports/EPUB-Export-1628725612.epub/OEBPS/table-of-contents.html(-1,-1): Error while parsing file: The content of elements must consist of well-formed character data or markup.
FATAL(RSC-016): /srv/www/university.pressbooks.pub/releases/20210810175859/web/app/uploads/sites/712/pressbooks/exports/EPUB-Export-1628725612.epub/toc.ncx(46,45): Fatal Error while parsing file: The content of elements must consist of well-formed character data or markup.
ERROR(RSC-005): /srv/www/university.pressbooks.pub/releases/20210810175859/web/app/uploads/sites/712/pressbooks/exports/EPUB-Export-1628725612.epub/toc.ncx(-1,-1): Error while parsing file: The content of elements must consist of well-formed character data or markup.
```
3. Remove the < and > from your title. Add them to the content of the chapter within an H1 element. 
4. Go to appearance->theme options and select 'Two-level TOC'
5. Produce an EPUB export. 
6. Observe a similar error message
See sample book with problem at https://university.pressbooks.pub/epubtest

**Expected behavior:**
EPUBs should be produced without fatal errors even if special HTML characters are used in chapter titles or H1 elements 

**Actual behavior:** 
EPUBs produce error messages

**Comment by richard015ar** [comment]
I could not replicate this using the new blade template in `exportHackathon-friday` branch, it seems to be fixed.

**Comment by richard015ar** [comment]
We tested it on integrations and seems to be fixed. See: https://integrations.pressbooks.network/tesimport4
There is a title with `>` and a heading 1 in the content. Also the settings in theme options is enabled.
