### ISSUE TITLE
Rebuild the clone a book page

### ISSUE THREAD

**Issue by SteelWagstaff** [pressbooks/pressbooks#2317]
As a Pressbooks user, I'd like to be able to find books of interest to clone directly from the Pressbooks 'clone a book' page. In order to do this, I should be able to enter a search phrase on the Clone a Book page, see initial results and click a book of interest. When clicked, the source URL should be populated for me. See https://www.figma.com/file/DDZ7YuklYsX9AAyVc5caUv/User-Dashboard?node-id=319%3A416&t=szl7INFb6UT7AM4W-0 for new proposed wireframe

According to Oscar's previous research, this will require the following:

1. Creating an specific js file for this change
1. Including the libraries needed to make this work (instant search and autocomplete)
1. Working on the styles and the required data to be presented on the suggestions box.

The initial prototype should only display books with licenses permitting cloning. Display should use the production directory's default 'relevance' display order. Results should include the book's cover (floated left), title, license, word count, # of H5P activities, and description. Where no short or long description is available, it should say 'no description available for this book'

When the user clicks the 'Select this book' button, the URL of the selected book should populate the Source Book URL field, the book title part of the path should populate the new book URL field, and browser focus should be shifted to the clone button. 

TODO:
- [x] Develop wireframe for 'Clone a book' page
- [x] Implement design changes
- [x] Add new 'search directory' feature on this page

**Comment by richard015ar** [comment]
Related: https://github.com/pressbooks/pressbooks/issues/2285

**Comment by richard015ar** [comment]
I will start the algolia integration with some tests using https://www.algolia.com/doc/integration/wordpress/indexing/setting-up-algolia/?client=php

**Comment by richard015ar** [comment]
PB Directory integration PR: https://github.com/pressbooks/pressbooks/pull/3049
Assigned to @fdalcin for revision.
