### ISSUE TITLE
Front Matter types and Back Matter types bug

### ISSUE THREAD

**Issue by colomet** [pressbooks/pressbooks#232]
http://rld.on-lingua.com/template/

if from the home of the book i try to go to Front Matter types introduction or Back Matter types appendix, also if direct i try just to read the book. The page jumt to the home.

in the same installation, with diferent books http://rld.on-lingua.com/templatex1/ i have not that problem. Do you have any idea why?

**Comment by greatislander** [comment]
This issue was previously identified and fixed (https://github.com/pressbooks/pressbooks/issues/192). I notice you are running Pressbooks 2.4.5. The current version is 2.6.6. Please ensure that you are running an up-to-date version of Pressbooks before posting bug reports.

**Comment by colomet** [comment]
sorry. my mistake.

**Comment by colomet** [comment]
I actualice to 2.6.6. but the mistake is in the same place http://rld.on-lingua.com/lexicala1en/

**Comment by greatislander** [comment]
You may need to visit this page http://rld.on-lingua.com/lexicala1en/wp-admin/options-permalink.php, then try viewing the book again.

**Comment by colomet** [comment]
ok. thanks. it was the solution. i was thinking with permalinks, but i did not kno whow to find it.
