### ISSUE TITLE
Enable Social Media

### ISSUE THREAD

**Issue by colomet** [pressbooks/pressbooks#233]
i can close Facebook buttom but not twitter or email.

**Comment by greatislander** [comment]
I'm sorry but I don't know what you mean. Can you explain further or add a screenshot?

**Comment by colomet** [comment]
![captura de pantalla 2015-08-30 a las 19 10 56](https://cloud.githubusercontent.com/assets/3929177/9568482/dcc85854-4f4a-11e5-85b1-8cb4e2a57e2c.png)
![captura de pantalla 2015-08-30 a las 19 10 42](https://cloud.githubusercontent.com/assets/3929177/9568483/dcd05310-4f4a-11e5-889d-3dee061e5d1a.png)

-----

![captura de pantalla 2015-08-30 a las 19 11 17](https://cloud.githubusercontent.com/assets/3929177/9568487/f92f8134-4f4a-11e5-859c-ea9ab7a64696.png)
![captura de pantalla 2015-08-30 a las 19 11 23](https://cloud.githubusercontent.com/assets/3929177/9568488/f9313358-4f4a-11e5-8a8d-6a157954d710.png)

**Comment by greatislander** [comment]
Fixed in https://github.com/pressbooks/pressbooks/commit/af347f0739b30d7bb346bc3f3391eda858f98012, will release on WordPress.org shortly.
