### ISSUE TITLE
user's profile language set to Chinese randomly

### ISSUE THREAD

**Issue by hughmcguire** [pressbooks/pressbooks#234]
user language (randomly) set to Chinese. more detail to come.

**Comment by hughmcguire** [comment]
to replicate: 
- go to dev install
- add a new user
- check user profile ... see profile language = chinese.

will investigate more, but this is happening on our web dev install.

**Comment by greatislander** [comment]
As in the language changes to Chinese when passwords are reset?

**Comment by hughmcguire** [comment]
yes

**Comment by hughmcguire** [comment]
note, just went through a client install w/ ~80 users, about 30% of them had profile language set (incorrectly) to `chinese (taiwan)`.

**Comment by greatislander** [comment]
It wasn't actually set to Chinese; those users had no interface language set but Chinese had ended up first in the list so it defaulted to Chinese. It only would have stuck if they saved their profile (e.g. updated password). This won't happen anymore.
