### ISSUE TITLE
Improve clone routine to not duplicate the contributors back matter

### ISSUE THREAD

**Issue by arzola** [pressbooks/pressbooks#2340]
### Description

We integrated a new back matter with a Contributors list this is automatically created for new books we should prevent to duplicate that page during the clone routine

`class-cloner`

```php
public function removeDefaultBookContent( $contents ) {
		foreach (
			[
				'introduction',
				'main-body',
				'chapter-1',
				'appendix',
			] as $post
		) {
			unset( $contents[ $post ] );
		}
		return $contents;
	}
```

**Comment by SteelWagstaff** [comment]
@arzola Cloning routine has major problems on integrations: https://images.zenhubusercontent.com/9209369/a7bd80af-b2ee-47ba-891f-3a89751e20e7/cloning_failure.mp4
