### ISSUE TITLE
Prince PDF exports with Chinese Characters on pressbooks.com render as question marks

### ISSUE THREAD

**Issue by jflowers45** [pressbooks/pressbooks#235]
If I set the language of a book to Chinese and then paste content like this into a chapter:

書作者楊繼繩接受美國之音採訪的時候指出

it renders as question marks in the prince PDF.  

Note that on my local, unedited subdirectory install of pressbooks, updated to the most recent 'dev' commit, I do not have this problem - .

![screenshot 2015-08-31 16 53 08 2](https://cloud.githubusercontent.com/assets/1021048/9590333/ecf6acdc-5001-11e5-922a-8699d5867119.png)
![screenshot 2015-08-31 16 53 27](https://cloud.githubusercontent.com/assets/1021048/9590334/ecf7fede-5001-11e5-8d34-1d79aba55bb1.png)

**Comment by hughmcguire** [comment]
you need to have a theme with support for chinese character fonts.

**Comment by hughmcguire** [comment]
and, need to provide the fonts.

**Comment by jflowers45** [comment]
Cool.  I had Luther enabled on both.  The one created locally automatically (OS X) embedded LiSong pro.  The one created on pressbooks.com did not.  So I just found this thread which indicates that's a prince/OS X thing.  mystery solved.  closing issue.

http://www.princexml.com/forum/topic/2707/chinese-charatcers-working-on-dev-server-not-on-live-server
