### ISSUE TITLE
Contributor image crop fails with vertical images

### ISSUE THREAD

**Issue by SteelWagstaff** [pressbooks/pressbooks#2353]
### Description

I'm not able to upload and crop an image that is taller than it is wide when adding a profile picture for a contributor. 

### Steps to Reproduce

1. Create a new contributor and add a profile picture
2. Upload an image that is taller than it is wide
3. Try to crop the image
4. Try to save the image

https://user-images.githubusercontent.com/13485451/131746446-ef93727b-759f-46ef-af73-fa9bc0ab75ca.mp4

**Expected behavior:** As long as the image is larger than 400x400, I should be able to upload it and crop to expected dimensions.

**Actual behavior:** I could not see the cropping interface, nor could I apply the crop and use an image if it was taller than it is wide.

**Comment by fdalcin** [comment]
Tested on integrations and works as expected.
