### ISSUE TITLE
Contributor profile pictures disassociated/disappear after editing some other part of existing contributor's profile

### ISSUE THREAD

**Issue by SteelWagstaff** [pressbooks/pressbooks#2355]
Profile pictures for contributors are disassociated with contributors when some other part of a contributor is edited and saved.

https://user-images.githubusercontent.com/13485451/131752431-e4ce9e96-5371-41f7-ab39-db17f31ec37c.mp4

**Comment by fdalcin** [comment]
Tested on integrations and works as expected.
