### ISSUE TITLE
Include new contributors in cloning routine

### ISSUE THREAD

**Issue by SteelWagstaff** [pressbooks/pressbooks#2358]
## Desired Outcome

When we clone an existing book, the resulting clone should include all of the contributors from the source book which were a) assigned a role in book info, b) assigned as an author to front/back matter, parts, or chapters. Each of these contributors should include all of the same contributor info they had in the source book (name, slug, first name, bio, links, profile photo, etc.) and should be associated with book info and book content in identical ways. 

## Notes
When we clone a new book, we first have to create a book shell. When we do this, a contributor is automatically created for the person who is cloning the book. It is possible that the cloned book will also have a contributor with the same slug as this new book. If this is the case, the contibutor in the source book should be overwritten and replaced by the contributor from the target book. At the end of the clone there should be no duplicate contributors, in other words. 

### Testing Scenarios
1. Ricardo clones a book which has 4 contributors in its contributor list (Oscar, Steel, Ho Man, and Dalcin). In book info, Oscar is listed as the editor, Steel listed as the author, and Ho Man and Dalcin listed as contributors. At the end of the cloning routine, the newly cloned book has 5 contributors in its contributor list: Oscar, Steel, Ho Man, Dalcin and Ricardo (the person who initiated the clone). In book info, Oscar is listed as the editor, Steel is listed as the author, and Ho Man & Dalcin are listed as the contributor. All of the contributor info for Oscar, Steel, Ho Man, and Dalcin should be cloned in the target book exactly as they appeared in the source book. Ricardo should exist in the contributor list but should not be assigned to a role in book info.
2. Ricardo clones a book which has 2 contributors in its contributor list: Steel and Ricardo. Steel is listed as the editor and Ricardo is listed as the author. During the cloning routine, we notice that the slugs for the two Ricardos are identical, so we overwrite the contributor information for Ricardo in the target book with the information from the source book. At the end of the clone, there are 2 contributors in the contributor list for the cloned book: Steel and Ricardo. Steel is listed as the editor and Ricardo is listed as the author. The contributor info for Steel and Ricardo in the target book is identical to the info from the source book.

## Ideas
In terms of what we need for contributors, we should look at https://github.com/pressbooks/pressbooks/blob/d712117757f36503505e61e85a82fa13acdc980b/inc/cloner/class-cloner.php#L422-L428

We need to make sure that all contributor information is included when books/contributors are cloned. We should probably add contributors to getBookTerms: https://github.com/pressbooks/pressbooks/blob/d712117757f36503505e61e85a82fa13acdc980b/inc/cloner/class-cloner.php#L862
and make sure we’re not overriding them with the get book info names (consider removing/altering this block): https://github.com/pressbooks/pressbooks/blob/d712117757f36503505e61e85a82fa13acdc980b/inc/cloner/class-cloner.php#L1317-L1321 

Once we do this, we still need to clone book info, but can remove the ‘create contributor’ step.

The cloning routine has major problems on integrations: https://images.zenhubusercontent.com/9209369/a7bd80af-b2ee-47ba-891f-3a89751e20e7/cloning_failure.mp4

**Comment by arzola** [comment]
Notes about cloning behavior

I have been able to clone properly new books on my local and also books from integrations, the only thing that I found is the issue we found about the contributors defined in this ticket because we use the slug to match contributors and chapters and due our new prefixes and suffixes the slugs became different when cloning.

![image](https://user-images.githubusercontent.com/4997549/132083564-7abf683e-2832-4b58-b0d5-8c0ffdf79be9.png)

We would need to address the following

1. Improve the contributors cloning using the terms as Ned suggested and remove oxford_comma handling 
2. Ensure and test we are cloning contributors properly with the new metadata (prefix/suffix) and also the contributors are being added to the chapters and book info. (maybe double check to respect slug being created only with name and not with the new suffix/prefix)

### Notes

I was doing xdebug step by step debugging to try to solve #2324 but I only found that the chapters are orphan without a post_parent relationship, we need to ensure the terms are being created properly I suggest to review the source book database structure to see if we can find any missing metadata.

**Comment by SteelWagstaff** [comment]
Bug I noticed -- all contributors were cloned as expected, but not all contributor info was included for the cloned contributors.

Original:
![screencapture-integrations-pressbooks-network-contributordemo-wp-admin-edit-tags-php-2021-09-24-15_44_04](https://user-images.githubusercontent.com/13485451/134746795-58b4d61e-46aa-4cfe-a4de-3359e2ba186d.png)

Clone:
![screencapture-integrations-pressbooks-network-rebusclone-wp-admin-edit-tags-php-2021-09-24-15_44_10](https://user-images.githubusercontent.com/13485451/134746792-93a15c99-53e1-438e-b7b3-1a1bf2184101.png)

Contributors for whom information was lost were ones which were only assigned to book info with a role but were not as authors of a specific front/back matter or chapter. 

Source book: https://integrations.pressbooks.network/contributordemo/wp-admin/
Target book: https://integrations.pressbooks.network/rebusclone

**Comment by SteelWagstaff** [comment]
Second bug:
the author assigned to the front matter was not associated correctly following the clone.
![Screenshot from 2021-09-24 15-58-27.png](https://images.zenhubusercontent.com/6012398f80b7cb0f8d1385bc/7501c9d1-239a-4dad-9151-ca0c73aea95f)
Source book: https://integrations.pressbooks.network/makingcontribs
![Screenshot from 2021-09-24 15-58-42.png](https://images.zenhubusercontent.com/6012398f80b7cb0f8d1385bc/a7e9f4af-becc-4c86-8aaa-5c9704c517cb)
Target book: https://integrations.pressbooks.network/contribsclone

**Comment by SteelWagstaff** [comment]
Here's a video of both issues (author disappearing from introduction after clone, and contributor info not being included when the user is assigned to book info but not a specific chapter)
https://user-images.githubusercontent.com/13485451/134749366-b0d37f23-ee78-42af-b6f8-2814b3be6625.mp4

**Comment by SteelWagstaff** [comment]
Confirmed working on integrations and bibliotest.
