### ISSUE TITLE
Jetpack is not working

### ISSUE THREAD

**Issue by colomet** [pressbooks/pressbooks#236]
i can not conect to wordpress.com with jetpack in a new installation

![captura de pantalla 2015-09-03 a las 13 46 11](https://cloud.githubusercontent.com/assets/3929177/9657525/302f05f2-5242-11e5-9755-aa1f2847e4d1.png)

The same page before and after push the buttom.

The domain name change from http://rld.on-lingua.com/wp-admin/admin.php?page=jetpack to http://rld.on-lingua.com/wp-admin/admin.php?page=jetpack&action=register&_wpnonce=3f0bfdbfd3

but nothing happen.

**Comment by greatislander** [comment]
Generally speaking, we do not provide support for other plugins used in conjunction with Pressbooks. Jetpack is particularly complex and prone to running into problems because of the ways in which Pressbooks alters WordPress' standard functionality, and as such is not supported.

**Comment by greatislander** [comment]
(If you can identify the specific issue that is taking place here through debug logs, I may be able to take a look but unfortunately this is low on our priority list.)

**Comment by colomet** [comment]
well. i don´t know, but i´ll check.

 besides it was working with pressbooks 2.4.5

**Comment by greatislander** [comment]
Are you getting the `site_lang_missing` error?

**Comment by greatislander** [comment]
Actually, I was able to connect it without issue using the following steps:

1. Create new installation of Pressbooks.
2. Create a new book.
3. Set the language to English on the Book Information page.

Connect Jetpack from the book (not from the root site—this does not seem to work).

**Comment by BillDStrong** [comment]
You can temporarily deactivate the Pressbooks plugin, connect JetPack, then reactivate Presbooks.

Wordpress is really pushing Jetpack as the way to manage multiple Wordpress installs, in part by pushing their new Calypso Desktop app. It might be strategic to fix this issue for the future.

**Comment by colomet** [comment]
good idea, I'll try

**Comment by greatislander** [comment]
@BillDStrong Pressbooks makes so many changes to the default functionality of WordPress that I can pretty much guarantee Calypso won't work to manage a Pressbooks book.

However, if you are interested in using other JetPack features and can diagnose the issue—ideally submitting a pull request that restores the ability to activate JetPack on a Pressbooks network—it will be considered for merging. We are a team that consists of one developer, so we hope you can appreciate that our resources are limited.
