### ISSUE TITLE
Contributors back matter is not being displayed

### ISSUE THREAD

**Issue by richard015ar** [pressbooks/pressbooks#2361]
### Prerequisites

* [x] Can you reproduce the behavior you wish to address with [all other plugins deactivated](http://codex.wordpress.org/Multisite_Network_Administration#Plugins)?
* [x] Are you running the [latest version of Pressbooks](http://github.com/pressbooks/pressbooks/releases/latest/) and the [latest version of WordPress](http://codex.wordpress.org/Upgrading_WordPress)?

### Description

When a new _Contributors Back Matter_ is created in a book, the contributors list is not displayed as expected, according to https://github.com/pressbooks/pressbooks/pull/2336.
It worked before, but looks we deployed some changes in Staging that breaks the feature.

### Steps to Reproduce

1. In a book with contributors (you can check and add those in Book Info section) add a new Back Matter (Contributors type).
2. Make sure the back matter is empty (title is allowed).
3. Visit the new Back Matter you just created.

**Expected behavior:** The list of contributors with its information must be displayed.

**Actual behavior:** The Contributors back matter is empty.

Example: https://integrations.pressbooks.network/contributorslisttest/back-matter/43/

More info:
- https://github.com/pressbooks/pressbooks/issues/2314
- https://github.com/pressbooks/pressbooks/pull/2336

**Comment by SteelWagstaff** [comment]
Problem was invisible div and $nbsp. Could add better check for this case in future.
