### ISSUE TITLE
Fix 'contributor' display throughout webbook and exports

### ISSUE THREAD

**Issue by SteelWagstaff** [pressbooks/pressbooks#2371]
## Remaining issues
- [ ] #2401
![Screenshot from 2021-09-24 20-21-11](https://user-images.githubusercontent.com/13485451/134756211-e2313764-37f7-4733-866a-a708fbbd7562.png)
![Screenshot from 2021-09-24 20-17-02](https://user-images.githubusercontent.com/13485451/134756218-4540c751-b51f-442d-a259-bcc42261ebff.png)
- [x] Twitter links get turned into oEmbeds in EPUB exports (just like they do in webbooks if you paste them on their own line). We need to turn off oEmbed for these links in our EPUB export routine. i think we have a function called overrideEmbeds: https://github.com/pressbooks/pressbooks/blob/dev/inc/interactive/class-content.php#L430-L443 which calls a function called replaceOembed: https://github.com/pressbooks/pressbooks/blob/dev/inc/interactive/class-content.php#L256-L280 that we use to replace oEmbed content using a Blade tempalte: https://github.com/pressbooks/pressbooks/blob/dev/templates/interactive/oembed.blade.php
Here's the output in the HTML of the EPUB which has a twitter link that has been 'oembedded' into an iframe:
` <p><a class="twitter-timeline" href="https://twitter.com/steelwagstaff?ref_src=twsrc%5Etfw">Tweets by steelwagstaff</a><script async="" src="https://platform.twitter.com/widgets.js" charset="utf-8"></script></p>`. I think there are two problems:
1. we're replacing the actual text inside the link
2. we're including a script which causes validation errors and display problems in certain EBOOK readers
The result of our not overriding these oEmbeds are broken EPUBs and lots of validation errors. 
![Screenshot from 2021-09-24 20-49-20](https://user-images.githubusercontent.com/13485451/134756924-efa73f87-b9fa-48d7-bba6-4d9cc6c515f3.png)
- [x] Don't automatically create 'Contributors' back matter when new books are created
- [x] We need to figure out better way to render HTML text in contributor bio. Current method which uses wp_kses, strips out `<p>` tags and other unwanted html elements: https://github.com/pressbooks/pressbooks/blob/3ab65feca72e43439e143a7ddab3e1fc175f2c0e/templates/posttypes/contributor.blade.php#L83 
As a result single paragraph bios are wrapped in `<p>` element thanks to autop, but those which had multiple paragraphs in them originally aren't (all `<p>` elements which existed in the bio are removed). The result is inconsistent justification -- elements which are in p elements are justified, and those which aren't ragged edge because of how styles are being applied. See screenshot below:
![Screenshot from 2021-09-24 20-55-59](https://user-images.githubusercontent.com/13485451/134757050-efd3a474-a36d-41b1-a841-e678392c6338.png)
- [x] SVG icon class doesn't match expected BEM pattern

We need to make sure that the 'About the Authors' section is displaying as desired in front/back matter & chapters and the new 'Contributors' back matter type displays contributors as desired in the webbook and all exports. 

## Rendering contributors consistently
We have a three new ways of rendering contributors We have a Blade template in pressbooks: https://github.com/pressbooks/pressbooks/blob/dev/templates/posttypes/contributors.blade.php that is used in contributors back matter, we have a PHP file in pressbooks-book partials: https://github.com/pressbooks/pressbooks-book/blob/dev/partials/content-contributor-profile.php that is used in the about the author section of webbook chapters, and we have a get_contributors_section function that is shared by export routines: https://github.com/pressbooks/pressbooks/blob/5ff6a0e0bf237e8a88cc33c8b888d3dc85a32be5/inc/modules/export/namespace.php#L291-L327

Dalcin recommended looking at https://github.com/pressbooks/pressbooks/blob/3217c734b9f3d25d840c247a5ac5b16b6c1698cb/inc/admin/class-sitemap.php#L67 as a model for how we could use/render Blade templates.

- [x] We reduce the scope of our existing Blade template to encompass a single contributor & support a variable for rendering SVG files or links for social links
We should then render this template (with modifications for SVG image/links) in the four places it is needed: 
- [x] 'About the author' section in webbook front/back matter & chapters (pressbooks-book)
- [x] export files for 'About the author' section in front/back matter & chapters (same as previous but with H3 instead of H2 and printed links instead of SVG for social icons)
- [x] 'Contributors' back matter list (book info contributor list, parsed by role)
- [x] export files for 'contributors' back matter list (same as previous but with printed links instead of SVG for social icons)

## General styling bugs:
- [x] SVGs display text-style: underline in contributors back-matter
![Screenshot from 2021-09-16 16-51-22](https://user-images.githubusercontent.com/13485451/133702957-d4623482-5c99-48e0-851f-503e7c91385d.png)

## Export bugs:
- [x] #2374
- [x] Profile image size (too big)
![Screenshot from 2021-09-16 15-30-52](https://user-images.githubusercontent.com/13485451/133693935-3a6ff6bf-95e7-4a7b-8da6-3018f4d4f295.png)
- [x] Aren't implementing SVG fallback for contributors back-matter

**Comment by SteelWagstaff** [comment]
To investigate:
1. Can we render the template as a variable (string) that can be modified before printing?
2. The parts of the template that need to be modified are the heading level and the SVG/link output

**Comment by SteelWagstaff** [comment]
Dalcine recommended looking at https://github.com/pressbooks/pressbooks/blob/3217c734b9f3d25d840c247a5ac5b16b6c1698cb/inc/admin/class-sitemap.php#L67 as a model for how we could use/render Blade templates.

We should use our existing Blade template by reducing its scope just to encompass a single contributor and then render the template (with modifications for SVG image/links) in the three places it is needed: 1) webbook front/back matter & chapters (pressbooks-book), 2) back matter of the type contributors, 3) export files for 1 and 2

**Comment by greatislander** [comment]
@SteelWagstaff see https://github.com/pressbooks/pressbooks/pull/2399
