### ISSUE TITLE
Some mPDF option defaults aren't valid until saved

### ISSUE THREAD

**Issue by jflowers45** [pressbooks/pressbooks#238]
If you create a new book and export an mPDF, it won't include the table of contents in the body of the PDF.  However, if you then browse to mPDF options, you will notice that the checkbox for including the ToC is checked.  If you simply click 'save' for the settings, the table of contents will show on next export.  

This is because pressbooks_theme_options_mpdf_init only includes defaults for mpdf_page_size, mpdf_include_cover, and mpdf_indent_paragraphs
https://github.com/pressbooks/pressbooks/blob/a55904d09483fa411a8f75c93cabea9fa174a495/themes-book/pressbooks-book/functions.php#L1091

However, the display callback functions for the settings tab have an empty check that sometimes sets a non-empty value.
https://github.com/pressbooks/pressbooks/blob/a55904d09483fa411a8f75c93cabea9fa174a495/themes-book/pressbooks-book/functions.php#L1346

I would think the ideal fix would be to have pressbooks_theme_options_mpdf_init set all the values by default and to remove the empty checks in the callbacks .. happy to submit a PR with that if you guys agree

**Comment by greatislander** [comment]
@jflowers45 If you are okay to put a pull request together that would be greatly appreciated!

**Comment by jflowers45** [comment]
Happy to do this, should be able to squeeze it in next week.

**Comment by hughmcguire** [comment]
@greatislander can we move these mPDF issues out of Pressbooks?
