### ISSUE TITLE
The contributors post metadata are not deleted when the contributor is deleted from Book info > Contributors

### ISSUE THREAD

**Issue by richard015ar** [pressbooks/pressbooks#2385]
### Prerequisites

* [x] Can you reproduce the behavior you wish to address with [all other plugins deactivated](http://codex.wordpress.org/Multisite_Network_Administration#Plugins)?
* [x] Are you running the [latest version of Pressbooks](http://github.com/pressbooks/pressbooks/releases/latest/) and the [latest version of WordPress](http://codex.wordpress.org/Upgrading_WordPress)?
* [x] Are you experiencing this issue with one of our built-in root or book themes?
* [x] Did you [perform a cursory search](https://github.com/issues?q=+is%3Aissue+repo%3Apressbooks%2Fpressbooks) to see if your bug or enhancement is already listed?

### Description

When a contributor which is an author, editor, illustrator, contributor, reviewer and/or translator declared in Book Info  is deleted from Book Info > Contributors list the post metadata is not deleted. 
I don't know what is the impact of this, but we could use this hook: https://developer.wordpress.org/reference/hooks/delete_taxonomy/ to make sure we are removing all post meta information related to the contributors deleted.

### Steps to Reproduce

1. From a book, assign one o more authors, editors or other valid contributor in Book Info section
2. Check in the database the post metadata related, example: ` SELECT * FROM wp_<Blog_id>_postmeta WHERE post_id = <post type metadata id> AND meta_key = 'pb_authors';`
3. Remove one of the authors or editor, or other in the Book Info > Contributors section
4. If you perform the same query you will be able to see the post metadata is still present
5. Go to Book Info, and click in Save button
6. The metadata this time was deleted properly.

**Expected behavior:** The book post metadata should me removed when the contributor is an valid contributor and is deleted.

**Actual behavior:** The book post metadata is not cleared until the Book Info is updated.

**Comment by SteelWagstaff** [comment]
Confirmed fixed on integrations and bibliotest.
