### ISSUE TITLE
Fix broken tests PHP 7.4 migration

### ISSUE THREAD

**Issue by arzola** [pressbooks/pressbooks#2386]
We currently see the following errors when trying to run our tests against PHP 7.4:
```
PHP Fatal error:  Uncaught SebastianBergmann\CodeCoverage\RuntimeException: No code coverage driver available in /home/runner/work/pressbooks/pressbooks/vendor/phpunit/php-code-coverage/src/CodeCoverage.php:908

Stack trace:
#0 /home/runner/work/pressbooks/pressbooks/vendor/phpunit/php-code-coverage/src/CodeCoverage.php(146): SebastianBergmann\CodeCoverage\CodeCoverage->selectDriver()
#1 /home/runner/work/pressbooks/pressbooks/vendor/phpunit/phpunit/src/TextUI/TestRunner.php(539): SebastianBergmann\CodeCoverage\CodeCoverage->__construct()
#2 /home/runner/work/pressbooks/pressbooks/vendor/phpunit/phpunit/src/TextUI/Command.php(206): PHPUnit\TextUI\TestRunner->doRun()
#3 /home/runner/work/pressbooks/pressbooks/vendor/phpunit/phpunit/src/TextUI/Command.php(162): PHPUnit\TextUI\Command->run()
#4 /home/runner/work/pressbooks/pressbooks/vendor/phpunit/phpunit/phpunit(61): PHPUnit\TextUI\Command::main()
#5 {main}
  thrown in /home/runner/work/pressbooks/pressbooks/vendor/phpunit/php-code-coverage/src/CodeCoverage.php on line 908
Fatal error: Uncaught SebastianBergmann\CodeCoverage\RuntimeException: No code coverage driver available in /home/runner/work/pressbooks/pressbooks/vendor/phpunit/php-code-coverage/src/CodeCoverage.php:908
Stack trace:
#0 /home/runner/work/pressbooks/pressbooks/vendor/phpunit/php-code-coverage/src/CodeCoverage.php(146): SebastianBergmann\CodeCoverage\CodeCoverage->selectDriver()
#1 /home/runner/work/pressbooks/pressbooks/vendor/phpunit/phpunit/src/TextUI/TestRunner.php(539): SebastianBergmann\CodeCoverage\CodeCoverage->__construct()
#2 /home/runner/work/pressbooks/pressbooks/vendor/phpunit/phpunit/src/TextUI/Command.php(206): PHPUnit\TextUI\TestRunner->doRun()
#3 /home/runner/work/pressbooks/pressbooks/vendor/phpunit/phpunit/src/TextUI/Command.php(162): PHPUnit\TextUI\Command->run()
#4 /home/runner/work/pressbooks/pressbooks/vendor/phpunit/phpunit/phpunit(61): PHPUnit\TextUI\Command::main()
#5 {main}
  thrown in /home/runner/work/pressbooks/pressbooks/vendor/phpunit/php-code-coverage/src/CodeCoverage.php on line 908
Script vendor/bin/phpunit --configuration phpunit.xml --coverage-clover coverage.xml handling the test event returned with error code 255
Error: Process completed with exit code 255.
```

See https://make.wordpress.org/core/2021/09/27/changes-to-the-wordpress-core-php-test-suite/
See https://github.com/shivammathur/setup-php/releases/tag/2.15.0
See https://github.com/Yoast/wp-test-utils/releases/tag/1.0.0

**Comment by arzola** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Pressbooks-Product-Backlog-2021-60ae7d807f6e370010b3d5be/issues/pressbooks/pressbooks/2386?planning-poker) with ZenHub @richard015ar @SteelWagstaff @fdalcin

**Comment by SteelWagstaff** [comment]
Tests now run in Pressbooks against PHP7.4 (but using PHPUnit 7.5). Here is output:
PHPUnit 7.5.20 by Sebastian Bergmann and contributors.

........................EE.....................................  63 / 701 (  8%)
............................................................... 126 / 701 ( 17%)
............................................................... 189 / 701 ( 26%)
............................................................... 252 / 701 ( 35%)
.............................F................................. 315 / 701 ( 44%)
............................................................... 378 / 701 ( 53%)

Pressbooks\Modules\Export\Epub\Epub3
Array
(
    [time] => Fri Nov 12 07:23:00 2021
    [user] => user 0000770
    [site_url] => http://example.org/testpath0000769
    [blog_id] => 79
    [theme] => McLuhan
)
INFO(CSS-007): /tmp/wordpress/wp-content/uploads/sites/79/pressbooks/exports/Site-0000769-1636701775._3.epub/OEBPS/mcluhan.css(3,3): Font-face reference "OEBPS/assets/Lora-Bold.ttf" refers to non-standard font type "font/sfnt".
INFO(CSS-007): /tmp/wordpress/wp-content/uploads/sites/79/pressbooks/exports/Site-0000769-1636701775._3.epub/OEBPS/mcluhan.css(8,3): Font-face reference "OEBPS/assets/Lora-BoldItalic.ttf" refers to non-standard font type "font/sfnt".
INFO(CSS-007): /tmp/wordpress/wp-content/uploads/sites/79/pressbooks/exports/Site-0000769-1636701775._3.epub/OEBPS/mcluhan.css(13,3): Font-face reference "OEBPS/assets/Lora-Italic.ttf" refers to non-standard font type "font/sfnt".
INFO(CSS-007): /tmp/wordpress/wp-content/uploads/sites/79/pressbooks/exports/Site-0000769-1636701775._3.epub/OEBPS/mcluhan.css(18,3): Font-face reference "OEBPS/assets/Lora-Regular.ttf" refers to non-standard font type "font/sfnt".
INFO(CSS-007): /tmp/wordpress/wp-content/uploads/sites/79/pressbooks/exports/Site-0000769-1636701775._3.epub/OEBPS/mcluhan.css(23,3): Font-face reference "OEBPS/assets/CormorantGaramond-Bold.ttf" refers to non-standard font type "font/sfnt".
INFO(CSS-007): /tmp/wordpress/wp-content/uploads/sites/79/pressbooks/exports/Site-0000769-1636701775._3.epub/OEBPS/mcluhan.css(28,3): Font-face reference "OEBPS/assets/CormorantGaramond-BoldItalic.ttf" refers to non-standard font type "font/sfnt".
INFO(CSS-007): /tmp/wordpress/wp-content/uploads/sites/79/pressbooks/exports/Site-0000769-1636701775._3.epub/OEBPS/mcluhan.css(33,3): Font-face reference "OEBPS/assets/CormorantGaramond-Italic.ttf" refers to non-standard font type "font/sfnt".
INFO(CSS-007): /tmp/wordpress/wp-content/uploads/sites/79/pressbooks/exports/Site-0000769-1636701775._3.epub/OEBPS/mcluhan.css(38,3): Font-face reference "OEBPS/assets/CormorantGaramond-Regular.ttf" refers to non-standard font type "font/sfnt".

....................................F.......................... 441 / 701 ( 62%)
....................EE.........E............................... 504 / 701 ( 71%)
............................................................... 567 / 701 ( 80%)
............................................................... 630 / 701 ( 89%)
............................................................... 693 / 701 ( 98%)
........                                                        701 / 701 (100%)

Time: 2.65 minutes, Memory: 101.00 MB

There were 5 errors:

1) Admin_CoverGeneratorTest::test_pressbooks_cg_design_callback
Trying to access array offset on value of type bool

/home/runner/work/pressbooks/pressbooks/inc/admin/covergenerator/namespace.php:449
/home/runner/work/pressbooks/pressbooks/tests/test-admin-covergenerator.php:135

2) Admin_CoverGeneratorTest::test_pressbooks_cg_front_background_image_callback
Trying to access array offset on value of type bool

/home/runner/work/pressbooks/pressbooks/inc/admin/covergenerator/namespace.php:471
/home/runner/work/pressbooks/pressbooks/tests/test-admin-covergenerator.php:145

3) OptionsTest::test_sanityChecks
Trying to access array offset on value of type bool

/home/runner/work/pressbooks/pressbooks/inc/modules/themeoptions/class-ebookoptions.php:503
/home/runner/work/pressbooks/pressbooks/tests/test-options.php:249

4) OptionsTest::test_sanityChecks_ShapeShifter
Trying to access array offset on value of type bool

/home/runner/work/pressbooks/pressbooks/inc/modules/themeoptions/class-ebookoptions.php:503
/home/runner/work/pressbooks/pressbooks/tests/test-options.php:249
/home/runner/work/pressbooks/pressbooks/tests/test-options.php:262

5) PDFOptionsTest::test_scssOverrides
Trying to access array offset on value of type bool

/home/runner/work/pressbooks/pressbooks/inc/modules/themeoptions/class-pdfoptions.php:1964
/home/runner/work/pressbooks/pressbooks/tests/test-pdfoptions.php:16

--

There were 2 failures:

1) ImageTest::test_fudge_factor
Failed asserting that false is true.

/home/runner/work/pressbooks/pressbooks/tests/test-image.php:93

2) Modules_Export_ExportTest::test_sanityChecks with data set #6 ('\Pressbooks\Modules\Export\Epub\Epub3', false)
Could not validate with \Pressbooks\Modules\Export\Epub\Epub3
Failed asserting that false is true.

/home/runner/work/pressbooks/pressbooks/tests/test-modules-export-export.php:404

ERRORS!
Tests: 701, Assertions: 9481, Errors: 5, Failures: 2

**Comment by SteelWagstaff** [comment]
Tests now pass for WP 5.9 + PHP 7.4 using PHPUnit 9.5
