### ISSUE TITLE
Post meta associations break when a contributor's slug is edited

### ISSUE THREAD

**Issue by SteelWagstaff** [pressbooks/pressbooks#2406]
Contributors have slugs. When you associate a contributor as the author of a chapter or assign them a book-level role, we associate the slug with the post meta. If you assign a contributor to be the author of a chapter and then edit their slug, this association is broken. 

We should do one of the following:
1. if possible, create a method which updates all post meta when a contributor's slug is edited (find original slug and replace with new slug)
2. hide/remove the ability to edit contributor slugs from users
3. Make the slug field 'read only' on the edit contributors form

**Comment by fdalcin** [comment]
We are setting the slug input as read only in Edit Contributor form.
