### ISSUE TITLE
Add 'Institution' field to book info

### ISSUE THREAD

**Issue by SevenSidedSquare** [pressbooks/pressbooks#2407]
Part of https://github.com/pressbooks/ideas/issues/404

We should make the following changes in Pressbooks
- [x] Create a new Institution list in our symbionts folder (see ideas below -- but we can start with JSON file from Ontario)
- [x] Create a new book info field called ‘Institution’ which will allow book authors to select one or more of the institutions available in their network’s ‘Institutions’ list. Provide text to allow users to suggest a new institution
- [x] Add institution field to API and include in cloning routine 

## Notes
For the first item, we would prefer to have institutions function as a controlled vocabulary/taxonomy. I think the most ideal option would be to create/use a prebuilt controlled vocabulary/list of institutions (which would then function like Thema subject headings), though I don't know whether we could create/find such a list or whether we'd want to maintain this. One option might be https://univ.cc/? Alternatively, we could allow institutions to be be created/maintained at the network level only by super admins/network managers. I don't understand how/whether a network level taxonomy can be shared with books/sites, nor do I have a clear idea what would/should happen when a book was cloned. At its simplest, network managers could simply input several institutions, one per line, the way we allow them to maintain an iframe Allowlist:
![Screenshot from 2022-01-05 19-18-45](https://user-images.githubusercontent.com/13485451/148322976-a7765326-62f2-436d-9785-96a06cb83539.png) 
We could also simply let this be a free-entry field in book info, and treat each line as a separate entity? 

This is currently [blocked in Asana](https://app.asana.com/0/1199100224616909/1200482439883299) by "Revamp Aldine theme." See https://github.com/pressbooks/pressbooks-aldine/issues/242

**Comment by SteelWagstaff** [comment]
Feature stakeholders: network managers for consortial Pressbooks networks (eCampusOntario, Open Oregon, etc)

Two options for this:
1. free text entry
2. create new taxonomy with set of associated fields
In either case, need to display institution on book list so it can be reviewed quickly by network managers

**Comment by SteelWagstaff** [comment]
Initial list of Ontarian institutions ([source](https://www.ecampusontario.ca/about/)):

- Algoma University
- Algonquin College
- Brock University
- Cambrian College
- Canadore College
- Carleton University
- Centennial College
- Collège Boréal
- Conestoga College
- Confederation College
- Durham College
- Fanshawe College
- First Nations Technical Institute (FNTI)
- Fleming College
- George Brown College
- Georgian College
- Humber College
- Kenjgewin Teg
- La Cité
- Lakehead University
- Lambton College
- Laurentian University
- Loyalist College
- McMaster University
- Mohawk College
- Niagara College
- Nipissing University
- Northern College
- OCAD University
- Ontario Tech University
- Queen’s University
- Royal Military College of Canada
- Ryerson University
- Sault College
- Seneca College
- Seven Generations Education Institute
- Sheridan College
- Six Nations Polytechnic
- St. Clair College
- St. Lawrence College
- Trent University
- Université de l’Ontario français
- University of Guelph
- University of Ottawa
- University of Toronto
- University of Waterloo
- University of Windsor
- Western University
- Wilfrid Laurier University
- York University

**Comment by SteelWagstaff** [comment]
No reply yet from univ.cc, but I did find this: https://github.com/endSly/world-universities-csv

**Comment by SteelWagstaff** [comment]
Tested and works as expected with Ontarian list.
