### ISSUE TITLE
add the "anchor" tool/in TinyMCE from pressbooks-textbook to pressbooks proper 

### ISSUE THREAD

**Issue by hughmcguire** [pressbooks/pressbooks#242]
Hi ned, one more tinymce request ... the anchor tool from Pressbooks-Textbook TinyMCE implementation. This can go with the other "advanced" tools in the TinyMCE toolbar.

Small, but a priority.

**Comment by hughmcguire** [comment]
Priority on this pls

**Comment by greatislander** [comment]
This is ready to go—just waiting for my pull request https://github.com/BCcampus/pressbooks-textbook/pull/40 to prevent conflicts with Pressbooks Textbook.
