### ISSUE TITLE
Question: would allowing the the ncx (epub2) and/or toc.php (epub3) to include 2nd level TOC be desirable?

### ISSUE THREAD

**Issue by jflowers45** [pressbooks/pressbooks#243]
Not making a feature request here, but more of a question for your general ePub expertise.  We have an ePub with 2 level TOC and I was wondering whether the 2nd level is left out of the NCX/TOC in Pressbooks by design (maybe it's considered too long/bad format) or if that would be a good option to allow our users if we were able to code it in.  

Thanks!

**Comment by greatislander** [comment]
Hi @jflowers45—I believe this may have been an omission on my part rather than an intentional one. I will look into this. Agreed that it would be good to have if possible.

**Comment by jflowers45** [comment]
@greatislander cool, good to know.

**Comment by hughmcguire** [comment]
yes pls.
