### ISSUE TITLE
Improve display of admin menus for users on narrow mobile devices

### ISSUE THREAD

**Issue by SteelWagstaff** [pressbooks/pressbooks#2438]
When viewport is 320 pixels wide some content and functionality is cut off. 
- [x] Organization options and checkboxes on the Organize page
![Screenshot from 2021-10-12 16-02-13](https://user-images.githubusercontent.com/13485451/137040334-5dc05905-82b8-4900-8aac-741f3f0bba04.png)
- [x] table header on the Contributors page. 
![Screenshot from 2021-10-12 16-02-35](https://user-images.githubusercontent.com/13485451/137040407-ffcb7661-c554-4b25-a9f9-2dc8f509633b.png)
- [ ] some inputs on the Edit Book Information page require horizontal scrolling
![Screenshot from 2021-10-12 16-02-44](https://user-images.githubusercontent.com/13485451/137040416-9dca1824-731e-4499-ab14-4922491868e4.png)
- [ ] content on the Theme Options page is cut off. 
![Screenshot from 2021-10-12 16-03-05](https://user-images.githubusercontent.com/13485451/137040421-fd8049aa-ab6e-46dc-97f7-fe6e2f412429.png)
- [x] content on the Contact Us page is cut off
![Screenshot from 2021-10-12 16-02-55](https://user-images.githubusercontent.com/13485451/137040439-dc42019e-d3a5-41d5-ac31-dad5b1a52037.png)

**Comment by greatislander** [comment]
@SteelWagstaff: the content on the theme options page is cut off because Select2 sets a minimum width on the custom combobox element of 412px (see https://github.com/pressbooks/pressbooks/issues/2436).

**Comment by greatislander** [comment]
I've opened PRs for all of the items in this issue except for those which will be addressed by replacing Select2. If #2963 and https://github.com/pressbooks/pressbooks-aldine/pull/380 are approved and merged, I think this issue can be closed.
