### ISSUE TITLE
[Hackathon] - Export introduction front matter in EPUB and XHTML

### ISSUE THREAD

**Issue by richard015ar** [pressbooks/pressbooks#2443]
From items pending in the export hackathon: https://github.com/pressbooks/pressbooks/issues/2425

Inspect and fix the front matter export action. 
When the front matter is an introduction type those are listed in the index in EPUB and XHTML (PDF) but are not exported.

See:
- https://github.com/pressbooks/pressbooks/blob/exportHackathon-friday/inc/modules/export/epub/class-epub.php#L1573
- https://github.com/pressbooks/pressbooks/blob/exportHackathon-friday/inc/modules/export/xhtml/class-xhtml11.php#L1317

**Comment by arzola** [comment]
I tested this on the experimental branch, front/back matters are being rendered properly
