### ISSUE TITLE
Large tables extend beyond body of content

### ISSUE THREAD

**Issue by sswettenham** [pressbooks/pressbooks#245]
Wordpress 4.3
Pressbooks Version 2.7.1
PressBooks Textbook Version 1.2.15

-------------
Visit Site display extends beyond body of text:
![html-table_1_lg](https://cloud.githubusercontent.com/assets/360534/9559543/00d945b6-4dc3-11e5-8a6d-71ad6b69f159.png)
 
EPUB display cuts off table content:
![epuf-table_1_lg](https://cloud.githubusercontent.com/assets/360534/9559545/188b4470-4dc3-11e5-8a39-6ed86a4da9ab.png)

No issue with mPDF rendering
![pdf-table_1_lg](https://cloud.githubusercontent.com/assets/360534/9559553/3f677618-4dc3-11e5-8662-80b45c28fd02.png)
-------------
PRESSBOOKS . COM site outputs Visit Site display correctly as a horizontal scroll:
![2015-09-13_11-03-42](https://cloud.githubusercontent.com/assets/360534/9839261/1432a50e-5a74-11e5-88b7-5d0c48fe8b95.png)
-------------

Research links:
Responsive Data Tables - https://css-tricks.com/responsive-data-tables/
How to Create Responsive Tables in WordPress - http://exisweb.net/responsive-tables-in-wordpress
10+ Solutions for Responsive Data Tables - http://exisweb.net/responsive-table-plugins-and-patterns

-------------
Workaround for epub seems to be converting large tables into images with link to larger content.

**Comment by sswettenham** [comment]
The following appears to be a potential solution:

Themes > Editor > Open Textbooks > style.css > #content table {

CHANGE display:table to block

**Comment by greatislander** [comment]
@sswettenham Please refrain from opening duplicate issues—I see you closed your previous issue but this could have been addressed there. Also, are you using the Open Textbooks theme? If so this should be posted in https://github.com/BCcampus/pressbooks-textbook.

**Comment by sswettenham** [comment]
Thank you for the feedback
I see large tables display as a critical issue in academic content publishing (posted since Aug. 6, 2015) but there was no solution (in particular for theme) so tried a different presentation/approach.   From my understanding, the current epub format cannot display large tables correctly.  CampusBC open textbooks appear to use images rather than original text to display large tables.  I have recreated the issue on pressbooks-textbook as per your direction; however I believe this is a two part issue for large tables - theme and export format. I am still researching text rendering of large text tables in epub format but not overly optimistic of a solution.
