### ISSUE TITLE
Improve styling for components which no longer use heading elements

### ISSUE THREAD

**Issue by SteelWagstaff** [pressbooks/pressbooks#2452]
Previously, the title page & page headers (in the PDF) used heading elements improperly. We also wrapped chapter numbers in H3 elements. We have replace these in our Blade templates with the appropriate paragraph or span tags. Now we need to make sure that we adjust styles in Buckram and other themes so that we don't break the appearance of export files.

See Title page in EPUB: https://github.com/pressbooks/pressbooks/blob/9dcbdce9958422d564096778cab17091dd0a1cc2/inc/modules/export/epub/class-epub201.php#L1060-L1084

Title page in XHTML: https://github.com/pressbooks/pressbooks/blob/9dcbdce9958422d564096778cab17091dd0a1cc2/inc/modules/export/xhtml/class-xhtml11.php#L1018-L1044

Improperly used heading elements in XHTML file: 
*  https://github.com/pressbooks/pressbooks/blob/9dcbdce9958422d564096778cab17091dd0a1cc2/inc/modules/export/xhtml/class-xhtml11.php#L1365-L1370
* https://github.com/pressbooks/pressbooks/blob/9dcbdce9958422d564096778cab17091dd0a1cc2/inc/modules/export/xhtml/class-xhtml11.php#L1111
* https://github.com/pressbooks/pressbooks/blob/9dcbdce9958422d564096778cab17091dd0a1cc2/inc/modules/export/xhtml/class-xhtml11.php#L1319
* https://github.com/pressbooks/pressbooks/blob/9dcbdce9958422d564096778cab17091dd0a1cc2/inc/modules/export/xhtml/class-xhtml11.php#L1435
* https://github.com/pressbooks/pressbooks/blob/9dcbdce9958422d564096778cab17091dd0a1cc2/inc/modules/export/xhtml/class-xhtml11.php#L1440
* https://github.com/pressbooks/pressbooks/blob/9dcbdce9958422d564096778cab17091dd0a1cc2/inc/modules/export/xhtml/class-xhtml11.php#L1625
* https://github.com/pressbooks/pressbooks/blob/9dcbdce9958422d564096778cab17091dd0a1cc2/inc/modules/export/xhtml/class-xhtml11.php#L1529-L1533
* https://github.com/pressbooks/pressbooks/blob/9dcbdce9958422d564096778cab17091dd0a1cc2/inc/modules/export/xhtml/class-xhtml11.php#L1658-L1663
* All uses of H6 in the XHTML file

Several themes make reference to h2 elements and not just their class name. For example: https://github.com/pressbooks/pressbooks-book/blob/dev/packages/buckram/assets/styles/components/section-titles/_chapters.scss. Fix this.

**Comment by arzola** [comment]
Review span styling inside of the TOC elements

**Comment by arzola** [comment]
This would require to update the following child themes I would create a PR in each repo

pressbooks/pressbooks-lewis
pressbooks/pressbooks-kolbert
pressbooks/pressbooks-cleary
pressbooks/pressbooks-bukowski
pressbooks/pressbooks-andreesseen
