### ISSUE TITLE
mPDF  Display cover image size dependant

### ISSUE THREAD

**Issue by ghost** [pressbooks/pressbooks#246]
Noteworthy that http://guide.pressbooks.com/chapter/how-to-design-your-book-cover/ recommends safe minimum dimensions: 666x1000px.  However, Book Info states "Your cover image should be 625px on the shortest side." ...which is critical in having a cover page in PDF.  Original size of 1275 × 1650 pixels did not display cover page in PDF.

**Comment by greatislander** [comment]
@hughmcguire—which is correct, the Guide or the Book Info page? This needs your attention I think.

**Comment by greatislander** [comment]
Actually, @sswettenham—it is quite possible that this has not been implemented fully in mPDF yet. Please be aware that Pressbooks has been developed for the past several years with Prince as the sole export method for PDF. @bdolor and others recently implemented mPDF export as a minimum viable product and there is a lot we still want to do to ensure that it supports all the features as our Prince export routine. The Guide's instructions for PDF refer specifically to Prince. I hope this clarifies—but we will look into this for you.

**Comment by hughmcguire** [comment]
The cover image in pressbooks is only used for epub mobi. @greatislander the book info page should be updated to reflect guide. Mpdf is an experimental mvp output devd by @bdolor ... Pull requests likely welcomed

**Comment by sswettenham** [comment]
Pressbooks Version 2.7.1
I currently use the cover image in mobi, epub, and pdf (via mPDF).  Works fine only if I follow exactly as directed in Book Info > Cover Image > Your cover image should be 625px on the shortest side.

**Comment by hughmcguire** [comment]
@greatislander can we move these mPDF issues out of Pressbooks?
