### ISSUE TITLE
Replace loadTemplate with blade templates

### ISSUE THREAD

**Issue by arzola** [pressbooks/pressbooks#2460]
As part of the epub/html modernization we want to replace loadTemplate with blade templates to have the HTML templating unified

We are using the following approach

```
<?php
\Pressbooks\Utility\put_contents(
			$this->tmpDir . "/EPUB/$filename",
			$this->loadTemplate( $this->dir . '/templates/epub201/html.php', $vars )
		);
```

We want to replace by the following

```
<?php
\Pressbooks\Utility\put_contents(
			$this->tmpDir . "/EPUB/$filename",
			$this->blade->render( 'export/html', $vars )
		);
```

**Comment by richard015ar** [comment]
Something we agreed in the dev team: it is a nice to have but not mandatory to achieve the sprint goals.
