### ISSUE TITLE
mPDF bookmarks display numeric in front of title

### ISSUE THREAD

**Issue by ghost** [pressbooks/pressbooks#247]
Example bookmarks with numbers in front of title:
![bookmarks](https://cloud.githubusercontent.com/assets/360534/9848103/65b297e4-5ade-11e5-8c42-3defab3c6c27.png)

Can the numerics be removed ?

**Comment by greatislander** [comment]
@bdolor Do you know how this numbering could be removed off the top of your head? I could dig but I expect you know better :)

**Comment by bdolor** [comment]
Just so I'm clear — the screenshot above is from a PDF client that generates a display of the values of bookmarks within the pdf file? 

[This is the line](https://github.com/pressbooks/pressbooks/blob/dev/includes/modules/export/mpdf/class-pb-pdf.php#L502) that starts a sequential numeric process that is placed in front of the title as the concatenated value of a bookmark. I gather from the method description that it was an inexpensive way to avoid collisions (two bookmarks with the same value).

**Comment by sswettenham** [comment]
Yes the above screenshot is from a PDF client - specifically Apple Preview table of contents, but also the same with Adobe Acrobat bookmarks.  I suppose if there was a space, dash, or underscore between numeric and words would help clarify bookmark titles.

**Comment by hughmcguire** [comment]
Possibly a constraint in mpdf CSS support ... Some epub rendering has same problem. 
Need support of ::before pseudoelement

**Comment by hughmcguire** [comment]
@greatislander can we move these mPDF issues out of Pressbooks?
