### ISSUE TITLE
Create a list of testing/clonable books

### ISSUE THREAD

**Issue by arzola** [pressbooks/pressbooks#2479]
Adding new features to PB and test them is hard, having some books with different front-matters/options could be a great idea to have to avoid spending a lot of time creating empty books with new content to test

Right now we've been using https://jctestbook.textopress.com/

If there are no books, create some example books with different conditions in the integrations network

* Different front/back matters
* Different theme options, sizes, on/off authors at the end of each chapter, etc...

DEFINITION of DONE
- [x] Set of books created (see comments)
- [x] Document explaining what has been done & proposal for how to use them
- [ ] Agreement from whole team on this document

**Comment by SteelWagstaff** [comment]
This might be a good first issue for @tw77 ?

**Comment by arzola** [comment]
Thomas ideas

with all front matter types 
with all back matter types
with two-level TOC
without two-level TOC
with “About the Author” and attributions at the end of each chapter
without “About the Author” or attributions at the end of each chapter
with section-level license on TOC in export formats
with section-level license at end of chapter in export formats
maximum display of attributions and licenses
large font size (PDF)
bigger margins (PDF)
footnotes displayed as chapter endnotes instead (PDF)

**Comment by SteelWagstaff** [comment]
Steel will follow up with Thomas to create these books and document what we've done and how they should be used.

**Comment by SteelWagstaff** [comment]
Test book used in EPUB/PDF tests: https://integrations.pressbooks.network/newepubtest

**Comment by SteelWagstaff** [comment]
See https://docs.google.com/document/d/199uO8oC0J07CMnRMhe4gm-ebXfdLzSKI9Tn5kKFPDMs/edit

**Comment by tw77** [comment]
Discussed with Steel, I'll add to the main [Test Reference](https://integrations.pressbooks.network/testreference/) book:

- two additional parts, one of them invisible, with two to three chapters per part
- for each part, one or more chapters containing H1 headers
- H5P, Tablepress, Hypothesis used in the book
- chapter subtitles used
- another glossary term
- a reviewer in Book Info
- a custom copyright notice
- Other Service URL filled in on the Publish page

Other books in the [list](https://docs.google.com/document/d/199uO8oC0J07CMnRMhe4gm-ebXfdLzSKI9Tn5kKFPDMs/edit) (linked in the previous comment) are approved
