### ISSUE TITLE
UI enhancement - Export Defaults

### ISSUE THREAD

**Issue by sswettenham** [pressbooks/pressbooks#248]
I find the export defaults to be less useful preset to enable than disabled. As per example...
![export-defaults](https://cloud.githubusercontent.com/assets/360534/9876026/34c20c98-5bb3-11e5-9953-5a794daf1e3a.png)

I would prefer to select what I need changed rather than have to constantly remember to deselect with every page refresh.

Thanks,

**Comment by greatislander** [comment]
This is something I've been considering. To be discussed with @hughmcguire. Another idea I had was that we could allow users to determine which export formats would be selected by default for their books under `Settings → Export`. Alternatively, export selections could be persistent—e.g. if the user selected only EPUB, this choice would be saved and would be reflected next time the user visits the Export page. In any case as someone who routinely has to test a single format by exporting it multiple times in a row I appreciate the need for some refinement here. I'm including this in the discussion of #250.

**Comment by connerbw** [comment]
Fixed in dev branch.
