### ISSUE TITLE
Administrator account password differs from network to book site levels

### ISSUE THREAD

**Issue by sswettenham** [pressbooks/pressbooks#252]
This is not fully researched but it has happened on an Administrator account that a password changed in the Network Admin level did not change at the Book site users level.  I changed the password at the Network Admin user level but this had no effect at the Book site user level for exactly the same administrator account.  However, when I changed the password at the Book site level, the administrator was able to login.  The administrator previously tried to change the password via the "forgot password" but nothing happened.
I suspect the aforementioned issue may be a result of using the Wordfence plugin or Pressbooks.  Not sure until tomorrow.  Thanks.

**Comment by nciske** [comment]
WordPress multisite has a common users table, so if it was truly changed, it should be changed everywhere. There is no separate login/password storage for a sub site (book) user, just a role on the sub (book) site.

Questions:

Did you also change the email at the same time? Some email changes (in multisite) get put in a queue and need to be verified via email before they get applied. Not sure if the password change gets queued up if done at the same time.

**Comment by greatislander** [comment]
@sswettenham This would not be a Pressbooks bug, as @nciske said. We don't do anything that would decouple user accounts between book and network users, if such a thing were even possible.

**Comment by sswettenham** [comment]
Thanks, this helps localize the issue to email queuing or Wordfence.
