### ISSUE TITLE
Interesting security FYI on visibility

### ISSUE THREAD

**Issue by sswettenham** [pressbooks/pressbooks#253]
Not an issue but rather interesting information display...
(Not sure if this is reproducible, but seems to work so far when I flush all web browser stuff)

1. Started Firefox 40.0.3
2. Logged into Pressbooks as Super admin.
3. Navigated to a book site > Book Info
4. Saved Page As...
5. Exited web browser and cleaned all cache, cookies, etc.
6. Restarted web browser
7. Dragged saved file Edit Book Information...html into web browser

8.The page displayed my username and entire Pressbooks network layout.  It did not auto log me in.

**Comment by greatislander** [comment]
This is, as you say, not an issue. When you "Save Page As" in any browser on any website, the rendered HTML contents of the page (which in this instance would include your username in the admin bar) are saved as a static HTML file. If you are logged in to GitHub and you choose "Save Page As", you will get an HTML file that includes your username in the top right hand corner. Is there a specific concern you have about this that requires the attention of the Pressbooks team?

**Comment by sswettenham** [comment]
No

Only an aside for enduser admins, if the sidebar and header were hidden upon save, content of the Information Book could be saved as a file without sensitive info.  In general, have changed workflow to avoid archiving admin webpages.

**Comment by greatislander** [comment]
If you are interested in a simple way to export the contents of the book information page, that is worth consideration as a feature request (although it is not on our roadmap right now). But unless I'm very much mistaken, this:

> if the sidebar and header were hidden upon save

…is impossible. When a user initiates a "Save As" action in a browser, a website can't intervene and prevent that from happening.

**Comment by sswettenham** [comment]
Yes well stated - a simple way to export the book information.
