### ISSUE TITLE
Bug accessing "Clone a book" as a new user added as a subscriber to a book

### ISSUE THREAD

**Issue by tw77** [pressbooks/pressbooks#2549]
### Description

Reported in [this ticket](https://pressbooks.zendesk.com/agent/tickets/8436) and replicated both on their network and on a test network:

A new user added to a network specifically via a book's user list -- as a subscriber to that book -- will not be able to access "Clone a book" in the "My Books" dropdown menu.  Instead they're brought to a page with a "Sorry, you are not allowed to access this page" message. That's at this URL: https://{domain}/{book}/wp-admin/admin.php?page=pb_cloner

But if this user navigates to the network Dashboard, away from the book they were added to, and _then_ navigates to "Clone a book" in the "My Books" dropdown menu, they can clone a book from there. The URL is different in this case: https://{domain}/wp/wp-admin/admin.php?page=pb_cloner

This bug only affects a new user added to a book as a subscriber.

### Steps to Reproduce

1. Add a new user to a book as a subscriber.
2. Log in as the new user.
3. Navigate to "My Books" or to the book that you were added to.
4. Navigate to "Clone a book" via the "My Books" dropdown menu.

**Expected behavior:** We're brought to the cloning tool.

**Actual behavior:** We see a "Sorry, you are not allowed to access this page" message.

**Comment by SteelWagstaff** [comment]
Can be fixed by adjusting capability here: https://github.com/pressbooks/pressbooks/blob/248d2bb198a5eb0c2858e7554f00427fe887863c/inc/admin/laf/namespace.php#L407
