### ISSUE TITLE
Favicon Customize Option

### ISSUE THREAD

**Issue by ghost** [pressbooks/pressbooks#255]
At one moment I thought I saw the Appearance -> Customize > Site Identity but it disappeared from the sidebar (perhaps during Wordpress or Pressbooks upgrade).  Now the only way to get it back is to use http:// domain / site / wp-admin / customize.php
Too bad it isn't visible anymore.

**Comment by sswettenham** [comment]
Really needs an show or hide option for this function.
Thanks,

**Comment by robmcclel** [comment]
Agreed.

**Comment by greatislander** [comment]
Moving this to https://github.com/pressbooks/pressbooks-book/issues/18
