### ISSUE TITLE
TOC Error on EPUB export

### ISSUE THREAD

**Issue by wexlerj** [pressbooks/pressbooks#2567]
I am getting a validation error on EPUB export. 

There was a recent update to the hosted PressBooks instance which I believe upped the EPUB validation version as I was not getting this error with the previous version.

The EPUB output file is attached. As the validation message indicates, the TOC is broken in the EPUB file. The TOC is fine in the PDF output.

This is the validation error information:

```
Array
(
    [time] => Sun Dec 26 02:42:30 2021
    [user] => jonathanwexler
    [site_url] => https://survivalintherelentlessnew.pressbooks.com/wp
    [blog_id] => 38875
    [theme] => Jacobs
)
ERROR(RSC-005): /srv/www/pressbooks.com/releases/20211221204719/web/app/uploads/sites/38875/pressbooks/exports/Survival-in-the-Relentless-New-1640486545.epub/EPUB/toc.xhtml(268,32): Error while parsing file: element "ol" incomplete; missing required element "li"
ERROR(RSC-005): /srv/www/pressbooks.com/releases/20211221204719/web/app/uploads/sites/38875/pressbooks/exports/Survival-in-the-Relentless-New-1640486545.epub/EPUB/toc.xhtml(298,32): Error while parsing file: element "ol" incomplete; missing required element "li"
ERROR(RSC-005): /srv/www/pressbooks.com/releases/20211221204719/web/app/uploads/sites/38875/pressbooks/exports/Survival-in-the-Relentless-New-1640486545.epub/EPUB/toc.xhtml(328,25): Error while parsing file: element "ol" incomplete; missing required element "li"

Check finished with errors
```
[EPUB-TOC-ERROR-JonathanWexler.zip](https://github.com/pressbooks/pressbooks/files/7776491/EPUB-TOC-ERROR-JonathanWexler.zip)

**Comment by SteelWagstaff** [comment]
Thanks for reporting @wexlerj. We'll try to fix for next release.

Initial testing found that the issue occurs in the toc.xhtml file. When a book includes visible parts which have content but do not include any chapters, we render an empty `ol`, which causes the validation issue. Here's where we'll need to make changes:  https://github.com/pressbooks/pressbooks/blob/51dce1a0387545602e5d5c1bda461261a993bff4/templates/export/epub/toc.blade.php#L13-L39

**Comment by omshivaprakash** [comment]
@SteelWagstaff Tried the above fix. But for the chapters without title - the error persists. Also - Disabling show title for the specific chapter also has no effect.

**Comment by SteelWagstaff** [comment]
@omshivaprakash thanks for noting the problem with chapters with blank/empty titles. We are tracking that problem in this ticket: https://github.com/pressbooks/pressbooks-book/issues/843 and will need to fix it separately from this issue.

**Comment by tw77** [comment]
Tested on Integrations and confirmed the fix for this issue is working. With "email me validation error logs on export" enabled, I exported EPUBs of books with: 
- an empty part
- a part with invisible chapters of all chapter types
- both of the above + parts with visible chapters

No errors came up on export. Exported files appear as they should. This is ready for next release.
