### ISSUE TITLE
fix PDF hyphenation in foreign languages (priority on German)

### ISSUE THREAD

**Issue by hughmcguire** [pressbooks/pressbooks#257]
Book language setting (in Book Info) should trigger Pressbooks to find the correct language hyphenation dictionary in PDF output. Currently this is not happening.

Priority on German.

**Comment by greatislander** [comment]
@hughmcguire When did it stop happening? It was working last month.

**Comment by greatislander** [comment]
Does the XHMTL `<body>` tag need a `lang` attribute? Is that the issue?

**Comment by connerbw** [comment]
Hi I am doing r&d.

Prince 10 has hyphenation fixes. So step 1 is upgrading.

Step 2 is I don't think Prince is using the built in German hyphenation when converting documents.

 + Our XTHML output, which prince uses to generate documents always puts English as the file.
  + @see: https://github.com/pressbooks/pressbooks/blob/dev/includes/modules/export/xhtml/class-pb-xhtml11.php#L461
 + The code that does enable Hyphenation only looks at a directory with one EN file in it
  + @see: https://github.com/pressbooks/pressbooks/blob/dev/functions.php#L174
 
Prince comes with several hypehenation dictionaries. Given the above, how can it be auto-determining that it should use German? I don't think it is.

**Comment by greatislander** [comment]
Hi @connerbw, I think you're right and I believe the solution is adding a `lang` attribute to the `<body>` element as per [here](http://www.princexml.com/forum/topic/1474/prince-and-hyphenation) (see comment by the user `bookdev`).

**Comment by connerbw** [comment]
Cool.

Also, FYI, Prince's hyphenation dictionaries are located here in

`/usr/lib/prince/hyph/*.*`

We wrote code that overrides this when a customer turns on Hyphens, here:

https://github.com/pressbooks/pressbooks/blob/dev/themes-book/pressbooks-book/functions.php#L1645

I don't remember why we did this. I think it's because a paying customer was not happy with English hyphenation so we improved it for that specific case, but by improving there we are not using Prince's built in dictionaries.

So in addition to the language we will have to undo, or improve our code as well.

**Comment by greatislander** [comment]
I think the way that `pb_get_hyphens_path` function works is that if there is no override hyphenation dictionary for the current book language (which would be the case for everything except English) it returns false, and thus:

https://github.com/pressbooks/pressbooks/blob/dev/themes-book/pressbooks-book/functions.php#L1650 

… also returns false, so we don't override Prince's built-in dictionaries. I could be wrong, but I had the same question when I was working on #100 and that was my impression.

**Comment by connerbw** [comment]
+1

**Comment by greatislander** [comment]
Good stuff.

**Comment by connerbw** [comment]
Ok. I pushed a change. It's based on Example 3 found in this spec example: 

 + http://www.w3.org/TR/WCAG20-TECHS/H57.html

We are exporting XHTML 1.1 so code like a lang attribute to <body> is invalid markup. Hopefully this is enough?

**Comment by greatislander** [comment]
Hm. Doesn't seem to have done anything.

In the first instance the language is set to German, in the second the language is set to English. No difference in hyphenation.

[Standardized-Test-Book-1443566043.pdf](https://github.com/pressbooks/pressbooks/files/4789/Standardized-Test-Book-1443566043.pdf)
[Standardized-Test-Book-1443566064.pdf](https://github.com/pressbooks/pressbooks/files/4790/Standardized-Test-Book-1443566064.pdf)

**Comment by hughmcguire** [comment]
do we have to make any changes to the paths in `prince/style/hyph.css` ?

**Comment by connerbw** [comment]
Can someone provide a list of words with bad breaks?

In my latest commit I am forcefully using the OpenOffice German hyphenation dictionary and, indeed, it is the same as the German output. 

Maybe that's right?

Please provide a list of German words that are currently hyphenating badly.

**Comment by connerbw** [comment]
Ok. Works for me now.

+ [English-Hyphens.pdf](https://github.com/pressbooks/pressbooks/files/4831/English-Hyphens.pdf)
+ [German-Hyphens.pdf](https://github.com/pressbooks/pressbooks/files/4832/German-Hyphens.pdf)

PS: 3rd party dictionary code doesn't work so I removed it.

**Comment by greatislander** [comment]
Deployed to production.
