### ISSUE TITLE
Add more information to institutions list

### ISSUE THREAD

**Issue by SteelWagstaff** [pressbooks/pressbooks#2595]
We have created an institutions list that contains a list of Ontarian schools/colleges here: https://github.com/pressbooks/pressbooks/blob/dev/symbionts/institutions/institutions.json

We should refine this list by adding two-level geographical organization: country and state/province, and adding a website field for each institution. We should also add more institutions, using data from https://carnegieclassifications.iu.edu/downloads/CCIHE2021-PublicData.xlsx, https://github.com/Hipo/university-domains-list-api + https://github.com/hipo/university-domains-list, https://github.com/endSly/world-universities-csv or https://github.com/hannep/world_universities 

Decisions:
- [x]  Create a two-level geographical structure for the list that includes Country -> Region (state/province, etc); e.g. 
```
country: "Canada" 
    regions: [ "Ontario
    institutions: [
```
- [x]  Each institution should have a code (Alpha-2 code for Country - Alpha-2 code for Region - ###): e.g. CA-ON-001; a name: "Algoma University"; and a URL: "https://algomau.ca/". Wherever possible, we should use ISO codes for countries/regions: https://en.wikipedia.org/wiki/ISO_3166-1 + https://en.wikipedia.org/wiki/ISO_3166-2
- [ ] When displaying the list of institutions to users in book info, we should display 
**Country / Region**
    - Institution 1
    - Institution 2
**Country**
    - Institution 1   
    - Institution 2
- [ ] #2607

Feature branch: https://github.com/pressbooks/pressbooks/tree/pb-2595-institutions

Steel will build a canonical spreadsheet to start with that will convert into a JSON file: https://docs.google.com/spreadsheets/d/1ddgBBmrbRbadbeazTUCboAgLGRr-kpvpxXxIh1rc-as/edit?usp=sharing

**Comment by SteelWagstaff** [comment]
Idea: what if we only load a subset of institutions based on a network setting (region/province, etc) and then give the user a 'load more' button?

**Comment by fdalcin** [comment]
I like the idea, specially once we have a huge institution list. We will need to setup a new input field I believe

**Comment by SteelWagstaff** [comment]
Institution field appears as expected when the eCampusOntario plugin is network activated. Institutions can be added, and display as expected on book home page, network catalog, etc. When the plugin is deactivated, the institutions field is no longer visible on book info, but institutions are present and display correctly on book home page and network catalog.

When a book with institutions is clone to a network which does not have the eCampuOntario plugin installed, institutions are displayed with their code rather than their name on the book homepage, though they're displayed correctly on the catalog page and in the filters. See:
![Screenshot from 2022-01-25 10-18-07](https://user-images.githubusercontent.com/13485451/151035688-cc2c7f1e-cf50-4d4c-9e2c-4585229cfc9f.png)
https://integrations.pressbooks.network/authorsdemo/

**Comment by SteelWagstaff** [comment]
There was a problem with the textopress bedrock being updated. Retested after making change there and feature works as expected!
