### ISSUE TITLE
Display part and chapter numbers - not turned off on TOC (PDF for print)

### ISSUE THREAD

**Issue by omshivaprakash** [pressbooks/pressbooks#2613]
### Description

Tried to turn off "Part and Chapter Numbers | Display part and chapter numbers" but continue to see "Main Body" displayed in TOC for PDF for print. 

### Steps to Reproduce

1.  Turn off Part and Chapter Numbers
2.  Export the PDF 
3.  Verify TOC

Tested with Jacob and dohnam themes

**Expected behavior:** 

In TOC we should not see the Part name

**Actual behavior:** 

Part name turned off

#### Browser

Platform: OS X
Browser Name: Chrome
Browser Version: 98.0.4758.66
User Agent String: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.66 Safari/537.36

#### WordPress Configuration

Network URL: https://
Network Type: Subdirectory
Version: 5.9
Language: en_US
WP_ENV: Not set
WP_DEBUG: Disabled
Memory Limit: 64M

#### Pressbooks Configuration

Version: 5.31.1
Book Theme: Jacobs
Book Theme Version: 1.2.1
Root Theme: Aldine
Root Theme Version: 1.12.0

#### Pressbooks Dependencies

Epubcheck: Installed
xmllint: Installed
PrinceXML: Installed
Saxon-HE: Installed

#### Must-Use Plugins

hm-autoloader.php: n/a
HMWP Ghost Loader: n/a
ManageWP - Worker Loader: n/a

#### Network Active Plugins

Adminimize: 1.11.7
Akismet Anti-Spam: 4.2.2
BM Custom Login: 2.3.2
Enable Media Replace: 3.6.3
Git Updater: 10.6.12
Git Updater - Gist: 1.1.0
Hide My WP Ghost: 6.0.13
ManageWP - Worker: 4.9.13
mPDF for Pressbooks: 3.3.1
Post Type Switcher: 3.2.1
Pressbooks: 5.31.1
Pressbooks Stats: 1.6.3
Translations for PressBooks: 1.2.7
WP QuickLaTeX: 3.8.6

#### Book Active Plugins

Adminimize: 1.11.7
Akismet Anti-Spam: 4.2.2
BM Custom Login: 2.3.2
Enable Media Replace: 3.6.3
Git Updater: 10.6.12
Git Updater - Gist: 1.1.0
Hide My WP Ghost: 6.0.13
ManageWP - Worker: 4.9.13
mPDF for Pressbooks: 3.3.1
Post Type Switcher: 3.2.1
Pressbooks: 5.31.1
Pressbooks Stats: 1.6.3
Translations for PressBooks: 1.2.7
WP QuickLaTeX: 3.8.6

#### Inactive Plugins

Git Updater - Gitea: 1.2.0
H5P: 1.15.4
Hypothesis: 0.6.0
TablePress: 1.14
Textbooks for Pressbooks: 4.3.1

#### Server Configuration

PHP Version: 7.4.27
MySQL Version: 5.7.36
Webserver Info: Apache/2.4.29 (Ubuntu)

#### PHP Configuration

Memory Limit: 256M
Upload Max Size: 128M
Post Max Size: 150M
Upload Max Filesize: 128M
Time Limit: 30
Max Input Vars: 1000
URL-aware fopen: On (1)
Display Errors: N/A

#### PHP Extensions

OPcache: Zend
XDebug: Disabled
cURL: Supported
cURL Version: 7.58.0
imagick: Installed
xsl: Installed

**Comment by tw77** [comment]
I see the Part name in a PDF export after "Display part and chapter numbers" is unchecked, but as far as I understand this option is intended to remove Part numbering, not Part names.
