### ISSUE TITLE
wp-nocaption routine not working, needed to wrap no-caption images... to enable proper styling in EPUB

### ISSUE THREAD

**Issue by hughmcguire** [pressbooks/pressbooks#263]
something to look at dac:

## Standard WordPress Behaviour
WordPress markup for images with captions wraps the image (and caption) in a `.wp-caption` div, generating something like the following: 

`<div id="attachment_295" style="width: 2394px" class="wp-caption aligncenter"><img class="size-full wp-image-295" src="http://standardtest.pressbooks.com/files/2015/10/Denison-big.jpg" alt="...." width="2384" height="2984" /> <p class="wp-caption-text">A caption about the things captions are about.</p> </div>`

However, default behaviour from WordPress does not wrap images without captions in a similar way, so we get the following in the case of an image (with no link):

`<p><img class="aligncenter size-full wp-image-294" src="http://standardtest.pressbooks.com/files/2015/10/Denison-small.jpg" alt="Denison-small" width="191" height="240" /></p>`

And this in the case of an image with a link:
`<p><a href="http://imagelink.com/image.jpg"><img class="aligncenter wp-image-294 size-full" src="http://standardtest.pressbooks.com/files/2015/10/Denison-small.jpg" alt="Denison-small" width="191" height="240" /></a></p>`

## The problem

The problem with the above is the following:
Certain ebook readers (including Apple's iBooks) do not recognize styling on an `img` tag (particularly for centering), and instead require the styling to happen on a wrapping div.

So, we could correctly style the `div`: `.wp-caption.aligncenter`

But we cannot correctly style the `img` tag: `img.aligncenter`

## The solution was.... 

The solution to this was to "force wrap" un-caption images in: `<div class="wp-nocaption">` with this function: 
https://github.com/pressbooks/pressbooks/blob/ede247eab59a624df095cc97044dd853df4992a7/includes/pb-media.php

This worked successfully.

## Unfortunately  .... 

Unfortunately, this is no longer working meaning that our image styling is ... broken, for both EPUB and PDF (since this was applied in PDF as well).  

## Possible solutions:

1. get `wp-nocaption` working again

2. force Pressbooks output to generate HTML5 tags `<figure>` and `<figcaption>` ... while properly incorporating the alignment classes of: `alignnone`, `aligncenter`, `alignright`, `alignleft`.

**Comment by hughmcguire** [comment]
fwiw I would lean towards `<figure>` tags.

**Comment by connerbw** [comment]
The fix is a regex that looks for \<p\> tag. The \<p\> tags are generated by the `wpautop` filter. This filter was moved to #priority 12 in fa1bd02fce37264f1bed12a420d353a31e13219e Therefore, we need to run our hack at $priority 13 (or higher) to get this working again.

**Comment by connerbw** [comment]
Went for option 1 (get wp-nocaption working again)

Will open ticket for 2 -- force Pressbooks output to generate HTML5 tags <figure> and <figcaption> ... while properly incorporating the alignment classes of: alignnone, aligncenter, alignright, alignleft.

**Comment by beckej13820** [comment]
@connerbw is there a regression of this in the latest version of pressbooks? I am working on exporting a book and images that are set to float right or left but don't have captions are not displaying properly. This old/closed issue came up as I was searching for open tickets..

**Comment by connerbw** [comment]
I doubt this issue is relevant. Maybe:

+ https://github.com/pressbooks/pressbooks-book/issues/252
+ https://github.com/pressbooks/pressbooks/pull/1684

But it's not a regression, it's a fix, and it's not recent, it was released in april.

I don't know of any reported problems from our customers about this.
