### ISSUE TITLE
EPUB export renders empty <div><!-- pb_fixme --> tags

### ISSUE THREAD

**Issue by connerbw** [pressbooks/pressbooks#2639]
### Description

Epub renders empty `<div><!-- pb_fixme -->` tags.

![image](https://user-images.githubusercontent.com/812192/153694997-0d18418c-8dbe-4731-993b-ac4fcead1570.png)

### For Developers

The problem is here: https://github.com/pressbooks/pressbooks/blob/38b69cb3b9ec488dd2ea0202e35c7f929ec1519e/inc/modules/export/epub/class-epub201.php#L1964-L1990

The html5 parser is supposed to be used like:

```php
$html5 = new HtmlParser();
$dom = $html5->loadHTML(...);
// ...
$html = $html5->saveHtml($dom);
```

Because its trying to render strict XHTML it instead does.

```php
$html5 = new HtmlParser();
$dom = $html5->loadHTML(...);
// ...
$html = $dom->saveXML( $dom->documentElement ); 
```

By not using `$html5->saveHtml($dom);` it missed doing this cleanup:
https://github.com/pressbooks/pressbooks/blob/38b69cb3b9ec488dd2ea0202e35c7f929ec1519e/inc/class-htmlparser.php#L73-L77

Either manually add the cleanup, or use HTML5 instead of XML? Not sure if this would affect CSS, because this would remove div wrappers that have been there for a while maybe.

### Steps to Reproduce

1. Export an ebub
2. Look at the html

**Expected behavior:** No pb_fixme tags

**Actual behavior:** pb_fixme tags

**Comment by SteelWagstaff** [comment]
Thanks for filing, @connerbw — we’ll look at this in next bug scrub.

**Comment by richard015ar** [comment]
I don't understand why we would need to add this: https://github.com/pressbooks/pressbooks/blob/38b69cb3b9ec488dd2ea0202e35c7f929ec1519e/inc/class-htmlparser.php#L44

It seems to be a legacy change that could be removed. I don't find in the code some use of this, so probably the best solution is just to remove this. 
I will wait for Steel to ask to Ned about this, probably he knows some reason of this.

**Comment by connerbw** [comment]
I think given this string html string:

```html
test<br>
```

The parser will fail. 

The parser expects the HTML to be wrapped in a root node, to be a a valid DOM.

Remove it, the tests will fail, and you can see the result?

**Comment by SteelWagstaff** [comment]
@tw77 This is ready for testing. To test, produce EPUB exports and inspect HTML to make sure that none of the `<div><!-- pb_fixme -->` tags are present inside of chapter content. Also check briefly to make sure that other HTML in the chapters appears valid. Can use HTML validator if desired (copy/paste contect into direct input option): https://validator.w3.org/

**Comment by tw77** [comment]
Tested with new EPUB exports from Integrations and can confirm that `<div><!-- pb_fixme -->` tags are no longer present inside of chapter content, vs. an earlier EPUB export of https://integrations.pressbooks.network/testreference/ where those empty tags were present. This fix is working and is ready for the next release.

Direct input of HTML of newly-exported chapters into https://validator.w3.org/ returns no errors save for known false positives with this validator ("Probable cause: Attempt to use an XML processing instruction in HTML"), which are not new. Chapters exported from before empty `<div><!-- pb_fixme -->` tags were dispensed with are validated identically.
