### ISSUE TITLE
Hide already supported languages on theme options page

### ISSUE THREAD

**Issue by greatislander** [pressbooks/pressbooks#264]
If a theme supports certain character sets out of the box, we want to let users know/prevent them from selecting it redundantly. (Re: #239.)

**Comment by hughmcguire** [comment]
problem: user may select language support, switch themes, then switch again.

or, select a theme with language support, then change themes to one without supported languages.

**Comment by greatislander** [comment]
I've thought of that, don't worry.

**Comment by greatislander** [comment]
@hughmcguire This is live. Try it out and see if it makes sense to you.
