### ISSUE TITLE
Overhaul the admin dashboard for users

### ISSUE THREAD

**Issue by SteelWagstaff** [pressbooks/pressbooks#2645]
As the pressbooks customer success manager, i'd like all Pressbooks users to have a better admin dashboard experience. 

See https://docs.google.com/document/d/1ddab0NO8kTcI0pp1PwO17EE7_suT7E1yWxkWz3SP8ZU/edit?usp=sharing for details.

**Comment by pb-amy** [comment]
Copy for all of the content is in here: https://docs.google.com/document/d/1nd2jcxRTBi_J87glwOCfC6lyuiKrCkfUJ1nOfSLDRl8/edit?usp=sharing
