### ISSUE TITLE
Add a "Contact your Network Manager" form on the admin dashboard

### ISSUE THREAD

**Issue by pb-amy** [pressbooks/pressbooks#2647]
### Description

As a regular user, I want to be able to contact my network manager when I have questions or problems. I would like the contact information to appear on my user dashboard.
<img width="1274" alt="Screen Shot 2022-02-15 at 2 20 39 PM" src="https://user-images.githubusercontent.com/61845107/154133456-c2526432-fc08-4aa4-8381-ee8978a6cb3b.png">

Network managers can enter a contact email on the Aldine Appearance module. Populate the contact link to update the email address.
<img width="302" alt="Screen Shot 2022-02-15 at 2 22 14 PM" src="https://user-images.githubusercontent.com/61845107/154133679-58275af1-49f3-4267-a1aa-9b275c2a3532.png">

Will need to prepare copy, location, and content of the box.

**Comment by pb-amy** [comment]
It would ideally look something like this.
<img width="594" alt="Screen Shot 2022-03-02 at 9 55 08 AM" src="https://user-images.githubusercontent.com/61845107/156398216-8bebe69e-6aa1-47f5-80c1-8af33ed69927.png">

A couple of notes:
1. Copy edits are welcome.
2. It should be somewhere near the bottom of the admin dashboard (should not be one of the first visible elements), but this will become more apparent later.
3. In the screenshot, you'll see that I added a "note to network managers". Is it possible to make this part visible only to network managers who are logged in?
4. Can we set an option so that if network managers de-populate / empty the contact email on the [aldine appearance module](https://integrations.pressbooks.network/wp/wp-admin/customize.php?return=%2Fwp%2Fwp-admin%2F"), this box will automatically disappear?

**Comment by SteelWagstaff** [comment]
Addressing with https://github.com/pressbooks/pressbooks/pull/2792
