### ISSUE TITLE
Feature Request: Option to disable comments on root site

### ISSUE THREAD

**Issue by marcusschiesser** [pressbooks/pressbooks#266]
Unregistered users can always leave comments on pages of the root site.
You can see that e.g. here:
http://www.turngeek.press/what-is-a-cloud-tutorial/
This behaviour might not be desired and should be disabled via an option in wp-admin

**Comment by connerbw** [comment]
You can already do this. It's a WP feature, not a Pressbooks problem?

### Step 1

![nobug-step-1](https://cloud.githubusercontent.com/assets/812192/10464886/1dfe9626-71ba-11e5-8ab3-05e6f2e30998.PNG)

### Step 2
 
![nobug-step-2](https://cloud.githubusercontent.com/assets/812192/10464887/1dfff232-71ba-11e5-960b-7915534f702f.PNG)

Regards,

**Comment by marcusschiesser** [comment]
ok, that works if you modify every single page. Thanks. But my feature
request was about a similar feature as you can find
for the book sites
at {bookname}/wp-admin/options-general.php?page=disable_comments_settings
There you can set a default behaviour for all pages of the site.

On Wed, Oct 14, 2015 at 2:54 AM, Dac Chartrand <notifications@github.com>
wrote:

> You can already do this. It's a WP feature, not a Pressbooks problem?
> Step 1
>
> [image: nobug-step-1]
> <https://cloud.githubusercontent.com/assets/812192/10464886/1dfe9626-71ba-11e5-8ab3-05e6f2e30998.PNG>
> Step 2
>
> [image: nobug-step-2]
> <https://cloud.githubusercontent.com/assets/812192/10464887/1dfff232-71ba-11e5-960b-7915534f702f.PNG>
>
> Regards,
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pressbooks/pressbooks/issues/266#issuecomment-147812953>
> .
>



-- 
Marcus Schiesser
Email: mail@marcusschiesser.de

http://www.marcusschiesser.de
