### ISSUE TITLE
Unwanted numbering in EPUB table of contents

### ISSUE THREAD

**Issue by ghost** [pressbooks/pressbooks#2666]
TOC in EPUB exports sometimes include unwanted numbering. The affected user wrote in to say that they thought that "ordered lists are being added after the level 1 (or headings) of the chapter names, and these lists are never being closed."

To reproduce this bug:
1. Uncheck "Display part and chapter numbers" in a book's Theme Options > Global Options.
2. Give multiple chapters the chapter type of either "Standard" or "No chapter type."
3. Export an EPUB.

The exported TOC looks like this:
<img width="134" alt="Screen Shot 2022-04-12 at 1 11 33 PM" src="https://user-images.githubusercontent.com/44182629/163045448-b50f459b-d99c-4544-8a81-9f6c20ebac26.png">

Reported by a different user here (internal PB reference only): https://pressbooks.zendesk.com/agent/tickets/9856

To fix, we should improve the conditional here: https://github.com/pressbooks/pressbooks/blob/de44864fa28dd520d31295bfddc4ed0b0b815b61/inc/modules/export/epub/class-epub.php#L1932-L1937 to make sure we check whether theme options for display part and chapter number is turned off.

**Comment by tw77** [comment]
I'm able to replicate this bug with these steps:

1. Uncheck "Display part and chapter numbers" in a book's Theme Options > Global Options.
2. Give multiple chapters the chapter type of either "Standard" or "No chapter type."
3.  Export an EPUB.

The exported ToC looks like this:
<img width="134" alt="Screen Shot 2022-04-12 at 1 11 33 PM" src="https://user-images.githubusercontent.com/44182629/163045448-b50f459b-d99c-4544-8a81-9f6c20ebac26.png">

Reported by a different user here (internal PB reference only): https://pressbooks.zendesk.com/agent/tickets/9856

**Comment by SteelWagstaff** [comment]
We need to improve the conditional here: https://github.com/pressbooks/pressbooks/blob/de44864fa28dd520d31295bfddc4ed0b0b815b61/inc/modules/export/epub/class-epub.php#L1932-L1937 to make sure we check whether theme options for display part and chapter number is turned off.

**Comment by SteelWagstaff** [comment]
See #2736 for more details on this issue

**Comment by wexlerj3** [comment]
I am not a Github expert but hope this all means the bug is being fixed. Thanks.

**Comment by SteelWagstaff** [comment]
Tested and working as expected on integrations. Ready for release.
