### ISSUE TITLE
As a user exporting EPUB3, I want to convert captioned images to HTML5 <figure> and <figcaption>

### ISSUE THREAD

**Issue by connerbw** [pressbooks/pressbooks#267]
As a user exporting EPUB3, I want to convert captioned images to HTML5 <figure> and <figcaption>

More info in ticket #263

**Comment by hughmcguire** [comment]
consider whether HTML5 should be our default output ... (which would feed into Prince as well).

**Comment by hughmcguire** [comment]
should we close one of these tickets as a dupe? 
this one or #342

**Comment by connerbw** [comment]
Missing details, specification, etc.
If we do this let's open a new ticket with a reasoned approach.
(no place holders)
