### ISSUE TITLE
Fix automated .pot translation update bot

### ISSUE THREAD

**Issue by arzola** [pressbooks/pressbooks#2686]
The new GitHub action which automatically updates our `.pot` files when relevant changes have been made is stripping some of the dynamic translations and comments. See https://github.com/pressbooks/pressbooks/commit/e341b3a92838f061bc8e77c1a2c690d98b1e84b5 for an example.

## Notes
the command we run manually is `wp pb make-pot . languages/<plugin>.pot --exclude="vendor,symbionts" --headers='{"Report-Msgid-Bugs-To":"https://github.com/pressbooks/<plugin>/"}'` or `wp pb make-pot . languages/<theme>.pot --exclude="vendor" --headers='{"Report-Msgid-Bugs-To":"https://github.com/pressbooks/<theme>/"}'`

The current action runs `wp pb make-pot . languages/pressbooks.pot --domain=pressbooks --slug=pressbooks --package-name="Pressbooks" --headers="{\"Report-Msgid-Bugs-To\":\"https://github.com/pressbooks/pressbooks/issues\"}"`

The action output includes several PHP Warnings: `strpos() expects parameter 1 to be string, object given in /home/runner/.wp-cli/packages/vendor/wp-cli/i18n-command/src/MakePotCommand.php on line 683`

There is only one use of strpos() in MakePotCommand.php: https://github.com/wp-cli/i18n-command/blob/fdc6e1548fa5146dc32718257c495962430dfeb1/src/MakePotCommand.php#L728-L741. The line reference differs from latest branch, which makes me think we're using the version of wp-cli _before_ this commit: https://github.com/wp-cli/i18n-command/commit/72f57f0c7461f8b84d8abd1829248f03649dd60e

Will try updating `wp package install wp-cli/i18n-command:2.2.8` to see what difference that might make

**Comment by SteelWagstaff** [comment]
Recent changes are working better, but now exclude blade template references. See https://github.com/pressbooks/pressbooks/commit/dfc68dc8f4e32af75ad57b8e46bcc765ed547446

![Screenshot from 2022-03-10 15-03-29](https://user-images.githubusercontent.com/13485451/157769788-31a4e7b3-209e-4c79-bc7a-a30681ee55db.png) and

**Comment by SteelWagstaff** [comment]
@arzola shared this in internal Slack, which is worth keeping an eye on? https://github.com/wp-cli/i18n-command/pull/304. We may want to resolve https://github.com/pressbooks/pressbooks/issues/1734 as well at some point soon

**Comment by ho-man-chan** [comment]
Looking at the latest release pot files in [pressbooks/pressbooks ](https://github.com/pressbooks/pressbooks/commit/0871b3eed4989769a94be1312060e41af46643bc#diff-64002f406e016d67acbfc92388741e7f70a3d36a0621d083ead382b2e061f59bR640),
the blade comments still persist.

**Comment by arzola** [comment]
@SteelWagstaff I downloaded the .POT generated by the PR and it seems working as expected, it seems the comments are optional and doesn't affect the translation behaviour at the end the translation function will do a lookup with the msgid string anytime the __ translation function is invoked

Also I read the following https://www.gnu.org/software/gettext/manual/html_node/PO-Files.html
