### ISSUE TITLE
Feature Request: Add repetitive text for each chapter

### ISSUE THREAD

**Issue by marcusschiesser** [pressbooks/pressbooks#269]
With our site we have the use case to add at the end of each chapter the same text. 
Right now we are using copy'n'paste which is of course a burden.
Therefore there should be a feature to add such repetitive texts automatically.

Two ideas how to do that:
1. It should be possible to define a snippet per book that is added automatically at the end of each chapter - I assume people want to add repetitive text usually at the end of a chapter, e.g. a copyright notice or in our case a message board. Doing so it would also be cool to add a possibility to add a snippets in other prominent page positions (e.g. header tag, before the chapter text, etc.) - that way, using the header tag, we could for example easily add google analytics
2. Define snippets somewhere in the backend. These snippets could then be reused by calling [snippet_x], e.g. [snippet_1] displays the content of the first snippet.

**Comment by colomet** [comment]
Maybe what is it necesary is to make one book the base book of the website. Then, all the configurations in that book it will be available in all the books of the installation.
It will be nice to control editor name, city of the company and other details from one centralised place.

**Comment by greatislander** [comment]
@colomet Pressbooks is used in a variety of environments, some of which are individuals authoring books for self-publication, some of which are universities, some of which are publishing companies—that is a solution that would only work for some of those use cases and as such we won't be implementing it.

**Comment by colomet** [comment]
Yes, that´s way one university would love to have the addres and information about the university in all the pages, also the license of the content or other information without let the teachers or students do it. Have to be a choice between centraliced or each book independent. Maybe the book configuration could overwrite the platform configuration if is it different. Anyway it is not really important.

**Comment by greatislander** [comment]
Our friend @monkecheese at @lumenlearning contributed a filter hook called `pb_append_chapter_content` (https://github.com/pressbooks/pressbooks/pull/399) which fulfills this exact function. In order to add repetitive content to the chapters of a book on a site-wide basis, you can do something like this:

```
function my_add_repetitive_content($value) {
  return 'Something the goes at the end of every chapter.';
}

add_filter('pb_append_chapter_content', 'my_add_repetitive_content');
```
