### ISSUE TITLE
Update migrated database IAC

### ISSUE THREAD

**Issue by ho-man-chan** [pressbooks/pressbooks#2714]
- [x] Add mariadb in terraform
- [x] Add ansible to handle multiple db 
- [x] Add user creation

TODO:

ca-central
- [x] Track terraform state in production
- [x] Make sure actual production state is reflected in IaC

us-east
- [x] Track terraform state in production
- [x] Make sure actual production state is reflected in IaC

ap-southeast
- [x] Track terraform state in production
- [x] Make sure actual production state is reflected in IaC

**Comment by SteelWagstaff** [comment]
@ho-man-chan what else does this issue need before closing?

**Comment by SteelWagstaff** [comment]
Production needs to have their terraform state tracked.

**Comment by cmurtagh** [comment]
ca-central-1 now has DB config in IaC.

**Comment by ho-man-chan** [comment]
Reviewed all region's terraform databases. The states are captured. Certain defined IAC cannot be set unless we refractor certain terraform code outside of scope. We will refractor it in the future.
