### ISSUE TITLE
Introduce Unit Testing

### ISSUE THREAD

**Issue by connerbw** [pressbooks/pressbooks#272]
WP-CLI makes writing Unit Tests for PB pretty trivial. I was playing around with it locally and it works pretty great.
- https://github.com/wp-cli/wp-cli/wiki/Plugin-Unit-Tests

We should start unit testing and aim for reasonable code coverage. We should refactor code that isn't testable into something that is. This will improve code quality and reliability.

More info:
- http://voceplatforms.com/2014/09/unit-testing-for-wordpress-part-1-the-setup/
- http://voceplatforms.com/2014/09/unit-testing-for-wordpress-part-2-writing-unit-tests/
- http://voceplatforms.com/2014/09/unit-testing-for-wordpress-part-3-annotations-coverage-reports-and-a-real-world-example/

Some books on writing testable code:
- https://leanpub.com/grumpy-testing
- http://amzn.to/1NN0btw

**Comment by hughmcguire** [comment]
does this ticket need to stay open? @greatislander

**Comment by greatislander** [comment]
Yes, it's gonna hang in there until we hit 80% coverage. Currently at 12%.

**Comment by greatislander** [comment]
Changed my mind. 30% is good enough for us to close this, I think.
