### ISSUE TITLE
Continuing TOC Problems in EPUB Output

### ISSUE THREAD

**Issue by wexlerj3** [pressbooks/pressbooks#2736]
I reported a bug several months back that the bump up in epub versions was breaking the table of contents of one particular PressBooks book I work on.

The issues is that there are some parts that have not content in them and this was messing up the hierarchy of the tags and the whole book was not compiling at the time.

That bug was fixed only partially - I will try and reference the original bug when I edit this now one.

The bug which still exists is that now every level 2 in the book TOC is precluded with a "1.".

I basically understand roughly what is happening: ordered lists are being added after the level 1 (or headings) of the chapter names, and these lists are never being closed.

Upon thinking about his for a second, what should be added is unordered lists so this is definitely a bug that must be fixed.

I am a long term paying customer so expect this to be looked at for the next release.

**Comment by wexlerj3** [comment]
You can see what I am talking about by looking at the TOC of my book on the Amazon.ca site:

[Book on Amazon - check out a Preview of the Book to see the TOC Problem](https://www.amazon.ca/Survival-Relentless-New-Elon-Musk-ebook/dp/B09XHZDVKN/ref=sr_1_2?crid=21ZCDMA48SVH2&keywords=survival+in+the+relentless+new&qid=1649533129&sprefix=survival+in+the+relentless+new%2Caps%2C278&sr=8-2)

**Comment by SteelWagstaff** [comment]
Thanks @wexlerj3 -- we've investigated and can reproduce this problem. See https://github.com/pressbooks/pressbooks/issues/2666 for details. Hope to have it fixed in a future release.

**Comment by wexlerj3** [comment]
Great thanks so much!
________________________________

**Comment by SteelWagstaff** [comment]
Closing in favor of https://github.com/pressbooks/pressbooks/issues/2666
