### ISSUE TITLE
Reduce amount of directories created in Uploads dir by Sass process

### ISSUE THREAD

**Issue by connerbw** [pressbooks/pressbooks#275]
Current process creates compiled CSS files in multiple places. Some optional, some not. It would be better if they were all in the same place, with better names. For example, change:

```
/editor/editor.css
/export-css/prince.css
/export-css/epub.css
/global-typographt/_global-font-stack.scss
```

To:

```
/scss/required/editor.css
/scss/required/_global-font-stack.scss
/scss/debug/prince.css
/scss/debug/epub.css
```

Or better names.

**Comment by greatislander** [comment]
So this is what I'm going for:

```
/css/editor.css// editor stylesheet
/css/style.css // webbook stylesheet
/css/debug // debug stylesheets
/css/scss // required scss files (currently just _global-font-stack.scss)
```

I need to fix the web book stylesheets for the bundled themes. They haven't been updated yet (I did all the ones in the private themes repository).
