### ISSUE TITLE
Update to the new version of Thema, v1.5

### ISSUE THREAD

**Issue by tw77** [pressbooks/pressbooks#2780]
Pressbooks ships with an open source subject taxonomy called [Thema](https://www.editeur.org/151/Thema) (by EDitEUR). The latest version of Thema (v1.5) was released on April 22, 2022 and includes 177 new core subject categories and 220 new qualifiers while retaining backward compatibility with previous versions. To give users to access to this expanded range from the Book Info page, we should update to Thema v1.5.

For internal reference, we've heard of faculty looking to use subject terms that are only available in v1.5 in this ticket: https://pressbooks.zendesk.com/agent/tickets/10319

**Comment by SteelWagstaff** [comment]
Tested -- new terms are available on integration2.pressbooks.network and feature works as expected. Noticed a bug, which I think may have been preexisting: https://github.com/pressbooks/pressbooks/issues/2901

**Comment by richard015ar** [comment]
@tw77 will mention this during sprint review.
