### ISSUE TITLE
Add UK higher ed institutions to our list of institutions

### ISSUE THREAD

**Issue by tw77** [pressbooks/pressbooks#2866]
### Description

University of Sussex is not yet listed in the drop-down menu of available selections for the Institutions field in the Book Info page on Pressbooks networks. They've requested that they be added to this list as they'd like to include the Institutions field in metadata for upcoming books on https://openpress.sussex.ac.uk/.

We should probably add entries for all higher ed institutions in the UK (and Europe, Asia, Africa, South America, eventually). For now we can start with the UK?

**Comment by SteelWagstaff** [comment]
Will need to add institutions from England/UK here: https://github.com/pressbooks/pressbooks/blob/dev/symbionts/institutions/institutions.json

**Comment by SteelWagstaff** [comment]
@tw77 I've adding institutions from the UK, Ireland, and New Zealand. Should be available for testing on integrations shortly.

**Comment by SteelWagstaff** [comment]
Tested and working as expected on integrations. Ready for release. Found a prexisting issue with filtering institutions in the catalog when the institution title includes a comma in its name that i'll file separately.

**Comment by SteelWagstaff** [comment]
Tested on integrations. Works as expected and is ready for release. Found a preexisting bug while testing https://github.com/pressbooks/pressbooks-network-catalog/issues/203
