### ISSUE TITLE
Import .docx with multiple images results in only one image repeatedly uploaded

### ISSUE THREAD

**Issue by rootl** [pressbooks/pressbooks#288]
Greetings,

We have several .docx manuscripts with multiple images within the content. Importing these .docx files results in one image uploaded numerous times into the media library, and that single image is repeated throughout the document in the Pressbooks editor.   

We have tried different methods of placing the images into the .docx files (ie 'place', insert, copy/paste)  Results are the same. 

The image file format does not seem to matter (png, jpg, jpeg) either.  Nor does the image order.  The repeated image is pretty random, not always the first one in the document.

We have converted the docx files to .odt and imported them successfully. So this appears to be a bug with .docx import. 

Below are tests of .docx vs .odt, also a screen cap of our Media library, to help explain the issue. Thank you. 

![import-docx - copy](https://cloud.githubusercontent.com/assets/3603179/10668153/ea84e3f4-78a8-11e5-859d-0864d4efe520.PNG)

![imported-odt](https://cloud.githubusercontent.com/assets/3603179/10668158/f0a3b684-78a8-11e5-9eea-f9d0cce92dbd.PNG)

![media-library](https://cloud.githubusercontent.com/assets/3603179/10668189/1ed73968-78a9-11e5-815b-d8325c61fb7f.PNG)

EDIT:  We are using the latest release of Pressbooks ( 2.7.2 )

**Comment by rootl** [comment]
Greetings, 

If this information will help you:  We upgraded to Pressbooks 3.0 and Pressbooks Textbooks 2.0. The issue with docx file import still exists.

WordPress version:  4.3.1

**Comment by thomasdumm** [comment]
I also experienced this behaviour with current version of pressbooks.pub.
