### ISSUE TITLE
Fix failing tests

### ISSUE THREAD

**Issue by SteelWagstaff** [pressbooks/pressbooks#2883]
We have two failing tests, each of which attempts to clone an actual book from pressbooks.com in order to satisfy their conditions: https://github.com/pressbooks/pressbooks/blob/1e987235684c73ee63d256a90a618235595febbb/tests/test-integrations.php#L10-L104

Both tests broke when we accidentally deployed changes that broke the expected cloning behaviour in Pressbooks 5.36.0. We should make a plan for how to mark or replace these unit tests in a way that doesn't depend on code deployed to a book on a production environment that will no longer be hosted after September 2022.

See failure ouput: https://github.com/pressbooks/pressbooks/runs/7363406642?check_suite_focus=true
```
1) IntegrationsTest::test_cloneRemoteBook
Failed asserting that false is true.
/home/runner/work/pressbooks/pressbooks/tests/test-integrations.php:23
phpvfscomposer:///home/runner/work/pressbooks/pressbooks/vendor/phpunit/phpunit/phpunit:97
2) IntegrationsTest::test_ImportUsingCloningApi
Failed asserting that false is true.
/home/runner/work/pressbooks/pressbooks/tests/test-integrations.php:79
phpvfscomposer:///home/runner/work/pressbooks/pressbooks/vendor/phpunit/phpunit/phpunit:97
```
We'll need to fix this to get our build/deploy step in our CI pipeline working again, to package releases for open source users as well.

**Comment by fdalcin** [comment]
This is fixed and tests are passing now. We still need to think about mocking the test to not use production books.
