### ISSUE TITLE
<ol> tag duplication  after  EPUB export of imported EPUB

### ISSUE THREAD

**Issue by rootl** [pressbooks/pressbooks#289]
Greetings,

We have an existing epub that we imported into Pressbooks.  Upon export,  'ol' ordered list tags are duplicated. 

Original EPUB sample code (from imported EPUB file)
![ol_import-epub](https://cloud.githubusercontent.com/assets/3603179/10694565/e2db682a-796c-11e5-9708-65b543f8615a.PNG)

Output after Pressbooks EPUB export 
![ol_export](https://cloud.githubusercontent.com/assets/3603179/10694581/01f0b9fe-796d-11e5-8f58-020bb09bb226.PNG)

**Comment by greatislander** [comment]
@rootl Is this still an issue in current versions of Pressbooks? We have not been able to reproduce.

**Comment by greatislander** [comment]
(Please reopen if it is still affecting your workflow!)
