### ISSUE TITLE
Use markdown to write books

### ISSUE THREAD

**Issue by marcusschiesser** [pressbooks/pressbooks#290]
Wordpress has support for writing posts in markdown (see
https://en.support.wordpress.com/markdown/).
For some reason this seems to be disabled in Pressbooks.
I guess it would be useful and should therefore be enabled.

**Comment by greatislander** [comment]
Strictly speaking, WordPress doesn't have support for it; WordPress.com's Markdown support is part of [Jetpack](http://jetpack.me) so it isn't just a matter of enabling it. We could take the Markdown support module from Jetpack and include it in Pressbooks, but we would need to make sure this wouldn't cause problems with the way we process HTML for outputs. Needs more study.

**Comment by hughmcguire** [comment]
If anyone would like to do some experimenting/testing on this you are encouraged to do so! ;-)

**Comment by connerbw** [comment]
Maybe "cheat" by sending Markdown to this GitHub API endpoint?

https://developer.github.com/v3/markdown/

**Comment by colomet** [comment]
The jetpack developers export the Markdonw module as an independent plugin https://es.wordpress.org/plugins/jetpack-markdown/

But if i try to use it, do not work because the comments are closed and i can not open the settings page of the plugin

/wp-admin/options-discussion.php#wpcom_publish_comments_with_markdown

**Comment by greatislander** [comment]
This is not something we will implement in Pressbooks Core. Add-on plugins welcomed.

**Comment by greatislander** [comment]
Implemented by @connerbw:

+ https://wordpress.org/plugins/parsedown-party/
+ https://github.com/connerbw/parsedownparty

**Comment by danyork** [comment]
@greatislander - Thanks for those links to parsedown-party. Just a note that you might want to consider updating your KB FAQ with this info: https://pressbooks.groovehq.com/knowledge_base/topics/does-pressbooks-support-markdown  (to make it easier for those of us trying to understand if PressBooks works with markdown)

**Comment by greatislander** [comment]
@danyork To be clear, the Groove knowledge base is for our Pressbooks.com and PressbooksEDU hosted services. We don't yet include @connerbw's plugin on these networks. Open Source users who host their own Pressbooks networks are free to install the plugin there.
