### ISSUE TITLE
Textbox menu

### ISSUE THREAD

**Issue by greatislander** [pressbooks/pressbooks#292]
Includes:

- Standard
- Shaded
- Learning Objective
- Key Takeaway
- Exercises
- Examples
- Custom (with modal)

**Comment by greatislander** [comment]
From @hughmcguire on #300:

- “Insert Textbox”
- “Textbox Properties” Modal: 
	- Textbox type dropdown (regular, shaded, learning objective, key takeaway, exercises, examples, custom=field)

**Comment by greatislander** [comment]
@hughmcguire Ready for you to add textbox styles [here](https://github.com/pressbooks/pressbooks/blob/dev/assets/scss/partials/_textboxes.scss). We need to discuss how we want to implement the three ones that are based on the PBT educational styles—they add content as well as a wrapper `div`.

**Comment by greatislander** [comment]
@hughmcguire FYI: textbox styles are imported via EPUB & PDF house styles.

**Comment by hughmcguire** [comment]
Hi Ned, yes let's add the content as well as the styles.

**Comment by greatislander** [comment]
@hughmcguire to style in https://github.com/pressbooks/pressbooks/blob/dev/assets/scss/partials/_textboxes.scss
