### ISSUE TITLE
Fetch pressbooks.com data for Steel for next batch of communications

### ISSUE THREAD

**Issue by cmurtagh** [pressbooks/pressbooks#2920]
Produce a CSV file with the following data from pressbooks.com data:

"blog_id","domain","pressbooks_upgrade_level","pb_title","pb_word_count","pb_book_license","pb_is_public","pb_last_edited","pb_created","ID","user_login","display_name","user_email","pressbooks_upgrade_level"

**Comment by cmurtagh** [comment]
The data has been fetched and placed here:

https://drive.google.com/file/d/1k-NnWfotiHQ4oKXQIMMNLxpzsweM7ut2/view?usp=sharing

**Comment by SteelWagstaff** [comment]
Looks good to me. Thank you Christopher!
