### ISSUE TITLE
Pressbooks 3 updated with error

### ISSUE THREAD

**Issue by sswettenham** [pressbooks/pressbooks#296]
Ran update from previous version of Pressbooks without interruption but when I went to any site the following errors were displayed:

PBT cannot find a Pressbooks install.

Cannot find Pressbooks install.

Noteworthy - I updated Pressbooks Textbook on another multisite to version 2 and had the following error:
PBT cannot find a Pressbooks install.

**Comment by connerbw** [comment]
Does Pressbooks work with PBT disabled? (PBT = The separate Pressbooks Textbook Plugin)

Please report here:
https://github.com/BCcampus/pressbooks-textbook

**Comment by greatislander** [comment]
@connerbw @sswettenham The SVN commit of Pressbooks 3.0 to WordPress.org appears to have been corrupted. I am replacing it now and the new version should be available shortly. Please stay tuned, apologies for the inconvenience.

**Comment by greatislander** [comment]
Pressbooks 3.0 should now be fully functional. You will need to re-download the plugin. Please note that PHP 5.6 is now required, but this requirement can be overridden at your own risk (see the readme for details).
