### ISSUE TITLE
Plugin could not be activated because it triggered a fatal error.

### ISSUE THREAD

**Issue by theauditor** [pressbooks/pressbooks#297]
Got this when I was testing and tried to activate 
Warning: require_once(/var/www/PressBook/wp-content/plugins/pressbooks/symbionts/custom-metadata/custom_metadata.php): failed to open stream: No such file or directory in /var/www/PressBook/wp-content/plugins/pressbooks/includes/pb-utility.php on line 363

Fatal error: require_once(): Failed opening required '/var/www/PressBook/wp-content/plugins/pressbooks/symbionts/custom-metadata/custom_metadata.php' (include_path='.:/usr/share/php:/usr/share/pear') in /var/www/PressBook/wp-content/plugins/pressbooks/includes/pb-utility.php on line 363

**Comment by theauditor** [comment]
Actually needs an update in the install instructions to update the submodules

**Comment by greatislander** [comment]
@theauditor Thanks for the note. We did not account for installations from GitHub in the readme as in the wordpress.org version, the GitHub submodules are bundled without any effort needed on the part of the user.

**Comment by crism** [comment]
This is true of the [distributed releases](https://github.com/pressbooks/pressbooks/releases), as well, at least 3.0; missing `custom_metadata.php` causes a fatal error.

**Comment by greatislander** [comment]
@crism We do not release through GitHub, but rather through [wordpress.org](https://wordpress.org/plugins/pressbooks/developers/)—for this reason we have not made an effort to bundle releases on GitHub that include the required submodules. If you need to use the GitHub version for some reason, you need [clone it and then update submodules](http://git-scm.com/book/en/v2/Git-Tools-Submodules#Cloning-a-Project-with-Submodules).

**Comment by crism** [comment]
Thanks, @greatislander. I ended up installing via git with submodules; having some tags marked as releases is a little confusing in that respect, though.
