### ISSUE TITLE
Anchor / Link Button (enable linking to an anchor on that page/chapter)

### ISSUE THREAD

**Issue by hughmcguire** [pressbooks/pressbooks#301]
Button(s) allow user to:
-- add an ID to an element
-- link to that element from within the page

ANCHOR SPEC:

- highlight content, select “add anchor” 
- insert link, select “Or link to existing content” (<< using existing LINK tool, or with new Anchor link button) 
	- add a selection of “Link to Content in this page” … which lists IDs in the page to link to, inserts correct markup.

NOTE: 
-- need to make sure paths work in all exports 
-- make sure paths work properly on:
- book.pressbooks.com 
as well
- clientsite.pressbooks.pub/book

**Comment by greatislander** [comment]
Duplicate of #294.
