### ISSUE TITLE
My Books menu appears with empty vertical space when user has few books

### ISSUE THREAD

**Issue by greatislander** [pressbooks/pressbooks#3022]
### Prerequisites

* [x] Can you reproduce the behavior you wish to address with [all other plugins deactivated](http://codex.wordpress.org/Multisite_Network_Administration#Plugins)?
* [x] Are you running the [latest version of Pressbooks](http://github.com/pressbooks/pressbooks/releases/latest/) and the [latest version of WordPress](http://codex.wordpress.org/Upgrading_WordPress)?
* [x] Are you experiencing this issue with one of our built-in root or book themes?
* [x] Did you [perform a cursory search](https://github.com/issues?q=+is%3Aissue+repo%3Apressbooks%2Fpressbooks) to see if your bug or enhancement is already listed?

### Description

This regression appears to have been introduced here: https://github.com/pressbooks/pressbooks/blob/9c4d262772aad8551f79d042fada7712156e57fe/assets/src/styles/pressbooks.scss#L66

The relevant PR addressed an issue when users with many books would have a "My Books" menu which overflowed the viewport height, preventing access to all books in the menu. However, this PR introduced the opposite problem. A user with one or two books will have a "My Books" menu with a minimum height of 100px:

<img width="527" alt="Blank space in a 'My Books' menu with only one book in it." src="https://user-images.githubusercontent.com/605361/201489623-e8ace04e-f359-4451-90a3-090dc86f2516.png">

Replacing `min-height: 100px` with `height: auto` resolves this issue while preserving the desired fix from #1900.

### Steps to Reproduce

1. Create a user account.
2. Add one book.
3. Open "My Books".

**Expected behavior:** Menu has an appropriate height.

**Actual behavior:** Menu has empty vertical space.

<details>

<summary><h3>System Information</h3></summary>

#### Book Info

Book ID: 2
Book URL: https://pb.test/mobydick/
Book Privacy: Public

#### Browser

Platform: OS X
Browser Name: Safari
Browser Version: 16.1
User Agent String: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.1 Safari/605.1.15

#### WordPress Configuration

Network URL: https://pb.test/
Network Type: Subdirectory
Version: 6.1
Language: en_US
WP_ENV: development
WP_DEBUG: Enabled
Memory Limit: 64M

#### Pressbooks Configuration

Version: 6.3.0
Book Theme: McLuhan
Book Theme Version: 2.24.0
Root Theme: Aldine
Root Theme Version: 1.17.0

#### Pressbooks Dependencies

Epubcheck: Not Installed
xmllint: Installed
PrinceXML: Not Installed
Saxon-HE: Not Installed

#### Must-Use Plugins

Bedrock Autoloader: 1.0.3
hm-autoloader.php: n/a

#### Network Active Plugins

Pressbooks: 6.3.0

#### Book Active Plugins

Pressbooks: 6.3.0

#### Server Configuration

PHP Version: 8.0.25
MySQL Version: 8.0.27
Webserver Info: nginx/1.23.2

#### PHP Configuration

Memory Limit: 512M
Upload Max Size: 512M
Post Max Size: 512M
Upload Max Filesize: 512M
Time Limit: 30
Max Input Vars: 1000
URL-aware fopen: On (1)
Display Errors: On (1)

#### PHP Extensions

OPcache: Zend
XDebug: Enabled
cURL: Supported
cURL Version: 7.86.0
imagick: Not Installed
xsl: Installed

</details>

**Comment by SteelWagstaff** [comment]
Tested and works as expected on Integrations. Ready for release. Thanks for catching my oversight @greatislander !
