### ISSUE TITLE
PHP alert when installing Pressbooks v.3

### ISSUE THREAD

**Issue by sswettenham** [pressbooks/pressbooks#303]
"... can be overridden, so long as it is remains above PHP 5.4.0. Add a line to wp-config.php as follows: $pb_minimum_php = 5.4.0; "

needs quotes:
      $pb_minimum_php = '5.4.0';

**Comment by greatislander** [comment]
Thank you for the report. The Pressbooks readme has this error, which I have fixed. However, the error message you have identified is in Pressbooks Textbook (see [here](https://github.com/BCcampus/pressbooks-textbook/blob/aa8af8d49e7e3344a974466b542ee9aeb2dc4589/pressbooks-textbook.php#L417)). I would encourage you to post this issue there.
