### ISSUE TITLE
two different book info pages appear

### ISSUE THREAD

**Issue by sswettenham** [pressbooks/pressbooks#304]
Pressbooks 3 / Pressbooks-textbook 2
![footer-bookinfo](https://cloud.githubusercontent.com/assets/360534/10913488/6ef38fc4-824e-11e5-82ce-e22ba6c34d9c.png)

The book site homepage now contains a footer with mostly blank information which appears to be derived from the URL ../wp-admin/wp-admin/post-new.php?post_type=metadata

However, the actual Book Info is at ../wp-admin/wp-admin/post.php?post=17&action=edit

I am a bit confused as to why two different book info pages ??

**Comment by greatislander** [comment]
I'm sorry, but I am not quite sure what you mean.

> “appears to be derived from the URL”

It can't be coming from that URL as that is not actually a post. Which information is blank? What have you filled in on your Book Info page?

**Comment by sswettenham** [comment]
The source of the issue is with the pressbooks-textbook plugin:
1. starting on ../wp-admin/options-general.php?page=pressbooks-textbook-settings
2. select Book Info link in "Two easy steps, using built-in functionality (recommended)
    Select your 'Copyright license' from the dropdown menu in the Copyright section on the Book Info page."
3. goes to a blank info page - saving this page will delete previous book info

I will re-post for Pressbooks-Textbook.

**Comment by greatislander** [comment]
Thank you.
