### ISSUE TITLE
Make compatible with PHP 8.1

### ISSUE THREAD

**Issue by SteelWagstaff** [pressbooks/pressbooks#3044]
Fix test matrix for PHP 8.1. We have a number of compatibility warnings in this repo: https://github.com/pressbooks/pressbooks/actions/runs/3568403390/jobs/5997235215

There are three types of deprecation notices:
1. We have 12 'automatic conversion of false to array' deprecation notices in In [inc/admin/covergenerator/namespace/php](https://github.com/pressbooks/pressbooks/blob/56be4dffcb09a83dc27cbcfece7d0969d3cf9228/inc/admin/covergenerator/namespace.php#L341-L581) (lines 341, 353, 365, 377, 389, 401, 417, 430, 512, 549, 560, & 581)

2. We have hundreds of deprecation notices in SCSSPHP: 
`substr(): Passing null to parameter #1 ($string) of type string is deprecated in /home/runner/work/pressbooks/pressbooks/vendor/scssphp/scssphp/src/Compiler.php on line 331`
`preg_match(): Passing null to parameter #4 ($flags) of type int is deprecated in /home/runner/work/pressbooks/pressbooks/vendor/scssphp/scssphp/src/Parser.php on line 1[23](https://github.com/pressbooks/pressbooks/actions/runs/3568403390/jobs/5997235215#step:9:24)`

We can probably resolve with https://github.com/pressbooks/buckram/issues/289 (or https://github.com/pressbooks/pressbooks/issues/2281)

3. There are 10 deprecation notices in rmccue/requests, a dependency of WP-CLI. For example:
`Return type of Requests_Cookie_Jar::offsetExists($key) should either be compatible with ArrayAccess::offsetExists(mixed $offset): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /home/runner/work/pressbooks/pressbooks/vendor/rmccue/requests/library/Requests/Cookie/Jar.php on line 63`

**Comment by richard015ar** [comment]
Number 2 is about the scssphp version. We are using an older version (1.1.0), the latest 1.11.0, that fixes some PHP 8.1 notices.
I fixed it by changing the dependency requirement to: `"scssphp/scssphp": "^1.11.0"`

Probably related to the compiler issue we have here @SteelWagstaff https://github.com/pressbooks/pressbooks-austen/commit/d20692b83f1b5382c6c2c53f0daaefa13b0e457d#diff-f6f9dd524bd3db1e61d135b19780c04eea4ce9b03e6a0c66981fefde803c321cR13-R24

**Comment by SteelWagstaff** [comment]
@richard015ar we have some known problems that are blocking us from upgrading to scssphp 1.11. See https://github.com/pressbooks/pressbooks/issues/2281#issuecomment-1007245092 and https://github.com/pressbooks/buckram/issues/289. I've reopened the dependabot scssphp update PR so we can have a recent CI run for you to see the errors: https://github.com/pressbooks/pressbooks/actions/runs/3584331650/jobs/6030865017

**Comment by richard015ar** [comment]
Thanks! I seeing those locally. I am investigating those scssphp deprecation notices + working on other PHP 8.1 issues on this repo.

**Comment by richard015ar** [comment]
branch with some progress: `chore/upgrade-php8.1`

**Comment by SteelWagstaff** [comment]
We've now updated scssphp to 1.11.0 in the dev branch of pressbooks/pressbooks.

**Comment by SteelWagstaff** [comment]
Just ran a new test run on Ricardo's upgrade branch: https://github.com/pressbooks/pressbooks/actions/runs/3857333058/jobs/6574607111

I see 1 error and 1 failure:
> There was 1 error:
```
1) ApiTest::test_BookEndpoints
Error: Cannot unset offset in a non-array variable

/tmp/wordpress/wp-includes/rest-api/endpoints/class-wp-rest-controller.php:327
/tmp/wordpress/wp-includes/rest-api/class-wp-rest-server.php:1487
/tmp/wordpress/wp-includes/rest-api.php:785
/tmp/wordpress/wp-includes/class-wp-hook.php:308
/tmp/wordpress/wp-includes/plugin.php:205
/tmp/wordpress/wp-includes/rest-api/class-wp-rest-server.php:983
/tmp/wordpress-tests-lib/includes/spy-rest-server.php:67
/home/runner/work/pressbooks/pressbooks/tests/test-api.php:293
```

>There was 1 failure:
``` 1) MetadataTest::test_add_citation_metadata
Failed asserting that Deprecated: Function strftime() is deprecated in /home/runner/work/pressbooks/pressbooks/inc/metadata/namespace.php on line 337
Deprecated: Function strftime() is deprecated in /home/runner/work/pressbooks/pressbooks/inc/metadata/namespace.php on line 340
<meta name="og:type" content="book">
<meta name="citation_title" content="Some Book">
<meta name="citation_year" content="2023">
<meta name="citation_publication_date" content="2023-01-06">
<meta name="citation_language" content="en-ca">
<meta name="citation_publisher" content="Book Oven Inc.">
<meta name="citation_isbn" content="9781234567897">
<meta name="citation_doi" content="10.1000/xyz123">
<meta name="citation_author" content="Some Author">' starts with "<meta name="og:type" content="book"".

/home/runner/work/pressbooks/pressbooks/tests/test-metadata.php:578
```
For the failure, see https://php.watch/versions/8.1/strftime-gmstrftime-deprecated

There are also dozens of PHP and SCSS deprecation warnings of various types. Might be a good time to try using Rector on our project? https://github.com/rectorphp/rector

**Comment by richard015ar** [comment]
Notes in https://docs.google.com/document/d/1Th56ipk19FNqdeXT32mdRgpAHoIV3wUQOtSrrEr8tjs/edit#

**Comment by richard015ar** [comment]
PR: https://github.com/pressbooks/pressbooks/pull/3115
