### ISSUE TITLE
Add new institutions to institutions list

### ISSUE THREAD

**Issue by JohnMcLeod13** [pressbooks/pressbooks#3045]
Can we add these institutions to the institutions of HED list:

Seattle Colleges District
Community Colleges of Spokane District
Atlanta University Center - Robert W. Woodruff Library

**Comment by JohnMcLeod13** [comment]
Seattle Colleges District and Community Colleges of Spokane District are both needed for Open WA network. Atlanta University Center serves 4 HBCUs in the Atlanta area (Clark Atlanta University, Morehouse College, Spelman College. Morehouse School of Medicine).

**Comment by SteelWagstaff** [comment]
@JohnMcLeod13 yes you did. Just opened a PR to address this today: https://github.com/pressbooks/pressbooks/pull/3095/files

**Comment by tw77** [comment]
These three are present in the institutions list on Integrations now.
