### ISSUE TITLE
In-network cloning error on Open Oregon

### ISSUE THREAD

**Issue by tw77** [pressbooks/pressbooks#3046]
### Description

Reported on November 29 by Open Oregon and replicable on [their network](https://openoregon.pressbooks.pub/): when they attempt to clone a book from within their network, they encounter an 'EventStream Connection Error.' The cloned book is created but the clone fails at the metadata stage, not bringing in the pages.

**Note:** I've been able to replicate this on Open Oregon's network, but not on Integrations (either when cloning an Integrations test book to Integrations or when cloning a book from Open Oregon to Integrations).

Also, only 'in-network' or 'internal' clones seem to encounter this problem. Cloning a book from a different network to their network works as expected.

### Steps to Reproduce

1. Choose a public, openly licensed book to clone on [Open Oregon](https://openoregon.pressbooks.pub/wp/wp-admin/).
2. On the same network, use the cloning tool to create a clone of the book.

**Expected behavior:** A clone is created.

**Actual behavior:** <img width="975" alt="Screenshot 2022-11-29 at 7 35 31 PM" src="https://user-images.githubusercontent.com/44182629/204703724-df5d8e8d-1330-443c-bbbd-2238e7b95e28.png">

<img width="622" alt="Screenshot 2022-11-29 at 8 00 26 PM" src="https://user-images.githubusercontent.com/44182629/204704549-05d1f5bf-06f6-4f4b-8ec6-d7d9c55ab2d5.png">

**Comment by SteelWagstaff** [comment]
We were able to reproduce on university. Import from URL worked, but cloning routine failed as Thomas describes.

**Comment by richard015ar** [comment]
Quick update: it seems to be related to H5P and/or API terms, according to the debugging I am doing. More to come.

**Comment by richard015ar** [comment]
When cloning the book from `<BOOK_URL>/wp-admin/options.php?page=pb_cloner` it works.
but when doing it through `<NETWORK_URL>/wp-admin/options.php?page=pb_cloner` it does not. It seems to be something related to the API setup hooks order in WP >= 6.0

**Comment by tw77** [comment]
I just tested an in-network clone of an Integrations book on the Integrations network, but ran into the same EventStream Connection Error.

<img width="1275" alt="Screenshot 2022-12-08 at 7 46 18 AM" src="https://user-images.githubusercontent.com/44182629/206492372-20582ece-2eba-4180-b303-8e7b0f1f83bd.png">

**Comment by tw77** [comment]
With the most recent deploy to Integrations, a test with the same Integrations source book now clones successfully.

**Comment by tw77** [comment]
This may be its own ticket, but currently on Integrations, when I make a clone of an Integrations book with H5P elements -- with the H5P plugin inactive at the network level, as recommended -- H5P isn't activated on the cloned book. This prevents H5P elements from being brought over in the clone.

Cloning a book with H5P elements from an external network to Integrations works as expected, however.

**Comment by tw77** [comment]
Closing this because the bug in the main description is effectively fixed on Integrations -- will open a new ticket on cloning with H5P elements within the same network.
