### ISSUE TITLE
Author role has some non-intuitive results

### ISSUE THREAD

**Issue by ghost** [pressbooks/pressbooks#305]
As author role, there are two user interface functions with non-intuitive expectations:
1. "Delete" link in Text > Organize > Edit column will appear to delete another authors’ content and will not provide the same permissions error message "You are not allowed to edit this item.” found when selecting edit on another authors’ content. The message "Are you sure you want to delete this?” appears but invoking does nothing because I am not the author of the content. Expectation was a permissions alert.
2. Authors can re-arrange order of matter in Text > Organize   including other authors’ matter. Expectation was that I can only arrange my own content.

**Comment by colomet** [comment]
I think the permissions of each role would have to be revised. I use to use Editor role for my partners instead of Author.
