### ISSUE TITLE
Store information about successful clones in database

### ISSUE THREAD

**Issue by SteelWagstaff** [pressbooks/pressbooks#3055]
Create some kind of API-based pub/sub type system which notifies the source network when clone requests are successfully completed. We should store information about books cloned FROM a network in a central metadata table of some kind on the source network (book ID for source book plus book URL for target book).

Christopher proposes changing the cloning routine so that the source book sends a simple token as part of its payload. At the end of the cloning process, the target network returns the token with its book completion URL.

**Comment by richard015ar** [comment]
Summary about what we agreed: 
![Diagrama sin título drawio](https://user-images.githubusercontent.com/13248424/207663383-dc7d464e-2d59-4623-a2dd-bd90b1e824c1.png)

**Comment by richard015ar** [comment]
The feature is in https://github.com/pressbooks/pressbooks/pull/3091
I am working on unit tests. 
Oscar is working in a separate branch for the front end, but with the base on this one to read the data.

**Comment by SteelWagstaff** [comment]
I cloned this book https://integrations.pressbooks.network/openedreader to integrations2 and this book https://integrations2.pressbooks.network/clonetest/ to integrations. i also cloned https://dev.pressbooks.pub/institutiontest to integrations. Clones displayed a success message in all cases, but I did not see information about the clones on the new book info/cloning stats pages

**Comment by SteelWagstaff** [comment]
Looking good on integrations now!
![Screenshot from 2022-12-22 10-25-29](https://user-images.githubusercontent.com/13485451/209202188-a936c51c-aefd-46e2-afdd-fb04d26bebfa.png)
