### ISSUE TITLE
Do we have to do something special with the update (from 2.7.2 to 3.0)

### ISSUE THREAD

**Issue by colomet** [pressbooks/pressbooks#307]
I did try and i had to upload the backup. Should i do something special? or just donwload from wordpress.org

**Comment by greatislander** [comment]
You shouldn't have to do anything special to update.

**Comment by connerbw** [comment]
Can you describe the problem you had?

**Comment by colomet** [comment]
I did update with no problems in the good one installation, but i have one for testing purposes, i did try first (just in case) and it did not update (should be server configuration). In the middle of the proces, stop.

**Comment by connerbw** [comment]
This probably happenend because WordPress SVN timed out (or some other communications error). Here is an example of such an error happening to us:

```
svn: OPTIONS of 'https://develop.svn.wordpress.org/tags/4.3.1/tests/phpunit/includes': SSL handshake failed: Secure connection truncated (https://develop.svn.wordpress.org)
```

Without any more info there isn't much we can do. Closing issue.
