### ISSUE TITLE
In-network clone not bringing over H5P elements on Integrations

### ISSUE THREAD

**Issue by tw77** [pressbooks/pressbooks#3075]
### Description

Only reproducible on Integrations right now, because other networks are currently affected by [the EventStream Connection Error when cloning a book within the same network](https://github.com/pressbooks/pressbooks/issues/3046), the fix for which is deployed to Integrations.

On Integrations, cloning a book from within the network with H5P elements does not bring over H5P elements.

Manually activating the H5P plugin on the cloned book does not cause the H5P elements to render, as they are not brought over in the clone.

However, cloning a book from an external network to Integrations brings over H5P elements as expected.

### Steps to Reproduce

1. Ensure H5P plugin is not active at the network level.
2. Clone a book from the same network (Integrations) with H5P elements in it.

**Expected behavior:** H5P is activated in the cloned book, and H5P elements are brought over in the clone.

**Actual behavior:** H5P is not activated in the cloned book. Elements are not brought over in the clone, and do not render after manually activating H5P on the cloned book.

**Comment by SteelWagstaff** [comment]
Places to look for cause of this problem:
https://github.com/pressbooks/pressbooks/blob/725d4aef261784658f171e072f08fa66b9ff3c77/inc/cloner/class-cloner.php#L609-L615 
https://github.com/pressbooks/pressbooks/blob/725d4aef261784658f171e072f08fa66b9ff3c77/inc/cloner/class-cloner.php#L633-L638

**Comment by richard015ar** [comment]
Elements seems to be replaced by the following text:
```
The original version of this chapter contained H5P content. You may want to remove or replace this element.
```

**Comment by richard015ar** [comment]
https://github.com/pressbooks/pressbooks/blob/725d4aef261784658f171e072f08fa66b9ff3c77/inc/cloner/class-cloner.php#L820-L831
The HTTP response of this exposes "route not found", therefore, the method returns false.

**Comment by richard015ar** [comment]
H5P WP plugin just launched a new version. I installed it locally, and I can confirm this bug is not related to that.

**Comment by arzola** [comment]
I don't totally understand why the H5P plugin needs to be inactive to test this because is a requirement to have that plugin installed in order to expose the H5P content through the same network because if the plugin is not active there is no way to expose the source book h5p content from the same network, it works for cloning remote books because the source network has the plugin installed and active.

So this will be solved activating the plugin in the network

**Comment by tw77** [comment]
This fix is working on Integrations. With H5P not active at the network level, I'm able to clone a book with H5P content within the network from `http://book_url/wp-admin/options.php?page=pb_cloner` and from `http://network_url/wp-admin/options.php?page=pb_cloner`. H5P is activated on the target book as expected and H5P content is brought over in the clone.
