### ISSUE TITLE
Final improvements for clone a book page

### ISSUE THREAD

**Issue by SteelWagstaff** [pressbooks/pressbooks#3078]
- [x] don't display directory search section when env variables aren't present
- [x] make sure progress bar text is hidden if clone fails
- [x] make sure all input have accessible labels
- [x] improve text when displaying search results (template should say 20 of ### results shown)

**Comment by richard015ar** [comment]
@SteelWagstaff , regarding:

> make sure progress bar text is hidden if clone fails

Would you explain in detail what do you expect at the UI level when a clone fails?

**Comment by tw77** [comment]
Searching and selecting books to clone works well.

The search placeholder text says ‘Search openly licensed books,’ but books with a CC BY-NC-ND or CC BY-ND license as well as All Rights Reserved books appear in the results. Books that aren’t openly licensed aren’t possible to clone, as expected. Filtering out books that aren't openly licensed might usefully narrow down the results, or making the listed book license into linked text that directs to the CC license summary (which could clarify why CC BY-NC-ND or CC BY-ND books aren’t licensed for cloning).

Books with multiple authors have the authors listed without a space after the comma separating each author name.

There is an extra underlined space after ‘# H5P Activities ’

If you enter a Source Book URL and misspell the path (a nonexistent book on an existing network) the error message shown when pressing ‘Clone book’ is ‘You can only clone from a book hosted by Pressbooks 4.1 or later. Please ensure that your source book meets these requirements.’ Could the message say something like: 'Book not found at that location. Please ensure you have the correct URL' ?

**Comment by SteelWagstaff** [comment]
Fixes for first three issues have been pushed to integrations and are ready for testing. I created a separate issue for the last one: #3084
