### ISSUE TITLE
Using Right to Left Text in Pressbooks 3.0

### ISSUE THREAD

**Issue by jflowers45** [pressbooks/pressbooks#308]
@greatislander @hughmcguire Really exciting to see the support for embedding in-language fonts regardless of theme!  We were just checking this feature out and were trying out the Arabic support.  I see that the font can be embedded, but is there a workflow that would allow us to produce Right to Left eBooks on pressbooks.com?  Wasn't sure if any of the themes supported it, or if we needed to do "pressbooks custom css" and then edit the CSS ourselves

Thanks!

**Comment by greatislander** [comment]
@jflowers45 There isn't yet. Unfortunately, the Custom CSS theme doesn't support SASS (which is required for including the language fonts). Comprehensive RTL support is definitely important, but didn't make the first cut of this feature—will look into this further. Thanks!

**Comment by jflowers45** [comment]
@greatislander cool, thanks for the heads up, makes sense.  We are working on a Uyghur eBook so if we get to the point where we can do it in our version of pressbooks, i'll certainly let you know how we go about it (even though your approach will likely differ since we're a fork of 2.x, it may still help)

**Comment by jflowers45** [comment]
@greatislander @hughmcguire we're nearing completion of our first ePub/mPDF book in Uyghur which is a right to left language

I'm sure you know that you have to update the opf spine with page progression direction.  But other than that, tricky things that may be good for you to know:

1)  ePub3 spec doesn't allow the "direction" property to be set in CSS (the ePub won't validate) so we put the dir='rtl' attribute in our body tags.  Reference for confirmation: http://www.idpf.org/accessibility/guidelines/content/style/reference.php

2)  We had the need to include both English and Uyghur text in the same chapter.  There's a plugin out there that adds left to right/right to left buttons to the TinyMCE editor but it seems to use <p> tags.   `<p dir="ltr">` 
wasn't enough to override the body settings.  However, `<div dir="ltr">` was.  

3)  TinyMCE can be initialized with an RTL attribute but getting wordpress to do that seemed like a hassle.   We hacked it like this ... you may have a more appropriate way, but if not, this has worked for us. 
```
jQuery(document).ready(function ($) {
	function setRTL() {
		if (tinyMCE.activeEditor != null) {
			jQuery('iframe').contents().find('body').attr('dir','rtl');
		} else {
			setTimeout(setRTL,100)
		}	
	}
	setRTL();
}); 
```

**Comment by atef81** [comment]
Hi, I am just wondering if there are any updates for supporting RTL? I am planning to run the Wordpress plugin on my self hosted wordpress installation.
thanks

**Comment by greatislander** [comment]
@atef81 None yet, sorry!
