### ISSUE TITLE
enable web-search of book (see PB Textbook) 

### ISSUE THREAD

**Issue by hughmcguire** [pressbooks/pressbooks#309]
PB Textbook has (re?)-enabled the book-based search bar in web output... 

I would like to add this feature to PB proper (note: needs some styling)..

see:
![image of search bar]
(https://dl.dropboxusercontent.com/s/wpu3l7vn0ttjbmb/2015-11-11%20at%209.20%20AM.png)

... 
http://opentextbc.ca/learningpowerpoint/front-matter/introduction-2/

**Comment by greatislander** [comment]
Duplicate of #280.
