### ISSUE TITLE
Open source users' book dashboards have a broken "Analytics" link on them

### ISSUE THREAD

**Issue by greatislander** [pressbooks/pressbooks#3099]
### Description

The new book dashboard hardcodes a link to the Koko Analytics page for the book. However, not all open source users will have this plugin installed; in fact, I'm not sure if all Pressbooks clients use it? The link to Analytics should be conditional on the plugin being active for the book.

### Steps to Reproduce

1. Visit a book dashboard post Pressbooks 6.5.0 (with all other plugins deactivated).
2. Follow the Analytics link.

**Expected behavior:** Link goes somewhere.

**Actual behavior:** An unhelpfully generic WordPress error.

### System Information

Latest everything, PHP 8.1.

**Comment by fdalcin** [comment]
Tested on integrations and seems to be working as expected
