### ISSUE TITLE
Update institution list on book info page

### ISSUE THREAD

**Issue by josieg** [pressbooks/pressbooks#3112]
The institution drop-down list on the book info page lists a Capilano College. It should be Capilano University.

"In 2008, the provincial government changed Capilano College's designation to Capilano University." ([Capilano University, Our History](https://www.capilanou.ca/about-capu/get-to-know-us/our-history/))

**Comment by SteelWagstaff** [comment]
Thanks @josieg PR open to do this now: https://github.com/pressbooks/pressbooks/pull/3116

**Comment by SteelWagstaff** [comment]
Tested and working as expected and working on integrations (after I cleared the cache): https://integrations.pressbooks.network/steel/

![Screenshot from 2023-01-06 12-10-17](https://user-images.githubusercontent.com/13485451/211091562-838f8276-fd38-43c5-ab48-d8476588ce5d.png)

Ready for inclusion in next release of Pressbooks.

**Comment by josieg** [comment]
Amazing. Thanks Steel!
