### ISSUE TITLE
Regenerate stylesheet not working

### ISSUE THREAD

**Issue by SteelWagstaff** [pressbooks/pressbooks#3125]
Clicking the link to regenerate the stylesheet from the diagnostics page:
![Screenshot from 2023-01-11 09-02-18.png](https://images.zenhubusercontent.com/6012398f80b7cb0f8d1385bc/16e18270-4c00-440e-ad16-779b3eef9c12)

produces an error:
![Screenshot from 2023-01-11 09-02-47.png](https://images.zenhubusercontent.com/6012398f80b7cb0f8d1385bc/f234aa7e-8e3d-46e5-86c5-d58c8abb1639)

**Comment by SteelWagstaff** [comment]
Fix in https://github.com/pressbooks/pressbooks/pull/3124

**Comment by fdalcin** [comment]
Tested on integrations and works as expected
