### ISSUE TITLE
Add Docker Container Installation for Pressbooks

### ISSUE THREAD

**Issue by wexlerj** [pressbooks/pressbooks#313]
Because of the complexity of installing Pressbooks, which includes the installation of WordPress multisite, and installing the output formats, can Pressbooks be provided in a self-contained Docker container, available off of Docker Hub?

**Comment by connerbw** [comment]
PressBooks uses WordPress as a development framework and, as such, it is not a typical WordPress plugin. Rather, it is an organization that has made open source the code that runs PressBooks dot com.

We have our own internal installation mechanisms, (Vagrant, Deploy.bot, Bash Scripts, Etc). We do not use Docker. We do not intend to provide such a container.

Sorry.
