### ISSUE TITLE
Sites - in catalog

### ISSUE THREAD

**Issue by colomet** [pressbooks/pressbooks#316]
if i do activate in the catalog some books, and then i want to take of some books of the catalog. It works (looks like), but there is an strange error message in the screen.

![captura de pantalla 2015-11-17 a las 13 19 02](https://cloud.githubusercontent.com/assets/3929177/11211213/24b74938-8d2e-11e5-8737-38f0747e9c22.png)
Later i do refresh the page and in the main home of the web site, i can see the books i want to have there.

Looks like is working but i had to do it twice the first time, before to show the books i want in the main home.

thanks.

**Comment by greatislander** [comment]
@colomet I can’t reproduce this bug on my end. Are you getting the error message when you check the box to add a book to the catalog, or when you uncheck the box to remove a book from the catalog? Thanks.

**Comment by colomet** [comment]
I do have pressbooks 3.1.1.
If i check one or several books. Then i refresh the page, it will show that prompt.

it happen if i check or ucheck (and refresh after one of these changes)

thanks

**Comment by greatislander** [comment]
I was able to reproduce by checking and then immediately refreshing. But—you don't need to refresh as the catalog setting on this page, much like the export toggles on the Organize page in a book, uses AJAX. What seems to be happening is that you are refreshing before the AJAX command has been delivered and the error message results. If you check or uncheck and then navigate away from the page without refreshing it, does this happen?

**Comment by colomet** [comment]
no, it just happen if i do refresh. Looks like is working with no problem. 

But the first time I did use it, I was not able to do it, I had to do it twice before i can see the books in the main page.
