### ISSUE TITLE
pb-webinars.png is missing in the ZIP file for the plugin.

### ISSUE THREAD

**Issue by thomasdumm** [pressbooks/pressbooks#3164]
### Prerequisites

* [x] Can you reproduce the behavior you wish to address with [all other plugins deactivated](http://codex.wordpress.org/Multisite_Network_Administration#Plugins)?
* [x] Are you running the [latest version of Pressbooks](http://github.com/pressbooks/pressbooks/releases/latest/) and the [latest version of WordPress](http://codex.wordpress.org/Upgrading_WordPress)?
* [x] Are you experiencing this issue with one of our built-in root or book themes?
* [x] Did you [perform a cursory search](https://github.com/issues?q=+is%3Aissue+repo%3Apressbooks%2Fpressbooks) to see if your bug or enhancement is already listed?

### Description

pb-webinars.png is missing in the ZIP file for the plugin.

### Steps to Reproduce

Go to the dashboard of a book. There are images for 3 of the 4 support resources. The image for the webinars is not shown.

#### Book Info

Book ID: 10
Book URL: https://pressbooks.delivros.ch/demo/
Book Privacy: Public

#### Browser

Platform: Windows
Browser Name: Firefox
Browser Version: 109.0
User Agent String: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/109.0

#### WordPress Configuration

Network URL: https://pressbooks.delivros.ch/
Network Type: Subdirectory
Version: 6.1.1
Language: en_US
WP_ENV: development
WP_DEBUG: Enabled
Memory Limit: 64M

#### Pressbooks Configuration

Version: 6.7.0
Book Theme: McLuhan
Book Theme Version: 2.25.2
Root Theme: Aldine
Root Theme Version: 1.18.1

#### Pressbooks Dependencies

Epubcheck: Installed
xmllint: Installed
PrinceXML: Installed
Saxon-HE: Installed

#### Must-Use Plugins

hm-autoloader.php: n/a

#### Network Active Plugins

ceLTIc LTI Library: 4.10.0
Enable Media Replace: 4.0.2
Flite Addon for WP: 1.0
Hypothesis: 0.6.0
Koko Analytics: 1.0.37
Login IP & Country Restriction: 6.3.0
LTI Tool: 3.1.0
Pressbooks: 6.7.0
Pressbooks LTI Tool: 1.0.2
Pressbooks Stats: 1.8.0
Two Factor: 0.7.3
When Last Login: 1.2.1
WP Mail SMTP Pro: 3.7.0
WPO365 | SAMESITE: 1.3
WP QuickLaTeX: 3.8.6

#### Book Active Plugins

ceLTIc LTI Library: 4.10.0
Enable Media Replace: 4.0.2
Flite Addon for WP: 1.0
H5P: 1.15.6
Hypothesis: 0.6.0
Koko Analytics: 1.0.37
Login IP & Country Restriction: 6.3.0
LTI Tool: 3.1.0
Pressbooks: 6.7.0
Pressbooks LTI Tool: 1.0.2
Pressbooks Stats: 1.8.0
Two Factor: 0.7.3
When Last Login: 1.2.1
WP Mail SMTP Pro: 3.7.0
WPO365 | SAMESITE: 1.3
WP QuickLaTeX: 3.8.6

#### Inactive Plugins

Co-Authors Plus: 3.5.10
Really Simple SSL: 6.1.1
Really Simple SSL Pro multisite: 6.0.3

#### Server Configuration

PHP Version: 8.0.26
MySQL Version: 8.0.31
Webserver Info: Apache/2.4.52 (Ubuntu)

#### PHP Configuration

Memory Limit: 256M
Upload Max Size: 512M
Post Max Size: 512M
Upload Max Filesize: 512M
Time Limit: 30
Max Input Vars: 1000
URL-aware fopen: On (1)
Display Errors: On (1)

#### PHP Extensions

OPcache: Zend
XDebug: Disabled
cURL: Supported
cURL Version: 7.81.0
imagick: Not Installed
xsl: Installed

**Comment by SteelWagstaff** [comment]
Thanks for reporting @thomasdumm. Was fixed in 6.8.0 release: https://github.com/pressbooks/pressbooks/blob/6.8.0/assets/dist/images/pb-webinars.png

**Comment by thomasdumm** [comment]
I think the icon is still missing in the ZIP file of the 6.8.0 release.
![Uploading 4545E8B9-9B74-4EEA-AC3E-CD84FEF83880.jpeg…]()
