### ISSUE TITLE
PHP Deprecated:Non-static method Search::valid_search() should not be called statically...

### ISSUE THREAD

**Issue by rootl** [pressbooks/pressbooks#317]
Greetings:

We recently upgraded our server to PHP 5.6.  We see these 2 errors:

PHP Deprecated: Non-static method Search::valid_search() should not be called statically, assuming $this from incompatible context in ....../wp-content/plugins/pressbooks/symbionts/search-regex/search-regex.php on line 50

PHP Deprecated: Non-static method Search::get_searches() should not be called statically, assuming $this from incompatible context in ...../wp-content/plugins/pressbooks/symbionts/search-regex/models/search.php on line 104

Pressbooks version 3.0
Pressbooks Texbooks version 2.0
WordPress version 4.3.1

Site functions normally otherwise.

**Comment by greatislander** [comment]
Fix for this will be released soon on wordpress.org. Cheers!

**Comment by rootl** [comment]
Fantastic! Thank you :)

**Comment by greatislander** [comment]
@rootl We will be releasing this on wordpress.org soon. Thanks for the bug report!
