### ISSUE TITLE
SCSS v2 review

### ISSUE THREAD

**Issue by greatislander** [pressbooks/pressbooks#318]

**Comment by hughmcguire** [comment]
getting a "no data received" error, see:
https://annotate.driftt.com/view?i=fy6gaesuk64w6vo%2F2015-11-24_at_3.42_PM.png

to reproduce: 
- go to our standard test book in web/dev instance
- export (tested with Adunis & Atwood)
- it throws the "No data received" error 
- ... but if you navigate back to export & refresh the files have exported.

**Comment by connerbw** [comment]
Hi @hughmcguire 

I tried and could not reproduce?

**Comment by hughmcguire** [comment]
hrm let me check again with Adunis. seems OK now with other themes.

**Comment by hughmcguire** [comment]
seems resolved now ?

**Comment by hughmcguire** [comment]
ok ... all looks OK here, including Custom CSS ... over to you @greatislander I think we are ready to push.
