### ISSUE TITLE
Update dashboard and nav icons

### ISSUE THREAD

**Issue by SteelWagstaff** [pressbooks/pressbooks#3183]
We've begun using new icons for several items in the new dashboards and network manager side-level nav. We should also update the side nav icons for the book dashboard at the same time, for consistency. Wireframe in Figma.

## Notes
It would be great if we could use Heroicons & Michelle' custom SVG icons seamlessly as if they were the regular dashicons. Something like: https://giteroptimized.com/how-to-remove-dashicons-in-wp/ might work here?

**Comment by arzola** [comment]
I submitted a new branch with the first iteration of this to discuss https://github.com/pressbooks/pressbooks/tree/feat/icons-integration

**Comment by SteelWagstaff** [comment]
@arzola https://github.com/pressbooks/pressbooks/pull/3193#issuecomment-1432274973
> this is a really interesting approach -- the problem I'm seeing now is that the markup results in the SVG files being referenced as part of the src bath for an img elements:

> This is a problem because I can't apply CSS to change the fill color of the SVG file for hover and active states. I think we need these icons to be rendered as SVG elements or as characters within a font-face (the way WP does this with dashicons), rather than <img> elements, so that we can alter fill. See https://stackoverflow.com/a/30419873

**Comment by arzola** [comment]
@SteelWagstaff yes I agree I was thinking how to properly map those svgs because they don't provide a webfont format but actually I found the following https://github.com/savatia/heroicons-css so probably this would be our best bet

**Comment by arzola** [comment]
Well the heroicons-css is pretty outdated and a lot of new icons are not included, I tried to generate the font/svg map with `fantasticon` but the generated files are corrupted

**Comment by SteelWagstaff** [comment]
Ideas: https://blog.adobe.com/en/publish/2017/11/15/weekoficons-prepare-svg-icons-for-icon-fonts + https://mediatemple.net/blog/design-creative/creating-implementing-icon-font-tutorial/. Might be better, more modern tooling, but that's the basic concept.

**Comment by SteelWagstaff** [comment]
@arzola spoke with Michelle about this task. She said she's capable of turning icons into a font family as described in the Adobe article and could do it in an afternoon, if desired. I told her we'd talk about it at stand up and get back to her on that. Let me know if useful?

**Comment by arzola** [comment]
That would be amazing,  probably it will be limited to the icons that we are using only, but sounds really helpful

**Comment by arzola** [comment]
I addressed almost all feedback, for the add user icon I think we would require @MichelleWeremczuk to help us to add an extra SVG to the font

**Comment by SteelWagstaff** [comment]
Opened a new PR (#3211) to address heroicon color.

**Comment by SteelWagstaff** [comment]
Pushed a commit to replace the pb-network-guide image: https://github.com/pressbooks/pressbooks/commit/4f96884ea90b56bb77ec18e55f918851bfe8aace

**Comment by SteelWagstaff** [comment]
Talked with Michelle -- remaining desired changes:
- [x] Fix height for avatar link when hovering
- [x] use pencil icon for book info on book dashboard instead of lightning zap
- [x] the icon hover color for active parent elements when children are hovered (is red currently, should be white?). This is present in production networks as well. 
- [x] fix positioning of heroicons relative to text in side nav menu
- [ ] fix positioning of PB logo in top nav on mobile view

**Comment by SteelWagstaff** [comment]
Pushed a simple commit to fix avatar link width on mobile devices: https://github.com/pressbooks/pressbooks/commit/bfe957d66625a20c415761ee1e0567340c9d603d

**Comment by SteelWagstaff** [comment]
Tested and ready for release.
