### ISSUE TITLE
H1 instead of H2

### ISSUE THREAD

**Issue by colomet** [pressbooks/pressbooks#319]
pressbooks/themes-book/pressbooks-book/single.php

If i´m not wrong that is the code : `<h2 class="entry-title"><?php`

i think it will be better if the title of the page is H1. To change h2 in the code for h1

![captura de pantalla 2015-11-24 a las 9 31 59](https://cloud.githubusercontent.com/assets/3929177/11361499/3fa04488-928e-11e5-86af-2e4bd77b6332.png)

if Preface is the name of the page, i think it should be h1, if somebody whant a subtitle, they could use h2 and then h3, but if you just need just one title, Preface start with h2 and then we can not use h1 tag

What do you think?

thanks

**Comment by greatislander** [comment]
Going to leave this one for @hughmcguire to review.

**Comment by colomet** [comment]
i have other web site, and that is the way it works.

![captura de pantalla 2015-11-25 a las 13 26 32](https://cloud.githubusercontent.com/assets/3929177/11397275/87a0841a-9378-11e5-9e5c-ccb7adf20bb9.png)


I´m not sure about the SEO,  how do it handle H1 in title and in content. But i will check.

**Comment by hughmcguire** [comment]
we could do with a review of how we handle all of the structuring of content.

there is a conceptual problem which is, roughly: 
for a single book object, you might want to say: 
h1 ... book title
h2 ... part title 
h3 ... chapter title
h4 ... subchapter title
h5 ... section title

etc.

At the other end of the conceptual spectrum , HTML5 spec says: each new *section* should be 
```
<section>
<h1>title</h1>
<h2>title</h2>
</section>
<section>
<h1>title</h1>
<h2>title</h2>
</section>
```

So, conceptually these two approaches conflict; and in fact Pressbooks is neither fish nor fowl, and made structural decisions early on that should be revisited and reconsidered.

The W3C is doing some work on this:
http://www.w3.org/TR/pwp/

and we should follow that closely as some kind of consensus emerges....

**Comment by colomet** [comment]
i think is not really a problem.  From my point of view with litle knoledge about what i´m talking about looks like you organice from a static point of view. In a paper book, we have 

<h1> book title</h1>
<h2>part title</h2> 
<h3>chapter title</h3>
<h4>subchapter title</h4>
<h5>section title</h5>

but in a digital book, each screen start from scratch. Each screen of the ipad or computer should have h1 for the title or the most important sentence in the top of the screen. and then, the others.

if we are in TOC screen , H1 is for book title
<h1> book title</h1>
<h2>part title</h2> 
<h3>chapter title</h3>
<h4>subchapter title</h4>
<h5>section title</h5>

if we are in a normal page screen, H1 is for the name of the chapter
<h1>chapter title</h1>
<h2>subchapter title</h2>
<h3>title</h3>
<h3>title</h3>

or 
<h1>chapter title</h1>
<h2>title</h2>
<h2>title</h2>

if whe have no subchapter. And then always we should start from the same point. At least if is not the best aproach, is not too bad.

just that are my thougths. Let´s keep thinking. 

Thanks.

**Comment by hughmcguire** [comment]
and what about when we are in xHTML of the whole document?

**Comment by colomet** [comment]
then, what do you think is the best way to organice the content of a page? 
In your opinion, wich tag i shoud use for each section inside of a page?

**Comment by hughmcguire** [comment]
if you want it to work with the multi-level TOC feature, then H1. otherwise, up to you.
