### ISSUE TITLE
Top and side bar menus - Iteration II

### ISSUE THREAD

**Issue by richard015ar** [pressbooks/pressbooks#3194]
As a developer, I would like to continue iterating over the new network / super admin users menu implementation.
Right now, we decided to override the implementation of the menu to deliver and validate the main feature. Ideally, we would like to remove the previous implementation and create the desired and validated menu once. 
It would reduce the complexity of the current implementation and will allow us to have a more maintainable code.

DoD: Remove the legacy implementation of network admin and super admin menus and implement the validated feature once.

For context and specs, see:
- https://github.com/pressbooks/pressbooks-network-analytics/issues/284
- https://github.com/pressbooks/pressbooks/issues/3152
- https://github.com/pressbooks/pressbooks/issues/3183

**Comment by richard015ar** [comment]
We will keep Settings in the network context and Tools in the root site context (only for super admins).

For Settings and tools, we want to allow plugins to register submenu items. When a 3rd party plugin adds a new submenu item we don't maintain the subitems. 
Submenu items in Settings could change according to the context. What needs to be fixed are the ones we defined in the specs.

If network managers add new plugins which add new submenu items in Settings, they should not see it.
Note: NM can not add/remove plugins at the network level. It is just a super admin action.

**Comment by richard015ar** [comment]
Progress in `feat/menus-builder-structure`:
- Builder pattern was added to the solution
- New menu items classes to separately manage each menu item according to role and context.
- We managed to keep setting and tools submenu items.

Next: we need to rework settings and tools to consider 3rd party plugin items. Construct the removed items according to the context and role following the specs.
Remove laf implementation for sidebar menu.
Adapt/change unit tests.

**Comment by richard015ar** [comment]
We are designing a schema property to be used in each builder and which will guide the builder itself to construct the menu for each role and context. We are not sure about how this solution will result, but we have confidence it can work well.

We would need to adjust our current sprint goals since this task will take more effort than expected.

**Comment by richard015ar** [comment]
We met with @fdalcin and write next steps of this in https://github.com/pressbooks/pressbooks/issues/3214

**Comment by SteelWagstaff** [comment]
Closing in favor of #3214
