### ISSUE TITLE
Webpage Table of Contents not linked to sub-headings

### ISSUE THREAD

**Issue by sswettenham** [pressbooks/pressbooks#320]
Tested in PB v.2.7.2 and 3.0
with PB Textbook v.1.2.16 and 2.0
(all other plugins deactivated)

Parse Sections	 Enabled a two-level TOC

Result - link of sub-heading goes to top of page, not to 2nd level heading.

example - http://epub-fhd.athabascau.ca/clinical-teaching

**Comment by sswettenham** [comment]
Tested PB 3.0 and Austen Theme 1.5
Result: TOC working correctly on pointing to subheadings.

**Comment by greatislander** [comment]
@sswettenham Please post this issue on https://github.com/BCCampus/pressbooks-textbook. Thank you.
