### ISSUE TITLE
'My Books' top nav link should point to user dashboard when a user has books

### ISSUE THREAD

**Issue by SteelWagstaff** [pressbooks/pressbooks#3208]
As a regular user who hasn't created any books yet, 'My Books' in the top nav links to the user dashboard:

<img width="1214" alt="Screenshot 2023-02-27 at 8 53 47 AM" src="https://user-images.githubusercontent.com/44182629/221628224-c84fcd81-37c0-4856-8c85-7db2e433b60f.png">

As a regular user who _has_ created a book, 'My Books' in the top nav links me back to the book dashboard for the one book I've created. I can no longer reach the user dashboard. Clicking 'My Books' or clicking **Dashboard > Home** in the left sidebar both keep me on the same page:

https://user-images.githubusercontent.com/44182629/221628529-5e11305c-8c36-4be2-8502-329333c3362b.mp4

_Originally posted by @tw77 in https://github.com/pressbooks/pressbooks/issues/3152#issuecomment-1446690121_

**Comment by tw77** [comment]
This link is now working for me as a regular user with a book on dev.pressbooks.network, bringing me to the user dashboard.
