### ISSUE TITLE
in insertContent mode standard, standardsidebar, shaded and shadedsidebar textboxes should have <p/> inside <div/> like educational textboxes

### ISSUE THREAD

**Issue by thomasdumm** [pressbooks/pressbooks#3213]
In insertContent for standard, standardsidebar, shaded and shadedsidebar textboxes there should be `<p/>` tag inside `<div/>` like in the case of educational textboxes:

_pressbooks/assets/src/scripts/textboxes.js_

This would prevent leaving the textbox when pressing return and would lead to the same behavior as with educational textboxes.

<img width="408" alt="mceInsertContent" src="https://user-images.githubusercontent.com/3658808/222465858-332728cb-0661-4fc6-a47d-67d0855a80c2.png">

**Comment by SteelWagstaff** [comment]
Ready for release!
