### ISSUE TITLE
Issue with unreleased network manager dashboard footer text

### ISSUE THREAD

**Issue by tw77** [pressbooks/pressbooks#3228]
### Description

In the unreleased network manager dashboard (on dev networks and locally), we're seeing this footer text before the end of the page:

<img width="1266" alt="Screenshot 2023-03-07 at 3 54 02 PM" src="https://user-images.githubusercontent.com/44182629/223582369-65e8d2d5-fa6c-47ba-bb3a-ad292bc348ee.png">

### Steps to Reproduce

1. Navigate to https://dev.pressbooks.network/wp/wp-admin/network/admin.php?page=pb_network_page or equivalent as a super admin or network manager user.

**Expected behavior:** The footer text is at the bottom of the page.

**Actual behavior:** The footer text appears during the page.

**Comment by SteelWagstaff** [comment]
Fixed on dev networks. Ready for release.
