### ISSUE TITLE
No scroll in 'My Books' dropdown

### ISSUE THREAD

**Issue by tw77** [pressbooks/pressbooks#3231]
### Description

The dropdown menu of books under 'My Books' in the top nav bar is no longer scrollable. This is an obstacle when a user belongs to many books, exceeding the number that can be shown onscreen at once.

<img width="701" alt="Screenshot 2023-03-09 at 7 25 03 AM" src="https://user-images.githubusercontent.com/44182629/224071147-4ebca9d1-3f85-4333-b6de-8114431f00f7.png">

### Steps to Reproduce

1. Belong to many books (30 or more to replicate at 100% zoom)
2. Hover over 'My Books' in the top nav bar of the dashboard.

**Expected behavior:** We can scroll up and down the 'My Books' dropdown menu.

**Actual behavior:** We don't have the ability to scroll up and down this list.

**Comment by SteelWagstaff** [comment]
We fixed this previously in https://github.com/pressbooks/pressbooks/issues/1901. See https://github.com/pressbooks/pressbooks/pull/1906 + https://github.com/pressbooks/pressbooks/pull/1900

**Comment by tw77** [comment]
Fix deployed and confirmed working.
