### ISSUE TITLE
Certain dashicons not appearing in the Visual Editor toolbar

### ISSUE THREAD

**Issue by tw77** [pressbooks/pressbooks#3232]
### Description

Four dashicons in the Visual Editor toolbar are broken / not appearing:

<img width="938" alt="Screenshot 2023-03-09 at 7 36 57 AM" src="https://user-images.githubusercontent.com/44182629/224074775-e2e6ca32-9089-42ea-9a14-4e1eec774848.png">

These four are affected:

- Apply Class
- Convert MS Word Footnotes
- Insert LaTeX
- Insert Glossary Term

**Comment by arzola** [comment]
This is interesting, I'll look into this I think I have an idea

**Comment by tw77** [comment]
Fix deployed to all networks and confirmed working.
