### ISSUE TITLE
Book creation for super admins / network managers unintentionally limited by network setting

### ISSUE THREAD

**Issue by tw77** [pressbooks/pressbooks#3241]
### Description

There is a bug at the moment where unchecking "Allow registered users to create and clone new books" in **Network Settings > Book & User Registration Settings** also removes the ability for super admins / network managers to create new books, hiding the Create Book buttons from them in the top nav and the dashboard.

This network setting is only intended to limit regular users from book creation, but it is being applied to super admins / network managers as well.

With this network setting unchecked, directly navigating to the book creation URL as a super admin / network manager does not work either, instead showing "Registration has been disabled" or "You are logged in already. No need to register again!" depending on whether the "Allow user self-registration" setting is checked.

### Steps to Reproduce

1. Log in as a super admin / network manager.
2. Uncheck "Allow registered users to create and clone new books" in **Network Settings > Book & User Registration Settings** 
3. Try to create a book.

**Expected behavior:** As a super admin / network manager I still see the Create Book buttons in the top nav and the dashboard, and I still have the ability to create books, while regular users on the network don't have this ability.

**Actual behavior:** 
<img width="1421" alt="Screenshot 2023-03-13 at 8 30 07 AM" src="https://user-images.githubusercontent.com/44182629/224749160-36f054b8-debb-4026-a4dd-27bb33e2d876.png">
Nobody on the network has the ability to create books or see the buttons for book creation. Navigating to the book creation URL either shows "Registration has been disabled" or "You are logged in already. No need to register again!" depending on whether the "Allow user self-registration" setting is checked.

**Comment by tw77** [comment]
Testing fix on dev networks as a super admin with "Allow registered users to create and clone new books" unchecked, I notice that the Create Book button is visible again in the top nav and directs me to the intended URL.

However, the "Create a book" block in the "My Books" dashboard is still not appearing for me:  

<img width="1440" alt="Screenshot 2023-03-13 at 1 22 03 PM" src="https://user-images.githubusercontent.com/44182629/224823506-43f5af6b-0ac6-48e9-ab64-8183bb17a45d.png">

Also, I'd expect the "Clone Book" button in the top nav to appear in this scenario. That and the "Clone a book" block in the "My Books" dashboard aren't visible at the moment.

**Comment by tw77** [comment]
The fix works partially on dev networks as a super admin with "Allow registered users to create and clone new books" unchecked -- the "Create Book" button appears in the top nav and links to the intended URL -- however, the "Create a book" block in the "My Books" dashboard still isn't appearing at the moment:

<img width="1440" alt="Screenshot 2023-03-13 at 1 28 59 PM" src="https://user-images.githubusercontent.com/44182629/224824942-177def99-1fc2-41fc-9768-486aeef10b1a.png">

Also, in this scenario I'd expect the "Clone book" buttons to appear as well (the button in the top nav and the block in this "My Books" dashboard). These aren't appearing at the moment.

**Comment by SteelWagstaff** [comment]
@tw77 we have removed the create a book and clone a book options from the My Books menu by design. They should now only appear in the top nav bar for all users.

**Comment by SteelWagstaff** [comment]
oh wait, i think i misunderstood your comment and we're talking past each other. sorry. maybe we can discuss briefly tomorrow. i think what you're saying is that network managers don't see the create book block on the 'user dashboard' after these changes. that makes sense and we can fix that if we like (or just leave it off)

**Comment by tw77** [comment]
@SteelWagstaff I'm referring to the blocks on the dashboard itself, not the My Books menu.

**Comment by tw77** [comment]
Posted at the same time :) Yes, let's discuss tomorrow. Regardless of the decision about the blocks, I believe the "Clone Book" button in the top nav should always appear for network managers, but it isn't appearing there at the moment with "Allow registered users to create and clone new books" unchecked on the dev network.

**Comment by tw77** [comment]
Testing since merge on dev.pressbooks.network I notice a small remaining issue. The URL to create a book when the "Allow registered users to create and clone new books" setting is unchecked is correctly updated for the top nav "Create Book" button, leading super admins / network managers to `site-new.php` as intended.

But in this situation, the URL to "Create a book" in the dashboard block is incorrect, leading super admins / network managers to `new-site.php` instead (not a working link)

<img width="796" alt="Screenshot 2023-03-15 at 7 20 01 AM" src="https://user-images.githubusercontent.com/44182629/225337667-5dbd7ac3-973f-4f7f-b832-f7f0e4cb7c28.png">

**Comment by tw77** [comment]
All settings working as intended. The URL mentioned above is the only remaining issue.

**Comment by SteelWagstaff** [comment]
Fixed and working as expected in dev. Pressbooks/pressbooks is ready for release!
