### ISSUE TITLE
Misleading links to "Appearance" and "Pages" for individual books

### ISSUE THREAD

**Issue by tw77** [pressbooks/pressbooks#3246]
### Description

I've noticed that as a super admin or network manager, if I navigate to an individual book dashboard and from there, hover over the Administer Network top nav dropdown menu --

<img width="785" alt="Screenshot 2023-03-14 at 11 25 42 AM" src="https://user-images.githubusercontent.com/44182629/225102192-953cd25d-c6e9-4b5c-9bee-d274bc9057a3.png">

-- the links in this menu to Appearance and Pages don't direct to the network root site Appearance and Pages, but rather to:

**Appearance**: the book URL + `wp-admin/customize.php`
**Pages**: the book URL + `wp-admin/edit.php?post_type=page`

This leads to misleading options, as the Appearance customization menu intended for the root site is reachable, but takes the individual book as its "site to customize":

<img width="784" alt="Screenshot 2023-03-14 at 11 34 02 AM" src="https://user-images.githubusercontent.com/44182629/225104056-2b9ad918-5252-488a-be65-b4086eb87e44.png">

On the individual book's "Pages" a number of pages are brought over by default:

<img width="1248" alt="Screenshot 2023-03-14 at 11 36 56 AM" src="https://user-images.githubusercontent.com/44182629/225104749-e0956b8e-7277-41f1-809e-72b3b0a5223b.png">

### Steps to Reproduce

1. Navigate to an individual book dashboard as a super admin / network manager.
2. From the Administer Network dropdown menu in the top nav bar, navigate to Appearance or Pages.

**Expected behavior:** We're brought to the network root site Appearance or Pages.

**Actual behavior:** We're brought to Appearance or Pages for the individual book.

**Comment by SteelWagstaff** [comment]
Good catch. We need to fix this!

**Comment by SteelWagstaff** [comment]
Fixed and working as expected. Ready for release.
