### ISSUE TITLE
PressBooks CSS editor

### ISSUE THREAD

**Issue by sswettenham** [pressbooks/pressbooks#325]
Question:
If all themes are network enabled will PressBooks CSS editor theme override all sites or only active site?
Is it preferable to create a child theme for custom CSS?

Primary purpose was to modify CSS for tables of PBT theme, due to the quantity of tables in book.

(Already tried current help file: http://pressbooks.com/blog/pressbooks-new-feature-customize-your-css )

**Comment by greatislander** [comment]
The Pressbooks CSS editor only functions on a per-book basis. So you have two options:

1. Create a child theme.
2. Edit CSS for desired effects, then copy that customized CSS into the custom CSS editor of all books on your network.
