### ISSUE TITLE
Pages Don't Autosave

### ISSUE THREAD

**Issue by alexdryden** [pressbooks/pressbooks#3258]
### Prerequisites

* [x] Can you reproduce the behavior you wish to address with [all other plugins deactivated](http://codex.wordpress.org/Multisite_Network_Administration#Plugins)?
* [x] Are you running the [latest version of Pressbooks](http://github.com/pressbooks/pressbooks/releases/latest/) and the [latest version of WordPress](http://codex.wordpress.org/Upgrading_WordPress)?
* [x] Are you experiencing this issue with one of our built-in root or book themes?
* [x] Did you [perform a cursory search](https://github.com/issues?q=+is%3Aissue+repo%3Apressbooks%2Fpressbooks) to see if your bug or enhancement is already listed?

### Description

The WordPress autosave feature is disabled

### Steps to Reproduce
For existing pages
1. Shorten the autosave interval so that you don't have to wait so long between autosaves by setting `define( 'AUTOSAVE_INTERVAL', 30 );` in wp-config.php
2. Open up an existing, previously saved book content of any post type in any publication 
3. Make some changes to the main body text 
4. Wait longer than the interval you set in `AUTOSAVE_INTERVAL`
5. Note the text at the bottom of the editor pane where it says "last edited by..."
6. Inspect the browser session storage
7. Refresh the page

**Expected behavior:** 
After the autosave interval, the page should generate a new autosave as indicated in the bottom of the edit pane with the text "Draft saved at ..."
<img width="978" alt="Screenshot 2023-03-22 at 1 15 01 PM" src="https://user-images.githubusercontent.com/47127862/226985422-bebefefe-593c-426d-9c57-ad4a16250a27.png">

In the session storage there should be a key that starts with 'wp-autosave' and contains a json with the post content.
<img width="1466" alt="Screenshot 2023-03-22 at 1 17 29 PM" src="https://user-images.githubusercontent.com/47127862/226985935-85d50feb-e06b-400f-8446-d572b4d44640.png">

When you refresh the page you should see a message that says that there is a more recent autosave of this content.
<img width="1010" alt="Screenshot 2023-03-22 at 1 19 11 PM" src="https://user-images.githubusercontent.com/47127862/226986474-0e9d1744-0631-4540-b05f-21f2eb9270dd.png">

**Actual behavior:** 

Autosave is not generated in local session store or sent through heartbeat api. Instead, a popup is generated saying the content has changed. However, if the browser crashes or a network issue prevents users from saving their work when they have finished working on a chapter, the work is lost. 

I recall this being a feature folks talked about in the past, and we have books that have [Autosave] in their revision history. I don't recall this being mentioned as something that would disappear, so it seems like a bug. For what its worth, I was able to restore the autosave feature by commenting out the [line here](https://github.com/pressbooks/pressbooks/blob/7b7d3be450880c6af5cec7826142bc3c987e673e/inc/admin/laf/namespace.php#L638) that deregisters the heartbeat script. 

#### Root Blog Info

Root Blog ID: 1
Root Blog URL: https://iopn-dev.library.illinois.edu/pressbooks/

#### Browser

Platform: OS X
Browser Name: Firefox
Browser Version: 110.0
User Agent String: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:109.0) Gecko/20100101 Firefox/110.0

#### WordPress Configuration

Network URL: https://iopn-dev.library.illinois.edu/pressbooks/
Network Type: Subdirectory
Version: 6.1.1
Language: en_US
WP_ENV: Not set
WP_DEBUG: Enabled
Memory Limit: 64M

#### Pressbooks Configuration

Version: 6.9.2
Root Theme: Aldine
Root Theme Version: 1.19.0

#### Pressbooks Dependencies

Epubcheck: Installed
xmllint: Installed
PrinceXML: Installed
Saxon-HE: Installed

#### Must-Use Plugins

hm-autoloader.php: n/a

#### Network Active Plugins

Pressbooks: 6.9.2

#### Root Blog Active Plugins

Pressbooks: 6.9.2

#### Inactive Plugins

Akismet Anti-Spam: 4.2.5
Excalibur: 0.3.4
Hello Dolly: 1.7.2
WP-Matomo Integration: 1.0.27

#### Server Configuration

PHP Version: 8.1.17
MySQL Version: 10.6.12
Webserver Info: Apache/2.4.37 (rocky) OpenSSL/1.1.1k

#### PHP Configuration

Memory Limit: 256M
Upload Max Size: 2M
Post Max Size: 8M
Upload Max Filesize: 2M
Time Limit: 30
Max Input Vars: 1000
URL-aware fopen: On (1)
Display Errors: On (1)

#### PHP Extensions

OPcache: Zend
XDebug: Disabled
cURL: Supported
cURL Version: 7.61.1
imagick: Not Installed
xsl: Installed

**Comment by SteelWagstaff** [comment]
Hey @alexdryden you're exactly right in noting this has changed. Not sure when or how, but it's in our backlog to investigate and restore. See https://github.com/pressbooks/pressbooks/issues/3268

**Comment by alexdryden** [comment]
@SteelWagstaff , good to hear that it is already in the pipeline. [Heartbeat](https://make.wordpress.org/core/2013/01/19/autosave-and-post-locking/) is used to implement the autosave feature natively in vanilla wp, and it looks like heartbeat is getting deregistered in a way that is maybe broader than intended in the line I linked above. The release that contains that commit also times up with when I stop seeing autosave's in revision histories. 

We just had a network outage and an author lost some work, which lead me down this rabbit hole. I'd like to be able to go back to that author with some sort of solution. Do you have any insights into why the `add_pb_cloner_page()` needs to deregister the heartbeat there?

**Comment by SteelWagstaff** [comment]
Not sure TBH. Will ask our developers, who should know more about this than I do. I suspect it was an unintended side effect of a change we made without fully understanding the relationship between `Heartbeat` and the autosave feature.

**Comment by SteelWagstaff** [comment]
@alexdryden We released a fix for this in the latest release of Pressbooks (https://github.com/pressbooks/pressbooks/releases/tag/6.9.3). It was indeed related to heartbeat as you suspected. Here's the PR that resolved it: https://github.com/pressbooks/pressbooks/pull/3269. Appreciate you bringing this to our attention!
