### ISSUE TITLE
add support for Turkish 

### ISSUE THREAD

**Issue by hughmcguire** [pressbooks/pressbooks#326]
add support for Turkish fonts/global typography.

**Comment by greatislander** [comment]
I've added Noto Sans (and Serif) for Turkish support. I don't know if you have test content for this, but the update is live on Textopress for you to test.

**Comment by hughmcguire** [comment]
make it so, we'll ask the user to test.

**Comment by greatislander** [comment]
Live on production now.

**Comment by hughmcguire** [comment]
no news is good news? I will close this.
