### ISSUE TITLE
Update the Pressbooks API to use core REST API functions

### ISSUE THREAD

**Issue by greatislander** [pressbooks/pressbooks#328]
WordPress is moving swiftly towards the integration of REST API endpoints into WordPress core (see [here](https://make.wordpress.org/core/tag/rest-api/)). It's probably a good idea for us to investigate the possibility of updating our current API system to one built on the core REST API functionality.

**Comment by connerbw** [comment]
WordPress REST API tutorials (series):

http://code.tutsplus.com/series/introducing-wp-rest-api--cms-896

**Comment by connerbw** [comment]
An in-depth report and analysis on the WordPress REST API:

https://hmn.md/uploads/2016/01/Talking-to-25-of-the-Web-1.pdf

**Comment by connerbw** [comment]
Core devs discussing "passionately" (Ma.tt in the comments as well.) Progress on the REST API seems more volatile than anticipated.

http://wptavern.com/wp-rest-api-delayed-contributors-facing-gridlock

**Comment by greatislander** [comment]
@connerbw Going to close this in favour of new, more specific issues.
