### ISSUE TITLE
Critical error when updating user infos

### ISSUE THREAD

**Issue by SylDanh** [pressbooks/pressbooks#3281]
Hi

Thank you in advance for your answers.

### Prerequisites

* [X] Are you running the [latest version of Pressbooks](http://github.com/pressbooks/pressbooks/releases/latest/) and the [latest version of WordPress](http://codex.wordpress.org/Upgrading_WordPress)?
* [X] Are you experiencing this issue with one of our built-in root or book themes?
* [X] Did you [perform a cursory search](https://github.com/issues?q=+is%3Aissue+repo%3Apressbooks%2Fpressbooks) to see if your bug or enhancement is already listed?

### Description

**Expected behavior:** 

**Actual behavior:** 

When i try to update users info i got this error 
```
A critical error occurred on this site.

Learn more about debugging WordPress.
```
If i try to change site language, nothing happen.

But in my debug.log file, i got this 
```
[17-Apr-2023 09:01:53 UTC] PHP Warning:  Undefined array key "institution" in /var/www/html/wordpress/wp-content/plugins/pressbooks/inc/admin/laf/namespace.php on line 1733
[17-Apr-2023 09:01:53 UTC] PHP Fatal error:  Uncaught TypeError: Pressbooks\Sanitize\decode(): Argument #1 ($slug) must be of type string, null given, called in /var/www/html/wordpress/wp-content/plugins/pressbooks/functions.php on line 119 and defined in /var/www/html/wordpress/wp-content/plugins/pressbooks/inc/sanitize/namespace.php:211
Stack trace:
#0 /var/www/html/wordpress/wp-content/plugins/pressbooks/functions.php(119): Pressbooks\Sanitize\decode()
#1 /var/www/html/wordpress/wp-content/plugins/pressbooks/inc/sanitize/namespace.php(830): pb_decode()
#2 /var/www/html/wordpress/wp-content/plugins/pressbooks/inc/admin/laf/namespace.php(1733): Pressbooks\Sanitize\sanitize_string()
#3 /var/www/html/wordpress/wp-includes/class-wp-hook.php(308): Pressbooks\Admin\Laf\update_user_profile_fields()
#4 /var/www/html/wordpress/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters()
#5 /var/www/html/wordpress/wp-includes/plugin.php(517): WP_Hook->do_action()
#6 /var/www/html/wordpress/wp-admin/user-edit.php(157): do_action()
#7 /var/www/html/wordpress/wp-admin/network/user-edit.php(13): require('...')
#8 {main}
  thrown in /var/www/html/wordpress/wp-content/plugins/pressbooks/inc/sanitize/namespace.php on line 211
```

### System Information

![Screenshot 2023-04-17 at 11-18-41 Diagnostics ‹ Bienvenue sur e-publish — Pressbooks2](https://user-images.githubusercontent.com/35763563/232477130-acfa0dd2-8b27-4ca4-a887-84090b9253ea.png)

**Comment by SylDanh** [comment]
Hi, 

The error is due to the helper var  for institution field. 
In the french translation, there is a simple quote (University => L'université) which is not escaped, and that beak the following JavaScript code
```
<script>
	const element = document.querySelector(".user-description-wrap").parentNode; //Biographical Info input as reference
	element.insertAdjacentHTML('afterbegin', '<?php echo str_replace( [ "\r\n", "\r", "\n", "\t" ], '', $row ); ?>');
</script>
```

**Comment by tw77** [comment]
Thank you for flagging this error and noting this as the cause. We'll fix this bug. For Pressbooks tech team: this issue hasn't been replicable on production networks, staging or integrations, but it is replicable on dev networks at the moment.

**Comment by SteelWagstaff** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Pressbooks-Product-Backlog-60ae7d807f6e370010b3d5be/issues/pressbooks/pressbooks/3281?planning-poker) with Zenhub @arzola @fdalcin @richard015ar

**Comment by fdalcin** [comment]
Tested and works as expected on dev networks
