### ISSUE TITLE
Fix book information

### ISSUE THREAD

**Issue by greatislander** [pressbooks/pressbooks#329]
Right now our book information is stored as post meta on a custom post type. This adds an unnecessary layer of abstraction to accessing the book meta—first we need to get the post ID of custom metadata post which contains the book info, then we can get the book info. It would probably be better to migrate all book information to the `wp_options` table for each book.

**Comment by greatislander** [comment]
This needs to wait. Implementing using the WP Settings API is going to be a headache and I'd rather not rely on any other third-party field management plugins going forward. Best to track the progress of https://github.com/sc0ttkclark/wordpress-fields-api and re-implement once it gets merged into core.

**Comment by colomet** [comment]
Once you decided what to do, let me know and we will use the same approach in our plugin.

https://github.com/Books4Languages/pressbooks-metadata/issues/41

**Comment by greatislander** [comment]
Closing this, for the time being.
