### ISSUE TITLE
Issue with rendering LaTeX equations in glossary

### ISSUE THREAD

**Issue by tw77** [pressbooks/pressbooks#3304]
LaTeX equations included in glossary term definitions render as expected when glossary terms are added in the editor. This looks good:

<img width="715" alt="Screenshot 2023-05-03 at 8 41 01 AM" src="https://user-images.githubusercontent.com/44182629/235967147-c3ed295d-3e09-407b-a8f7-075e067c8a7f.png">

However, when we generate a **glossary list**, all definitions in the resulting page that include LaTeX equations just present the code for the equations; equations are not rendered here:

<img width="470" alt="Screenshot 2023-05-03 at 8 40 29 AM" src="https://user-images.githubusercontent.com/44182629/235967022-6b5f193a-346c-4b0a-8561-d8d06ca73a0a.png">

### Steps to Reproduce

1. Create a glossary term with a definition that includes an equation in [latex] shortcodes.
2. Click **Organize->Add Back Matter** to create a new piece of back matter for glossary terms.
3. Add your desired title for the glossary. 
4. Select **‘Glossary‘** from the Back Matter Type menu.
5. Leave the content blank and click **‘Create‘**
6. View the glossary.

**Expected behavior:** The equation in the definition is rendered on this page.

**Actual behavior:** The equation is not rendered and is shown in [latex] shortcodes.

**Comment by tw77** [comment]
Let's check if this applies to shortcodes generally

**Comment by tw77** [comment]
This doesn't seem to apply to shortcodes generally. [blockquote] and [textbox] shortcodes are being handled normally in this auto-generated glossary list definition:

<img width="387" alt="Screenshot 2023-05-03 at 12 51 57 PM" src="https://user-images.githubusercontent.com/44182629/236031766-f635aeb0-f969-4107-b510-31364edf6622.png">

I notice that in order for the LaTeX to render in the tooltip for a glossary term definition within a chapter, that chapter must include LaTeX elsewhere, outside of the glossary term. If not, the LaTeX in the definition doesn't render.

**Comment by SteelWagstaff** [comment]
Closing in favour of #3408
