### ISSUE TITLE
Feature Request - PB XML export/download icon

### ISSUE THREAD

**Issue by sswettenham** [pressbooks/pressbooks#332]
An Pressbooks XML icon hinted with more meaning?
![pb_export_icon](https://cloud.githubusercontent.com/assets/360534/12298945/e22df918-ba14-11e5-98c1-e2f3db02ece4.png)

**Comment by greatislander** [comment]
We decided against this. The files are named differently. Non-Pressbooks XML filenames have a different prefix, e.g∴

`Standard-Test-Book-1452704325._vanilla.xml` (vanilla WXR)

`Standard-Test-Book-1452704325.xml` (Pressbooks WXR)
