### ISSUE TITLE
sass and child themes

### ISSUE THREAD

**Issue by bdolor** [pressbooks/pressbooks#333]
I'm seeing some undesirable behaviour with child themes that don't use sass. https://github.com/BCcampus/pressbooks-textbook/issues/49 
Is sass now compulsory for theme developers?

**Comment by greatislander** [comment]
Okay, so two things were happening here.

1. We had an error in our code which was incorrectly loading generated CSS for your theme (https://github.com/pressbooks/pressbooks/commit/1d3056bd23f4382168df8d82f12b1356873ccec5)—and the paths to images were incorrect in that CSS (https://github.com/pressbooks/pressbooks/commit/bb29196bfdadd36d8cd2786be690214f03d40ed9). I have fixed both of these problems.

However on the PBT end, I'm confused about these two functions:

https://github.com/BCcampus/pressbooks-textbook/blob/dev/pressbooks-textbook.php#L319

https://github.com/BCcampus/pressbooks-textbook/blob/dev/themes-book/opentextbook/functions.php#L13

They both seem to do exactly the same thing—load your Textbook theme stylesheet AND the Pressbooks Book (Luther) stylesheet (which is also being imported within your Textbook theme's stylesheet). Am I missing something really obvious? For your Textbook theme, though, you should be able to get rid of the stylesheet enqueue function altogether. Pressbooks now detects if a child theme is installed in the Pressbooks Book functions file and enqueues that theme's stylesheet as well as the Pressbooks Book one for webbook structure. See:

https://github.com/pressbooks/pressbooks/blob/dev/themes-book/pressbooks-book/functions.php#L75

I hope this clarifies. In my testing, the two commits I made fixed the broken image issues when running Pressbooks Textbook. But I would suggest eliminating some of those redundant enqueues/imports on the Textbook side (the Textbook stylesheet is currently being enqueued twice, and the Pressbooks Book stylesheet is being imported by it and also enqueued twice).

To answer your question: SASS is not compulsory. However, we are introducing new features that rely on it so vanilla CSS themes will become less functional as time goes on (for example, they don't support the global typography support that we've added). That being said, changes we make shouldn't break CSS themes, so I appreciate the bug report.

**Comment by greatislander** [comment]
P.S. I'm going to do a release within the next 24 hours which will push this fix out to wordpress.org.

**Comment by bdolor** [comment]
thanks @greatislander  - I was looking at those redundant functions about 10 minutes ago thinking "what was I thinking?" — I have removed them and will be pushing out an update soon. I will endeavor to move OTB theme to SASS as well.

**Comment by greatislander** [comment]
Great, thanks!

**Comment by JackDougherty** [comment]
Thanks @bdolor and @greatislander. Looking forward to testing both of your updates soon.
