### ISSUE TITLE
Invisible Export Icon

### ISSUE THREAD

**Issue by sswettenham** [pressbooks/pressbooks#334]
Latest PB and WP:
1. Selected all format options for export.
2. Then trashed all visible icons
3. Result was as follows:
![invisible export](https://cloud.githubusercontent.com/assets/360534/12351409/9275a42e-bb7d-11e5-8719-b318792b933a.png)

**Comment by sswettenham** [comment]
ODT Option Export produces:
![export odt option output](https://cloud.githubusercontent.com/assets/360534/12351514/4b438552-bb7e-11e5-8b64-2b10397c7a5b.png)

**Comment by greatislander** [comment]
This has been fixed in the development branch.
