### ISSUE TITLE
new WP srcset ... breaks EPUB2.01 & 3 validation (yay!)

### ISSUE THREAD

**Issue by hughmcguire** [pressbooks/pressbooks#335]
"WordPress 4.4 will add native responsive image support by including `srcset` and `sizes` attributes to the image markup it generates." see: 
https://make.wordpress.org/core/2015/11/10/responsive-images-in-wordpress-4-4/

good for WordPress, keeping up with the universe.

unfortunately, because EPUB is a [redacted] [redacted] [redacted] specification .... 
`srcset` ... breaks EPUB validation. [redacted] [redacted] EPUB [redacted].

So, we'll need to intelligently strip out `scrset` tags from exports to maintain [redacted] EPUB (and MOBI) validity.

**Comment by greatislander** [comment]
So EPUB 3.0 doesn't support `srcset` either? Boo.

**Comment by hughmcguire** [comment]
our EPUB3 export throws the same error.

**Comment by greatislander** [comment]
Fixed.

**Comment by hughmcguire** [comment]
thanks ned. can you fix the IDPF and EPUB standard-making body as well pls?

**Comment by greatislander** [comment]
working on it
