### ISSUE TITLE
Add license exclusion Book API parameter option

### ISSUE THREAD

**Issue by richard015ar** [pressbooks/pressbooks#3363]
From: We added `licenses` GET parameters for the Book API endpoint. 
As a developer, I would like to exclude licenses by adding `-` sign, just like the title exclusion option. For example, to get all books except those with `CC BY` license, I would like to make the following GET call: `<BOOK_API_URL>?licenses[]=-CC BY`.

DoD: Implement the new Book API Parameter to exclude books with specific licenses.

**Comment by SteelWagstaff** [comment]
Tested and works as expected on staging. Ready for release.
