### ISSUE TITLE
add "highlight text" button to TinyMCE, with dropdown for color 

### ISSUE THREAD

**Issue by hughmcguire** [pressbooks/pressbooks#338]
This should inject:

`Text text <span style="background-color: XYZ">text text</span> text text.`

**Comment by hughmcguire** [comment]
bumping this up in priority.

**Comment by hughmcguire** [comment]
can we have a dropdown something like this one:
https://annotate.driftt.com/view?i=bj95tonptkuy9wn%2F2016-03-18_at_4.11_PM_(1).png%2F

?

**Comment by greatislander** [comment]
Okay, so I added the stock TinyMCE background colour control instead, but… we have too many things on the second row so it pushes a couple buttons to a new row, see:

<img width="751" alt="screen_shot_2016-03-22_at_11_06_29_pm" src="https://cloud.githubusercontent.com/assets/605361/13973597/1d4dab20-f083-11e5-9d1c-0d529a84e26d.png">

Thoughts?
