### ISSUE TITLE
fix & standardize image floats in all outputs

### ISSUE THREAD

**Issue by hughmcguire** [pressbooks/pressbooks#339]
- epub: avoid pixelation)
- pdf: big image ... float right/left ... should float (w a max-width)
- web: big image ... float right/left ... should float (w a max-width)

**Comment by hughmcguire** [comment]
@greatislander:
a. I have added partials for all of the above (in pressbooks/dev)
b. I have added support for these partials in 5 themes (in private-themes/dev)

So, could you:
1. merge a. to pressbooks/master
2. deploy production

THEN
3. merge b. to private-themes/master
4. deploy to production

Note, it must be done in that order ... otherwise, some themes will be broken.

**Comment by greatislander** [comment]
Done.
