### ISSUE TITLE
create new book page content/copy confusing ("site" vs "book") ... to change

### ISSUE THREAD

**Issue by hughmcguire** [pressbooks/pressbooks#340]
this might be a root theme issue... but:
the add new book language is very confusing to new users ... need to update to remove "site" & replace with "book" .... etc.

see:
https://annotate.driftt.com/view?i=h7by9ct69ugl44e%2F2016-01-20_at_1.57_PM.png

**Comment by greatislander** [comment]
Specify changes as needed and I'll proceed to make them.

**Comment by hughmcguire** [comment]
New registration of a user, must register a book, copy should be: 
https://annotate.driftt.com/view?i=iw9g7zk35ydw47g%2F2016-02-11_at_5.47_PM.png

New user/book reg activation page:
https://annotate.driftt.com/view?i=mjzpxfmuzx5jg7u%2F2016-02-29_at_6.05_PM.png

More to come on "add new book" copy..

**Comment by hughmcguire** [comment]
Add new book copy:
https://annotate.driftt.com/view?i=g8mhvhtv0vt6iet%2F2016-02-29_at_6.16_PM.png

**Comment by hughmcguire** [comment]
siging up for the first time through OAuth:
https://annotate.driftt.com/view?i=vgzx0n2gb2dehba%2F2016-03-01_at_11.40_AM.png

**Comment by greatislander** [comment]
Okay, all copy adjusted as follows.

Screen for initial registration:

<img width="1232" alt="1" src="https://cloud.githubusercontent.com/assets/605361/13440356/0bf89c84-dfc8-11e5-96ea-95f7a24a66b3.png">

New user activation screen (if you choose not to register your book on initial signup—this can't be overridden… yet):

<img width="1240" alt="2a" src="https://cloud.githubusercontent.com/assets/605361/13440390/2de07a38-dfc8-11e5-82c2-e14d0451337f.png">

Screen for registering your book on initial signup :

<img width="1237" alt="2b" src="https://cloud.githubusercontent.com/assets/605361/13440399/3a84a7be-dfc8-11e5-9065-0714173e8b3f.png">

New user + book activation screen:

<img width="930" alt="screen shot 2016-03-01 at 4 13 02 pm" src="https://cloud.githubusercontent.com/assets/605361/13440487/a9722cc8-dfc8-11e5-91ef-29ad6e707750.png">

Screen for registering an additional site _or_ registering your first book via OAuth:

<img width="1227" alt="3" src="https://cloud.githubusercontent.com/assets/605361/13440439/65c3e62e-dfc8-11e5-8dc4-c0c16e612c19.png">

**Comment by hughmcguire** [comment]
good.
