### ISSUE TITLE
Complete support for LaTeX in footnotes, glossary terms, TablePress tables

### ISSUE THREAD

**Issue by tw77** [pressbooks/pressbooks#3408]
As an author, I'd like to be able to include LaTeX equations in footnotes, glossary terms, and TablePress tables in my books in multiple formats.

There are cases where LaTeX equations in these elements aren't being rendered, exposing the `[latex]` shortcodes and code instead.

**Footnotes**: LaTeX in footnotes renders in webbooks, but not in PDF exports: https://github.com/pressbooks/pressbooks/issues/1993 

**Glossary terms**: LaTeX is rendered in a glossary term, but only if there's another LaTeX equation somewhere else in the chapter / page where that glossary term appears. LaTeX never renders in auto-generated Glossary Lists. https://github.com/pressbooks/pressbooks/issues/3304

**TablePress tables**: In PDF exports, LaTeX in TablePress tables isn't rendered (e.g. the PDF export of https://viva.pressbooks.pub/openmusictheory/chapter/major-scales/). In webbooks, LaTeX in a TablePress table only renders when there's a LaTeX equation somewhere else in the chapter / page where the table has been added.

**Comment by tw77** [comment]
The release of https://github.com/pressbooks/pressbooks/issues/3507 increases the scope of the issue with LaTeX failing to be parsed in glossary term definitions. 

It used to be possible to have LaTeX parsed within glossary term definitions in a webbook page, provided that a LaTeX equation was included elsewhere in the webbook page, outside of a glossary term definition. 

This workaround no longer works, as flagged by a network manager at LOUIS and noticed in a book that was relying on this approach. See https://staging.pressbooks.network/glossarylatex/chapter/chapter-1/ for an example.

(LaTeX equations in definitions within an auto-generated glossary list remain broken, but this is the same as before.)

**Comment by MichSpieler** [comment]
A recent ticket ([link](https://pressbooks.zendesk.com/agent/tickets/20345) for internal use) reports a similar issue for **Media attributions** at the end of chapters (works in webbook, but not in PDF exports) and **Captions** (works in webbook, but not in PDF exports). The work around for **Footnotes** (using $latex ... $ notation) does not work for Media attributions, but it does work for Captions.

**Comment by SteelWagstaff** [comment]
Requested by multiple users, most recently by users at UEN who are writing a math text and want to be able to include LaTeX expressions in glossary terms.

**Comment by cmurtagh** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Pressbooks-Product-Backlog-60ae7d807f6e370010b3d5be/issues/pressbooks/pressbooks/3408?planning-poker) with Zenhub @arzola @fdalcin @ho-man-chan @richard015ar

**Comment by cmurtagh** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Pressbooks-Product-Backlog-60ae7d807f6e370010b3d5be/issues/pressbooks/pressbooks/3408?planning-poker) with Zenhub @tw77

**Comment by richard015ar** [comment]
From our previous [Product Meeting Agenda doc](https://docs.google.com/document/d/16zFMx6so-27UQxhkGeOFMGBnAtIWESdsN4a5mij5QOA/edit):

> WordPress has a concept called shortcodes: https://codex.wordpress.org/Shortcode + https://codex.wordpress.org/Shortcode_API + https://kinsta.com/blog/wordpress-shortcodes/. Pressbooks uses shortcodes extensively: https://github.com/pressbooks/pressbooks/tree/dev/inc/shortcodes. See https://github.com/pressbooks/private/wiki/Shortcodes + https://guide.pressbooks.com/chapter/shortcodes/. They can get complicated with export formats. 
> Shortcodes can be processed within shortcodes, but you have to nest them properly (https://codex.wordpress.org/Shortcode_API#Nested_Shortcodes). If a shortcode is intended to permit other shortcodes in its output, the handler function can call apply_shortcode() recursively:
> function caption_shortcode( $atts, $content = null ) {
>     return '<span class="caption">' . apply_shortcode($content) . '</span>';
> }
> We started supporting some nested shortcodes: https://github.com/pressbooks/pressbooks/issues/1826 + https://github.com/pressbooks/pressbooks/pull/1836. More to do on this in future: https://github.com/pressbooks/ideas/issues/159. We should also replace do_shortcode with apply_shortcode throughout our project: https://github.com/pressbooks/pressbooks/issues/2183.    
> Ned notes: Gutenberg has some transform API tools to convert old shortcodes into new shortcodes. Didn’t have a way to handle nested shortcodes gracefully (he opened an issue).

**Comment by tw77** [comment]
Appears to be supported so far. Aiming to wrap up testing this morning

**Comment by tw77** [comment]
Works as expected across formats on dev.
