### ISSUE TITLE
Add Belgian universities to our institutions list

### ISSUE THREAD

**Issue by SteelWagstaff** [pressbooks/pressbooks#3423]
Jason Dufrasne has requested the addition of the following 5 French-speaking universities in Belgium to the institutions list available in Pressbooks:
1. Université Libre de Bruxelles (ULB)
2. Université Catholique de Louvain (UCLouvain)
3. Université de Namur (UNamur)
4. Université de Liège (ULiège)
5. Université de Mons (UMons).

**Comment by MichSpieler** [comment]
Added all 5 institutions to a test book and confirmed working as expected on the book homepage and in the network catalog. Ready for release!
