### ISSUE TITLE
Entries for pb_authors, pb_editors, etc. are not being cleaned up as expected in wp_blogmeta table

### ISSUE THREAD

**Issue by SteelWagstaff** [pressbooks/pressbooks#3449]
Authors are not displayed in the correct order in the catalog for open source users (i.e. users who are running Pressbooks and Pressbooks Network Catalog but not our private Pressbooks Network Analytics plugin & its data collector cron job).

First, it appears that we are not properly updating `pb_authors` in the `wp_blogmeta` table after book info is updated. For example, when a book's author is deleted/removed from book info, the corresponding record is not deleted from wp_blogmeta. Second, the catalog author display order is not the same as used in book info, on the book homepage or in the catalog when network analytics and its cron are working. I don't know why.

See https://github.com/pressbooks/pressbooks-network-catalog/issues/173 and this short video I made with Ed Beck, the open source user who reported the issue:

https://github.com/pressbooks/pressbooks-network-catalog/assets/13485451/ce993b87-aa02-4764-8967-f1f36eb83d40

DoD:
- [ ] Only the listed authors and editors in book info are displayed on the catalog listing page (when book is cloned or created new)
- [ ] wp_blogmeta is updated correctly when book info is updated (especially when users are _removed_ from pb_authors or pb_editors in book info)

We believe this is connected to https://github.com/pressbooks/pressbooks-network-catalog/issues/236 and https://github.com/pressbooks/pressbooks-network-catalog/issues/230

**Comment by MichSpieler** [comment]
Behaviour that could be connected to this was also reported in this ticket (for internal reference) [#16912](https://pressbooks.zendesk.com/agent/tickets/16912)

**Comment by MichSpieler** [comment]
Behaviour that could be connected to this was also reported in this ticket (for internal reference) [#17424](https://pressbooks.zendesk.com/agent/tickets/17424)

**Comment by MichSpieler** [comment]
Behaviour that could be connected to this was also reported in this ticket (for internal reference) [#17493](https://pressbooks.zendesk.com/agent/tickets/17493)

**Comment by MichSpieler** [comment]
Behaviour that could be connected to this was also reported in this ticket (for internal reference) [#17491](https://pressbooks.zendesk.com/agent/tickets/17491)

**Comment by SteelWagstaff** [comment]
It looks to me like we're cleaning up the existing blogmeta data for other values before updating, but don't do it for pb_authors and pb_editors and pb_contributors. Compare https://github.com/pressbooks/pressbooks/blob/ad4314ff3fdcce800cf63d91ee7addaaf8acbb23/inc/datacollector/class-book.php#L301-L311 
or https://github.com/pressbooks/pressbooks/blob/ad4314ff3fdcce800cf63d91ee7addaaf8acbb23/inc/datacollector/class-book.php#L285-L295
with 
https://github.com/pressbooks/pressbooks/blob/ad4314ff3fdcce800cf63d91ee7addaaf8acbb23/inc/datacollector/class-book.php#L348-L352
and 
https://github.com/pressbooks/pressbooks/blob/ad4314ff3fdcce800cf63d91ee7addaaf8acbb23/inc/datacollector/class-book.php#L470-L480

For some reason, I don't think old pb_authors and pb_editors and pb_contributors values are being removed consistently or as expected when the data collectors run.

**Comment by tw77** [comment]
Following the fix pushed to dev networks, I was able to fix an entry in a dev network catalog that had been affected by the issue where an unintended author name was permanently listed despite not being present in the Book Info / book metadata.

The book appeared like this in the catalog:

<img width="560" alt="Screenshot 2023-08-29 at 10 41 09 PM" src="https://github.com/pressbooks/pressbooks/assets/44182629/86e37c5a-4d03-4a4b-b2d8-73e67dbaf0c7">

Even though in Book Info, only one author was listed for the book:

<img width="392" alt="Screenshot 2023-08-29 at 10 41 19 PM" src="https://github.com/pressbooks/pressbooks/assets/44182629/99e096de-ead5-4605-b729-8beeb6b253dd">

I tried saving changes in Book Info after the change pushed to dev, and the entry in the dev network catalog updated correctly:

<img width="533" alt="Screenshot 2023-08-29 at 10 41 39 PM" src="https://github.com/pressbooks/pressbooks/assets/44182629/35a0da99-4791-486b-bc0a-796c59b4e4e6">

This is encouraging -- I'll test further before closing following the steps outlined in the fix.

**Comment by tw77** [comment]
Works as expected when adding/removing contributors and running the sync.
