### ISSUE TITLE
Correctly link footnotes on Word import

### ISSUE THREAD

**Issue by crism** [pressbooks/pressbooks#346]
When importing a single-chapter Word document with end-notes, the end notes and their references are converted. However, linking between them is incomplete.

The references have links of the form `<a href="#sdfootnote1sym">` and the footnotes themselves have links, around their numbers, of the form `<a href="#sdfootnote1anc">`, but each is missing the necessary anchors to make the links from the other work.

That said, it looks like #103 is mostly working, aside from this; importing a multi-chapter Word file did cause the end-notes to be distributed appropriately among the different chapters.

**Comment by hughmcguire** [comment]
note I wonder if this broke the Pressbooks footnote feature. To investigate.

**Comment by crism** [comment]
I’d be really surprised if my focused changes affected list styling as in #384, but I’m happy to help fix it however I can.

**Comment by hughmcguire** [comment]
@crism don't think they are related -- it might be something particular with the user's word doc.

also, note that there is a Pressbooks Convert Word Footnotes feature, see:
http://guide.pressbooks.com/chapter/footnotes-and-chapter-endnotes/

**Comment by crism** [comment]
Interesting, @hughmcguire, thanks; that will come in handy. Can we re-close this issue, do you think?
