### ISSUE TITLE
Contributor import hint displays as HTML (not rendered)

### ISSUE THREAD

**Issue by greatislander** [pressbooks/pressbooks#3501]
### Description

This hint: https://github.com/pressbooks/pressbooks/blob/940c928e8da2857fef617cad773a23ceb6e6a51a/inc/class-contributors.php#L577

Is not rendered as HTML but displays as HTML source.

### Steps to Reproduce

1. Visit Contributors editing page.

**Expected behavior:** See rendered HTML.

**Actual behavior:** See source.

<img width="431" alt="Screenshot 2023-10-28 at 2 11 03 PM" src="https://github.com/pressbooks/pressbooks/assets/605361/bd94c9fc-b05e-4cd5-a488-ad59561dd0b6">

#### Book Info

Book ID: 754
Book URL: https://integrations.pressbooks.network/sasstest/
Book Privacy: Public

#### Browser

Platform: OS X
Browser Name: Safari
Browser Version: 17.1
User Agent String: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.1 Safari/605.1.15

#### WordPress Configuration

Network URL: https://integrations.pressbooks.network/
Network Type: Subdirectory
Version: 6.3.2
Language: en_US
WP_ENV: staging
WP_DEBUG: Enabled
Memory Limit: 96M

#### Pressbooks Configuration

Version: 6.15.1
Book Theme: McLuhan
Book Theme Version: 2.26.1
Root Theme: Aldine
Root Theme Version: 1.19.1

#### Pressbooks Dependencies

Epubcheck: Installed
xmllint: Installed
PrinceXML: Not Installed
Saxon-HE: Installed

#### Must-Use Plugins

Bedrock Autoloader: 1.0.3
hm-autoloader.php: n/a
Register Theme Directory: 1.0.0
telemetry.php: n/a
WordPress Sentry: must-use-proxy

#### Network Active Plugins

Koko Analytics: 1.2.2
Lord of the Files: Enhanced Upload Security: 1.3.17
Object Cache Pro: 1.20.0
Pressbooks: 6.15.1
Pressbooks BISAC: 2.6.0
Pressbooks CAS Single Sign-On: 2.3.1
Pressbooks eCampus Ontario: 1.5.0
Pressbooks Network Analytics: 2.7.0
Pressbooks Network Catalog: 1.3.4
Pressbooks OIDC Single Sign-On: 2.3.1
Pressbooks Plugins Config: 1.8.0
Pressbooks Results for LMS: 2.5.1
Pressbooks Results for LMS: 1.4.2
Pressbooks SAML2 Single Sign-On: 2.4.1
Pressbooks Shortcode Handler: 1.1.0
Pressbooks Stats: 1.9.0
Pressbooks Whitelabel: 1.8.0
TablePress Extension: DataTables Buttons: 1.5
User Activation Keys: 4.6
WordPress Sentry: 6.27.0
WP Fail2Ban Redux: 0.9.1

#### Book Active Plugins

Koko Analytics: 1.2.2
Lord of the Files: Enhanced Upload Security: 1.3.17
Object Cache Pro: 1.20.0
Pressbooks: 6.15.1
Pressbooks BISAC: 2.6.0
Pressbooks CAS Single Sign-On: 2.3.1
Pressbooks eCampus Ontario: 1.5.0
Pressbooks Network Analytics: 2.7.0
Pressbooks Network Catalog: 1.3.4
Pressbooks OIDC Single Sign-On: 2.3.1
Pressbooks Plugins Config: 1.8.0
Pressbooks Results for LMS: 2.5.1
Pressbooks Results for LMS: 1.4.2
Pressbooks SAML2 Single Sign-On: 2.4.1
Pressbooks Shortcode Handler: 1.1.0
Pressbooks Stats: 1.9.0
Pressbooks Whitelabel: 1.8.0
TablePress Extension: DataTables Buttons: 1.5
User Activation Keys: 4.6
WordPress Sentry: 6.27.0
WP Fail2Ban Redux: 0.9.1

#### Inactive Plugins

Akismet Anti-spam: Spam Protection: 5.3
Candela Citation: 0.2.4
Enable Media Replace: 4.1.4
Excalibur: 0.7.0
H5P: 1.15.6
Hypothesis: 0.6.0
Parsedown Party: 1.2.1
Redirection: 5.3.10
Regenerate Thumbnails: 3.1.6
TablePress: 1.14
WP QuickLaTeX: 3.8.6

#### Server Configuration

PHP Version: 8.1.24
MySQL Version: 10.5.21
Webserver Info: nginx/1.24.0

#### PHP Configuration

Memory Limit: 256M
Upload Max Size: 25M
Post Max Size: 25M
Upload Max Filesize: 25M
Time Limit: 240
Max Input Vars: 1000
URL-aware fopen: On (1)
Display Errors: N/A

#### PHP Extensions

OPcache: Zend
XDebug: Disabled
cURL: Supported
cURL Version: 7.68.0
imagick: Not Installed
xsl: Installed

**Comment by SteelWagstaff** [comment]
Fixed and working as expected on dev networks: 
![Screenshot from 2023-11-27 15-07-03](https://github.com/pressbooks/pressbooks/assets/13485451/a2b2fcc0-682d-48c6-9626-ebd1424ed1a7)

Ready for release.
