### ISSUE TITLE
Buckram Bug: Paragraph indent setting not shared to prince PDFs

### ISSUE THREAD

**Issue by beckej13820** [pressbooks/pressbooks#3509]
### Prerequisites

* [x] Can you reproduce the behavior you wish to address with [all other plugins deactivated](http://codex.wordpress.org/Multisite_Network_Administration#Plugins)?
* [x] Are you running the [latest version of Pressbooks](http://github.com/pressbooks/pressbooks/releases/latest/) and the [latest version of WordPress](http://codex.wordpress.org/Upgrading_WordPress)?
* [ ] Are you experiencing this issue with one of our built-in root or book themes?
* [x] Did you [perform a cursory search](https://github.com/issues?q=+is%3Aissue+repo%3Apressbooks%2Fpressbooks) to see if your bug or enhancement is already listed?

### Description

I am working to create a custom book theme. I have found that no matter what I set the buckram variable [$para-indent](https://buckram.pressbooks.org/#variable-para-indent) the Prince export will always have 1em indents.

### Steps to Reproduce

1. Download the Buckram theme to get a minimally styled books
2. Add at least 2 paragraphs to the book
3. From the pressbooks theme editor add a line to the elements scss file making the indent 2 em
<img width="1189" alt="Screenshot 2023-11-05 at 6 55 52 PM" src="https://github.com/pressbooks/pressbooks/assets/29982981/03432711-24ca-4e99-911d-f853dd3f8362">
4. From the Pressbooks diagnostics page, insert the pagedjs and inspect an element that should now indented 2em instead of 1 em.
5. Notice that its still 1 em
<img width="854" alt="Screenshot 2023-11-05 at 6 53 02 PM" src="https://github.com/pressbooks/pressbooks/assets/29982981/223bbf70-c366-4b66-871a-e81ec6dba60b">

**Expected behavior:** 
I expect the indent should apply to web, prince, and epub

**Actual behavior:** 
Indent seems to only apply to webbook.

#### Book Info

Book ID: 95
Book URL: https://restoryingeducation.pressbooks.sunycreate.cloud/
Book Privacy: Public

#### Browser

Platform: OS X
Browser Name: Chrome
Browser Version: 119.0.0.0
User Agent String: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36

#### WordPress Configuration

Network URL: https://pressbooks.sunycreate.cloud/
Network Type: Subdomain
Version: 6.3.2
Language: en_US
WP_ENV: Not set
WP_DEBUG: Enabled
Memory Limit: 64M

#### Pressbooks Configuration

Version: 6.15.1
Book Theme: SUNY Press
Book Theme Version: 1.0
Root Theme: Aldine
Root Theme Version: 1.19.1

#### Pressbooks Dependencies

Epubcheck: Installed
xmllint: Installed
PrinceXML: Installed
Saxon-HE: Installed

#### Must-Use Plugins

hm-autoloader.php: n/a

#### Network Active Plugins

Editoria11y Accessibility Checker: 1.0.12
Git Updater: 12.3.1
Koko Analytics: 1.3.2
Limit Login Attempts Reloaded: 2.25.26
Multisite Plugin Manager: 3.1.6
Pressbooks: 6.15.1
Pressbooks Network Catalog: 1.3.3
Pressbooks Stats: 1.9.0
Unconfirmed: 1.3.6
User Switching: 1.7.0

#### Book Active Plugins

Editoria11y Accessibility Checker: 1.0.12
Git Updater: 12.3.1
Koko Analytics: 1.3.2
Limit Login Attempts Reloaded: 2.25.26
Multisite Plugin Manager: 3.1.6
Pressbooks: 6.15.1
Pressbooks Network Catalog: 1.3.3
Pressbooks Stats: 1.9.0
Unconfirmed: 1.3.6
User Switching: 1.7.0

#### Inactive Plugins

Candela Citation: 0.2.4
Excalibur: 0.7.0
H5P: 1.15.6
Hypothesis: 0.6.0
Parsedown Party: 1.2.1
Pressbooks Shortcode Handler: 0.1
Pressbooks Shortcode Handler: 1.0.1
TablePress: 2.2
WordPress Importer: 0.8.1
WP QuickLaTeX: 3.8.6

#### Server Configuration

PHP Version: 8.1.18
MySQL Version: 5.7.30
Webserver Info: Apache

#### PHP Configuration

Memory Limit: 256M
Upload Max Size: 150M
Post Max Size: 150M
Upload Max Filesize: 150M
Time Limit: 60
Max Input Vars: 5000
URL-aware fopen: On (1)
Display Errors: N/A

#### PHP Extensions

OPcache: Disabled
XDebug: Disabled
cURL: Supported
cURL Version: 7.86.0
imagick: Installed
xsl: Installed

**Comment by greatislander** [comment]
Slight correction: if you set the web theme options Paragraph Separation to "Indent" it will also override the custom `$para-indent` value. The reason for this is that Theme Options injects a `$para-indent` value of `1em` to the SCSS processor, which overrides any customization at the theme level. This is a significant limitation insofar as no theme can indent paragraphs by anything other than 1em.

I'm exploring solutions to this and will update this issue accordingly.

**Comment by SteelWagstaff** [comment]
@tw77 this can be tested with the Clarke theme with has a 2em para-indent value set. To test:
1. Go onto a dev network and create a book that has a chapter with multiple consecutive paragraphs. 
2. Change the book theme to Clarke
3. Set paragraph separation to 'Indent paragraphs' in Web, PDF, and Ebook theme options
![screenshot_from_2024-04-02_12-30-36_720](https://github.com/pressbooks/pressbooks/assets/13485451/8b0782af-17ad-4812-a791-56253c2c005a)
4. Check that the paragraph indentation in the webbook and export files is in fact 2em rather than the 1em default

**Comment by tw77** [comment]
This fix is ready for next release (appearing as 2em rather than 1em in webbook and export files for books using Clarke theme on the dev network now)
