### ISSUE TITLE
Question - Is wkhtmltopdf a viable PDF generator alternative for Pressbooks?

### ISSUE THREAD

**Issue by sswettenham** [pressbooks/pressbooks#351]
While mPDF has merit, I am wondering if wkhtmltopdf (http://wkhtmltopdf.org) would be a worthy alternative for Pressbooks?

**Comment by greatislander** [comment]
Simply put, no it isn't. It doesn't support loading comprehensive custom stylesheets, which is what mPDF and Prince use to differentiate print layout from web book layout.
