### ISSUE TITLE
Books - in catalog

### ISSUE THREAD

**Issue by colomet** [pressbooks/pressbooks#352]
![captura de pantalla 2016-02-12 a las 23 18 21](https://cloud.githubusercontent.com/assets/3929177/13022115/7f99f24c-d1df-11e5-9d4d-1f9970feeaca.png)
If i select several books in the catalog and i whant to show all of them, is working, but if i want to show just one, after I push the link: show in the catalog, that happen
![captura de pantalla 2016-02-12 a las 23 18 05](https://cloud.githubusercontent.com/assets/3929177/13022160/cc6f2150-d1df-11e5-8b0e-8b4568db3ebe.png)
and there is no book in the catalog

**Comment by greatislander** [comment]
Is this issue fixed for you in the latest development version of Pressbooks?

**Comment by greatislander** [comment]
@colomet Can you test this with the latest development version of Pressbooks? It is working properly in my testing.

**Comment by colomet** [comment]
sorry, but i do not know how to update correct the plugin from github. I did a disaster, and I´m fixing it.

**Comment by colomet** [comment]
yes , is it working. Thanks
