### ISSUE TITLE
Error with subdomain

### ISSUE THREAD

**Issue by obaninja** [pressbooks/pressbooks#353]
Hi, I am following this steps https://wordpress.org/plugins/pressbooks/installation/ to create a multi site .  I got stuck on number 13 It's showing the page can't be display for the new site

**Comment by greatislander** [comment]
Please refrain from opening duplicate issues. I have closed #354. Did you successfully [create a network](http://codex.wordpress.org/Create_A_Network) as per the instructions? Did you receive any error messages earlier in the process? It sounds like you may have not completed step 5 [here](https://wordpress.org/plugins/pressbooks/installation/).

**Comment by obaninja** [comment]
Hi Zimmerman,

Sorry for duplicating the issue.

I did complete it.  I didn't get any error message or where do  I check that.

Thanks

Emmanuel Baba-Lola
President,
Missions Aid Network;
Messenger,
Acts Ten Thirty-eight Ministries

**Comment by greatislander** [comment]
It sounds like you have not completed the installation of WordPress properly, or if you have, you have not installed and activated the Pressbooks plugin. Errors about pages which can't be found usually have to do with your [.htaccess](https://codex.wordpress.org/htaccess) file. My apologies, but we can't provide support for basic WordPress installation and usage.

**Comment by obaninja** [comment]
HI Ned,

I did complete the installation.  Please see the link
http://www.rabbonibooks.com/wp-signup.php?new=rabbonibooks.com.  I'll
appreciate ypur help

**Comment by greatislander** [comment]
Did you s

**Comment by obaninja** [comment]
Hi,

It was a subdomain I created

**Comment by greatislander** [comment]
We cannot support you any further with this. Sorry. It appears to be user error of some sort on your part.

**Comment by obaninja** [comment]
ok thanks

**Comment by obaninja** [comment]
Can you delete my full name and address in the previous chat
