### ISSUE TITLE
Contributor names in metadata always being listed in alphabetical order

### ISSUE THREAD

**Issue by tw77** [pressbooks/pressbooks#3565]
### Description

The recent release of https://github.com/pressbooks/pressbooks/issues/2749 has the overlooked side effect of enforcing alphabetical order for listed contributors in a given field. The following fields are affected in Book Info: Authors, Editors, Translators, Reviewers, Illustrators, and Contributors. The Chapter Authors field in Chapter Metadata has the same issue. 

Any contributors included are always listed alphabetically by name, unlike before where the order of names could be changed as needed.

If a book currently has contributors listed in a specific order in one of the affected fields, saving Book Info or the chapter will reset the listed names to alphabetical order.

### Steps to Reproduce

1. Try to list book or chapter authors (or book editors, translators, etc.) in a certain (non-alphabetical) order.
2. Save changes.

**Expected behavior:** A custom order of selected contributors in a field can be saved.

**Actual behavior:** Saving changes resets the order of selected contributors in a field to alphabetical order.

It is also possible to reproduce the issue by going to an existing test book with contributor names listed in non-alphabetical order and saving changes. Here's a video of this occurring with book author names after pressing save in Book Info:

https://github.com/pressbooks/pressbooks/assets/44182629/a246fde9-265f-4ddb-a86c-d4b39233d7e4

**Comment by greatislander** [comment]
Related, but for the old system: https://github.com/pressbooks/pressbooks/pull/1167

**Comment by vhartma2** [comment]
Adding support for resolution. We launch new text on 02/26/2024 and NEED this issue resolved. Thanks!

**Comment by SteelWagstaff** [comment]
Update from Ned:
> An improved web component is mostly done, see here: https://pressbooks-reorderable-multiselect.netlify.app/. I have to add a few more features to it— support for localizing the default strings and a few more affordances for assistive technology users. Plan on doing that tonight and then filing a PR to add it to the book info page and other spots.

**Comment by tw77** [comment]
The improved component is working well when I test it on the dev network. Changing the order of names in any of the fields using this component and saving changes works as expected: the custom order is reflected in webbooks, exports, and the network catalog.

I also see that the order of names in book metadata immediately prior to this improved component being deployed to the dev network is preserved following deploy (including when pressing save without making changes).

Ready to be included in the next release.
