### ISSUE TITLE
Unexpected placement for glossary term pop-up window and unexpected behaviour upon closing of the pop-up window

### ISSUE THREAD

**Issue by MichSpieler** [pressbooks/pressbooks#3572]
### Description

Several clients have commented on an unexpected behaviour with the glossary term pop-up window. They expect the pop-up modal to appear over the glossary term, but instead the modal appears at the top of the page (the reading position in the background is lost). Upon closing the modal, the user is taken back to the placement of the first instance of the glossary term.

### Steps to Reproduce for the location of the pop-up window

1. Create a glossary term in a longer chapter.
2. Click on the glossary term.
3. Close the pop-up window.

**Expected behavior:** the window view of the reading interface (in the background) does not change throughout the whole process.

**Actual behavior:** the window view jumps to the top of the page when the modal is opened and back to the glossary term when the modal is closed.

A second issue is that if the same term is included multiple times in a given chapter, focus is always returned to the first instance of the term upon closing the modal, even if the user launched the definition from say the second or third occurrence of that term.

### Steps to Reproduce for the location after closing the pop-up window

1. Create a glossary term in a longer chapter and reuse it further down in the text.
2. Click on the glossary term's second occurrence.
3. Close the pop-up window.

**Expected behavior:** after closing the pop-up window, the user returns to the location of the second occurrence of the glossary term.

**Actual behavior:** the user returns to the location of the first occurrence of the glossary term.

https://github.com/pressbooks/pressbooks/assets/13485451/b3d313db-987d-4d09-aaf0-3ecd1a518e15

Finally, if the glossary term is formatted and the shortcode around it is not (i.e. bolded, a `span` element is added between the two pieces of shortcode), the glossary term pop-up will not appear. [Steel's note: I think this may be a prexisting issue and is unrelated to recent changes?]

### Steps to Reproduce for the formatted glossary term

1. Create a glossary term
2. Make the glossary term bold (but not the short code)
3. Click on the glossary term.

**Expected behavior:** a pop-up window appears.

**Actual behavior:** nothing happens.

**Comment by SteelWagstaff** [comment]
Mark Lane from Oregon State notes
> The codepen has the two containers nested:

```
<div overlay, modal container, fixed position>
<div modal content, absolute position>
</div></div>
```

> The pressbooks version does not have the containers nested:

```
<div overlay opaque, absolute position></div>
<div glossary__definition modal content, absolute position></div>
```

> Because of the way they populate, if I update each class to a fixed position instead of absolute, the glossary modals populate without navigating to the top of the screen. I also tweaked the width and starting positions of the popup so they render better on mobile (for some reason, the modals were extending past the width of the page).

**Comment by greatislander** [comment]
@SteelWagstaff I believe this needs to be split into two issues. The fix for the first one is trivial and I've implemented it in https://github.com/pressbooks/pressbooks/pull/3594. Can the second part related to multiple occurrences of the same term be moved to a separate issue? I think it can be resolved in due course but I didn't want to hold up the fix for the first part.

EDIT: I've fixed the second part too.

**Comment by SteelWagstaff** [comment]
@tw77 @MichSpieler Issues one and two described in this issue should be addressed by Ned's PR (just merged to pressbooks/pressbooks) and should be available for testing on dev networks shortly. The last issue (described below) was not. I've opened a separate issue for that pre-existing bug: https://github.com/pressbooks/pressbooks/issues/3599

**Comment by tw77** [comment]
Working as expected, testing in a chapter (on a dev network with the fix) that includes multiple duplicate glossary terms. Focus remains in the expected place. Ready for release.
