### ISSUE TITLE
Footnotes continue numbering

### ISSUE THREAD

**Issue by nmdws** [pressbooks/pressbooks#359]
### Prerequisites
- [x] Can you reproduce the behavior you wish to address with [all other plugins deactivated](http://codex.wordpress.org/Multisite_Network_Administration#Plugins)?
- [x] Are you running the [latest version of Pressbooks](http://wordpress.org/plugins/pressbooks/) and the [latest version of WordPress](http://codex.wordpress.org/Upgrading_WordPress)?
- [x] Did you [perform a cursory search](https://github.com/issues?q=+is%3Aissue+repo%3Apressbooks%2Fpressbooks) to see if your bug or enhancement is already listed?
### Description

Currently when you add footnotes it adds a number and if you add additional footnotes on other chapters the numbering starts over. Would like to have the option or have a way to have the footnotes numbering continue and not start over for each chapter. Not sure if there modification to the code I can do right away or some type of change I can do to continue the footnote numbering.
### Steps to Reproduce
1. Add a footnote to a chapter
2. Add another footnote on another chapter
3. You will see how the footnotes numbering starts over on any chapter you create a footnote in

**Expected behavior:** [What you expected to happen]
The option to start number over each chapter (current) or footnotes can continue numbering no matter what chapter your on. 
**Actual behavior:** [What actually happened]
Footnotes start number from 1 on each chapter
### Versions

Pressbooks: 3.2.1
WordPress: 4.4.1
PHP: 5.4

You can get the version of Pressbooks from the readme.txt file in the Pressbooks plugin (usually located at `http://<yourdomain.tld>/wp-content/plugins/pressbooks/readme.txt`) and the version of WordPress from the readme.html file in the WordPress root directory (usually located at `http://<yourdomain.tld>/readme.html`). You can usually get your PHP version from your web host, or by using the [`phpversion()`](http://php.net/manual/en/function.phpversion.php) function.

**Comment by greatislander** [comment]
This is not an option at present, but would be a useful feature.

**Comment by nmdws** [comment]
Ok thanks. I will work on the code see if I can get to work

**Comment by hughmcguire** [comment]
note that you must get it to work across all outputs: 
- epub/mobi, pdf/prince, and web.

**Comment by bseeger** [comment]
This is a feature I'd like as well.  Can I help out at all @nmdws?   I have a user who is publishing a paper 'in chapters' and would really like this feature.

**Comment by greatislander** [comment]
Closing for now. Footnotes will be reviewed in a future sprint.
