### ISSUE TITLE
Cloner page is accessible even when users are not allowed to create or clone books

### ISSUE THREAD

**Issue by MichSpieler** [pressbooks/pressbooks#3603]
### Description

An open source user has reported that it is possible for users to clone books even when networks settings are set not allow users to register new sites. Users can still clone books by navigating to {network-url}/wp-admin/admin.php?page=pb_cloner.

### Steps to Reproduce

1. Set Network Settings "Allow new registrations" to "User accounts may be registered."
2. Register a new account (or log in with an existing user account)
3. Navigate to {network-url}/wp-admin/admin.php?page=pb_cloner
4. Enter a book source URL and fill other fields
5. Click "Clone"

**Expected behavior:** 
The page {network-url}/wp-admin/admin.php?page=pb_cloner should produce the same error message [Sorry, you are not allowed to access this page.] as for the page {network-url}/wp/wp-admin/network/site-new.php

**Actual behavior:** 
The {network-url}/wp-admin/admin.php?page=pb_cloner page is accessible and functional for users.

**Comment by tw77** [comment]
Fix is working as expected on dev and is ready for release.
