### ISSUE TITLE
Book Info > Language = German > PDF "Contents & "Chapter" not translated.

### ISSUE THREAD

**Issue by hughmcguire** [pressbooks/pressbooks#361]
### Prerequisites

* [x] Can you reproduce the behavior you wish to address with [all other plugins deactivated](http://codex.wordpress.org/Multisite_Network_Administration#Plugins)?
* [x] Are you running the [latest version of Pressbooks](http://wordpress.org/plugins/pressbooks/) and the [latest version of WordPress](http://codex.wordpress.org/Upgrading_WordPress)?
* [x] Did you [perform a cursory search](https://github.com/issues?q=+is%3Aissue+repo%3Apressbooks%2Fpressbooks) to see if your bug or enhancement is already listed?

### Description

Assuming we have translation files, then Book Info > Language = [language] ... should do some content translations ... specifically: 

On the TOC page, in PDF/EPUB: 
"Contents" >> "localization of 'Contents'" 

In certain Themes: 
"Chapter" >> "localization of 'Chapter'"

Surveying languages with OK Transifex coverage, the following have successful translations: 

Greek/ 
-PDF/Contents : YES | Chapter: NO 
-EPUB/ Contents: YES | Chapter: NO

Spanish/
-PDF/Contents : YES | Chapter: NO 
-EPUB/ Contents: YES | Chapter: NO

Korean/
-PDF/Contents : NO | Chapter: NO 
-EPUB/ Contents: NO | Chapter: NO

German/
-PDF/Contents : NO | Chapter: NO 
-EPUB/ Contents: NO | Chapter: NO

Dutch/
-PDF/Contents : NO | Chapter: NO 
-EPUB/ Contents: NO | Chapter: NO

French/
-PDF/Contents : YES | Chapter: NO 
-EPUB/ Contents: YES | Chapter: NO

### Steps to Reproduce

1. go to: https://pressbookstest.pressbooks.com/wp-admin/post.php?post=17&action=edit
2. set language = German
3. export PDF/EPUB

ON TOC page, "Contents" is not translated, nor is "Chapter" 

NOTE: it is 50% working in: Greek, Spanish, and French ...

**Comment by greatislander** [comment]
Please test and confirm that this is working for you, @hughmcguire.

**Comment by hughmcguire** [comment]
looks fixed. tx.
