### ISSUE TITLE
Contributor Type titles are not available for translation

### ISSUE THREAD

**Issue by SteelWagstaff** [pressbooks/pressbooks#3633]
When rendering the 'Contributors' back matter type in a book, a list of all contributors is displayed, sorted by contributor type. However, the title of each contributor type is rendered in English, no matter what the book language has been set to. The contributor title should be localized and should display the relevant text in the book's target language. It does not, as seen here:
![Screenshot from 2024-03-13 08-55-53](https://github.com/pressbooks/pressbooks/assets/13485451/b825d01f-e519-451b-9ffd-b680fd9baba8)

https://pressbooks.etsmtl.ca/modelisationcomportementacoustique/back-matter/353/

The blade template that renders this string is https://github.com/pressbooks/pressbooks/blob/c9044fbf2371ca6824a7d05203b240f25bc4f0a7/templates/posttypes/contributors.blade.php#L3

Localization needs to be able to handle both singular and plural forms of each Contributor title (i.e. Editor/Editors, Author/Authors, Translator/Translators, etc.)

At present, the Pressbooks project .pot file does not have singular/plural strings for each of the Contributor role titles. Some exist because the word is used elsewhere in the interface, but these do not exist consistently anywhere.

I believe the issue here is how to handle translation for dynamically generated strings in Blade templates.

**Comment by SteelWagstaff** [comment]
We discussed adding a helper method in the contributors class that uses a switch or match statement to define singular and plural forms of each of the supported contributor types:  https://github.com/pressbooks/pressbooks/blob/1cdbb3369201ac8e54c317c8ef89cd30822ace16/inc/class-contributors.php#L41-L47

**Comment by tw77** [comment]
Translations from https://github.com/pressbooks/pressbooks/pull/3675 appear as expected on dev.
