### ISSUE TITLE
Fix menu order for Pages in root site context

### ISSUE THREAD

**Issue by SteelWagstaff** [pressbooks/pressbooks#3638]
When I enter the root site context, the pages menu item has moved from its expected location/order:
(on dev network) -- jumped to bottom instead of being displayed between appearance & plugins
![Screenshot from 2024-03-14 10-46-42](https://github.com/pressbooks/pressbooks-multi-institution/assets/13485451/5f9b19ec-6722-48d3-bfa0-06d670b06262)
(on integrations) -- stays in between appearance and plugins
![Screenshot from 2024-03-14 10-46-29](https://github.com/pressbooks/pressbooks-multi-institution/assets/13485451/34c6e2f3-a9b4-4128-81bd-98544b6879c1)

To reproduce: visit https://dev.pressbooks.network/wp/wp-admin/edit.php?post_type=page and click the pages link from the admin dashboard. Notice that the location of the pages menu item moves to the bottom of the list. This shouldn't happen.

Perform the same actions at https://integrations.pressbooks.network/wp/wp-admin/edit.php?post_type=page to see expected behaviour.

See https://us02web.zoom.us/rec/share/Ci9NJWHwtMeWfP75D49m9gId1PDbsW1-I-T9LYuuDdk4UgdMn_K1be3H0WgJESYt.GhOUM_Y4SvJ7xVRN for a brief demonstration.

_Originally posted by @SteelWagstaff in https://github.com/pressbooks/pressbooks-multi-institution/issues/96#issuecomment-1998009159_

**Comment by richard015ar** [comment]
This PR: https://github.com/pressbooks/pressbooks-multi-institution/pull/124

Is ready and working on Ricardodev, but I will wait for the [Code Improvements](https://github.com/pressbooks/pressbooks-multi-institution/issues/76) to include those changes there.

I extended my PR to add more changes, described in https://github.com/pressbooks/pressbooks-multi-institution/pull/124.

**Comment by tw77** [comment]
Works as expected on dev.pressbooks.network.
