### ISSUE TITLE
Let user select password when registering

### ISSUE THREAD

**Issue by greatislander** [pressbooks/pressbooks#364]
### Prerequisites

* [x] Can you reproduce the behavior you wish to address with [all other plugins deactivated](http://codex.wordpress.org/Multisite_Network_Administration#Plugins)?
* [x] Are you running the [latest version of Pressbooks](http://wordpress.org/plugins/pressbooks/) and the [latest version of WordPress](http://codex.wordpress.org/Upgrading_WordPress)?
* [x] Did you [perform a cursory search](https://github.com/issues?q=+is%3Aissue+repo%3Apressbooks%2Fpressbooks) to see if your bug or enhancement is already listed?

### Description

When user registration is open, users must await a confirmation email with a generated password before they can activate their account. They should be able to pick their own password when registering.

### Steps to Reproduce

1. Register as a new user.

**Desired behavior:** Choose a username and password; await confirmation email.

**Actual behavior:** Choose a username; await confirmation email with password.

### Versions

Pressbooks: 3.2.0
WordPress: 4.4.2
PHP: 5.6

**Comment by hughmcguire** [comment]
1. copy confusing again, can we fix this: 
https://annotate.driftt.com/view?i=alug61ue5rw7rr5%2F2016-03-11_at_3.03_PM.png%2F

2. when I click to activate my account, I get this: 
https://annotate.driftt.com/view?i=yrq87erg1091gbr%2F2016-03-11_at_3.09_PM.png%2F

other than that, works as expected.
