### ISSUE TITLE
Please add following Turkish Universities to institutions list.

### ISSUE THREAD

**Issue by hkdemiralp** [pressbooks/pressbooks#3656]
### Prerequisites

* [x] Can you reproduce the behavior you wish to address with [all other plugins deactivated](http://codex.wordpress.org/Multisite_Network_Administration#Plugins)?
* [x] Are you running the [latest version of Pressbooks](http://github.com/pressbooks/pressbooks/releases/latest/) and the [latest version of WordPress](http://codex.wordpress.org/Upgrading_WordPress)?
* [x] Are you experiencing this issue with one of our built-in root or book themes?
* [x] Did you [perform a cursory search](https://github.com/issues?q=+is%3Aissue+repo%3Apressbooks%2Fpressbooks) to see if your bug or enhancement is already listed?

### Description
Could you please add the following Turkish universities to the institution list? Also it seems the Boğaziçi University is already in the "institutions.json" file, but it is not listed in `Book info -> Institutions`.
1. Ankara University
https://ankara.edu.tr/
2. Boğaziçi University
https://bogazici.edu.tr/
3. Gazi University
https://gazi.edu.tr/

In Turkish, these university names are written like this: Ankara Üniversitesi, Boğaziçi Üniversitesi, Gazi Üniversitesi 
### Steps to Reproduce

1. Go to "Book info -> institutions"
2. Those universities are not listed
3. 

#### Book Info

Book ID: 25
Book URL: https://ekitap.ankara.edu.tr/hareketli-bolumlu-protezler/
Book Privacy: Public

#### Pressbooks Configuration

Version: 6.17.1
Book Theme: McLuhan
Book Theme Version: 2.26.1
Root Theme: Aldine
Root Theme Version: 1.19.1

#### Server Configuration

PHP Version: 8.1.27
MySQL Version: 8.0.26
Webserver Info: Apache/2.4.57 (Red Hat Enterprise Linux) OpenSSL/3.0.7

**Comment by SteelWagstaff** [comment]
Thanks @hkdemiralp -- #3662 adds the two additional universities requested. These won't be available in production until the next release of Pressbooks, which should happen later this week.

**Comment by SteelWagstaff** [comment]
After clearing object cache for the network, I was able to select any of the three requested Turkish institutions from Book Info. They display on the book homepage as expected:
![Screenshot from 2024-04-02 16-48-56](https://github.com/pressbooks/pressbooks/assets/13485451/19da7ab2-a1c6-42d2-a1f3-255708eb6b87)

This is ready for inclusion in the next release of Pressbooks.
