### ISSUE TITLE
 Enabled a two-level TOC but not displayed on Table of Contents

### ISSUE THREAD

**Issue by sswettenham** [pressbooks/pressbooks#366]
### Description
 Enabled a two-level TOC but not displayed on Table of Contents

### Steps to Reproduce

1. Installed WP + PB3.1.2 via FTP upload
2. Created site
3. Updated PB 3.1.2 to 3.2.0
4. PBTextbook Theme > Options > Enabled a two-level TOC

**Expected behavior:**
H1 and H2 level headings to display in Table of Contents
**Actual behavior:**
Only H1 displayed

### Versions

Pressbooks: 3.2.0
WordPress: 4.4.2
PHP: 5.6.1

**Comment by greatislander** [comment]
@sswettenham Support for two-level TOC in exports must explicitly be enabled in themes. My guess is that Pressbooks Textbook theme may not support the two-level TOC in its export formats—but a reminder that that theme is not maintained by Pressbooks. IF you have the same issue with built-in themes, you should post a ticket here.

**Comment by sswettenham** [comment]
I have the same issue with all Pressbook themes (even when dropping all other plugins).

**Comment by greatislander** [comment]
@sswettenham Are you using mPDF export? Multilevel TOC has not been implemented in mPDF yet.

**Comment by hughmcguire** [comment]
And... we are not actively developing mPDF.

**Comment by sswettenham** [comment]
I installed mPDF and PBTextbook, but uninstalled these plugins and deactivated all other plugins except Pressbooks.  Webbook not displaying enabled two-level TOC.  Previous Pressbooks 3.1.2 did not have this issue.  Will now retest by uninstalling the plugins and reinstalling via WordPress Plugin Install.

**Comment by greatislander** [comment]
I can't reproduce this. The issue is only in the web output?

**Comment by sswettenham** [comment]
I can reproduce the issue when I install PB via FTP zip extract.  The issue is in the web output - no 2nd level TOC.
EPUB produces TOC but only H1 level.
I am now testing adding PB via WP plugin install.

**Comment by sswettenham** [comment]
Installed fresh WP 4.4.2 and PB 3.2 with Luther theme. Created a new site, then edited default chapter 1 in Main Body and added a Heading 2 in front of default paragraph (also added a Heading 3 after paragraph). Setup theme option to enable a two-level TOC.  Front webpage of site does not display a two-level TOC. EPUB3 does not display Chapter 1 in TOC. EPUB does display TOC.

**Comment by sswettenham** [comment]
Will now go backwards and install PB 3.1.2  and so on until I find the point at which TOC does work.

Noteworthy,  I upgraded an existing Pressbooks 3.1.2 installation where two-level TOC was working with PB 3.2 and TOC continues to display correctly for existing sites.  However, when creating a new site, a two-level TOC is not displayed on Frontpage. EPUB does display one-level TOC. Adding a Heading 1 in Chapter 1 text body does not promote the display of a two-level TOC.

**Comment by sswettenham** [comment]
PB 3.1.2 with two-level TOC displays HEADING 1 but not HEADING 2 in frontpage.  EPUB displays one-level TOC.

**Comment by sswettenham** [comment]
NOTE: A side issue - in Text > Organize > Show Title checkbox does not enable unless in edit page.

**Comment by sswettenham** [comment]
Conclusions:
1. Export for download not displayed on frontpage using a single chapter export to EPUB.
2. Show title checkbox in organize not sticking (when moving out to Dashboard).
3. Resolved two level TOC - only can use H1

**Comment by greatislander** [comment]
@sswettenham

> 1. Export for download not displayed on frontpage using a single chapter export to EPUB (luther theme).

That is a feature which is enabled by Pressbooks Textbook, so it wouldn't work unless you have Pressbooks Textbook enabled.

> 2. Show title checkbox in organize not sticking (when moving out to Dashboard).

That is a separate bug which should be filed as its own issue.

> 3. Resolved two level TOC - only use H1

That is the way the feature always worked. Two-level TOC = top level items (chapters) are given a second level by adding `<h1>` elements within them.

Please try to be clearer with your issue reports. If you are expecting a feature that is part of Pressbooks Textbook and you've disabled Pressbooks Textbook, please don't tell us about it—we can't do anything! And, most critically, please try to distinguish between bugs (e.g. something doesn't work or no longer works) and user error or confusion. Two-level TOC has never supported TOC entries for `<h2>` or `<h3>` elements. If that is a feature that you want, pull requests will be considered, but when our limited development resources are spent chasing bugs which aren't actually bugs it diverts time and energy which could be spent improving Pressbooks in other ways. I encourage you to consult our guide on [Contributing to Pressbooks](https://github.com/pressbooks/pressbooks/blob/dev/CONTRIBUTING.md) to make sure that your contributions are effective and efficient. Thanks for your attention to this.
