### ISSUE TITLE
How the hell to configure LTI?

### ISSUE THREAD

**Issue by fishfree** [pressbooks/pressbooks#3750]
The latest Pressbooks and Wordpress.
I both installed [pressbooks-lti-tool](https://wordpress.org/plugins/pressbooks-lti-tool/) and [pressbooks-lti-provider](https://github.com/pressbooks/pressbooks-lti-provider) and their dependencies.

When I follow [this tutorial](https://networkmanagerguide.pressbooks.com/chapter/configure-lti/#moodle:~:text=following%20tool%20URL%3A-,https%3A//%5BPRESSBOOKS%20DOMAIN%5D/format/lti/registration,-Then%2C%20press%20the) to access the LTI endpoint in my pressbooks, it showed error as below:
![image](https://github.com/user-attachments/assets/b69b6c26-ded4-4492-b5b2-ac11554a7166)

And also tried [this one](https://networkmanagerguide.pressbooks.com/chapter/configure-lti-results/#moodle), still no luck.

**Comment by SteelWagstaff** [comment]
hi @fishfree , the LTI plugin you're trying to work with has been deprecated and retired. The documentation you see is for network managers on our enterprise networks, which uses a different plugin (which is not openly licensed). If you're looking for an LTI 1.3 compatible solution, you can either try our enterprise hosting plans or look into https://github.com/celtic-project/pressbooks-lti-tool, which was developed by Stephen Vickers with funding from an open source Pressbooks user in Switzerland. We don't make or maintain that plugin, so you'd have to contact its maintainers with any questions about installation or configuration.
