### ISSUE TITLE
Cannot import docx file correctly

### ISSUE THREAD

**Issue by fishfree** [pressbooks/pressbooks#3751]
In a MS Word docx file, I applied Style-> Header 1 to several lines. Then imported it into Pressbooks, however, no chapters were extracted. All the content of the file was treated as a whole chapter with the title `__UNKOWN__` . I also tried set the outline level of a paragrpah in MS Word. The same result.
I change the docx file extension into zip, unzip it, open the word/document.xml file, there is `<w:outlineLvl>` or `<w:pStyle w:val="1"/>`, but no `H1` tag.

Did anyone succeed in importing a docx file? If so, pls share the method~.

**Comment by SteelWagstaff** [comment]
hi @fishfree this sounds like a support question or issue. We have a community forum for questions like this at https://pressbooks.community. You'd be welcome to ask this question there, where it will be more likely to be seen by other open source users like yourself. I'm closing this as it doesn't fit the criteria for the way we use GitHub issues.

**Comment by SteelWagstaff** [comment]
Also -- this ticket looks very similar to one you opened several years ago: https://github.com/pressbooks/pressbooks/issues/868. The advice you were given there is still relevant now.
