### ISSUE TITLE
Where is the Pressbooks OIDC SSO plugin?

### ISSUE THREAD

**Issue by fishfree** [pressbooks/pressbooks#3752]
I found nowhere to download the official Pressbooks OIDC SSO plugin described in [the official doc](https://networkmanagerguide.pressbooks.com/chapter/configure-sso-for-multiple-institutions/). Or is the doc outdated? If so, what's the alternative for configuring SSO for multiple institutions?

**Comment by SteelWagstaff** [comment]
hi @fishfree we have developed a plugin that we use to enable multialteral SSO for enterprise clients. However, it requires a paid integration with OpenAthens. We will not be releasing it with an open source license. I'm afraid you'd have to find or purchase your own solution for multilateral SSO. If you want to know about our enterprise hosting plans (which include this feature), you can request a quote or a demo via our marketing website: https://pressbooks.com/get-a-pressbooks-enterprise-quote/
