### ISSUE TITLE
Please add two Spanish Universities to institutions list

### ISSUE THREAD

**Issue by luis-r-izquierdo** [pressbooks/pressbooks#3785]
Could you please add the following two Spanish Universities to the [institutions list](https://github.com/pressbooks/pressbooks/blob/dev/symbionts/institutions/institutions.json)?

- University of Burgos (Universidad de Burgos). [https://www.ubu.es](https://www.ubu.es)
- University of Valladolid (Universidad de Valladolid). [https://www.uva.es](https://www.uva.es)

Thanks a lot!

**Comment by SteelWagstaff** [comment]
hi @luis-r-izquierdo -- thanks for the request. I opened a PR adding these two institutions today. It should be included in our next release. We'll let you know when those become available.

**Comment by arzola** [comment]
@luis-r-izquierdo you'll find those Spanish institutions on the latest PB release

**Comment by luis-r-izquierdo** [comment]
Thanks a lot!
