### ISSUE TITLE
class-sidebar.php critical error on getSubmenuBySlug( $settings_items, 'setup.php' )

### ISSUE THREAD

**Issue by Arodny** [pressbooks/pressbooks#3796]
### Prerequisites

* [x] Can you reproduce the behavior you wish to address with [all other plugins deactivated](http://codex.wordpress.org/Multisite_Network_Administration#Plugins)?
* [x] Are you running the [latest version of Pressbooks](http://github.com/pressbooks/pressbooks/releases/latest/) and the [latest version of WordPress](http://codex.wordpress.org/Upgrading_WordPress)?
* [x] Are you experiencing this issue with one of our built-in root or book themes?
* [x] Did you [perform a cursory search](https://github.com/issues?q=+is%3Aissue+repo%3Apressbooks%2Fpressbooks) to see if your bug or enhancement is already listed?

### Description
On seemingly all network admin pages in wp-admin there is a critical error caused by the `getSubmenuBySlug()` function within inc/admin/menus/class-sidebar.php (line 674).
The function return signature is of type array, yet, on line 644 earlier in that file, the call to `$this->getSubmenuBySlug( $settings_items, 'setup.php' )` returns null, violating the return signature and causing the following critical error:
```
Warning: Undefined array key 0 in /var/www/html/opentext/wp-content/plugins/pressbooks/inc/admin/menus/class-sidebar.php on line 681

Fatal error: Uncaught TypeError: Pressbooks\Admin\Menus\SideBar::getSubmenuBySlug(): Return value must be of type array, null returned in /var/www/html/opentext/wp-content/plugins/pressbooks/inc/admin/menus/class-sidebar.php:681 Stack trace: #0 /var/www/html/opentext/wp-content/plugins/pressbooks/inc/admin/menus/class-sidebar.php(644): Pressbooks\Admin\Menus\SideBar->getSubmenuBySlug() #1 /var/www/html/opentext/wp-content/plugins/pressbooks/inc/admin/menus/class-sidebar.php(619): Pressbooks\Admin\Menus\SideBar->reorderSettingsSubMenu() #2 /var/www/html/opentext/wp-includes/class-wp-hook.php(324): Pressbooks\Admin\Menus\SideBar->reorderSuperAdminMenu() #3 /var/www/html/opentext/wp-includes/plugin.php(205): WP_Hook->apply_filters() #4 /var/www/html/opentext/wp-admin/includes/menu.php(306): apply_filters() #5 /var/www/html/opentext/wp-admin/network/menu.php(118): require_once('...') #6 /var/www/html/opentext/wp-admin/admin.php(154): require('...') #7 /var/www/html/opentext/wp-admin/network/admin.php(13): require_once('...') #8 /var/www/html/opentext/wp-admin/network/plugins.php(11): require_once('...') #9 {main} thrown in /var/www/html/opentext/wp-content/plugins/pressbooks/inc/admin/menus/class-sidebar.php on line 681
```

This is caused by the function falling back to `return $submenu[0]` when it doesn't find the slug. In the case of `setup.php`, it doesn't find the slug so it falls back to the item with array key 0, however there is no array key 0, only array keys 1, 2, 3 ... (possibly because of the calls to unset() earlier?). This results in a null return.

Below is a JSON print of the $submenu array passed in `$this->getSubmenuBySlug( $settings_items, 'setup.php' )` - inc/admin/menus/class-sidebar.php:644:
```json
{"1":["Network Managers","manage_network","pb_network_managers","Network Managers"],"2":["Sharing & Privacy","manage_network","pressbooks_sharingandprivacy_options","Sharing and Privacy Settings"],"3":["SolidWP Licensing","manage_options","ithemes-licensing","SolidWP Licensing"],"4":["Google Analytics","manage_network_options","pb_analytics","Google Analytics"],"5":["Connect Matomo","manage_sites","wp-piwik\/classes\/WP_Piwik.php","Connect Matomo"],"6":["Root Site General Settings","manage_network","https:\/\/opentextbc.ca\/wp-admin\/options-general.php","Root Site General Settings"],"7":["Root Site Media Settings","manage_network","https:\/\/opentextbc.ca\/wp-admin\/options-media.php","Root Site Media Settings"],"8":["Root Site Privacy Settings","manage_network","https:\/\/opentextbc.ca\/wp-admin\/options-privacy.php","Root Site Privacy Settings"]}
```

I've applied a temporary fix to restore access to the admin dashboard (included below with some comments on the fix), but it would be great to figure out why this is happening and have a more permanent fix.

```php
// Updated the function's return signature to include the possibility of null
private function getSubmenuBySlug( array &$submenu, string $slug ): array|null {
	// $foundKey stores the array key of the first item in the array.
	$foundKey = null;
	foreach ( $submenu as $key => $item ) {
		// this happens only on the first loop, updated $foundKey with the key of the first item in the array.
		if(is_null($foundKey)) $foundKey = $key;
		if ( str_contains( $item[2], $slug ) ) {
			unset( $submenu[ $key ] );
			return $item;
		}
	}
	// $slug wasn't found, try to return $submenu[0] if exists, then $submenu[1], then the first item in the array with $submenu[$foundKey], then finally just return null.
	return $submenu[0] ?? $submenu[1] ?? $submenu[$foundKey] ?? null;
}
```

### Steps to Reproduce

1. Upgrade to pressbooks version 6.20.2
2. Visit any of the network pages, such as plugins

**Expected behavior:** Not encounter a critical error.
**Actual behavior:** Critical error. (see above for more info)

### System Information
I tested also with disabling all plugins except pressbooks and using the Aldine root theme and the issue is still present.
This issue came up when we upgraded from Pressbooks 6.17.1 to 6.20.2
Diagnostic info:
Wordpress: 6.6.2
Pressbooks: 6.20.2
Root Theme: Aldine 1.19.1
PHP: 8.1
Using Apache

#### WordPress Configuration
Network URL: https://opentextbc.ca/
Network Type: Subdirectory
Version: 6.6.2
Language: en_US
WP_ENV: Not set
WP_DEBUG: Enabled
Memory Limit: 64M

#### Pressbooks Configuration
Version: 6.20.2
Root Theme: Aldine
Root Theme Version: 1.19.1

#### Pressbooks Dependencies
Epubcheck: Installed
xmllint: Installed
PrinceXML: Installed
Saxon-HE: Installed

#### Must-Use Plugins
hm-autoloader.php: n/a

#### Network Active Plugins
Akismet Anti-spam: Spam Protection: 5.3.3
BCC Archived: 1.0.0
BCC Colummns: 1.0.0
BCC Kaltura: 1.0.0
Code Snippets: 3.6.5.1
Connect Matomo: 1.0.30
f5 Force SSL: 1.0.0
Pressbooks: 6.20.2
Pressbooks Stats: 1.6.5
Solid Security Pro: 8.5.0
TablePress: 2.4.2
Wordfence Security: 7.11.7

#### Root Blog Active Plugins
Akismet Anti-spam: Spam Protection: 5.3.3
BCC Archived: 1.0.0
BCC Colummns: 1.0.0
BCC Kaltura: 1.0.0
Code Snippets: 3.6.5.1
Connect Matomo: 1.0.30
f5 Force SSL: 1.0.0
Pressbooks: 6.20.2
Pressbooks Stats: 1.6.5
Solid Security Pro: 8.5.0
TablePress: 2.4.2
Wordfence Security: 7.11.7

#### Inactive Plugins
H5P: 1.16.0
Health Check & Troubleshooting: 1.7.1
Hypothesis: 0.7.3
Multisite Enhancements: 1.7.1
Pressbooks: 5.27.1
Pressbooks Stats: 1.6.3
WP QuickLaTeX: 3.8.8

#### Server Configuration
PHP Version: 8.1.29
MySQL Version: 10.5.22
Webserver Info: Apache/2.4.62 (Ubuntu)

#### PHP Configuration
Memory Limit: 750M
Upload Max Size: 1024M
Post Max Size: 1024M
Upload Max Filesize: 1024M
Time Limit: 600
Max Input Vars: 2000
URL-aware fopen: On (1)
Display Errors: On (1)

#### PHP Extensions
OPcache: Zend
XDebug: Disabled
cURL: Supported
cURL Version: 7.68.0
imagick: Installed
xsl: Installed

**Comment by cmurtagh** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Pressbooks-Product-Backlog-60ae7d807f6e370010b3d5be/issues/pressbooks/pressbooks/3796?planning-poker) with Zenhub @arzola @fdalcin @richard015ar @tw77

**Comment by arzola** [comment]
Definitely that piece of code can lead to a null value thank you for catching I'll add a better check for that, however I'm not able to reproduce it with only Pressbooks activated, I think some of the plugins you are using are adding some unexpected menu items, we'll send a fix that will check for array index before return and always return an array.

![image](https://github.com/user-attachments/assets/fa309b93-412d-4654-90ef-65933c6067c0)

**Comment by cmurtagh** [comment]
We will tackle the wrong data type/fatal error now based on the suggestion above, and have a more complete fix in the near future as we refactor some of this code.

**Comment by Arodny** [comment]
Thank you @arzola and @cmurtagh for the quick response and turnaround on this!

I'm not sure what was unique about our setup, as I did have all plugins deactivated except Pressbooks and Aldine theme, but perhaps there was a drop-in or something else I missed; I'll poke around again to see if I can determine what that was.

I'll keep my fix in place for now and keep an eye out for the next Pressbooks release! Thank you both again!

**Comment by richard015ar** [comment]
Hi @Arodny thank you for reporting and providing all the details for fixing it.
I was not able to get a `$submenu` array with no elements in position 0, however, I think it might be possible according to what you described, so I decided to propose [this fix](https://github.com/pressbooks/pressbooks/pull/3812). The team will review, test and eventually release this fix soon.

I'll keep you posted!
