### ISSUE TITLE
When a new book is created, its theme is set to "pressbooks-malala", which doesn't exist.

### ISSUE THREAD

**Issue by TangentFoxy** [pressbooks/pressbooks#3807]
### Prerequisites

* [x] Can you reproduce the behavior you wish to address with [all other plugins deactivated](http://codex.wordpress.org/Multisite_Network_Administration#Plugins)?
* [x] Are you running the [latest version of Pressbooks](http://github.com/pressbooks/pressbooks/releases/latest/) and the [latest version of WordPress](http://codex.wordpress.org/Upgrading_WordPress)?
* [x] Are you experiencing this issue with one of our built-in root or book themes?
* [x] Did you [perform a cursory search](https://github.com/issues?q=+is%3Aissue+repo%3Apressbooks%2Fpressbooks) to see if your bug or enhancement is already listed?

### Description

On a fresh install of Pressbooks, whenever a new book is created, its theme is set to a non-existent theme. The only themes that exist are those in the installation instructions, and they are network enabled.

### Steps to Reproduce

1. Install Pressbooks
2. Create a book
3. As you can see, a non-existent theme is selected: https://pressbooks.tangentfox.com/all-plugins-disabled/

**Expected behavior:** The book is created with the McLuhan theme ("pressbooks-book")

**Actual behavior:** The book is created with the "pressbooks-malala" theme, which doesn't exist.

#### Book Info

Book ID: 7
Book URL: https://pressbooks.tangentfox.com/all-plugins-disabled/
Book Privacy: Public

#### Browser

Platform: Windows 10
Browser Name: Chrome
Browser Version: 128.0
User Agent String: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36

#### WordPress Configuration

Network URL: https://pressbooks.tangentfox.com/
Network Type: Subdirectory
Version: 6.6.2
Language: en_US
WP_ENV: Not set
WP_DEBUG: Disabled
Memory Limit: 64M

#### Pressbooks Configuration

Version: 6.20.3
Book Theme: pressbooks-malala
Book Theme Version: 
Root Theme: Aldine
Root Theme Version: 1.19.2

#### Pressbooks Dependencies

Epubcheck: Installed
xmllint: Installed
PrinceXML: Installed
Saxon-HE: Installed

#### Must-Use Plugins

hm-autoloader.php: n/a

#### Network Active Plugins

Pressbooks: 6.20.3

#### Book Active Plugins

Pressbooks: 6.20.3

#### Inactive Plugins

WP QuickLaTeX: 3.8.8

#### Server Configuration

PHP Version: 8.2.24
MySQL Version: 11.5.2
Webserver Info: Apache/2.4.62 (Debian)

#### PHP Configuration

Memory Limit: 256M
Upload Max Size: 2M
Post Max Size: 8M
Upload Max Filesize: 2M
Time Limit: 30
Max Input Vars: 1000
URL-aware fopen: On (1)
Display Errors: N/A

#### PHP Extensions

OPcache: Zend
XDebug: Disabled
cURL: Supported
cURL Version: 7.88.1
imagick: Installed
xsl: Not Installed

**Comment by TangentFoxy** [comment]
I see under "Pressbooks Configuration" that "pressbooks-malala" has somehow been set, but I didn't change anything to do with book themes. This is a fresh install.

I am also very confused that under "Must-Use Plugins", there is `hm-autoloader.php: n/a` as the site is functioning normally and this plugin is in the correct place.

**Comment by alexdryden** [comment]
Malala is a closed source theme used for Pressbooks SaaS clients. See #3725 for the change. This change was one of the factors that motivated my questions in #3759.

**Comment by TangentFoxy** [comment]
Thank you for alerting me to these problems!

Edit: From looking at the affected file, it seems like I can temporarily add `define( 'WP_DEFAULT_THEME', 'pressbooks-book' );` to my `wp-config.php` to fix this until it is corrected.

**Comment by cmurtagh** [comment]
@TangentFoxy @alexdryden I'm not sure what I was thinking, and was stunned when I saw my name in git blame! Very sorry for the inconvenience here. We're pushing a new release out right away. Thank you for pointing this out.
