### ISSUE TITLE
LaTex PDF print not exporting correctly

### ISSUE THREAD

**Issue by cmurtagh** [pressbooks/pressbooks#3813]
A user is reporting that PDF exports with MathJax/LaTex is behaving differently, and it seems recent.  As described here:

https://pressbooks.community/t/pdf-print-not-exporting-correctly/2947/5

**Comment by cmurtagh** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Pressbooks-Product-Backlog-60ae7d807f6e370010b3d5be/issues/pressbooks/pressbooks/3813?planning-poker) with Zenhub @arzola @fdalcin @ho-man-chan @MichelleWeremczuk @richard015ar @tw77

**Comment by tw77** [comment]
This looks rough. Note the author hasn't added custom CSS and is using [latex] shortcodes normally, so this seems like a bug on our side. https://ecampusontario.pressbooks.pub/fundamentalsofbusinessmath/wp-admin/admin.php?page=pb_export

**Comment by tw77** [comment]
Other note: issue doesn't occur in September exports of the above book, it occurs in the October 18 export, so this definitely seems recent.

**Comment by tw77** [comment]
Ready for release. On dev, this fix solves the issue that emerged recently.

In a future sprint, it would be good to work on getting LaTeX expressions to follow the same font size set in the theme + the proper line-height (which isn't something that was in place before).
