### ISSUE TITLE
Pressbooks 6.21.3 Mc-Luhan theme not displayed

### ISSUE THREAD

**Issue by prbt2016** [pressbooks/pressbooks#3857]
I installed WP Multisite (version 6.6.1) with following process to install Pressbooks (using version 6.21.3)  : 

[](https://pressbooks.org/user-docs/installation/) 

on Centos 7 with PHP 8.1.2, MYSQL 5.5, Apache 2.2.

However, I can see only Aldine theme post installation . Under Administer Network -> Appearance -> Click on Change button under 'Active theme' section only Aldine is shown to be listed . 

![image](https://github.com/user-attachments/assets/ee60b244-eec9-49a0-87e4-88dc4e3f42fb)

FYI , I have network enabled both the themes i.e Aldine and  Mc-Luhan

![image](https://github.com/user-attachments/assets/04270f83-5797-44a8-81c5-0350b66ce541)

### Steps to Reproduce

1. Install WP multisite
2. Follow steps mentioned in https://pressbooks.org/user-docs/installation/ under section Manual Installation, Activate Plugins & Themes
3. Check under Administer Network -> Appearance -> Click on Change button under 'Active theme' 

**Expected behavior:** 
Mc-Luhan theme should also have been displayed

**Actual behavior:** 
Mc-Luhan theme isn't displayed.

#### Root Blog Info

Root Blog ID: 1
Root Blog URL: {{URL}}/{{TO}}/{{PRESSBOOKS}}

#### Browser

Platform: {{PLATFORM}}
Browser Name: Firefox
Browser Version: 115.0
User Agent String: Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:109.0) Gecko/20100101 Firefox/115.0

#### WordPress Configuration

Network URL: {{URL}}/{{TO}}/{{PRESSBOOKS}}
Network Type: Subdirectory
Version: 6.6.1
Language: en_US
WP_ENV: Not set
WP_DEBUG: Disabled
Memory Limit: 64M

#### Pressbooks Configuration

Version: 6.21.3
Root Theme: Aldine
Root Theme Version: 1.19.2

#### Pressbooks Dependencies

Epubcheck: Not Installed
xmllint: Installed
PrinceXML: Not Installed
Saxon-HE: Not Installed

#### Must-Use Plugins

hm-autoloader.php: n/a

#### Network Active Plugins

Pressbooks: 6.21.3

#### Root Blog Active Plugins

Pressbooks: 6.21.3

#### Inactive Plugins

Akismet Anti-spam: Spam Protection: 5.3.3
Hello Dolly: 1.7.2

#### Server Configuration

PHP Version: 8.1.2
MySQL Version: 5.5.62
Webserver Info: Apache

#### PHP Configuration

Memory Limit: 512M
Upload Max Size: 20M
Post Max Size: 8M
Upload Max Filesize: 20M
Time Limit: 200
Max Input Vars: 1000
URL-aware fopen: On (1)
Display Errors: N/A

#### PHP Extensions

OPcache: Zend
XDebug: Disabled
cURL: Supported
cURL Version: 7.67.0
imagick: Not Installed
xsl: Installed

I have masked some data in this due to security reasons.

**Comment by arzola** [comment]
Hello @prbt2016 

Book themes like McLuhan are available to use and activate under Book Settings Appearance menu, not at network level (like Aldine).

We are working on documentation updates to make that more clear.

You can read more about that here: https://guide.pressbooks.com/chapter/appearance/#howtochangeatheme



<img width="884" alt="Pasted_Image_2024-12-05__11_16 AM" src="https://github.com/user-attachments/assets/e9b335ff-aae0-4326-a529-9448dd5dc1a6">
