### ISSUE TITLE
PHP 7: deprecated constructor in SearchRegex class

### ISSUE THREAD

**Issue by r66r** [pressbooks/pressbooks#391]
### Prerequisites

* [X] Can you reproduce the behavior you wish to address with [all other plugins deactivated](http://codex.wordpress.org/Multisite_Network_Administration#Plugins)?
* [X] Are you running the [latest version of Pressbooks](http://wordpress.org/plugins/pressbooks/) and the [latest version of WordPress](http://codex.wordpress.org/Upgrading_WordPress)?
* [X] Are you experiencing this issue with one of our built-in root or book themes?
* [X] Did you [perform a cursory search](https://github.com/issues?q=+is%3Aissue+repo%3Apressbooks%2Fpressbooks) to see if your bug or enhancement is already listed?

### Description

Greetings,

This is the warning message I have on a WP Multisite + Pressbooks plugin installed on an Apache server with PHP 7:

Deprecated: Methods with the same name as their class will not be constructors in a future version of PHP; SearchRegex has a deprecated constructor in /var/www/html/wp1/wp-content/plugins/pressbooks/symbionts/search-regex/search-regex.php on line 13

### Steps to Reproduce

1. Install WordPress Multisite on a server with PHP 7
2. Install and activate Pressbooks plugin

### Versions

Pressbooks: 3.3.2
WordPress: 4.5.1
PHP: 7.0.5

**Comment by greatislander** [comment]
Thanks for the bug report—I identified this myself and will be updating our fork of this plugin to address this issue.

**Comment by r66r** [comment]
Great, thanks! It is always a pleasure to contribute.
