### ISSUE TITLE
Warnings with WordPress Widget Customizer

### ISSUE THREAD

**Issue by r66r** [pressbooks/pressbooks#392]
### Prerequisites

* [X] Can you reproduce the behavior you wish to address with [all other plugins deactivated](http://codex.wordpress.org/Multisite_Network_Administration#Plugins)?
* [X] Are you running the [latest version of Pressbooks](http://wordpress.org/plugins/pressbooks/) and the [latest version of WordPress](http://codex.wordpress.org/Upgrading_WordPress)?
* [X] Are you experiencing this issue with one of our built-in root or book themes?
* [X] Did you [perform a cursory search](https://github.com/issues?q=+is%3Aissue+repo%3Apressbooks%2Fpressbooks) to see if your bug or enhancement is already listed?

### Description

Greetings,

On a really fresh install, with everything activated by default, if I go to the Customizer of the main site, these warnings are displayed:

Warning: array_merge(): Argument #3 is not an array in /var/www/html/wp1/wp-includes/class-wp-customize-widgets.php on line 383

Warning: Invalid argument supplied for foreach() in /var/www/html/wp1/wp-includes/class-wp-customize-widgets.php on line 424

Maybe it's a problem with WordPress, maybe not. The fact is that there is no section for widgets in the customizer menu (only site identity, about us, menus and static front page).

### Steps to Reproduce

1. Install WordPress Multisite
2. Install and activate Pressbooks plugin
3. Add a new book
4. Go to main site (catalog)
5. Go to appearance > customize

The warnings are displayed in the preview.

### Themes

Root Theme: Pressbooks Publisher
Book Theme: Luther

### Versions

Pressbooks: 3.3.2
WordPress: 4.5.1
PHP: 7.0.5

**Comment by greatislander** [comment]
This is a recently-reported bug in WordPress. See: https://core.trac.wordpress.org/ticket/36660

**Comment by r66r** [comment]
OK, thanks fo information.
