### ISSUE TITLE
Invisible part setting has no effect

### ISSUE THREAD

**Issue by greatislander** [pressbooks/pressbooks#395]
### Prerequisites
- [x] Can you reproduce the behavior you wish to address with [all other plugins deactivated](http://codex.wordpress.org/Multisite_Network_Administration#Plugins)?
- [x] Are you running the [latest version of Pressbooks](http://wordpress.org/plugins/pressbooks/) and the [latest version of WordPress](http://codex.wordpress.org/Upgrading_WordPress)?
- [x] Are you experiencing this issue with one of our built-in root or book themes?
- [x] Did you [perform a cursory search](https://github.com/issues?q=+is%3Aissue+repo%3Apressbooks%2Fpressbooks) to see if your bug or enhancement is already listed?
### Description

The 'Invisible' checkbox for parts doesn't appear to affect their appearance in TOC/numbering.
### Steps to Reproduce
1. Check 'Invisible' while editing a part.
2. Save the part.
3. Export the book.

**Expected behavior:** Part is not listed in the TOC and doesn't increment the part counter.

**Actual behavior:** It does tho.
### Themes

Root Theme: Pressbooks Publisher
Book Theme: Luther
### Versions

Pressbooks: 3.4-dev
WordPress: 4.5
PHP: 5.6

**Comment by greatislander** [comment]
What is this supposed to do, and where?

**Comment by hughmcguire** [comment]
There is a reason and usecase for this, let me figure out what it is.
Here is the original specification: 

> "We've got a question about parts.  In a project, we have a few parts, but the first two chapters should not be part of any part.  Is there any way we can prevent "Part I" from appearing in the TOC and body of the book? "

So, you would use the Invisible Part function when you have a TOC that looks as follows: 

Dedication
Epigraph
TOC
Acknowledgements
Introduction
Chapter 1
Chapter 2
PART I: A PART
Chapter 3
Chapter 4
PART II: ANOTHER PART
Chapter 5
Chapter 6 

That is, Pressbooks chapters always belong to a Part, but sometimes you don't want that Part to be visible as a Part, or in the TOC ... so, you make it an invisible part.

**Comment by greatislander** [comment]
Okay. I don't think it works right now.

**Comment by greatislander** [comment]
Never mind, seems okay.
