### ISSUE TITLE
Export formats

### ISSUE THREAD

**Issue by ausapa** [pressbooks/pressbooks#404]
Hello
After updating Pressbook Textbook download formats options disappeared. I'm using the pluging with wordpress with the last version.
Does anybody know how to solve this issue?
Thanks so  Much
Aurelian

**Comment by greatislander** [comment]
Hi @ausapa, Pressbooks Textbook is not supported here—please post your issues on their repository: https://github.com/BCCampus/pressbooks-textbook. (FYI @bdolor.)
