### ISSUE TITLE
Search & replace showing blank screen.

### ISSUE THREAD

**Issue by hughmcguire** [pressbooks/pressbooks#407]
### Prerequisites

* [n/a] Can you reproduce the behavior you wish to address with [all other plugins deactivated](http://codex.wordpress.org/Multisite_Network_Administration#Plugins)?
* [x] Are you running the [latest version of Pressbooks](http://wordpress.org/plugins/pressbooks/) and the [latest version of WordPress](http://codex.wordpress.org/Upgrading_WordPress)?
* [x] Are you experiencing this issue with one of our built-in root or book themes?
* [x] Did you [perform a cursory search](https://github.com/issues?q=+is%3Aissue+repo%3Apressbooks%2Fpressbooks) to see if your bug or enhancement is already listed?

### Description

Search and Replace tool returning a blank screen.

### Steps to Reproduce

1.  login to the admin of a book
2. go to LEFT MENU >> TOOLS >> SEARCH AND REPLACE
3. the screen is blank

**Expected behavior:** [What you expected to happen]
to see the S&R tool page

**Actual behavior:** [What actually happened]
you see a blank page.

NOTE this is true on PB.com and .pub instances.

### Versions

Pressbooks: 3.4.0
WordPress:  4.5.1
PHP: production

**Comment by greatislander** [comment]
Closed in https://github.com/pressbooks/pressbooks/commit/de418573ef2005332c3c7cf4f19b77a53067a818.
