### ISSUE TITLE
Search & replace does not work as expected (searching front matter only?)

### ISSUE THREAD

**Issue by hughmcguire** [pressbooks/pressbooks#417]
### Prerequisites

* [n/a ] Can you reproduce the behavior you wish to address with [all other plugins deactivated](http://codex.wordpress.org/Multisite_Network_Administration#Plugins)?
* [y] Are you running the [latest version of Pressbooks](http://wordpress.org/plugins/pressbooks/) and the [latest version of WordPress](http://codex.wordpress.org/Upgrading_WordPress)?
* [n/a] Are you experiencing this issue with one of our built-in root or book themes?
* [y] Did you [perform a cursory search](https://github.com/issues?q=+is%3Aissue+repo%3Apressbooks%2Fpressbooks) to see if your bug or enhancement is already listed?

### Description
Search and replace is not finding strings of text it should find. It looks like the Content S&R is ONLY searching front matter? 

### Steps to Reproduce

1. go to: https://standardtest.pressbooks.com/wp-admin/post.php?post=29&action=edit
2. select some text, say: "who and what manner of man"
3. go to Tools > S&R
4. select "Search within Content"
4. add to the Search For field : "who and what manner of man"
5. press "search" 

**Expected behavior:** 
Expect to see the text string in the search results

**Actual behavior:** [What actually happened]
no search results are returned

NOTE: ... it looks like ? Front Matter searches are working as expected, but Chapter & backmatter content searches are not. So perhaps the "search across all content" isn't working fully?

**Comment by greatislander** [comment]
It does work, but memcached was causing problems. Try it again.
