### ISSUE TITLE
Global Typography Theme Options not present in Custom CSS? 

### ISSUE THREAD

**Issue by hughmcguire** [pressbooks/pressbooks#421]
### Prerequisites

* [x] Can you reproduce the behavior you wish to address with [all other plugins deactivated](http://codex.wordpress.org/Multisite_Network_Administration#Plugins)?
* [x] Are you running the [latest version of Pressbooks](http://wordpress.org/plugins/pressbooks/) and the [latest version of WordPress](http://codex.wordpress.org/Upgrading_WordPress)?
* [x] Are you experiencing this issue with one of our built-in root or book themes?
* [x] Did you [perform a cursory search](https://github.com/issues?q=+is%3Aissue+repo%3Apressbooks%2Fpressbooks) to see if your bug or enhancement is already listed?

### Description

Apperance >> Theme Options >> Global Typography  ... is not available when Custom themes are selected.

Should be? (Remind me if this is a known issue?) 

### Steps to Reproduce

1. Select  Custom CSS Theme
2. Go to Appearance >> Theme Options 

**Expected behavior:** [What you expected to happen]
expect to see Global Typography options

**Actual behavior:** [What actually happened]
don't see Global Typography options

**Comment by greatislander** [comment]
Not supported because Custom CSS uses compiled SCSS.
