### ISSUE TITLE
EPUB dependency pathname change in Ubuntu 16.04

### ISSUE THREAD

**Issue by JackDougherty** [pressbooks/pressbooks#422]
### Prerequisites

* [x] Did you [perform a cursory search](https://github.com/issues?q=+is%3Aissue+repo%3Apressbooks%2Fpressbooks) to see if your bug or enhancement is already listed?

### Description

My sys admin tells me that in Ubuntu 16.04, java is now located in /usr/share/java, rather than /usr/bin/java

If so, then consider changing or notifying users in this line:
https://github.com/pressbooks/pressbooks/blob/dev/readme.txt#L116

**Comment by JackDougherty** [comment]
sorry, this may be something specific to our system

**Comment by greatislander** [comment]
Yes, those are defaults, and as such are easily overridden. Depends on your distro (we use CentOS for pressbooks.com, others use RHEL, etc.).
