### ISSUE TITLE
Problems cloning the books - just information

### ISSUE THREAD

**Issue by colomet** [pressbooks/pressbooks#423]
### Prerequisites
- [ no ] Can you reproduce the behavior you wish to address with [all other plugins deactivated](http://codex.wordpress.org/Multisite_Network_Administration#Plugins)?
- [ yes ] Are you running the [latest version of Pressbooks](http://wordpress.org/plugins/pressbooks/) and the [latest version of WordPress](http://codex.wordpress.org/Upgrading_WordPress)?
- [ yes ] Are you experiencing this issue with one of our built-in root or book themes?
- [ yes ] Did you [perform a cursory search](https://github.com/issues?q=+is%3Aissue+repo%3Apressbooks%2Fpressbooks) to see if your bug or enhancement is already listed?
### Description

I use to use MultiSite Clone Duplicator or similar plugins if i need to make a copy of one book. It is a fast solution because we have some books that we use as a template. We use to work with no problems in the past, but i find today (if I'm not wrong, i did use that funcionality 1-2 months ago the last time) is not working. I know you do not provide support for problems with other plugins, and we can export the book and import but i just want to let you know. 

The good is i find a solution just working with other plugin WPMU DEV Cloner WordPress Plugin. It works, but not as usually, the screen is blank until it finish. But in the end, the book is clone it.
### Steps to Reproduce
1. [activate the cloning plugin]
2. [deactivate all the other plugins]
3. [clone one site]

**Expected behavior:** [to have the same site twice]

**Actual behavior:** [the new site it is just a new empty book, is like to create a new book]
### Themes

Root Theme: [Enter the root theme you are using here, e.g. "Pressbooks Publisher"]
Book Theme: [Enter the book theme you are using here, e.g. "Luther"]
### Versions

Pressbooks: [3.5.2]
WordPress: [4.5.2]
PHP: [5.6]

You can get the version of Pressbooks from the readme.txt file in the Pressbooks plugin (usually located at `http://<yourdomain.tld>/wp-content/plugins/pressbooks/readme.txt`) and the version of WordPress from the readme.html file in the WordPress root directory (usually located at `http://<yourdomain.tld>/readme.html`). You can usually get your PHP version from your web host, or by using the [`phpversion()`](http://php.net/manual/en/function.phpversion.php) function.

**Comment by greatislander** [comment]
Closing this, as we will be providing a built-in cloning feature in [4.1](https://github.com/pressbooks/pressbooks/milestone/27).
