### ISSUE TITLE
Create an export routine which produces Thin Common Cartridges

### ISSUE THREAD

**Issue by SteelWagstaff** [pressbooks/pressbooks#432]
### Description

I'd like to propose that we add an export routine which would result in a [Thin Common Cartridge](https://www.imsglobal.org/cc/ccv1p3/imscc_Overview-v1p3.html) file made up of each of the book's chapters/parts as simple weblinks. Bracken Mosbacker has already written [a plugin which will export Pressbooks titles as thin common cartridge files](https://github.com/lumenlearning/candela/tree/master/wp-content/plugins/candela-thin-exports), but his plugin uses LTI links and requires LTI integration. I'd like to propose making a simpler version of this plugin which links to book content as weblinks only and would like to add it to Pressbooks core. 

This would be useful for any user who would like to quickly bring a text (as a structured, organized set of chapters/pages) into a Learning Management System that supported/implemented thin common cartridges.

I think this would be a fairly simple plugin to make and have been in touch with Bracken about writing it myself (with a bit of advice from him). I'm probably at 60% completion, currently, and think I'll be able to have something testable by mid-July. I'd like some help understanding how/where export routines are handled currently in Pressbooks, and advice about the advisability of adding this to core.

**Comment by greatislander** [comment]
Hi @SteelWagstaff, this is great. I think this issue is blocked by #385 as there is currently no way for plugins to add export routines to Pressbooks (but we want to change that). Let's discuss in the near future.

**Comment by connerbw** [comment]
Code wise have a look at:

**Export modules:**
https://github.com/pressbooks/pressbooks/tree/dev/includes/modules/export
Create a directory, create a class that extends the abstract`Pressbooks\Modules\Export\Export`, implement `convert()` and `validate()`, look at other modules for examples.

**Adding to Form**
https://github.com/pressbooks/pressbooks/blob/dev/includes/modules/export/class-pb-export.php#L546
Add your class to `formSubmit()`
https://github.com/pressbooks/pressbooks/blob/dev/templates/admin/export.php#L66
Add your option to the HTML form.

As mentioned by @greatislander this is not a plugin approach but if you want to get started now this would be a reasonable way. Porting to a separate plugin would  mean tracking what is going on in #385 and copying the migration path.

Good luck.

**Comment by SteelWagstaff** [comment]
Sounds good to me. For now, I think we'll just write it as a plugin that adds the option to the export menu, in the same way that @bracken's plugin does now (see below), but it would be nice if we could add these export type to the main selection menu (and perhaps replace the deprecated ICML option):
![screen shot 2016-06-29 at 11 06 38 am](https://cloud.githubusercontent.com/assets/13485451/16459737/9f1fdcbe-3de9-11e6-9b35-6518f11b1124.png)
![screen shot 2016-06-29 at 11 06 45 am](https://cloud.githubusercontent.com/assets/13485451/16459734/9d22d3c6-3de9-11e6-949e-ee95a65df98a.png)

**Comment by SteelWagstaff** [comment]
Never noted it previously, but @bracken has a newer version of this plugin up on GitHub, which allows users to export Common Cartridge packages that use simple weblinks rather than LTI links: https://github.com/lumenlearning/candela/tree/master/wp-content/plugins/candela-thin-exports. Would be very useful to all users who intend to import texts into Learning Management Systems (especially relevant for higher ed users).

**Comment by greatislander** [comment]
@bracken I note you have a separate repo for this plugin ([lumenlearning/candela-then-exports](https://github.com/lumenlearning/candela-thin-exports)) which is not up to date with the version included in the Candela stack repo. Would you and @monkecheese be able to update the standalone repo with the latest commits and add it to [Packagist](https://packagist.org)? It would be great to have a Pressbooks add-on installable via Composer for the work I'm doing on plugin discovery and installation.

**Comment by bracken** [comment]
yeah, we can get the code updated. That Candela repo is kind of deprecated, so it's usually the stand-alone one that has the newer code. 

But, as I've mentioned before, that plugin wasn't really built with general-use in mind. Not because it can't be, but just because we haven't spent the time to make it smart for other people's use. The default option of LTI links wouldn't work for someone not using our LTI stuff.

What it should do then, for example, is check if that plugin is installed before allowing that option. I don't know when we'll get around to things like that.

**Comment by greatislander** [comment]
Okay, fair enough.

**Comment by SteelWagstaff** [comment]
If it’d be useful to others, I think we could make a stripped down version of Bracken’s plugin that only produced thin cc's with weblinks and make that available for Packagist. Would that be a wiser course of action, do you think, @bracken ?

**Comment by bracken** [comment]
That'd  be totally fine with me. I noticed I haven't put the license file on that repo, but we use MIT so it's all good. 

But, it'd be better if we (lumen) just improved the existing repo a bit and used that. Mostly because we're far less likely to spend time maintaining/updating some other repo that we don't actually use.

It's _is_ actually useful for others right now, it's just that the default export option wouldn't be.

**Comment by SteelWagstaff** [comment]
Agreed. Would you consider something so simple as changing the default value of 'use weblinks' to checked? Even that might go some way towards making it more readily useful for non-Lumen folks ...

**Comment by bracken** [comment]
Yeah, that might be fine. The whole UI of this thing is very utilitarian because our audience has been our internal team only. 

@monkecheese likes to do small side projects like this. With a little work he'd probably be able to make it nice enough for sharing. (code and UI-wise) He'd probably be able to get to it in the next couple weeks.

We don't really know anything about packagist though. I'm sure it's not too hard, but if we get it all cleaned up I'll try to get to that too.

**Comment by greatislander** [comment]
@SteelWagstaff Pressbooks support for Common Cartridge as a format on the export page is now possible (since #674). I touched base with @monkecheese about this yesterday—he's excited but doesn't have much time to work on this at present. Hoping we can get things moving soon.

**Comment by SteelWagstaff** [comment]
Great news! I may be able to do a little work on this, but would probably need some coaching/guidance in terms of code review. I'm willing but maybe not as competent as I need to be, as @bracken can probably attest :-)

**Comment by monkecheese** [comment]
This is something I'm also interested in working on @SteelWagstaff, though I am currently tied down on other projects and unable hop on this right now.  My goal is to have a solid, standalone plugin that does import/export routines for IMSCC files, and with these new changes, this should be achievable.  When I do start digging in, I'll let you know, as I may need your help with testing.  :)

**Comment by greatislander** [comment]
Just to clarify, this will be in a third-party plugin (`pressbooks-imscc`) which will be released by Lumen when it's done as @monkecheese has done the lion's share of the work on this. I'm going to close this issue and continue development here: https://github.com/lumenlearning/candela-utility/tree/imscc

**Comment by greatislander** [comment]
(Not to say that Pressbooks team members won't be contributing, just that it won't be a core export format.)
