### ISSUE TITLE
Learning Objectives not displaying properly in visual editor

### ISSUE THREAD

**Issue by zwhpressbooks** [pressbooks/pressbooks#439]
### Prerequisites

* [x] Can you reproduce the behavior you wish to address with [all other plugins deactivated](http://codex.wordpress.org/Multisite_Network_Administration#Plugins)?
* [x] Are you running the [latest version of Pressbooks](http://wordpress.org/plugins/pressbooks/) and the [latest version of WordPress](http://codex.wordpress.org/Upgrading_WordPress)?
* [x] Are you experiencing this issue with one of our built-in root or book themes?
* [x] Did you [perform a cursory search](https://github.com/issues?q=+is%3Aissue+repo%3Apressbooks%2Fpressbooks) to see if your bug or enhancement is already listed?

### Description

Learning Objectives textbox not formatted correctly in visual editor when inserted. Only occurring on some books and inconsistently, issue resolved itself in some books. Displaying fine in all exports.

Hugh says: pls take a look at this one ... as Tufts keeps asking about it, and it is occurring randomly on some books.

### Steps to Reproduce

**Expected behavior:** Learning Objectives textbox should display with black header and border

**Actual behavior:** Displaying as follows:
![learningobj](https://cloud.githubusercontent.com/assets/20113571/16774062/7013f1d2-4828-11e6-9144-cfb0c7e4cb33.png)

### Themes

Root Theme: Pressbooks Publisher
Book Theme: Tufts

### Versions

Pressbooks: 3.6.0
WordPress: 4.5.3
PHP: 5.6

**Comment by greatislander** [comment]
This appears to be a caching issue; I refreshed and it is displaying properly now.
