### ISSUE TITLE
Importer not uploading files

### ISSUE THREAD

**Issue by zwhpressbooks** [pressbooks/pressbooks#441]
### Prerequisites

* [x] Can you reproduce the behavior you wish to address with [all other plugins deactivated](http://codex.wordpress.org/Multisite_Network_Administration#Plugins)?
* [x] Are you running the [latest version of Pressbooks](http://wordpress.org/plugins/pressbooks/) and the [latest version of WordPress](http://codex.wordpress.org/Upgrading_WordPress)?
* [x] Are you experiencing this issue with one of our built-in root or book themes?
* [x] Did you [perform a cursory search](https://github.com/issues?q=+is%3Aissue+repo%3Apressbooks%2Fpressbooks) to see if your bug or enhancement is already listed?

### Description

Several instances of files failing to upload:
- mainly .docx, but one PB XML file and another WordPress XML have also failed
- files are under 10MB
- tried disabling storage quota then uploading which didn't help
- one import was into a private install with no storage limit
- happening inconsistently - I imported two other PB XML files into the same private install with no trouble
- fewer chapters selected doesn't have an effect
- either stays on second import screen (where you can select chapters to import) or shows this error:

![error1](https://cloud.githubusercontent.com/assets/20113571/16783074/8080af6a-4850-11e6-9966-c2c601e5fe4b.png)

### Steps to Reproduce

1. Go to import screen and select file as normal (will send you files separately)
2. On second page, select all or some chapter/parts/book info to import
3. Click on "Start"

**Expected behavior:** After pressing "Start", should load next screen as "Text"-->"Organize" with newly imported chapters present.

**Actual behavior:** After pressing "Start", either refreshes to same page with chapters deselected, or gives error shown in image above.

### Themes

Root Theme: [Enter the root theme you are using here, e.g. "Pressbooks Publisher"]
Book Theme: [Enter the book theme you are using here, e.g. "Luther"]

### Versions

Pressbooks: 3.6.0
WordPress: 4.5.3
PHP: [Enter PHP version here]

You can get the version of Pressbooks from the readme.txt file in the Pressbooks plugin (usually located at `http://<yourdomain.tld>/wp-content/plugins/pressbooks/readme.txt`) and the version of WordPress from the readme.html file in the WordPress root directory (usually located at `http://<yourdomain.tld>/readme.html`). You can usually get your PHP version from your web host, or by using the [`phpversion()`](http://php.net/manual/en/function.phpversion.php) function.

**Comment by zwhpressbooks** [comment]
@hughmcguire just double checked a ticket and the WordPress XML file was over 10MB so can leave that one off list.

**Comment by hughmcguire** [comment]
@zwhpressbooks ... could you separate out tickets for individual files (docx)

**Comment by zwhpressbooks** [comment]
@hughmcguire will do, first thing tomorrow.

**Comment by zwhpressbooks** [comment]
Update: solved PB XML case, so just .docx causing trouble. Re-writing ticket specific to that.

**Comment by hughmcguire** [comment]
note for @greatislander fyi: when xml files have special chars in the title (eg guajarati chars), the import fails.

closing this ticket.
