### ISSUE TITLE
Clicking the 'EXPORT YOUR BOOK' button executes a SASS error, blank screen and outputs no EPUB, EPUB3, or MOBI format.

### ISSUE THREAD

**Issue by bearkrust** [pressbooks/pressbooks#446]
### Prerequisites

* [ ] Can you reproduce the behavior you wish to address with [all other plugins deactivated](http://codex.wordpress.org/Multisite_Network_Administration#Plugins)?

**Answer**: Yes.

* [ ] Are you running the [latest version of Pressbooks](http://wordpress.org/plugins/pressbooks/) and the [latest version of WordPress](http://codex.wordpress.org/Upgrading_WordPress)?

**Answer**: Yes.

* [ ] Are you experiencing this issue with one of our built-in root or book themes?

**Answer**: I don't know if it is the themes or something else that is causing the SASS error.

* [ ] Did you [perform a cursory search](https://github.com/issues?q=+is%3Aissue+repo%3Apressbooks%2Fpressbooks) to see if your bug or enhancement is already listed?

**Answer**: Yes.

### Description

**Answer**: Clicking the 'EXPORT YOUR BOOK' button executes a blank screen and outputs no EPUB, EPUB3, or MOBI format (all wanted formats).

### Steps to Reproduce

**Answer**:
EPUB (for Nook, iBooks, Kobo etc.) Option
1. Clicked on 'Export' in WP sidebar menu.
2. Selected **only** 'EPUB (for Nook, iBooks, Kobo etc.)' option.
3. Clicked on big red 'EXPORT YOUR BOOK' button.
4. I was taken to this page (WP backend disappeared):
        ~/wp-admin/admin.php?page=pb_export&export=yes&_wpnonce=b7a8ef262d
5. That displayed this message:
        The [site name] page isn't working
        [site name] is currently unable to handle this request.
        HTTP ERROR 500
6. Clicked on the Chrome browser back arrow button.
7. I was taken back to a visible and functional WordPress backend (the Export page).
8. That returned and displayed this message:
      "There was a problem with SASS. Contact your site administrator" Error: parse error: failed at `content: $part" ";` (stdin) on line 177

Since the EPUB (for Nook, iBooks, Kobo etc.) didn't work, I tried the next option.

=====
MOBI (for Kindle) Option
1. Clicked on 'Export' in WP sidebar menu.
2. Selected **only** 'MOBI (for Kindle)' option.
3. Clicked on big red 'EXPORT YOUR BOOK' button.
4. I was taken to this page (WP backend disappeared):
        ~/wp-admin/admin.php?page=pb_export&export=yes&_wpnonce=b7a8ef262d
5. That displayed this message:
        The [site name] page isn't working
        [site name] is currently unable to handle this request.
        HTTP ERROR 500
6. Clicked on the Chrome browser back arrow button.
7. I was taken back to a visible and functional WordPress backend (the Export page).
8. That returned and displayed this message:
      "There was a problem with SASS. Contact your site administrator" Error: parse error: failed at `content: $part" ";` (stdin) on line 177

Since the MOBI (for Kindle) didn't work, I tried the next option.

=====
EPUB 3 (beta) Option
1. Clicked on 'Export' in WP sidebar menu.
2. Selected **only** 'EPUB 3 (beta)' option.
3. Clicked on big red 'EXPORT YOUR BOOK' button.
4. I was taken to this page (WP backend disappeared):
        ~/wp-admin/admin.php?page=pb_export&export=yes&_wpnonce=b7a8ef262d
5. That displayed this message:
        The [site name] page isn't working
        [site name] is currently unable to handle this request.
        HTTP ERROR 500
6. Clicked on the Chrome browser back arrow button.
7. I was taken back to a visible and functional WordPress backend (the Export page).
8. That returned and displayed this message:
      "There was a problem with SASS. Contact your site administrator" Error: parse error: failed at `content: $part" ";` (stdin) on line 177

Since the EPUB 3 (beta) didn't work, I tried another option out of curiosity and not want.

=====
 ICML (for InDesign) Option
1. Clicked on 'Export' in WP sidebar menu.
2. Selected **only** 'ICML (for InDesign)' option.
3. Clicked on big red 'EXPORT YOUR BOOK' button.
4. I was taken to this page (WP backend disappeared):
        ~/wp-admin/admin.php?page=pb_export&export=yes&_wpnonce=b7a8ef262d

5. That displayed this message:
        The [site name] page isn't working
        [site name] is currently unable to handle this request.
        HTTP ERROR 500
6. Clicked on the Chrome browser back arrow button.
7. I was taken back to a visible and functional WordPress backend (the Export page).
8. That returned and displayed this message:
      "There was a problem with SASS. Contact your site administrator" Error: parse error: failed at `content: $part" ";` (stdin) on line 177

Since the ICML (for InDesign) didn't work, I tried another option out of curiosity and not want.

=====
OpenDocument (beta) Option
1. Clicked on 'Export' in WP sidebar menu.
2. Selected **only** 'OpenDocument (beta)' option.
3. Clicked on big red 'EXPORT YOUR BOOK' button.
4. I was taken to this page (just the Pressbooks Export page in WP):
        ~/wp-admin/admin.php?page=pb_export&export_error=true
5. That displayed this message:
        Error: The export failed. See logs for more details.

I have no idea where these logs were and didn't care because I don't want that format anyway. The other 'Exotic formats' worked, even though I don't need these formats, either: XHTML, Pressbooks XML, and WordPress XML.

**Expected behavior:** 

**Answer**: I expected an EPUB, EPUB3, or MOBI version of my pretty basic and simple extremely short book.

**Actual behavior:**

**Answer**: I got nothing but a blank page with an error page.

### Themes

**Answer**:
Root Theme: Pressbooks Publisher
Book Theme: Luther (the default). I thought the theme was the problem. So, I switched to Fitzgerald which I actually like better, but the error still occurs.

### Versions

**Answer**:
Pressbooks: version 3.6.0.
WordPress: version 4.5.3.
PHP: version 5.5 (per Pressbooks WP listing FAQs, I added the following line to wp-config.php: $pb_minimum_php = '5.4';)

**Comment by greatislander** [comment]
@bearkrust I may be able to help you debug this. However, please note that running PHP 5.6 (our minimum *supported* version), I cannot reproduce this behaviour, so it could be an environment-related issue.

1. Navigate to your Pressbooks install's network admin and determine the relevant book ID. Specifically, go to `http://<yourpressbooksnetwork.com>/wp-admin/network/sites.php` and click the link to the book you are trying to export—you should see a URL like this: `http://<yourpressbooksnetwork.com>/wp-admin/network/site-info.php?id=2`. The book ID would be `2` in my example.
2. Paste the following URL into your browser, replacing `<id>` with the book ID you found in step 1: `http://<yourpressbooksnetwork.com>/wp-content/uploads/sites/<id>/scss-debug/localizations.scss`.
3. Reply to this thread and let me know what you see in step 2.

Thanks!

**Comment by bearkrust** [comment]
@greatislander Yeah, I knew it wasn't a supported php version per your FAQs on the plugins page, but I thought maybe you had documentation helping someone that maybe someone emailed you privately in the past when it was supported concerning this SASS issue. So, I do thank you for even attempting to assist me.

I did as instructed. And, it seems I have to contact my host provider because I'm getting this error message after executing step 2:

Internal Server Error

The server encountered an internal error or misconfiguration and was unable to complete your request.

Please contact the server administrator at [email] to inform them of the time this error occurred, and the actions you performed just before this error.

More information about this error may be available in the server error log.

Additionally, a 500 Internal Server Error error was encountered while trying to use an ErrorDocument to handle the request.

So, I hope they can fix the SASS issue.

**Comment by greatislander** [comment]
@bearkrust It's not likely that they will be able to as Pressbooks is a very unique use case. Can you turn on WP_DEBUG, try another EPUB export and then follow my steps again?

**Comment by bearkrust** [comment]
@greatislander Oh, I was just about shoot them an email. Okay so I did the following:

1. Opened wp-config.php file.
2. Edited define('WP_DEBUG', false); to be define('WP_DEBUG', true);.
3. Saved the file.
4. Repeated your steps using another EPUB export.
5. Result: same error.
5. Repeated your steps using the other EPUB exports I have, too.
6. Results: same error.

**Comment by greatislander** [comment]
@bearkrust Can you look in the folder `/wp-content/uploads/sites/<id>/scss-debug/` on your server and see if you see that file?

**Comment by bearkrust** [comment]
@greatislander There is actually no 'scss-debug' folder. This is all I have is a 'scss' folder.

**Comment by bearkrust** [comment]
Nevermind. I'm just going to call it quits. Thanks again.

**Comment by greatislander** [comment]
Hi @bearkrust, I am able to reproduce this on a fresh install (PHP 5.6) so I'm re-opening and will let you know once I figure out what's happening. Thanks for reporting.

**Comment by greatislander** [comment]
@bearkrust I just released an updated version of Pressbooks that fixes the issue. Thanks again for the bug report! https://wordpress.org/plugins/pressbooks/changelog/
