### ISSUE TITLE
Outside margin in Clarke differs from previous version

### ISSUE THREAD

**Issue by zwhpressbooks** [pressbooks/pressbooks#467]
### Prerequisites

* [x] Can you reproduce the behavior you wish to address with [all other plugins deactivated](http://codex.wordpress.org/Multisite_Network_Administration#Plugins)?
* [x] Are you running the [latest version of Pressbooks](http://wordpress.org/plugins/pressbooks/) and the [latest version of WordPress](http://codex.wordpress.org/Upgrading_WordPress)?
* [x] Are you experiencing this issue with one of our built-in root or book themes?
* [x] Did you [perform a cursory search](https://github.com/issues?q=+is%3Aissue+repo%3Apressbooks%2Fpressbooks) to see if your bug or enhancement is already listed?

### Description

Current Clarke theme version has 2cm outside margin, which has changed from 1.5cm in previous version. This change is significantly affecting books that previously had Clarke applied.

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** Outside margin should be 1.5cm

**Actual behavior:** Outside margin is 2cm

### Themes

Root Theme: [Enter the root theme you are using here, e.g. "Pressbooks Publisher"]
Book Theme: Clarke

### Versions

Pressbooks: 3.7.1
WordPress: 4.6
PHP: [Enter PHP version here]

You can get the version of Pressbooks from the readme.txt file in the Pressbooks plugin (usually located at `http://<yourdomain.tld>/wp-content/plugins/pressbooks/readme.txt`) and the version of WordPress from the readme.html file in the WordPress root directory (usually located at `http://<yourdomain.tld>/readme.html`). You can usually get your PHP version from your web host, or by using the [`phpversion()`](http://php.net/manual/en/function.phpversion.php) function.

**Comment by greatislander** [comment]
Blocked by #456.

**Comment by greatislander** [comment]
@zwhpressbooks It is my understanding that the outside marg
