### ISSUE TITLE
SCSS v2 documentation

### ISSUE THREAD

**Issue by greatislander** [pressbooks/pressbooks#471]
### Prerequisites
- [x] Can you reproduce the behavior you wish to address with [all other plugins deactivated](http://codex.wordpress.org/Multisite_Network_Administration#Plugins)?
- [x] Are you running the [latest version of Pressbooks](http://wordpress.org/plugins/pressbooks/) and the [latest version of WordPress](http://codex.wordpress.org/Upgrading_WordPress)?
- [x] Are you experiencing this issue with one of our built-in root or book themes?
- [x] Did you [perform a cursory search](https://github.com/issues?q=+is%3Aissue+repo%3Apressbooks%2Fpressbooks) to see if your bug or enhancement is already listed?
### Description

SCSS v2 themes need comprehensive documentation.
### Steps to Reproduce

Not applicable.
### Themes

Book Theme: Clarke
### Versions

Pressbooks: 3.8-dev
WordPress: 4.6.1
PHP: 5.6

**Comment by thomasdumm** [comment]
In Clarke V2 there are no variables for the following adjustments:
 
·         There are no variables to set the chapter subheading numberings (h1...h6) on a per heading level (currently no numbering of the chapter subheadings)
·         There is no variable for the textbox header text-align (currently fixed to centered)
·         There is no variable for the textbox header font-size (currently fixed to 0.9em)
·         There is no variable to set the part-number content (currently fixed to empty string)

**Comment by greatislander** [comment]
@thomasdumm Fixed a couple of these. https://github.com/pressbooks/pressbooks/commit/01f2029a78dce7279f8a634ef859f0c3de2b8987
