### ISSUE TITLE
Conduct accessibility & inclusivity audit of administration interface

### ISSUE THREAD

**Issue by greatislander** [pressbooks/pressbooks#487]
### Prerequisites
- [x] Can you reproduce the behavior you wish to address with [all other plugins deactivated](http://codex.wordpress.org/Multisite_Network_Administration#Plugins)?
- [x] Are you running the [latest version of Pressbooks](http://wordpress.org/plugins/pressbooks/) and the [latest version of WordPress](http://codex.wordpress.org/Upgrading_WordPress)?
- [x] Are you experiencing this issue with one of our built-in root or book themes?
- [x] Did you [perform a cursory search](https://github.com/issues?q=+is%3Aissue+repo%3Apressbooks%2Fpressbooks) to see if your bug or enhancement is already listed?
### Description

Conduct an audit of the Pressbooks administration interface for accessibility and inclusivity, including:
#### General
- [ ] Colour scheme
#### Network Admin
- [ ] Network Managers (`/wp-admin/network/settings.php?page=pb_network_managers`)
- [ ] Dashboard Settings (`/wp-admin/network/settings.php?page=pb_dashboard`)
- [ ] Google Analytics (`/wp-admin/network/settings.php?page=pb_analytics`)
- [ ] Sharing and Privacy Settings (`/wp-admin/network/settings.php?page=pressbooks_sharingandprivacy_options`)
#### Root Site Admin
- [ ] Customizer (`/wp-admin/customize.php`
#### Book Admin
- [ ] My Catalog (`<book>/wp-admin/index.php?page=pb_catalog`)
- [ ] My Catalog Profile (`<book>/wp-admin/index.php?page=pb_catalog&action=edit_profile`)
- [ ] Edit Tags (`<book>/wp-admin/index.php?page=pb_catalog&action=edit_tags&ID=<book_id>`)
- [ ] Organize (`<book>/wp-admin/admin.php?page=pb_organize`)
- [ ] Book Info (`<book>/wp-admin/post-new.php?post_type=metadata`)
- [ ] Theme Options (`<book>/wp-admin/themes.php?page=pressbooks_theme_options`)
- [ ] Export (`<book>/wp-admin/admin.php?page=pb_export`)
- [ ] Publish (`<book>/wp-admin/admin.php?page=pb_publish`)
- [ ] Your Profile (`<book>/wp-admin/profile.php`)
- [ ] Import (`<book>/wp-admin/tools.php?page=pb_import`)
- [ ] Search and Replace (`<book>/wp-admin/tools.php?page=pressbooks-search-and-replace`)
- [ ] Sharing and Privacy Settings (`<book>/wp-admin/options-general.php?page=pressbooks_sharingandprivacy_options`)
- [ ] Export Settings (`<book>/wp-admin/options-general.php?page=pressbooks_export_options`)
- [ ] Disable Comments Settings (`<book>/wp-admin/options-general.php?page=disable_comments_settings`)
- [ ] Pressbooks LaTex (`<book>/wp-admin/options-general.php?page=pb-latex`)
### Steps to Reproduce

Not applicable.
### Themes

Not applicable.
### Versions

Pressbooks: 5.2.0
WordPress: 4.9.4
PHP: 7.1

**Comment by colomet** [comment]
what should i do here. To take a look if all of the features works as it should work?

**Comment by christopherphillips** [comment]
Accessibility can be a complex process and a full review might require professional resources. However, it can be easy for anyone to get started. 

To do a quick accessibility check, anyone can download the free [WAVE Accessibility checker](http://wave.webaim.org/extension/) that can help identify some errors. [Easy Checks - A First Review of Web Accessibility](https://www.w3.org/WAI/eval/preliminary.html) from the W3C Web Accessibility Initiative may also be helpful.

**Comment by greatislander** [comment]
@jhung Let me know if you need any further info, and thanks again!

**Comment by SteelWagstaff** [comment]
We have contracted with a professional third-party accessibility service in Canada to provide a full accessibility audit of our administration interface, testing against WCAG 2.0 AA criteria. We expect to have an initial VPAT based on that audit published by the end of March (to accompany the release of [Pressbooks 5.7](https://github.com/pressbooks/pressbooks/projects/38)).

**Comment by SteelWagstaff** [comment]
The a11y audit has been completed. We are currently reviewing the results of the audit, opening relevant a11y issues in https://github.com/pressbooks/pressbooks/issues?q=is%3Aissue+is%3Aopen+label%3Aa11y and preparing to publish the VPAT with additional context shortly.
