### ISSUE TITLE
Conduct accessibility & inclusivity audit of web book interface

### ISSUE THREAD

**Issue by greatislander** [pressbooks/pressbooks#488]
### Prerequisites
- [x] Can you reproduce the behavior you wish to address with [all other plugins deactivated](http://codex.wordpress.org/Multisite_Network_Administration#Plugins)?
- [x] Are you running the [latest version of Pressbooks](http://wordpress.org/plugins/pressbooks/) and the [latest version of WordPress](http://codex.wordpress.org/Upgrading_WordPress)?
- [x] Are you experiencing this issue with one of our built-in root or book themes?
- [x] Did you [perform a cursory search](https://github.com/issues?q=+is%3Aissue+repo%3Apressbooks%2Fpressbooks) to see if your bug or enhancement is already listed?
### Description

Conduct an audit of the Pressbooks web book interface for accessibility and inclusivity, including:
- [ ] Cover page UI/UX
- [ ] Content UI/UX
- [ ] Schema.org metadata
- [ ] ARIA metadata
### Steps to Reproduce

Not applicable.
### Themes

Root Theme: Pressbooks Publisher
Book Theme: Luther
### Versions

Pressbooks: 3.8.1
WordPress: 4.6.1
PHP: 5.6

**Comment by colomet** [comment]
I can first to try to fix some bugs:
![captura de pantalla 2016-11-24 a las 13 55 52](https://cloud.githubusercontent.com/assets/3929177/20599317/c2ce33c6-b24d-11e6-94d6-53fd6e8814aa.png)
![captura de pantalla 2016-11-24 a las 13 55 46](https://cloud.githubusercontent.com/assets/3929177/20599318/c4706a0a-b24d-11e6-97b7-cdc647a60144.png)

**Comment by colomet** [comment]
About schema. We have metadata for educational books in our plugin for add new metadata for pressbooks.

. maybe you whant to create a section for such purposes where educators can write medatada about the purpose of the educational book.

![captura de pantalla 2016-11-24 a las 13 58 50](https://cloud.githubusercontent.com/assets/3929177/20599388/359fabbe-b24e-11e6-8234-d9dde4b82921.png)

**Comment by greatislander** [comment]
https://github.com/GoogleChrome/accessibility-developer-tools/wiki/Audit-Rules

**Comment by greatislander** [comment]
Closing in favour of https://github.com/pressbooks/pressbooks-book/issues/14
