### ISSUE TITLE
Search/Replace replacing additional characters (backslash "\" ) in editor

### ISSUE THREAD

**Issue by rootl** [pressbooks/pressbooks#501]
### Prerequisites

* [ YES] Can you reproduce the behavior you wish to address with [all other plugins deactivated](http://codex.wordpress.org/Multisite_Network_Administration#Plugins)?
* [YES] Are you running the [latest version of Pressbooks](http://github.com/pressbooks/pressbooks/releases/latest/) and the [latest version of WordPress](http://codex.wordpress.org/Upgrading_WordPress)?
* [YES] Are you experiencing this issue with one of our built-in root or book themes?
* [YES ] Did you [perform a cursory search](https://github.com/issues?q=+is%3Aissue+repo%3Apressbooks%2Fpressbooks) to see if your bug or enhancement is already listed?

### Description

Search/Replace problems within post editor.   Note: Book is dependent on WP QuickLaTeX plugin. Replacement problem occurs whether plugin is deactivated or not.

"
I did a search for a CSS class in the post editor, which it found and previewed nicely, and replaced correctly. Unfortunately it also randomly replaced a lot of "\"s rendering my LaTeX useless on those pages. I'm including the screen shots of the replacement preview and then the version compare showing that only the classes were previewed, but other code was replaced as well. I duplicated this in multiple chapters."

### Steps to Reproduce

1. Search for css class in post editor  (see screen capture)
2. Replace (see screen capture)
3. 

**Expected behavior:**  Previews all changes, only the changes we wanted replaced get replaced

**Actual behavior:** Random \ characters replaced in results, but did not show in preview.  The \ was not intended to be replaced anywhere

### Themes

Root Theme: [Pressbooks Publisher]
Book Theme: [Custom CSS based on Luther ]

![find-replace-error1](https://cloud.githubusercontent.com/assets/3603179/19160425/d3f37dfc-8bbd-11e6-8f1d-689fbcd6a2ea.png)
![find-replace-error2](https://cloud.githubusercontent.com/assets/3603179/19160426/d3f3a96c-8bbd-11e6-83b0-b427b94db691.png)

### Versions
Pressbooks: [3.8.0]
WordPress: 4.6.1
PHP: [7.0 ]

You can get the version of Pressbooks from the readme.txt file in the Pressbooks plugin (usually located at `http://<yourdomain.tld>/wp-content/plugins/pressbooks/readme.txt`) and the version of WordPress from the readme.html file in the WordPress root directory (usually located at `http://<yourdomain.tld>/readme.html`). You can usually get your PHP version from your web host, or by using the [`phpversion()`](http://php.net/manual/en/function.phpversion.php) function.

**Comment by greatislander** [comment]
@rootl Just fixed this—will be releasing a new version of the Pressbooks plugin that incorporates the fix within the week. Thanks for reporting!

**Comment by rootl** [comment]
Fantastic!  Thank you @greatislander !
