### ISSUE TITLE
Improve GitHub Updater experience

### ISSUE THREAD

**Issue by greatislander** [pressbooks/pressbooks#502]
### Prerequisites

* [x] Can you reproduce the behavior you wish to address with [all other plugins deactivated](http://codex.wordpress.org/Multisite_Network_Administration#Plugins)?
* [x] Are you running the [latest version of Pressbooks](http://github.com/pressbooks/pressbooks/releases/latest/) and the [latest version of WordPress](http://codex.wordpress.org/Upgrading_WordPress)?
* [x] Are you experiencing this issue with one of our built-in root or book themes?
* [x] Did you [perform a cursory search](https://github.com/issues?q=+is%3Aissue+repo%3Apressbooks%2Fpressbooks) to see if your bug or enhancement is already listed?

### Description

Currently, the experience of using https://github.com/afragen/github-updater/ to update Pressbooks is suboptimal. This is largely because of #411.

### Steps to Reproduce

Not applicable.

### Themes

Not applicable.

### Versions

Pressbooks: 3.8.1
WordPress: 4.6.1
PHP: 5.6

**Comment by greatislander** [comment]
Blocked by #411.

**Comment by greatislander** [comment]
Should be better now— we shall see.

**Comment by WhatLibrarian** [comment]
Hi - so I'm realizing I need to upgrade my pressbook install and I'm wondering about the best way to go about doing it.  I'm trying to use the https://github.com/afragen/github-updater/  and I'm still getting the same Pressbook version (2.1).

I've refreshed the Cache to update - which is what I believe this sentence means:  "Use the Refresh Cache button in the GitHub Updater Settings Page screen and all the transients will be deleted and the API will be queried again. "

I've also tried adding the style.css header  "GitHub Theme URI: pressbooks/pressbooks" (and reloaded, logged in and logged out).

I am maybe not quite grokking this process?

Should I download the latest pressbook .zip and upload the folder manual?  Trying not to nuke my current install.

I also tried simply reinstalling the theme and got this message:
"The package could not be installed. The theme is missing the style.css stylesheet. Theme install failed."

Any help would be nice and I would be happy to write up any 'instructions for dummies' or a "Hey - Pressbooks isn't in the WP repository anymore, what do I do now?" type of thing.

![image](https://cloud.githubusercontent.com/assets/2349781/22444363/73536120-e6f7-11e6-908c-f5be5e290b12.png)

**Comment by greatislander** [comment]
@WhatLibrarian Thanks for the question! The issue is that we added support for GitHub updater a couple releases before we removed Pressbooks from the plugin directory, so the version you are running (which is quite old) doesn't show up as a plugin that GH updater can manage.

It should work if you change the end of the header block of `pressbooks.php` (in the root of the plugin) from this:

```
Text Domain: pressbooks
License: GPLv2
*/
```

To this:

```
Text Domain: pressbooks
License: GPLv2
GitHub Plugin URI: https://github.com/pressbooks/pressbooks
Release Asset: true
*/
```

(You're trying to get GitHub Updater to pickup the plugin update, so you need to use the plugin header rather than the theme header.)

Let me know if that works!

**Comment by WhatLibrarian** [comment]
Thank you so much - that did the trick!  Very grateful for your help. 🥇

**Comment by greatislander** [comment]
@WhatLibrarian Glad to hear it.
