### ISSUE TITLE
Simplify ‘disable comments’ feature

### ISSUE THREAD

**Issue by greatislander** [pressbooks/pressbooks#509]
### Prerequisites

* [x] Can you reproduce the behavior you wish to address with [all other plugins deactivated](http://codex.wordpress.org/Multisite_Network_Administration#Plugins)?
* [x] Are you running the [latest version of Pressbooks](http://github.com/pressbooks/pressbooks/releases/latest/) and the [latest version of WordPress](http://codex.wordpress.org/Upgrading_WordPress)?
* [x] Are you experiencing this issue with one of our built-in root or book themes?
* [x] Did you [perform a cursory search](https://github.com/issues?q=+is%3Aissue+repo%3Apressbooks%2Fpressbooks) to see if your bug or enhancement is already listed?

### Description

Right now we let users disable comments via a fork of https://github.com/solarissmoke/disable-comments which adds our custom post types to the options page, disables comments on all of them by default, and removes other features.

<img width="752" alt="screen shot 2016-10-23 at 11 15 19 am" src="https://cloud.githubusercontent.com/assets/605361/19626912/11e4b61a-9912-11e6-9c10-3333fcbe81ba.png">

A simpler method might be:

1. Give the user a binary setting under Sharing and Privacy: Disable Comments? [ Yes / No ];
2. Default to yes;
3. If yes, load https://github.com/solarissmoke/disable-comments-mu for their book, which disables comments on all post types with zero config.

**Pros:** We don't need to maintain a fork and we can load the dependency via Packagist. Simpler to configure for the end user.
**Cons:** User can no longer disable comments on a post type-specific basis (but what is the use case for this—maybe not necessary?).

### Steps to Reproduce

Not applicable.

### Themes

Not applicable.

### Versions

Pressbooks: 3.9.2
WordPress: 4.6.1
PHP: 5.6

**Comment by hughmcguire** [comment]
would user still be able to turn comments on/off on a per-post (not post-type) basis?

ie: 
turn comments ON on chapter 4
and
turn comments OFF on chapter 7 

?

**Comment by greatislander** [comment]
@hughmcguire There's no change in that functionality—you can't override individual chapters, front/back matter etc. with the current implementation and you wouldn't be able to with the new implementation. If you need a different setting for different chapters you can't use this feature (and it doesn't really make sense to—it's there to allow a user to easily turn off ALL comments).

**Comment by hughmcguire** [comment]
if comments are set to ON can i turn them off on an individual chapter?

**Comment by greatislander** [comment]
Yes—this feature only changes comments from ON to OFF, not the other way around.

**Comment by greatislander** [comment]
(That is the case with both the current implementation and the proposed new implementation.)
