### ISSUE TITLE
Warning messages about undefined variable: _SESSION and Browser has a deprecated constructor

### ISSUE THREAD

**Issue by thomasdumm** [pressbooks/pressbooks#530]
### Prerequisites

* [x] Can you reproduce the behavior you wish to address with [all other plugins deactivated](http://codex.wordpress.org/Multisite_Network_Administration#Plugins)?
* [x] Are you running the [latest version of Pressbooks](http://github.com/pressbooks/pressbooks/releases/latest/) and the [latest version of WordPress](http://codex.wordpress.org/Upgrading_WordPress)?
* [x] Are you experiencing this issue with one of our built-in root or book themes?
* [x] Did you [perform a cursory search](https://github.com/issues?q=+is%3Aissue+repo%3Apressbooks%2Fpressbooks) to see if your bug or enhancement is already listed?

### Description

After updating to version 3.9.4 I see the following messages on all pages.

Deprecated: Methods with the same name as their class will not be constructors in a future version of PHP; Browser has a deprecated constructor in /Applications/MAMP/htdocs/wordpress/wp-content/plugins/pressbooks/symbionts/browser.php on line 147

Notice: Undefined variable: _SESSION in /Applications/MAMP/htdocs/wordpress/wp-content/plugins/pressbooks/includes/admin/pb-laf.php on line 917

Notice: Undefined variable: _SESSION in /Applications/MAMP/htdocs/wordpress/wp-content/plugins/pressbooks/includes/admin/pb-laf.php on line 918

### Steps to Reproduce

Go to any page.

**Comment by greatislander** [comment]
@thomasdumm Can you please visit the Diagnostics link at the bottom of any page in the Pressbooks administration interface and copy and paste what you see into this ticket?

**Comment by thomasdumm** [comment]
### System Information

#### Book Info

Book ID: 16
Book URL: http://localhost/wordpress/test/
Book Privacy: Public

#### Browser

Platform: Apple
Browser Name: Firefox
Browser Version: 49.0
User Agent String: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:49.0) Gecko/20100101 Firefox/49.0

#### WordPress Configuration

Network URL: http://localhost/wordpress/
Network Type: Subdirectory
Version: 4.6.1
Language: en_US
WP_ENV: Not set
WP_DEBUG: Enabled
Memory Limit: 64M

#### Pressbooks Configuration

Version: 3.9.4
Book Theme: Delivros
Book Theme Version: 1.0
Root Theme: Pressbooks Publisher
Root Theme Version: 2.1

#### Pressbooks Dependencies

Epubcheck: Installed
Kindlegen: Installed
xmllint: Installed
PrinceXML: Installed
Saxon-HE: Not Installed

#### Must-Use Plugins


#### Network Active Plugins

Pressbooks: 3.9.4

#### Book Active Plugins


#### Inactive Plugins

H5P: 1.7.5
Pressbooks Table Classes: 1.0.0

#### Server Configuration

PHP Version: 7.0.10
MySQL Version: 5.6.28
Webserver Info: Apache/2.2.31 (Unix) mod_wsgi/3.5 Python/2.7.12 PHP/7.0.10 mod_ssl/2.2.31 OpenSSL/1.0.2h DAV/2 mod_fastcgi/2.4.6 mod_perl/2.0.9 Perl/v5.24.0

#### PHP Configuration

Safe Mode: Disabled
Memory Limit: 256M
Upload Max Size: 32M
Post Max Size: 32M
Upload Max Filesize: 32M
Time Limit: 30
Max Input Vars: 1000
URL-aware fopen: On (1)
Display Errors: On (1)

#### PHP Extensions

cURL: Supported
cURL Version: 7.50.0
imagick: Not Installed
sass: Not Installed
xsl: Installed

**Comment by greatislander** [comment]
Thanks. The deprecation error only appears in PHP >= 7, and we run 5.6 as our base version still which is why we hadn't flagged it. I've updated the library which was causing the error and it is fixed. The other error would have been there before—I'm wondering if you turned on WP_DEBUG recently? In any case it is fixed too.
