### ISSUE TITLE
Error on Pressbooks plugin network activation: Pressbooks dependencies are missing. Please make sure that your project’s Composer autoload file is being required

### ISSUE THREAD

**Issue by deniscarr** [pressbooks/pressbooks#539]
### Prerequisites

* [YES ] Can you reproduce the behavior you wish to address with [all other plugins deactivated](http://codex.wordpress.org/Multisite_Network_Administration#Plugins)?
* [YES ] Are you running the [latest version of Pressbooks](http://github.com/pressbooks/pressbooks/releases/latest/) and the [latest version of WordPress](http://codex.wordpress.org/Upgrading_WordPress)?
* [NO ] Are you experiencing this issue with one of our built-in root or book themes?
* [ YES] Did you [perform a cursory search](https://github.com/issues?q=+is%3Aissue+repo%3Apressbooks%2Fpressbooks) to see if your bug or enhancement is already listed?

### Description

When I attempted to activate the Pressbooks plugin in my Worpress multi site admin - I got this error:
"Pressbooks dependencies are missing. Please make sure that your project’s Composer autoload file is being required, or use the latest release instead."

### Steps to Reproduce

1. I uploaded the Pressbooks plugin zip
2. I navigated to: Plugins → Installed Plugins
3. I clicked 'Network Activate' link under Pressbooks plugin line

**Expected behavior:** [What you expected to happen]
The Pressbooks plugin would activate successfully.

**Actual behavior:** [What actually happened]
 I got this error:
"Pressbooks dependencies are missing. Please make sure that your project’s Composer autoload file is being required, or use the latest release instead."

### Themes N/A

Root Theme: [Enter the root theme you are using here, e.g. "Pressbooks Publisher"]
Book Theme: [Enter the book theme you are using here, e.g. "Luther"]

### Versions

Pressbooks: [pressbooks-3.9.4.2]
WordPress: [ 4.6.1]
PHP: [5.6.28 ]

**Comment by greatislander** [comment]
Hi @deniscarr,

You need to download the number release zip, not the source code. See:

<img width="773" alt="screen_shot_2016-11-16_at_2_58_24_pm" src="https://cloud.githubusercontent.com/assets/605361/20361258/4a132f68-ac0d-11e6-8836-4f86e32ae115.png">

The source code does not include third-party dependencies. The release zip does.
