### ISSUE TITLE
PDF Issues

### ISSUE THREAD

**Issue by acoolidge** [pressbooks/pressbooks#545]
Comment from one of our Users:
Using PressBooks for anything other than an online version is a "pain." I am definitely going to look to produce the texbook later with a book designer. Images never seem to stay put where we place them in the text and they can't be customized. For a k-12 textbook - this is not ideal. So, we're will definitely get everything done for the web version. I would not like to publish the pdf version for the next book.

The PDF output does not accurately display images on the pages as they appear in the web/online version. Images are either moved to the next page or out of alignment with the text.

**Comment by hughmcguire** [comment]
Hi Amanda, 

Depending on the theme used, some images are styled to float to the top of the page to avoid blank space at the bottom of the page. It is accurate to say that a book in need of tightly-controlled design (eg a highly graphic K-12 book) will not be best-suited content for PB PDF production.

**Comment by greatislander** [comment]
@acoolidge Zoe (@zwhpressbooks) will be in touch with some specific tips that may help. I'm going to close this issue as this is more of a support question than a bug or feature ticket that we can address.
