### ISSUE TITLE
Compatibility with CM Tooltip Glossary Plugin

### ISSUE THREAD

**Issue by SteelWagstaff** [pressbooks/pressbooks#546]
### Description

I've installed the CM Tooltip Glossary Plugin on a server running the latest version of Pressbooks. I have tested the plugin with a non-Pressbooks instance of WP Multisite and am experiencing some errors with PB that don't occur with WP-Multisite. We have a couple of strange behaviors that I think are a result of some conflicts from how PB handles user permissions, custom post types, and permalinks, and I was hoping you could help me figure out whether these are resolvable.

### Steps to Reproduce

1. Installed [CM Tooltip Glossary Plugin](https://wordpress.org/plugins/enhanced-tooltipglossary/), but did not network activate it. Activated it within the book we wanted to test within while logged in with network super-admin permissions.
2. A user with super-admin permissions created 3 new glossary items. They published just fine and appeared on the [glossary index](https://wisc-dev.pb.unizin.org/anatomy622upperlimbcoursebook/glossary-2/ ) page.
3. A user that was a site/book admin logged in and was able to successfully edit posts created by the super-admin.
4. When that user tried to create a new glossary item, however, they received an unsupported post type error:
![screen shot 2016-11-23 at 2 40 39 pm](https://cloud.githubusercontent.com/assets/13485451/20578035/da7effc8-b18a-11e6-872a-f54a722d5609.png)
5. We tried to load the sub-pages for any of the 3 published glossary terms (, but were redirected to the network homepage and told 'The manager of this Pressbooks network has not made any books public viewable.' Try https://wisc-dev.pb.unizin.org/anatomy622upperlimbcoursebook/glossary/cockatrice/, for example.

6a. The plugin's authors responded to a similar issue to the one described in step 4 on the plugin support page by suggesting the user resave the site's permalinks settings: https://wordpress.org/support/topic/redirected-to-index-page-and-not-definition/. However, this setting is suppressed in the PB dashboard, and attempting to load the URL 'wp-admin/options-permalink.php' results in a 'You do not have sufficient permissions to access that URL.' error message.
6b. A user logged in with the super-admin role visited the permalinks settings page (via URL since it was suppressed in the settings menu). After setting it to 'post name' and saving, the individual glossary pages now display, but this doesn't seem like a viable option for users who hope to install the plugin on their books, and seems like an unnecessary burden for network super-admins.

**Expected behavior:** [What you expected to happen]
4. I expected that book admins would be able to create new 'glossary' posts, just like network admins could.
5-6. I expected that published glossary pages would be viewable without having to update/save permalinks settings.

**Actual behavior:** [What actually happened]
4. The user was given a unsupported post type error and not permitted to create a new glossary entry.
5-6. Individual glossary item pages could not be viewed until permalinks were saved (by a network super admin) with the 'post name' option.

**Comment by SteelWagstaff** [comment]
If this isn't the right place to put details re: some of our plugin compatibility testing, I'll happily move this, but I'm not sure if we decided for a good place to put this kind of stuff. We're going to be testing 6-10 plugins over the next few weeks, and I imagine we'll have a few more similar reports ...

**Comment by greatislander** [comment]
Moving here: https://discourse.pressbooks.org/t/cm-tooltips-plugin-troubleshooting/34
