### ISSUE TITLE
On pressbooks.pub Clarke theme leads to warning messages during export.

### ISSUE THREAD

**Issue by thomasdumm** [pressbooks/pressbooks#550]
### Prerequisites

* [x] Can you reproduce the behavior you wish to address with [all other plugins deactivated](http://codex.wordpress.org/Multisite_Network_Administration#Plugins)?
* [x] Are you running the [latest version of Pressbooks](http://github.com/pressbooks/pressbooks/releases/latest/) and the [latest version of WordPress](http://codex.wordpress.org/Upgrading_WordPress)?
* [x] Are you experiencing this issue with one of our built-in root or book themes?
* [x] Did you [perform a cursory search](https://github.com/issues?q=+is%3Aissue+repo%3Apressbooks%2Fpressbooks) to see if your bug or enhancement is already listed?

### Description

On pressbooks.pub Clarke theme leads to warning messages during export.

Array
(
    [time] => Sun Nov 27 09:36:54 2016
    [user] => tdumm
    [site_url] => https://delivros.pressbooks.pub/test
    [blog_id] => 33
    [theme] => Clarke
)
INFO(CSS-007): /home/delivros/wordpress/wp-content/uploads/sites/33/exports/test-1480239409._3.epub/OEBPS/clarke.css(4,3): Font-face reference OEBPS/assets/GFSNeohellenic.ttf refers to non-standard font type application/x-font-ttf.
INFO(CSS-007): /home/delivros/wordpress/wp-content/uploads/sites/33/exports/test-1480239409._3.epub/OEBPS/clarke.css(10,3): Font-face reference OEBPS/assets/GFSNeohellenicItalic.ttf refers to non-standard font type application/x-font-ttf.
INFO(CSS-007): /home/delivros/wordpress/wp-content/uploads/sites/33/exports/test-1480239409._3.epub/OEBPS/clarke.css(16,3): Font-face reference OEBPS/assets/GFSNeohellenicBold.ttf refers to non-standard font type application/x-font-ttf.
INFO(CSS-007): /home/delivros/wordpress/wp-content/uploads/sites/33/exports/test-1480239409._3.epub/OEBPS/clarke.css(22,3): Font-face reference OEBPS/assets/GFSNeohellenicBoldItalic.ttf refers to non-standard font type application/x-font-ttf.
INFO(CSS-007): /home/delivros/wordpress/wp-content/uploads/sites/33/exports/test-1480239409._3.epub/OEBPS/clarke.css(28,3): Font-face reference OEBPS/assets/SBL-grk.ttf refers to non-standard font type application/x-font-ttf.

Diagnostics page:

#### Book Info

Book ID: 33
Book URL: https://delivros.pressbooks.pub/test/
Book Privacy: Public

#### Browser

Platform: Apple
Browser Name: Firefox
Browser Version: 50.0
User Agent String: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:50.0) Gecko/20100101 Firefox/50.0

#### WordPress Configuration

Network URL: http://delivros.pressbooks.pub/
Network Type: Subdirectory
Version: 4.6.1
Language: en_US
WP_ENV: production
WP_DEBUG: Disabled
Memory Limit: 64M

#### Pressbooks Configuration

Version: 3.9.5
Book Theme: Clarke
Book Theme Version: 2.0
Root Theme: Pressbooks Publisher
Root Theme Version: 3.0

#### Pressbooks Dependencies

Epubcheck: Installed
Kindlegen: Installed
xmllint: Installed
PrinceXML: Installed
Saxon-HE: Installed

#### Network Active Plugins

Pressbooks: 3.9.5
Pressbooks Cover Generator: 1.7.0
Pressbooks Stats: 1.0.0
User Activation Keys: 4.6

#### Inactive Plugins

Akismet: 3.1.11
Batcache Manager: 1.2
Memcached: 3.0.1
Pressbooks Table Classes: 1.0.0

#### Server Configuration

PHP Version: 5.6.27
MySQL Version: 5.5.50
Webserver Info: Apache/2.4.6 (CentOS) OpenSSL/1.0.1e-fips PHP/5.6.27

#### PHP Configuration

Safe Mode: Disabled
Memory Limit: 256M
Upload Max Size: 10M
Post Max Size: 10M
Upload Max Filesize: 10M
Time Limit: 30
Max Input Vars: 1000
URL-aware fopen: On (1)
Display Errors: N/A

#### PHP Extensions

cURL: Supported
cURL Version: 7.29.0
imagick: Installed
sass: Installed
xsl: Installed

**Comment by greatislander** [comment]
Known behaviour of EpubCheck which should not affect your outputs at all. See: https://github.com/IDPF/epubcheck/pull/633
