### ISSUE TITLE
Question on the correct use/conversion of chapter title and heading tags. 

### ISSUE THREAD

**Issue by thomasdumm** [pressbooks/pressbooks#552]
The current hierarchy of titles in Pressbooks is: chapter title (blog title), h1, h2, h3, h4, h5, h6. The chapter title leads to inconsistencies in toc, import and export:

- Chapter title and h2 are used for two-level table of contents. This would suggest that you should not use h1 inside Pressbooks to structure the content which is not very intuitive.
- As there is no chapter structure in word and xhtml, during epub and word export the Pressbooks chapter cannot be tagged in a straight forward way. This would suggest not to use the chapter title inside Pressbooks to structure the content of the book.
- During epub import the Pressbooks chapter title is currently filled with the <title> of the xhtml file. 

Would it not make more sense to assume that the chapter title and h1 contain the same text and consequently: 

- use h1 and h2 for the two level toc
- export the chapter title into the <title> tag in the epub export. 
- fill the chapter title with the <title> during epub import. 

Any thoughts or suggestions on Pressbooks title structures for textbooks?

**Comment by greatislander** [comment]
Closing this in favour of: https://github.com/pressbooks/pressbooks/issues/830
