### ISSUE TITLE
Import of valid EPUB document leads to empty chapters

### ISSUE THREAD

**Issue by thomasdumm** [pressbooks/pressbooks#554]
### Prerequisites

* [x] Can you reproduce the behavior you wish to address with [all other plugins deactivated](http://codex.wordpress.org/Multisite_Network_Administration#Plugins)?
* [x] Are you running the [latest version of Pressbooks](http://github.com/pressbooks/pressbooks/releases/latest/) and the [latest version of WordPress](http://codex.wordpress.org/Upgrading_WordPress)?
* [x] Are you experiencing this issue with one of our built-in root or book themes?
* [x] Did you [perform a cursory search](https://github.com/issues?q=+is%3Aissue+repo%3Apressbooks%2Fpressbooks) to see if your bug or enhancement is already listed?

### Description
Import of valid EPUB document test_import_not_ok.epub does not work. The two chapters that are created by the import are both empty. If I open test_import_not_ok.epub with Sigil and save the document as test_import_ok.epub it can be imported.

The difference of the two EPUB files is the folder structure. But test_import_ok.epub should be working too?

[EPUB.zip](https://github.com/pressbooks/pressbooks/files/616238/EPUB.zip)

**Comment by connerbw** [comment]
HTML in "test_import_not_ok.epub" looks like:

```
<html
lang="en-US"
xmlns="http://www.w3.org/1999/xhtml"
><head
><title
>Main</title
></head
><body
// ... snip ...
></body
></html
>
```

Technically, this is valid. But wow, really? :)

Will change preg to [detect optional spaces](https://stackoverflow.com/questions/14293024/optional-whitespace-regex) in closing tag.

**Comment by greatislander** [comment]
@thomasdumm This is fixed in the dev branch, please test.
