### ISSUE TITLE
suggestions:

### ISSUE THREAD

**Issue by colomet** [pressbooks/pressbooks#568]
### Prerequisites

* [x] Can you reproduce the behavior you wish to address with [all other plugins deactivated](http://codex.wordpress.org/Multisite_Network_Administration#Plugins)?
* [x] Are you running the [latest version of Pressbooks](http://github.com/pressbooks/pressbooks/releases/latest/) and the [latest version of WordPress](http://codex.wordpress.org/Upgrading_WordPress)?
* [x] Are you experiencing this issue with one of our built-in root or book themes?
* [x] Did you [perform a cursory search](https://github.com/issues?q=+is%3Aissue+repo%3Apressbooks%2Fpressbooks) to see if your bug or enhancement is already listed?

### Description

What about to add social buttons in the footer of the main page?
What about to add Terms of Service and Privacy Policy information, in the same way we add the license?
What about to add a contact butttom with a redirection to the email?

Or maybe to create space for 3 widgets in the bootom allowign the customization by users.

What about to add cookie notice? in europe is necesary.

I believe we need to add space for custom information, allowing more interaction with the readers. my question is: We do for each book, for all the books the same, or in the installation we choose if we do for each book or for all the books?

_I think by default have to be for all the books. The multisite administrator write all the content, if one information is empty, if exist such data in the books, the book will show the book information, instead of nothing. - or maybe the main administrator just in the catalog_

(something simmilar to pressbooks.com can it be nice
![captura de pantalla 2016-11-29 a las 9 31 33](https://cloud.githubusercontent.com/assets/3929177/20702108/b2c47f7c-b616-11e6-8fbc-f0be84f12501.png)
)

**Comment by colomet** [comment]
Do we need to add a simple post views counter?

**Comment by greatislander** [comment]
Please add these as individual threads in Discourse.
