### ISSUE TITLE
educational suggestions:

### ISSUE THREAD

**Issue by colomet** [pressbooks/pressbooks#569]
### Prerequisites

* [x] Can you reproduce the behavior you wish to address with [all other plugins deactivated](http://codex.wordpress.org/Multisite_Network_Administration#Plugins)?
* [x] Are you running the [latest version of Pressbooks](http://github.com/pressbooks/pressbooks/releases/latest/) and the [latest version of WordPress](http://codex.wordpress.org/Upgrading_WordPress)?
* [x] Are you experiencing this issue with one of our built-in root or book themes?
* [x] Did you [perform a cursory search](https://github.com/issues?q=+is%3Aissue+repo%3Apressbooks%2Fpressbooks) to see if your bug or enhancement is already listed?

### Description
If we need to use pressbooks for education (i use for texbooks) we need to develop some way to copy content from book to book. Allowing customersthe 5r framework (http://www.opencontent.org/definition/). The Open content is not really open content if we do not allow the users copy and paste a course and modify. But we need to do it in a way the author name and the original course remain in the informaton of the book. 

Also wee need to be able to decide as main administrator if we allow or not such copy of content in our installation. The autor too. We have to allow sharing content between authors just if we whant and the authors whant too.

Also a system of Categories or tags (global for the multisite) is necesary. We need to allow the readers to find information in all the installation. If we have 2 books for maths. Maths 1 and 2. If in books 2 we have more information about one topic, we have to be able to link between the content in the book 1 and 2 such content. Something like the current search of preessbooks but for the full installation. I´ trying to create something like twitter # for content in my own child theme. 

And specific metadata for education in a new place.

**Comment by thomasdumm** [comment]
Are you collecting input for "4. Sharing and Cloning of Pressbooks Content" from the roadmap with this issue?

If I am able to create a new book by pulling in individual chapters from existing books into my book, 
- I would like to be able to see if the pulled in chapter has been edited and 
- I would like to be able to decide if/when I what to update the puled in chapter to its latest version. 
- I would like to be able to compare versions of the pulled in chapter the way I can currently compare versions of a chapter.
- I would like to be able to decide that the pulled in version of the book looses the connection to the original version making it a normal chapter that I can edit.
- As the owner of a chapter, I would like to be able to contact the owner of the books that pulled in my chapter to get feedback on the chapter and plan updates to the chapter.

**Comment by colomet** [comment]
You whant something more advance than Github for code. 

I think is good idea, but looks like that is a final version, we need to create the roadmap with easy features (some of them will be not available in the future) till we develop something more complex. Maybe we could use trello for organice the roadmap, and later copy and paste here. 
What do you think?

**Comment by greatislander** [comment]
@colomet https://github.com/pressbooks/pressbooks/projects

**Comment by colomet** [comment]
how can i add content?

**Comment by greatislander** [comment]
@thomasdumm @colomet Please move these ideas to Discourse threads. https://discourse.pressbooks.org
