### ISSUE TITLE
Name of the author as a link

### ISSUE THREAD

**Issue by colomet** [pressbooks/pressbooks#570]
### Prerequisites

_Check the boxes below by changing them from `[ ]` to `[x]`._

* [x] Can you reproduce the behavior you wish to address with [all other plugins deactivated](http://codex.wordpress.org/Multisite_Network_Administration#Plugins)?
* [x] Are you running the [latest version of Pressbooks](http://github.com/pressbooks/pressbooks/releases/latest/) and the [latest version of WordPress](http://codex.wordpress.org/Upgrading_WordPress)?
* [x] Are you experiencing this issue with one of our built-in root or book themes?
* [x] Did you [perform a cursory search](https://github.com/issues?q=+is%3Aissue+repo%3Apressbooks%2Fpressbooks) to see if your bug or enhancement is already listed?

### Description

Maybe each time or some times, the author name, can it be a link to the author´s catalog.

I believe it can be the personal page for authors, now is quite hard to find. just users can send the link.

what do you think?

![captura de pantalla 2016-11-29 a las 17 30 28](https://cloud.githubusercontent.com/assets/3929177/20719402/114973c8-b65c-11e6-8ea3-a6f9fa6796ba.png)

**Comment by greatislander** [comment]
The problem is that this assumes that all users have set up and are actively using the catalog. Many don't.

**Comment by colomet** [comment]
The people do not use the catalog because now is pretty simple. If we spend a litle more time there, it could be useful. Besides, nobody use the catalog because is not available to the readers, is hidden. 

If PB is going to the the place where the autors write books, I´ sure to have all the books of the autor in the same place is good. It helps to the readers to find more books of the same author. For me, educational books, works as a keywork or twitter #.
