### ISSUE TITLE
To create a place for the ISSN for the books.

### ISSUE THREAD

**Issue by colomet** [pressbooks/pressbooks#573]
### Prerequisites

_Check the boxes below by changing them from `[ ]` to `[x]`._

* [x] Can you reproduce the behavior you wish to address with [all other plugins deactivated](http://codex.wordpress.org/Multisite_Network_Administration#Plugins)?
* [x] Are you running the [latest version of Pressbooks](http://github.com/pressbooks/pressbooks/releases/latest/) and the [latest version of WordPress](http://codex.wordpress.org/Upgrading_WordPress)?
* [x] Are you experiencing this issue with one of our built-in root or book themes?
* [x] Did you [perform a cursory search](https://github.com/issues?q=+is%3Aissue+repo%3Apressbooks%2Fpressbooks) to see if your bug or enhancement is already listed?

### Description
ISBN is for paper books. If the book is digital and it hava many changes over the time, the correct number is ISSN (Also is a free code)

We could add space for that in Book Info

### Some information about [ISSN](http://www.issn.org/understanding-the-issn/assignment-rules/issn-manual/) 

**0.2 Scope of ISSN**

Each ISSN is a unique identifier for a specific continuing resource in a defined medium. Continuing resources are bibliographic resources issued over time with no predetermined conclusion, they include serials and ongoing integrating resources.
All continuing resources, whether past, present, or to be produced in the foreseeable future, whatever the medium of production, are eligible for ISSN assignment.
Also eligible for ISSN assignment are those bibliographic resources issued in successive issues or parts which bear numbering and that also bear other characteristics of a serial (e.g. frequency in the title), but whose duration is limited (e.g. the newsletter of an event)[4].
Eligibility does not necessarily mean ISSN assignment in practice. Section 0.3 below provides criteria for determining whether or not a continuing resource shall be ISSN assigned in accordance with the current policy of the ISSN Network.

**0.3 Criteria for ISSN assignment**
**0.3.1 Serials**

Serials are continuing resources issued in a succession of discrete issues or parts, usually bearing numbering, that have no predetermined conclusion.
ISSN are assigned to the entire population of serials. However, National Centres can decide to exclude ephemeral serials or serials of purely local interest from systematic ISSN assignment (see Section 0.7).

**0.3.2 Ongoing integrating resources**

Ongoing integrating resources are resources that are updated over time and with no predetermined
conclusion, for which the updates are integrated into the resources and do not remain discrete.
ISSN are assigned to ongoing integrating resources which fulfill all the inclusion and exclusion criteria listed hereafter. National Centres can decide to exclude ephemeral ongoing integrating resources or ongoing integrating resources of purely local interest from systematic ISSN assignment (see Section 0.7).
Meeting only one of the criteria is not sufficient for ISSN assignment. These criteria apply to all the categories of ongoing integrating resources, whether print or electronic: databases, websites, wikis, print loose-leaf services, etc. Although blogs are considered to be serials, these same criteria should be applied to blogs.
Editorial note: If a part of an ongoing integrating resource (part of website, for instance) is eligible for ISSN assignment, e.g., a newsletter that is part of the website is assigned an ISSN, this does not mean necessarily that the whole website is eligible for ISSN assignment.

**0.3.2.1 Inclusion criteria**

1. There is editorial content (i.e., the resource mostly consists of written, textual content, and there is evidence of editorial or journalistic treatment);
2. There is identified editorial responsibility (i.e., a statement indicating the name of the
publisher / producer, and at least the country of publication). Generally, editorial responsibility will consist of more than one individual;
3. There is a consistent title (i.e., a title which remains consistent when the resource is updated) and the title is prominently visible on the resource;
4. There is a valid URL (i.e., a URL leading to the actual resource);
5. The resource has subject-related content or has identified subject-related audience.

**0.3.2.2 Exclusion criteria**

1. Personal resources (personal web sites and web pages, online diaries);
2. Resources focusing on a company, a product, an institution or organization (advertising and promotional web sites, commercial web sites, product information web sites, company and institutional web sites, web sites of organizations);
3. Web sites consisting only of links;
4. Ephemeral resources (i.e., resources known to be ephemeral).

**Comment by colomet** [comment]
In book info, we have a space for ISBN, why not also for ISSN?
![captura de pantalla 2016-11-30 a las 20 09 09](https://cloud.githubusercontent.com/assets/3929177/20767011/f207c2e8-b738-11e6-8461-b5b36139a6ad.png)

**Comment by greatislander** [comment]
@colomet Because nobody has ever requested it. But we will look into this, thanks.
