### ISSUE TITLE
Pressbooks Publisher Theme discussion

### ISSUE THREAD

**Issue by pbstudent** [pressbooks/pressbooks#574]
### Prerequisites
* [x] Did you [perform a cursory search](https://github.com/issues?q=+is%3Aissue+repo%3Apressbooks%2Fpressbooks) to see if your bug or enhancement is already listed?

### Description
Looking for a general forum on basic inquiries but this appears to be the only location; my inquiries are:

1. How can I preserve the Pressbooks Publisher Theme 2.1 when upgrading to the latest Pressbooks? (PB Publisher theme 2.1 is great with clean separation of content, preferably with smaller footprint per book as found in latest Pressbooks Publisher theme 3.0)

2. How can I remove the sign in button because this is confusing to students who believe they have to login to get an open source e-textbook.

### Steps to Reproduce
1. Focus of inquiries is on home page of Pressbooks Publisher Theme

### System Information
Pressbooks: 3.9.2.1
WordPress: 4.6.1
PHP:7.0.8-0ubuntu0.16.04.3

**Comment by greatislander** [comment]
@pbstudent You can use any theme as the root theme of your Pressbooks network. If you wish to use the old Pressbooks Publisher I will make it available as a standalone theme on GitHub.

**Comment by greatislander** [comment]
Download here, upload to `/wp-content/themes/`. https://github.com/pressbooks/pressbooks-publisher-two

**Comment by pbstudent** [comment]
That is great news.  Although the current PB Publisher 3.x theme is bright with very red text, the PB Publisher 2.x had classical sublime visual esthetics that is perfect for our open source e-textbook incubator.

**Comment by pbstudent** [comment]
Once the theme is uploaded to WP, disabling the current default Pressbooks Publisher theme can be challenging as disabling it on the network will not change anything.  I wonder if the best practice is to do the following:

1. Rename uploaded theme folder to pressbooks-publisher
2. Go to ../wp-admin/network/site-settings.php?id=1
3. Modify entries for:
Template Root : /plugins/pressbooks/themes-root  >to> /themes
Stylesheet Root : /plugins/pressbooks/themes-root  >to>  /themes

**Comment by greatislander** [comment]
@pbstudent It probably will break something eventually ;) Pressbooks 3.9.6 will allow themes (root and book) outside of the Pressbooks plugin to be enabled by default. Right now they must be explicitly whitelisted. If you want to try this right away you can add the following to your `wp-config.php` file:

```
$GLOBALS['PB_SECRET_SAUCE']['ROOT_THEMES'] = array(
  'pressbooks-publisher-two',
  'twenty sixteen',
  'another-theme-for-root'
);
```

From now on you can post these kinds of questions in the form at https://discourse.pressbooks.org.
