### ISSUE TITLE
Textbox messes with paragraphs

### ISSUE THREAD

**Issue by lukaiser** [pressbooks/pressbooks#58]
The flowing code (new lines after text are important)
````
[textbox]

bla

[/textbox]
````

creates the following unclean HTML Code:

`````
<div class="textbox"></p>
<p>bla</p>
<p></div>
``````

generating the following warning in the table of content:
`````
Warning: DOMDocument::loadHTML() [domdocument.loadhtml.php]: Unexpected end tag : p in Entity, line: 1 in .../wp-content/plugins/pressbooks/includes/class-pb-book.php on line 337
````

**Comment by chrillep** [comment]
seems some changes have been made to wordpress so 
commenting out || removing
```
remove_filter( 'the_content', 'wpautop' );
add_filter( 'the_content', 'wpautop' , 12); // execute wpautop after shortcode processing
```
seems to fix it for me...

**Comment by matthias-noetzli** [comment]
This change leads to paragraph tags being inserted into shortcode content, which is often not desirable and messes up the shortcode output. The original issue with the textbox now seems to work correctly without this change to the filter order. Is there any chance this could be reverted or are there any other factors at play?
