### ISSUE TITLE
Word import drops styles and language information

### ISSUE THREAD

**Issue by crism** [pressbooks/pressbooks#582]
### Prerequisites

* [x] Can you reproduce the behavior you wish to address with [all other plugins deactivated](http://codex.wordpress.org/Multisite_Network_Administration#Plugins)?
* [x] Are you running the [latest version of Pressbooks](http://github.com/pressbooks/pressbooks/releases/latest/) and the [latest version of WordPress](http://codex.wordpress.org/Upgrading_WordPress)?
* [x] Are you experiencing this issue with one of our built-in root or book themes?
* [x] Did you [perform a cursory search](https://github.com/issues?q=+is%3Aissue+repo%3Apressbooks%2Fpressbooks) to see if your bug or enhancement is already listed?

### Description

When Word documents are prepared using best practices—styles for formatting, and no direct bold or italic markup, the Word import process into Pressbooks ignores this information. It also ignores language tagging.

### Steps to Reproduce

1. Import [this Word DOCX file](https://github.com/pressbooks/pressbooks/files/632124/styles_language_clean.docx).

**Expected behavior:** The word “styles” should be italicized. The phrase “en français” should be italicized and marked as French.

**Actual behavior:** The document results in two paragraphs with no inline formatting or tagging whatsoever.

### System Information

Pressbooks: 3.9.5.1
WordPress: 4.6.1
PHP: 5.6.28

**Comment by thomasdumm** [comment]
what is the document language of your word document?

**Comment by thomasdumm** [comment]
maybe related to https://github.com/pressbooks/pressbooks/issues/298

**Comment by crism** [comment]
@thomasdumm, the document is in US English. It’s not #298; that’s a result of the heading styles having different names in different languages. This is a problem with inline styles; the Emphasis style is defined as italic, but the import just ignores it as there’s no direct formatting.

I’m working on a fix in the XSLT…

**Comment by greatislander** [comment]
Thanks, @crism!

**Comment by crism** [comment]
I think this will fix it, but I need to upgrade WordPress before I can test it server-side. [Here’s an updated Word doc](https://github.com/pressbooks/pressbooks/files/643247/styles_language_clean.docx) I used for testing (exercising a few additional features).

**Comment by crism** [comment]
Thanks, @greatislander, @emasters!
