### ISSUE TITLE
When importing Pressbooks XML (WXR), should recognize Front matter & Back matter Types

### ISSUE THREAD

**Issue by hughmcguire** [pressbooks/pressbooks#601]
### Prerequisites

_Check the boxes below by changing them from `[ ]` to `[x]`._

* [x] Can you reproduce the behavior you wish to address with [all other plugins deactivated](http://codex.wordpress.org/Multisite_Network_Administration#Plugins)?
* [x] Are you running the [latest version of Pressbooks](http://github.com/pressbooks/pressbooks/releases/latest/) and the [latest version of WordPress](http://codex.wordpress.org/Upgrading_WordPress)?
* [x] Are you experiencing this issue with one of our built-in root or book themes?
* [x] Did you [perform a cursory search](https://github.com/issues?q=+is%3Aissue+repo%3Apressbooks%2Fpressbooks) to see if your bug or enhancement is already listed?

### Description

When importing a Pressbooks XML/WXR file ... I expect that Front Matter & Back Matter Types will be preserved. But they are not.  Instead, no Type appears to be assigned.

[Description of the bug or feature]

### Steps to Reproduce

1. I set up a new book in pressbooks.
2. I import a Pressbooks WXR file (say the standard test book)
3.  Everything comes in peaches
4. ... *except:* Front Matter & Back Matter items Types have been stripped.

**Expected behavior:** [What you expected to happen]

FM & BM Types (for instance, Dedication) should be preserved. 

**Actual behavior:** [What actually happened]

FM & BM Types (for instance, Dedication) were stripped.

#### Book Info

Book ID: 2
Book URL: http://pressbooks.dev/standardtestbook/
Book Privacy: Public

#### Browser

Platform: Apple
Browser Name: Chrome
Browser Version: 55.0.2883.95
User Agent String: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.95 Safari/537.36

#### WordPress Configuration

Network URL: http://pressbooks.dev/
Network Type: Subdirectory
Version: 4.7
Language: en_US
WP_ENV: development
WP_DEBUG: Enabled
Memory Limit: 64M

#### Pressbooks Configuration

Version: 3.9.6
Book Theme: Clarke
Book Theme Version: 2.0
Root Theme: Pressbooks Publisher
Root Theme Version: 3.0.1

#### Pressbooks Dependencies

Epubcheck: Installed
Kindlegen: Installed
xmllint: Installed
PrinceXML: Installed
Saxon-HE: Not Installed

#### Network Active Plugins

Pressbooks: 3.9.6

#### Server Configuration

PHP Version: 7.1.0-3+deb.sury.org~xenial+1
MySQL Version: 5.5.5
Webserver Info: nginx/1.11.5

#### PHP Configuration

Safe Mode: Disabled
Memory Limit: 256M
Upload Max Size: 25M
Post Max Size: 25M
Upload Max Filesize: 25M
Time Limit: 120
Max Input Vars: 1000
URL-aware fopen: On (1)
Display Errors: On (1)

#### PHP Extensions

cURL: Supported
cURL Version: 7.47.0
imagick: Not Installed
sass: Not Installed
xsl: Installed

**Comment by greatislander** [comment]
We thought this was fixed in #426 but it wasn't, oops.
