### ISSUE TITLE
Word import doubles endnotes

### ISSUE THREAD

**Issue by crism** [pressbooks/pressbooks#603]
### Prerequisites

* [x] Can you reproduce the behavior you wish to address with [all other plugins deactivated](http://codex.wordpress.org/Multisite_Network_Administration#Plugins)?
* [x] Are you running the [latest version of Pressbooks](http://github.com/pressbooks/pressbooks/releases/latest/) and the [latest version of WordPress](http://codex.wordpress.org/Upgrading_WordPress)?
* [x] Are you experiencing this issue with one of our built-in root or book themes?
* [x] Did you [perform a cursory search](https://github.com/issues?q=+is%3Aissue+repo%3Apressbooks%2Fpressbooks) to see if your bug or enhancement is already listed?

### Description

When importing a Word document with endnotes, each endnote is repeated. Each is formatted correctly, with back-links to the reference, but each is present twice.

### Steps to Reproduce

1. Make a Word document with endnotes.
1. Import it into Pressbooks.

**Expected behavior:**

Each endnote should appear at the end of the chapter or part. Each should appear only once.

**Actual behavior:**

The endnotes are present correctly, but each repeats.

### System Information

Pressbooks: 3.9.6
WordPress: 4.7
PHP: 5.6.28

**Comment by crism** [comment]
This happens in PHP, and it’s code I changed a few months back, and worked correctly then. I’ll dive into it right after addressing #602.

**Comment by greatislander** [comment]
Thanks @crism!

**Comment by crism** [comment]
Hmm… looks like my pull request #608 is actually relevant here—I’ll merge it into the branch for this. The problem is that the PHP presumes that _all_ `<sup>` elements represent a footnote/endnote reference. But there’s still a better way, which is to look for the `<a>` elements that have footnote-shaped references (_i.e._, `sdfootnote*sym`).

**Comment by crism** [comment]
Bah… that commit misses the end notes altogether. Will work on it more tomorrow.
