### ISSUE TITLE
Word import produces excessive inline styles

### ISSUE THREAD

**Issue by greatislander** [pressbooks/pressbooks#616]
### Prerequisites

* [x] Can you reproduce the behavior you wish to address with [all other plugins deactivated](http://codex.wordpress.org/Multisite_Network_Administration#Plugins)?
* [x] Are you running the [latest version of Pressbooks](http://github.com/pressbooks/pressbooks/releases/latest/) and the [latest version of WordPress](http://codex.wordpress.org/Upgrading_WordPress)?
* [x] Are you experiencing this issue with one of our built-in root or book themes?
* [x] Did you [perform a cursory search](https://github.com/issues?q=+is%3Aissue+repo%3Apressbooks%2Fpressbooks) to see if your bug or enhancement is already listed?

### Description

In the wake of a few recent PRs (#588, #607, #608, #609) we seem to be getting excessive inline styling from Word imports. See [here](https://gist.github.com/greatislander/69e126e7fa22b58bdeda60d13d70f797/revisions) (before and after the PRs).

@crism, hoping you can help with this.

### Steps to Reproduce

1. Import a Word document.

**Expected behavior:** Basic Word styles are imported.

**Actual behavior:** Inline styles appear throughout, sometimes on a per-word level.

### System Information

Pressbooks: 3.9.7-dev
WordPress: 4.7
PHP: 7.1

**Comment by greatislander** [comment]
@crism Here's the doc we used for testing: [lorem-ipsum-footnotes.docx](https://github.com/pressbooks/pressbooks/files/683148/lorem-ipsum-footnotes.docx)

**Comment by crism** [comment]
Yes, I erred on the side of preserving information. We can simplify it: Right now, a CSS style string is created; it is then inspected by a series of templates that generate HTML markup as appropriate, and remove the corresponding styles (_e.g._, `font-style:italic;` becomes `em`). Whatever CSS style is left is then dumped into a `style` attribute on a `span` element. It could be discarded instead.

**Comment by greatislander** [comment]
@crism That would be great. I reverted the PRs that we merged in—would you be able to put together one PR that consolidates your fixes for all the issues you targeted in those four PRs that discards styles other than bold, italic, superscript and subscript?

**Comment by crism** [comment]
Yes, I can do that, @greatislander.

**Comment by greatislander** [comment]
Thanks again for all your work on this, @crism!
