### ISSUE TITLE
Import drops language information

### ISSUE THREAD

**Issue by crism** [pressbooks/pressbooks#630]
### Prerequisites

* [x] Can you reproduce the behavior you wish to address with [all other plugins deactivated](http://codex.wordpress.org/Multisite_Network_Administration#Plugins)?
* [x] Are you running the [latest version of Pressbooks](http://github.com/pressbooks/pressbooks/releases/latest/) and the [latest version of WordPress](http://codex.wordpress.org/Upgrading_WordPress)?
* [x] Are you experiencing this issue with one of our built-in root or book themes?
* [x] Did you [perform a cursory search](https://github.com/issues?q=+is%3Aissue+repo%3Apressbooks%2Fpressbooks) to see if your bug or enhancement is already listed?

### Description

When importing language-tagged content, the Tidy stage strips out `lang` and `xml:lang` attributes from the resulting HTML.

### Steps to Reproduce

1. Import the styles-and-language document in #582.
2. Examine the resulting markup in the Pressbooks editor. The French phrase has no language tagging associated with it.

**Expected behavior:** 

```html
<em class="import-Foreign" lang="fr-FR" xml:lang="fr-FR">en français</em>
```

**Actual behavior:**

```html
<em class="import-Foreign">en français</em>
```

### System Information

Pressbooks: 3.9.6
WordPress: 4.7
PHP: 5.6.29

**Comment by crism** [comment]
I believe this is due to the configuration in the `htmLawed` module, which is called after every import. There is no security risk in allowing language tagging, so it should be configured not to strip those attributes.

**Comment by greatislander** [comment]
It doesn't seem to be htmLawed— I tried importing your sample doc while bypassing htmLawed altogether in the import module and the `lang` and `xml:lang` attributes were still absent.

**Comment by crism** [comment]
Thanks, @greatislander—I’d only done a superficial search for the source. Let me know if you want help or want to assign it to me.

**Comment by greatislander** [comment]
If you could take a look that would be great, thanks!

**Comment by crism** [comment]
@greatislander, how did you rule out `htmLawed`? It’s called directly in `Docx::tidy()`, though imported in the `Import` class file… I think it is still getting called, and I don’t see anywhere else that the HTML is manipulated to that degree.

**Comment by greatislander** [comment]
I modified the `Docx::tidy()` method to just return the `$html` variable without passing it through `htmLawed`. I missed the identically-named method in the parent class, though.

**Comment by crism** [comment]
OK… this is weird. When I insert `return $html;` in `Docx::tidy()` before the call to `htmLawed()`, I get an `xml:lang` attribute but no `lang`. A couple of days ago, neither was there. `d-:`

**Comment by greatislander** [comment]
@crism FYI, this bug has been causing me problems—just so you are aware as you continue working on this http://core.trac.wordpress.org/ticket/39550

**Comment by crism** [comment]
The `valid_xhtml` setting to `htmLawed` causes `xml:lang` to be set to `2`, which in turn causes the cleaner to set `xml:lang` and omit `lang`. I think that’s OK, and it’s the behavior I’m currently seeing (though what changed from previously, I still have no idea). If we set `xml:lang` to `1` in the config options passsed to `htmLawed`, it returns both.

**Comment by crism** [comment]
Thanks for the heads-up, @greatislander—that does seem to have to do with WordPress and PHP security settings, though, and hasn’t affected me (yet).

**Comment by greatislander** [comment]
@crism I ran into it because I updated my local development environment to WP 4.7.1 and then found that your test file would no longer upload :)

**Comment by crism** [comment]
@greatislander: the WP bug is triggered by MIME type detection on the zip’d docx file; certain internal structures seem to make a difference. 
```
$ file *.docx
naively-zipped.docx:     Microsoft OOXML
saved_from_word.docx:    Microsoft Word 2007+
```
[This file](https://github.com/pressbooks/pressbooks/files/705460/styles_language_clean.docx) passes muster both with the `file` command and WordPress.

More concerning, it also appears that WordPress 4.7.1 filters `lang` and `xml:lang` attributes, even when entered directly in the editing area, rendering this whole thing moot without a configuration change.



Ugh. Probably not worth reopening this, but:

**Comment by greatislander** [comment]
@crism Ugh.
