### ISSUE TITLE
Footnote/endnote styling is lost in Word import

### ISSUE THREAD

**Issue by crism** [pressbooks/pressbooks#631]
### Prerequisites

* [x] Can you reproduce the behavior you wish to address with [all other plugins deactivated](http://codex.wordpress.org/Multisite_Network_Administration#Plugins)?
* [x] Are you running the [latest version of Pressbooks](http://github.com/pressbooks/pressbooks/releases/latest/) and the [latest version of WordPress](http://codex.wordpress.org/Upgrading_WordPress)?
* [x] Are you experiencing this issue with one of our built-in root or book themes?
* [x] Did you [perform a cursory search](https://github.com/issues?q=+is%3Aissue+repo%3Apressbooks%2Fpressbooks) to see if your bug or enhancement is already listed?

### Description

Footnote and endnote text is incorporated when importing Word .docx documents, but any styling is lost.

### Steps to Reproduce

1. Import the _Lorem ipsum_ footnote test document
2. Observe that footnote 2 has lost its italic styling.

**Expected behavior:** Footnote 2 should have an italic phrase in it.

**Actual behavior:** Footnote 2 is entirely in roman.

### System Information

Pressbooks: 3.9.6
WordPress: 4.7
PHP: 5.6.28

**Comment by crism** [comment]
The body of the Word document is converted via XSLT. The footnotes and endnotes are pillaged manually in PHP, after transformation. The footnotes and endnotes should be made available to the transformation (just cram them in, as is done for style information), and then handled appropriately.

**Comment by greatislander** [comment]
Thanks @crism!

**Comment by crism** [comment]
The book we’re working on right now had few enough footnotes that we addressed the formatting manually, but I do still intend to address this.

Currently, the import dumps the footnotes all at the end of the relevant chapter, with hyperlinks, but does not use the Pressbooks `[footnote]` markup, meaning that formatting gets pretty ugly, too. The convert-Word-footnotes button then loses any formatting that has been applied to the footnotes in the meanwhile.

The footnotes should be brought into the `[footnote]` structure right off the bat, rather than being dumped at the end; that way the presentation, once imported, will be kept.

**Comment by greatislander** [comment]
Thanks, @crism. We've noted another issue with Word footnote importing, namely that the entire `[footnote]` shortcode from an imported Word doc is wrapped in `<sup>` tags. I thought I remembered that this wasn't desired behaviour? This was discussed in https://github.com/pressbooks/pressbooks/pull/608 IIRC.

**Comment by crism** [comment]
Right, @greatislander—the Word importer now only places `sup` elements if the footnote/endnote references were superscripts in the Word doc—usually, but not always true. It also uses a `class` attribute on the `sup` elements if they were styled in Word (also usually true).

The Word footnote converter doesn’t expect the `sup` with `class`, I think—I haven’t really looked into it. If the Word importer generates the `[footnote]` shortcode right off the bat, then there’s no need to put it inside a `sup` (and, in fact, that would be bad to do).

**Comment by greatislander** [comment]
@crism Yes, the `[footnote]` shortcode is generated within the converter: https://github.com/pressbooks/pressbooks/blob/dev/includes/shortcodes/footnotes/class-pb-footnotes.php#L310

Not sure if that's what you're asking. But yes, I think we should get rid of the `<sup>` if possible. Is this something you'd be able to investigate this week?

**Comment by crism** [comment]
@greatislander Right—but what is the merit in having the Word importer put the footnotes at the end of the chapter with hyperlinks, then having the converter create `[footnote]` shortcodes, when the Word importer could just create the `[footnote]` shortcodes directly?

I will probably not get to this this week—trying to finish production on our first publication.

**Comment by greatislander** [comment]
Okay. Worth some further discussion. Thanks.

**Comment by greatislander** [comment]
@crism Any chance you'll be able to take a look at this in the near future? Cheers!

**Comment by crism** [comment]
@greatislander, I may not be able to carve out the time until our next PB-based project comes up, and I don’t know when that will be. I’m tracking down bugs in several of the other tools we’re using ATM.
