### ISSUE TITLE
"Additional Resources" feature for chapters 

### ISSUE THREAD

**Issue by hughmcguire** [pressbooks/pressbooks#641]
### Prerequisites

* [x] Can you reproduce the behavior you wish to address with [all other plugins deactivated](http://codex.wordpress.org/Multisite_Network_Administration#Plugins)?
* [x] Are you running the [latest version of Pressbooks](http://github.com/pressbooks/pressbooks/releases/latest/) and the [latest version of WordPress](http://codex.wordpress.org/Upgrading_WordPress)?
* [x] Are you experiencing this issue with one of our built-in root or book themes?
* [x] Did you [perform a cursory search](https://github.com/issues?q=+is%3Aissue+repo%3Apressbooks%2Fpressbooks) to see if your bug or enhancement is already listed?

### Description (Feature request):
 
* In making Open Textbooks (and other instructional materials) an author/editor will often want to link to additional resources (eg: an audio version of the text, a quiz, videos etc).

* Currently, this would be done in an unstructured way, by simply adding the links etc.

* Ideally, we would have an additional box in the chapter editing interface, that would allow the author to add an arbitrary number of external resources as follows: 

`[Link Text] [link URL] [description]`  

* This content would then be added to all exports in appropriate ways, so, eg video might appear on the web, but be linked in PDF etc.

NOTE this is not high priority at the moment, just wanted to record the feature idea.

**Comment by colomet** [comment]
Maybe we could help with that. We have that in our road map for our theme...

**Comment by SteelWagstaff** [comment]
Connected to https://github.com/pressbooks/ideas/issues/169
