### ISSUE TITLE
ODT icon and link to file not visible to public

### ISSUE THREAD

**Issue by pbstudent** [pressbooks/pressbooks#649]
### Prerequisites

_Check the boxes below by changing them from `[ ]` to `[x]`._

* [X] Can you reproduce the behavior you wish to address with [all other plugins deactivated](http://codex.wordpress.org/Multisite_Network_Administration#Plugins)?
* [X] Are you running the [latest version of Pressbooks](http://github.com/pressbooks/pressbooks/releases/latest/) and the [latest version of WordPress](http://codex.wordpress.org/Upgrading_WordPress)?
* [X ] Are you experiencing this issue with one of our built-in root or book themes?
* [x] Did you [perform a cursory search](https://github.com/issues?q=+is%3Aissue+repo%3Apressbooks%2Fpressbooks) to see if your bug or enhancement is already listed?

### Description
Export to ODT.  ODT produced in admin export. All export files enabled for public view. However, ODT icon not displayed, only white space with ODT link that fails.

[Description of the bug or feature]

### Steps to Reproduce

1. Share Latest Export Files enabled
2. Export to ODT
3. ODT file displayed in Export Your Book page
4. ODT icon not displayed on book site homepage
5. White space where icon should be with a link but selecting link creates a file not found error.

**Expected behavior:** [What you expected to happen]
ODT icon with direct download link to file
**Actual behavior:** [What actually happened]
White space with link to .../download?filename=Open-Educational-Resources-1477598819&type=odf
### System Information

_Replace this section with the contents of the Diagnostics page, available at `https://<yourdomain.tld>/<yourbook>/wp-admin/options.php?page=pressbooks_diagnostics` or via the Diagnostics link in the admin footer. If you are using Pressbooks < 3.9.4, you will have to enter the following information manually:_
#### Book Info
Book ID: 12
Book URL: http://epub-fhd.athabascau.ca/oer/
Book Privacy: Public

#### Browser

Platform: Apple
Browser Name: Firefox
Browser Version: 51.0
User Agent String: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:51.0) Gecko/20100101 Firefox/51.0

#### WordPress Configuration

Network URL: http://epub-fhd.athabascau.ca/
Network Type: Subdirectory
Version: 4.7.2
Language: en_US
WP_ENV: Not set
WP_DEBUG: Disabled
Memory Limit: 256M

#### Pressbooks Configuration

Version: 3.9.6
Book Theme: Open Textbooks
Book Theme Version: 1.0
Root Theme: Pressbooks Publisher
Root Theme Version: 3.0.1

#### Pressbooks Dependencies

Epubcheck: Installed
Kindlegen: Installed
xmllint: Installed
PrinceXML: Not Installed
Saxon-HE: Installed

#### Network Active Plugins

Antispam Bee: 2.6.9
Enable Media Replace: 3.0.5
GitHub Updater: 6.2.1
jQuery Smooth Scroll: 1.4.1
Pressbooks: 3.9.6
Pressbooks mPDF: 1.0.1
Pressbooks Textbook: 3.0.1
Simple Comment Editing: 2.1.5
Slider Captcha: 1.4.4
Slim Stat - Email Reports: 3.5.1
Slim Stat - Export to Excel: 2.5.5
Slim Stat Analytics: 4.5.2
SVG Support: 2.3.6
Thin Out Revisions: 1.8.3
UpdraftPlus - Backup/Restore: 2.12.32.22
Wordfence Security: 6.3.0
WP-FileManager: 1.4.0
WP First Letter Avatar: 2.2.7
WP SlimStat - Default Filters: 1.4.1
WP SlimStat - IP Address Fix: 1.7
WP SlimStat - Network Analysis: 1.5.1
WP SlimStat - Track Cookies: 1.5.1

#### Inactive Plugins

gee Search Plus: 1.4.4
Relevanssi: 3.5.7.1
WP SlimStat - Network Settings: 1.3

#### Server Configuration

PHP Version: 7.0.8-0ubuntu0.16.04.3
MySQL Version: 5.7.17
Webserver Info: Apache/2.4.18 (Ubuntu)

#### PHP Configuration

Safe Mode: Disabled
Memory Limit: 256M
Upload Max Size: 200M
Post Max Size: 200M
Upload Max Filesize: 200M
Time Limit: 30
Max Input Vars: 1000
URL-aware fopen: On (1)
Display Errors: N/A

#### PHP Extensions

cURL: Supported
cURL Version: 7.47.0
imagick: Not Installed
sass: Not Installed
xsl: Installed

**Comment by pbstudent** [comment]
Fix works on PBT 3.0.1 theme books sites.  However, I get a blank page when trying to access the Pressbooks Publisher 2.1 default root homepage.

**Comment by greatislander** [comment]
@pbstudent That doesn't sound like it's related. Also, we don't support Publisher 2.1 anymore but if you can find the error and submit a fix that would be great.

**Comment by pbstudent** [comment]
Correct! It was a combination of bad Internet connection at the same time I was applying the fixes and restarting Firefox. All good now, considering I don't know coding but your Github fix details worked. Thank you very much for the quick solution.
