### ISSUE TITLE
Custom Styles

### ISSUE THREAD

**Issue by greatislander** [pressbooks/pressbooks#658]
### Prerequisites

* [x] Can you reproduce the behavior you wish to address with [all other plugins deactivated](http://codex.wordpress.org/Multisite_Network_Administration#Plugins)?
* [x] Are you running the [latest version of Pressbooks](http://github.com/pressbooks/pressbooks/releases/latest/) and the [latest version of WordPress](http://codex.wordpress.org/Upgrading_WordPress)?
* [x] Are you experiencing this issue with one of our built-in root or book themes?
* [x] Did you [perform a cursory search](https://github.com/issues?q=+is%3Aissue+repo%3Apressbooks%2Fpressbooks) to see if your bug or enhancement is already listed?

### Description

The Pressbooks Custom CSS theme should be replaced for new users with an 'Custom Styles' feature, that allows additive (S)CSS on top of any theme's built-in stylesheets.

### Steps to Reproduce

Not applicable.

### System Information

Pressbooks: 4.1
WordPress: 4.8.1
PHP: 7.1

**Comment by pressbooksapurva** [comment]
An example of the code we have removed in the past, in the Christie EBOOK stylesheet is:
ul li li {
  list-style-image: url(images/em-dash.png); }

ul li li li {
  list-style-image: url(images/asterisk.png); }

**Comment by greatislander** [comment]
Could be overruled by:

```
ul li li {
  list-style-image: none;
}

ul li li li {
  list-style-image: none;
}
```

**Comment by greatislander** [comment]
### Mockup

![custom styles](https://user-images.githubusercontent.com/605361/29488797-8e2e65be-84e8-11e7-80bf-2acbda4d2b42.jpg)

### Notes

- Top block (Theme Styles) contains the compiled stylesheet for the selected format, and is NOT editable by the user (this will necessitate a separate compilation routine which excludes the custom styles so that we don't end up in INCEPTION).
- Bottom block (Your Styles) contains user-editable style rules which are appended to the end of the theme stylesheet for the selected format prior to compiling for export.
- Custom style rules will be saved in a custom post type created for this feature (`custom-style`).
- The theme style viewer and the custom styles editor will both use [CodeMirror](https://github.com/codemirror/CodeMirror) for syntax highlighting and (for the editor) linting (see implementation [here](https://github.com/WordPress/codemirror-wp)). It looks like CodeMirror will be bundled with WordPress 4.9 (see Trac [#12423](https://core.trac.wordpress.org/ticket/12423)) but for now we will have to include it ourselves.
- Export routines will append the user's custom styles to the theme stylesheet prior to compilation. For the webbook stylesheet, a recompile will be triggered whenever the user saves custom styles targeting web.
- OPTIONAL: Custom style rules can be added in either CSS or SCSS. A post meta key (`pb_custom_style_style_format`) will be used to indicate to Pressbooks whether the user has selected CSS or SCSS.

**Comment by connerbw** [comment]
PR:
https://github.com/pressbooks/pressbooks/pull/912

Suggestion: Don't merge until after eCampus/Pressbooks demo day. This change is pretty big and I'd like it to sit on the testing server for a week or two before going out for release.
