### ISSUE TITLE
Ability to hide front matter/chapters/back matter from TOC

### ISSUE THREAD

**Issue by greatislander** [pressbooks/pressbooks#659]
### Prerequisites

* [x] Can you reproduce the behavior you wish to address with [all other plugins deactivated](http://codex.wordpress.org/Multisite_Network_Administration#Plugins)?
* [x] Are you running the [latest version of Pressbooks](http://github.com/pressbooks/pressbooks/releases/latest/) and the [latest version of WordPress](http://codex.wordpress.org/Upgrading_WordPress)?
* [x] Are you experiencing this issue with one of our built-in root or book themes?
* [x] Did you [perform a cursory search](https://github.com/issues?q=+is%3Aissue+repo%3Apressbooks%2Fpressbooks) to see if your bug or enhancement is already listed?

### Description

It would be nice to be able to hide various content types other than parts from the TOC.

### Steps to Reproduce

Not applicable.

### System Information

Pressbooks: 3.9.7-dev
WordPress: 4.7.2
PHP: 7.1

**Comment by WhatLibrarian** [comment]
This would help with accessibility as when there is no Front or Back matter, this code:
`<h4><!-- Back-matter--> OR <!--Front-matter--></h4>`
Gets flagged as an error "A heading element is present that contains no text (or only spaces) and no images with alternative text. Standards and Guidelines:
-     Section 508 (o)
-     1.3.1 Info and Relationships (Level A)
-     2.4.1 Bypass Blocks (Level A)
-     2.4.6 Headings and Labels (Level AA)"
