### ISSUE TITLE
Format of tagged releases

### ISSUE THREAD

**Issue by bdolor** [pressbooks/pressbooks#669]
### Prerequisites

_Check the boxes below by changing them from `[ ]` to `[x]`._

* [ ] Can you reproduce the behavior you wish to address with [all other plugins deactivated](http://codex.wordpress.org/Multisite_Network_Administration#Plugins)?
* [x] Are you running the [latest version of Pressbooks](http://github.com/pressbooks/pressbooks/releases/latest/) and the [latest version of WordPress](http://codex.wordpress.org/Upgrading_WordPress)?
* [ ] Are you experiencing this issue with one of our built-in root or book themes?
* [x] Did you [perform a cursory search](https://github.com/issues?q=+is%3Aissue+repo%3Apressbooks%2Fpressbooks) to see if your bug or enhancement is already listed?

### Description

I believe the format of the PB tagged release ($repo-**v**$tag.zip *or* pressbooks-**v**3.9.7.1.zip) is preventing Github Updater from grabbing the latest tagged release of PB. It falls back to grabbing the master branch of PB which results in a fatal error after an update. (Line 101 in pressbooks.php gets triggered because no `/vendor/` directory.) If the format of the tagged release for PB is modified to ($repo-$tag.zip *or* pressbooks-3.9.7.1.zip) as is specified [here](https://github.com/afragen/github-updater/wiki/Settings#release-assets) will the Github Updater grab the tagged release instead of the master branch?

### Steps to Reproduce

1. Have Github Updater installed, activated and pointed to Pressbooks repo in Github 
2. Have a version of PB less than the latest version in Github. 
2. Update PB plugin using Github Updater

**Expected behavior:** 
An absence of fatal errors after PB updates to the latest tagged release (3.9.7.1) 

**Actual behavior:** 
Fatal error is triggered (line 101 in `pressbooks.php`) because it appears to grab the master branch instead of the tagged, compiled version.  

Pressbooks: 3.9.6
WordPress: 4.7.2
PHP: 5.6+

**Comment by greatislander** [comment]
@bdolor Well, gee, all this time I had thought it was supposed to be `$repo-v$tag.zip`. 😳

I'll fix this…

**Comment by bdolor** [comment]
I use the same format for PBT.

**Comment by bdolor** [comment]
Further information (not resolved): The directory name /**v**3.9.7.1/ is significant @see here https://github.com/afragen/github-updater/blob/develop/src/GitHub_Updater/API.php#L288 

It will be looking for `https://github.com/pressbooks/pressbooks/releases/download/3.9.7.1/pressbooks-3.9.7.1.zip`

It is currently
`https://github.com/pressbooks/pressbooks/releases/download/v3.9.7.1/pressbooks-3.9.7.1.zip`

**Comment by greatislander** [comment]
✅ https://github.com/pressbooks/pressbooks/releases/tag/3.9.7.1

**Comment by bdolor** [comment]
I'm under the impression we may just have to wait until the next tagged release from PB. There is a difference between how the tags are named in the api and how the tags have been re-named in the github interface. 

https://api.github.com/repos/pressbooks/pressbooks/tags
