### ISSUE TITLE
Some predefined table stylings might be unexpected or even wrong 

### ISSUE THREAD

**Issue by thomasdumm** [pressbooks/pressbooks#672]
### Prerequisites

_Check the boxes below by changing them from `[ ]` to `[x]`._

* [x] Can you reproduce the behavior you wish to address with [all other plugins deactivated](http://codex.wordpress.org/Multisite_Network_Administration#Plugins)?
* [x] Are you running the [latest version of Pressbooks](http://github.com/pressbooks/pressbooks/releases/latest/) and the [latest version of WordPress](http://codex.wordpress.org/Upgrading_WordPress)?
* [x] Are you experiencing this issue with one of our built-in root or book themes?
* [x] Did you [perform a cursory search](https://github.com/issues?q=+is%3Aissue+repo%3Apressbooks%2Fpressbooks) to see if your bug or enhancement is already listed?

### Description

Some predefined table stylings might be unexpected or even wrong. I made printscreens of what they look like in ebpub3 and pdf and printscreens of what I would expect them to look like.

ALSO: The editor view and the online version should be consistant with the PDF and EPUP3, eg should look like delivros_epub3.jpg, delivros_print_pdf.jpg .

### Steps to Reproduce

1. create 4 tables
2. assign the 4 predefined tables classe to each table
3. create pdf and epub3

**Expected behavior:** [What you expected to happen]
delivros_epub3.jpg, delivros_print_pdf.jpg

**Actual behavior:** [What actually happened]
clarke_epub3.jpg, clarke_print_pdf.jpg

CSS added to clake to make delivros (actually $shade-color-1 did not work for me, so is used #eee):
-----
table:not([class]), table:not([class]) td, table:not([class]) th {
  border: $table-border-width solid;
  border-color: if-map-get($line-color-1, $type);
}

.no-lines, .no-lines td, .no-lines th {
  border: 0;
}

.lines tr {
  border-top: $table-border-width solid;
  border-bottom: $table-border-width solid;
  border-left: none;
  border-right: none;
  border-top-color: if-map-get($line-color-1, $type);
  border-bottom-color: if-map-get($line-color-1, $type);
}

thead, thead td, thead th, th {
  background-color: $shade-color-1;
}
.shaded {
  background-color: $shade-color-1;
  border: 0;
}

-----
clarke_epub3
![clarke_epub3](https://cloud.githubusercontent.com/assets/3658808/23263242/f3df3c08-f9dd-11e6-9ceb-04e55f9e01f6.jpg)
clarke_print_pdf
![clarke_print_pdf](https://cloud.githubusercontent.com/assets/3658808/23263247/f75b359e-f9dd-11e6-84a4-fc650d9c885f.jpg)
delivros_epub3
![delivros_epub3](https://cloud.githubusercontent.com/assets/3658808/23263255/fc641952-f9dd-11e6-89a4-a39d8ec170b4.jpg)
delivros_print_pdf
![delivros_print_pdf](https://cloud.githubusercontent.com/assets/3658808/23263261/ffd769b8-f9dd-11e6-94ea-6a0273ccd4ee.jpg)

**Comment by greatislander** [comment]
Moving this to https://github.com/pressbooks/pressbooks-book/issues/17
