### ISSUE TITLE
Odd spacing after first paragraph after headers

### ISSUE THREAD

**Issue by crism** [pressbooks/pressbooks#676]
### Prerequisites

* [x] Can you reproduce the behavior you wish to address with [all other plugins deactivated](http://codex.wordpress.org/Multisite_Network_Administration#Plugins)?
* [x] Are you running the [latest version of Pressbooks](http://github.com/pressbooks/pressbooks/releases/latest/) and the [latest version of WordPress](http://codex.wordpress.org/Upgrading_WordPress)?
* [x] Are you experiencing this issue with one of our built-in root or book themes?
* [x] Did you [perform a cursory search](https://github.com/issues?q=+is%3Aissue+repo%3Apressbooks%2Fpressbooks) to see if your bug or enhancement is already listed?

### Description

The first paragraph after a heading has an odd gap after it.

This appears to be a result of [this rule](https://github.com/pressbooks/pressbooks/blob/dev/themes-book/pressbooks-book/style.scss#L149):
```css
h1 + p,
h2 + p,
h3 + p,
h4 + p,
h5 + p,
h6 + p {
  margin-top: -10px;
  margin-bottom: 30px;
}
```
This is double the bottom margin for other paragraphs. The fix is obvious, but I want to be sure I’m not misunderstanding the intent or overlooking something.

### Steps to Reproduce

1. Create a chapter with at least three paragraphs, a subheader, and at least three more paragraphs.
2. Publish it.
3. Observe the published book in a browser.

**Expected behavior:**

Paragraphs should be evenly spaced.

**Actual behavior:**

The first paragraph after the subheader has a jarring gap between itself and the second paragraph.

### System Information

Pressbooks: 3.9.7
WordPress: 4.7.2
PHP: 5.6.29

**Comment by greatislander** [comment]
@crism No idea. Fixing this.
