### ISSUE TITLE
The xhtml export is invalid because of the lang attribut on the body element

### ISSUE THREAD

**Issue by thomasdumm** [pressbooks/pressbooks#683]
### Prerequisites

* [x] Can you reproduce the behavior you wish to address with [all other plugins deactivated](http://codex.wordpress.org/Multisite_Network_Administration#Plugins)?
* [x] Are you running the [latest version of Pressbooks](http://github.com/pressbooks/pressbooks/releases/latest/) and the [latest version of WordPress](http://codex.wordpress.org/Upgrading_WordPress)?
* [x] Are you experiencing this issue with one of our built-in root or book themes?
* [x] Did you [perform a cursory search](https://github.com/issues?q=+is%3Aissue+repo%3Apressbooks%2Fpressbooks) to see if your bug or enhancement is already listed?

### Description

The xhtml export is invalid because of the lang attribut on the body element

### Steps to Reproduce

1. export xhtml file
2. open it in an validation tool like Oxygen
3. validate

**Expected behavior:** [What you expected to happen]
xhtml file is valid
**Actual behavior:** [What actually happened]
xhtml file is invalid

**Comment by greatislander** [comment]
@thomasdumm I ran a Pressbooks XHTML file through the [W3C Validator](http://validator.w3.org) service and it validated as XHTML 1.1 despite the `lang` attribute. Not sure if I'm missing something here.

**Comment by greatislander** [comment]
The reason we added the `<body lang='en'>` attribute was to support Prince's hyphenation dictionaries in non-English languages. See https://github.com/pressbooks/pressbooks/issues/257#issuecomment-144208827.
