### ISSUE TITLE
PB Update 3.9.7.2 has Version 3.9.8-dev in plugins list description.

### ISSUE THREAD

**Issue by pbstudent** [pressbooks/pressbooks#694]
### Prerequisites

_Check the boxes below by changing them from `[ ]` to `[x]`._

* [X] Can you reproduce the behavior you wish to address with [all other plugins deactivated](http://codex.wordpress.org/Multisite_Network_Administration#Plugins)?
* [X ] Are you running the [latest version of Pressbooks](http://github.com/pressbooks/pressbooks/releases/latest/) and the [latest version of WordPress](http://codex.wordpress.org/Upgrading_WordPress)?
* [ x] Are you experiencing this issue with one of our built-in root or book themes?
* [x ] Did you [perform a cursory search](https://github.com/issues?q=+is%3Aissue+repo%3Apressbooks%2Fpressbooks) to see if your bug or enhancement is already listed?

### Description

Wrong version in description

### Steps to Reproduce

1. update plugin within plugins page or download pressbooks-3.9.7.2.zip
2. PB plugin displays Version 3.9.8-dev

**Expected behavior:** [What you expected to happen]

display Version 3.9.7.2

**Actual behavior:** [What actually happened]

Displayed Version 3.9.8-dev

### System Information

_Replace this section with the contents of the Diagnostics page, available at `https://<yourdomain.tld>/<yourbook>/wp-admin/options.php?page=pressbooks_diagnostics` or via the Diagnostics link in the admin footer. If you are using Pressbooks < 3.9.4, you will have to enter the following information manually:_
Diagnostics link states - Sorry, you are not allowed to access this page.

Pressbooks: pressbooks-3.9.7.2.zip  Version 3.9.8-dev
WordPress: 4.7.3
PHP: 7.0.15-0ubuntu0.16.04.4

_You can get the version of Pressbooks from the readme.txt file in the Pressbooks plugin (usually located at `https://<yourdomain.tld>/wp-content/plugins/pressbooks/readme.txt`) and the version of WordPress from the readme.html file in the WordPress root directory (usually located at `https://<yourdomain.tld>/readme.html`). You can usually get your PHP version from your web host, or by using the [`phpversion()`](http://php.net/manual/en/function.phpversion.php) function._

**Comment by greatislander** [comment]
Thanks for catching this. Please download the fixed version, unzip and replace the pressbooks folder in your plugins directory: https://github.com/pressbooks/pressbooks/releases/download/3.9.7.2/pressbooks-3.9.7.2.zip
