### ISSUE TITLE
Changing global privacy to Private on Organize doesn’t update view

### ISSUE THREAD

**Issue by greatislander** [pressbooks/pressbooks#711]
### Prerequisites

* [x] Can you reproduce the behavior you wish to address with [all other plugins deactivated](http://codex.wordpress.org/Multisite_Network_Administration#Plugins)?
* [x] Are you running the [latest version of Pressbooks](http://github.com/pressbooks/pressbooks/releases/latest/) and the [latest version of WordPress](http://codex.wordpress.org/Upgrading_WordPress)?
* [x] Are you experiencing this issue with one of our built-in root or book themes?
* [x] Did you [perform a cursory search](https://github.com/issues?q=+is%3Aissue+repo%3Apressbooks%2Fpressbooks) to see if your bug or enhancement is already listed?

### Description

Toggling the global privacy radio button from Public → Private on the Organize page should update the status text.

### Steps to Reproduce

1. Set Book Visibility to Public in Sharing & Privacy settings. 
2. Navigate to the Organize page.
3. Toggle the global privacy radio button to Private.

**Expected behavior:** The status text should change to: "This book's global privacy is set to PRIVATE."

**Actual behavior:** It remains unchanged.

### System Information

Pressbooks: 3.9.8-RC1
WordPress: 4.7.3
PHP: 7.1

**Comment by greatislander** [comment]
Now it's not working at all 👎

**Comment by pressbooksapurva** [comment]
Looks good to go!
