### ISSUE TITLE
Chapter types bug

### ISSUE THREAD

**Issue by colomet** [pressbooks/pressbooks#712]
### Prerequisites

_Check the boxes below by changing them from `[ ]` to `[x]`._

* [x ] Can you reproduce the behavior you wish to address with [all other plugins deactivated](http://codex.wordpress.org/Multisite_Network_Administration#Plugins)?
* [x ] Are you running the [latest version of Pressbooks](http://github.com/pressbooks/pressbooks/releases/latest/) and the [latest version of WordPress](http://codex.wordpress.org/Upgrading_WordPress)?
* [x ] Are you experiencing this issue with one of our built-in root or book themes?
* [x ] Did you [perform a cursory search](https://github.com/issues?q=+is%3Aissue+repo%3Apressbooks%2Fpressbooks) to see if your bug or enhancement is already listed?

### Description

The chapters do not show the number. If i try to change change the Chapter Type from  one to the other, do not work. Numberless or Standard. Always the selected buttom is Numberless.

![captura de pantalla 2017-04-05 a las 9 21 37](https://cloud.githubusercontent.com/assets/3929177/24694826/c1b6c400-19e3-11e7-8cad-a96661ed6221.png)
### Steps to Reproduce

1. open a chapter
2. change the chapter type
3. view the page

**Expected behavior:** to see numers or not upon request

**Actual behavior:** nothing.

#### Book Info

Book ID: 7
Book URL: http://pressbooks.lvps84-39-103-248.mammuts-servidor.es/test/
Book Privacy: Public

#### Browser

Platform: Apple
Browser Name: Firefox
Browser Version: 52.0
User Agent String: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:52.0) Gecko/20100101 Firefox/52.0

#### WordPress Configuration

Network URL: http://pressbooks.lvps84-39-103-248.mammuts-servidor.es/
Network Type: Subdirectory
Version: 4.7.3
Language: en_US
WP_ENV: Not set
WP_DEBUG: Disabled
Memory Limit: 64M

#### Pressbooks Configuration

Version: 3.9.8
Book Theme: Luther
Book Theme Version: 1.7.0
Root Theme: Pressbooks Publisher
Root Theme Version: 3.0.1

#### Pressbooks Dependencies

Epubcheck: Not Installed
Kindlegen: Not Installed
xmllint: Not Installed
PrinceXML: Not Installed
Saxon-HE: Not Installed

#### Network Active Plugins

Pressbooks: 3.9.8-RC1

#### Inactive Plugins

Akismet Anti-Spam: 3.3
Hello Dolly: 1.6
Pressbooks mPDF: 1.6.1
Pressbooks Textbook: 3.0.2
Wordfence Security: 6.3.5

#### Server Configuration

PHP Version: 7.0.16
MySQL Version: 5.5.53
Webserver Info: Apache

#### PHP Configuration

Safe Mode: Disabled
Memory Limit: 256M
Upload Max Size: 2M
Post Max Size: 8M
Upload Max Filesize: 2M
Time Limit: 30
Max Input Vars: 1000
URL-aware fopen: On (1)
Display Errors: N/A

#### PHP Extensions

cURL: Supported
cURL Version: 7.35.0
imagick: Installed
xsl: Installed

**Comment by greatislander** [comment]
Hi Antonio, I can't reproduce this. See [screen recording](https://www.dropbox.com/s/ewgmmjb0wz8xe72/Chapter%20Types.mov?dl=0).
