### ISSUE TITLE
Pressbooks 3.9.8-RC2: I do not understand the new "Section Openings" 

### ISSUE THREAD

**Issue by thomasdumm** [pressbooks/pressbooks#714]
### Prerequisites

_Check the boxes below by changing them from `[ ]` to `[x]`._

* [x] Can you reproduce the behavior you wish to address with [all other plugins deactivated](http://codex.wordpress.org/Multisite_Network_Administration#Plugins)?
* [x] Are you running the [latest version of Pressbooks](http://github.com/pressbooks/pressbooks/releases/latest/) and the [latest version of WordPress](http://codex.wordpress.org/Upgrading_WordPress)?
* [x] Are you experiencing this issue with one of our built-in root or book themes?
* [x] Did you [perform a cursory search](https://github.com/issues?q=+is%3Aissue+repo%3Apressbooks%2Fpressbooks) to see if your bug or enhancement is already listed?

### Description

No blank pages (for web PDF) --> I do not understand this option.  I thought the web PDF never has blank pages.  I would only expect the first two options, labeled like this
- Left or right page section openings in print PDF
- Right page section openings in print PDF
I would expect that these options have no influence on the web PDF

What am I not understanding correctly?

**Comment by greatislander** [comment]
This is consistent with the old behaviour. In Pressbooks < 3.9.8, there were two options, one suitable for digital distribution (remove blank pages) and the other for print. This isn't perfect yet but we wanted to add the open right option in addition to the open auto option.

**Comment by greatislander** [comment]
(There may be circumstances where someone may want to digitally distribute a PDF with blank pages, so there are some assumptions there we can't make at the point of export—at least not at this point.)

**Comment by thomasdumm** [comment]
ok
