### ISSUE TITLE
 Hide of the Ebook Options Exports

### ISSUE THREAD

**Issue by colomet** [pressbooks/pressbooks#717]
### Prerequisites

_Check the boxes below by changing them from `[ ]` to `[x]`._

* [x] Can you reproduce the behavior you wish to address with [all other plugins deactivated](http://codex.wordpress.org/Multisite_Network_Administration#Plugins)?
* [x] Are you running the [latest version of Pressbooks](http://github.com/pressbooks/pressbooks/releases/latest/) and the [latest version of WordPress](http://codex.wordpress.org/Upgrading_WordPress)?
* [x] Are you experiencing this issue with one of our built-in root or book themes?
* [x] Did you [perform a cursory search](https://github.com/issues?q=+is%3Aissue+repo%3Apressbooks%2Fpressbooks) to see if your bug or enhancement is already listed?

### Description

The Ebook options should be active just if we have the dependencies installed and the epub export buttom activate.

**Expected behavior:** 
Not the see such section in the options page

**Actual behavior:** 
![3fe9da4cad6ad2d7ecd318e8fde607b21737cf8a_1_690x391](https://cloud.githubusercontent.com/assets/3929177/24761974/4275f0c0-1aed-11e7-8a42-c252aa8da625.png)

#### Book Info

Book ID: 3
Book URL: http://pressbooks.lvps84-39-103-248.mammuts-servidor.es/fitzgerald/
Book Privacy: Public

#### Browser

Platform: Apple
Browser Name: Firefox
Browser Version: 52.0
User Agent String: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:52.0) Gecko/20100101 Firefox/52.0

#### WordPress Configuration

Network URL: http://pressbooks.lvps84-39-103-248.mammuts-servidor.es/
Network Type: Subdirectory
Version: 4.7.3
Language: en_US
WP_ENV: Not set
WP_DEBUG: Enabled
Memory Limit: 64M

#### Pressbooks Configuration

Version: 3.9.8
Book Theme: Fitzgerald
Book Theme Version: 1.6
Root Theme: Pressbooks Publisher
Root Theme Version: 3.0.1

#### Pressbooks Dependencies

Epubcheck: Not Installed
Kindlegen: Not Installed
xmllint: Not Installed
PrinceXML: Not Installed
Saxon-HE: Not Installed

#### Network Active Plugins

Pressbooks: 3.9.8-RC2
Pressbooks mPDF: 1.6.1

#### Inactive Plugins

Akismet Anti-Spam: 3.3
Hello Dolly: 1.6
Pressbooks Textbook: 3.0.2
Wordfence Security: 6.3.5

#### Server Configuration

PHP Version: 7.0.16
MySQL Version: 5.5.53
Webserver Info: Apache

#### PHP Configuration

Safe Mode: Disabled
Memory Limit: 256M
Upload Max Size: 2M
Post Max Size: 8M
Upload Max Filesize: 2M
Time Limit: 30
Max Input Vars: 1000
URL-aware fopen: On (1)
Display Errors: On (1)

#### PHP Extensions

cURL: Supported
cURL Version: 7.35.0
imagick: Installed
xsl: Installed

**Comment by greatislander** [comment]
Fixed in #745.
