### ISSUE TITLE
Remove 300dpi image resolution option and forced 300dpi images from print PDF

### ISSUE THREAD

**Issue by greatislander** [pressbooks/pressbooks#744]
### Prerequisites

* [x] Can you reproduce the behavior you wish to address with [all other plugins deactivated](http://codex.wordpress.org/Multisite_Network_Administration#Plugins)?
* [x] Are you running the [latest version of Pressbooks](http://github.com/pressbooks/pressbooks/releases/latest/) and the [latest version of WordPress](http://codex.wordpress.org/Upgrading_WordPress)?
* [x] Are you experiencing this issue with one of our built-in root or book themes?
* [x] Did you [perform a cursory search](https://github.com/issues?q=+is%3Aissue+repo%3Apressbooks%2Fpressbooks) to see if your bug or enhancement is already listed?

### Description

Forcing 300dpi doesn't work well. Sometimes the uploaded images are too small and they get downscaled, which is confusing and frustrating. We should remove the 300dpi image resolution option and corresponding SCSS output (as well as the forced version in Print PDF outputs) and seek a better solution for guiding users to upload print-ready images. (See also #497, #640.)

### Steps to Reproduce

Not applicable.

### System Information

Pressbooks: 3.9.9-dev
WordPress: 4.7.4
PHP: 7.1

**Comment by connerbw** [comment]
Back to the drawing board. More thorough solution to come.
