### ISSUE TITLE
In new themes, footnote block needs variables for top-margin & border 

### ISSUE THREAD

**Issue by hughmcguire** [pressbooks/pressbooks#748]
### Prerequisites

_Check the boxes below by changing them from `[ ]` to `[x]`._

* [x] Can you reproduce the behavior you wish to address with [all other plugins deactivated](http://codex.wordpress.org/Multisite_Network_Administration#Plugins)?
* [x] Are you running the [latest version of Pressbooks](http://github.com/pressbooks/pressbooks/releases/latest/) and the [latest version of WordPress](http://codex.wordpress.org/Upgrading_WordPress)?
* [x] Are you experiencing this issue with one of our built-in root or book themes?
* [x] Did you [perform a cursory search](https://github.com/issues?q=+is%3Aissue+repo%3Apressbooks%2Fpressbooks) to see if your bug or enhancement is already listed?

### Description

In new theme structure there is no mechanism to control footnote block top-margin & border.

Need to add in `~styles/components/specials/_footnotes.scss` the following: 
```
@page {
  @footnotes {
    margin-top: $footnote-block-margin-top;
    border-top: $footnote-block-border-top;
 }
}
```
and then in `~styles/variables/specials.scss` the following: 

```
// footnotes
$footnote-block-margin-top: .5em;
$footnote-block-border-top: 0;
```

and test.

**Comment by hughmcguire** [comment]
note: i should do this but pressed for time & don't want to mess anything up.

**Comment by greatislander** [comment]
Closed in favour of https://github.com/pressbooks/pressbooks-book/issues/2
