### ISSUE TITLE
API: map /wp-json/wp/v2/media to our namespace

### ISSUE THREAD

**Issue by greatislander** [pressbooks/pressbooks#772]
### Prerequisites

* [x] Can you reproduce the behavior you wish to address with [all other plugins deactivated](http://codex.wordpress.org/Multisite_Network_Administration#Plugins)?
* [x] Are you running the [latest version of Pressbooks](http://github.com/pressbooks/pressbooks/releases/latest/) and the [latest version of WordPress](http://codex.wordpress.org/Upgrading_WordPress)?
* [x] Are you experiencing this issue with one of our built-in root or book themes?
* [x] Did you [perform a cursory search](https://github.com/issues?q=+is%3Aissue+repo%3Apressbooks%2Fpressbooks) to see if your bug or enhancement is already listed?

### Description

There is already a media endpoint in the WordPress REST API: https://developer.wordpress.org/rest-api/reference/media/

We need to map it to our namespace: `/wp-json/pressbooks/v2/media`

### Steps to Reproduce

Not applicable.

### System Information

Pressbooks: 4.0.0-dev
WordPress: 4.7.5
PHP: 7.1

**Comment by connerbw** [comment]
I've been playing around with this for hours.
Mapping this endpoint into our endpoint breaks too many other objects `_links`.
I'm going to revert this.
