### ISSUE TITLE
v3.9.9: Undefined class constant 'VERSION' in includes/modules/themeoptions/class-pb-themeoptions.php on line 38

### ISSUE THREAD

**Issue by crism** [pressbooks/pressbooks#773]
### Prerequisites

* [ ] Can you reproduce the behavior you wish to address with [all other plugins deactivated](http://codex.wordpress.org/Multisite_Network_Administration#Plugins)?
* [x] Are you running the [latest version of Pressbooks](http://github.com/pressbooks/pressbooks/releases/latest/) and the [latest version of WordPress](http://codex.wordpress.org/Upgrading_WordPress)?
* [x] Are you experiencing this issue with one of our built-in root or book themes?
* [x] Did you [perform a cursory search](https://github.com/issues?q=+is%3Aissue+repo%3Apressbooks%2Fpressbooks) to see if your bug or enhancement is already listed?

### Description

I upgraded a Pressbooks 3.9.8 install to 3.9.9 via:
```
git pull
git checkout tags/3.9.9
php composer.phar update
```
The Pressbooks homepage is OK, but visiting the dashboard produces the error message in the title. Rolling back to 3.9.8.2 resolves the problem.

The problem appears to be related to af588665.

### Steps to Reproduce

See above.

### System Information

Pressbooks: 3.9.9
WordPress: 4.7.5
PHP: 5.6.30

**Comment by greatislander** [comment]
Do you have any other plugins installed?

**Comment by crism** [comment]
I have Akismet, Hello Dolly, mPDF, and Google Analytics Dashboard for WP, all disabled. (Normally, mPDF and GA are enabled.) New info, though: logging in as the admin user, everything’s fine, regardless of plugins. Logging in as an ordinary user, it is fine with GA Dashboard, but dies with mPDF activated. That’s a problem; mPDF is kind of important…

**Comment by greatislander** [comment]
Yes, and a patch has been submitted and merged: https://github.com/BCcampus/pressbooks-mpdf/pull/25

I'm not sure when an updated release of Pressbooks mPDF will be available with this fix as that plugin is not maintained by the Pressbooks organization. However, you should be able to pull down the dev branch of Pressbooks mPDF to resolve this issue in the meantime.

On a more general note, the issue template asks whether your bug occurs with third-party plugins enabled for a good reason, so please don't check that box unless the issue really does occur with only Pressbooks active. Thanks!

**Comment by crism** [comment]
@greatislander—thanks for the info on mPDF. And sorry again for the oversight—I thought they were disabled when I found this, but it’s hard to tell when the dashboard is broken. `)-:`

**Comment by greatislander** [comment]
Fair point! Cheers.
