### ISSUE TITLE
Review network manager functionality

### ISSUE THREAD

**Issue by greatislander** [pressbooks/pressbooks#791]
### Prerequisites

* [x] Can you reproduce the behavior you wish to address with [all other plugins deactivated](http://codex.wordpress.org/Multisite_Network_Administration#Plugins)?
* [x] Are you running the [latest version of Pressbooks](http://github.com/pressbooks/pressbooks/releases/latest/) and the [latest version of WordPress](http://codex.wordpress.org/Upgrading_WordPress)?
* [x] Are you experiencing this issue with one of our built-in root or book themes?
* [x] Did you [perform a cursory search](https://github.com/issues?q=+is%3Aissue+repo%3Apressbooks%2Fpressbooks) to see if your bug or enhancement is already listed?

### Description

The network managers feature could use some reconfiguring, ideally to use capabilities in a more orthodox fashion.

See:

* https://github.com/pressbooks/pressbooks/blob/dev/inc/admin/networkmanagers/namespace.php
* https://github.com/pressbooks/pressbooks/blob/dev/inc/admin/class-network-managers-list-table.php
* https://github.com/pressbooks/pressbooks/blob/dev/assets/src/scripts/network-managers.js

### Steps to Reproduce

Not applicable.

### System Information

Pressbooks: 4.0.0-dev
WordPress: 4.7.5
PHP: 7.1

**Comment by connerbw** [comment]
I did some work on this, setting/removing capabilities successfully, but  `\WP_User::has_cap` still uses `is_super_admin`

@see https://github.com/WordPress/wordpress-develop/blob/master/src/wp-includes/class-wp-user.php#L729

AFAIK Pressbooks doesn't offer any Network user controls except for the default "Grant this user super admin privileges for the Network." option available in WP. 

+ With super admin privileges set to ON: Capabilities are ignored. my code changes do nothing.
+ With super admin privileges set to OFF: User is not considered a site_admin, my code changes do nothing.

I'm not sure we can improve your current approach. Will continue looking into it.

**Comment by connerbw** [comment]
Let's come back when is_super_admin() is removed from `\WP_User::has_cap`

For now what was done works fine.
