### ISSUE TITLE
Change is_super_admin() to current_user_can('manage_network')

### ISSUE THREAD

**Issue by connerbw** [pressbooks/pressbooks#796]
### Prerequisites

_Check the boxes below by changing them from `[ ]` to `[x]`._

* [x] Can you reproduce the behavior you wish to address with [all other plugins deactivated](http://codex.wordpress.org/Multisite_Network_Administration#Plugins)?
* [x] Are you running the [latest version of Pressbooks](http://github.com/pressbooks/pressbooks/releases/latest/) and the [latest version of WordPress](http://codex.wordpress.org/Upgrading_WordPress)?
* [x] Are you experiencing this issue with one of our built-in root or book themes?
* [x] Did you [perform a cursory search](https://github.com/issues?q=+is%3Aissue+repo%3Apressbooks%2Fpressbooks) to see if your bug or enhancement is already listed?

### Description

WP is planning to remove the `is_super_admin()` function for future releases.

Sources:
 + https://make.wordpress.org/core/2017/05/22/multisite-focused-changes-in-4-8/
 + https://core.trac.wordpress.org/ticket/37616

Let's beat the clock?

Change: `is_super_admin();`
To: `user_can( $user_id, 'manage_network' );` or  `current_user_can( 'manage_network' );` 

### Steps to Reproduce

Not applicable.

### System Information

Pressbooks: 4.0.0-dev
WordPress: 4.7.5
PHP: 7.1

**Comment by connerbw** [comment]
More info:
https://codex.wordpress.org/Roles_and_Capabilities#manage_network

**Comment by connerbw** [comment]
Related: https://github.com/pressbooks/pressbooks/issues/791

**Comment by greatislander** [comment]
Let's re-open this when changes land in WordPress Core.
