### ISSUE TITLE
Content licensing

### ISSUE THREAD

**Issue by greatislander** [pressbooks/pressbooks#805]
### Prerequisites

* [x] Can you reproduce the behavior you wish to address with [all other plugins deactivated](http://codex.wordpress.org/Multisite_Network_Administration#Plugins)?
* [x] Are you running the [latest version of Pressbooks](http://github.com/pressbooks/pressbooks/releases/latest/) and the [latest version of WordPress](http://codex.wordpress.org/Upgrading_WordPress)?
* [x] Are you experiencing this issue with one of our built-in root or book themes?
* [x] Did you [perform a cursory search](https://github.com/issues?q=+is%3Aissue+repo%3Apressbooks%2Fpressbooks) to see if your bug or enhancement is already listed?

### Description

Licensing (Creative Commons flavours, public domain, etc.) should available for all content: books, parts/chapters/front matter/back matter, and media. See also: https://github.com/pressbooks/pressbooks/issues/108, https://github.com/pressbooks/pressbooks/issues/195, https://github.com/lumenlearning/candela-citation

### Steps to Reproduce

Not applicable.

### System Information

Pressbooks: 4.0.0-dev
WordPress: 4.8.0
PHP: 7.1

**Comment by hughmcguire** [comment]
Hi Ned, here is a detailed spreadsheet (conceptual & then detailed) of how the licensing module in general should work: 
https://docs.google.com/spreadsheets/d/1pMFuNUF9fRFBEN8VlfPasXFp2y6tvZyuTfEAa7T02eE/edit

**Comment by zwhpressbooks** [comment]
# Testing Notes

## All exports:
Custom/freeform notice should appear *after* the auto license on copyright page.

## EPUB:
Section license does not display correctly at end of section & I have had two different results. With same license, on one chapter the image is missing but text is present, in other chapter image is missing and text cuts off at author.

Check an EPUB export here: https://testbook.textopress.com/wp-admin/

## MOBI:
CC license image does not appear at end of section (copyright page ok).

## PDF:
Section license appears correctly at end of section, but could benefit from some styling. Is this easy to do? I could write up a snippet.

## Webbook:
Freeform/custom copyright notice does not appear in footer, just the auto license text.

**Comment by greatislander** [comment]
@connerbw Can you fix as many of these issues as you can? I think the PDF styling will be the sticking point so you can leave that for me.

**Comment by connerbw** [comment]
TODO: PDF: Section license appears correctly at end of section, but could benefit from some styling. Is this easy to do? I could write up a snippet.

**Comment by greatislander** [comment]
@zwhpressbooks This should be all fixed except for the PDF styling which I'll check tomorrow.

**Comment by pressbooksapurva** [comment]
## Testing Notes

### All exports:
Custom/freeform notice appears *after* the auto license on copyright page. 

### EPUB:
Section license does not displays correctly at end of section.

### MOBI:
CC license image appears at end of section. However, the author name is linked to the corresponding section on the Pressbooks webbook. Is this the desired behaviour?

Check an export here: https://apurvatestbook.textopress.com/wp-admin/

### PDF:
Still waiting on styling.

### Webbook:
Freeform/custom copyright notice appears in footer, below the chapter/book-level license.

**Comment by connerbw** [comment]
After a week of hanging out at the cottage, then coming back to this issue, it feels rough around the edges.  

_TODO:_ PDF styling, can we improve Epub end of section with a line break or something, MOBI author name link.

Wait until @zwhpressbooks  is back from vacation to discuss?

**Comment by greatislander** [comment]
I've added default styles for PDF and EPUB:

```
text-align: center;
font-size: 0.8em;
font-style: italic;
margin-top: 2em;
```

Also removed the links to webbook in other formats.

**Comment by zwhpressbooks** [comment]
## Testing Notes

[ ] Author name still linked to webbook in both global and section licenses (PDF and ebook)
[ ] License image in MOBI is pretty small (don't know if we can do anything about that)
![screen shot 2017-08-16 at 4 51 23 pm](https://user-images.githubusercontent.com/20113571/29384759-48ba1506-82a3-11e7-96e1-5ca67b7f6383.png)
[ ] Image and text are very close together in EPUB (again, don't know if we can do anything)
![screen shot 2017-08-16 at 4 51 44 pm](https://user-images.githubusercontent.com/20113571/29384852-a055143c-82a3-11e7-9c12-77b2597d79ea.png)

**Comment by greatislander** [comment]
- The author name link should be there in the webbook, I think. At least until we have author profile pages. See: https://creativecommons.org/use-remix/get-permission/
- I will add a bit more spacing to the image for EPUB and try to force it to be a specific size in MOBI

**Comment by greatislander** [comment]
Back to you!

**Comment by zwhpressbooks** [comment]
EPUB spacing is much better, but image is still small in MOBI.

**Comment by greatislander** [comment]
@zwhpressbooks I think MOBI image is fixed now, can you confirm?
