### ISSUE TITLE
Cannot access books with subfolder installation of WordPress 

### ISSUE THREAD

**Issue by followfung** [pressbooks/pressbooks#818]
Does Pressbooks work under a WordPress subfolder installation?

Our WordPress installation is accessed by something like this: https://www.example.com/pressbooks. After creating a new book, a 404 gets thrown when trying to view it. The URL to the book looks like this: https://www.example.com/pressbooks/book.

**Comment by greatislander** [comment]
Hi @followfung, we've never had anyone try to do this (to our knowledge). Pressbooks networks tend to be either:

1. A subdomain install, with root site at `yourpressbooks.network` and books at `book.yourpressbooks.network` etc.
2. A subdirectory install, which (if it needs to be differentiated from the main contents of the domain, can be attached to a subdomain, e.g. root site at `pressbooks.yourdomain.com` and books at `pressbooks.yourdomain.com/book`).

I found a couple articles describing the issue you are encountering with vanilla multisite on Nginx:

http://community.rtcamp.com/t/multisite-in-subfolder/1591
https://easyengine.io/wordpress-nginx/tutorials/multisite/subdirectories/in-a-subdirectory/

Are you using Nginx or Apache? In any case I don't think this is a bug in Pressbooks; sounds like a configuration issue (and in a quick test I tried to set up a multisite install in a subfolder and got a 404, so maybe it takes some extra configuration at the WordPress level). I'd encourage you to open a thread on our [Discourse forum](https://discourse.pressbooks.org/c/devops); perhaps someone there might have run into this.
