### ISSUE TITLE
Templating engine for XHTML/HTML/EPUB outputs

### ISSUE THREAD

**Issue by greatislander** [pressbooks/pressbooks#831]
### Prerequisites

* [x] Can you reproduce the behavior you wish to address with [all other plugins deactivated](http://codex.wordpress.org/Multisite_Network_Administration#Plugins)?
* [x] Are you running the [latest version of Pressbooks](http://github.com/pressbooks/pressbooks/releases/latest/) and the [latest version of WordPress](http://codex.wordpress.org/Upgrading_WordPress)?
* [x] Are you experiencing this issue with one of our built-in root or book themes?
* [x] Did you [perform a cursory search](https://github.com/issues?q=+is%3Aissue+repo%3Apressbooks%2Fpressbooks) to see if your bug or enhancement is already listed?

### Description

Using http://github.com/jenssegers/blade/ we can clean up our export routines according to a more manageable MVC-seperation paradigm. Then things like #830 will be way easier.

### Steps to Reproduce

Not applicable.

### System Information

Pressbooks: 4.0.0-dev
WordPress: 4.8.0
PHP: 7.1

**Comment by connerbw** [comment]
Done for XHTML. Wontfix for Epub201. Moving towards a more unified HTMLBook and Epub3 strategy. These will use Blade.
