### ISSUE TITLE
Document images for export files

### ISSUE THREAD

**Issue by bdolor** [pressbooks/pressbooks#839]
### Prerequisites

* [x] Can you reproduce the behavior you wish to address with [all other plugins deactivated](http://codex.wordpress.org/Multisite_Network_Administration#Plugins)?
* [x] Are you running the [latest version of Pressbooks](http://github.com/pressbooks/pressbooks/releases/latest/) and the [latest version of WordPress](http://codex.wordpress.org/Upgrading_WordPress)?
* [x] Are you experiencing this issue with one of our built-in root or book themes?
* [x] Did you [perform a cursory search](https://github.com/issues?q=+is%3Aissue+repo%3Apressbooks%2Fpressbooks) to see if your bug or enhancement is already listed?

### Description

For users who would like to share export files, the icons `epub3-36.png` and the like are using an incorrect path and do not display.

### Steps to Reproduce

1. Activate any theme, export some files
2. Check radio button at `Share the latest export files`
3. Visit homepage

**Expected behavior:**
Images of file types should display.

**Actual behavior:**
They do not. 

### System Information

Pressbooks: [latest dev branch]
WordPress: [latest]
PHP: [7.0.x]

![image](https://user-images.githubusercontent.com/2048170/27969950-d0d56376-6301-11e7-80c7-0da91ffffccc.png)

![image](https://user-images.githubusercontent.com/2048170/27970048-29ebbe74-6302-11e7-8e69-37391e6a4335.png)

**Comment by connerbw** [comment]
I tested and it's working for me locally.

I think the code was changed here:
https://github.com/pressbooks/pressbooks-book/commit/6b025271dbd2211ae5199cfdf9ea7e9804efc8b0#diff-0d80d0ffc285ef53331643a43bc173e6L703

Maybe `composer update pressbooks/pressbooks-book --with-dependencies` or your preferred method of updating the book theme?

**Comment by greatislander** [comment]
Yes, as per @connerbw’s comment, the paths have been updated in the latest dev version of pressbooks/pressbooks-book.

**Comment by bdolor** [comment]
`composer update pressbooks/pressbooks-book` will only grab v1.8.0 which still has the old paths. Updating the version number of pressbooks-book and releasing it will allow composer to grab the latest changes. That said, it doesn't seem like the best update method for developers like me who need the lastest of the latest.

**Comment by greatislander** [comment]
@bdolor If you require `dev-dev` as the version you will always get the latest commit on the dev branch.

**Comment by bdolor** [comment]
roger that. thank you. 

![image](https://user-images.githubusercontent.com/2048170/27975892-0bceffa2-6319-11e7-8517-61b28fb48606.png)
