### ISSUE TITLE
View link in organize page

### ISSUE THREAD

**Issue by greatislander** [pressbooks/pressbooks#840]
### Prerequisites

* [x] Can you reproduce the behavior you wish to address with [all other plugins deactivated](http://codex.wordpress.org/Multisite_Network_Administration#Plugins)?
* [x] Are you running the [latest version of Pressbooks](http://github.com/pressbooks/pressbooks/releases/latest/) and the [latest version of WordPress](http://codex.wordpress.org/Upgrading_WordPress)?
* [x] Are you experiencing this issue with one of our built-in root or book themes?
* [x] Did you [perform a cursory search](https://github.com/issues?q=+is%3Aissue+repo%3Apressbooks%2Fpressbooks) to see if your bug or enhancement is already listed?

### Description

As per @colomet's Discourse post, it would make sense to have a link to view each part, chapter, front matter, and back matter from the **Organize** page.

### Steps to Reproduce

Not applicable.

### System Information

Pressbooks: 4.0.0-dev
WordPress: 4.8.0
PHP: 7.1

**Comment by greatislander** [comment]
Should look like this:

![view link](https://user-images.githubusercontent.com/605361/29488919-14d04fc2-84eb-11e7-8277-70ad779b50d5.jpg)

**Comment by colomet** [comment]
The people have acces to the edit mode by opening the title, the people will not use to go the edit buttom for opening the page. As is going to be used few times as view, and in order to put delete buttom as save as posible. Maybe if the order is:

View | Edit | Delete 

the changes of choose the delete option by mistake are much lower.

Just and idea. but cool anyway.

**Comment by greatislander** [comment]
Actually thinking we should remove the edit column and follow the WordPress convention a bit more, changing the first column to something like (without Quick Edit):

![screen shot 2017-08-20 at 9 15 54 pm](https://user-images.githubusercontent.com/605361/29499652-f02f101a-85ec-11e7-96c3-81c98bc25b00.png)

**Comment by colomet** [comment]
Well, in the current form with +1 column, we have a larger width, in wordpress form we have a bigger scroll.

Maybe is a good momment to change the witdh of the colums and to give a litle more of space to the column of the titles.
![captura de pantalla 2017-08-21 a las 8 52 40](https://user-images.githubusercontent.com/3929177/29506922-33ada0c0-864e-11e7-8e52-ca5e744dc0af.png)

**Comment by zwhpressbooks** [comment]
All in working order!
