### ISSUE TITLE
Cloning internal books

### ISSUE THREAD

**Issue by greatislander** [pressbooks/pressbooks#841]
### Prerequisites

* [x] Can you reproduce the behavior you wish to address with [all other plugins deactivated](http://codex.wordpress.org/Multisite_Network_Administration#Plugins)?
* [x] Are you running the [latest version of Pressbooks](http://github.com/pressbooks/pressbooks/releases/latest/) and the [latest version of WordPress](http://codex.wordpress.org/Upgrading_WordPress)?
* [x] Are you experiencing this issue with one of our built-in root or book themes?
* [x] Did you [perform a cursory search](https://github.com/issues?q=+is%3Aissue+repo%3Apressbooks%2Fpressbooks) to see if your bug or enhancement is already listed?

### Description

Books should be cloneable via the v2 REST API within a network (given appropriate permissions).

### Steps to Reproduce

Not applicable.

### System Information

Pressbooks: 4.0.0-RC1
WordPress: 4.8.0
PHP: 7.1

**Comment by greatislander** [comment]
- [ ] Verify book/section license, prohibit cloning for `all-rights-reserved` and [`by-nd`](https://creativecommons.org/licenses/by-nd/2.0/).
- [ ] Assign `pb_is_based_on` metadata key to URL of source book.

**Comment by connerbw** [comment]
TODO: 
+ If you are admin, and in the Network or Root Site dashboard, clicking, clone a book shows"Forbidden"
+ Add animated progress bar while waiting.
+ Fix animated progress bar in Safari. (Apparently some Safari users haven't seen this bar in a while?) 
+ Add option to turn off Cloning like we do the Root API.

**Comment by zwhpressbooks** [comment]
##Testing Notes

1. URL with numbers is not great - are we working towards the user being able to enter their own?
2. 500 error on big book
3. “Cloning failed” error when I tried: https://fourpointoh.textopress.com, can’t see why

**Comment by greatislander** [comment]
@zwhpressbooks @pressbooksapurva Added a field to choose the URL of the new book, please test and then we are good to go.

**Comment by zwhpressbooks** [comment]
Looks like the cloning process is overwriting an existing URL when I try it. Works great otherwise, though!

**Comment by greatislander** [comment]
@zwhpressbooks Can you clarify? You enter the URL of a book that already exists and it lets you clone on top of it? :/

**Comment by zwhpressbooks** [comment]
Yep, it overrode it completely.

**Comment by greatislander** [comment]
Figured it out. Was testing against a malformed URL because the `$domain` global was the url of the current book, not the root site. https://github.com/pressbooks/pressbooks/commit/e889f12f1dca831dbcfbac3f155050add715f125

**Comment by greatislander** [comment]
Ready for you to test again @zwhpressbooks
