### ISSUE TITLE
Word count

### ISSUE THREAD

**Issue by greatislander** [pressbooks/pressbooks#842]
### Prerequisites

* [x] Can you reproduce the behavior you wish to address with [all other plugins deactivated](http://codex.wordpress.org/Multisite_Network_Administration#Plugins)?
* [x] Are you running the [latest version of Pressbooks](http://github.com/pressbooks/pressbooks/releases/latest/) and the [latest version of WordPress](http://codex.wordpress.org/Upgrading_WordPress)?
* [x] Are you experiencing this issue with one of our built-in root or book themes?
* [x] Did you [perform a cursory search](https://github.com/issues?q=+is%3Aissue+repo%3Apressbooks%2Fpressbooks) to see if your bug or enhancement is already listed?

### Description

There should be a way to get a book's word count. Where and how one does this TBD, but we can start with the implementation of actually counting the words.

### Steps to Reproduce

Not applicable.

### System Information

Pressbooks: 4.0.0-RC1
WordPress: 4.8.0
PHP: 7.1

**Comment by zwhpressbooks** [comment]
Proposed interface handling:
1. Display at end of chapter: “Word Count: 250 (chapter) / 1,250 (total)” (Using existing WP chapter counter - is this possible?)
2. Organize Page, top right next to ‘Global Privacy’ box (see below)
    a. Total word count
    b. Total of chapters selected for export

![screen shot 2017-07-12 at 4 36 57 pm](https://user-images.githubusercontent.com/20113571/28138967-92468766-6720-11e7-9e7f-af4440a0870d.png)

**Comment by greatislander** [comment]
@zwhpressbooks Looks great!

**Comment by hughmcguire** [comment]
@greatislander all ok now, OK for priority list.

**Comment by connerbw** [comment]
>  (Using existing WP chapter counter - is this possible?)

Not possible for now.

**Comment by connerbw** [comment]
@greatislander Can you help me?

![how-do-i](https://user-images.githubusercontent.com/812192/28794521-9802c852-7604-11e7-8d04-c0a43ce0c530.png)

Branch: https://github.com/pressbooks/pressbooks/tree/wordcount

**Comment by connerbw** [comment]
-- 1.

On a book with a lot of words it starts off like this:
> Word Count: 743848 (whole book) / 729728 (selected for export) (edited)

Then when I click an export checkmark:
> Word Count: 743848 (whole book) / 729,701 (selected for export)

Notice the comma.

-- 2.

With large word counts, when I start it does add/subtract from the current count so the animation looks sharp, but if I click 3 or 4 times. It starts doing the animation from zero so it's a bit weird. 

Probably related to the comma. 

-- 3. 

If you click the export  \<TH\>, ajax calls occur as many times as there are rows, but because JS async there's no guarantee it's in order so the count can be off. 

Maybe not worth the extra effort.

**Comment by greatislander** [comment]
@connerbw made some improvements in #880.

**Comment by zwhpressbooks** [comment]
Good to go from my end
