### ISSUE TITLE
path to USWebCoatedSWOP.icc seems to be hard coded instead of being relative to PB_PRINCE_COMMAND

### ISSUE THREAD

**Issue by thomasdumm** [pressbooks/pressbooks#843]
### Prerequisites

* [x ] Can you reproduce the behavior you wish to address with [all other plugins deactivated](http://codex.wordpress.org/Multisite_Network_Administration#Plugins)?
* [x] Are you running the [latest version of Pressbooks](http://github.com/pressbooks/pressbooks/releases/latest/) and the [latest version of WordPress](http://codex.wordpress.org/Upgrading_WordPress)?
* [x] Are you experiencing this issue with one of our built-in root or book themes?
* [x] Did you [perform a cursory search](https://github.com/issues?q=+is%3Aissue+repo%3Apressbooks%2Fpressbooks) to see if your bug or enhancement is already listed?

### Description

path to USWebCoatedSWOP.icc seems to be hard coded in

pressbooks/inc/modules/export/prince/class-printpdf.php 

protected function getPdfOutputIntent() {
		return '/usr/lib/prince/icc/USWebCoatedSWOP.icc';
	}

instead of relative path to PB_PRINCE_COMMAND 
the hard coding can lead to a corresponsing file not found error message in the php error log

#### Book Info

Book ID: 2
Book URL: http://localhost/wordpress/test/
Book Privacy: Public

#### Browser

Platform: OS X
Browser Name: Firefox
Browser Version: 54.0
User Agent String: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:54.0) Gecko/20100101 Firefox/54.0

#### WordPress Configuration

Network URL: http://localhost/wordpress/
Network Type: Subdirectory
Version: 4.8
Language: en_US
WP_ENV: Not set
WP_DEBUG: Disabled
Memory Limit: 64M

#### Pressbooks Configuration

Version: 4.0.0
Book Theme: Clarke
Book Theme Version: 2.0.1
Root Theme: twentyseventeen
Root Theme Version: 

#### Pressbooks Dependencies

Epubcheck: Installed
Kindlegen: Installed
xmllint: Installed
PrinceXML: Installed
Saxon-HE: Installed

#### Must-Use Plugins

hm-autoloader.php: n/a

#### Network Active Plugins

Pressbooks: 4.0.0-RC1

#### Server Configuration

PHP Version: 7.0.15
MySQL Version: 5.6.35
Webserver Info: Apache/2.2.31 (Unix) mod_wsgi/3.5 Python/2.7.13 PHP/7.0.15 mod_ssl/2.2.31 OpenSSL/1.0.2j DAV/2 mod_fastcgi/2.4.6 mod_perl/2.0.9 Perl/v5.24.0

#### PHP Configuration

Safe Mode: Disabled
Memory Limit: 256M
Upload Max Size: 32M
Post Max Size: 32M
Upload Max Filesize: 32M
Time Limit: 30
Max Input Vars: 1000
URL-aware fopen: On (1)
Display Errors: N/A

#### PHP Extensions

cURL: Supported
cURL Version: 7.52.1
imagick: Not Installed
xsl: Installed

**Comment by greatislander** [comment]
@thomasdumm Well-spotted, but `PB_PRINCE_PATH` is the path to the executable (e.g. `/usr/bin/prince`), while the accompanying files are in `/usr/lib/prince`. We might be able to extrapolate assuming that the base of both paths (in this example, `/usr/`) is the same. I'll push a branch which tests this and you can see if the issue is resolved for you.

**Comment by greatislander** [comment]
@thomasdumm Please test: https://github.com/pressbooks/pressbooks/tree/intent-path

**Comment by thomasdumm** [comment]
I tested and find this:
CURRENT: /usr/local/lib/prince/bin/princeicc/USWebCoatedSWOP.icc
CORRECT: /usr/local/lib/prince/icc/USWebCoatedSWOP.icc

**Comment by greatislander** [comment]
@thomasdumm Just pushed a change that we think will work better.

**Comment by thomasdumm** [comment]
@greatislander :  this works for me.
