### ISSUE TITLE
Delete book feature

### ISSUE THREAD

**Issue by greatislander** [pressbooks/pressbooks#845]
### Prerequisites

* [x] Can you reproduce the behavior you wish to address with [all other plugins deactivated](http://codex.wordpress.org/Multisite_Network_Administration#Plugins)?
* [x] Are you running the [latest version of Pressbooks](http://github.com/pressbooks/pressbooks/releases/latest/) and the [latest version of WordPress](http://codex.wordpress.org/Upgrading_WordPress)?
* [x] Are you experiencing this issue with one of our built-in root or book themes?
* [x] Did you [perform a cursory search](https://github.com/issues?q=+is%3Aissue+repo%3Apressbooks%2Fpressbooks) to see if your bug or enhancement is already listed?

### Description

Administrators of a book should be able to delete it.

To discuss: books should be set to `deleted` status for 30 days in case of regrets, then automatically deleted (via WP cron?).

### Steps to Reproduce

1. Click **Book Title** &rarr; **Delete Book**:

![screen shot 2017-07-12 at 11 27 33 am](https://user-images.githubusercontent.com/605361/28122672-3dde5008-66f5-11e7-8fb4-c881f1b05d79.png)

2. Enter the title of the book on the interstitial page, then click to confirm deletion.

**Expected behavior:** Book status is changed to `deleted`. After 30 days, book tables are dropped from the database and book uploads directory is erased.

### System Information

Pressbooks: 4.0
WordPress 4.8
PHP 7.1

**Comment by zwhpressbooks** [comment]
Have discussed the 30 day window and agree that it's the best way to handle potential regrets.

The problem of books with multiple admins also came up, and we would propose that in an instance where someone tries to delete a book with multiple admins, they receive an error message directing them to contact support@pressbooks.com for pb.com or their network manager on other networks so this can be handled manually. Thoughts?

**Comment by greatislander** [comment]
Makes sense to me.

**Comment by hughmcguire** [comment]
this is OK to go @greatislander .... over to priority list.

**Comment by connerbw** [comment]
It turns out we disabled an existing WP feature.

Instead of re-inventing the wheel, let's tweak [ms-delete-site.php](https://github.com/WordPress/wordpress-develop/blob/master/src/wp-admin/ms-delete-site.php)

**Comment by pressbooksapurva** [comment]
Tested, and good to go!
