### ISSUE TITLE
ODT export fails when DOMDocument::loadXML encounters errors

### ISSUE THREAD

**Issue by greatislander** [pressbooks/pressbooks#847]
### Prerequisites

* [x] Can you reproduce the behavior you wish to address with [all other plugins deactivated](http://codex.wordpress.org/Multisite_Network_Administration#Plugins)?
* [x] Are you running the [latest version of Pressbooks](http://github.com/pressbooks/pressbooks/releases/latest/) and the [latest version of WordPress](http://codex.wordpress.org/Upgrading_WordPress)?
* [x] Are you experiencing this issue with one of our built-in root or book themes?
* [x] Did you [perform a cursory search](https://github.com/issues?q=+is%3Aissue+repo%3Apressbooks%2Fpressbooks) to see if your bug or enhancement is already listed?

### Description

If there is an parsing error while importing book XHTML on [this line](https://github.com/pressbooks/pressbooks/blob/dev/inc/modules/export/odt/class-odt.php#L113), the rest of the conversion fails horribly.

We need to handle these kinds of errors more gracefully (see other uses of `libxml_use_internal_errors()` throughout Pressbooks) and we need to break the conversion function into modules similarly to the EPUB exporter so that failures can be isolated and made testable.

### Steps to Reproduce

1. Create a book with a character that `DOMDocument::loadXML()` doesn't like.
2. Attempt to export.

**Expected behavior:** The export fails, leaving some random files strewn throughout the exports folder.

**Actual behavior:** The export fails cleanly and provides the user with a helpful error message instructing them to fix their book content OR, even better, cleans up along the way.

### System Information

Pressbooks: 4.0.0
WordPress: 4.8
PHP: 7.1

**Comment by greatislander** [comment]
@connerbw This is fixed in #867, yes? (Or at least: greatly improved?)

**Comment by connerbw** [comment]
@greatislander Yes. Improved. Should not crash like this anymore.
