### ISSUE TITLE
Add support for Punjabi (Gurmukhi script) font

### ISSUE THREAD

**Issue by hughmcguire** [pressbooks/pressbooks#858]
### Prerequisites

_Check the boxes below by changing them from `[ ]` to `[x]`._

* [x] Can you reproduce the behavior you wish to address with [all other plugins deactivated](http://codex.wordpress.org/Multisite_Network_Administration#Plugins)?
* [x] Are you running the [latest version of Pressbooks](http://github.com/pressbooks/pressbooks/releases/latest/) and the [latest version of WordPress](http://codex.wordpress.org/Upgrading_WordPress)?
* [x] Are you experiencing this issue with one of our built-in root or book themes?
* [x] Did you [perform a cursory search](https://github.com/issues?q=+is%3Aissue+repo%3Apressbooks%2Fpressbooks) to see if your bug or enhancement is already listed?

### Description

Request for support for Pubjabi font (Gurmukhi script), which is a Noto font: 
https://www.google.com/get/noto/#sans-guru

@greatislander would you prefer font requests go to Pressbooks-book or Pressbooks repo?

**Comment by greatislander** [comment]
I was going to say Pressbooks Book but I changed my mind.

**Comment by alexpflores** [comment]
@greatislander completed via: https://github.com/pressbooks/pressbooks-book/pull/27 and https://github.com/pressbooks/pressbooks/pull/877

**Comment by pressbooksapurva** [comment]
Tested, and works as expected in webbook and export formats!
