### ISSUE TITLE
Editors should be able to manage theme options and edit custom CSS

### ISSUE THREAD

**Issue by greatislander** [pressbooks/pressbooks#862]
### Prerequisites

* [x] Can you reproduce the behavior you wish to address with [all other plugins deactivated](http://codex.wordpress.org/Multisite_Network_Administration#Plugins)?
* [x] Are you running the [latest version of Pressbooks](http://github.com/pressbooks/pressbooks/releases/latest/) and the [latest version of WordPress](http://codex.wordpress.org/Upgrading_WordPress)?
* [x] Are you experiencing this issue with one of our built-in root or book themes?
* [x] Did you [perform a cursory search](https://github.com/issues?q=+is%3Aissue+repo%3Apressbooks%2Fpressbooks) to see if your bug or enhancement is already listed?

### Description

Currently, only users with admin privileges can manage theme options and edit custom CSS on a book. These permissions should be extended to editors.

### Steps to Reproduce

Not applicable.

### System Information

Pressbooks: 4.0.1
WordPress: 4.8
PHP: 7.1

**Comment by pressbooksapurva** [comment]
Can view and change theme options, don't have access to custom CSS as an editor.

**Comment by greatislander** [comment]
@pressbooksapurva The Custom CSS theme has to be activated by the book admin (editors shouldn't be able to change the theme), but once that's done you should have no problem editing the CSS. Can you confirm?

**Comment by pressbooksapurva** [comment]
Yes, once custom CSS has been activated by admin, I can as an editor edit the CSS. :)
