### ISSUE TITLE
Import from DOCX file "__UNKNOWN__" as the title and no H1 headings recognized as chapters.

### ISSUE THREAD

**Issue by fishfree** [pressbooks/pressbooks#868]
Or anybody can give me some docx files which can be imported as expected?

**Comment by greatislander** [comment]
Hi, please don't delete all the contents of the issue template when opening issues. This is better discussed in our forum where you can compare notes with other users as to how to prepare your DOCX files for import: https://discourse.pressbooks.org.

Also, see: https://guide.pressbooks.com/chapter/import-from-word-docx/

**Comment by fishfree** [comment]
Sorry for forgetting to give the versions info:
My pressbooks is the latest dev branch. PHP: 5.6.
I also had followed the tutorial before I submitted this issue, but no luck.
Now I think the information is enough, so could you reopen this issue, please?

**Comment by greatislander** [comment]
Can you provide a sample document so we can reproduce this?

**Comment by greatislander** [comment]
@fishfree Since we haven't heard from you since July I'm going to assume that you have resolved this or are no longer in need of a fix. We cannot reproduce internally.
