### ISSUE TITLE
Enable search & replace regex for super admins

### ISSUE THREAD

**Issue by connerbw** [pressbooks/pressbooks#870]
### Prerequisites

_Check the boxes below by changing them from `[ ]` to `[x]`._

* [X] Can you reproduce the behavior you wish to address with [all other plugins deactivated](http://codex.wordpress.org/Multisite_Network_Administration#Plugins)?
* [X] Are you running the [latest version of Pressbooks](http://github.com/pressbooks/pressbooks/releases/latest/) and the [latest version of WordPress](http://codex.wordpress.org/Upgrading_WordPress)?
* [X] Are you experiencing this issue with one of our built-in root or book themes?
* [X] Did you [perform a cursory search](https://github.com/issues?q=+is%3Aissue+repo%3Apressbooks%2Fpressbooks) to see if your bug or enhancement is already listed?

### Description

Pressbooks has a constant that enables search & replace regular expressions (`PB_ENABLE_REGEX_SEARCHREPLACE`) Setting this constant to true enables the feature for all users accross a network. Disabled, no one can use this feature.

Feature request: Always enable for Super Admins regardless of the value of `PB_ENABLE_REGEX_SEARCHREPLACE`.

### System Information

Pressbooks: 4.0.2
WordPress: 4.8
PHP: 5.6 / 7.1

**Comment by zwhpressbooks** [comment]
Just tested this and I'm seeing this when I hit any of the buttons:

![screen shot 2017-08-01 at 3 42 19 pm](https://user-images.githubusercontent.com/20113571/28843683-1300365e-76d0-11e7-9bf4-8356a3068d50.png)

**Comment by connerbw** [comment]
@zwhpressbooks 

Works for me?


![works-for-me](https://user-images.githubusercontent.com/812192/28845195-3235c304-76d5-11e7-8d4f-616ba5146164.png)

**Comment by greatislander** [comment]
Also works for me… What search pattern are you using, @zwhpressbooks?

**Comment by zwhpressbooks** [comment]
Ah, that's what I get for trusting the internet - I grabbed something without checking if it was correct. My expression was at fault, although interesting to note that that's the result of inputting a bad expression. Don't mind me!

**Comment by connerbw** [comment]
@zwhpressbooks Can you paste the expression please? A bad expression should show an error.

**Comment by zwhpressbooks** [comment]
/[0-9a-f]*/ (in theory, trying to match hex colours)

**Comment by connerbw** [comment]
I tested the regex and got:

> ( ! ) Fatal error: Allowed memory size of 268435456 bytes exhausted (tried to allocate 4096 bytes) in /srv/www/example.com/current/web/app/plugins/pressbooks/inc/modules/searchandreplace/class-search.php on line 186

This error is not shown in production, instead it's a blank screen. I'll see if I can somehow catch this.
