### ISSUE TITLE
Fatal Error

### ISSUE THREAD

**Issue by Quixzap** [pressbooks/pressbooks#890]
Hello

Have used Pressbooks before and all OK. Get this on fresh install:

Fatal error: Call to undefined function HM\Autoloader\register_class_path() in /home/admin/web/sitename.com/public_html/wp-content/plugins/pressbooks/pressbooks.php on line 77

Thank you

**Comment by connerbw** [comment]
"Copy Pressbooks’ autoloader file from /path/to/your/site/wp-content/plugins/pressbooks/hm-autoloader.php to /path/to/your/site/wp-content/mu-plugins/hm-autoloader.php. You may need to create the wp-content/mu-plugins/ directory if it doesn’t yet exist."

Source:
https://docs.pressbooks.org/installation/
