### ISSUE TITLE
Substitute full-size images in print PDF exports

### ISSUE THREAD

**Issue by greatislander** [pressbooks/pressbooks#894]
### Prerequisites

* [x] Can you reproduce the behavior you wish to address with [all other plugins deactivated](http://codex.wordpress.org/Multisite_Network_Administration#Plugins)?
* [x] Are you running the [latest version of Pressbooks](http://github.com/pressbooks/pressbooks/releases/latest/) and the [latest version of WordPress](http://codex.wordpress.org/Upgrading_WordPress)?
* [x] Are you experiencing this issue with one of our built-in root or book themes?
* [x] Did you [perform a cursory search](https://github.com/issues?q=+is%3Aissue+repo%3Apressbooks%2Fpressbooks) to see if your bug or enhancement is already listed?

### Description

Print PDF requires high-resolution (~300dpi) images. However, if a user has inserted an image at a smaller size (e.g. "large", "medium" etc.) they will end up with a downsampled image in their book. Ideally the full-size image should be substituted, and sizing can be determined from the width & height attributes of the `<img>` tag.

Methods for accomplishing this:

- Find the original image URL via the API (`/wp/v2/media`) or a database query; replace the `src` attribute with this URL;
- Find the largest image URL in the `srcset` attribute, replace the `src` attribute with this URL;
- Try to guess the original image URL from the `src` attribute (if the src is https://pressbooks.com/wp-content/uploads/sites/1/2017/01/image-500x500.png then test if https://pressbooks.com/wp-content/uploads/sites/1/2017/01/image.png exists); replace the `src` attribute with this URL;
- When trying to find the best version of a resized image, use [Imagehash](https://github.com/jenssegers/imagehash) to check if it's the closest match (thumbnails, for example, are not use different cropping).

### Steps to Reproduce

1. Insert an image, choosing "large" size or smaller.
2. Export Print PDF.

**Expected behavior:** Image in export is 300dpi.

**Actual behavior:** Image in export is 72dpi or something.

### System Information

Pressbooks: 4.2-dev
WordPress: 4.8.1
PHP: 7.1

**Comment by pressbooksapurva** [comment]
Works as expected! Print PDF confirms that images inserted at smaller sizes (medium, custom) are 300dpi or higher, and that pixel dimensions are the same as the original image (largest dimensions available).
