### ISSUE TITLE
Import/clone full-size images

### ISSUE THREAD

**Issue by greatislander** [pressbooks/pressbooks#895]
### Prerequisites

* [x] Can you reproduce the behavior you wish to address with [all other plugins deactivated](http://codex.wordpress.org/Multisite_Network_Administration#Plugins)?
* [x] Are you running the [latest version of Pressbooks](http://github.com/pressbooks/pressbooks/releases/latest/) and the [latest version of WordPress](http://codex.wordpress.org/Upgrading_WordPress)?
* [x] Are you experiencing this issue with one of our built-in root or book themes?
* [x] Did you [perform a cursory search](https://github.com/issues?q=+is%3Aissue+repo%3Apressbooks%2Fpressbooks) to see if your bug or enhancement is already listed?

### Description

Both the WXR import module and the cloner pull in downsampled images (they look at HTML and fetch whatever is set in an `<img>` `src` attribute.

Ideas for improvement:

- Use the media endpoint (`wp/v2/media`). Fetch all images, then work backwards into posts, updating `src` attributes where possible.
- Use the image `srcset` attribute to determine the largest image; fetch that instead of the downsampled version, then update the `src` to the local image.
- Try to guess the original image URL from the `src` attribute (if the `src` is https://pressbooks.com/wp-content/uploads/sites/1/2017/01/image-500x500.png then test if https://pressbooks.com/wp-content/uploads/sites/1/2017/01/image.png exists); fetch this image, then update the `src` to the local image.
- When trying to find the best version of a resized image, use [Imagehash](https://github.com/jenssegers/imagehash) to check if it's the closest match (thumbnails, for example, are not use different cropping).

### Steps to Reproduce

1. Clone a book or import a WXR file.
2. Compare source and target images.

**Expected behavior:** The "original" sizes of the images are the same.

**Actual behavior:** The cloned/imported images are downsampled.

### System Information

Pressbooks: 4.1
WordPress: 4.8.1
PHP: 7.1

**Comment by greatislander** [comment]
See comment on PR.

**Comment by zwhpressbooks** [comment]
Image src now correctly appended with pixels and appear as expected in webbook & exports.

One outstanding issue: When I click on any image to open the editor, I don't see the usual 'Size' dropdown under 'Display Settings'.

**Comment by greatislander** [comment]
@zwhpressbooks Can you send me a link?
