### ISSUE TITLE
Clone it! Fatal Error: Maximum execution time

### ISSUE THREAD

**Issue by bdolor** [pressbooks/pressbooks#903]
### Prerequisites

_Check the boxes below by changing them from `[ ]` to `[x]`._

* [ ] Can you reproduce the behavior you wish to address with [all other plugins deactivated](http://codex.wordpress.org/Multisite_Network_Administration#Plugins)?
* [x] Are you running the [latest version of Pressbooks](http://github.com/pressbooks/pressbooks/releases/latest/) and the [latest version of WordPress](http://codex.wordpress.org/Upgrading_WordPress)?
* [ ] Are you experiencing this issue with one of our built-in root or book themes?
* [x] Did you [perform a cursory search](https://github.com/issues?q=+is%3Aissue+repo%3Apressbooks%2Fpressbooks) to see if your bug or enhancement is already listed?

### Description

Clone feature makes it through cloning most of a book but dies with a 500 error. 

### Steps to Reproduce

1. clone Mike Caufields CC-BY book 'webliteracy' at https://webliteracy.pressbooks.com/ from outside the pressbooks.com domain.
2. tail -f wp-content/debug.log file during import
3. watch for PHP Fatal error:  Maximum execution time of 30 seconds exceeded in /var/www/html/ssl/pressbooks/wp-includes/class-wp-image-editor-gd.php on line 190 - either [imagecopyresampled](http://php.net/manual/en/function.imagecopyresampled.php) or [wp_imagecreatetruecolor](https://wpseek.com/function/wp_imagecreatetruecolor/)
4. browser returns a 500 error.
5. Half of the book is created, the last page to import is https://webliteracy.pressbooks.com/chapter/finding-a-journals-impact-factor/ 

The next page, which doesn't import is https://webliteracy.pressbooks.com/chapter/using-google-scholar-to-check-author-expertise/ 

![image](https://user-images.githubusercontent.com/2048170/29723340-11a4d2d6-8979-11e7-91a5-a768fae712b0.png)

**Expected behavior:** 
Whole book should be cloned. No Fatal Error. 

**Actual behavior:** 
Fatal Error. 

![image](https://user-images.githubusercontent.com/2048170/29723381-43753c6a-8979-11e7-801b-d07351f94798.png)

### System Information

Pressbooks: tested on both 4.1.0 and latest dev branch
WordPress: 4.8.1
PHP: same behaviour with both 5.6 and 7.1

**Comment by greatislander** [comment]
You will likely need to increase your maximum execution time. We found that this was necessary for some books with lots of media/large media to import. I’d suggest bumping it up to 60 seconds and see where you get.

**Comment by greatislander** [comment]
(Ideally we should catch this error, exit the clone and delete the partial book, informing the user that they may need to make a configuration change. CC: @connerbw.)

**Comment by bdolor** [comment]
60 seconds max_execution_time works. Thank you also for considering a graceful degradation path.

**Comment by connerbw** [comment]
> (Ideally we should catch this error, exit the clone and delete the partial book, informing the user that they may need to make a configuration change. CC: @connerbw.)

PHP Fatals are not really catchable. They imply that PHP died and that the operator should do something about it. For example, if PHP runs out of memory, then it will give a Fatal error, and since there's no more memory to do anything else, it's unlikely we can continue.

There is a discussion, with different points of view, on how to deal with (some) fatals: https://stackoverflow.com/questions/277224/how-do-i-catch-a-php-fatal-error

Maybe a quick fix is like [how we do in Exports](https://github.com/pressbooks/pressbooks/blob/dev/inc/modules/export/class-export.php#L636)?

`set_time_limit( 300 );`

This won't work with our Nginx infra, but for typical use cases it will probably extend the limit. 

I'll add it now.
