### ISSUE TITLE
PB Latex settings should only appear in books, not root site

### ISSUE THREAD

**Issue by greatislander** [pressbooks/pressbooks#910]
### Prerequisites

* [x] Can you reproduce the behavior you wish to address with [all other plugins deactivated](http://codex.wordpress.org/Multisite_Network_Administration#Plugins)?
* [x] Are you running the [latest version of Pressbooks](http://github.com/pressbooks/pressbooks/releases/latest/) and the [latest version of WordPress](http://codex.wordpress.org/Upgrading_WordPress)?
* [x] Are you experiencing this issue with one of our built-in root or book themes?
* [x] Did you [perform a cursory search](https://github.com/issues?q=+is%3Aissue+repo%3Apressbooks%2Fpressbooks) to see if your bug or enhancement is already listed?

### Description

`/symbionts/pb-latex/` should only register its admin settings page if we are on the dashboard of a book.

### Steps to Reproduce

1. Activate a generic theme (e.g. Twenty Seventeen) for your root site. 
2. Visit the dashboard.

**Expected behavior:** Only standard settings pages are visible in the settings menu.

**Actual behavior:** PB Latex appears in the settings menu.

### System Information

Pressbooks: 4.1
WordPress: 4.8.1
PHP: 7.1

**Comment by zwhpressbooks** [comment]
A-ok so far as I can see!
