### ISSUE TITLE
Gutenberg compatibility

### ISSUE THREAD

**Issue by greatislander** [pressbooks/pressbooks#924]
### Prerequisites

* [x] Can you reproduce the behavior you wish to address with [all other plugins deactivated](http://codex.wordpress.org/Multisite_Network_Administration#Plugins)?
* [x] Are you running the [latest version of Pressbooks](http://github.com/pressbooks/pressbooks/releases/latest/) and the [latest version of WordPress](http://codex.wordpress.org/Upgrading_WordPress)?
* [x] Are you experiencing this issue with one of our built-in root or book themes?
* [x] Did you [perform a cursory search](https://github.com/issues?q=+is%3Aissue+repo%3Apressbooks%2Fpressbooks) to see if your bug or enhancement is already listed?

### Description

We need to assess the [Gutenberg](https://github.com/WordPress/Gutenberg) editor's compatibility with Pressbooks. There are likely many features we need to disable and it has probably broken some things. 

### Steps to Reproduce

Not applicable.

### System Information

Pressbooks: master
Gutenberg: master
WordPress: 4.8.1
PHP: 7.1

**Comment by connerbw** [comment]
Light reading: 

 + https://github.com/WordPress/gutenberg/issues/952
 + https://github.com/WordPress/gutenberg/issues/1419

Fun stuff:

 + https://automattic.github.io/wp-post-grammar/explorer/

**Comment by greatislander** [comment]
More light reading:

https://premium.wpmudev.org/blog/gutenberg-editor-wordpress/

> When trying to paste text from Word into the new editor, all formatting is lost.

**Comment by greatislander** [comment]
See:

https://github.com/WordPress/gutenberg/issues/3462

**Comment by greatislander** [comment]
Closing; will create a project for this when the time comes.
