### ISSUE TITLE
User catalog page is inaccessible on some networks

### ISSUE THREAD

**Issue by greatislander** [pressbooks/pressbooks#939]
### Prerequisites

* [x] Can you reproduce the behavior you wish to address with [all other plugins deactivated](http://codex.wordpress.org/Multisite_Network_Administration#Plugins)?
* [x] Are you running the [latest version of Pressbooks](http://github.com/pressbooks/pressbooks/releases/latest/) and the [latest version of WordPress](http://codex.wordpress.org/Upgrading_WordPress)?
* [x] Are you experiencing this issue with one of our built-in root or book themes?
* [x] Did you [perform a cursory search](https://github.com/issues?q=+is%3Aissue+repo%3Apressbooks%2Fpressbooks) to see if your bug or enhancement is already listed?

### Description

On some networks the user catalog page is not accessible. Related to #905.

### Steps to Reproduce

1. Visit `http://pressbooks.dev/catalog/<username>`

**Expected behavior:** User catalog is displayed.

**Actual behavior:** Page not found.

### System Information

Pressbooks: 4.3-dev
WordPress: 4.8.1
PHP: 7.1

**Comment by emasters** [comment]
I took a look at #905 and used line 182 of `inc/redirect/namespace.php` as a hint to create this URL:  
`http://lawbooks.cali.org/index.php?pagename=pb_catalog&pb_catalog_user=emasters`
That URL opens the users public catalog. The rewrite it is supposed to be doing doesn't work though.

**Comment by connerbw** [comment]
@emasters 

In `wp_options` there will be an option named `rewrite_rules` with serialized data.

If you copy/pasted it into: http://www.unserialize.com

Do you see:  ` [^oauth/(.*)] => index.php?signup=true&pb_oauth_provider=$matches[1]`

**Comment by greatislander** [comment]
Fixed in https://github.com/pressbooks/pressbooks/commit/c4b7e7bdb96b21fa5e91448268cdcdd3ba839d55
