### ISSUE TITLE
Enable search in Custom Styles editor

### ISSUE THREAD

**Issue by greatislander** [pressbooks/pressbooks#940]
### Prerequisites

* [x] Can you reproduce the behavior you wish to address with [all other plugins deactivated](http://codex.wordpress.org/Multisite_Network_Administration#Plugins)?
* [x] Are you running the [latest version of Pressbooks](http://github.com/pressbooks/pressbooks/releases/latest/) and the [latest version of WordPress](http://codex.wordpress.org/Upgrading_WordPress)?
* [x] Are you experiencing this issue with one of our built-in root or book themes?
* [x] Did you [perform a cursory search](https://github.com/issues?q=+is%3Aissue+repo%3Apressbooks%2Fpressbooks) to see if your bug or enhancement is already listed?

### Description

See:
https://github.com/WordPress/better-code-editing/issues/75
https://github.com/WordPress/better-code-editing/pull/76

### Steps to Reproduce

Not applicable.

### System Information

Pressbooks: 4.3-dev
WordPress: 4.8.1
PHP: 7.1

**Comment by connerbw** [comment]
The built-in browser search can be used if we increase `viewportMargin` 

We can set that property to `Infinity` but I'm going to arbitrarily select the number 5000 in the hopes it helps performance. Our transpiled CSS files are never bigger than ~3000 lines

Let's try that first, use the search plugin when it comes with WP core?

@see https://github.com/codemirror/CodeMirror/issues/4491
