### ISSUE TITLE
Custom styles: recompile theme styles when changing options/adding language support

### ISSUE THREAD

**Issue by greatislander** [pressbooks/pressbooks#943]
### Prerequisites

* [x] Can you reproduce the behavior you wish to address with [all other plugins deactivated](http://codex.wordpress.org/Multisite_Network_Administration#Plugins)?
* [x] Are you running the [latest version of Pressbooks](http://github.com/pressbooks/pressbooks/releases/latest/) and the [latest version of WordPress](http://codex.wordpress.org/Upgrading_WordPress)?
* [x] Are you experiencing this issue with one of our built-in root or book themes?
* [x] Did you [perform a cursory search](https://github.com/issues?q=+is%3Aissue+repo%3Apressbooks%2Fpressbooks) to see if your bug or enhancement is already listed?

### Description

User actions that impact compiled stylesheets should be reflected in custom styles editor.

### Steps to Reproduce

1. Update language support options (e.g. add support for Biblical Hebrew or something) or change a theme option.
2. Navigate to custom styles editor.

**Expected behavior:** Changes are reflected in 'Theme Styles' viewer.

**Actual behavior:** Changes are not reflected.

### System Information

Pressbooks: 4.3-dev
WordPress: 4.8.1
PHP: 7.1

**Comment by connerbw** [comment]
Cannot reproduce. 

Holding on to this ticket until the other stuff is deployed to avoid confusion.

**Comment by greatislander** [comment]
Closing, can re-open if needed.
