### ISSUE TITLE
Automatic running numbering for figures/tables/other HTML elements

### ISSUE THREAD

**Issue by SteelWagstaff** [pressbooks/pressbooks#960]
### Description

**Feature idea:** I just stumbled across a [very clever, very clean way to provide automatic numbering for figures/tables/HTML elements](https://tympanus.net/codrops/2013/05/02/automatic-figure-numbering-with-css-counters/3). I think this might be especially valuable for textbooks and other kinds of standardized publications, where having numbered ‘figures’ or ‘tables’ might be desirable. We'd be interested in seeing CSS counters used with more HTML elements, and/or figuring out a way for this to degrade gracefully into other export formats. See also our discussion on [the PB forum on this topic](https://discourse.pressbooks.org/t/theme-support-for-automatic-numbering-of-tables-figures/238).

**Comment by greatislander** [comment]
Hi @SteelWagstaff, this is functionality is on our roadmap, (see [Editing and Content](https://pressbooks.org/roadmap/)) but the implementation is a question mark for me. The problem is that to my knowledge no EPUB readers fully/properly support CSS counters so a different solution that works on all formats may be more desirable. We _do_ use CSS counters for PDF running heads and feet already.

**Comment by thomasdumm** [comment]
I think the two CSS properties "counter-reset" and "counter-increment" work in most EPUB3 readers. The problem that I had in getting the numbering right the EPUB3, was to get the numbering to increment accross the all chapters. Most importantly for chapter numbering (e.g. chapter 4.5.1...)
  
For the PDF this is done with 
With CSS this would be done with the "string-set" property that copies text content to a named variable that then can be used for the couter-reset:

.chapter-number{
string-set: chapter-number content();

"string-set" does not even work in browsers ...
I solution that might work is to have an inline CSS style in the export that is used for WEB book and EPUB3 eBook with a counter-reset inline style containing on the chapter title tag:

Below a demo for what I mean. No idea if it is useful...

`

    <head>
        <title>Counter Demo</title>
        <style>
            h1{
                counter-reset: num2;
            }
            
            h2{
                counter-increment: num2;
            
            }
            h1:before{
                content: counter(num1) " ";
                color: red;
            }
            h2:before{
                content: counter(num1) "." counter(num2) " ";
                color: red;
            }</style>

    </head>
    <body>
        <h1 style="counter-increment: num1 5">Title Level 1 in the 5th chapter of the book</h1>
        <p>Text....</p>
        <h2>Title Level 2 in the 5th chapter of the book</h2>
        <p>Text....</p>
    </body>



`

**Comment by hughmcguire** [comment]
NOTE: `:before` and `:after` are not always supported by bad epub readers (mostly anything using the Adobe epub reading engine). At least they weren't last time I looked.

Should we support crappy epub readers that can't support basic CSS2 in 2017? I'd argue not.

**Comment by thomasdumm** [comment]
With the edu focus I would also ignorw limmitations of old walled epub readers.

**Comment by hughmcguire** [comment]
we'll need to discuss in some more detail -- as PB evolves we need a clear policy for: 
-- old EPUB readers
-- old Kindle formats
