### ISSUE TITLE
Custom import option not giving file upload option

### ISSUE THREAD

**Issue by monkecheese** [pressbooks/pressbooks#964]
### Prerequisites

_Check the boxes below by changing them from `[ ]` to `[x]`._

* [x] Can you reproduce the behavior you wish to address with [all other plugins deactivated](http://codex.wordpress.org/Multisite_Network_Administration#Plugins)?
* [x] Are you running the [latest version of Pressbooks](http://github.com/pressbooks/pressbooks/releases/latest/) and the [latest version of WordPress](http://codex.wordpress.org/Upgrading_WordPress)?
* [x] Are you experiencing this issue with one of our built-in root or book themes?
* [x] Did you [perform a cursory search](https://github.com/issues?q=+is%3Aissue+repo%3Apressbooks%2Fpressbooks) to see if your bug or enhancement is already listed?

### Description

In the Import area, we have a custom import method we use.  When we select it in the list of import options, we are supplied a field that wants a url.  Before, we had an option to upload a file from our computer.

### Steps to Reproduce

1. Navigate to Admin > Tools > Import
2. Select a custom option from the drop down
3. The next field is not a file upload field as we expect for our custom import stuff to work

**Expected behavior:** We expect a file upload option

**Actual behavior:** We are given an input field that wants `https://file-to-import.com`

### System Information

Pressbooks: 4.3.3
WordPress: 4.8.2
PHP: 7.0

**Comment by monkecheese** [comment]
The problem is in this bit of javascript that show/hides the options based on what import type is selected:

```
// approximately line 140 in import.php

<script type="text/javascript">
	jQuery(function ($) {
		$('#pb-www').hide();

		$(".pb-html-target").change(
			function () {
				var val = $('.pb-html-target').val();

				if (val == 'wxr' || val == 'epub' || val == 'odt' || val == 'docx') {
					$('#pb-file').show();
					$('#pb-www').hide();
					// clear http value at input elem
					$('.widefat').val('');
				} else {
					$('#pb-file').hide();
					$('#pb-www').show();

				}

			});

	});
</script>
```

I can think of a hacky way of the top of my head to solve this, but I'd rather formulate a clean solution.  Any thoughts?

**Comment by bdolor** [comment]
with this filter you can modify the contents of the default table cell - perhaps that will work? 

https://github.com/pressbooks/pressbooks/blob/dev/templates/admin/import.php#L195

**Comment by monkecheese** [comment]
@bdolor, heh...sort of?  It adds the field to the same row in the table.

This is the code I'm using on my end to hook into that filter:

```
function add_file_upload_field() {
	return '<td id="pb-other"><input type="file" name="import_file" id="import_file"></td>';
}
add_filter( 'pb_import_table_cell', '\Candela\Utility\Import\add_file_upload_field' );
```
<img width="1091" alt="screen shot 2017-10-06 at 4 17 30 pm" src="https://user-images.githubusercontent.com/10492228/31301837-e450a846-aab1-11e7-8d17-ba30ba21a2ed.png">

**Comment by monkecheese** [comment]
Here's a potential fix.  We could add a third id `pb-other`, hide it by default, and if `val` is something other than the formats you have baked in, hide the `pb-www` and `pb-file`, and show `pb-other`.

```
<!-- Start by uploading a file -->

<script type="text/javascript">
	jQuery(function ($) {
		$('#pb-www').hide();
		$('#pb-other').hide();

		$(".pb-html-target").change(
			function () {
				var val = $('.pb-html-target').val();

				if (val == 'wxr' || val == 'epub' || val == 'odt' || val == 'docx') {
					$('#pb-file').show();
					$('#pb-www').hide();
					// clear http value at input elem
					$('.widefat').val('');
				} else if (val == 'html') {
					$('#pb-file').hide();
					$('#pb-www').show();
				} else {
					$('#pb-other').show();
					$('#pb-file').hide();
					$('#pb-www').hide();
				}

			});

	});
</script>
```

Would this work for you guys?

**Comment by monkecheese** [comment]
PR submitted: 967

**Comment by bdolor** [comment]
you could use that hook to pass back javascript instead of html 
```	
function add_file_upload_field_imscc() {
	$js = '
		<script type="text/javascript">
			jQuery(function ($) {
				$(".pb-html-target").change(
					function () {
						var val = $(".pb-html-target").val();
						if (val == "imscc") {
							$("#pb-file").show();
							$("#pb-www").hide();
						}
					});
			});
		</script>';

	return $js;
}

add_filter( 'pb_import_table_cell', 'add_file_upload_field_imscc' );
```

**Comment by monkecheese** [comment]
@bdolor, this is great!  I had started down that path, but couldn't quite get it to work right.  Your suggestion however, works.  I think I'll close the issue and pull request and use this solution, since it's simplest and doesn't require a change in the PB codebase.  Thank you for the help!

**Comment by greatislander** [comment]
Thanks @bdolor and @monkecheese!
