### ISSUE TITLE
the publication date in the book info is not saved

### ISSUE THREAD

**Issue by thomasdumm** [pressbooks/pressbooks#965]
### Prerequisites

_Check the boxes below by changing them from `[ ]` to `[x]`._

* [x] Can you reproduce the behavior you wish to address with [all other plugins deactivated](http://codex.wordpress.org/Multisite_Network_Administration#Plugins)?
* [x] Are you running the [latest version of Pressbooks](http://github.com/pressbooks/pressbooks/releases/latest/) and the [latest version of WordPress](http://codex.wordpress.org/Upgrading_WordPress)?
* [x] Are you experiencing this issue with one of our built-in root or book themes?
* [x] Did you [perform a cursory search](https://github.com/issues?q=+is%3Aissue+repo%3Apressbooks%2Fpressbooks) to see if your bug or enhancement is already listed?

### Description

I set the publication date in the book info. After saving the book info the publication date is empty again.

#### Book Info

Book ID: 38
Book URL: https://delivros.pressbooks.pub/pwlo00117r2/
Book Privacy: Public

#### Browser

Platform: OS X
Browser Name: Firefox
Browser Version: 55.0
User Agent String: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:55.0) Gecko/20100101 Firefox/55.0

#### WordPress Configuration

Network URL: http://delivros.pressbooks.pub/
Network Type: Subdirectory
Version: 4.8.2
Language: en_US
WP_ENV: production
WP_DEBUG: Disabled
Memory Limit: 64M

#### Pressbooks Configuration

Version: 4.3.3
Book Theme: Clarke
Book Theme Version: 2.0.1
Root Theme: Pressbooks Publisher
Root Theme Version: 3.1.3

#### Pressbooks Dependencies

Epubcheck: Installed
Kindlegen: Installed
xmllint: Installed
PrinceXML: Not Installed
Saxon-HE: Installed

#### Must-Use Plugins

Bedrock Autoloader: 1.0.0
hm-autoloader.php: n/a
telemetry.php: n/a

#### Network Active Plugins

Docraptor for Pressbooks: 2.1.0
Pressbooks: 4.3.3
Pressbooks Cover Generator: 2.2.1
Pressbooks Stats: 1.4.0
Pressbooks Whitelabel: 1.0.2
User Activation Keys: 4.6

#### Inactive Plugins

Akismet Anti-Spam: 3.3.4
Pressbooks BISAC: 2.0.0
Pressbooks Table Classes: 1.0.0

#### Server Configuration

PHP Version: 7.1.4-1+deb.sury.org~xenial+1
MySQL Version: 5.5.5
Webserver Info: nginx/1.11.9

#### PHP Configuration

Safe Mode: Disabled
Memory Limit: 256M
Upload Max Size: 25M
Post Max Size: 25M
Upload Max Filesize: 25M
Time Limit: 120
Max Input Vars: 1000
URL-aware fopen: On (1)
Display Errors: N/A

#### PHP Extensions

OPcache: Zend
XDebug: Disabled
cURL: Supported
cURL Version: 7.47.0
imagick: Not Installed
xsl: Installed

**Comment by connerbw** [comment]
I was able to reproduce if the UI wasn't English.
