### ISSUE TITLE
Can't save network level Sharing & Privacy options

### ISSUE THREAD

**Issue by SteelWagstaff** [pressbooks/pressbooks#976]
The ability to download exports from our book’s home pages has suddenly disappeared across our network & the option to display them is now missing from the ‘sharing & privacy settings’ page for our books. 

When I go to look at the network-level sharing & privacy permissions `https://OURNETWORK.ORG/wp-admin/network/settings.php?page=pressbooks_sharingandprivacy_options`, they appear to have been reset. 
![screen shot 2017-10-30 at 9 05 23 pm](https://user-images.githubusercontent.com/13485451/32204435-2af3e318-bdb7-11e7-9e3f-30192ba3e125.png)
When I try to restore them as they were (all boxes checked) and save changes, I get a notification that my changes were saved, but when I reload the page, the first two options instantly revert to unchecked boxes. Anyone else having this problem? @bdolor -- I notice that download options appear to have disappeared from some books on your BC Campus network as well, like: https://opentextbc.ca/opentextbook/

**Comment by SteelWagstaff** [comment]
@connerbw I’m seeing some changes you made to the network sharing & privacy settings options in June and August: https://github.com/pressbooks/pressbooks/commits/f02f7f2b5e5696e40ded8f3192afba5bc1005160/inc/admin/network/class-sharingandprivacyoptions.php. Not skilled enough to parse them and understand the implications of all your changes, but is it possible that something in these changes might be causing our issue?

**Comment by monkecheese** [comment]
I was just perusing this @SteelWagstaff, and though I haven't tested anything, it looks like the culprit(s) _might_ be lines [229 and 232](https://github.com/pressbooks/pressbooks/commit/234df125e6382e6396e6c6d2933c6c9aaafd03c1#diff-a92fab10fac096f663559e4bb55a38bfL229) of `inc/admin/laf/namespace.php`, where the optional `false` argument was removed (the `get_site_option` function defaults to `true` on the optional argument, where before it was explicitly set to false, which decides whether to use cache or not).  I could be totally off base because I'm just perusing, but that leaped out at me and thought I might be helpful to share.

https://codex.wordpress.org/Function_Reference/get_site_option

**Comment by connerbw** [comment]
I'll look.

@monkecheese The docs are wrong. The actual function signature for get_site_option is 

```php
function get_site_option( $option, $default = false, $deprecated = true ) {
	return get_network_option( null, $option, $default );
}
```
( [Source ](https://github.com/WordPress/WordPress/blob/master/wp-includes/option.php#L1108))

The change you are talking about removes the third param which is deprecated, never used.

**Comment by greatislander** [comment]
@monkecheese Yeah, looks like it's up to date on the new code reference but not on the codex:

https://developer.wordpress.org/reference/functions/get_site_option/

**Comment by greatislander** [comment]
Hi @bdolor @SteelWagstaff @monkecheese,

The issue is in Pressbooks Textbook 3.1.5.

https://github.com/BCcampus/pressbooks-textbook/blob/3083f2634fa8f3983cd5cae22894ccfae0dbb165/inc/class-textbook.php#L426-L430

Specifically, this block runs on every load of Pressbooks Textbook, and tries to force all the sharing and privacy options to true, but fails because each line in the block wipes out the key set in the previous line. It should be:

```
if ( version_compare( '3.1.5', self::VERSION ) == 0 ) {
  update_site_option( 'pressbooks_sharingandprivacy_options', array(
    'allow_redistribution' => 1,
    'enable_network_api' => 1,
    'enable_cloning' => 1
  ) );
}
```

**Comment by pelaprat** [comment]
What could a value for `pressbooks_sharingandprivacy_options` be if "Allow Redistribution" was enabled by a user? Here's the value we have right now in our test PB deployment, which is running the latest and where we see the problem described in this issue:

```
+--------------------------------------+------------------------------------+
| option_name                          | option_value                       |
+--------------------------------------+------------------------------------+
| pressbooks_sharingandprivacy_options | a:1:{s:16:"disable_comments";i:1;} |
+--------------------------------------+------------------------------------+
```

The the `option_value` data doesn't change when I change the settings in the UI. Also, changing the data itself in mysql doesn't seem to affect the UI. 

But perhaps I am looking at the right `option_name` for this setting.

**Comment by greatislander** [comment]
@pelaprat This is a bug in Pressbooks Textbook.

**Comment by pelaprat** [comment]
Ok, thanks @greatislander .

**Comment by pelaprat** [comment]
Is the right next action to file an issue in Pressbooks Textbook?

**Comment by greatislander** [comment]
I'm submitting a pull request.

**Comment by pelaprat** [comment]
Great, thanks again!

**Comment by greatislander** [comment]
Gentle reminder @SteelWagstaff et al… if you cannot reproduce the issue with all plugins other than Pressbooks disabled, it is an issue with something other than Pressbooks. That's what the issue template is for. If you had tried to disable Pressbooks Textbook and test you would have noticed that! :simple_smile:

**Comment by SteelWagstaff** [comment]
Thanks @greatislander and noted. I'll more thorough (and circumspect) in filing future issues.

**Comment by connerbw** [comment]
@pelaprat 

For curiosity:

1) This is a network wide config, not a blog specific config, look in `wp_sitemeta`

2) Looks like:

```
186 | 1 | pressbooks_sharingandprivacy_options | a:3:{s:20:"allow_redistribution";i:1;s:18:"enable_network_api";i:1;s:14:"enable_cloning";i:1;}
```

It's a [serialized ](http://php.net/manual/en/function.serialize.php)array with 3 (or less) keys in it.

Good times.
